### ISSUE TITLE
AEM ACS Commons - Component Design Paradigm Idea

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#10]
### Problem

Re-usable AEM Component rarely contain the markup or sum of features required for various customer use cases. This results in a copy-down overlay approach of the original JSP. This causes grief when upgrading source materials as enhancements are not recognized without re-integration.

This problem is very common when using the Foundation AEM Components.
### Idea

(Re-usable) ACS AEM Components will:
- Contain minimal, semantic markup. An example is the audio component; it only outputs `<audio>` tag)
- Re-usable components will contain all the "working" jsps in an "partials" folder (naming TBD). The Working JSPs will be responsible for rendering a specific facet of the Component; in this case the `<audio ...>...</audio>` tag

```
/apps/acs-commons/components/content/audio/partials/audio.jsp
```
- The default script `/apps/acs-commons/components/content/audio/audio.jsp` will simply include the partials:

```
<cq:include script="partials/audio.jsp"/>
```

For a developer to augment the component markup, they simply have to superResourceType (i guess it would be sub-ResourceType) the ACS AEM Commons audio component and selectively include whatever partials they want intermixed with whatever markup or other facets they need (as long as the superType is set)

```
/apps/myapp/components/content/audio/audio.jsp
```

```
<div class="myclass-for-audio">
  <cq:include script="partials/audio.jsp"/>
  <p><%= properties.get('instructions', "Press play") %></p>
</div>
```
### Concerns
- What level of granularity are the partials broken out; by logical facet of Component?
  - Ex. If Audio had the audio player AND instructions, should there only be one `partials/audio.jsp` with both facets, or one for each facet; `partials/audio.jsp` (audio tag) and `partials/instructions.jsp` (print instruction text).
  - Which scripts are responsible for which drop-targets/placeholders? 
  - Will this cause (serious) code duplication across partials?
- Generally too confusing and a departure from normal process.

**Comment by badvision** [comment]
IMHO, Core Components might be along the same lines.  Does ACS Commons need to focus on that, or would it be more productive to have an ACS fork of core components and direct our efforts there?

**Comment by davidjgonzalez** [comment]
Closing as the new HTL + Sling Model abstraction supersedes. Some good ideas, but closing as to not confuse.
