### ISSUE TITLE
ACL Packager

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#100]
Migrating custom permissions (ACLs) can be a cumbersome. The ACL Packager helps in this activity by created automatic package definitions for all rep:policy nodes which contain at least 1 ACE for a targeted principal (or if not targeted principals, then all rep:policy nodes). Optionally exclude patterns can be defined.

I am building this for easy extension to allow other package defs to be built off queries (xpath, sql2, etc.) and a more robust regex handler (filter set include/excludes regex capabilities seem to be hamstrung).

![workflow_and_crx_package_manager_-__etc_packages_acls_workflow-users-3_0_0_zip-9](https://f.cloud.github.com/assets/1451868/1911648/5292e5da-7d2f-11e3-9cd5-aee075947fc6.png)

WDYT?

**Comment by gshrutig** [comment]
we have a requirement where for the  backup purpose we need all users and group associated with a Principal name (which will be a group name in my case) should be the part of the package. Currently as i understand if we add Group name only permission associated with that group comes. We need something where users associated with the Group along with their permission becomes part of ACL package. 

Is it possible to have this feature?
Can we build and deploy changes in local setup and test?
