### ISSUE TITLE
Workflow Remover should use smaller transactions

### ISSUE THREAD

**Issue by thomasmueller** [Adobe-Consulting-Services/acs-aem-commons#1002]
Currently, the workflow remover uses one (possibly very large) transaction. This is a problem for example for indexing. The transaction should be split into many small ones (about 1000 changes per commit).

Also, after each commit, there should be a pause, so that other operations have a chance to run. This pause might be configurable.

**Comment by davidjgonzalez** [comment]
Looking at the code it seems this is exactly what it does. Is there a reason you think it isn't?

There is not a pause that could be added; suggestion on a pause multiplier (i.e. Batch size of 1000 gets N ms)

I'll do a rest run when I get in front if a computer.

**Comment by thomasmueller** [comment]
Hm, that's great then! Somebody told me that it is using one transaction... Maybe in an older version?

**Comment by davidjgonzalez** [comment]
Highly doubtful (without checking git history) -- I  always batch potentially large commits on principle.

**Comment by thomasmueller** [comment]
OK then let's close the issue.

**Comment by badvision** [comment]
Food for thought: If you wanted to refresh this tool using FAM then ActionBatch can be used to limit changes per transaction and also adds retry support.
