### ISSUE TITLE
Throttled Task Runner Factory

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1003]
It would be nice to define sets of Throttle Task Runner configurations each with their own thresholds (cpu, heap, cooldown) to allow other functionality to auto-throttle their execution based on the urgency and importance of the work. I.e.. background imports could be set to a lower priority, while blocking behavior could be set to a higher priority.

Currently there is only a single Throttled Task Runner.

1) Im not sure if the throttle behavior should be decoupled from the runner capability (probably via a more limited interface)
2) If not, how should the current config be handled; ideally we'd want to have it set as the default, but what if someone has provided their own already; do we try to intelligently keep that and mark it as the default?

Or is this not a good idea since if the thresholds are set too low, the thread could just sit there forever waiting (and/or we'd have to define failure criteria/behavior)

This would be a 3.x.x only feature.

**Comment by badvision** [comment]
#1526 kind of provides this by way of priority support.  It's still a single queue but priority can move things up in the queue more conveniently.
