### ISSUE TITLE
Feature request: Named Transform Image Servlet preserves PNG palette

### ISSUE THREAD

**Issue by tb29491kfo** [Adobe-Consulting-Services/acs-aem-commons#1004]
If I do a slight scaledown on a .png image with an optimized color palette in it, the Named Transform Image Servlet does not preserve the palette but just creates a new one. I have a (classified) example with 140 colors and 585 kilobytes in the original image. The scaled-down image has 19669 colors and 2000 kilobytes. I am scaling down the image because of bandwith saving, especially mobile devices, so I would like to get smaller .png images. Gimp, for example, preserves the original palette (it is even using only 133 colors in the scaled output image), and at highest compression rate, uses only 575 kilobytes.

**Comment by manisha199010** [comment]
@tb29491kfo As per given information, you are scaling down an image of 140 colors and 585 kilobytes size to 19669 colors and 2000 kilobytes, which seems like the image has been scaled up. 

Could you please confirm I'm on the same track or there is something wrong or missing in the information provided by you?

**Comment by tb29491kfo** [comment]
Hi Manisha,

the source image is being scaled down. But the source image has an indexed color model with 140 colors. When scaling it down, there are additional colors being generated - I think this is because of antialiasing (when scaling down, multiple pixel's color values are used for calculating the color value of each result pixel). So, the number of colors raises to 19669 colors, and this is the reason why the resulting image cannot be compressed as strong as the source image. Of course, sticking to the color palette of the source image will be a loss of accuracy, but it will also consume much less space (and bandwith, when the images are delivered via the web).

**Comment by davidjgonzalez** [comment]
@tb29491kfo have you tried outputting the resizes image as JPG or PNG? Something that handles many colors more efficiently? Or would that overly degrade the image quality? Unfortunately the image APIs were using are what they are. if you have clever tricks to get around it were all ears.

**Comment by tb29491kfo** [comment]
I needed PNG because of the alpha channel (which is not provided by the JPG format).
I made some small tests on my own to get around the described problem.
The Java API is capable of producing a PNG image with indexed palette:

`					colorModel = bufferedImage.getColorModel();
...

			if (isPNG && null != colorModel && colorModel instanceof IndexColorModel) {
				// PNG with palette
				final IndexColorModel indexColorModel = (IndexColorModel) colorModel;
				final BufferedImage layerImage = layer.getImage();
				BufferedImage imageToWrite = layerImage;
				if (indexColorModel.hasAlpha()) {
					BufferedImage indexedImage = new BufferedImage(layerImage.getWidth(), layerImage.getHeight(), BufferedImage.TYPE_BYTE_INDEXED,
							indexColorModel);
					final WritableRaster raster = indexedImage.getRaster();
					indexedImage = new BufferedImage(colorModel, raster, layerImage.isAlphaPremultiplied(), null);
					copyImage(layerImage, indexedImage, indexColorModel);
					// indexedImage.getGraphics().drawImage(layerImage, 0, 0, null);
					imageToWrite = indexedImage;
				}
				ImageIO.write(imageToWrite, "png", response.getOutputStream());
			} else {
				layer.write(mimeType, quality, response.getOutputStream());
			}

`

However, in my test, it had problems with rendering a BufferedImage into that image with indexed palette, and I had to write Java code which decides pixel-by-pixel which index value to use, by running through the palette and select the indexed value with the smallest quadratic difference compared to the source image:

`	private void copyImage(final BufferedImage srcImage, final BufferedImage indexedImage, final IndexColorModel indexColorModel) {

		final int scanSize = srcImage.getWidth();
		final int[] rgbArray = new int[scanSize];
		final int[] sampleArray = new int[scanSize];
		final int mapSize = indexColorModel.getMapSize();
		final int[] rgbs = new int[mapSize];
		indexColorModel.getRGBs(rgbs);
		final WritableRaster indexedRaster = indexedImage.getRaster();
		for (int y = 0; y < srcImage.getHeight(); y++) {
			srcImage.getRGB(0, y, scanSize, 1, rgbArray, 0, scanSize);
			for (int x = 0; x < scanSize; x++) {
				final int pixel = rgbArray[x];
				final int alpha = (pixel >> 24) & 255;
				final int red = (pixel >> 16) & 255;
				final int green = (pixel >> 8) & 255;
				final int blue = (pixel) & 255;
				final int index = bestMatch(red, green, blue, alpha, indexColorModel, rgbs);
				sampleArray[x] = index;
			}
			indexedRaster.setSamples(0, y, scanSize, 1, 0, sampleArray);
		}
	}


	private int bestMatch(final int red, final int green, final int blue, final int alpha, final IndexColorModel indexColorModel, final int[] rgbs) {
		int bestMatched = -1;
		int matchDifference = Integer.MAX_VALUE;
		for (int i = 0; i < rgbs.length; i++) {
			final int indexPixel = rgbs[i];
			final int indexAlpha = (indexPixel >> 24) & 255;
			final int indexRed = (indexPixel >> 16) & 255;
			final int indexGreen = (indexPixel >> 8) & 255;
			final int indexBlue = (indexPixel) & 255;
			final int difference = (sqr(indexRed - red) + sqr(indexGreen - green) + sqr(indexBlue - blue) + sqr(indexAlpha - alpha));
			if (difference < matchDifference) {
				matchDifference = difference;
				bestMatched = i;
			}
		}
		return bestMatched;
	}

	int sqr(final int value) {
		return value * value;
	}

`

Anyway, in my project there will be other solutions used for creating optimized images now.

**Comment by davidjgonzalez** [comment]
@tb29491kfo thanks for the code; im going to close this for now since it seems you have a work around. If this gets raised again we can take a look to see if we can leverage this code.
