### ISSUE TITLE
RTE New Plugin is not appearing for AEM 6.3

### ISSUE THREAD

**Issue by singhd12** [Adobe-Consulting-Services/acs-aem-commons#1007]
I am trying to test this plugin with AEM 6.3 but seems like its not working for me. I am not able to see plugin for both inline and fullscreen.

Steps i am following

1) Install ACS 3.9.0 - https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases/tag/acs-aem-commons-3.9.0

2) Overlay One of RTE components - /apps/mcm/campaign/components/personalization

Overlayed Package : 
[RTE_Personalization_Text.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1013249/RTE_Personalization_Text.zip)

Content where i am using overlaid Personalisation Text Component

[Page_Content.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1013260/Page_Content.zip)

3) Follow Instruction provided under step section -
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/rte-plugins/source/dialog-plugin.js

Please let if this is compatible with AE 6.3

Devesh Singh

**Comment by davidjgonzalez** [comment]
@schoudry any ideas?

**Comment by schoudry** [comment]
@davidjgonzalez no, havent tried 63 yet

**Comment by Akuyi** [comment]
In 6.3 are two versions of RTE. The 6.2 variant "rte.coralui2" and the new one for 6.3 "rte.coralui3".
When I change the categories property under /apps/acs-commons/rte-plugins to "rte.coralui3" the icon for the custom dialog is shown in RTE.
But when I click the icon a javascript error occurs instead of opening the custom dialog.

![image](https://user-images.githubusercontent.com/26923038/28916709-70b811f8-7843-11e7-8b6c-27629c6741e3.png)

**Comment by AndreiShilov** [comment]
Seems that problem is here

```javascript
        var dialogContent;
        if (Coral.templates.RichTextEditor['dlg_' + dataType]) {
          dialogContent = Coral.templates.RichTextEditor['dlg_' + dataType].call(this._elements, config);
        } else if (CUI.rte.templates['dlg-' + dataType]) {
          dialogContent = $(CUI.rte.Templates['dlg-' + dataType](config))[0];
        }
        this.$dialog[0].childNodes[0].content.appendChild(this.content? this.content: dialogContent);
```
They check if a template available here 'CUI.rte.templates['dlg-' + dataType]' , but
for real template stores here 'CUI.rte.Templates['dlg-' + dataType](config))[0]'

**Comment by shamrox** [comment]
I know this is stale, but has anyone found a fix?

**Comment by AndreiShilov** [comment]
@shamrox 

We fixed it with custom assign of empty object

```
  CUI.rte.Templates = CUI.rte.templates || {};

    CUI.rte.Templates['dlg-selectkeys'] =
```
