### ISSUE TITLE
Icon picker is not showing the selected Icon in the dialog

### ISSUE THREAD

**Issue by pokkunuri** [Adobe-Consulting-Services/acs-aem-commons#1009]
**Issue:**
I am testing the Icon Picker in Touch UI dialog and found out that the selected Icon is not displayed Properly. 
<img width="329" alt="screen shot 2017-05-23 at 7 06 21 pm" src="https://cloud.githubusercontent.com/assets/18440476/26357013/9f32b65e-3feb-11e7-8f41-b195b514ea99.png">

Its shows a square box for all the Icons.

**Root Cause Analysis**
There is a vendor javascript file named - jquery.fonticonpicker.js has been used and this is out of date. The latest version of this file is available @ https://github.com/micc83/fontIconPicker/blob/master/jquery.fonticonpicker.js

**Solution**
This vendor JS file can be replaced and updated in ACS commons to avoid any further issues.

**Next Steps**
Please let me know if you consider it as valid issue, I will create a branch and update the same.

**Comment by erved** [comment]
AEM 6.3L15 Content Fragment editor UI breaks due to the inclusion of: /apps/acs-commons/touchui-widgets/source/icon-picker.js

$('[data-init~=graphiciconselect] > select') is undefined.

$(document).on('cui-contentloaded.data-api', function (e) {
    $('[data-init~=graphiciconselect] > select').fontIconPicker({
        'theme' : 'fip-coral'
    }); 
});

**Comment by davidjgonzalez** [comment]
@erved thats L15 (very old pre-release) -- i thought that got fixed?  Is it still an issue?

**Comment by davidjgonzalez** [comment]
@pokkunuri whoa; any idea why a new version of that JS fixed the issue? is this a AEM 6.3 only issue? Seems reasonable to upgrade to the latest assuming it doesnt break anything for AEM 6.2.

**Comment by pokkunuri** [comment]
@davidjgonzalez  - Apologises for the delayed response. I have tested with the third party library and seems working. Hence, I proposed this to fix at acs-commons level. I guess this should be the problem with AEM 6.2 as well and not specific to touch UI. I mentioned in the ticket as Touch UI as I am only using the touch UI dialog.

**Comment by tfs** [comment]
Update - we just encountered this issue on a 6.4.8 instance. This results in the picker not working for selecting XF variations. If I understand everything correct the file jquery.fonticonpicker.js is missing currently?

**Comment by davidjgonzalez** [comment]
@tfs are you attaching these clientlib categories to the correct AEM-product clientlib category via a proxy category so they can get loaded in the XF Editor?

**Comment by tfs** [comment]
Update - we just encountered this issue on a 6.4.8 instance. This results in the picker not working for selecting XF variations. If I understand everything correct the file jquery.fonticonpicker.js is missing currently?

> @tfs are you attaching these clientlib categories to the correct AEM-product clientlib category via a proxy category so they can get loaded in the XF Editor? Was this working "as is" for you before upgrading to 6.4.8 and then that SP broke the inclusion? If so, that would be a regression in AEM itself.

I was informed of the issue and tested it only after 6.4.8 has been added. So the answer is "I don't know, yet" - will setup a earlier version and retest.

**Comment by tfs** [comment]
As additional info: I was quite suprised to see this behavior - because this is a ACS Commons feature beeing called by an OOTB AEM functionality. I am not aware of any configuration on our side which could be the culprit here, but further debugging seems necessary.
