### ISSUE TITLE
Multifield is not working for the AEM 6.3 Coral UI 3-based Dialog fields

### ISSUE THREAD

**Issue by acheson0410** [Adobe-Consulting-Services/acs-aem-commons#1013]
Hi,

The html markup & classes of Coral UI 3-based dialog fields have been updated in AEM 6.3. Therefore the ACS Touch UI Multi Field might not work as it will not able to find the field to set widget value.

Can we please have another version of ACS.TouchUI.NodeCompositeMultiField, ACS.TouchUI.CompositeMultiField & ACS.TouchUI.Widget, so it is compatible with the Coral UI 3-based dialog fields?

Thanks,
Johnny Yang

**Comment by mzgubin** [comment]
Could this issue be re-opened? We have been working on upgrading to AEM 6.4 and Adobe is recommending to change to Coral 3 but we cannot because we use this Multi-field component.

**Comment by davidjgonzalez** [comment]
@mzgubin This widget has caused us a great deal of pain over the years (many bugs/issues/time) - it would be most prudent to move to the Adobe supported multi-field [1] given that you are in the midst of a large upgrade project already (from the sounds of it) - Generally, we also don't want to encourage or grow its use. 

Is it not possible/the cost very high to move over to the GraniteUI version? How come? (dialog configs or content serialization? Thinking if we could create a util or something to transform)?

If we were to re-open this, would you be planning on updating and supporting it moving forward? (Im not sure there is alot of appetite out there to do this work).

I don't mean to be rude ;) -- but this particular feature has been a thorn; i've never tallied up, but i expect it tops the "reported bugs" in the issues.

[1] https://helpx.adobe.com/experience-manager/6-3/sites/developing/using/reference-materials/granite-ui/api/jcr_root/libs/granite/ui/components/coral/foundation/form/multifield/index.html

**Comment by Ronald-Diemicke** [comment]
@davidjgonzalez - It seems like this would be the perfect opportunity for someone to create a 'one-time' run script to convert the ACS commons multifield into the granite multifield.

**Comment by davidjgonzalez** [comment]
.. and to be clear this would be a script that changes the CONTENT structures (across author and pubs somehow), and the dialog nodes would have to be changed by developers, and deployed.

There is the concern (which I don’t think we can automate) in updating consuming code to match new structures - esp if you were using JSON before, and now moves to composite nodes.

**Comment by felipeabellan** [comment]
Still struggling with this in 2019. Coral 3 multifield work with coral-template which doesnt seem to be accessible to the 'selectors in JS. Another difference is that when nested multifield.js is fired, Coral 2 has already all the necessary structure (i.e the correct number of items added beforehand). Coral 3 not so much.

**Comment by davidjgonzalez** [comment]
@felipeabellan are you commenting on the OOTB AEM Multifields, or on the ACS COmmons multifield? 
Ideally, you aren't using the ACS Commons multfield, but instead the OOTB multfields, and logging any potential issues you find w/ the OOTB one w/ Adobe support.

**Comment by felipeabellan** [comment]
ACS Commons Mulifield looking to migrate to OOB coral 3 multifield. So really not an issue with Adobe's. I'm using json store because project comes from way back EXTJS multifield would save composite fields as json, so ACS commons was a good bandaid for a while, until coral3 migration came along. So what I'm looking for is a possible migration JS from ACS commons coral 2 JSON store to OOB multifield coral 3.
