### ISSUE TITLE
Classic UI  multifield does not save values on reloading/editing in dialog but is stored in CRX as JSON

### ISSUE THREAD

**Issue by vishwas6** [Adobe-Consulting-Services/acs-aem-commons#1018]
Classic UI multifield does not save values on reloading/editing in dialog but is stored in CRX as JSON.

We are in AEM 6.2 and ACS Commons version is 3.3, Please help us with the fix. This was working fine when we have this in AEM 6.0

**Comment by davidjgonzalez** [comment]
@Sandeep18051990 any chance you could package up the component that is having this problem?

**Comment by Sandeep18051990** [comment]
@davidjgonzalez  thanks for the reply.

Attached is the dialog where we have issues
[dialog.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1065777/dialog.zip)

**Comment by Sandeep18051990** [comment]
@davidjgonzalez  Below is the issue in brief
|- MultiField (ootb multifield )
   |-fieldConfig - xtype : multifieldpanel
      |- field A (xtype:textfield example textfield)
      |- field B (xtype:pathfield example pathfield)
      |- field C (xtype:tags example tags field)
  
Where tag field is not a mandatory field but when a tagfield doesn't contain any values/no values selected all the pre entered values below that multifield set are getting disappeared from the dialog.
On Save it's saving in CRX after reloading Dialog for edit field A2,field B2 and field C2 are disappearing from dialog.

Thanks for any suggestions to overcome this issue.

**Comment by davidjgonzalez** [comment]
@Sandeep18051990 i tried your dialog on AEM 6.2 and AEM 6.3 instances w ACS Commons 3.9.0 and it works fine.. see attached. Have you tried checking your dialog on a a vanilla instance without your code installed to make sure you dont have something that is causing issues (tbh, doesnt sound likely but it works fine for me on a vanilla...)

[1018-aem62-acscommone3.9.0.mp4.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1066180/1018-aem62-acscommone3.9.0.mp4.zip)

[1018-aem63-acscommons3.9.0.mp4.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1066179/1018-aem63-acscommons3.9.0.mp4.zip)

**Comment by Sandeep18051990** [comment]
@davidjgonzalez  This seems strange but It's not working for me on AEM 6.2 vanilla instance with ACS Commons 3.9.0 
Below is the url and attached is the packaged I used to verify in vanilla instance.
🔢 https://youtu.be/MagRFeeVj_A

**Comment by Sandeep18051990** [comment]
[header-1.0.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1066392/header-1.0.zip)

**Comment by Sandeep18051990** [comment]
[header-1.0.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1066392/header-1.0.zip)

**Comment by Sandeep18051990** [comment]
I'm using windows 10 and Chrome browser to test this

**Comment by Sandeep18051990** [comment]
It will be great help if you provide the package of component you created and the test page from AEM 6.2,I'll cross verify on my end.

Thanks for the help

**Comment by davidjgonzalez** [comment]
here's the simple component i made to test: [acs-commons-issue-1018-1.0.0.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1066578/acs-commons-issue-1018-1.0.0.zip)

**Comment by davidjgonzalez** [comment]
@Sandeep18051990 hopefully this isnt a Windows thing since i cant help you with that. Can you:

1) verify there are no JS errors when you POST the data back (save the dialog)
2) verify in the network request headers on the POST that all the data is present (A2, B2, C2)
3) verify that all the data is present in the JCR post the post (check the JSON obj persisted to the node)
4) when opening the dialog, verify that the HTTP GET for the data is sending all the data (A2, B2, C2)

You might have to roll up your sleeves and debug this one yourself in Windows though :(

**Comment by Sandeep18051990** [comment]
I tried various options .. even tried listener options loadContent
function(){
var valu=this.findParentByType('dialog').getField('./navitems').getValue();
alert("find it"+valu);
}

It's giving a stripped value even though JCR node has a correct json values this is happening only when tag field is empty.
:(

**Comment by Sandeep18051990** [comment]
@davidjgonzalez

**Comment by Sandeep18051990** [comment]
Is there anyway I can set default value to tags pro-grammatically or by some property settings

**Comment by davidjgonzalez** [comment]
@Sandeep18051990 so the issue if confirmed as the dialog can't repopulate the fields on reload (the correct data is persisted and read from jcr). Right?

**Comment by Sandeep18051990** [comment]
Yes you are correct

**Comment by Sandeep18051990** [comment]
https://github.com/davidjgonzalez

**Comment by Sandeep18051990** [comment]
@davidjgonzalez If the tag field is selected than dialog is repopulated with correct field,It will fail to populate the values one below where tag field is empty/not selected

**Comment by Sandeep18051990** [comment]
@davidjgonzalez Data in JCR {"linktitle":"one","linkurl":"","privatelinkurl":"","eserviceRole":["forum:topic","forum:topic/answered"]},
 {"linktitle":"three","linkurl":"","privatelinkurl":"","eserviceRole":[]},
{"linktitle":"twi","linkurl":"","privatelinkurl":"","eserviceRole":["forum:topic","forum:topic/answered"]};

listener
function(){
var valu=this.findParentByType('dialog').getField('./navitems').getValue();
alert("find it"+valu);
}

alert in above listener is giving only 2 values

{"linktitle":"one","linkurl":"","privatelinkurl":"","eserviceRole":["forum:topic","forum:topic/answered"]},
 {"linktitle":"three","linkurl":"","privatelinkurl":"","eserviceRole":[]};

**Comment by Sandeep18051990** [comment]
@davidjgonzalez So to conclude correct data is persisted but while reading it has an issue .. it's excluding values below where tag is not selected

**Comment by davidjgonzalez** [comment]
@Sandeep18051990 if you look at the HTTP request that GETS the JSON from the JCR; do you see the 3 items coming back OR are you seeing only those last 2?

If the HTTP requests the sends the content back only contains the 2, then there is a problem w the serialization of the data (server-side), if the HTTP request HAS the 3 entries, then its something in the JS.

**Comment by Sandeep18051990** [comment]
@davidjgonzalez I have observed HTTP requests and the request contain only 2 items. Do you have any leads which component in acs-commons I need to verify in order to fix this. 

Thanks for your help here

**Comment by rtellez-xumak** [comment]
I had the same issue, I created a component called "blog" and apparently other component called called "blog" was called in the load process. To solve the issue I just change the name of my component /apps/myproject/components/blog -> /apps/myproject/components/other-blog 
and everything worked fine.
