### ISSUE TITLE
Clarify use of ResourceResolverMapTransformerFactory over Link Transformer Factory

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Consulting-Services/acs-aem-commons#1021]
The code inside ResourceResolverMapTransformerFactory doesn't seem to do anything other than what the Link Transformer Factory does.

Is it supposed to work with every element & attribute? Because it doesn't. You still have to do manual configuration of the /apps/x/config/rewriter and if you do, then the linktransformerfactory will also pick up those elements & attributes.

**Comment by davidjgonzalez** [comment]
@henrykuijpers yeh ... you can actually configure the link rewriter to ~ do what the RRMapTransformerFactory does ... probably should deprecate it ..

**Comment by henrykuijpers** [comment]
Hi @davidjgonzalez , can you reopen this ticket?

I've been digging through the Day CQ Linkchecker code a few days ago and the Linkchecker doesn't do everything the ResourceResolverMapTransformerFactory can do.

It's code is very limited:
  private static final Set<String> LINK_NAMES = new HashSet(Arrays.asList(new String[] { "href", "src", "action" }));
  private static final Set<String> CHECK_ELEMENT_NAMES = new HashSet(Arrays.asList(new String[] { "a", "area" }));

These are basically the elements that can be checked and they don't allow further configuration. So you can set the configuration to img:src as you wish, but these LINK_NAMES and CHECK_ELEMENT_NAMES are not being checked anyway. It also only checks .html links, it doesn't check .jpg links for example (so if you want to map the images that are rendered with the image components, you're out of luck).

**Comment by henrykuijpers** [comment]
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/564
https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/issues/45
