### ISSUE TITLE
composite-multifield - Order of fields

### ISSUE THREAD

**Issue by jbaix** [Adobe-Consulting-Services/acs-aem-commons#1025]
Hello.

I’m using AEM 6.2 SP1 CFP2.

I’m using the **composite-multifield** in a dialog with attribute acs-commons-nested="**NODE_STORE**". https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/master/content/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/composite-multifield

I can see the nodes in the CRXDE, and the order in the JCR is always the same than in the dialog, which is perfect. But, when I use the data-sly-list HTL statement, the order of the elements in the HTL list is different.

I don’t know if the problem is with the composite-multifield or with HTL data-sly-list (or with my implementation).

Anybody with the same issue? Any idea?

Any help would be appreciated.
Kind regards,

**Comment by davidjgonzalez** [comment]
@jbaix if the content is persisted in the correct order in the JCR (i assume its all stored as `nt:unstructured` nodes aka an `ordered node type`), then the issue is with how your using HTL to pull the list out.  

Can you post a screenshot (or package) of the node-structure and the HTL snippet reading the list of nodes?

**Comment by jbaix** [comment]
Thank you @davidjgonzalez for you answer.

The nodes of both the parent and children composite-multifield elements are of type oak:unstructured (so, non ordered node types). But the question is that, as far as I can see, the elements in the dialog are always ordered! Is the composite-multifield client-side code including any logic to order the elements (based on jcr:name, it could be)?

Anyway, if the node type is the key, is there any way to change the node type that the composite-multifield is using to store the elements in the JCR, from oak:unstructured to nt:unstructured?

This is an example of a node-structure (with some composite-multifield):
{
  "jcr:primaryType": "oak:Unstructured",
  "jcr:lastModifiedBy": "admin",
  "agenda:dataInici": "Mon Oct 02 2017 00:00:00 GMT+0000",
  "agenda:dataFi": "Tue Oct 31 2017 00:00:00 GMT+0000",
  "agenda:subtitol": "<p>Subtítol de l'article<\/p>\r\n",
  "jcr:lastModified": "Wed Jun 14 2017 11:54:27 GMT+0000",
  "sling:resourceType": "agenda/components/structure/article",
  "agenda:dataFiAprox": "true",
  "agenda:tagsCategories": [
    "agenda:categories/concerts",
    "agenda:categories/espectacles"
  ],
  "agenda:denominacio": "<p>Article de proves keyword1<\/p>\r\n",
  "documents": {
    "jcr:primaryType": "oak:Unstructured",
    "10": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:nom": "Nom document 1b",
      "agenda:path": "/content/dam/agenda/admin/portada/destacat2.jpg"
      },
    "9": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:nom": "Nom document 2a",
      "agenda:path": "/content/dam/agenda/admin/portada/destacat2.jpg"
      }
    },
  "enllacos": {
    "jcr:primaryType": "oak:Unstructured",
    "7": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:nom": "Nom de l'enllaç 1",
      "agenda:url": "http://www.google.es"
      },
    "8": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:nom": "Nom de l'enllaç 2",
      "agenda:url": "http://www.google.es"
      }
    },
  "organitzadors": {
    "jcr:primaryType": "oak:Unstructured",
    "6": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:organitzador": "Organitzador 2",
      },
    "5": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:organitzador": "Organitzador 1",
      }
    },
  "llocs": {
    "jcr:primaryType": "oak:Unstructured",
    "4": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:localitat": "Girona",
      "agenda:espai": "Centre Ciutat",
      },
    "2": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:localitat": "Barcelona",
      "agenda:espai": "Gran Teatre del Liceu",
      },
    "3": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:espai": "catedral",
      },
    "1": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:localitat": "Barcelona",
      "agenda:espai": "Palau de la música",
      }
    },
  "videos": {
    "jcr:primaryType": "oak:Unstructured",
    "13": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:codi": "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/uD-d4Q2yF88\" frameborder=\"0\" allowfullscreen><\/iframe>",
      "agenda:descripcio": "Descripció del vídeo 1"
      },
    "14": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:codi": "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/uD-d4Q2yF88\" frameborder=\"0\" allowfullscreen><\/iframe>",
      "agenda:descripcio": "Descripció del vídeo 2"
      }
    },
  "imatges": {
    "jcr:primaryType": "oak:Unstructured",
    "11": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:peuImatge": "peuImatge 1",
      "agenda:path": "/content/dam/agenda/admin/portada/destacat2.jpg"
      },
    "12": {
      "jcr:primaryType": "oak:Unstructured",
      "agenda:peuImatge": "peuImatge 2",
      "agenda:path": "/content/dam/agenda/admin/portada/destacat2.jpg"
      }
    }
  }

**Comment by jbaix** [comment]
I've realized that if I change the jcr:primaryType of the component node to 'nt:unstructured', then the nodetypes used in the parent/children nodes of the composite-multifield elements are also 'nt:unstructured'. So, my issue is resolved.

I had been using oak:Unstructured in my root component node to improve the performance of future search operations, but I can change it to nt:.

Anyway, I'm wondering if the parent/children nodes of the composite-multifield elements could be nt:unstructured (to preserve the order of the elements) while the component root node remains as oak:Unstructured (given that the order of the parent nodes of the different composite-multifield inside the component root node is not important to build the dialog). It has sense? Is a composite-multifield implementation issue?

**Comment by davidjgonzalez** [comment]
How many nodes are in there? Non-ordered nodes only really make a meaningful difference when the flat tree segments become very very large, which I have a hard time believing and authored content via a dialog will grow to.

I think mixing node types is just going to add complexity for no real life benefit.

**Comment by jbaix** [comment]
Thank you very much, David! We'll let the nt:unstructured node types.
