### ISSUE TITLE
Sharedcomponent Properties

### ISSUE THREAD

**Issue by kishore4784** [Adobe-Consulting-Services/acs-aem-commons#1031]
when using shared component, if i open its dailog in chrome it is working properly.
But when I inspect using developer tools in chrome and open shared component dailog it is not going back to the same page when i close the dailog. It is navigating to the root page which I provided in the rootpageprovider config.

**Comment by davidjgonzalez** [comment]
@kishore4784 are you saying that this issue (of not going back to the same page) ONLY occurs when you have Chrome Dev Tools open? And when you dont, it works as expected?

**Comment by kishore4784** [comment]
Yes only when chrome developer tools is open.

**Comment by davidjgonzalez** [comment]
Closing as this seems like a low impact issue, effecting only developers; if someone wants to fix please re-open and submit a PR.
