### ISSUE TITLE
PageRootProvider should support factory configurations and different implementations

### ISSUE THREAD

**Issue by stefanseifert** [Adobe-Consulting-Services/acs-aem-commons#1037]
currently, there is a service interface `PageRootProvider` with a single implementation `com.adobe.acs.commons.wcm.impl.PageRootProviderImpl`. the latter has a singleton configuration for setting a list of regex patterns for detecting the page root.

this is too inflexible if multiple applications from different providers are deployed to a single AEM instance. each application may have a different pattern for detecting the root path, and for each application a distinct set of configurations may be deployed because they are maintained by different teams. using factory configurations solves this problem, so each application can have it's own set of regex patterns configured.

additionally this would allow alternative implementations for detecting the page root path. in wcm.io for example the page root path is detected by using the "inner-most" Sling Context-Aware Configuration root path, so there is not need to declare this twice.

my proposal would be something like this:

* create a new interface like `RootPathStrategy` which is not intended to be used by applications directly, but only to provide different strategies to the RootPathProvider. it has only one method for mapping Resource to root path (String)
* a default implementation exists like the current implementation of PageRootProviderImpl which allows configuration via a list of regex strings. but this can be configured multiple times by osgi factory configurations.
* if multiple implementations of `RootPathStrategy` exist the first wins in service ranking order that has a non-null answer for given resource
* for backward compatibility the PID `com.adobe.acs.commons.wcm.impl.PageRootProviderImpl` should still be supported for providing the regex configurations

**Comment by HitmanInWis** [comment]
Seems like a great idea.  Would be happy to review a PR if someone wants to put one together.  Otherwise, its possible we might be able to do something like this at the next HS2 Solutions hackathon in a couple months.

**Comment by daniel-lima** [comment]
Hi all.

I wasn't aware of this thread. Thanks, @stefanseifert to brought it to my attention.

I believe #1087 will only fullfill the 2nd and 4rd requirements:

> - a default implementation exists like the current implementation of PageRootProviderImpl which allows configuration via a list of regex strings. but this can be configured multiple times by osgi factory configurations.
> - for backward compatibility the PID com.adobe.acs.commons.wcm.impl.PageRootProviderImpl should still be supported for providing the regex configurations

Best regards,

Daniel.

**Comment by HitmanInWis** [comment]
Seems like #1087 is a good start on this, and once that is pulled in this issue can remain to add support for different "strategies" (other than path regex) if that is still desired.

**Comment by daniel-lima** [comment]
@stefanseifert, what are your thoughts about the changes made by [PR 1088](https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1088) and [PR 1089](https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1089)? Are they good enough?

@HitmanInWis , I apologize for my newbie question, but how do I apply a label to [1087]? Do I need to request a special permission for that?

Thanks!

**Comment by stefanseifert** [comment]
the PRs are a step in the right directy, but i still would prefer to introduce an interface like described in my initial post to allow different implementations than only regex.

i'm thinking for example about implementations that detects root path by getting configuration context paths from Sling Context-Aware Configuration, or by detecting the root by finding a page with a certain AEM template.

**Comment by HitmanInWis** [comment]
I agree with @stefanseifert that his suggestion would be a further improvement, but I think that PR 1088 and PR 1089 stand on their own as a useful feature and thus can move forward as-is unless someone wants to make further modifications to those PRs.  The remaining functinoality (different implementations than regex) can still be added as a new feature later.

As for "apply a label to 1087" I'm not sure - probably more a question for justinedelson or davidjgonzalez but 1087 should probably remain open if PRs 1088 and 1089 go without the extra functionality requested by stefanseifert.

**Comment by daniel-lima** [comment]
Thanks for your answers, @stefanseifert and @HitmanInWis!

stefanseifert, because I always prefer small and incremental changes in development and my primary goal with PR 1088 and 1089 was to reuse PageRootProvider in our client's multisites/apps, I would agree with HitmanInWis, treat them independently of 1087 and keep this opened for the remaining changes.

Does it make sense for you?

**Comment by stefanseifert** [comment]
this is fine from my side - we only should try to avoid introducing new configuration we need to deprecate later like {{com.adobe.acs.commons.wcm.impl.PageRootProviderImpl}}. but if we find a new name for the interface if it is introduced later we can keep your factory configuration class.

**Comment by daniel-lima** [comment]
Agreed!

I had only "deprecated" PageRootProviderImpl to warn users about the new config behavior (single config vs multiple/factory config), while preserving backward compatibility.
