### ISSUE TITLE
Health Check Status E-mailer

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1039]
It would be nice to have a way to have to periodically run sets of of Sling Health Checks and e-mail the results to a set of users. It would provide a simple, consistent digest across any AEM environment (even lower envs that might not enjoy prod-level monitoring). I can see two major uses:

1) Run a set of health checks frequently (every hour?)  and ONLY send e-mails if at least 1 failure occurs. (So as not to numb people to these emails)
2) Run a set of health checks less frequently (once a day/week?) and send the full status (All Success and Failures)

This has the achilles heel of if the SMTP server is unavailable, no e-mail will be sent. but hopefully the absence of emails from use case #2 is sufficient to identify this (along w other monitoring).

This should be an OSGI config factory so different schedulers w/ different configurations can be setup based on the multiple (2) uses outlined above.

## OSGi Factory Config
![image](https://user-images.githubusercontent.com/1451868/27871821-e06e13d4-6174-11e7-86db-25f3e2655a9d.png)

## Example E-mail

![email](https://user-images.githubusercontent.com/1451868/27872066-87d333fc-6175-11e7-9d1a-f0fc8228edc4.png)

_note this screenshot has the success and failure #'s in the subject line flipped_

**Comment by davidjgonzalez** [comment]
Do we have a good way of getting human-understandable AEM instance names? It just occurred to me specifying it in the osgi config isn't good as it requires a 1:1 between aem instance and runmode. (or requires manual configuration of the osgi config)

**Comment by justinedelson** [comment]
Yeah, in a cluster or farm, the OSGi config route isn't very useful. I doubt most folks set up a unique run mode per instance.

Two options come to mind:
* Doing a reverse DNS lookup.
* Using a system property

In both cases, you could fall back to the OSGi config if unspecified.

**Comment by davidjgonzalez** [comment]
Was chatting w @tomblackford and looks like https://github.com/mattsheppard/gethostname4j is a reasonable impl; can see if it can be ported in w attributions.

**Comment by justinedelson** [comment]
That one class looks trivial enough, but I think getting JNA working inside AEM might be interesting :)

**Comment by andrewmkhoury** [comment]
Seems you could embed jna in the bundle http://apache-felix.18485.x6.nabble.com/JNA-problem-td4841562.html
