### ISSUE TITLE
Not able to get all the users

### ISSUE THREAD

**Issue by psjaison** [Adobe-Consulting-Services/acs-aem-commons#1042]
While i m trying to export users to csv, I am not able to get all users in my environment. Please let me know if  I am missing something or it is a known bug

**Comment by davidjgonzalez** [comment]
What version of acs commons and aem? What is your user exporter config? And who are you running the report As?

What is the pattern to who is missing for your report?

**Comment by davidjgonzalez** [comment]
Closing due to lack of information. Please re-open with more information if you continue to have issues.
