### ISSUE TITLE
JcrPackageReplicationStatusEventHandler should set replicatedBy by default to the user who replicated the package

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#1044]
Currently the `replicated by` value is hardcoded in the OSGi configuration. Instead it should be taken from the user who originally replicated the package itself.

**Comment by kwin** [comment]
You should use `com.day.cq.replication.ReplicationAction#fromEvent(Event)` to construct a `ReplicationAction` object exposing all relevant metadata about the replication event (including the user triggering it).

**Comment by justinedelson** [comment]
@davidjgonzalez this is fixed, right?

**Comment by davidjgonzalez** [comment]
Yes
