### ISSUE TITLE
Utility to repair broken nodes 

### ISSUE THREAD

**Issue by vaibhav6451956** [Adobe-Consulting-Services/acs-aem-commons#1048]
Hi Contributors,

I have worked on various cases with customers where during the upgrade or some other activity, there are various properties which are missed and not being registered thereby leading to several issues.

In that case, the developers are needed to write a script to traverse through all the required nodes and repair the faulty nodes by adding missing properties to them.

I am thinking to develop a utility with a UI, where one needs to enter the type of nodes and the missing property to be added and the utility takes care of the rest.

Do let me know your views on this. 

I would appreciate if someone is interested teaming up to build this.

**Comment by badvision** [comment]
You shouldn't have to build this from scratch.  Look at the MCP pull
request...

**Comment by badvision** [comment]
Ok now that MCP is officially in, I recommend you look at the Asset Report and Tree Prune process definitions for inspiration on this.  Basically you:
1) Create a class which implements process definition
2) Add annotated variables which allow the user to specify the root node to start crawling, what property to set, and finally what value to set it to
3) In the build process step, add a method reference to the actual method that will do the work
4) In your main method, take advantage of the same visitor (I recommend folder visitor but you can use whatever you want) to process nodes.
5) Use a retry batch just in case there's any errors, and in there call your method to set the desired property on each node in question if required.
6) Commits, error handling, user interface are all handled for you.  I don't expect this to be more than 100 lines of code, if that.

**Comment by badvision** [comment]
@vaibhav6451956 thoughts?

**Comment by vaibhav6451956** [comment]
@badvision  Sorry for the late reply...Was busy with work. I will take a look at the steps mentioned by you and will get back.

Thanks a lot!

**Comment by badvision** [comment]
I am in the midst of needing to do the same thing so I might just write it before you get around to it.  Stay tuned...

**Comment by badvision** [comment]
This is still pending my ability to test what I've already written.  Let's keep this open a bit longer.
