### ISSUE TITLE
Too many open issues.

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1056]
Please review issues > 2 years old and close if no longer relevant.

**Comment by badvision** [comment]
Thanks @davidjgonzalez !!!

**Comment by davidjgonzalez** [comment]
Sadly I only go through about half :)

Reopening since this is a nice reminder

**Comment by badvision** [comment]
Wow, ok thanks!

**Comment by davidjgonzalez** [comment]
ok - think thats pretty much it. I tried to tag things properly as well to its easier understand feature/enhancement/bug.
