### ISSUE TITLE
Tree activation utility

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1060]
As a regular user I would like to replicate a structure of folders (for DAM) or site/pages (for Sites) such that:
- Indicate the starting folder
- specify how many levels to go (aka 1 page, or all if desired)
- Indicate if this uses regular replication (all default publishers) or specify a list of publishers
- Pick either replication queue or self-managed queue for replication
- At the end, get a report of how many pages/folders/assets were replicated.

Also, this tool should be smart enough that once some entities are replicated, there is no need for subsequent replication of child nodes.  For example, replicating an asset is a terminal tree traversal operation.  That is, however, not the case for a page.

**Comment by badvision** [comment]
@davidjgonzalez, @justinedelson any thoughts on activation of pages?  Does replicating a page automatically replicate any children/grandchildren etc as long as they themselves are not cq:page?  Are there any other gotchas?

**Comment by davidjgonzalez** [comment]
Replication operates on the nt:hierarchy structure; so the cq:page and cq:page/jcr:content sub structure. 

main gotcha w page replication is replicating references which requires calls to reference provider and explicit replication of the referneced resources; with the advent of template editor based pages this web has expanded (templates, policies, etc).

I wonder if there is a tipping point where making a package ( ala SCD) of pages and supporting resources becomes better/worse than inidiviual repoication. (You'd want to do something like jcr package replication status updater to ensure packages resources get the right rep status)

**Comment by davidjgonzalez** [comment]
Wdyt about making the selection criteria support a query as well? Maybe you could add the root plus level to the QueryHelperImpl and support all the resource collection options that supports?

**Comment by andrewmkhoury** [comment]
@badvision and @davidjgonzalez I see a lot of AEM developers and admins asking for these abilities in an activation tool:
* Re-activate the last activated version of the content (this is used to build out new publish instances or fix content that failed to activate to one or more publish instances)
* Activate content based on a timeframe (e.g. date/time X to current date/time)
* Skip deactivated content
* Activate paths from query result

**Comment by YegorKozlov** [comment]
my wish list:

- dry-run 
- replicate direct references. 
- optionally pass the activated resource through a user code. I had projects where all replications went through the Request For Activation workflow which included  workflow steps with business logic. It would be great to mimic it and execute user code before a resource is added to the replication queue. 
- throttle replication. The tool should be smart to  stop putting items in the replication queue if it is stuck or longer than N elements.

**Comment by badvision** [comment]
See the MCP framework -- you can use MCP/FAM for replication and avoid using the replication queue.  That would solve the performance problem you are mentioning in your last bullet point.  Problem with looking at size of queue is that it requires running a query, and that can get really slow if things aren't behaving properly.  By using synchronous replication, you can offload the work entirely to MCP, but this leaves you at a slightly higher risk because there is no queue persistence this route.

**Comment by badvision** [comment]
Psych!  You thought I forgot about this but nope here's a tree activation utility.  No query, sorry, but we can add that as a follow-up feature if there's a lot of demand.
