### ISSUE TITLE
Email Service adds <pre></pre> tag around templates

### ISSUE THREAD

**Issue by sagarmandal** [Adobe-Consulting-Services/acs-aem-commons#1063]
If someone wants to use full HTML (`<html><head>...</head><body>...</body></html>`) template, then whole HTML gets wrapped in `<pre></pre>` tags, which breaks the HTML formatting/styles of he template.

**Comment by justinedelson** [comment]
based on the feedback in #1070, this is a product bug.

**Comment by pat-lego** [comment]
This is because it uses it uses this https://github.com/apache/commons-email/blob/master/src/main/java/org/apache/commons/mail/HtmlEmail.java#L90-L92 and it hard coded to wrap it with pre.
