### ISSUE TITLE
Documentation for EnsureServiceUser is missing escaping for the comma & missing short-close-tag

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Consulting-Services/acs-aem-commons#1069]
https://adobe-consulting-services.github.io/acs-aem-commons/features/ensure-service-users/index.html

"jcr:read,rep:write" should be "jcr:read\\,rep:write"
Also the short-close-tag is missing.

**Comment by justinedelson** [comment]
well spotted. fixed.
