### ISSUE TITLE
Instant Package Utility

### ISSUE THREAD

**Issue by edubey1** [Adobe-Consulting-Services/acs-aem-commons#1071]
**Description:** Allow user to instantly create a package from selected resource.

**Current Steps**

- Create package
- Add filter by copy / paste I guess
- Build and download

**New Steps**

- Select the pages 
- Click to download an AEM Package 

**Purpose:**   Save time and simplified process

![package](https://user-images.githubusercontent.com/6499027/29186965-c2376518-7e2b-11e7-8194-ef97a7392431.jpg)

Do share your feedback on it.

**Comment by davidjgonzalez** [comment]
I think this is quite interesting indeed! Are you thinking it would support descending downs content paths? Would this be sites admin specific? Or assets as well?

**Comment by adobecquser** [comment]
Hi Praveen,

This is a nice feature developed. Nice work.

Just an additional thought. 

Have seen in certain cases with clients , wherein during some critical launches which keeps happening at periodic intervals, they need to create packages of several pages [say 100 to 200] and deploy it to prod. Probably by the above solution, we need to individually select pages. But in case, the pages are spread across the site, it kind of becomes difficult for the administrator to go about using this. If there is something that can be done w.r.t this , it would be a really good-to-have feature.

**Comment by edubey1** [comment]
@davidjgonzalez Thanks
1. Yes, that's the idea as of now making it descending down the path but giving an simple option in pop up for user to select this, can also be considered. As there can be scenarios where user may not descending downs content paths. :)

2. Yes, Assets use also sounds good.

**Comment by poojachauhan** [comment]
@edubey1 Have you started working on this feature?

**Comment by edubey1** [comment]
Not Yet, but I will soon get started working on this.
You have any thoughts?

**Comment by badvision** [comment]
One additional request is to create a package using a date modified filter on the contents, so that folks have a way to package new or recently modified content.  This is a common request, especially for migrations/upgrades.

**Comment by davidjgonzalez** [comment]
@badvision is the date modified something for this feature? It seems this is not a query feature but rather a manual select. I believe the query packager can do this already?
