### ISSUE TITLE
Page SEO Tracker

### ISSUE THREAD

**Issue by edubey1** [Adobe-Consulting-Services/acs-aem-commons#1072]
**Description** - Allow business to easily evaluate SEO at the page level. There have been times where business did not follow certain SEO practices while authoring and realize these mistakes later where search ranking was already lower. 
 

- The Certain aspect of the authoring always contributes to SEO, the idea is to probably show a rating or stats of things can be improved for a page.
- Rating will help a business person to keep SEO in mind.

![seo](https://user-images.githubusercontent.com/6499027/29187390-352d3146-7e2d-11e7-8405-b7acd31c1f66.png)

Do share your thoughts on it

**Comment by davidjgonzalez** [comment]
Would be good to share how the seo guidance will be derived.. 3rd party service? Some custom backing logic?

**Comment by edubey1** [comment]
@davidjgonzalez Yes, I see two options here either we can go for some 3rd party service [OR] can built some service in AEM which take care of those SEO checkpoint. I am still exploring on what options we can look for. 
Will post update here.

**Comment by justinedelson** [comment]
This looks to be exactly what is provided by the BrightEdge connector. I'm sure there are other 3rd parties which provide similar services.
