### ISSUE TITLE
Independent configurations for PageRootProvider (Shared Component Properties)

### ISSUE THREAD

**Issue by daniel-lima** [Adobe-Consulting-Services/acs-aem-commons#1087]
**Use case:** To use PageRootProvider and/or Shared Component Properties in shared AEM environments.

**Description**: We usually work with clients whose AEM instances are shared by multiple independent vendors. Each vendor develops and controls solely its corresponding sites/apps.
Therefore, to configure PageRootProvider only for our site/app as an embeded sling:OsgiConfig node, without affecting any other site/app, PageRootProvider must support multiple and independent configurations.

To achieve that, I've changed the current implementation ([here](https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1089) and [here](https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1088)) to be configurable through PageRootProviderConfig. The change is backward compatible, so it **won't** break sites/apps that are still using PageRootProviderImpl to configure a Page Root Provider.

**Comment by stefanseifert** [comment]
this is related to #1037

**Comment by daniel-lima** [comment]
Hi, @stefanseifert. 

I wasn't aware of that, but thank you for letting me know.
I came up with this simpler solution to meet only our current requirements.

Regards,

Daniel.

**Comment by daniel-lima** [comment]
@justinedelson and @davidjgonzalez , how do I apply labels to the Github issues that I've created? Do I need a special permission for that?

BTW, is there any label to apply for minor changes?

Thanks!

**Comment by justinedelson** [comment]
@daniel-lima only committers can add labels (a "feature" of GitHub Issues I personally don't love). What label do you want to add?

**Comment by daniel-lima** [comment]
Hi, @justinedelson . I asked about tagging because of the following text in the [contributing doc](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/CONTRIBUTING.md#how-to-contribute-code):

> In many cases, it is worth having a discussion with the community before investing serious time in development. For these cases, create a GitHub issue of type "feature review" with a description of the problem you are trying to solve.

BTW, to request commit rights on this repository, I just need to open a ticket here on GitHub?

https://github.com/Adobe-Consulting-Services/acs-aem-commons#want-commit-rights

**Comment by justinedelson** [comment]
@daniel-lima that's a good callout. It is possible that when that document was written the restriction on labels wasn't presents. @davidjgonzalez do you remember what the intention was there?
