### ISSUE TITLE
QR code contains bug that makes it log WARN/ERROR all the time

### ISSUE THREAD

**Issue by royteeuwen** [Adobe-Consulting-Services/acs-aem-commons#1094]
With a standard AEM 6.3 CFP2, when opening for example the /content/we-retail/us/en/men, you default get following logs in the error.log, making the logs very bloated and wrong. This should definitely be an ERROR, and I don't know why a WARN would be logged either on a standard with no configuration

```
29.08.2017 23:12:20.908 *WARN* [0:0:0:0:0:0:0:1 [1504041140907] GET /etc/acs-commons/qr-code/_jcr_content/config.json/content/we-retail/us/en/user.html HTTP/1.1] com.day.cq.wcm.core.impl.components.ComponentCacheImpl No component node found at /apps/acs-commons/components/utilities/qr-code/config
29.08.2017 23:12:20.908 *ERROR* [0:0:0:0:0:0:0:1 [1504041140907] GET /etc/acs-commons/qr-code/_jcr_content/config.json/content/we-retail/us/en/user.html HTTP/1.1] com.adobe.acs.commons.wcm.impl.QrCodeServlet Externalizer configuration for AEM Publish did not yield a valid URL
```

**Comment by davidjgonzalez** [comment]
@royteeuwen is this without QR Code enabled at all?

**Comment by davidjgonzalez** [comment]
@royteeuwen can you try this [1] out? You may need to toggle QR Code on and off [1] (to clear the clientlib category setting) and also clear you browser cache.

[1] [acs-aem-commons-content-3.10.1-SNAPSHOT-min.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1262122/acs-aem-commons-content-3.10.1-SNAPSHOT-min.zip)
[2] http://localhost:4502/etc/acs-commons/qr-code.html

**Comment by royteeuwen** [comment]
Perfect, this seems to fix it, thanks a lot @davidjgonzalez

**Comment by davidjgonzalez** [comment]
@royteeuwen thanks for confirming - will likely cut a build this weekend w the fix. Don't have much time after work this week to do much :(

**Comment by royteeuwen** [comment]
@davidjgonzalez no worries, I know the feeling, thanks a lot :)!
