### ISSUE TITLE
MCP Process and Report tables should use CoralUI3 table

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1098]
The MCP Process and Report tables should use the CUI3 table.

![image](https://user-images.githubusercontent.com/1451868/29851805-2cde8b8a-8d04-11e7-8156-79128b3b0f78.png)

![image](https://user-images.githubusercontent.com/1451868/29851815-36bddb92-8d04-11e7-9583-834f66041dcf.png)

**Comment by badvision** [comment]
Much improved!  Thanks!

**Comment by davidjgonzalez** [comment]
Added a lockable column - this turns out to be helpful when culling long reports for a few rows of interest.

![2017-08-31_at_8 58_am-2](https://user-images.githubusercontent.com/1451868/29924490-18311982-8e2b-11e7-9abb-4ee070793438.png)
