### ISSUE TITLE
Add feature to grab publish url of an asset or a page

### ISSUE THREAD

**Issue by kunalgaba** [Adobe-Consulting-Services/acs-aem-commons#1101]
Business users quickly want to grab publish url for sharing or for using it in external tools like Target. 

<img width="1132" alt="screen shot 2017-08-31 at 5 13 27 pm" src="https://user-images.githubusercontent.com/388029/29964714-96a7b354-8f28-11e7-966f-01881be2b809.png">

**Comment by davidjgonzalez** [comment]
Makes sense to me; I assume his only shows of the asset is published? Or has some indication that it is/isn't from this UI?

**Comment by kunalgaba** [comment]
Yes the button will be hidden if the asset is not published.

**Comment by davidjgonzalez** [comment]
Looks like a cool feature! TBH surprised ita not part of the product :)

**Comment by kunalgaba** [comment]
Yes. I was surprised too. I can commit this if you grant me commit rights.

**Comment by davidjgonzalez** [comment]
@kunalgaba can you PR it as described here?

https://adobe-consulting-services.github.io/acs-aem-commons/pages/contribute.html
