### ISSUE TITLE
Bulk workflow manager : "Start bulk workflow" disabled

### ISSUE THREAD

**Issue by Khrogar** [Adobe-Consulting-Services/acs-aem-commons#1103]
Hello,

acs-aem-commons version : 3.10.0
aem version : 6.2

The button start bulk workflow is disabled, i have a message informing me that the form is incomplete.

To activate it, i have to switch from aem workflow to synthtic workflow and fill the "Set user-event-data" wich appear, then i can go back to "Aem workflow" and start it.

**Comment by davidjgonzalez** [comment]
@Khrogar this is indeed an issue. Keeping it open and hope to find time soon.

**Comment by justinedelson** [comment]
@davidjgonzalez FYI - you can add the "pinned" tag to tell stalebot not to close an issue

**Comment by davidjgonzalez** [comment]
Fixed via  #1306
