### ISSUE TITLE
Move CSV Asset Importer to use MCP

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1105]

**Comment by badvision** [comment]
awwwwww yeah.  But by the time you do that it's virtually the same as the asset ingestor example.  Almost.  (except CSV import is better-tested)

**Comment by badvision** [comment]
That is the major difference between the two, yes.  But isn't it possible to run CSV without any metadata being imported?

**Comment by davidjgonzalez** [comment]
Sure - but why would you do that! :)

**Comment by pflory** [comment]
+1 to this marriage, though retaining CSV Importer pre-import parameters & features is key!
I'm currently working with a 6.0 customer that *heavily* depends upon CSV Importer for ongoing consolidation from several legacy DAM(-like) systems into AEM (across many business units). The ability to define the incoming assets' metadata -- using, specifically, Excel (for its familiarity and ease of use for biz users) -- is pretty much required at this point. We are in the process of planning a 6.3 upgrade, so now I'm stoked about the possibility of this feature request materializing!

**Comment by badvision** [comment]
This was implemented via URL Asset Import earlier this year.

**Comment by davidjgonzalez** [comment]
We should review(close as needed) the functionality gap, and then deprecate CSV Asset Importer.

It would be good to support the CSV header format as well (especially since it follows the products metadata import/export format)
