### ISSUE TITLE
ACS Commons dependency is not getting resolved for AEM 6.2 and AEM6.3 as well

### ISSUE THREAD

**Issue by abhishukl** [Adobe-Consulting-Services/acs-aem-commons#1107]
E:\frameworks>mvn -version
Apache Maven 3.3.9 
Java version: 1.8.0_40, vendor: Oracle Corporation

Above is the java and maven configuration versions.

I am using Email API of ACS Commons bundle by using following dependecy steps as per steps mentioned at ACS portal (https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html), for both AEM 6.2 and AEM 6.3 however none of the version are able to resolve the dependencies put in by ACS commons email api code.

I am getting following error after installing the package and my bundle is in installed state with these errors.
com.adobe.acs.commons.email,version=[1.1,2) -- Cannot be resolved
com.adobe.acs.commons.wcm,version=[2.0,3) -- Cannot be resolved

Genuine solutions please, where ACS Commons has worked for either of aem versions (6.2 or 6.3).

**Comment by justinedelson** [comment]
Is the ACS AEM Commons package installed in your AEM instance? Is the ACS AEM Commons bundle started?

**Comment by abhishukl** [comment]
No I am just having pom dependency in content and bundle projects pom for acs commons. ACS AEM Commons is not present at installed bundles.

**Comment by justinedelson** [comment]
The bundle will need to be installed and started in order for those packages to be resolved.

**Comment by mahesh1222** [comment]
Hi All,

Can someone please clarify the issue which am experiencing.

We have AEM 6.2 V and installed ACS AEM Commons package for debuggin and troubleshooting purpose.But the issue is For Audit-Search.html page it is having UTC time and our publisher which is hosted on server riting logs in EST timings.
When I search will all parameters, it is not giving any results to me.

Can someone please sort this out.

**Comment by justinedelson** [comment]
@mahesh1222 That wouldn't appear to be related to this issue, which is closed in any case.

**Comment by mahesh1222** [comment]
@justinedelson Can I get any help in any Forums?

**Comment by justinedelson** [comment]
maybe. Gitter can also be useful

**Comment by mahesh1222** [comment]
@justinedelson Thank you.
