### ISSUE TITLE
Version Clientlibs doesn't work under specific rummode

### ISSUE THREAD

**Issue by umeshtiwari23** [Adobe-Consulting-Services/acs-aem-commons#1109]
This solution doesn't work if the rewriter is in rummode specific folder. For an example if you have /apps/myapp/config.publish.prod/rewriter/versioned-clientlibs version never created.

**Comment by justinedelson** [comment]
Are you saying that other rewriter pipeline components work? As far as I know, the folder name containing the rewriter pipeline configuration must be exactly `config`. See https://sling.apache.org/documentation/bundles/output-rewriting-pipelines-org-apache-sling-rewriter.html

**Comment by umeshtiwari23** [comment]
No other rewrite pipeline also doesn't work, but defeats the purpose of having rummodes specific rewrite pipelines

**Comment by justinedelson** [comment]
That's what I expected. This is a Sling issue.
