### ISSUE TITLE
What is permanent fix for 'Responsive colum control'  for earlier and older versions?

### ISSUE THREAD

**Issue by Ramadevi3** [Adobe-Consulting-Services/acs-aem-commons#1115]
Reference ticket - #701
Input: /apps/acs-commons/components/content/column-control/clientlib/css/colctrl.less

**Solution**: 
Replacing
(~".acs-commons-resp-colctrl-col-@{index}")
with
.acs-commons-resp-colctrl-col-@{index}

This solution is working for 6.1 and 6.2 versions.
Is it possible to make permanent fix for this issue and it should work for earlier versions as well?

**Comment by justinedelson** [comment]
I'm not sure I follow. That change was released in 2.11.0 and 3.8.0.
