### ISSUE TITLE
Version 3.10 of has not been put into Adobe's nexus.

### ISSUE THREAD

**Issue by sasconsul** [Adobe-Consulting-Services/acs-aem-commons#1117]
I have been tracking down a bug and noticed that 
```
			<artifactId>acs-aem-commons-bundle</artifactId>
				<version>3.10.0</version>
```
has not been put into:
https://repo.adobe.com/nexus/content/groups/public/com/adobe/acs/acs-aem-commons-bundle/

Is it possible to add this version to the repo?

**Comment by sasconsul** [comment]
Sorry,  I did not notice the message on the webpage.

**Comment by davidjgonzalez** [comment]
@sasconsul hopefully in the next few days we'll see some traction in this issue; fingers crossed!

**Comment by justinedelson** [comment]
FYI - this was deployed yesterday.

**Comment by justinedelson** [comment]
argh. ignore that last commit. should have said 1119
