### ISSUE TITLE
ACL Packager do not export folder level permissions

### ISSUE THREAD

**Issue by rgummalla** [Adobe-Consulting-Services/acs-aem-commons#1118]
While using the ACL Packager on AEM 6.2 SP1/Mongo, Customer noticed this doesn't capture the appropriate folder-level permissions set up for that ACL. This is a key component missing in order for customer to use this ACLpackager.

**Comment by rgummalla** [comment]
[SampleACLPackage.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1322008/SampleACLPackage.zip)

**Comment by justinedelson** [comment]
The attached package just contains a group and it shows that the `rep:policy` node for that group was placed as part of the filter. I'm not sure what that is supposed to represent. I would expect to see a package (created manually, presumably) containing the uncaptured content (looks like some folders), the user/group, and the packager definition node.
