### ISSUE TITLE
How to change the timezone of the System Notification form?

### ISSUE THREAD

**Issue by simongangshen** [Adobe-Consulting-Services/acs-aem-commons#1119]
I am using the System Notification in AEM 6.1.
When I set the on-time and off-time in this form, the time will -4 hours.
I can see in the crx/de the time is 2017-09-26T20:00:00.000-04:00

How can I fix this? I want the time is exactly what I input in the field.

Thanks,
Simon

**Comment by badvision** [comment]
What's the time zone on the server itself?

**Comment by simongangshen** [comment]
We are using the EDT – Eastern Daylight Time

**Comment by justinedelson** [comment]
Dates are stored using the timezone of the client, so if you are in EDT and select 8pm, it'll get stored as 20:00:00.000-04:00.

I did uncover a problem (and just fixed it in c0c88924cfefb8490724ce9f6e03686de2e596e1) whereby roundtripping didn't work correctly, i.e. the initial save was correct, but when you reload the page and saved again, it could change the time unintentionally. Please test this and confirm that it fixes your issue (perhaps indirectly).

**Comment by simongangshen** [comment]
Thanks,justinedelson.
Your solution works.
