### ISSUE TITLE
/etc/acs-commons/users-to-csv does not exist in 3.10.0

### ISSUE THREAD

**Issue by somarc** [Adobe-Consulting-Services/acs-aem-commons#1123]
Requests to http://host:port/etc/acs-commons/users-to-csv.html 404's

Looking in crx/de the cp:page for this is not present.

**Comment by justinedelson** [comment]
Where did you see that path documented? Per https://adobe-consulting-services.github.io/acs-aem-commons/features/exporters/users/index.html, you have to create the page under /etc/acs-commons/exporters

**Comment by badvision** [comment]
Is this issue still valid?  If not may we close this out?

**Comment by somarc** [comment]
It has it's own tile card in the UX. The href points to the wrong path then OOTB after installing 3.10.0

**Comment by justinedelson** [comment]
thanks @somarc I see the link now.

https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/master/content/src/main/content/jcr_root/apps/cq/core/content/nav/tools/acs-commons/users-to-csv

@davidjgonzalez  any idea why this is there?

**Comment by davidjgonzalez** [comment]
@justinedelson it shouldn't be there. Im guessing i created that initially thinking there would be a single exporter page; and forgot to remove when the feature was moved over to multi-exporter pages.
