### ISSUE TITLE
Use of Hard-coded Password (CWE ID 259) Common Weakness Enumeration via VeraCode

### ISSUE THREAD

**Issue by LambaSwati** [Adobe-Consulting-Services/acs-aem-commons#1124]
We are using acs-aem-commons-3.9.0 bundle in our project.
According to Veracode security scan Report run on our project,
In  acs-aem-commonsbundle-3.9.0.jar, for class com/adobe/acs/commons/http/impl/HttpClientFactoryImpl.java on line number: 24, 14
A method uses a hard-coded password that may compromise system security in a way that cannot be easily remedied. The use of a hard-coded password significantly increases the possibility that the account being protected will be compromised.  Moreover, the password cannot be changed without patching the software.  If a hard-coded password is compromised in a commercial product, all deployed instances may be vulnerable to attack.

Could anyone confirm
1. If there is any hardcoded paasword used in this file?
2. If issue is present, is there any fix for it in any other version?

**Comment by justinedelson** [comment]
There's no hardcoded password in this file. Also, that specific line of code corresponds to an import statement, so I'm not sure what your security scanner is thinking.

**Comment by davidjgonzalez** [comment]
@LambaSwati - also, this is an open source project and release commits are tagged; it should be trivial for you to review files yourself - if the scanner finds verified real problems, of course please report them.
