### ISSUE TITLE
Improper Neutralization of CRLF Sequences in HTTP Headers ('HTTP Response Splitting') (CWE ID 113)

### ISSUE THREAD

**Issue by LambaSwati** [Adobe-Consulting-Services/acs-aem-commons#1125]
We are using acs-aem-commons-3.9.0 bundle in our project.
According to Veracode security scan Report run on our project,
In acs-aem-commonsbundle-3.9.0.jar, for class com/.../util/CookieUtil.java 
Description A function call contains an HTTP response splitting flaw.  Writing untrusted input into an HTTP header allows an attacker to manipulate the HTTP response rendered by the browser, leading to cache poisoning and cross-site scripting attacks.
Effort to Fix: 2 - Implementation error. Fix is approx. 6-50 lines of code. 1 day to fix.
Recommendations Remove unexpected carriage returns and line feeds from untrusted data used to construct an HTTP response.  Always validate untrusted input to ensure that it conforms to the expected format, using centralized data validation routines when possible.
Instances found via Static Scan

**Comment by justinedelson** [comment]
I don't see how this applies to CookieUtil.

**Comment by badvision** [comment]
@LambaSwati Please submit a source code pull request if you determine that 
- This is not a false positive in your scan
- You have identified a way to fix it and are willing to share your results.

The CookieUtil itself is not a widely used class, nor is it critical to most of the tools in this package so I don't see this being an indicator of any major concern.

**Comment by justinedelson** [comment]
I did some additional research. As with #1126, this is the responsibility of the caller to `addCookie`. Where `CookitUtil` does create new `Cookie` objects, it does so by cloning an existing one from the request object.
