### ISSUE TITLE
Sensitive Cookie in HTTPS Session Without 'Secure' Attribute (CWE ID 614)

### ISSUE THREAD

**Issue by LambaSwati** [Adobe-Consulting-Services/acs-aem-commons#1126]
We are using acs-aem-commons-3.9.0 bundle in our project.
According to Veracode security scan Report run on our project,
In acs-aem-commonsbundle-3.9.0.jar, for class com/.../util/CookieUtil.java
Description Setting the Secure attribute on an HTTP cookie instructs the web browser to send it only over a secure channel, such as a TLS connection.  Issuing a cookie without the Secure attribute allows the browser to transmit it over unencrypted connections, which are susceptible to eavesdropping.  It is particularly important to set the Secure attribute on any cookies containing sensitive data, such as authentication information (e.g. "remember me" style functionality).
Effort to Fix: 1 - Trivial implementation error. Fix is up to 5 lines of code. One hour or less to fix.
Recommendations Set the Secure attribute for all cookies used by HTTPS sessions.
Instances found via Static Scan
Flaw Id Module # Class #                                                                      Module                                                  Location Fix By
4 13 -                                                                     
                                                                   acs-aem-commonsbundle-3.9.0.jar
com/.../util/CookieUtil.java 54

**Comment by justinedelson** [comment]
This is the responsibility of the caller to `addCookie`.
