### ISSUE TITLE
URL Redirection to Untrusted Site ('Open Redirect') (CWE ID 601

### ISSUE THREAD

**Issue by LambaSwati** [Adobe-Consulting-Services/acs-aem-commons#1127]
Description A web application accepts a untrusted input that specifies a link to an external site, and uses that link to generate a redirect.  This enables phishing attacks.

Instances found via Static Scan
Flaw Id Module # Class
Flaw Id Module # Class # Module Location Fix By
47 8 - JS files within acsaem-commonscontent-3.9.0.zip
/jcr_root/.../clientlibs/js/app.js 59 6/5/11
45 12 - JS files within acsaem-commonscontent-3.9.0.zip
/jcr_root/.../clientlibs/js/app.js 115

**Comment by justinedelson** [comment]
That's not how these files work. The location is generated to an internal site.
