### ISSUE TITLE
Environment indicator doesn't work on 6.3

### ISSUE THREAD

**Issue by heervisscher** [Adobe-Consulting-Services/acs-aem-commons#1136]
The title of the environment indicator doesn't work on 6.3 (haven't tried in 6.2)
It does work during pageload, then it reverts back to the normal page-title.

**Comment by davidjgonzalez** [comment]
I think this unmerged fix is a/the fix: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/842

It’s a bit hacky - open to cleaner fixes.
