### ISSUE TITLE
Unable to get component of class 'interface org.apache.sling.rewriter.Transformer' with type 'versioned-clientlibs'

### ISSUE THREAD

**Issue by joemaffia** [Adobe-Consulting-Services/acs-aem-commons#1141]
1. Deploy a custom config for com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl
[com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl.txt](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1387039/com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl.txt)
2. Restart AEM Publish
3. Website goes down with following error [error.log](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1387037/error.log)
4. Restart ACS Common bundle
5. Restart Adobe Granite UI Clientlibs com.adobe.granite.ui.clientlibs
6. Website is up again

**Comment by justinedelson** [comment]
The most common cause for this message is that the bundle is not started. The log you supplied doesn't show the entire startup sequence, so it isn't possible to see if that was the case.

**Comment by joemaffia** [comment]
All the bundles were all started fine...

**Comment by justinedelson** [comment]
In that case, there is nothing we can do in Commons about this. If the component is being provided and Sling can't find it, that isn't something we can impact here.

**Comment by RashidJorvee** [comment]
All bundles are active and I restarted the AEM but still, I am getting this error.  What could be the reason for this and how to fix it?
