### ISSUE TITLE
Page will not create version on activation if it contains link to itself

### ISSUE THREAD

**Issue by rwinterpacht** [Adobe-Consulting-Services/acs-aem-commons#1143]
We have a content page at a level in node structure which contains a nav component. This nav component has a link to itself, so sub-pages can use the nav content for their own nav. 

When the page is modified and activated, the reference provider shows the page as outdated and allows user to include as part of activation. When this is selected, the jcr:content for the page is activated, but then the subsequent page activation doesn't see it as modified, and no version is created for the activation. 

Ideally, the reference provider class can check if it's itself, and not prompt as a reference.

**Comment by justinedelson** [comment]
@rwinterpacht would another way of phrasing this be "the pages reference provider should not report the current page as a reference to itself"?

**Comment by justinedelson** [comment]
@rwinterpacht assuming the answer to my question is "yes", I created a fix for this.

**Comment by rwinterpacht** [comment]
@justinedelson the answer is yes. Thanks!
