### ISSUE TITLE
Context-Aware Configuration Tool

### ISSUE THREAD

**Issue by jmanuelbr** [Adobe-Consulting-Services/acs-aem-commons#1149]
It would be great to have a tool that allows users with certain privileges to manage Context-Aware Configurations: create, remove and modify the values in a nice Touch UI interface.

I am not sure if this is a feature that Adobe might be working on and will be available in next releases or it would worth implementing.

**Comment by davidjgonzalez** [comment]
Have you checked out http://wcm.io/caconfig/editor/usage.html ? It looks like it does exactly this?

**Comment by jmanuelbr** [comment]
@davidjgonzalez not quite. What @stefanseifert and their team implemented in pro!vision is a different approach, allowing caconfigs to be managed in the /content tree, which has some pros and cons, like ACS control over those resources which for some organisations might not be suitable. 

It is a nice tool but not actually the out-of-the-box functionality that ships with AEM 6.3, you can check the presentation from the laste adaptTo() conference https://www.youtube.com/watch?v=ZPIDwBqwZTM

Another question is the compatibility with AEM 6.2 since Context-Aware Configurations are only available since 6.3

[AEM 6.2 Javadoc](https://docs.adobe.com/docs/en/aem/6-2/develop/ref/javadoc/index-all.html)

[AEM 6.3 Javadoc](https://docs.adobe.com/docs/en/aem/6-3/develop/ref/javadoc/index-all.html)

**Comment by davidjgonzalez** [comment]
Ah - gotcha; TBH I haven’t use it but it looks nice.

As long as the feature doesn’t break 6.2 compat in the package the feature is fine - we can have features that build on 6.3 only func, as long as it doesn’t preclude the other features of commons from running on 6.2 — not sure if that was your question.

**Comment by jmanuelbr** [comment]
Yup, so my main concern is that in order to be compatible with 6.2 the following bundles would need to be installed as a dependency

[org.apache.sling.caconfig.api](https://mvnrepository.com/artifact/org.apache.sling/org.apache.sling.caconfig.api/1.1.0)
[org.apache.sling.caconfig.impl](https://mvnrepository.com/artifact/org.apache.sling/org.apache.sling.caconfig.impl/1.4.6)
[org.apache.sling.caconfig.spi](https://mvnrepository.com/artifact/org.apache.sling/org.apache.sling.caconfig.spi/1.3.2)

I am not sure if that goes against the policy of including new features to ACS Commons?

**Comment by justinedelson** [comment]
Can’t those dependencies be optional?

**Comment by justinedelson** [comment]
@jmanuelbr I don't think your assessment of the wcm.io utility is accurate. While the editor page is in /content, the configuration itself would be under /conf.

I don't think it would make sense to build something in ACS AEM Commons which duplicates functionality in wcm.io. If you have improvement suggestions for wcm.io, I'd suggest using their issue tracker.

**Comment by jmanuelbr** [comment]
Hi @justinedelson 
apologies if the approach I proposed wasn't clear. 

What I was aiming for is building a tool that extends the actual http://localhost:4502/libs/granite/configurations/content/view.html/conf from AEM 6.3, so users can not only manage permissions for specific configuration (this is provided out-of-the-box by AEM) but also modify values, create new ones, remove them, etc. - in a nutshell, have full control over Context-Aware Configurations - all controlled by this interface as opposed to the approach implemented in http://wcm.io/caconfig/editor/ which allows managing this from http://localhost:4502/sites.html/content which has some drawbacks as for instance setting ACL permissions to this configurations.

It would also be sensible to propose this implementation to https://github.com/wcm-io/wcm-io-caconfig if you consider this would be more an improvement of an existing tool than a different approach that could be implemented in ACS AEM Commons.

**Comment by justinedelson** [comment]
@jmanuelbr again, aside from the entry point, I don't see the difference. The ACLs are the same since the content being edited is the same. 

Regardless, I think that what you are describing makes sense (and it would be worth talking with the wcm.io team as to why they didn't do this approach), but I think it would be very challenging to do so in a way that was opt-in. Overlays (and I'm assuming what you are describing would be implemented as an overlay) are generally something we try to avoid since there is no way to turn them on or off via configuration. The rendercondition/featureflag approach used recently on #1106 works for individual buttons, but it is hard to see that working for a whole console in the way you are describing.

**Comment by jmanuelbr** [comment]
Fair enough @justinedelson , feel free to close this ticket :)
I will try to reach the people of wcm.io to discuss about it.

Thanks all for your time.
