### ISSUE TITLE
Audio component in 6.2 - rendition in http so not working / Mixed Content 

### ISSUE THREAD

**Issue by davenichols** [Adobe-Consulting-Services/acs-aem-commons#1152]
I wondered if anybody can please advise me.
 
I'm using the standard audio component in 6.2.  In author it works fine, but when published and viewing on the site I get a 'mixed content' error and it doesn't work - it provides the mixed content error.
 
All of the other DAM assets work fine and point to https when we link to them from AEM and the sling mappings are working, it just appears to be audio component is auto linking to http.
 
On the page this is the error, in case this helps, which seems to indicate AEM is referencing a rendition in http:
 
Mixed Content: The page at 'https://xxxxx.html' was loaded over HTTPS, but requested an insecure video 'http://xxxxx/content/dam/x/yyy/misc-/aaa.mp3/jcr:content/renditions/cq5dam.audio.aaa.mp3.html '. This content should also be served over HTTPS.

Is this an issue, or do I not have the configuration correct ? 
 
Thank you for your time,

**Comment by justinedelson** [comment]
The links created by the audio component are server-relative and don't contain the html extension (see https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/components/content/audio/audio.jsp#L38). Are you sure that you are using the ACS AEM Commons audio component without modification?

**Comment by davenichols** [comment]
Hi @justinedelson 

Thank you for the reply.  I have checked, and I believe that we are using the standard audio component from ACS without modification, and in looking at CRX DE I can find that line of code you are referring to.  I might be wrong, but I'm sure this worked before, and we have recently upgraded from the base 6.2 to 6.2 SP 6.  This might be a coincidence, but wanted to mention.

Sorry if this is an obvious question, but if the component is still picking up the renditions as http then could it be something to do with our sling mappings or anything else I could look into ?

Just to confirm again, when viewing as published on author it appears to work correctly.

Thank you again for your time.

**Comment by justinedelson** [comment]
What is the actual HTML being generated by the component?

**Comment by justinedelson** [comment]
@davenichols have you had a chance to look into this further?

**Comment by davenichols** [comment]
Hi @justinedelson ,

Thanks for the message and your time.  Sorry, this is still referencing http.  I was trying to reproduce this on a personal site, but couldn't.  Here is the URL with a podcast, which doesn't work as it's pointing to HTTP:

https://laboratory.pall.com/en/analytical-qc/hplc-and-uhplc-sample-preparation.html

If you look the HTML then I think it's producing this:

<audio id="cq-audio-html5-1511191972751" controls="controls">
        <source src="/content/dam/pall/laboratory/podcasts/pallHPLCcolumn9.mp3/jcr:content/renditions/cq5dam.audio.mp3hq.mp3" type="audio/mpeg">
        <source src="/content/dam/pall/laboratory/podcasts/pallHPLCcolumn9.mp3/jcr:content/renditions/cq5dam.audio.ogghq.ogg" type="audio/ogg">
        No audio available.
</audio>


Thanks again for your time.

**Comment by justinedelson** [comment]
The audio component is working fine. As you can see, it is outputting server-relative links.

The problem appears to be related to the webserver/dispatcher configuration and the mixed content is just the beginning of the problem. Here's what happens.

1. The browser makes a request for https://laboratory.pall.com/content/dam/pall/laboratory/podcasts/pallHPLCcolumn9.mp3/jcr:content/renditions/cq5dam.audio.mp3hq.mp3 (as referenced in the `<source>` tag.
2. The server returns a 301 redirect to http://laboratory.pall.com/content/dam/pall/laboratory/podcasts/pallHPLCcolumn9.mp3/jcr:content/renditions/cq5dam.audio.mp3hq.mp3.html (this is the source of the mixed content warning)
3. When a redirect is made to this URL, it is redirected (again with a 301) to https://laboratory.pall.com/content/dam/pall/laboratory/podcasts/pallHPLCcolumn9.mp3/jcr:content/renditions/cq5dam.audio.mp3hq.mp3.html
4. When a request is made to this URL, it is redirected (this time with a 302) to https://laboratory.pall.com/en/content/dam/pall/laboratory/podcasts/pallHPLCcolumn9.mp3/jcr:content/renditions/cq5dam.audio.mp3hq.mp3.html
5. That URL returns a 404

**Comment by justinedelson** [comment]
Closing as this isn't an issue in Commons and there's nothing we can do about it.

**Comment by davenichols** [comment]
OK, thanks @justinedelson for your time with this, sorry for the confusion.  I will look into the webserver/dispatcher configuration.
