### ISSUE TITLE
Select in Nested Multi-field is not stored correctly

### ISSUE THREAD

**Issue by bearcherian** [Adobe-Consulting-Services/acs-aem-commons#1154]
When a nested multi-field has a select widget, and the values are stored as JSON, the value is not stored correctly. Up to version 3.9.0, this worked fine. Starting in 3.10.0, this now stores the value under the key using the `*@Delete` name instead of the actual property name. 

For example, in the structure below, the JSON String should have a property `selectProperty`, but in 3.10.0 and 3.11.0 the value is stored as `selectProperty@Delete`

Sample widget structure:
```
<myMultifield
    jcr:primaryType="nt:unstructured"
    sling:resourceType="granite/ui/components/foundation/form/multifield"
    class="groupOfLinks-multifield"
    expand="{Boolean}true"
    fieldLabel="My Multifield">
    <field
        jcr:primaryType="nt:unstructured"
        sling:resourceType="granite/ui/components/foundation/form/fieldset"
        acs-commons-nested="JSON_STORE"
        name="./myMultifield">
        <layout
            jcr:primaryType="nt:unstructured"
            sling:resourceType="granite/ui/components/foundation/layouts/fixedcolumns"
            method="absolute"/>
        <items jcr:primaryType="nt:unstructured">
            <column
                jcr:primaryType="nt:unstructured"
                sling:resourceType="granite/ui/components/foundation/container">
                <items jcr:primaryType="nt:unstructured">
                    <linkStyle
                        jcr:primaryType="nt:unstructured"
                        sling:resourceType="granite/ui/components/foundation/form/select"
                        name="./selectProperty">
                        <items jcr:primaryType="nt:unstructured">
                            <option1
                                jcr:primaryType="nt:unstructured"
                                text="Option 1"
                                value="option1"/>
                            <option2
                                jcr:primaryType="nt:unstructured"
                                text="Option 2"
                                value="option2"/>    
                            <option3
                                jcr:primaryType="nt:unstructured"
                                text="Option 3"
                                value="option3"/>
                        </items>
                    </linkStyle>
                </items>
            </column>
        </items>
    </field>
</myMultifield>
```

**Comment by justinedelson** [comment]
Can you attach a sample component which illustrates this behavior?

**Comment by bearcherian** [comment]
Do you want a content package with the above dialog snippet, or just the XML content of the full dialog?

**Comment by justinedelson** [comment]
A content package which contains a component which has this in the dialog.

**Comment by tnebe** [comment]
Hi @bearcherian, observed the same but with using `granite/ui/components/coral/foundation/form/select`, JSON string for property name is not broken.
However, applying the value again when reopening the dialog does not work in both ways.

**Comment by henrykuijpers** [comment]
I have exactly the same issue. 

I'm using NODE_STORE, but when switching to JSON_STORE, I indeed also see the properties saved with the @Delete suffix.

**Comment by henrykuijpers** [comment]
The issue is with the following piece of code (that lives in touchui-composite-multifield-nodestore.js:
`            function fillValue($form, fieldSetName, $field, counter){
                var name, value;
                // for userpicker and richtext $field length is 2, excluding richtext
                if($field.length > 1 && !$field.parent().hasClass("richtext-container")) {
                    name = $($field[1]).attr("name");
                } else {
                    name = $field.attr("name");
                }`

It enters the if and picks the second field it can find, which is the @Delete one. 

I'm not very sure what this is trying to do, but I'd suggest doing something in the terms of:
Look at all fields and select the one not having a '@'-sign in the name (because that is most likely the field the user (developer) intended to fill.

**Comment by schoudry** [comment]
the following statement is problematic, causing regressions eg. in my tests it failed storing check box and select 

```
if($field.length > 1 && !$field.parent().hasClass("richtext-container") && !$field.parent().hasClass("coral-DatePicker")) {
                    name = $($field[1]).attr("name");
                }
```
agree with @henrykuijpers look for names not containing "@"

**Comment by schoudry** [comment]
Fix in PR https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1182
