### ISSUE TITLE
Audit Log Search: Incorrect logs filtration - date casting issue

### ISSUE THREAD

**Issue by DaryaNikiforova** [Adobe-Consulting-Services/acs-aem-commons#1158]
Hello,

While using Audit Log Search module I faced with the issue that filtration by date criteria hided some log entries which had to be included in the query result.

Here is test data:

1.  I have log entry node that page was created with [cq:time] = "2017-11-01T15:01:43.751+03:00"

2.  Here is the http query -  http://localhost:4502/etc/acs-commons/audit-log-search/_jcr_content.auditlogsearch.json?contentRoot=%2Fcontent&includeChildren=true&type=&user=&**startDate=2017-10-31T01%3A00&endDate=2017-11-01T23%3A00**&order=%5Bcq%3Atime%5D+DESC&limit=10

3. After data casting date part will be looked as following - "SELECT * FROM [cq:AuditEvent] AS s WHERE [cq:time] > CAST('2017-11-01T01:00:00.000Z' AS DATE) AND [cq:time] < CAST('2017-11-01T11:00:00.000Z' AS DATE)", **but the correct one for this case is** "SELECT * FROM [cq:AuditEvent] AS s WHERE [cq:time] > CAST('2017-10-31T01:00:00.000Z' AS DATE) AND [cq:time] < CAST('2017-11-01T23:00:00.000Z' AS DATE)"

As a result my entry is not in the selection :( The issue is in patterns:

	private static final SimpleDateFormat HTML5_DATETIME_FORMAT = new SimpleDateFormat("yyyy-MM-dd'T'hh:mm");
	private static final SimpleDateFormat QUERY_DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd'T'hh:mm:ss");

According to https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html , hh is 12-hour format, so the assumption the mistake is here.

**Comment by justinedelson** [comment]
Thanks for catching this! Very well spotted.

**Comment by DaryaNikiforova** [comment]
Thank you a lot for the help with this issue 👍
