### ISSUE TITLE
Custom class attribute breaks data loading for touchui composite multifield

### ISSUE THREAD

**Issue by victor994** [Adobe-Consulting-Services/acs-aem-commons#1160]
According to the CoralUi 2 [documentation](https://docs.adobe.com/docs/en/aem/6-3/develop/ref/granite-ui/api/jcr_root/libs/granite/ui/components/foundation/form/fieldset/index.html), the widget /libs/granite/ui/components/foundation/form/fieldset should support class attribute. But adding class attribute will break the data loading for touchui composite multifield.

**Comment by justinedelson** [comment]
thanks for fixing this!
