### ISSUE TITLE
RTE (used in multifield) is not showing the previously stored content when edit the component.

### ISSUE THREAD

**Issue by anshukhare** [Adobe-Consulting-Services/acs-aem-commons#1162]
I have used one RTE inside a multifield in touchUI in AEM 6.3. it is not retaining the values in dialog when reopen for editing.

please suggest a solution.

**Comment by tnebe** [comment]
Observing the same when using selectbox with `granite/ui/components/coral/foundation/form/select` withing ACS AEM commons multifield

**Comment by schoudry** [comment]
@anshukhare can you attach the dialog xml
