### ISSUE TITLE
OSGI:Config Can Not Auto Bind Bundle On AEM 6.3

### ISSUE THREAD

**Issue by longerZ** [Adobe-Consulting-Services/acs-aem-commons#1163]
Regarding the Shared Component Properties, there are two osgi config.

- com.adobe.acs.commons.wcm.impl.PageRootProviderImpl

- com.adobe.acs.commons.wcm.properties.shared.impl.SharedComponentPropertiesImpl

But on Felix config console, there is no Configuration Binding info, hence the feature not work.

The code use org.apache.felix.scr.annotations.Component annotation, but on AEM 6.3 recommend that use the org.osgi.service.component.annotations.Component, in this case no bundle binding issue.

**Comment by justinedelson** [comment]
@longerZ the Configuration Binding is optional in current versions of ConfigAdmin. If the "feature not work" it would not be related to Configuration Binding.

While updating to the standard components would be a good thing to do, it is a lot of work with very little value at this point. As always, pull requests are welcome.

**Comment by nikhil24393** [comment]
For Osgi configuration and reading it's values visit : 
https://aemsimplifiedbynikhil.wordpress.com/2018/07/30/creating-and-reading-osgi-configuration-values-for-adobe-experience-manager-6-3/
