### ISSUE TITLE
HTTPCache : JCR storage handler

### ISSUE THREAD

**Issue by Sc0rpic0m** [Adobe-Consulting-Services/acs-aem-commons#1164]
Hi! I am quite new here, but would like to take part of this awesome project.

I wanted to contribute by developing a JCR storage handler for the HTTP cache.

Just to prevent me from doing work thats already done, is somebody already working on this?
My idea was the following: 

-Have the storage work under 1 root node (configureable through OSGI config)
-Have then bucket nodes under this root node (like a hashmap) that comes from the hashcode in the cachekey.
-Have the bucket nodes go a few levels deep, since you dont want all buckets under 1 node, this might cause storage performance issues. So for instance if you have the hashcode  12345678910:

rootNode / 123456 / 078910 / entrynode1

The breakpoint to split can then be configureable through OSGI config.

To retrieve a node, it would be like a hashmap, so loop all the nodes under a bucket and perform equals on the cachekey. The cachekey would have extend Serializeable.

What do you guys think?

**Comment by davidjgonzalez** [comment]
@Sc0rpic0m no one is working on this!

Its been a while since i looked at the code; but sounds like a good approach!  Thoughts around clearing the cache? Would the cache contents be deny all and only accessible via a service user?

@Sivaramvt thoughts on the approach?

**Comment by Sc0rpic0m** [comment]
Cheers for the reply!

Clearing the cache would be as follows: 

Expiry: 
1: Put an expiry in (through OSGI config) as epoch timestamp or calendar object as property. 
2: The cache store also implement scheduler, and in the run method, fire off a service that performs a query on the root node, targeting nodes with the expiry time expired. 
3: delete these nodes.

Regular flush:
Same as regular hashmap, just fetch the node and delete is.


Just gotta think of an efficient way to delete the bucket nodes that don't contain contents after a cleanup or regular flush.

**Comment by Sc0rpic0m** [comment]
For cache contents: yes, would be deny all and only accessible via a service user indeed.

**Comment by Sc0rpic0m** [comment]
You can look at my fork here as well:

https://github.com/Sc0rpic0m/acs-aem-commons/tree/feature/httpcache-jcr-memstore/bundle/src/main/java/com/adobe/acs/commons/httpcache/store/jcr/impl 

Of course it's just WIP.

**Comment by davidjgonzalez** [comment]
@Sc0rpic0m could you make a PR to /develop and just put in the PR's title `[REVIEW ONLY] HTTP Cache JCR Store implementation` - its a bit easier to review and leave comments in the context of a PR. We can always close the PR. Thanks!

**Comment by davidjgonzalez** [comment]
This has been merged for the 6.0 compat line.
