### ISSUE TITLE
HtmlLibraryManagerImpl No library configured at /apps/clientlibs/granite/jquery

### ISSUE THREAD

**Issue by victorToledo3share** [Adobe-Consulting-Services/acs-aem-commons#1165]
Hi all, when we open a page we can see in our log file these WARN:

02.11.2017 16:18:12.398 *WARN* [0:0:0:0:0:0:0:1 [1509650292355] GET /en_US.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl No library configured at /apps/clientlibs/granite/jquery
02.11.2017 16:18:12.398 *WARN* [0:0:0:0:0:0:0:1 [1509650292355] GET /en_US.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl No library configured at /apps/clientlibs/granite/utils
02.11.2017 16:18:12.399 *WARN* [0:0:0:0:0:0:0:1 [1509650292355] GET /en_US.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl No library configured at /apps/clientlibs/granite/jquery/granite
 
If I uninstall ACS commons, the warns disappear
 
AEM 6.3.0 and ACS Commons 3.9.0
 
Thanks in advance

**Comment by justinedelson** [comment]
Please test with the latest release. If the issue persists, please provide a package which can be used to reproduce the issue.

**Comment by justinedelson** [comment]
I can't reproduce this. Here's what I did:

* Started AEM 6.3 GA in author mode.
* Installed acs-aem-commons-content-3.11.0.zip
* Loaded http://localhost:4502/content/we-retail/us/en.html

There are no WARN messages in the logs for HtmlLibraryManagerImpl

**Comment by justinedelson** [comment]
I did find some other warnings, just not these. See #1166

**Comment by justinedelson** [comment]
As discussed in AEM-Tech Slack, this is unrelated to Commons.
