### ISSUE TITLE
Value of datepicker of multifield won't load or set properly

### ISSUE THREAD

**Issue by victor994** [Adobe-Consulting-Services/acs-aem-commons#1167]
The ui fix for #896 is breaking datepicker as datepicker also has two children elements with name attrib. Like richtext field, the first name attrib is the right one.

**Comment by victor994** [comment]
this line. the logic will read the name attrib from the second field which is for typehint.

if($field.length > 1 && !$field.parent().hasClass("richtext-container")) {
                name = $($field[1]).attr("name");
            }

**Comment by justinedelson** [comment]
PR merged
