### ISSUE TITLE
Add Permission Sensitive Cache Servlet

### ISSUE THREAD

**Issue by kaushalmall** [Adobe-Consulting-Services/acs-aem-commons#1175]
Currently, this code gets copied and pasted from one project to another and every developer seem to have their own version. Might be good to have one version in Commons that people can reuse. 

Idea is for this servlet to have two configurable properties 

- The servlet path
- The list of extensions to be removed from the URI so it resolves to a valid resource. 

Thanks @justinedelson for pointing this out.

**Comment by justinedelson** [comment]
PR has been merged
