### ISSUE TITLE
RoundRobin to return potentially negative index

### ISSUE THREAD

**Issue by mp911de** [Adobe-Consulting-Services/acs-aem-commons#1202]
[RoundRobin](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/f7424effb1fd68e8d494988fe74c009b4ccab4bb/bundle/src/main/java/com/adobe/acs/commons/functions/RoundRobin.java#L21) can return a negative index on integer overflow:

```java
AtomicInteger index = new AtomicInteger(Integer.MAX_VALUE);
int idx = index.getAndIncrement() % items.size();

-1 > idx == true
```

This can happen if `RoundRobin` was called `Integer.MAX_VALUE` times.

**Comment by justinedelson** [comment]
@badvision can you look into this?
