### ISSUE TITLE
Add source/Javadoc jars into maven repos

### ISSUE THREAD

**Issue by paul-bjorkstrand** [Adobe-Consulting-Services/acs-aem-commons#1215]
It would be nice if the bundle jar's source and/or javadoc were available in the maven repos (adobe, maven central, others?), that way we can get more IDE support for documentation.

**Comment by justinedelson** [comment]
As discussed in #1036, these are available on bintray (https://dl.bintray.com/acs/releases/) we just can't host them on repo.adobe.com.

**Comment by paul-bjorkstrand** [comment]
Apologies, I didn't catch that ticket in my search (before posting this one). I'll add Bintray into my repos list. I still think adding them into Maven Central would be a good idea as well, but I understand if it is not feasible.
