### ISSUE TITLE
Versioned clientlibs causes error log to be filled

### ISSUE THREAD

**Issue by royteeuwen** [Adobe-Consulting-Services/acs-aem-commons#1216]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3 SP1
* [ ] ACS AEM Commons Version: 3.12.1
* [ ] Reproducible on Latest? yes

### Expected Behavior

There should be no error log lines from the versioned clientlibs when opening ANY page in the author environment

### Actual Behavior

For every page that is opened on author, the following log lines are produced:

> 15.12.2017 17:34:40.248 *WARN* [10.45.0.1 [1513355680163] GET /MB/aem/start.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl No library configured at /apps/clientlibs/granite/typekit
15.12.2017 17:34:40.248 *WARN* [10.45.0.1 [1513355680163] GET /MB/aem/start.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl No library configured at /apps/clientlibs/granite/jquery
15.12.2017 17:34:40.248 *WARN* [10.45.0.1 [1513355680163] GET /MB/aem/start.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl No library configured at /apps/clientlibs/granite/utils
15.12.2017 17:34:40.248 *WARN* [10.45.0.1 [1513355680163] GET /MB/aem/start.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl No library configured at /apps/clientlibs/granite/jquery/granite
15.12.2017 17:34:40.248 *WARN* [10.45.0.1 [1513355680163] GET /MB/aem/start.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl No library configured at /apps/clientlibs/granite/moment
15.12.2017 17:34:40.249 *WARN* [10.45.0.1 [1513355680163] GET /MB/aem/start.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl No library configured at /apps/clientlibs/granite/coralui3
15.12.2017 17:34:40.249 *WARN* [10.45.0.1 [1513355680163] GET /MB/aem/start.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl No library configured at /apps/clientlibs/granite/uritemplate
15.12.2017 17:34:40.249 *WARN* [10.45.0.1 [1513355680163] GET /MB/aem/start.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl No library configured at /apps/clientlibs/granite/history
15.12.2017 17:34:40.249 *WARN* [10.45.0.1 [1513355680163] GET /MB/aem/start.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl No library configured at /apps/granite/ui/components/coral/foundation/clientlibs/foundation

The reason is that the clientlib is actually /etc.clientlibs/clientlibs/granite/uritemplate and for this the resourceResolver.getSearchPaths() is queried to search for the clientlib, but this returns an array in the form of [ '/apps/', '/libs/' ], and because /apps is first, that one will be looked up first, producing the warning from the HtmlLibraryManagerImpl that it doesn't exist

### Steps to Reproduce

Set up versioned clientlibs on author and open any author page (for example /aem/start.html)

### Fixing it

Sadly enough there is no public api available in AEM that allows to suppress the warnings, there is a method in the HtmlLibraryManagerImpl that does exactly what we want, allow to pass a boolean to suppress the warnings, but it isn't available in the api...

Else I would have proposed the following fix in VersionedClientlibsTransformerFactory, where only for the last search path available you will not suppress the warnings being outputted. Because /apps/ is the first search path by default, you always get the warnings first before the clientlibs are actually found int /libs

```
private HtmlLibrary getLibrary(LibraryType libraryType, String libraryPath, ResourceResolver resourceResolver) {
        HtmlLibrary htmlLibrary = null;
        if (libraryPath.startsWith(PROXY_PREFIX)) {
            final String relativePath = libraryPath.substring(PROXY_PREFIX.length());
            String[] searchPaths = resourceResolver.getSearchPath();
            for (int i = 0; i < searchPaths.length; i++) {
                final String prefix = searchPaths[i];
                final String absolutePath = prefix + relativePath;
                final boolean suppressWarnings = (i != searchPaths.length -1);
                htmlLibrary = htmlLibraryManager.getLibrary(libraryType, absolutePath, suppressWarnings);
                if (htmlLibrary != null) {
                    break;
                }
            }
        } else {
            htmlLibrary = htmlLibraryManager.getLibrary(libraryType, libraryPath);
        }
        return htmlLibrary;
    }
```

**Comment by justinedelson** [comment]
FWIW, this was originally worked around with a log filter, but then removed because that had a performance impact: https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/cb81e169efe9a9efa672d8e14d4839f6d26a90f6#diff-87012c484548d1e4ed5486dde75a5cb2

**Comment by royteeuwen** [comment]
Aha cool, didn't know! Was the performance impact that bug to add the logfilter? And is there another solution coming up? Or is the only workaround to separate the entire HtmlLibrarManagerImpl to a separate log file, potentially masking other problems.

No way to try and get it into the API of HtmlLibraryManager itself ;)?

**Comment by justinedelson** [comment]
yeah, the problem is that the TurboFilter is a drag on overall performance since it gets queried on every log call (which, as you can imagine, is a lot).

I also looked at using reflection to invoke the 3-argument method if it was available, but there were thread-safety issues with that (due to the need to call `Method.setAccessible` since this is a package-scope method.

I think it would be safe to change the log level of HtmlLibraryManagerImpl to ERROR.

**Comment by royteeuwen** [comment]
Thread safety as in when you would make it accessible and then unaccessible again? Is there a reason to make it unaccessible again? There is no real security risk, we just want to be able to supress the logging

**Comment by justinedelson** [comment]
I see what you mean, but I generally think if you call `setAccessible(true)` you should call `setAccessible(false)` as soon as possible. There was also the issue that the three argument method wasn't API and so liable to change without warning.

Thinking some more about the logging option, what if we added something to the MDC and then you could write a filtering expression as described here: https://sling.apache.org/documentation/development/logging.html#logback-groovy-fragment

**Comment by royteeuwen** [comment]
Looks interesting! The docs dont state where to place that logback configuration though, can you make that work through an osgi config or would it have to be created programatically or a jcr node or will it only work on file system, because that would be not so handy for installation

**Comment by henrykuijpers** [comment]
@justinedelson  Any update on this issue? It's continuously filling up our logs.

@royteeuwen did you find any fix/workaround for this in the meantime?

**Comment by justinedelson** [comment]
@royteeuwen sorry, missed your question above. the options for providing a config file are documented on the same page: https://sling.apache.org/documentation/development/logging.html#logback-config-fragment-support

@henrykuijpers I think the only workaround at present is to set the log level to ERROR. I've added this information to the log.
