### ISSUE TITLE
Many calls to undefined.2.json from touchui-configure-parsys-placeholder.js

### ISSUE THREAD

**Issue by szymonkrzysztyniak** [Adobe-Consulting-Services/acs-aem-commons#1230]
When opening the page with some parsys, there are a lot of calls to ../undefine.2.json when rolling over the page content (especially over a parsys). Calls comes from touchui-configure-parsys-placeholder.js code line 131 https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/28bf1ed1c8fd457dce2c80d00637a85717b6ada5/content/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/configure-parsys-placeholder/touchui-configure-parsys-placeholder.js#L131. 

For some reason method getDesignPath return "undefined" text instead of undefined object and the condition pass and sends the request to undefined.2.json. 

* [ ] AEM Version: 6.3.1.0
* [ ] ACS AEM Commons Version: 3.11.0
* [ ] Reproducible on Latest? yes

### Steps to Reproduce

1. Install acs-aem-commons-content-3.11.0.zip
2. Open any page with parsys
3. Open dev tools in browser - network tab
4. Roll over the page and hover over some parsys

### Expected Behavior

No calls to undefined.2.json

### Actual Behavior

Many calls to ../undefined.2.json

**Comment by szymonkrzysztyniak** [comment]
PR:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1234

**Comment by justinedelson** [comment]
Fixed by pull request. Thanks!
