### ISSUE TITLE
ACS AEM Commons Twitter Support Bundle is not working after AEM 6.3 upgradation from 6.1

### ISSUE THREAD

**Issue by manoj707** [Adobe-Consulting-Services/acs-aem-commons#1236]
## Required Information

* [] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _AEM 6.3______
* [ ] ACS AEM Commons Version: _____acs-aem-commons-content-3.14.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

I am in process of upgrading my AEM version for my client from AEM 6.1 to AEM 6.3 and installed acs-aem-commons-content-3.14.0.zip which further giving error on one bundle i.e. ACS AEM Commons Twitter Support Bundle. for following imported packages:
twitter4j,version=[3.0.5,4) -- Cannot be resolved
twitter4j.auth,version=[3.0.5,4) -- Cannot be resolved
twitter4j.conf,version=[3.0.5,4) -- Cannot be resolved
twitter4j.json,version=[3.0.5,4) -- Cannot be resolved

### Actual Behavior

I am in process of upgrading my AEM version for my client from AEM 6.1 to AEM 6.3 and installed acs-aem-commons-content-3.14.0.zip which further giving error on one bundle i.e. ACS AEM Commons Twitter Support Bundle. for following imported packages:
twitter4j,version=[3.0.5,4) -- Cannot be resolved
twitter4j.auth,version=[3.0.5,4) -- Cannot be resolved
twitter4j.conf,version=[3.0.5,4) -- Cannot be resolved
twitter4j.json,version=[3.0.5,4) -- Cannot be resolved

Please suggest to re-mediate it.

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by justinedelson** [comment]
Is the twitter4j bundle installed?

**Comment by justinedelson** [comment]
Assuming not. Please reopen if it is.

**Comment by ajaykpaul** [comment]
facing exactly same issue in AEM 6.4 with SP2 upgrade from 6.3
