### ISSUE TITLE
Multifield not working in page property in IE-11

### ISSUE THREAD

**Issue by ankurvashisht** [Adobe-Consulting-Services/acs-aem-commons#1246]
## Required Information

* [ ] AEM6., sp10
* [ ] 3.14.6
* [ ] yes

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

### Actual Behavior

The issue is with IE only, if I create an ACS commons multifield on my page property, It won't save the data.
![image](https://user-images.githubusercontent.com/16204204/35911105-da5d5694-0c1e-11e8-8b7b-e8c9cf58c43a.png)

When I check HTML DOM, I can see elements are getting created successfully.

![image](https://user-images.githubusercontent.com/16204204/35911206-2c236d06-0c1f-11e8-8087-7484ce9efb95.png)

But if I inspect request header, I cannot see the JSON parameter in this case "links"

![image](https://user-images.githubusercontent.com/16204204/35911387-b0ac9a48-0c1f-11e8-8fd9-503fb466c666.png)

### Steps to Reproduce

1) Create an ACS commons multified at page property level of any template.
2) Create a page using that template.
3) Edit the multifiled in the page property of the newly created page.
4) Click Save & Close.
5) Reopen the page property, And you can see data is not persisted.

**Comment by davidjgonzalez** [comment]
Have you tried the OOTB GraniteUI multifield?

https://helpx.adobe.com/experience-manager/6-3/sites/developing/using/reference-materials/granite-ui/api/jcr_root/libs/granite/ui/components/coral/foundation/form/multifield/index.html

**Comment by alexramos1** [comment]
I'm having a similar issue, except it's worse: multifield will not work at all (cannot add items) in Page Properties, regardless of browser (tested IE11 and Chrome).
