### ISSUE TITLE
Dispatcher TTL feature no longer works in AEM 6.2

### ISSUE THREAD

**Issue by andrewmkhoury** [Adobe-Consulting-Services/acs-aem-commons#1248]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: *AEM6.2GA*
* [X] ACS AEM Commons Version: 3.14.6
* [X] Reproducible on Latest? yes/no

## Bug Description
The Dispatcher TTL feature no longer works on AEM 6.2 due to a regression bug caused by the commit in #975.
 
https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/040365685114d14613f3553bb2d4d3144b09c03c

### Steps to Reproduce

Try using the ACS Commons TTL features on AEM6.2GA with ACS Commons 3.14.6.  It no longer works, this is due to the commit from #975.  If you install ACS Commons 3.8.2 to the instance instead then it works since the _deprecated_ "pattern" configuration property is used instead.

https://adobe-consulting-services.github.io/acs-aem-commons/features/dispatcher-ttl/index.html

**Comment by justinedelson** [comment]
@andrewmkhoury I can't reproduce this issue. Can you clarify what exact steps you used to reproduce? I tested the Max Age filter (on 6.2 GA w/ ACS AEM Commons 3.14.6) and see the Cache-Control header being set correctly:

    $ curl -H"Server-Agent: Communique-Dispatcher" -u admin:admin -v http://localhost:4502/content/geometrixx/en.html 2>&1 | grep Cache-Control
    < Cache-Control: max-age=60

Can you also provide the output of /system/console/status-httpservice ?

**Comment by davidjgonzalez** [comment]
@andrewmkhoury remember the dispatcher http request header must be present for the filter to process the request; this is often overlooked when testing directly against  Aem. Iirc this header requirement is customizable in the osgi service.

**Comment by justinedelson** [comment]
FWIW, the header requirement is not currently customizable, but it is easy to set when using curl (see example above).

**Comment by davidjgonzalez** [comment]
@andrewmkhoury any idea if this is still an issue?
