### ISSUE TITLE
I am trying to use the redirect Map feature in my project in AEM 6.3. I am using acs aem commons version #3.14.6. Issue i am facing is when i am trying to upload a text file having the redirect it is not uploading the file and in the logs  i am getting File upload Exception saying "*ERROR* [qtp1517652272-166] org.apache.sling.engine.impl.parameters.ParameterSupport parseMultiPartPost: Error parsing request org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found"

### ISSUE THREAD

**Issue by nthapl** [Adobe-Consulting-Services/acs-aem-commons#1249]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [ ] ACS AEM Commons Version: _____
* [ ] Reproducible on Latest? yes/no

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by justinedelson** [comment]
Please update this issue following the template. It is very difficult to process issues where the title is so long.

**Comment by justinedelson** [comment]
Once that is done, feel free to reopen.

**Comment by justinedelson** [comment]
Would also be useful to understand which browsers this occurs in.
