### ISSUE TITLE
Error Pages with CUG doesn't honor root page with errorpages defined

### ISSUE THREAD

**Issue by jamiecounsell** [Adobe-Consulting-Services/acs-aem-commons#1252]
* AEM version: 6.3, SP2 CFP
* AEM ACS v3.13.0
* Reproducible on latest: YES

### Expected Behavior

I have a site that is entirely behind SAML authentication, and a subset of the pages on the site need to be restricted by the user's group.

When using the ErrorPageHandler with AEM Closed User Groups, I would expect to be able to arrange the following structure:

![untitled drawing](https://user-images.githubusercontent.com/2321599/36158911-7b3e2f08-10ab-11e8-8990-4e53398a1a79.jpg)

By default, a page restricted by CUGs returns a 404 (to avoid exposing the existence of a page at that location), so I should be able to use the 404 page to display to users who are unable to see those sections. This means the 404 page needs to be customized to say "you can't see this content", which means I can't set the errorpages property on the Site Root, as I don't want legitimate 404s being caught by this.

### Actual Behavior

When a user who does not have access to Private Page 1 tries to access it, it gets a 404. However, the "first real parent" detected is the _parent_ page of the page I expect it to find looking for with the errorpages defined. This is because the ErrorPageHandlerImpl will start at the erroring page and crawl upward in the page tree. It skips the CUG root because it uses `resourceResolver.resolve(request, candidatePath)` which I believe will attempt to use the requesting user authorizable to retrieve the page. If the root page is protected using CUG, then the user does not have access and it will continue up the tree to the Site Root. 

As a result, I've created the following structure:

![untitled drawing 2](https://user-images.githubusercontent.com/2321599/36161072-c1ea3a64-10b0-11e8-8f8b-8c1fffffb102.jpg)

This is not ideal, since we have to define the closed user group setting multiple times (or have yet another parent page to wrap the child pages) and it leaves us with this page that everyone can access. 

What I've done is set a redirect on Private Root to the homepage, so no user will _see_ that page. This works, but is not ideal

### Possible Resolution

When crawling up the page tree looking for a new root page, check if (in order)
- The page exists (if not, continue, if yes, next step)
- The page has errorpages set (if yes, return, if no, next step)
- The user has access to the page (if not, continue, if yes, return)

### Steps to Reproduce

- Create the following page structure above (with error pages and CUGs configured)
- Attempt to reach a private page with a user who does not have access
- Receive default 404 error

**Comment by justinedelson** [comment]
@davidjgonzalez can you look at this? seems feasible if using a service user, but we'd have to ensure that the service user can still see the errorPages property even if the CUG was setup.

**Comment by jamiecounsell** [comment]
@justinedelson Thanks for the quick response! it's also reasonable if there was some documentation that the service user needs to be added to the whitelist of groups for the CUG page or that user needs to be explicitly granted read access to the errorpages root. I can't think of a way to guarantee that otherwise, as error pages can be anywhere and we can't predict their ACLs.

**Comment by davidjgonzalez** [comment]
@jamiecounsell not sure if youre married to setting this on the page via ./errorPages, but i believe if you setup the mapping in the osgi configuration for the error page handler using the `pages`property, you should be able to achieve permission agnostic mapping - or perhaps at least a stop-gap until we can update EPH. Based on the code [1] i looks permission-safe.

```
paths="[/content/geometrixx/en:errors,/content/geometrixx/fr:/content/geometrixx/fr/erruers/ ]"
```

Would have to check out a service user w CUGs, but assume since it'd be a "read" defined at the user level it should be preferred over pretty much any other ACL.

[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/errorpagehandler/impl/ErrorPageHandlerImpl.java#L365

**Comment by jamiecounsell** [comment]
@davidjgonzalez this looks like it'll work. I'll give this a shot. Thanks!
