### ISSUE TITLE
acs-aem-tools-bundle-livereload not started 

### ISSUE THREAD

**Issue by aleksap** [Adobe-Consulting-Services/acs-aem-commons#1257]
AEM Version 6.3 with SP2 (AEM 6.3.1)
ACS AEM Commons version 3.14.6.zip

So I have noticed that com.adobe.acs.acs-aem-tools-bundle-livereload is not starting and when I checked the logs I have noticed it requires com.day.cq.widget 5.5.0 while with SP1 on AEM 6.3 default version of com.day.cq.widget is 6.0.0. 

Error log shows: 

```
19.02.2018 15:56:55.258 *ERROR* [qtp1328618248-107] org.apache.felix.http.jetty %bundles.pluginTitle: Cannot start (org.osgi.framework.BundleException: Unable to resolve com.adobe.acs.acs-aem-tools-bundle-livereload [478](R 478.0): missing requirement [com.adobe.acs.acs-aem-tools-bundle-livereload [478](R 478.0)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.widget)(version>=5.5.0)(!(version>=6.0.0))) Unresolved requirements: [[com.adobe.acs.acs-aem-tools-bundle-livereload [478](R 478.0)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.widget)(version>=5.5.0)(!(version>=6.0.0)))])
org.osgi.framework.BundleException: Unable to resolve com.adobe.acs.acs-aem-tools-bundle-livereload [478](R 478.0): missing requirement [com.adobe.acs.acs-aem-tools-bundle-livereload [478](R 478.0)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.widget)(version>=5.5.0)(!(version>=6.0.0))) Unresolved requirements: [[com.adobe.acs.acs-aem-tools-bundle-livereload [478](R 478.0)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.widget)(version>=5.5.0)(!(version>=6.0.0)))]
```

Regards,
Alex

**Comment by davidjgonzalez** [comment]
This should be in the ACS AEM Tools project; that being said this is because you are not using the ACS Tools Min package OR you are not installing the LiveReload dependency bundles.

See: https://adobe-consulting-services.github.io/acs-aem-tools/features/live-reload/index.html

**Comment by ehimsi** [comment]
I have checked twice for both the acs as well as netty packages but still cannot get it to work on AEM 6.3.3.2.
