### ISSUE TITLE
SharedComponentPropertiesImpl cannot be configured directly in Apache Felix Web Console

### ISSUE THREAD

**Issue by puradawid** [Adobe-Consulting-Services/acs-aem-commons#1259]
My first "contribution" to ACS, hello ACSers!

## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3 SP1
* [ ] ACS AEM Commons Version: 3.14 and 3.14.7-SNAPSHOT
* [ ] Reproducible on Latest? yes

### Expected Behavior

`SharedComponentPropertiesImpl` should be available for configuration (it can be created through Felix Web Console).

### Actual Behavior

There is an error regarding to missing AD node in OCD metatype. I described this [problem already on StackOverflow](https://stackoverflow.com/questions/48873236/is-osgi-component-with-metatype-and-without-properties-illegal-state-in-scr). but not sure is it properly generalised.

### Steps to Reproduce

1. Install ACS Commons
2. Go to Felix OSGi Web Console, e.g. http://localhost:4502/system/console/configMgr
3. Create configuration for `SharedComponentPropertiesImpl`

### Clues

I was investigating this issue for some time. It is not critical problem since it Shared Component Properties feature can be enabled by installed configuration file into JCR. But I have to admit it makes really uncomfortable that this configuration is not visible automatically just since a moment of ACS installation.

The problem can be avoided by putting some meaningless property like Enable or something else but this might be misleading or just wrong.

**Comment by HitmanInWis** [comment]
Completely agree @puradawid.  Are you able to make the code changes and submit a PR?

**Comment by HitmanInWis** [comment]
@davidjgonzalez Please let me know if there's anything that needs to happen with this PR other than getting the unit tests written (which I'm planning on, just haven't gotten the time yet).

**Comment by justinedelson** [comment]
@HitmanInWis is there a pull request for this?

**Comment by HitmanInWis** [comment]
oh oops LOL I posted on the wrong task :(

No there is not a PR for this.

Deleted my previous comment.
