### ISSUE TITLE
	 	ACS AEM Commons Installation Failure

### ISSUE THREAD

**Issue by shubhaga** [Adobe-Consulting-Services/acs-aem-commons#1266]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.2 SP1 
* [ ] ACS AEM Commons Version:
Tried to install below versions of ACS AEM commons 
acs-aem-commons-content-3.9.0.zip
acs-aem-commons-content-3.14.6.zip
--

* [ ] Reproducible on Latest? yes/no
Yes, i have tested on windows, linux issue is coming, below is the stack trace [1].

ACS AEM Commons Twitter Support Bundlecom.adobe.acs.acs-aem-commons-bundle-twitter | 3.14.8 |   | Installed, is not getting active
twitter4j,version=[3.0.5,4) -- Cannot be resolved
twitter4j.auth,version=[3.0.5,4) -- Cannot be resolved
twitter4j.conf,version=[3.0.5,4) -- Cannot be resolved
twitter4j.json,version=[3.0.5,4) -- Cannot be resolved

[1]
23.02.2018 12:03:05.235 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.core.impl.tasks.BundleStartTask Could not start bundle com.adobe.acs.acs-aem-commons-bundle-twitter [470]. Reason: {}. Will retry.
org.osgi.framework.BundleException: Unable to resolve com.adobe.acs.acs-aem-commons-bundle-twitter [470](R 470.0): missing requirement [com.adobe.acs.acs-aem-commons-bundle-twitter [470](R 470.0)] osgi.wiring.package; (&(osgi.wiring.package=twitter4j)(version>=3.0.5)(!(version>=4.0.0))) Unresolved requirements: [[com.adobe.acs.acs-aem-commons-bundle-twitter [470](R 470.0)] osgi.wiring.package; (&(osgi.wiring.package=twitter4j)(version>=3.0.5)(!(version>=4.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:97)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:894)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:729)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:286)
	at java.lang.Thread.run(Thread.java:748)
23.02.2018 12:03:05.314 *INFO* [OsgiInstallerImpl] org.apache.sling.audit.osgi.installer Installed configuration com.adobe.acs.commons.wcm.impl.QrCodeServlet from resource TaskResource(url=jcrinstall:/apps/acs-commons/config.author/com.adobe.acs.commons.wcm.impl.QrCodeServlet, entity=config:com.adobe.acs.commons.wcm.impl.QrCodeServlet, state=INSTALL, attributes=[org.apache.sling.installer.api.tasks.ResourceTransformer=:26:, service.pid=com.adobe.acs.commons.wcm.impl.QrCodeServlet], digest=27ba19805d52e788ce7ee21d6f82137c)
23.02.2018 12:03:05.332 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.adobe.acs.commons.wcm.impl.QrCodeServlet)] org.apache.sling.servlets.resolver Service [ServletResourceProvider for Servlets at [/libs/acs-commons/components/utilities/qr-code/config/json.GET.servlet],5205, [org.apache.sling.spi.resource.provider.ResourceProvider]] ServiceEvent REGISTERED
23.02.2018 12:03:05.332 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.adobe.acs.commons.wcm.impl.QrCodeServlet)] com.adobe.acs.acs-aem-commons-bundle Service [com.adobe.acs.commons.wcm.impl.QrCodeServlet,5204, [javax.servlet.Servlet, javax.servlet.ServletConfig, java.io.Serializable]] ServiceEvent REGISTERED
23.02.2018 12:03:05.334 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.core.impl.tasks.BundleStartTask Could not start bundle com.adobe.acs.acs-aem-commons-bundle-twitter [470]. Reason: {}. Will retry.
org.osgi.framework.BundleException: Unable to resolve com.adobe.acs.acs-aem-commons-bundle-twitter [470](R 470.0): missing requirement [com.adobe.acs.acs-aem-commons-bundle-twitter [470](R 470.0)] osgi.wiring.package; (&(osgi.wiring.package=twitter4j)(version>=3.0.5)(!(version>=4.0.0))) Unresolved requirements: [[com.adobe.acs.acs-aem-commons-bundle-twitter [470](R 470.0)] osgi.wiring.package; (&(osgi.wiring.package=twitter4j)(version>=3.0.5)(!(version>=4.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:97)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:894)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:729)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:286)
	at java.lang.Thread.run(Thread.java:748)

### Expected Behavior

package should install
### Actual Behavior

not installing

### Steps to Reproduce

Deployed on Weblogic App server.
Uploaded & Installed cq-6.2.0-hotfix-12785-7.0.zip & restarted the server.
Uploaded & Installed AEM-6.2-Service-Pack-1-6.2.SP1.zip.
Uploaded & Installed acs-aem-commons-content-3.14.6.zip/acs-aem-commons-content-3.9.0.zip.

**Comment by saurabhsaxenajava** [comment]
@justinedelson Can you please review and fix this, this is blocker for one of the customer

**Comment by justinedelson** [comment]
Is the twitter4j bundle installed? Per https://adobe-consulting-services.github.io/acs-aem-commons/features/social/twitter/index.html this is a requirement.

**Comment by losharma** [comment]
@justinedelson 
Installing the twitter4j bundle fixed the issue at our end (Worked with **shubhaga** on this one).
Shouldn't the twitter4j bundle be installed as a part of the complete package?

We did share the twitter4j bundle with the customer as well, but seems they were also reporting other errors in the acs-aem-commons bundle like errors from sunmisc, amazonaws.

We asked the customer to raise an issue themselves, and here is the issue they created:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1267

**Comment by justinedelson** [comment]
@losharma If you don't want to install any 3rd party dependencies, you should use the "min" packages. See https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html
