### ISSUE TITLE
AEM 6.2 WAR installation ACS Common issue

### ISSUE THREAD

**Issue by lavishrathodlavish** [Adobe-Consulting-Services/acs-aem-commons#1267]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.2
* [ ] ACS AEM Commons Version: 3.9
* [ ] Reproducible on Latest? yes

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

We are trying to upgrade our systems with AEM 6.2 WAR file.
This is working properly on windows machine with AEM 6.2.jar file but when we are getting the same implemented on our DEV Server we are getting ACS Commons error with AEM 6.2WAR file.

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

Tried to install below versions of ACS AEM commons
acs-aem-commons-content-3.9.0.zip
acs-aem-commons-content-3.14.6.zip

With AEM - 6.2 War(Which was created after downloading AEM 6.2 zip file & converting it to war file)

But ACS AEM Commons Bundlecom.adobe.acs.acs-aem-commons-bundle & ACS AEM Commons Twitter Support Bundlecom.adobe.acs.acs-aem-commons-bundle-twitter bundles are not getting resolved(Active).

While replicating on call we found many error from sunmisc, amazonaws.
This issue is related to ACS common package and Adobe Consulting team will be the correct point of contact to answer the above raised concern.
Please raise the ticket at @[ https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/new ]@.
AEM is working fine, jar was correctly deployed
SP1 was perfectly installed
[ACS-3.14.8.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1751248/ACS-3.14.8.zip)

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by lavishrathodlavish** [comment]
Please find the txt file
[status-Bundles.txt](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1766495/status-Bundles.txt)

**Comment by justinedelson** [comment]
According to this text file, there are no issues. All of the errors for the acs-aem-commons bundle are for non-required packages, e.g. 

    ERROR: com.amazonaws.auth,version=[1.10,2) -- Cannot be resolved but is not required

Again, what specific error messages do you get when starting these bundles?

**Comment by justinedelson** [comment]
have not received any feedback in a month. closing
