### ISSUE TITLE
ACS Commons does not support CMYK Images

### ISSUE THREAD

**Issue by manhnguyen308** [Adobe-Consulting-Services/acs-aem-commons#1268]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.2 SP1
* [x] ACS AEM Commons Version: 3.9.0
* [x] Reproducible on Latest? yes

### Request summary

We are currently using ACS AEM Commons - Named Image Transformer Factory to transform our images to different resolution to fit our webpage. You can refer to the attach image.
We are customizing our page to view these images with different resolutions on our webpage. But we cannot see any images when browsing our webpage.
We Did some more analysis and found that the image is not rendering, because it uses the CMYK color space and not RGB, and Java Image IO does not support CMYK.
For more detail, you can refer in the attached log file.

Thanks and Best Regards,

### Actual Behavior

Getting error when we tried accessing image URL with the Image Transformer config. But without Image Transformer config, we can view the image.

### Steps to Reproduce

1. Upload 2 images from 141751 - CMYK images.zip to DAM.
2. Create an Image Transformer config from ACS AEM Commons - Named Image Transformer Factory at AEM Config Mgr. See detail from the image in Using image transformer.zip file.
3. Access the image by URL with Transform Image config: 
e.g. http://localhost:4502/content/dam/VLV-Halloween-982818.jpg.transform/cap-highres/image.jpg
You will see the error message.

4 (additional step). But when you access the image by URL without Transform Image config, the image can be loaded and viewed:
http://localhost:4502/content/dam/VLV-Halloween-982818.jpg

### Attached files

[141751 - CMYK images.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1761627/141751.-.CMYK.images.zip)
[Image Testing.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1761629/Image.Testing.zip)
[Using image transformer.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1761628/Using.image.transformer.zip)
[Images error.log](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1761686/Images.error.log)

**Comment by justinedelson** [comment]
If the Java ImageIO library doesn't support CMYK images, I'm not sure there's anything we can do about this. @davidjgonzalez should this just be documented as a limitation?

**Comment by manhnguyen308** [comment]
Can I know is there any way to detect an image is CMYK? Thanks
