### ISSUE TITLE
Enhancement: Page Refresh after Shared Component Properties updated

### ISSUE THREAD

**Issue by ichirital** [Adobe-Consulting-Services/acs-aem-commons#1269]
## Required Information

* [AEM 6.3 SP1 CFP2]
* [ACS AEM Commons Version 3.14.8]

### Expected Behavior

Using the ACS Commons Shared Component Properties feature for storing Header / Footer configuration. The shared properties are stored at /content/my-site/gb/en level and are being read properly in all pages that use said component.
The component's shared properties can be edited on any page in the hierarchy and after editing the shared (or global) properties dialog, the current page should refresh so that authors could see the outcome of this configuration without manually refreshing the page.

### Actual Behavior

After editing the shared (or global) properties dialog, the current page does not refresh so authors cannot see the outcome of this configuration without manually refreshing the page. A typical listener `afteredit="REFRESH_PAGE"` doesn’t seem to work since the properties are modified at a higher level than the page where editing is done. 

### Steps to Reproduce

Starting from a vanilla instance of AEM at the above version, install the demo packages available here: https://adobe-consulting-services.github.io/acs-aem-commons/features/shared-component-properties/index.html

Use the shared component properties on a page in /content/my-site/gb/en/abc/cde page for instance and after changing the shared properties, although they are stored as expected in /content/my-site/gb, the cde.html page does not refresh.

**Comment by ichirital** [comment]
@HitmanInWis I understand you might be able to help on this or potentially suggest if there is some way around that I’ve not identified yet?

**Comment by HitmanInWis** [comment]
Hi @ichirital thanks for reaching out!

We wrote the initial feature, and I'll be happy to add this enhancement to pour internal backlog, though I'm unsure how quickly we'll be able to get to it.  If you have access to engineers (or are one yourself) please feel free to submit a pull request addressing the issue.

One potential workaround to try is to ensure the node exists in the JCR for the component you are modifying from.  If the component is templated onto a page but without a node, this behavior can happen.  I believe if the node exists on the page (either by templating it in or by going to the standard config dialog and saving even if there are no configs to set) then the `afteredit="REFRESH_PAGE"` setting will work.

**Comment by ichirital** [comment]
Hi @HitmanInWis, I would appreciate if you could add it to the backlog. Thank you!

**Comment by HitmanInWis** [comment]
Added!  However, if anyone else sees this and wishes to make a contribution before we get to it, please feel free!
