### ISSUE TITLE
cq-msm-lockable on composite multifield

### ISSUE THREAD

**Issue by FrankDeGrootIsobar** [Adobe-Consulting-Services/acs-aem-commons#1271]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM6.2, CFP10
* [ ] ACS AEM Commons Version: ACS 3.11
* [ ] Reproducible on Latest? yes (3.14.8)

### Expected Behavior
a composite multifield has its cq-msm-lockable property set on the fieldset. 
1) the chain icon should appear to the right of the fieldset as it does on non-composite multifields
2) break the inheritance on this multifield, then populate the multifield with some values. These are stored as either a String[] of json strings or as subnodes. Re-establish inheritance. The current values of the fields in the fieldset should still resemble the values given.  

### Actual Behavior
1) the chain icon is added as the last item *in* the fieldset, rather than outside of the fieldset
2) break the inheritance on this multifield, then populate the multifield with some values. Re-establish inheritance. In the case of a json-based multifield, the entire value of the json property is copied into the first field of each fieldset. In the case of a node-based fieldset, a string [Object] is copied into the first field of each fieldset.

### Steps to Reproduce
add the following to a dialog:
```
<multifield
        jcr:primaryType="nt:unstructured"
        sling:resourceType="granite/ui/components/foundation/form/multifield"
        fieldLabel="Multifield">
    <field
            jcr:primaryType="nt:unstructured"
            sling:resourceType="granite/ui/components/foundation/form/fieldset"
            acs-commons-nested=""
            cq-msm-lockable="multifield-value"
            name="./multifield-value">
        <items jcr:primaryType="nt:unstructured">
            <column
                    jcr:primaryType="nt:unstructured"
                    sling:resourceType="granite/ui/components/foundation/container">
                <items jcr:primaryType="nt:unstructured">
                    <text
                            jcr:primaryType="nt:unstructured"
                            sling:resourceType="granite/ui/components/foundation/form/textfield"
                            fieldLabel="Text"
                            name="./text"/>
                    <value
                            jcr:primaryType="nt:unstructured"
                            sling:resourceType="granite/ui/components/foundation/form/numberfield"
                            fieldLabel="Value"
                            name="./value"/>
                </items>
            </column>
        </items>
    </field>
</multifield>
```
- open the dialog from a livecopy page
- note the location of the chain icon
- click the chain icon to break inheritance
- populate the multifield
- save
- reopen the dialog
- click the chain icon to re-establish inheritance
- note the contents of the "text" fields

**Comment by ssharma1logitech** [comment]
But this is a valid issue
