### ISSUE TITLE
Documentation - Asset Import Process Using Manage Control Process (MCP)

### ISSUE THREAD

**Issue by ksurendra** [Adobe-Consulting-Services/acs-aem-commons#1281]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3x
* [ ] ACS AEM Commons Version: 3.10.0
* [ ] Reproducible on Latest? No.

# Asset Import Process
AEM has several options to import assets using spreadsheets. Adobe Consulting Services maintains and releases a set of tools called as ACS Commons. Manage Control Process (MCP) is a part of the ACS Commons tools. This document details the usage of MCP to import assets into AEM.

![alt text][overview-of-mcp-asset-import-process]

## Spreadsheet Formats
MCP requires the input spreadsheet to be in a certain format and column header names. These headers are picked and while creating the asset, data in these columns are used as metadata for that specific asset.

### Required columns headers
1. Source – defies where the file will be downloaded from. Should be full url.
2. Original – Name of the original asset name.
3. Rendition – Optional. If we provide a rendition that is filled in and an original; Then it looks for the asset with the name in the same target folder, and then added as renditions to that asset.

    Note: The provided spreadsheet by SiriusXM team had the column “Image Type”. This is used in 2 ways. 1) The rendition’s name is the “Image Type”. If we have data filled in the original column, that means these are renditions and use the value from “image type” column as the name of the rendition. 2) The Image Type column is copied and renamed as “sxm:image-type” to be used as metadata for master/original assets.

4. Target – Takes target folder where the asset must be in AEM. Takes Target as folder name, takes files name from the url. And uploads to the AEM.

### Optional fields
Note: Columns header with “:” in the name – if we see a property like “abc:” (where "abc' is a custom namespace) or “dam:” or “jcr:” we will import this metadata as is in the system to the asset. And store that on the asset. But w will do that only if it is ORGINAILS. Renditions do not get metadata in AEM. So these can be blank for Renditions.

* abc:category – The Category asset belongs to. In AEM these are saved as full tags i.e., abc:shows/sports/nfl but the spreadsheet has these values in 2 separate columns viz., “category” and “channel”. There is another tab in the spreadsheet that is used as a lookup to build this full tag.

  **Note**: Refer to Lookup in spreadsheet in Appendix section of this document. 

* abc:channel – the Channel asset belongs to. In AEM these are saved as full tags i.e., abc:shows/music/dance/9145 but the spreadsheet has these values in 2 separate columns viz., “category” and “channel”. There is another tab in the spreadsheet that is used as a lookup to build this full tag.

  **Note**: Refer to Lookup in spreadsheet in Appendix section of this document.

* dc:title – AEM uses this as name of the asset to display on the AEM UI

* dc:description – Description of the Asset

* jcr:title - title of the asset 

### Ignored fields
Not all columns from the spreadsheet are read by MCP. Some of them will be ignored. A few examples of columsn that ususally appear in spreadshets are:

* Name – name of the file. Is ignored by code
* Category – Ignored
* Channel - Ignored

After you have the spreadsheets in the required formats, move to the next step to use these spreadsheets in MCP.

## Using Manage Control Process(MCP)

Note: The user must be in AEM's "Administration" group to access and run MCP. 

### Steps
1. In AEM, go to Tools > ACS AEM Commons > Manage Control Process

![alt text][mcp-choose-from-acscommons]

2. Choose "Start Process"

![alt text][mcp-choose-start-process]

3. Choose the "Asset Ingestor" process
![alt text][mcp-choose-process]

4. Options and Upload the cleaned spreadsheet
![alt text][mcp-asset-ingestor]

 * Mandatory:
   * Source: Source folder for content ingestion
   * Target JCR Folder: Base folder for ingestion
   * Ignore folders: List of folder names to be ignored
   * Ignore files: List of file names to ignore
   * Ignore extensions: List of extensions to ignore
   * Minimum size: Mimimum size of the asset to imported in bytes. Defaults to 1024. 0=none
   * Maximum size: Maximum size of any assets that is imported. Defaults to 1073741824. 0=none

 * Optional:
   * Existing action:
     * Replace
     * Skip
     * Version

## Reports
Every run provides a report both on the Manage Control Process ui and spreadsheets. Below are some screenshots of the report spreadsheets.

* Sample Report - Manage Control Process
![alt text][mcp-sample-report-ui]

* Sample Report - Spreadsheet:
![alt text][mcp-sample-report-spreadsheet]

### Links
[mcp-sample-report-spreadsheet]: https://user-images.githubusercontent.com/902972/37531950-a8f07a00-290b-11e8-9e96-2b320e39d63c.png "Sample report from spreadsheet"

[mcp-asset-ingestor]: https://user-images.githubusercontent.com/902972/37531951-a914c8d8-290b-11e8-9142-035fb3f470d7.png "Options and upload spreadsheet"

[mcp-choose-process]: https://user-images.githubusercontent.com/902972/37531952-a936a002-290b-11e8-8483-2c519471d153.png "Choose Asset Ingestor Process"

[mcp-choose-start-process]: https://user-images.githubusercontent.com/902972/37531953-a9580418-290b-11e8-84bc-c62870bc1c3e.png "Choose Start Process"

[mcp-choose-from-acscommons]: https://user-images.githubusercontent.com/902972/37531954-a97756ce-290b-11e8-89e2-9c1c6710157f.png "Find MCP Listed Under ACS Commons"

[mcp-sample-report-ui]: https://user-images.githubusercontent.com/902972/37531956-a9a83a00-290b-11e8-9904-183e12cd287a.png "Sample report from MCP UI"

[overview-of-mcp-asset-import-process]: https://user-images.githubusercontent.com/902972/37531987-b9de6c82-290b-11e8-8ab6-a6d8ddee727c.png "Overview Of MCP Asset Import Process"

**Comment by badvision** [comment]
Excellent work!  I'll start getting this into the documentation project within the next week.

**Comment by justinedelson** [comment]
I'm confused on what this issue is intended to do. Did you intend to create a pull request in the https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/ project?

**Comment by badvision** [comment]
Incorporated and edited the documentation.  Thanks @ksurendra !
