### ISSUE TITLE
Documentation - Summary of all Processes in Manage Control Process (MCP)

### ISSUE THREAD

**Issue by ksurendra** [Adobe-Consulting-Services/acs-aem-commons#1282]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3x
* [ ] ACS AEM Commons Version: 3.14.10
* [ ] Reproducible on Latest? No

# Summary of all Processes in Manage Control Process (MCP)

Manage Control Process (MCP) packaged with ACS COmmons 3.14.10 has 10 different process. This document detials options in each of the processes. 

## 1. Asset Folder Creator
Allows to create folder structure.

![alt text][mcp-asset-folder-creator]

### Mandatory:
   * Excel file: Provide the .xlsx file that dfines the Asset Folder taxonomy
   * Folder Type: Choose folder type
     * Ordered Folder
     * Unordered Folder
   * Primary Creator: This will be used first and the Fallback will only be used if this fails to generate a valid Asset Folder definition.
     * Title and Node Name
     * Lowercase with Dashes
     * None
   * Fallback Creator: This is only invoked when the Primary cannot generate a valid Asset Folder definition. If this can also not generate a valid Asset Folder definition then the row will be skipped.
     * Title and Node Name
     * Lowercase with Dashes
     * None

## 2. Asset Ingestor
Allows to import assets into AEM using data from spreadsheets (pre-fromatted).

![alt text][mcp-asset-ingestor]

### Mandatory:
* Source: Source folder for content ingestion
* Target JCR Folder: Base folder for ingestion
* Ignore folders: List of folder names to be ignored
* Ignore files: List of file names to ignore
* Ignore extensions: List of extensions to ignore
* Minimum size: Mimimum size of the asset to imported in bytes. Defaults to 1024. 0=none
* Maximum size: Maximum size of any assets that is imported. Defaults to 1073741824. 0=none
* Optional:
   * Existing action:
     * Replace
     * Skip (default)
     * Version

## 3. Asset Report
Asset Report

![alt text][mcp-asset-report]

### Mandatory:
* Folder: Examines everying in this folder and all other subfolders below it
* Levels: Determines how many levels down are included in report summary -- all levels below are rolled up into that the level.
  ### Optional:
  * Include subassets: If checked, subassets are counted and evaluated as part of the total folder size. This takes additional time to process. (Checked by default)
  * Include versions: If checked, versions are counted and evaluated as part of the asset size. This takes additional time to process. (Checked by default)

## 4. Broken References
Broken References

![alt text][mcp-broken-references]

### Mandatory:
* Source page: Select page/site to be analyzed

### Optional:
* Property Regex: (Default **^/(etc|content)/.+**) Regular expression to detect properties containing references to Sling resources
* Exclude Properties: (Default **cq:allowedTemplates**) Comma-separated list of properties to ignore
  * Deep check in html: (Default **checked**) if checked, links will be exracted from html properties.
* Properties containing html: (Default **html**) Comma-separate list of properties containing html to extract links.

## 5. Deep Prune
Deep Prune

![alt text][mcp-deep-prune]

### Mandatory:
* Starting folder: Starting point for event removal
* Minimum purge level: (Default 3) Folder depth relative to start where purge will happen
* Passes: (Default 3) Number of passes to attempt removal
* Ignore: (Default **rep:policy,jobs,offloading**) Ignore nodes which have these names (comma-delimited)
* Batch size: (Default 10) Max number of operations to commit at a time
* Retries: (Default 3) Max number of retires per commit
* Retry delay: (Default 25) Delay between retries (in milliseconds)

### Optional:
* Delete Folders
  * All
  * Numeric
  * None
  * Hexadecimal
  * Skip job queues: (Default checked) If checked, stop job queues before and resume them after the purge process

## 6. Folder Relocator
Allows to move folders.

![alt text][mcp-folder-relocator]

### Mandatory:
* Source folder(s): One or more source folders must be provided. Multiple folders implies a move operation.
* Destination folder: Destination parent for move, or destination parent folder plus new name for rename

### Optional:
* Mode: Options..
  * Rename 
  * Move

## 7. Page Relocator
Allows to move pages between folders.

![alt text][mcp-page-relocator]

### Mandatory:
* Source Page: source page/site to be moved.
* Destinateion: Destination parent for move, or destination parent folder plus new name for rename.
 
### Optional:
* Max Rerences: (Default **-1**) Limit of how many page references to handle (max per page).
* Reference Search root: (Default **-1**) Root for reference searches. Depending on how indexes are set up, / might be the only working value on your system.
* Mode: (Default **Move**)
* Publish
  * Self Managed (Default **Checked**) or Queeu or None
  * Create Versions: (Default **Checked*) Create versions for anything being replicated
  * Update Status: (Default **Checked*) Updates status of content affected by this operation.
  * Extensice ACL Checks: (Default **UnChecked*) If checked, this evaluates ALL nodes. If not checked, it only evaluates pages.
  * Dry run: (Default **Checked*) This runs the ACL checks but doesn't do any actual work.

## 8. Process Cleanup
Process Cleanup

![alt text][mcp-process-cleanup]

### Mandatory:
* Age: (Default **7**) Minimum age (in days) to be considered for removal.

## 9. S3 Asset Ingestor
S3 Asset Ingestor

![alt text][mcp-s3-asset-ingestor]

### Mandatory:
* Bucket: S3 bucket name.
* Access Key: S3 access key.
* Secret Key: S3 secret key.
* S3 Base Path: S3 base path (prefix).
* Endpoint URL: Endpoint URL, leave blank for default. Used primarily for S3-compatible object-storage solutions.
* Target JCR Folder: (Default **/content/dam**) Base folder for ingestion.
* Ignore folders: (Default **tmp,ds_store,.ds_store,.thumbs,.appledouble**) List of folder names to be ignored.
* Ignore files: (Default **ds_store,.ds_store**) List of files names to be ignored.
* Ignore extensions: (Default **txt,html,css,js,thm,exe,db**) List of extensions to be ignored.
* Minimum size: Mimimum size of the asset to imported in bytes. Defaults to 1024. 0=none
* Maximum size: Maximum size of any assets that is imported. Defaults to 1073741824. 0=none

### Optional:
* Existing action:
     * Replace
     * Skip (default)
     * Version

## 10. Tag Creator
Allows to create Tags with inputs from speadsheets

![alt text][mcp-tag-creator]

### Mandatory:
* Excel file:
* Primary Converter: This will be used first and the Fallback will only be used if this fails to generate a valid Tag definition. 
  * Title and Node Name
  * Lowercase with Dashes
  * None
* Fallback Converter: This is only invoked when the Primary cannot generate a valid Tag definition. If this can also not genreate a valid Tag definition then the row will be skipped.
  * Title and Node Name
  * Lowercase with Dashes
  * None

## Links
[mcp-tag-creator]: https://user-images.githubusercontent.com/902972/37556626-c7fc3b80-29c6-11e8-816e-92c8470b0bb7.png "Tag Creator"
[mcp-s3-asset-ingestor]: https://user-images.githubusercontent.com/902972/37556628-c8174d58-29c6-11e8-94f1-c35dd827de41.png "S3 Asset Ingestor"
[mcp-process-cleanup]: https://user-images.githubusercontent.com/902972/37556629-c831c250-29c6-11e8-8a22-3008f9578b53.png "Process Cleanup"
[mcp-page-relocator]: https://user-images.githubusercontent.com/902972/37556630-c84dde7c-29c6-11e8-86b2-e3cb24145a17.png "Page Relocator"
[mcp-folder-relocator]: https://user-images.githubusercontent.com/902972/37556631-c879fc3c-29c6-11e8-9d30-d4303729cd4e.png "Folder Relocator"
[mcp-deep-prune]: https://user-images.githubusercontent.com/902972/37556632-c8967682-29c6-11e8-9351-f4550e194c17.png "Deep Prune"
[mcp-broken-references]: https://user-images.githubusercontent.com/902972/37556633-c8b15cea-29c6-11e8-912e-85c3f146baf5.png "Broken References"
[mcp-asset-folder-creator]: https://user-images.githubusercontent.com/902972/37556634-c8cf34e0-29c6-11e8-8f81-a28eb4c75f19.png "Asset Folder Creator"
[mcp-asset-ingestor]: https://user-images.githubusercontent.com/902972/37556635-c8e6e5e0-29c6-11e8-8bdc-cf7cfec9d60f.png "Asset Ingestor"
[mcp-asset-report]: https://user-images.githubusercontent.com/902972/37556773-9c12034a-29c8-11e8-88e9-957bdc41c58e.png "Asset Report"

**Comment by ksurendra** [comment]
There is already a [Tools page](https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp-tools/index.html) that lists the tools in MCP. I created this like a 1 page summary. If this is redundant, then please ignore this page.

**Comment by justinedelson** [comment]
I'm confused on what this issue is intended to do. Did you intend to create a pull request in the https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/ project?

**Comment by badvision** [comment]
Yes I believe he didn't see that project -- I'll move this over as a PR.  Thanks @ksurendra
