### ISSUE TITLE
Page and Design Reference Providers no longer Work for Publish Later Workflows AEM 6.3 

### ISSUE THREAD

**Issue by marto** [Adobe-Consulting-Services/acs-aem-commons#1283]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3 SP1 CFP2 (6.3.1.2)
* [x] ACS AEM Commons Version: 3.14.10
* [x] Reproducible on Latest? yes

### Expected Behavior

In AEM 6.3 the "ACS AEM Commons - Pages Reference Provider"  no longer functions when using the "Publish Later" functionality. It correctly works and picks up pages when activating pages immediately, however it does not work when using the "Publish Later" ability.

### Actual Behavior
The underlying workflow process (```com.day.cq.wcm.workflow.process.ReplicatePageProcess```) expects a workflow package that references only ```cq:Page``` or ```dam:Asset``` node types. The ```acs.commons.wcm.impl.PagesReferenceProvider``` lists reference to the pages underlying ```jcr:content``` node rather than the page itself (eg: ```/content/we-retail/ca/en/New2/jcr:content``` rather than ```/content/we-retail/ca/en/New2```) thus the ```ReplicatePageProcess``` drops those references and the linked pages are not published.

This sound and smell like an AEM bug rather than an ACS Commons bug, so I will also raise a daycare ticket, but perhaps it's a change in the API contract of ```com.day.cq.wcm.api.reference.ReferenceProvider```?

### Steps to Reproduce
* Create a page ```/content/we-retail/ca/en/New1```
* Create a page ```/content/we-retail/ca/en/New2```
* Make New1 link to New2
* Publish Later "New1", and select to also publish references (i.e. the reference to "New 2")

**Comment by davidjgonzalez** [comment]
Fixed via #1310
