### ISSUE TITLE
exposing jcr node to authors

### ISSUE THREAD

**Issue by ajaykpaul** [Adobe-Consulting-Services/acs-aem-commons#1285]
## Required Information

Any version AEM 6.3+ 
ACS version: Latest
* [x] Reproducible on Latest? feature

### Expected Behavior

there are instances where jcr node with jcr:primaryType: unstructured has to be exposed to the authors in siteadmin/tools to view the catalog data and edit if needed instead of quering to backend database

### Actual Behavior

jcr node can't be exposed. only cq:page and nt:folder can be seen in siteadmin/tools

steps:
1. login to crx/de and get the catalog data path. 
2. goto miscadmin and see the corresponding path. Only the folders with name nt:folders and cq: page will be listed.

**Comment by justinedelson** [comment]
This looks like something which would be specific to your application. I'm not sure what the "common" functionality is here. Touch UI consoles are generally very application-specific.

**Comment by royteeuwen** [comment]
I have the feeling that this is a bit of bad design? The author should have no knowledge of the internal structure of AEM, cq:Page and nt:folders are like file's and folders on a file system. Other nodes are just internal data that could be anything. You should make a sling:resourceType that allows the author to edit this in a nice Touch UI dialog, without having any knowledge of node / property structure

**Comment by justinedelson** [comment]
closing due to lack of feedback and confusing description
