### ISSUE TITLE
acs-commons-dispatcher-flush-service system user dispatcher flush ACLs for jcr:removeNode

### ISSUE THREAD

**Issue by johnnyyangyang** [Adobe-Consulting-Services/acs-aem-commons#1287]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.2 CFP 6
* [x] ACS AEM Commons Version: Latest
* [x] Reproducible on Latest? yes

### Expected Behavior

After deployment of ACS common package to a new instance, the acs-commons-dispatcher-flush-service system user should have the permission to remove the child nodes as it's required for delete the cache.

### Actual Behavior

The 'jcr:removeNode' permission does not get added into the root path '/'  for the system user acs-commons-dispatcher-flush-service after deployment latest of ACS acs-aem-commons-content-* package, even the permission jcr:removeNode is set in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/_rep_policy.xml

It might need the additional permission: jcr:removeChildNodes add into the _rep_policy.xml:

 <allow1
            jcr:primaryType="rep:GrantACE"
            rep:principalName="acs-commons-dispatcher-flush-service"
            rep:privileges="{Name}[jcr:read,crx:replicate,jcr:removeNode]"/>

### Steps to Reproduce

1. Deployment the latest ACS common content package
2. Check the acs-commons-dispatcher-flush-service permission in the user admin for the root path '/'

### Links

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/_rep_policy.xml

**Comment by davidjgonzalez** [comment]
@johnnyyangyang So i double checked this, and this appears to be fine with just the jcr:removeNode property.  Here's and install of ACS Commons 3.14.2 .. and the permissions are there. Im not sure if they show up on the /useradmin, but they are applied. 

What issues exactly are you seeing? Can you show via CRXDE Lite that the permission not applied?

![image](https://user-images.githubusercontent.com/1451868/38284315-9a07145a-3788-11e8-87de-784ed1e15490.png)

**Comment by johnnyyangyang** [comment]
Hi @davidjgonzalez, thanks for confirming. You are right, the jcr:removeNode is appearing after installing it into the new instance. 

It was not appearing for us, it's because we have installed the Old ACS common package which did not have the jcr:removeNode permission for the user acs-commons-dispatcher-flush-service and the AC handling for the package is merge_preserve so it will not add the permission jcr:removeNode to the existing policy. We just cleaned the permission for the user acs-commons-dispatcher-flush-service and reinstall the ACS Common package. It looks fine for us now and also re-testing the delete flush request it's passing the permission check.

Thanks, should close the ticker it possible.

Kind regards
Johnny Yang

**Comment by johnnyyangyang** [comment]
Hi @davidjgonzalez, the jcr:removeChildNodes does not require for deleting request. The  jcr:removeNode should be enough to processing the cache deleting. Please close the ticket.

private void checkDeletePermission(Session session, ReplicationActionType type, String path) throws AccessDeniedException {
    try {
        AccessControlManager acMgr = session.getAccessControlManager();
        if (type == ReplicationActionType.DELETE && session.nodeExists(path) && !acMgr.hasPrivileges(path, new Privilege[]{acMgr.privilegeFromName("{http://www.jcp.org/jcr/1.0}removeNode")})) {
            this.logger.warn("User {} has not enough privileges to delete {}", session.getUserID(), path);
            throw new AccessDeniedException(path);
        }
    } catch (RepositoryException var5) {
        this.logger.error("Error while evaluating user privileges.", var5);
        throw new AccessDeniedException(path);
    }
}

**Comment by davidjgonzalez** [comment]
Thanks for confirming!!!
