### ISSUE TITLE
Feature request: cq:template updater (TBD: Better name)

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Consulting-Services/acs-aem-commons#1293]
I have a container component that includes another component. I have added this component to the cq:template of the container component, so that the node will always be present (and will not result in a synthetic resource).

Later on, I change the container component to include an additional component. I add the definition to the cq:template of the container component, so that the node will always be present.

However, the existing instances of the container component, don't have the new component node under it and therefore still result in being synthetic resources.

It would be very nice if we can create a tool that finds all components of a specific sling:resourceType, and then apply the cq:template again. It would be nice if this tool would be configurable/reusable, such as the resource type updater for example.

**Comment by royteeuwen** [comment]
Hey @henrykuijpers ,

Why don't you just use Sling Pipes for this? This is meant to do migrations like this and is generic instead of this pretty custom use case

Greets,
Roy
