### ISSUE TITLE
acs commons error 

### ISSUE THREAD

**Issue by venkat0502** [Adobe-Consulting-Services/acs-aem-commons#1297]
## Required Information

* [6.2 ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: CFP10_______
* [3.6.2 ] ACS AEM Commons Version: _____
* [ ] Reproducible on Latest? yes/no

Hi , I am using AEM Ver 6.2 CFP10, Im migrating data from File Data store to S3 , and using a S3 connector of 1.4.8 I have one Author and 2 Publishers all of them running ( AEM Ver 6.2 CFP10) , I m getting the following errors . with regard to "acs commons".
16.03.2018 14:59:55.506 ERROR [192.150.10.201 [1521226795503] GET /bin/acs-commons/dam/custom-components.json HTTP/1.1] org.apache.sling.servlets.resolver.internal.SlingServletResolver Calling the error handler resulted in an error
java.lang.Error: Unresolved compilation problems:
Only a type can be imported. com.day.cq.commons.inherit.InheritanceValueMap resolves to a package
com.day.cq.commons.inherit.InheritanceValueMap cannot be resolved to a type
com.day.cq.commons.inherit.InheritanceValueMap cannot be resolved to a type

at org.apache.jsp.apps.sling.servlet.errorhandler._404_jsp.<init>(_404_jsp.java:10)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

### Expected Behavior

When we test the images the meta data error shouldn't occur.

### Actual Behavior

When we upload a image see the metadata errors.

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

I have attached the logs at the following location
https://files.acrobat.com/a/preview/a3d3ebbf-e884-4a2b-b534-cc34f131abe2
_Links to related assets, e.g. content packages containing test components_

**Comment by justinedelson** [comment]
This stack trace looks like a problem in your 404.jsp, not an issue with ACS AEM Commons.
