### ISSUE TITLE
Overlapping TTL configs result in multiple Cache-Control headers

### ISSUE THREAD

**Issue by ChestersGarage** [Adobe-Consulting-Services/acs-aem-commons#1298]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.1 SP2 CFP12
* [x] ACS AEM Commons Version: 2.14.0
* [x] Reproducible on Latest? yes

Using the Dispatcher TTL feature

### Expected Behavior

When I create multiple OSGI configurations with overlapping coverage in the regex, I expect the tool to use only one of the rules and set only one Cache-Control header and value.  And the rules should be subject to a predictable order, for example, as they are listed inside an osgi:orderedFolder, or "whichever is most specific".

### Actual Behavior

Each rule creates its own Cache-Control header, resulting in the cache behavior being subject to how the endpoint handles ambiguous cache headers.

### Steps to Reproduce

Create two or more rules which have overlapping scopes in the match pattern.  Create a page which matches both rules, and request that page.

#### Response headers
HTTP/1.1 200 OK
Date: Fri, 30 Mar 2018 22:20:20 GMT
**Cache-Control: max-age=21602
Cache-Control: max-age=3600**
X-Content-Type-Options: nosniff
Set-Cookie: cq-authoring-mode=TOUCH;Path=/;Expires=Fri, 06-Apr-2018 22:20:20 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Server: Jetty(9.2.9.v20150224)
X-Powered-By: Jetty(9.2.9.v20150224)

**Comment by justinedelson** [comment]
It seems simple enough to ensure that the Cache-Control filter only acts once per request. Ordering can (and should) be done with service.ranking. No need to invent a new capability for that.

**Comment by ChestersGarage** [comment]
Hello, can I request this to be back-ported to the 2.xx line?  We will be stuck on AEM 6.1 for the foreseeable future.  Thank you!
