### ISSUE TITLE
Documentation request - Manage Controlled Processes > Tag Creator - Add sample spreadsheet

### ISSUE THREAD

**Issue by ksurendra** [Adobe-Consulting-Services/acs-aem-commons#1308]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3
* [ ] ACS AEM Commons Version: 3.14.10
* [ ] Reproducible on Latest? yes

### Documentation Request

Can you include a sample spreadsheet that users can use to test the On the page where [Manage Controlled Processes > Tag Creator](https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp-tools/tag-creator/index.html) is listed.

### Sample
Attaching a sample 
[MCP-TagCrator-Sample-Import.txt](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1872821/MCP-TagCrator-Sample-Import.txt) . The attached file is a tab-delimited TXT file, open in Excel and save as CSV to be used in MCP > Tag Creator

**Comment by davidjgonzalez** [comment]
@ksurendra FYI - ACS Commons Tag Creator requires an XLSX file and NOT a CSV. The ACS Tools uses CSV - as ive been moving them over to ACS Commons, they're switching to XLSX as its a more robust format. CSV is, of course, trivial to save out as XLSX as well.

I've added a link to your sample file on this page: https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp-tools/tag-creator/index.html

Feel free to PR an update if you think it can be better placed, etc.
