### ISSUE TITLE
Reference Providers lacking section titles in TouchUI

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1311]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.2/ 6.3 / 6.4 (in TouchUI)
* [X] ACS AEM Commons Version: 3.14.2
* [X] Reproducible on Latest? yes

### Expected Behavior

When the ACS Commons reference providers (Pages/Design) are enabled, I expect to see sections in the referenced but unpublished dialogs listing these unreferenced resources. These lists should have titles to let me know that they are lists of Pages and Designs (respectively).

### Actual Behavior

There are no titles for the references pages or designs.

![image](https://user-images.githubusercontent.com/1451868/38288143-cfb0ef86-379c-11e8-9533-22c8791d0c27.png)

### Steps to Reproduce

1. Enable ACS Commons Pages Reference Providers
2. Start create a new page `/content/page-1`
3. Start create a new page `/content/page-2`
4. Create a component on page-1 that links to page 2 (ie a hyperlink in a text component)
5. From Site Admin; select page-1 > Manage Publication > Publish > Select the page-1 row > tap publish references
6. See that page-2 is listed by has no heading (heading area is blank)

### Links

It looks like the headings are set in references.jsp (there are 4 used across AEM)

Here's the file that drives the steps to produce above, but dont see a simple/clean way to inject a new key/pair (ie. "page" -> "All Pages") into the attrs map.

`/libs/cq/gui/components/common/admin/managepublication/references/references.jsp`

**Comment by justinedelson** [comment]
@davidjgonzalez I believe this has always been the way -- those headings weren't designed for extension.

**Comment by davidjgonzalez** [comment]
@kwin FYI ... 

Closing due to lack of support in AEM for this extension model. If a clever way to handle this is discovered, please re-open and fix via PR.

**Comment by kwin** [comment]
@davidjgonzalez Is this tracked in the Adobe bugtracker already? Otherwise I can create a Daycare ticket to request it.

**Comment by davidjgonzalez** [comment]
@kwin I’m not aware of this being logged as w Adobe

**Comment by kwin** [comment]
I reported now via Daycare ticket 164816.
