### ISSUE TITLE
"Query Packager Configuration" is missing when acs-aem-commons is installed on publish server

### ISSUE THREAD

**Issue by 95359646** [Adobe-Consulting-Services/acs-aem-commons#1312]
## Required Information

* [ ] AEM Version:  Adobe Experience Manager (6.3.1.0)
* [ ] ACS AEM Commons Version:  acs-aem-commons-content-3.14.12
* [ ] Reproducible on Latest? yes 

### Expected Behavior

 I installed the tool on publish server, it should have "Query Packager Configuration" functionality on query page,
I did the same on author server, it is fine and I can set "Query Packager Configuration" on query page.

### Actual Behavior

I cannot see "Query Packager Configuration" and Edit link on query page
 
### Steps to Reproduce

1.Install acs-aem-commons-content-3.14.12
2.create a new Page test of Template type “Query Packager”
3. on page test, "Query Packager Configuration" is missing on it

### Links

reference to https://adobe-consulting-services.github.io/acs-aem-commons/features/packagers/query-packager/index.html

**Comment by justinedelson** [comment]
This feature is documented as being intended to run on Author.

First step in the documentation is:

> Log in to AEM Author

**Comment by davidjgonzalez** [comment]
Added a small note about how to handle using Packages on AEM Publish on all 4 Packages docs pages (the main index and the 3 packagers)

**Comment by 95359646** [comment]
Thank you all!
