### ISSUE TITLE
Jacoco Powermock issue

### ISSUE THREAD

**Issue by prasadu-boggavarapu** [Adobe-Consulting-Services/acs-aem-commons#1321]
Hi Team,

We are working on AEM 6.3 Project.  We are using Jacoco plugin to generate the code coverage report.
Power mocks are ignored in the final report.
jacoco report has issues with Powermock. So, we need to do offline Instrumentation.

https://github.com/powermock/powermock/wiki/Code-coverage-with-JaCoCo
http://www.eclemma.org/jacoco/trunk/doc/offline.html

We need to do same in acs-aem-commons as well if we use power mocks.

I would like increase overall code coverage as well.

 AEM Version  6.3
ACS AEM Commons Version: Latest : 3.14.13-SNAPSHOT

Thanks & Regards,
Prasad.

**Comment by justinedelson** [comment]
I'm not sure what this point of creating this issue is. What exactly are you trying to address?

**Comment by prasadu-boggavarapu** [comment]
Sorry for the confusion.

If we use jacoco plugin, Junits created using powermock will be ignored in the final report if we run the code coverage report in sonar using the command like mvn sonar:sonar

So, we need to offline instrumentation. 
For EX: 

 
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <executions>

                    <execution>
                        <id>default-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>

                    <execution>
                        <id>jacoco-instrument</id>
                        <goals>
                            <goal>instrument</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>jacoco-restore-instrumented-classes</id>
                        <goals>
                            <goal>restore-instrumented-classes</goal>
                        </goals>
                    </execution>

                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>

                <configuration>
                    <excludes>
                        <exclude>*</exclude>
                    </excludes>
                </configuration>

            </plugin>

I am not sure where we are checking the code coverage report in acs-commons.

Thanks,
Prasad.

**Comment by justinedelson** [comment]
Sorry, I'm still not following your intention. Are you going to create a pull request to change how the coverage is calculated before sending to coveralls?

**Comment by prasadu-boggavarapu** [comment]
Ya. Exactly. 
I will raise a new pull request to to make sure that coverage is calculated for power mocks as well.
If Plugin works properly, it will create a new folder called site and code coverage report will be generated in that folder with the name. We can easily check code coverage report class wise and package wise.

And ,I  will try to add few more Junits to existing code.

Note:  I will test first in my local sonar server then only I will raise pull request.

![image](https://user-images.githubusercontent.com/14185519/38585812-8f7eb7ca-3d1b-11e8-82a0-6e40c05e8bfc.png)

**Comment by justinedelson** [comment]
OK. But again, we do not use Sonar for code coverage. We use Coveralls. We only use Sonar, via CodeClimate, for quality.

**Comment by justinedelson** [comment]
FYI - I tried implementing this. We'll see what coveralls says back. It did turn out to be a bit more complicated due to SCR generation.
