### ISSUE TITLE
PMD Failures

### ISSUE THREAD

**Issue by prasadu-boggavarapu** [Adobe-Consulting-Services/acs-aem-commons#1322]
Hi Team,

The latest version has PMD issues.
EX: The Logger variable declaration does not contain the static and final modifiers

Thanks,
Prasad.

**Comment by justinedelson** [comment]
do you have specific examples? note that we've generally been moving away from using PMD directly and instead using Codeclimate

**Comment by prasadu-boggavarapu** [comment]
Thanks for the response.

<?xml version="1.0" encoding="UTF-8"?>
<pmd version="5.3.2" timestamp="2018-04-10T23:00:50.097">
<file name="C:\Dev\Adobe\acs-commons\acs-aem-commons-master\bundle\src\main\java\com\adobe\acs\commons\dispatcher\impl\PermissionSensitiveCacheServlet.java">
<violation beginline="52" endline="52" begincolumn="26" endcolumn="93" rule="LoggerIsNotStaticFinal" ruleset="Java Logging" package="com.adobe.acs.commons.dispatcher.impl" class="PermissionSensitiveCacheServlet" variable="log" externalInfoUrl="http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/logging-java.html#LoggerIsNotStaticFinal" priority="2">
The Logger variable declaration does not contain the static and final modifiers
</violation>
</file>
<file name="C:\Dev\Adobe\acs-commons\acs-aem-commons-master\bundle\src\main\java\com\adobe\acs\commons\hc\impl\HealthCheckStatusEmailer.java">
<violation beginline="79" endline="79" begincolumn="26" endcolumn="86" rule="LoggerIsNotStaticFinal" ruleset="Java Logging" package="com.adobe.acs.commons.hc.impl" class="HealthCheckStatusEmailer" variable="log" externalInfoUrl="http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/logging-java.html#LoggerIsNotStaticFinal" priority="2">
The Logger variable declaration does not contain the static and final modifiers
</violation>
</file>
<file name="C:\Dev\Adobe\acs-commons\acs-aem-commons-master\bundle\src\main\java\com\adobe\acs\commons\ondeploy\impl\OnDeployExecutorImpl.java">
<violation beginline="79" endline="79" begincolumn="26" endcolumn="74" rule="LoggerIsNotStaticFinal" ruleset="Java Logging" package="com.adobe.acs.commons.ondeploy.impl" class="OnDeployExecutorImpl" variable="logger" externalInfoUrl="http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/logging-java.html#LoggerIsNotStaticFinal" priority="2">
The Logger variable declaration does not contain the static and final modifiers
</violation>
</file>
<file name="C:\Dev\Adobe\acs-commons\acs-aem-commons-master\bundle\src\main\java\com\adobe\acs\commons\ondeploy\scripts\OnDeployScriptBase.java">
<violation beginline="52" endline="52" begincolumn="28" endcolumn="76" rule="LoggerIsNotStaticFinal" ruleset="Java Logging" package="com.adobe.acs.commons.ondeploy.scripts" class="OnDeployScriptBase" variable="logger" externalInfoUrl="http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/logging-java.html#LoggerIsNotStaticFinal" priority="2">
The Logger variable declaration does not contain the static and final modifiers
</violation>
</file>
<file name="C:\Dev\Adobe\acs-commons\acs-aem-commons-master\bundle\src\main\java\com\adobe\acs\commons\users\impl\EnsureAuthorizableManagerImpl.java">
<violation beginline="52" endline="52" begincolumn="26" endcolumn="91" rule="LoggerIsNotStaticFinal" ruleset="Java Logging" package="com.adobe.acs.commons.users.impl" class="EnsureAuthorizableManagerImpl" variable="log" externalInfoUrl="http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/logging-java.html#LoggerIsNotStaticFinal" priority="2">
The Logger variable declaration does not contain the static and final modifiers
</violation>
</file>
</pmd>
