### ISSUE TITLE
WorkflowDelegationStep should use CA-Config

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#1325]
At the moment the WorkflowDelegationStep is using an InheritanceValueMap plus some other tricks to lookup the workflow which should be invoked. The code can be simplified if Sling CA-Config is used.

It should be changed in a way, that first CA-Config is checked; if it isn't used, as fallback the current mechanism should be used. In the logs it should be stated, that the fallback mechanism is used and that a switch to CA-Config is recommended.

The parameters of the lookup should be identical; that means, that the properties to the WorkflowDelegationStep should be usable in the CA-Config as they are today.

**Comment by justinedelson** [comment]
There was a pull request for this: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1225, but it never got polished enough. It'd be a good idea to revisit that.
