### ISSUE TITLE
Manage control process has JS errors and not able to start a process from the interface

### ISSUE THREAD

**Issue by sharath-madappa-icfi** [Adobe-Consulting-Services/acs-aem-commons#1330]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3 , AEM 6.3 Service Pack 1, AEM Cumulative Fix Pack 6.3.1.2
* [x] ACS AEM Commons Version: 3.14.4
* [x] Reproducible on Latest? yes [Tried with 3.14.12]

### Expected Behavior

* Navigate to <protocol>://<host>:<port>/etc/acs-commons/manage-controlled-processes.html
* The interface should render a start button
* Clicking on start should show a list of processes
* You should be able to select a process, fill the form and start the process

### Actual Behavior
* The interface does not have a start button

![image](https://user-images.githubusercontent.com/11866217/38729296-269a3b82-3f30-11e8-83a1-9cff8a58738a.png)

* Searching for "start" from dev tools in DOM and navigating to the button DOM element, internally activates some scroll listeners and gets the button to show up
![image](https://user-images.githubusercontent.com/11866217/38729385-7777d88e-3f30-11e8-8243-4234b25d83ce.png)

* Clicking on start then shows a list of processes. When you select one and switch to provide inputs, input form is not displayed. Clicking on start leads to an error.

![image](https://user-images.githubusercontent.com/11866217/38729634-384cdba4-3f31-11e8-8943-f5ba2e50e612.png)

![image](https://user-images.githubusercontent.com/11866217/38729654-4728465e-3f31-11e8-9188-cd8abeaf81ba.png)
 

### Steps to Reproduce

* Navigate to /etc/acs-commons/manage-controlled-processes.html and try to start a process.

### Links

NA

### Errors in JS

There are errors in the clientlib for this interface, none of the project specific JS files seem to be loading on this page to suspect collision from other custom code on the instance.

![image](https://user-images.githubusercontent.com/11866217/38729774-ac5be828-3f31-11e8-984a-c2b2bcb0f25f.png)

**Comment by justinedelson** [comment]
Actually, most of those exception are not coming from "project-specific JS files" but rather core product files. Have you tried to reproduce this issue with a vanilla 6.3.1.2 instance?

**Comment by sharath-madappa-icfi** [comment]
Works on vanilla instance, it was one of the custom clientlibs breaking this page. Will close this issue.
