### ISSUE TITLE
Remove 6.2 Support

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#1331]
With the release of AEM 6.4, I think we should drop 6.2 support. This will enable the use of various 6.3 features, most significantly Sling CA Config. Opening this issue to collect feedback.

**Comment by joerghoh** [comment]
+1

**Comment by badvision** [comment]
Might want to consider deprecating the Forms API (as well as other stuff that forces you to use JSP)

**Comment by badvision** [comment]
Also remove old Function declarations which are present in Java 8 and have been deprecated already.
