### ISSUE TITLE
Version 3.15 not available on Adobe Maven Repo

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#1333]
The most recent version 3.15 is not available on the Adobe Maven Repo.
Is there any reason why you don't publish to Maven Central directly (http://central.sonatype.org/pages/ossrh-guide.html)? Maybe that is easier/faster.

**Comment by justinedelson** [comment]
it's up now. using Maven Central is an interesting idea. I see they have relaxed the restriction on the transitive closure being all in Central (which was the original blocker to doing this). @badvision do you have any interest in following up on this?

**Comment by badvision** [comment]
Yes I do actually @justinedelson -- Just not this week.  Hopefully within the next couple of releases though I'll have some time.  Would we just deploy through bintray?

**Comment by justinedelson** [comment]
@badvision looks that way - https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/
