### ISSUE TITLE
Sling Rewriter Pipelines use deprecated generator / serializers

### ISSUE THREAD

**Issue by royteeuwen** [Adobe-Consulting-Services/acs-aem-commons#1340]
Hey guys,

When I have a look at the presentations (@justinedelson that would be your mastering of the sling rewriters) and the docs, I see that it states you should use the generatorType htmlparser and serializerType htmlwriter. But looking at the javadocs they seem to be deprecated:

https://helpx.adobe.com/experience-manager/6-3/sites/developing/using/reference-materials/javadoc/com/day/cq/rewriter/htmlparser/HtmlParser.html

Are there other generators / serializers that should be used now? There is a nasty bug in the htmlparser and I'm not sure what will happen when I create a daycare ticket for it, they might state its deprecated code...

Greets
Roy

**Comment by justinedelson** [comment]
@royteeuwen As near as I can tell, the `htmlparser` & `htmlwriter` components are not actually the classes in the JavaDoc, but are non-API classes.

**Comment by royteeuwen** [comment]
Hey @justinedelson ,

Can you please elaborate before closing? If i look at the source code it shows the following:

@Deprecated
@Component(factory="com.day.cq.rewriter.pipeline.Generator/htmlparser")
public class HtmlParser

and

@Component(label="CQ Rewriter HTML Parser Factory", description="HTML Parser Factory for CQ Reqriter", metatype=true, immediate=true)
@Service({GeneratorFactory.class})
@Properties({@org.apache.felix.scr.annotations.Property(name="pipeline.type", value={"htmlparser"}, propertyPrivate=true), @org.apache.felix.scr.annotations.Property(label="Additional Tags to process", name="htmlparser.processTags", cardinality=100, value={"HEAD", "/HEAD"}, description="Add additonal tags which need to be processed { default tags processed: A,IMG,AREA,FORM,BASE,LINK,SCRIPT,BODY,HEAD}"), @org.apache.felix.scr.annotations.Property(label="Preserve Camel Case", name="htmlparser.preserveCamelCase", boolValue={false}, description="Preserve Camel Casing of HTML Attributes")})
public class HtmlParserFactory
public class HtmlParserFactory
  implements GeneratorFactory
{
  private static String[] includedTags;
  private static boolean preserveCamelCase;
  private static final String INCLUDE_TAGS = "htmlparser.processTags";
  private static final String PRESERVE_CAMELCASE = "htmlparser.preserveCamelCase";
  
  public Generator createGenerator()
  {
    final HtmlParser parser = new HtmlParser(includedTags, preserveCamelCase);
    
    new Generator()
...

**Comment by justinedelson** [comment]
@royteeuwen please do not post proprietary source code in a public Github comment. I close this because it isn't an issue for ACS AEM Commons -- we don't reference either the deprecated or the non-deprecated HtmlParser classes.

But to answer your question, the `htmlparser` generator is referring to `com.day.cq.rewriter.processor.impl.HtmlParserFactory` (at least on AEM 6.4). You can see this by looking at the Services web console plugin and using the filter `(&(objectClass=org.apache.sling.rewriter.GeneratorFactory)(pipeline.type=htmlparser))`

**Comment by royteeuwen** [comment]
@justinedelson Okey, sorry, that was not what I was going for. Sorry if I made an infringement of licensed code.

Anyways, seeing as the HtmlParserFactory uses deprecated code (yes, even in AEM 6.4). What do you use for html parser if its not that one?

**Comment by justinedelson** [comment]
The documentation recommends to copy the default pipeline configuration and edit it to suit, so that would be whatever AEM uses by default. If that is deprecated, it would have to be fixed in AEM (or maybe the deprecation was incorrectly done).
