### ISSUE TITLE
Endless Loop in BrandPortalAgentFilter

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#1349]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: any
* [x] ACS AEM Commons Version: master
* [x] Reproducible on Latest? yes

### Expected Behavior

Should be able to create a `BrandPortalAgentFilter` instance when the `mpConfig` is not set.

### Actual Behavior

An endless loop is created

### Steps to Reproduce

I ran into this while writing a unit test for `ReplicateWithOptionsWorkflowProcess`. It looks like if the `mpConfig` property isn't set, the `BrandPortalAgentFilter` constructor never returns.

@davidjgonzalez not sure how big a deal this is, but wanted to document it.

**Comment by justinedelson** [comment]
To see this problem in action, use the branch at https://github.com/justinedelson/acs-aem-commons/tree/issue/checkstyle-for-tests and remove line 25 at https://github.com/justinedelson/acs-aem-commons/blob/issue/checkstyle-for-tests/bundle/src/test/resources/com/adobe/acs/commons/workflow/process/impl/ReplicateWithOptionsWorkflowProcessTest.json#L25. Then run `ReplicateWithOptionsWorkflowProcessTest`

**Comment by davidjgonzalez** [comment]
Fixed in 3.17.2
