### ISSUE TITLE
Audit Log Search - Cannot switch back to "Yes" after clicking "No" at "Include Children"

### ISSUE THREAD

**Issue by HKCRaymond** [Adobe-Consulting-Services/acs-aem-commons#1351]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.1 SP2 CFP13
* [ ] ACS AEM Commons Version: 2.14.0
* [ ] Reproducible on Latest? Yes

### Expected Behavior

After clicking the option "No" at the "Include Children" field, I should able to resume the option to "Yes"

### Actual Behavior

After clicking the option "No" at the "Include Children" field, I cannot switch back to "Yes"

### Steps to Reproduce

1. Click Tools > ACS AEM Commons > Audit Log Search
2. At the "Include Children?" field, select No
3. Then switch back to Yes

### Links
Nil

**Comment by badvision** [comment]
Thanks @davidding! 👍
