### ISSUE TITLE
Feature /Editable Configuration Grid

### ISSUE THREAD

**Issue by kalyanar** [Adobe-Consulting-Services/acs-aem-commons#136]
A configuration page to store all site specific configurations and a corresponding key lookup.
Rather than adding to page property, this can be leveraged for any site specific configs.
The configuration page can be created with a configuration template, with the properties dialog allowing us to configuring the columns of the configuration grid.
This is a project requirement. If this can be accepted, I shall add junit cases and create a PR
![screenshot 2014-02-28 00 05 40](https://f.cloud.github.com/assets/6203088/2286164/05089234-9fde-11e3-9bea-975a240389f2.png)

**Comment by davidjgonzalez** [comment]
ClassicUI and closed per convos in #144
