### ISSUE TITLE
Bulk publishing

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1361]
As a business user I would like a simple way to publish large amounts of content.

- From a folder (and subfolders)
- From a site or page (and all sub pages)
- From a collection

I would also like options to control how publishing happens
- Skip already-published content or republish all
- ACL handling options
- Replication options (sync/async, update publish time, replication queue selection vs. default replication)
- Possibly other options like SCD?

**Comment by davidjgonzalez** [comment]
I would also like:

* the resource selection to be (optionally) query based
*  the conditional replication mechanism to be pluggable, so I can easily develop my own conditions and select them. 
    * Ideally the "OOTB" options are just implementations against this pluggable interface

**Comment by admjls** [comment]
I would like to see:

- to perform dry runs (to validate that my query will deliver the nodes I'm expecting)
- to choose which replication agent(s) will participate
- to schedule event to happen at a future time
- to pause or cancel an active event

**Comment by badvision** [comment]
Heck since we're throwing the kitchen sink in I also want other stuff but I'm going to make a separate story for those things because this is already getting to be a long list. :)

**Comment by badvision** [comment]
@davidjgonzalez Does this mean we include the query builder component as this feature?

**Comment by badvision** [comment]
Also would the pluggable options be via a factory/whiteboard pattern?  How would that implementation need to look?

**Comment by davidjgonzalez** [comment]
@badvision 

> @davidjgonzalez Does this mean we include the query builder component as this feature?

Yes!

> Also would the pluggable options be via a factory/whiteboard pattern? How would that implementation need to look?

I would be happy w an OSGi Service Interface that multiple impl's can be coded against, and the MCP Tool would have a multi-field of dropdowns, and the dropdowns are powered by a DataSource that simply lists all implementations of said OSGi service interface. The tool would in turn simply run through each service impl (probably in the order specified in the tool) and accept/reject based on that.
