### ISSUE TITLE
[Moved to  #1909] Need to refactor stuff out of /etc

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1369]
**This issue has been picked up at  #1909**

## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4+
* [X] ACS AEM Commons Version: 3.16.0
* [x] Reproducible on Latest? yes

### Expected Behavior

In 6.4, the use of /etc is deprecated, at least from a product perspective.  Though user-installed code living in /etc will continue to work, it is a generally good idea to refactor pages and settings to live in their respective designated locations in the JCR for forward compatibility.

### Links

[Summary of new JCR Locations](https://helpx.adobe.com/experience-manager/6-4/sites/deploying/using/repository-restructuring-in-aem64.html)

**Comment by justinedelson** [comment]
I'd suggest breaking this down to the individual changes. To my knowledge, there also needs to be some kind of migration strategy for certain items, e.g. generic lists. IMO, the largest unit of work here (aside from migration) is the creation of new (20ish) consoles and that's definitely going to take some time. So having discreet issues will help track that more easily.

**Comment by davidjgonzalez** [comment]
We should also align on the pattern(s) for how these new consoles are implemented.

**Comment by badvision** [comment]
Can we leave this open as a reminder until each of the consoles have been dealt with?

**Comment by joerghoh** [comment]
@kwin raised #1909 some days ago, and the discussion there produced some more results regarding this topic. Can we close this issue and continue in #1909 then?
