### ISSUE TITLE
Add CSV support to Data spreadsheet API

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1381]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: any
* [ ] ACS AEM Commons Version: 3.16.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

Today anything relying on Spreadsheet requires an XLSX file, but some people would like to provide data in other formats such as CSV.  It should be possible to determine the mime type of an uploaded file and inform the Spreadsheet constructor what kind of file is being provided.  CSV parsing is already provided by the product API.

### Actual Behavior

Only XSLX types are supported in the data importer and url asset importer tools.

### Links

Product API for CSV imports: https://helpx.adobe.com/experience-manager/6-3/sites/developing/using/reference-materials/javadoc/com/day/text/csv/Csv.html

**Comment by davidjgonzalez** [comment]
It seems like saving a CSV as XLSX is trivial; TBH CSV seems like a step backward; surely everyone is managing these files in MS Excel or Open Office?

**Comment by royteeuwen** [comment]
Everyone that wants to view the file yes, but CSV is still widely used when using the exports in other systems that would like to import it
