### ISSUE TITLE
Documentation - Can we add an example to Manage Controlled Process(MCP) > Data Importer tool

### ISSUE THREAD

**Issue by ksurendra** [Adobe-Consulting-Services/acs-aem-commons#1382]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3.x, AEM 6.4
* [ ] ACS AEM Commons Version: 3.16.0
* [ ] Reproducible on Latest? yes

### Improve documentation
Can we add an example to the "Data Importer" tool on **Manage Controlled Process (MCP) > Data Importer** tool

### Attached Example
Attaching an example. 
[data-importer-sample-weretail-activities-added-jcrtitle.xlsx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/2017568/data-importer-sample-weretail-activities-added-jcrtitle.xlsx)

## Notes
1. I used AEM 6.4's "Metadata Export" option to generate the spreadsheet. Added "jcr:title" additional column.
2. The first column of the spreadsheet must be "**path**"
3. I added **jcr:title** column. When we run MCP > Data Importer with this file, assets under we-retail/activities will have "jcr:title" applied.

**Comment by badvision** [comment]
That's a fantastic idea, but we have a separate repository for the docs.  Can you open the issue here? https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io

Thanks for your contribution.
