### ISSUE TITLE
AEM 6.3 - Granite UI Multifield - JSON array supported?

### ISSUE THREAD

**Issue by rafeekbhasha** [Adobe-Consulting-Services/acs-aem-commons#1384]
## Required Information

* [ ] AEM Version: 6.3.2
* [ ] ACS AEM Commons Version: 3.12.0
* [ ] Reproducible on Latest? yes/no: YES

1. ACS Commons (3.12.0) Multi-field Extension stores multi field data as JSON array.
2. But as per the suggestion it is recommended to use Adobe's fully supported Granite UI Multifield which stores data as individual nodes.
3. Please let us know how to proceed with this. If we use adobe supported multi field then it will affect the existing component which stored multifield data as JSON array.

### Links
https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/multifield-extension/index.html

**Comment by justinedelson** [comment]
@rafeekbhasha I would assume there is some kind of data migration necessary.
