### ISSUE TITLE
ACS Parsys Placeholder Text feature not working on AEM 6.3

### ISSUE THREAD

**Issue by jainankush385** [Adobe-Consulting-Services/acs-aem-commons#1386]
## Required Information

* AEM Version: 6.3.1.2
* ACS AEM Commons Version: 3.14.8
* Reproducible on Latest:  yes
### Expected Behavior

Parsys Placeholder Text feature not working

### Actual Behavior
`/apps/acs-commons/touchui-widgets/configure-limit-parsys/touchui-limit-parsys.js`
```
function getDesignPath(editable){
        var parsys = editable.getParent(),
            designSrc = parsys.config.designDialogSrc,
            result = {}, param;

        if (designSrc === undefined) {
            return undefined;
        }

        designSrc = designSrc.substring(designSrc.indexOf("?") + 1);

        designSrc.split(/&/).forEach( function(it) {
            if (_.isEmpty(it)) {
                return;
            }
            param = it.split("=");
            result[param[0]] = param[1];
        });

        if (result.content === undefined) {
            return undefined;
        }

        return decodeURIComponent(result.content);
    }
```
`designSrc` not having content attribute.

**Comment by spauwels** [comment]
We have 
ACS AEM Commons Version: 3.14.10
and still a lot of calls to undefined.2.json

**Comment by badvision** [comment]
@jainankush385 can you confirm if the master branch resolves this bug?

**Comment by jainankush385** [comment]
Hi @badvision  sorry for late reply. 
Can you  please provide me aem package of master branch so i can test on my local.
Thanks

**Comment by jainankush385** [comment]
Hi, @badvision tested locally master branch. The feature is still not working.

Thanks

cc: @wimsymons
