### ISSUE TITLE
[AEM 6.3]-Icon Picker Not Showing Icons when using custom fonts  

### ISSUE THREAD

**Issue by jainankush385** [Adobe-Consulting-Services/acs-aem-commons#1387]
## Required Information

* [ ] AEM Version : 6.3.1.2
* [ ] ACS AEM Commons Version: 3.14.8
* [ ] Reproducible on Latest : yes

### Expected Behavior

Icon should be shown

### Actual Behavior

http://localhost:4502/editor.html/content/../.html
![bug](https://user-images.githubusercontent.com/39520807/40430091-f0926bfc-5ec1-11e8-9c9e-31fcc6be7c8a.gif)

Icons only showing in drop down when **debug client library** is true.
http://localhost:4502/editor.html/content/../.html?debugClientLibs=true
![working](https://user-images.githubusercontent.com/39520807/40430042-c4eaf212-5ec1-11e8-957d-eb8ec8674f66.gif)

**Comment by badvision** [comment]
Smells like a code minification bug.

**Comment by radmike** [comment]
also note comments from ~4 months ago on the docs page: https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/icon-picker/index.html

**Comment by alissonxavierosf** [comment]
This issue has been solved?

**Comment by pjbrof** [comment]
No. Bad stale bot

**Comment by bansalarjit** [comment]
what is the fix for this ?
