### ISSUE TITLE
URL Asset Import dies with an NPE when source column is blank

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1389]
## Required Information

* [x] ACS AEM Commons Version: 3.17.0
* [x] Reproducible on Latest? yes

### Expected Behavior

The row should be skipped and logged as an error, but the process shouldn't die

### Actual Behavior

NPE is thrown and whole process halts on start

```java.lang.NullPointerException at
com.adobe.acs.commons.mcp.impl.processes.asset.UrlAssetImport.extractFile(UrlAssetImport.java:340) at
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at
java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373) at
java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) at
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) at com.adobe.acs.commons.mcp.impl.processes.asset.UrlAssetImport.extractFilesAndFolders(UrlAssetImport.java:180) at ...```

**Comment by badvision** [comment]
Also the Spreadsheet class dies on reading the file if a header column is blank, instead of skipping the column

**Comment by joerghoh** [comment]
Shouldn't this issue be closed? @badvision already added the fix nearly a year ago.

**Comment by badvision** [comment]
Yes, but I should double-check the unit test is accurate before I close.

**Comment by joerghoh** [comment]
@badvision In #2145 I enhanced the unittests to cover this case as well, please check. Maybe we can close this issue then.

**Comment by badvision** [comment]
I think so.  I added this issue so I wouldn't forget to fix it but I might have inadvertently forgotten to close this issue. ;)  I'll re-open if necessary.
