### ISSUE TITLE
DispatcherFlushRules block the call synchronously on replicator.replicate

### ISSUE THREAD

**Issue by royteeuwen** [Adobe-Consulting-Services/acs-aem-commons#1390]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3 SP1
* [ ] ACS AEM Commons Version: last version
* [ ] Reproducible on Latest? yes

### Expected Behavior

The dispatcher flush rules get executed AFTER the resource has been published and should be async

### Actual Behavior

- The dispatcher flush rules is in the preprocessor which makes it executed BEFORE the resource is published => this could cause race conditions where the page is already requested again before its published
- The dispatcher flush rules block the actual call to replicator.replicate because it's in the preprocessor and it has to do all the dispatcher flush rules before returing from the replicate rule (I would expect it to just be added to the queue and not be blocking)

### Steps to Reproduce

Do a replicator.replicate and see the logs to see that the flush rules will be executed before returning from the method

**Comment by davidjgonzalez** [comment]
These rules should be setup on aem publish, which has the trigger flush replication setup. So the content is already on publish when this rep event is trigger - I thought this was covers on the docs page, no?

**Comment by royteeuwen** [comment]
This only applies when the flush agent is actually on the publish, which is not a hard requirement by AEM nor is it in the docs of the dispatcher flush, it only states that they are also possible from publish : "Dispatcher Flush Rules work from AEM 5.6 Publish Servers as well."

**Comment by davidjgonzalez** [comment]
Ok - let’s update the docs

**Comment by davidjgonzalez** [comment]
Just has to be active on AEM Publish (config.publish/my-flush-config).

Updated the docs.
