### ISSUE TITLE
Drag and Drop to `Image` Component Dialog Non-functional After Installing

### ISSUE THREAD

**Issue by gerardvh** [Adobe-Consulting-Services/acs-aem-commons#1393]
## Required Information

* [x] ACS AEM Commons Version: 3.17.0 (also confirmed with 3.13.0)
* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3.0 (also tested with 6.3.0.1, 6.3.1)
* [x] Reproducible on Latest? yes

### Expected Behavior

Dragging an image from the filesystem onto the `Image` component dialog drop zone should add the image to the dialog for submission.

### Actual Behavior

Dragging an image from the filesystem onto the `Image` component dialog drop zone opens the image to be viewed in the browser (default browser behavior).

### Steps to Reproduce

1. Create fresh AEM author instance at v6.3.0 (with sample We.Retail content)
    - Note: also confirmed to occur with CFP1 and SP1
2. Navigate to http://localhost:4502/editor.html/content/we-retail/us/en.html
3. Add Image component to parsys at bottom of page
4. Open dialog for Image component and drag image onto the drop zone
5. Observe expected behavior.
6. Install ACS Commons Content package through `crx/packmgr`
7. Reload page at http://localhost:4502/editor.html/content/we-retail/us/en.html
8. Repeat step 4
9. Observe unexpected behavior
10. Completely remove and delete ACS Commons Content package through `crx/packmgr`
11. Observe unexpected behavior *still* occurs

### Additional Note

At the possibility of this being an issue with AEM itself, I also have created a DayCare ticket for them to investigate the issue on their end.

**Comment by gerardvh** [comment]
### Further clarification:

Here's the expected ending behavior for a drag and drop action to a dialog box drop zone:
![expected_behavior](https://user-images.githubusercontent.com/8163299/41372534-38a169aa-6f13-11e8-9b5d-46aa525dc833.png)

And here is the actual behavior when dropping an image after installing `acs-aem-commons-content`:
![actual_behavior](https://user-images.githubusercontent.com/8163299/41372687-a5f2a582-6f13-11e8-89cf-c1a108a12a58.png)

### Versions
Also, I have confirmed this issue is similar when testing on the latest version of Chrome, as well as Safari 11.1.1 on Mac OS 10.12.6, and for AEM versions 6.3.0, 6.3.0.1, 6.3.2.0.

**Comment by davidjgonzalez** [comment]
@gerardvh are there any JavaScript errors in the browser's Console between loading the page in the page editor and D&D'ing into the Image component?

**Comment by gerardvh** [comment]
Hi @davidjgonzalez, thanks for the response. 

I just checked again while watching the Console in Chrome, and the only warning or message is something like this: 
`Resource interpreted as Document but transferred with MIME type image/png: "file:///Users/gerardvh/Desktop/test%20png%20images/L1030152%20(1).png".`

This message appears to be pretty standard and also comes up when dragging and dropping an image on the browser from a different site.

There are no other errors.

**Comment by gerardvh** [comment]
Just another note here regarding steps 9 and 10 on the initial issue.

It appears that rebuilding the JSP's and clientlibs after uninstalling the content package fixes the issue again. But there is still an issue while the ACS Commons Content package is installed.

Also, DayCare was able to also reproduce this issue on their end and they have created an internal Jira issue to track it, just in case there is a problem with their code. However, they believe the issue is actually being caused by something in the ACS Commons Content package and were not able to offer any sort of work-around.
