### ISSUE TITLE
NPE on Manage Controlled Process > URL Asset Import when "source" column is empty or has invalid url/date

### ISSUE THREAD

**Issue by ksurendra** [Adobe-Consulting-Services/acs-aem-commons#1403]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3 CPF2
* [ ] ACS AEM Commons Version: 3.17.0
* [ ] Reproducible on Latest? yes

### Expected Behavior
Process imports the assets and skip the rows that have no "source". Report them in the Error report.

### Actual Behavior
The import process fails without processing any rows. Error report does not say thai instead a java stack trace. Sample stack trace listed in this file [url_asset_import (1).xlsx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/2124901/url_asset_import.1.xlsx)

![screen shot 2018-06-21 at 1 39 55 pm](https://user-images.githubusercontent.com/902972/41738787-a19d0c34-7558-11e8-83fd-56bff69ed2d8.png)

### Steps to Reproduce
1. Choose a spreadsheet with details of assets to be imported
2. Remove data from some of the rows under "source" column. Save the file
3. Use this file under ACS Commons > Manage Controlled Process > Start > URL Asset Import
3.1 Attach the file
3.2 Leave all the other values are default

**Comment by badvision** [comment]
Confirmed ... need to look for places in the code that try to call toString() without checking if the value is present. Ideally this would be a good place to use Optional instead but will need some meditation on this one.
