### ISSUE TITLE
Page Relocator renaming failure on Destination field unfocus

### ISSUE THREAD

**Issue by Promathia** [Adobe-Consulting-Services/acs-aem-commons#1405]
AEM 6.3
ACS AEM Commons Version: 3.17.0
Reproducible on Latest? yes

in Page Relocator:
1) I need mode 'Rename' so I click it
2) Source page - /content/we-retail/us/en/testpage (existing one and activated)
3) Destination I put: '/content/we-retail/us/en/experience/testpage2'
BUT here comes the problem, when I unfocus the field Destination the path is changed to a page name which is under 'experience', i.e. '/content/we-retail/us/en/experience/summit-success-in-the-himalayas' so I'm not able to put a new name

Links:
https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp/subpages/tools.html

**Comment by badvision** [comment]
I will keep this open but ultimately this will be replaced with a new tool that takes its input from a spreadsheet so you can move multiple things at a time.  Moving this to #1446 which will supersede both the page relocator and the folder relocator tools as one merged tool
