### ISSUE TITLE
ACS Redirect Map Manager

### ISSUE THREAD

**Issue by YevheniiDrozdyk** [Adobe-Consulting-Services/acs-aem-commons#1413]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.2
* [x] ACS AEM Commons Version: 3.17.0
* [x] Reproducible on Latest? yes

### Expected Behavior

When you installing ACS AEM Commons package on publish environment, it should provide access on read for /etc/acs-commons/redirect-maps/redirect-map tree

### Actual Behavior

After installing the ACS AEM Commons package on publish environment, there is no granted access to tree (/etc/acs-commons/redirect-maps/redirect-map)

### Steps to Reproduce

1. Download ACS AEM Commons package
2. Login into publish env. /crx/packmgr/index.jsp by admin credentials
3. Install package
4. Logout from publish env.
5. Look at /crx/de/index.jsp that there is no access to /etc/acs-commons/redirect-maps/redirect-map for "Everyone" group

### Comment
The actual problem with access to /etc/acs-commons/redirect-maps/redirect-map while running script from the (https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-map-manager/index.html)
![image](https://user-images.githubusercontent.com/20265140/42160154-d8e04e96-7dfe-11e8-8606-1478df71d537.png)

When user is signed it to publish:
![image](https://user-images.githubusercontent.com/20265140/42272581-48246620-7f8f-11e8-8d7c-07fd06cc88dd.png)

When user is logout from publish:
![image](https://user-images.githubusercontent.com/20265140/42272461-d47585ce-7f8e-11e8-85d7-9325ee3d0af2.png)

**Comment by davidjgonzalez** [comment]
Fixed in 3.17.4
