### ISSUE TITLE
Issues with audio renditions

### ISSUE THREAD

**Issue by gvilcins** [Adobe-Consulting-Services/acs-aem-commons#1427]
I am running 6.3 locally using ACS Commons 3.17, logged in as the default 'admin' user.
I have also included the workflow process step as [outlined here](https://adobe-consulting-services.github.io/acs-aem-commons/features/wcm-components/audio/index.html).

When adding an MP3 audio file into the DAM, I receive the following errors:

```
24.07.2018 15:40:39.803 *ERROR* [JobHandler: /etc/workflow/instances/server0/2018-07-24_1/update_asset_24:/content/dam/audio/TESTAUDIO-3.mp3/jcr:content/renditions/original] com.day.cq.dam.core.impl.AssetIDProvider Session doesn't have appropriate privileges

24.07.2018 15:40:41.332 *ERROR* [JobHandler: /etc/workflow/instances/server0/2018-07-24_1/update_asset_24:/content/dam/audio/TESTAUDIO-3.mp3/jcr:content/renditions/original] com.day.cq.workflow.compatibility.CQWorkflowProcessRunner Process execution resulted in an error: null

24.07.2018 15:40:41.333 *ERROR* [JobHandler: /etc/workflow/instances/server0/2018-07-24_1/update_asset_24:/content/dam/audio/TESTAUDIO-3.mp3/jcr:content/renditions/original] com.adobe.granite.workflow.core.job.JobHandler Error executing workflow step
```

Any ideas?

**Comment by davidjgonzalez** [comment]
@gvilcins If you remove the ACS Commons WF step does the WF pass successfully? Is there any other error.log data?
This WF Process is using the security context provided by the WorkflowSession ..
