### ISSUE TITLE
Multifield Extension not compatible with Coral3 pathfield

### ISSUE THREAD

**Issue by marto** [Adobe-Consulting-Services/acs-aem-commons#1429]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3.2 (6.3 SP2)
* [x] ACS AEM Commons Version: 3.17.0
* [x] Reproducible on Latest? yes

### Expected Behavior

When using the now deprecated "Multifield Extension" it does not support `granite/ui/components/coral/foundation/form/pathfield` components. When it's used the value of the item is blank and is not hydrated from the json stored in AEM and is left blank.

### Actual Behavior

Although this feature has been deprecated, we can't move to the recommended approach as we require both classic and touch UI to function and currently the classic UI only supports saving the data as json values. We thus need a compatible touch UI approach to search for images in the DAM. The easiest approach was to use a pathfield with a custom picker source, however due to this bug we stuck.

### Steps to Reproduce

Use a `granite/ui/components/coral/foundation/form/pathfield` as one of the items in the miltifield.

### Links

I will be providing a patch to the existing codebase to fix this particular issue.

**Comment by davidjgonzalez** [comment]
Fixed in 3.17.2! thanks!
