### ISSUE TITLE
Multifield Extension not compatible with Coral3 Checkbox

### ISSUE THREAD

**Issue by Narayan15** [Adobe-Consulting-Services/acs-aem-commons#1433]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3
* [ ] ACS AEM Commons Version: 3.17.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

When using the deprecated "Multifield Extension" it does not support granite/ui/components/coral/foundation/form/checkbox component. When it's used the value of the item is blank and is not hydrated from the json stored in AEM.

### Actual Behavior

We can't use OOTB approach as we require both classic and touch UI to function and currently the classic UI only supports saving the data as json values. But the composite multifield supports only Coral 2 UI fields and it should work with Coral 3 UI fields too.

### Steps to Reproduce

Add granite/ui/components/coral/foundation/form/checkbox as one of the items in the multifield.

### Links

I will be providing a patch to the existing codebase to fix this particular issue.

**Comment by davidjgonzalez** [comment]
Fixed in 3.17.2! thanks @Narayan15
