### ISSUE TITLE
Scene 7 step is not executing when i run DAM Update Asset workflow through ACS Commons Bulk workflow manager

### ISSUE THREAD

**Issue by praveenv2018** [Adobe-Consulting-Services/acs-aem-commons#1439]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3 SP2
* [ ] ACS AEM Commons Version: 3.17
* [ ] Reproducible on Latest? yes/no

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by davidjgonzalez** [comment]
What Runner are you using?

**Comment by praveenv2018** [comment]
Synthetic Workflow with Multi threading.

**Comment by davidjgonzalez** [comment]
This is expected as Synthetic WF does not support External WF Processes (since the raison d'etre of Synthetic is to avoid use of Jobs to manage work; and External Processes indicate long-running works outside of AEM.)
