### ISSUE TITLE
Redirect Map Manager NullPointerException when no file uploaded

### ISSUE THREAD

**Issue by brendan-walsh** [Adobe-Consulting-Services/acs-aem-commons#1442]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: Version 6.3.1.1
* [ ] ACS AEM Commons Version: 3.17.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

When I create a new redirect map under http://localhost:4502/miscadmin#/etc/acs-commons/redirect-maps I can't actually add any entries until uploading a file.  To get around this for now I'm just uploaded an empty dummy file so that the initial file will be created in /crx/de

### Actual Behavior

When trying to edit/create redirect entries without first entering a file nothing happens.  UI shows "Success entry added" but in the logs there are actually exceptions.  Log entries are attached.
[error.log](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/2250905/error.log)

### Steps to Reproduce

Create a redirect map at http://localhost:4502/miscadmin#/etc/acs-commons/redirect-maps
Open you new redirect map for editing
Go to edit entries and try to add a new entry.  UI will show success but if you search for the redirect or go to preview you will not see it there.

### Links

N/A

[error.log](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/2250906/error.log)

**Comment by klcodanr** [comment]
@davidjgonzalez @brendan-walsh I opened a PR #1447 to resolve this issue.

**Comment by davidjgonzalez** [comment]
Fixed by @klcodanr!  thanks!
