### ISSUE TITLE
Multifield Extension not compatible with Coral3 DatePicker

### ISSUE THREAD

**Issue by Narayan15** [Adobe-Consulting-Services/acs-aem-commons#1443]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3
* [ ] ACS AEM Commons Version: 3.17.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

When using the deprecated "Multifield Extension", it does not support granite/ui/components/coral/foundation/form/datepicker component. When it's used the value of the item is hydrated from the json stored in AEM, but not saving the value in json second time.

### Actual Behavior

The current composite multifield supports only Coral 2 UI fields and it should work with Coral 3 UI fields too.

### Steps to Reproduce

Add granite/ui/components/coral/foundation/form/datepicker as one of the items in the multifield.

### Links

I will be providing a patch to the existing codebase to fix this particular issue.

**Comment by davidjgonzalez** [comment]
Fixed in 3.17.2
