### ISSUE TITLE
New feature: DAM Reorganizer

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1446]
I would like to be able to supply a mapping spreadsheet that instructs a tool where to move and/or combine existing folders in the DAM.  The source data should be a spreadsheet with the following columns:

- Source folder (validation: Must exist)
- Destination folder
- Mode
    - Move/Merge -- Moves the source folder as a child of the indicated destination folder (creating destination if missing)
    - Rename -- Moves source folder to new path, changing name to match provided destination folder

A report should be generated that summarizes all actions taken.  If a detailed report flag is checked, that report should include all assets moved as well.

Optionally, the user can enable an additional page update mode which scans for pages/components affected by changed asset paths and update them as needed.

A dry run mode should offer a report of operations required without making any changes.

The utility should also provide additional options to enable/disable versioning and publish behavior.  The versioning should cover any pages updated, and publishing should include assets and/or pages which were previously published to automatically republish them after all changes have been made.

**Comment by badvision** [comment]
I don't think that moving an asset triggers any workflow, but we could provide a workflow model as an optional thing, assuming they want to do that.  The extras we might want to embellish on a follow-on story to keep things simple.

**Comment by toddhaser** [comment]
Would report be CSV based so that it could be imported into excel or what not?
Also, you mention optional ability to enable page update mode.  As folders and children assets are moved, I'm thinking of two things that need to be solved for:
1. Updating Publishers of the changes (curious how this would happen)
2. Modifying the pages/components that use the moved assets (and then updating the Publishers)

**Comment by klcodanr** [comment]
@badvision This would also be really useful for pages as well as assets. Generally I've been doing this mapping during migrations as a pre-process, but adjusting pathing etc is a PITA compared to doing it once the content is in AEM.

**Comment by badvision** [comment]
@toddhaser Yes the reports are actually XLSX -- this is part of MCP: https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp/subpages/generic-report 

@klcodanr Actually not a bad idea, that.  I have a page-related utility for this which I will be combining into the fold so it makes sense to support both use cases.  Is there any difference in the way you search for references for page vs. asset?

**Comment by klcodanr** [comment]
@badvision - as far as I know searching for both pages and assets is sup;ported in the ReferenceProvider API:
https://helpx.adobe.com/experience-manager/6-2/sites/developing/using/reference-materials/javadoc/com/day/cq/wcm/api/reference/ReferenceProvider.html

**Comment by badvision** [comment]
Fun fact: It's coming along swimmingly, we're actively testing this one out but it's going to need more time to get all the edge cases 100% right.

**Comment by badvision** [comment]
Feature is called Renovator now.  Enjoy!
