### ISSUE TITLE
Improved Multifield panel

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#145]
With https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/113 a multifield was committed based on http://experience-aem.blogspot.in/2013/09/aem-cq-56-multifield-panel.html. That basically wraps all the properties of the multiple items in a json which is stored in one JCR property.
The example attached in http://www.citytechinc.com/us/en/blog/2013/08/cq_component_plugin_3_fun_with_objects.html stores each item in a new node with dedicated properties. That is much easier to access from the code afterwards (no need to parse JSON, just use regular JCR/Sling API). That code was obviously initially developed by Day but there are still some smaller bugs in there. Once those bugs are resolved, that widget would be a lot better than all the other approaches.

**Comment by SKumarKola** [comment]
Hi,
There is an "order" issue in the dialog.
Clicking on the order navigation- it copies the content to the next item instead on re-ordering.

**Comment by kwin** [comment]
This has been superseded by https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/590.
