### ISSUE TITLE
ACS Bulk workflow is not processing and very slow(1 asset per 2min).

### ISSUE THREAD

**Issue by praveenv2018** [Adobe-Consulting-Services/acs-aem-commons#1450]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3 SP2
* [ ] ACS AEM Commons Version: 3.17
* [ ] Reproducible on Latest? yes

### Expected Behavior

__

### Actual Behavior

_ACS bulk workflow is not processing "DAM Update Asset". It shows completed in the page but not processed all the assets_

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by davidjgonzalez** [comment]
What runner are you using and what are the config params? And what wf?

**Comment by praveenv2018** [comment]
AEM Workflow, 
Batch Size | 200
Batch Interval | 200 seconds
Workflow Model | /etc/workflow/models/dam/update_asset
Processing 150 assets per hour.

**Comment by davidjgonzalez** [comment]
* What's the CPU usage?
* What's the mem usage?
* Is DAM Update Asset WF marked as transient?
* Have you made any changes to the WF?
* Is there a  reason why you're not using Synthetic?
* Have you tried dropping the batch size to something like 10 and checking every 10 seconds?
* How long is an actual WF taking to complete (if you look at the logs?)
* Try setting DEBUG on com.adobe.acs.commons.workflow.bulk and see if theres anything interesting...
