### ISSUE TITLE
Release 3.17.2 has jcr_root/home/users/system/acs-commons/remote-assets-service/

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#1454]
```
unzip -l acs-aem-commons-content-3.17.2.zip | grep remote-assets
        0  08-13-2018 14:37   jcr_root/home/users/system/acs-commons/remote-assets-service/
```

This should not be there. I'm not sure how this is possible with the maven release plugin.

**Comment by justinedelson** [comment]
@davidjgonzalez can you take a look?

**Comment by davidjgonzalez** [comment]
@justinedelson sure - any issues with merging 1448 and releasing 3.17.4?

Not sure how/why this old dir stuck around when i checked out origin/master :(

**Comment by justinedelson** [comment]
no issues from me.
