### ISSUE TITLE
Pages created using ACS Campaign Template does not show cloud services configuration in Touch UI

### ISSUE THREAD

**Issue by SaravanaPrasadM** [Adobe-Consulting-Services/acs-aem-commons#1482]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4_______
* [x] ACS AEM Commons Version: _3.17.4____
* [x] Reproducible on Latest? yes

### Expected Behavior
Campaign Page properties should allow cloud services tab to choose the required config to be applied on the page

### Actual Behavior
Pages created using ACS Campaign Templates does not show the cloud services tab in Touch UI

### Steps to Reproduce
Create a campaign page using ACS Campaign Template
Go to page properties of the page to configure the cloud service

### Links
_Links to related assets, e.g. content packages containing test components_

**Comment by justinedelson** [comment]
I don't think ACS AEM Commons has a Campaign Template. Can you clarify?
