### ISSUE TITLE
Audio Component has different controls on different browsers

### ISSUE THREAD

**Issue by prateekagrawal002** [Adobe-Consulting-Services/acs-aem-commons#1483]
Hi,

I have used the OOTB audio component and it works fine, except for that the player has different controls on Chrome and Firefox. On Chrome I have the download button whereas on Firefox I do not get the download functionality but I do get the controls for adjusting the volume of the audio clip.
Is this the expected behavior or am I missing something?
I have provided the further details below:

AEM Version - 6.2.0 (Vanilla Instance)
ACS AEM Commons Version: 3.6.2
Chrome:
![image](https://user-images.githubusercontent.com/33212756/45366316-da061900-b5de-11e8-8dcb-067ebf8ffaf0.png)
Firefox:
![image](https://user-images.githubusercontent.com/33212756/45366338-e8543500-b5de-11e8-88c5-ccc819d80d65.png)

**Comment by justinedelson** [comment]
This is a browser-native control, so a variance is expected. IIUC, the download functionality is specific to Chrome, although Firefox may add it.
