### ISSUE TITLE
New Feature: Generic cloud service configuration

### ISSUE THREAD

**Issue by josephrignanese** [Adobe-Consulting-Services/acs-aem-commons#1485]
There are times when it is necessary to inject arbitrary header / footer code on the page.

One such time is when integrating AEM 6.3 with Adobe Launch.

I would like to introduce a generic cloud service configuration that projects can use for this purpose. It would be similar to the deprecated feature DTM cloud service configuration.

**Comment by josephrignanese** [comment]
Link to the current suggested approach:
https://helpx.adobe.com/experience-manager/using/aem63_launch_integration.html#AddingAdobeLaunchsHeaderinAEM

**Comment by justinedelson** [comment]
Can't the Generic Analytics Snippet Cloud Service be used for this?

**Comment by josephrignanese** [comment]
Thanks for the suggestion @justinedelson.

I wasn't aware of it, but I had a look and there are 3 issues I can see with using the Generic Analyics Snippet.

1. The contents of the configuration are embedded within a script tag, so you can't inject arbitrary HTML
2. There is only 1 field so you can't specify different contents for <head> or at the end of the <body>.
3. The value is placed at the end of the <body>, but the Adobe launch docs suggest that the launch embed code should be injected in the head (for async mode)

Any other ideas?

**Comment by josephrignanese** [comment]
@justinedelson let me know if you think this is something worth contributing to ACS commons otherwise please go ahead and close.

I was also thinking of how we might be able to do this in a safe way to mitigate risks around introduction of XSS vulnerabilities.

Ultimately, it would be good for consumers to have the capability to control who can insert HTML in an unsafe context using this feature.
