### ISSUE TITLE
Default config of the Package Replication Status Updater does not consider policy mapping nodes

### ISSUE THREAD

**Issue by salexb** [Adobe-Consulting-Services/acs-aem-commons#1486]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3.2.1
* [ ] ACS AEM Commons Version: 3.17.4
* [ ] Reproducible on Latest? yes

### Expected Behavior

Template policy mappings, contained within the package that is being replicated, are also marked as activated. 

### Actual Behavior

With default configuration of the Package Replication Status Updater policy mapping nodes are not being considered. This leads to page activation issue, even so those nodes are actually being replicated.

### Steps to Reproduce

1. Make sure ACS Commons is installed and default configuration JcrPackageReplicationStatusEventHandler, is provided as described in the https://adobe-consulting-services.github.io/acs-aem-commons/features/package-replication-status-updater/index.html
2. Go to package manager and replicate existing we.retail.ui.content-x.x.x.zip package
3. Go to CRX and verify if the e.g. /conf/we-retail/settings/wcm/templates/product-page/policies/jcr:content is activated. Node is not being marked as activated.
4. To see the consequence, create page using template from step 3. and try to activate the page. 

Polices which are already present on a publish instance and actually replicated via step 2. are reported as not replicated content.

**Comment by salexb** [comment]
As discussed @kwin please have a look as well and provide additional info if needed. As a solution we should consider adding additional configuration to list of existing defaults:

`cq:Page/nt:unstructured /conf/.*/settings/wcm/templates/.*/policies/.*`

This should be listed before the following entry, as it will not be considered otherwise (more specific first, generic last):

`nt:unstructured /conf/.*/settings/wcm/policies/.*`

**Comment by kwin** [comment]
Actually cq:Page/nt:unstructured has never been considered. Even the old version prior to https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/7048b71b63590c9175faad15966d1e521a159140 did not have it. But I think it makes sense to add this as well.
