### ISSUE TITLE
403 Implementation using ACS Commons Error Handling

### ISSUE THREAD

**Issue by prateekagrawal002** [Adobe-Consulting-Services/acs-aem-commons#1493]
Hi,

I have implemented the custom error handling using ACS-Commons and I get re-redirected to my 404 page when a 404 error occurs.
I have also created a custom page for 403, just like I created for 404.
I have configured a test page with CUG (Closed User Group, I am not a part of the group applied as a part of CUG).
I should now be redirected to a 403 page in this scenario, but this does not happen.

I have followed the steps mentioned in the video (https://www.youtube.com/watch?time_continue=1&v=w4P9T_miX8Q)

Is 403 error handling not supported by ACS-Commons or am I missing something here?
AEM Version - 6.2.0 (Vanilla Instance)
ACS AEM Commons Version: 3.6.2

**Comment by davidjgonzalez** [comment]
What’s the response status on the page? 403 or 404?  Error page handler uses whatever status code sling provides, so unless 404 is your fallback/default page, if check to make sure aem/sling is resolving the request as a 403 (and not a 404)
