### ISSUE TITLE
Disable ACS Commons Multifield?

### ISSUE THREAD

**Issue by Ronald-Diemicke** [Adobe-Consulting-Services/acs-aem-commons#1504]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3/6.4
* [x] ACS AEM Commons Version: 3.18.2
* [x] Reproducible on Latest? yes

### Expected Behavior

I have a multifield referencing the out of the box granite path: 										sling:resourceType="granite/ui/components/foundation/form/multifield"
but it is using the ACS commons multifield including storing the data as JSON

### Actual Behavior

I'd like to have a way to switch back to the OOTB functinoality of mutlifield in AEM 6.3/6.4 with ACS commons installed - while still allowing the ACS commons multifield to be used for legacy components we have that use it.

**Comment by bearcherian** [comment]
Does your component dialog have the 'acs-commons-nested` property? I'm using `granite/ui/components/coral/foundation/form/multifield` and it is storing as nodes, as it should. The structure of the mutlifield is different as well. `field` should be a `granite/ui/components/coral/foundation/container` with items, as opposed to a `granite/ui/components/coral/foundation/form/fieldset`.

**Comment by Ronald-Diemicke** [comment]
@bearcherian - so we're not using the `acs-commons-nested` property - BUT, I don't think we reformatted the nodes...  so I'll look at that and report back asap.
