### ISSUE TITLE
Undefined exception on configure-limit-parsys.min.js

### ISSUE THREAD

**Issue by Mupc** [Adobe-Consulting-Services/acs-aem-commons#1516]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4
* [ ] ACS AEM Commons Version: 3.17.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

With a custom component that has a resource of 'wcm/foundation/components/parsys', when we drag and drop any component no console error is expected.

### Actual Behavior

One error is logged every time that I drag and drop one component. This error is an undefined exception on /apps/acs-commons/widgets/configure-limit-parsys.min.js
This error happens on the: cellSearchPathInfo = cellSearchPathInfo[parNames[c]]; Since the pasys was created dynamically using sly resource and for the component the firt time on the fir it gets undefined, and in the second it breaks. (almost as a nullpointer issue)

![image](https://user-images.githubusercontent.com/7215105/46820354-60d42000-cd5c-11e8-99b8-24b6a4ed4a6e.png)

### Steps to Reproduce

Some component with a resource parsys:
<sly data-sly-resource="${ column.parsysKey @ resourceType='wcm/foundation/components/parsys'}"/>

The final structure would be something like:

![image](https://user-images.githubusercontent.com/7215105/46820311-48640580-cd5c-11e8-87b8-84dff0522926.png)

Drag and drop some component on the last parsys and see the error being logged on the console.

First iteration:
![image](https://user-images.githubusercontent.com/7215105/46820484-ae508d00-cd5c-11e8-8852-4e5621a904f7.png)

Second one:
![image](https://user-images.githubusercontent.com/7215105/46820509-c0323000-cd5c-11e8-86de-573ffde78d25.png)

Third and last one:
![image](https://user-images.githubusercontent.com/7215105/46820559-dcce6800-cd5c-11e8-978c-0e376d511640.png)

ParNames:
0: "common_content_iparsys"
1: "responsivecolumncont"
2: "column0"

**Comment by anand19cse** [comment]
Is this issue fixed?
I tried with latest version of ACS (4.1.0) and issues still exists.
Better explained at this url https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1516
We are also getting same error on all environment including prod. And business is not able to drag and drop any component in parsys.
Could you please fix it as soon as possible? It is very critical issue for editors.

**Comment by komariraju** [comment]
Hi @kwin 
Can you please provide an update on this as we are seeing this issue in AEM6.4 and ACS(3.19.2), thank you.

**Comment by kwin** [comment]
@komariraju Please report a new issue if it still appears with version 5.3.0. This issue has been closed a long time ago.

**Comment by komariraju** [comment]
HI @kwin 
Thanks for the update, we are seeing below fix added for this file #/apps/acs-commons/widgets/configure-limit-parsys/classicui-limit-parsys.js
 if(typeof limit !== 'undefined' && !limit.isWithin){
why this change was not part of ACS 3.19.2 version package?
