### ISSUE TITLE
Installation of ACS AEM Commons 3.18.2 package on AEM 6.4 is taking long time

### ISSUE THREAD

**Issue by csimion19** [Adobe-Consulting-Services/acs-aem-commons#1521]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.0
* [ ] ACS AEM Commons Version: 3.18.2
* [ ] Reproducible on Latest? yes

### Expected Behavior
Usually the package get installed in few seconds

### Actual Behavior
The package installation is not ending.
I have tried to install ACS AEM Commons 3.18.2 package on an upgraded customer environment, running 6.4.0. The package installation is parsing the whole /content/* , and when the repository is very big, looks like the installation will not end. I left the package in installation phase for 2 days and it didn't finish yet. 
After few days, I stopped the 3.18.2 package installation and started a new one with 3.17 version which ended in ~20 seconds.

### Steps to Reproduce

Within a big content repository try to install ACS Commons 3.18.2 version using package manager, and look for the progress bar. You will notice the installation will parse the every element in /content/*

**Comment by davidjgonzalez** [comment]
@csimion19 can you provide any logs of the "parsing" of /content? 
The only reason i can think of for this would be an issue with the filter.xml that makes package manager think it needs to snapshot all of /content .. or something like that. But the 2 filters for /content are explicit rep:policies and have been in the project for 2 years..

**Comment by davidjgonzalez** [comment]
Looked at this offline with @csimion19 - does not appear to be an issue with ACS Commons, but rather some other OOTB packages. 

Closing. If this turns out to be ACS Commons related, we can re-open.
