### ISSUE TITLE
Typo on templated email documentation

### ISSUE THREAD

**Issue by scotty6435** [Adobe-Consulting-Services/acs-aem-commons#1534]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: N/A
* [x] ACS AEM Commons Version: 3.18.2
* [x] Reproducible on Latest? yes

### Steps to Reproduce

* Visit https://adobe-consulting-services.github.io/acs-aem-commons/features/workflow-processes/send-templated-email/index.html
* See that "greate" should be "great"

**Comment by davidjgonzalez** [comment]
fixed - thanks!
