### ISSUE TITLE
Review use of QueryBuilder and prevent ResourceResolver leakage

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1539]
Use of QueryBuilder APIs for querying often results in a leaking ResourceResolver.

The ACS Commons code-base should be reviewed for use of QueryBuilder and any leakage should be mitigated.

**Comment by adamcin** [comment]
@davidjgonzalez I think we should reopen this issue after merging #1686 . The CloseableQueryBuilder should ease mitigation in most places.

**Comment by davidjgonzalez** [comment]
@adamcin Do you recall where this was left off? I thought you actually ended up going through and updated the uses of QueryBuilder to use CloseableQueryBuilder. Do you recall if you only tackled a subset?

**Comment by adamcin** [comment]
@davidjgonzalez I believe I converted all usages of QueryBuilder that were present at the time.

**Comment by davidjgonzalez** [comment]
thanks @adamcin took a quick scan and looks like you did; there were a few unused references left but easy enough to clean up in #1794 - thanks!!!

**Comment by davidjgonzalez** [comment]
This was fixed w/ CloseableQueryBuilder
