### ISSUE TITLE
ACS AEM Commons Twitter Support Bundle is not working after AEM 6.4 upgradation

### ISSUE THREAD

**Issue by ajaykpaul** [Adobe-Consulting-Services/acs-aem-commons#1548]
This is exactly same issue as the following:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1236

**Comment by davidjgonzalez** [comment]
@ajaykpaul as per the convo on #1236 - is the twitter bundle installed?

**Comment by ajaykpaul** [comment]
it seems that it has been fix it with latest update.
