### ISSUE TITLE
EnsureServiceUser config format should strip leading/trailing whitespace for array elements in `aces` property, for better diff visibility in config files.

### ISSUE THREAD

**Issue by adamcin** [Adobe-Consulting-Services/acs-aem-commons#1552]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: any
* [x] ACS AEM Commons Version: <=3.19
* [x] Reproducible on Latest? **yes**

### Expected Behavior

Given an EnsureServiceUser sling:OsgiConfig file with multiple values for aces separated by newlines, the whitespace surrounding each element should not be treated as part of the first key or the last value:

```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
    jcr:primaryType="sling:OsgiConfig"
    operation="add"
    aces="[
         type\=allow;privileges\=jcr:versionManagement\,jcr:read\,crx:replicate\,rep:write\,jcr:lockManagement\,jcr:modifyProperties;path\=/content/dam,
         type\=allow;privileges\=jcr:versionManagement\,jcr:read\,crx:replicate\,rep:write\,jcr:lockManagement\,jcr:modifyProperties;path\=/content,
         type\=allow;privileges\=jcr:versionManagement\,jcr:read\,crx:replicate\,rep:write\,jcr:lockManagement\,jcr:modifyProperties;path\=/content/projects,
         type\=allow;privileges\=jcr:all;path\=/var/workflow,
         type\=allow;privileges\=jcr:all;path\=/etc/workflow
    ]"
    principalName="acme-workflow-service"
    ensure-immediately="{Boolean}true"
/>
```

### Actual Behavior

Given the above file, the current behavior results in an EnsureAuthorizableException thrown because the whitespace before the "type" key is retained, and therefore fails to match the `PROP_TYPE` constant in the comparison logic. 

The bug manifests here: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/d8201d0a76dfb0a8c5a83bd4e05e8a701bc3333c/bundle/src/main/java/com/adobe/acs/commons/users/impl/Ace.java#L91

The symptomatic exception is thrown here: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/d8201d0a76dfb0a8c5a83bd4e05e8a701bc3333c/bundle/src/main/java/com/adobe/acs/commons/users/impl/Ace.java#L118

The inconvenient workaround is to eliminate the white space altogether, which forces code reviewers to scroll to the right a ways in order to spot any changes in a pull request.

### Steps to Reproduce

Create a new sling:OsgiConfig node at `/apps/system/config/com.adobe.acs.commons.users.impl.EnsureServiceUser-acme-workflow-service.xml` with the above content, and capture the log output during config installation.

**Comment by joerghoh** [comment]
So trimming the values would be sufficient?

**Comment by adamcin** [comment]
I think so. Probably safe to call entry.trim() right here: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/d8201d0a76dfb0a8c5a83bd4e05e8a701bc3333c/bundle/src/main/java/com/adobe/acs/commons/users/impl/AbstractAuthorizable.java#L70,L72
