### ISSUE TITLE
Data Importer - not able to handle property names such as "cq:tags@[]"

### ISSUE THREAD

**Issue by ncordeiro** [Adobe-Consulting-Services/acs-aem-commons#1561]
Please  note that the fix for the issue is to update the  DataImporter class in the package com.adobe.acs.commons.mcp.impl.processes  at line 61 setting the enableHeaderNameConversion to true
Alternative way would be to avoid passing it in the constructor since the Spreadsheet java constructor sets it to true in the class

## Required Information

* [6.4 ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: sp2
* [x] ACS AEM Commons Version: 3.18.3
* [x] Reproducible on Latest? yes/no- yes

### Expected Behavior
I am using the data import feature to update asset's properties,

property names in the header of an excel, of the format propertyname@[] such as cq:tags@[] should be  stored in aem as cq:tags and not cq:tags%5... 

The value stored in aem is not cq:tags or any propertyname but a representation of(maybe creating a valid property name of @[]) "@[]"

Links: https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp-tools/data-importer/index.html

### Actual Behavior
The aem property name should be stored as cq:tags without parsing the "@[]"

### Steps to Reproduce
1.  Create an excel with property name(test@[] or cq:tags@[]) in the header 
2. Import the excel using data import in the MCP uploading the excel file and choosing create/overwrite property
3. Check the metadata property name 

Attaching the sample excel sheet data 
![image](https://user-images.githubusercontent.com/4909353/48511817-6e7a3b00-e81d-11e8-965e-344d021b11b5.png)

**Comment by badvision** [comment]
Good sleuthing!  Sorry about that.  I'll get something in for 4.0.0, but if you beat me to it I'll approve the pull request post-haste.

**Comment by ncordeiro** [comment]
@badvision : for some reason i could not create a pull request , complains of permissions, i will try again.. thanks Brendan

**Comment by badvision** [comment]
Let me know if my patch is acceptable @ncordeiro.  I think the approach I took in #1579 allows some flexibility as well as addressing the root issue.
