### ISSUE TITLE
Limiting the parsys does not work when pasting multiple paragraphs

### ISSUE THREAD

**Issue by livvius** [Adobe-Consulting-Services/acs-aem-commons#1563]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3
* [ ] ACS AEM Commons Version: 3.17.4
* [ ] Reproducible on Latest? yes

### Expected Behavior

When pasting multiple paragraphs the parsys should count if there are enough free slots available based on the limitation and how many paragraphs are already in place.

### Actual Behavior

The parsys allows to paste, all at once, more elements than the capacity available. So if there is only one available slot, I'm still able to paste 2 paragraphs, all at once.

### Steps to Reproduce

1. Limit the parsys to 2 paragraphs.
2. Paste 3 paragraphs, all at once.

**Comment by kwin** [comment]
Related PR: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1577/commits
