### ISSUE TITLE
Hardcoded path to /etc/tags not compliant with AEM 6.4 new location at /content/cq:tags

### ISSUE THREAD

**Issue by Lrochefort** [Adobe-Consulting-Services/acs-aem-commons#1574]
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/979121c213a8c664a75204011226e218b0c97ba4/bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/TagCreator.java#L328

**Comment by davidjgonzalez** [comment]
Yes we should fix this (looks like this issue was opened twice? Closing this and we can use the original #1573)
