### ISSUE TITLE
Asset import needs additional configuration inputs

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1578]
Currently the asset import utility assumes that the path should include an SFTP URL which includes username and password, but using that will also disclose the password everywhere.  Also, in the event of using SFTP, it would be helpful to add controls over connection timeout.

**Comment by cylinder-y** [comment]
He everyone.

We need this feature in our project. 
I have forked acs-aem-commons, and I'm going to fix it in the following branch: https://github.com/cylinder-y/acs-aem-commons/tree/feature/Fix-1578.
When feature will be fixed I will create pull request that described in CONTRIBUTING.md

--Yaraslau

**Comment by cylinder-y** [comment]
Hello @badvision,
Could you please review pull request?
--Yaraslau

**Comment by badvision** [comment]
Having a look now, thanks!  I just got back from holiday.

**Comment by badvision** [comment]
Looks great!  Thanks for helping improve these tools @cylinder-y !
