### ISSUE TITLE
Url Asset Ingestor tries to create folder that was created several steps ago

### ISSUE THREAD

**Issue by cylinder-y** [Adobe-Consulting-Services/acs-aem-commons#1583]
Url Asset Ingestor tries to create folder that was created several steps ago

## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.1, 6.4.2
* [ ] ACS AEM Commons Version: 3.19.1
* [ ] Reproducible on Latest? yes

### Expected Behavior

When I have the following content in excel file used for migration:

| Source  | Destination |
| ------------- | ------------- |
| /some-assets/somefolder/dam-test/myproject/images/2017/10/destination/file1.jpg  | /some-assets/somefolder/dam-test/myproject/images/2017/10/destination |
| /some-assets/somefolder/dam-test/myproject/images/2017/10/destination/file2.jpg  | /some-assets/somefolder/dam-test/myproject/images/2017/10/destination  |
| /some-assets/somefolder/dam-test/myproject/images/2017/10/destination/file3.jpg  | /some-assets/somefolder/dam-test/myproject/images/2017/10/destination  |
| ......  | .......  |

Non-existing folders should be created once:

> /content/dam/some-assets/
> /content/dam/some-assets/somefolder/
> ..........

### Actual Behavior

The following folders are generated in report:

> /content/dam/some-assets
> /content/dam/some-assets/somefolder
> /content/dam/some-assets
> /content/dam/some-assets/somefolder
> /content/dam/some-assets/somefolder/dam-test
> /content/dam/some-assets/somefolder/dam-test
> /content/dam/some-assets/somefolder/dam-test/myproject
> /content/dam/some-assets/somefolder/dam-test
> /content/dam/some-assets/somefolder/dam-test/myproject/images
> /content/dam/some-assets/somefolder/dam-test/myproject/images/2017
> /content/dam/some-assets/somefolder/dam-test/myproject/images/2017/10
> /content/dam/some-assets/somefolder/dam-test/myproject/images/2017/10/destination
> /content/dam/some-assets/somefolder/dam-test/myproject
> /content/dam/some-assets/somefolder/dam-test/myproject/images/2017/10/destination/File2.jpg
> /content/dam/some-assets/somefolder/dam-test/myproject/images/2017/10/destination/file1.jpg

log error example:

> 26.11.2018 18:23:31.260 *INFO* [pool-28-thread-4] com.adobe.acs.commons.fam.actions.Actions Error commit, retry count is 10
> javax.jcr.ItemExistsException: dam-test
> 	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$5.perform(NodeImpl.java:287) [org.apache.jackrabbit.oak-jcr:1.8.3]
> 	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$5.perform(NodeImpl.java:264) [org.apache.jackrabbit.oak-jcr:1.8.3]
> 	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:208) [org.apache.jackrabbit.oak-jcr:1.8.3]
> 	at org.apache.jackrabbit.oak.jcr.session.ItemImpl.perform(ItemImpl.java:112) [org.apache.jackrabbit.oak-jcr:1.8.3]
> 	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.addNode(NodeImpl.java:264) [org.apache.jackrabbit.oak-jcr:1.8.3]
> 	at com.adobe.acs.commons.mcp.impl.processes.asset.AssetIngestor.createFolderNode(AssetIngestor.java:333) [com.adobe.acs.acs-aem-commons-bundle:3.19.1.SNAPSHOT]
> 	at com.adobe.acs.commons.mcp.impl.processes.asset.AssetIngestor.createFolderNode(AssetIngestor.java:327) [com.adobe.acs.acs-aem-commons-bundle:3.19.1.SNAPSHOT]
> 	at com.adobe.acs.commons.mcp.impl.processes.asset.AssetIngestor.createFolderNode(AssetIngestor.java:327) [com.adobe.acs.acs-aem-commons-bundle:3.19.1.SNAPSHOT]
> 	at com.adobe.acs.commons.mcp.impl.processes.asset.AssetIngestor.createFolderNode(AssetIngestor.java:327) [com.adobe.acs.acs-aem-commons-bundle:3.19.1.SNAPSHOT]
> 	at com.adobe.acs.commons.mcp.impl.processes.asset.AssetIngestor.createFolderNode(AssetIngestor.java:327) [com.adobe.acs.acs-aem-commons-bundle:3.19.1.SNAPSHOT]
> 	at com.adobe.acs.commons.mcp.impl.processes.asset.UrlAssetImport.lambda$null$7(UrlAssetImport.java:226) [com.adobe.acs.acs-aem-commons-bundle:3.19.1.SNAPSHOT]
> 	at com.adobe.acs.commons.fam.actions.Actions.lambda$retry$2(Actions.java:141) [com.adobe.acs.acs-aem-commons-bundle:3.19.1.SNAPSHOT]
> 	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:200) [com.adobe.acs.acs-aem-commons-bundle:3.19.1.SNAPSHOT]
> 	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runActionAndLogErrors(ActionManagerImpl.java:167) [com.adobe.acs.acs-aem-commons-bundle:3.19.1.SNAPSHOT]
> 	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$deferredWithResolver$0(ActionManagerImpl.java:159) [com.adobe.acs.acs-aem-commons-bundle:3.19.1.SNAPSHOT]
> 	at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:88) [com.adobe.acs.acs-aem-commons-bundle:3.19.1.SNAPSHOT]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)

### Steps to Reproduce

1. Create new Url Asset Import process
2. Upload excel mapping with non existing folders in target column
3. Use file:/ or sftp:/ prefix
4. Use /content/dam path Target JCR folder field
5. Press Start
6. See report
7. See logs

**Comment by badvision** [comment]
Let me know if PR #1584 is sufficient.  It does try to prevent doing duplicate work in most places, but the fact that folder creates are run in parallel does allow for some (non-fatal) race conditions to occur.  This patch should minimize the effect of that.

**Comment by cylinder-y** [comment]
Hi @badvision, I would try to verify it tomorrow

**Comment by badvision** [comment]
No rush.  Thanks!

**Comment by cylinder-y** [comment]
Let's close it when pull request will be merged

**Comment by badvision** [comment]
Thanks @cylinder-y for verifying! 👍
