### ISSUE TITLE
Sftp File Asset Ingestor do not report failed items

### ISSUE THREAD

**Issue by cylinder-y** [Adobe-Consulting-Services/acs-aem-commons#1587]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6..4.1, 6.4.2
* [ ] ACS AEM Commons Version: 3.19.1
* [ ] Reproducible on Latest? yes

### Expected Behavior

When URISyntaxException | JSchException | SftpException occurs report should be updated accordingly

### Actual Behavior

When URISyntaxException occurs. This information is only logged into error.log, but not mentioned on report or errors

### Steps to Reproduce

Run sftp migration(Asset Injestor with sftp configuration) of folder containing children files/folder with space character

**Comment by cylinder-y** [comment]
Hello @badvision, 

From my point of view we could do the following:
As we have no access to the ActionManager within SftpHierarchicalElement, could we just add failed items with "Failed" status into Regular Report?

With the current code structure I have no idea how to generate Errors Report using ActionManager

**Comment by badvision** [comment]
It's supposed to retry a few times and then ultimately handle the error for you.  You will see a number of errors in the log.  If the exception is being swallowed and not thrown then that would explain why it's not bubbling up.  The design of MCP (and FAM which it is build around) is that you just throw errors, you shouldn't have to explicitly report them yourself unless you decide that retrying is no longer a good idea.

**Comment by badvision** [comment]
https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp/subpages/error-handling

**Comment by cylinder-y** [comment]
Hi @badvision,
I have the following idea: 

As we can't throw exception outside of SftpHierarchicalElement.getChildren() method, because fileVisitor will stop it's work, we could create the following method:

```
    public static void reportFailedItem(Exception ex, String nodeName) {
        ActionManager manager = getCurrentActionManager();
        if (manager != null) {
            //create Failure iteam and add it to the failures list
        } else {
            LOG.error("Could not identify current action manager.", new IllegalStateException());
        }
    }
```

We could use this method in 'catch' sections, where we swallow exceptions.

What do you think?

**Comment by cylinder-y** [comment]
Well in this case we will have spam in the report, closing issue
