### ISSUE TITLE
Sftp Asset Ingestor throws URISyntaxException if item contains special characters

### ISSUE THREAD

**Issue by cylinder-y** [Adobe-Consulting-Services/acs-aem-commons#1593]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.1, 6.4.2
* [ ] ACS AEM Commons Version: 3.19.1
* [ ] Reproducible on Latest? yes

### Expected Behavior

If migrated folder contains files or folders with special characters, those items should be imported

### Actual Behavior

When we have space characters inside of imported folder, we have the following:

1. Asset is not imported, only exception is written into log
2. Folder not imported, and process is running in endless loop

### Steps to Reproduce

Run Sftp Asset Injector(file or url), with special chars in names

**Comment by cylinder-y** [comment]
working on it

**Comment by badvision** [comment]
Dude you rock! 🗡 Let me know if you need any assistance with this patch.  Also, if possible, could you update the unit test to assert it works?  I think I have a few mocks in there already that help bypass the SFTP library to at least test the rest of the code.
