### ISSUE TITLE
mvn install is failed on master 22c2a0d3da

### ISSUE THREAD

**Issue by cylinder-y** [Adobe-Consulting-Services/acs-aem-commons#1595]
## Required Information

* [ ] ACS AEM Commons Version: 3.19.1
* [ ] Reproducible on Latest? yes

### Expected Behavior

All tests are passed

### Actual Behavior

[ERROR] Failures: 
[ERROR]   SyntheticDialogTest.testSimpleMultifieldComponentGeneration:88 Multifield node check

### Steps to Reproduce

run mvn test or install on bundle

### Links
https://travis-ci.org/Adobe-Consulting-Services/acs-aem-commons/jobs/461214620
possible reason is change on 22c2a0d3da347e2fbfb00b9d2a4ea9958f59a5f4

**Comment by badvision** [comment]
GAH!  No bugfix goes unpunished by another bug.  In this case the test was actually invalid.  I fixed this in the master.  Thanks for catching it.
