### ISSUE TITLE
Asset Ingestor and Valid Jcr Name

### ISSUE THREAD

**Issue by cylinder-y** [Adobe-Consulting-Services/acs-aem-commons#1597]
JcrUtil.createValidName() has the following issues:

1. It trunk truncates the filename to a length of 64, but JcrUtils.isValidName(stringGraterThan64) still returns true
2. It turns all alphabet letters into lower case.

Is it good idea to create custom createValidName() method, and use it if "Preserve Filename" is disabled?
This method will support 

1. Uppercase letters 
2. Any length

As a result we will support only numbers, letters(large and small cases) and dashes in filenames.

The same is actual for folder names

**Comment by davidjgonzalez** [comment]
Off-topic, but i think @cylinder-y found the official new name for this feature: **Asset Injestor**! 🤡

**Comment by badvision** [comment]
Hey man, he's from Belarus.  Be nice. 😛  But yes given all the bugs he's finding (and fixing) it is a bit of a silly feature isn't it?

**Comment by badvision** [comment]
According to the JCR Spec:

**Comment by cylinder-y** [comment]
As pull request #1601 was merged, may we close it?

**Comment by badvision** [comment]
Yes of course.  It's up to you to decide if this feature request is still relevant since you opened it. 😉  I'll close this out.
