### ISSUE TITLE
Disable all Clientlibs by default

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1614]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: All
* [X] ACS AEM Commons Version: All
* [X] Reproducible on Latest? yes

We have several features that inject JavaScript into OOTB client library categories by default (opposed to the opt-in method of all other ACS Commons) features. This is problematic in that this JS runs even if the consumer does not want the feature (unnecessary code execution) and this can also occasionally break or surface breaking behavior in OOTB features [#1602](https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1602).

Ideally, all JS/Clientlibs are "off by default" and a consumer of ACS Commons must actively enable them. This is a breaking change, so this should be part of the 4.0.0 release.

## Possible solutions 

1) We have the DynamicTouchUIClientLibLoader [944](https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/944) and [1199](https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1199) that can be used to disable ClientLiib inclusion, but this assumes the Clientlibs are ON by default. We could enable this by default, and allow users of the features to override the defaults, however, this now results in the DynamicTouchUIClientLibLoader feature being enabled by default. I

2) Do not include our clientlibs into default categories by default, and require a consumer to do this manually if they use the feature. (XML inclusion node definitions to be included in the docs).
     1) Reset our cq:clientLibraryFolder's to have an acs-commons specific category (`acs-commons.limited-parsys`)
    2)  Provide instructions that to enable this feature, you have to deploy your own cq:clientLibraryFolder definitions that looks like
  `/apps/my-project/clientlibs/vendor/acs-commons-limited-parsys` => `category: <the OOTB category>`, `embed: acs-commons.limited-parsys`

**Comment by schoudry** [comment]
or just thinking out loud...

3.a. Remove the otb categories added in all UI extensions and may be add `categories=enable.this.extension.in.osgi`

b. Add an OSGI service named "ACS Commons Enable Touch UI extensions" with a list of all UI extensions added as boolean `org.apache.felix.scr.annotations.Property`  

c. Enabling an extension would add the specific categories in respective clientlib location under /apps/acs-commons...

Similarly add an OSGI service for Classic Extensions, test upgrades etc....

**Comment by davidjgonzalez** [comment]
@schoudry moving forward we'll want to avoid writing to /apps at runtime as this will be immutable space (ie. writes are runtime will fail) for some 6.5 deployments.

Im not sure if the OOTB HtmlLibrary APIs allow programmatic registration (via a custom OSGI service).. perhaps?

We'd also want a way to say "acs-commons X clientlib" should only be injected into contexts A and B (ex. only page editor, or only assets browse UI) ... i think the only reasonable way to do this is by mapping to existing clientlib categories (?)

**Comment by badvision** [comment]
That multifield client library is causing problems in 6.4 so I vote for disabling.

**Comment by kwin** [comment]
How is this supposed to work e.g. for https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/configure-limit-parsys/touchui-limit-parsys.js? This clientlib is supposed to be loaded in the outer frame. AFAIK there is no easy way to configure additional categories to be loaded there.

For clientlibs being used on either dialogs/page properties and also within the actual page the OptInt totally makes sense, but for this particular case I don't know how to achieve that.
@davidjgonzalez Any ideas?

**Comment by davidjgonzalez** [comment]
@kwin the general pattern/guidance will be to embed the ACS Commons categories in a "Wrapper" ClientLibrary which in turn specifies the "AEM" categories. See the example Wrapper ClientLib here:

https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1715/files#diff-6a4190fced2f9858cabd036f36231453

The wrapper approach should result in the same injection points as before, just requiring the Wrapper CL definition to be deployed. Am i missing something?

**Comment by kwin** [comment]
@davidjgonzalez Thanks for that hint. But IMHO this is a different approach than using the https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/source/dynamic-loader.js together with the servlet from https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/DynamicTouchUiClientLibraryServlet.java. Why is the latter still used for https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/configure-limit-parsys/.content.xml?

I like your new approach better instead of using the OSGi configuration from https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/a8ecf5b18ef43cdf12b53f95e6498b9f86c7d240/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/DynamicTouchUiClientLibraryServlet.java#L47 to specify which clientlib categories to load. Do you plan to remove the dynamic loader feature completely?

Having two different mechanism in place seems too complex to me.

**Comment by davidjgonzalez** [comment]
See #1753
