### ISSUE TITLE
ACS AEM Commons 4.0.0 Release

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1629]
**_ACS Commons 4.0.0 will be a breaking release._**

* ACS Commons 4.0.0 supported AEM versions: **6.3.x, 6.4.x and 6.5.x** (dropping support for AEM 6.2). (6.5.x support is to the best of our ability given the current pre-release Load)

* `master` will act as the release branch
* Moving forward NO issues should be merged unless they address issues outlined in this issue (ONLY PRs directly in support fo 4.0.0 release are to be merged to master until 4.0.0 is release)

#### The following list defines the issues to included (and are required) to release 4.0.0

- [x] Decide if its ACS Commons 4.0.0 or 5.0.0 (see discussion w JE) **(Decision: AEM Commons 4.0.0)**
- [x] Support short-names on TLDs (fixed via https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1748)
- [x] Review and merge Disabling auto-on clientlibs by default https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1715 (Requires documentation; @davidjgonzalez will do this)
- [x] Revert to SCR Annotations (https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1741#issuecomment-461836942)
- [x] Handle XSS API import range for AEM 6.5 compatability (https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1743)
- [x] Fix Http Cache MBean errors at startup (https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1747) (fixed via https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1741)
- [x] Align osgi property names, and align name felix namehints for HttpCache (fixed via https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1749)

> In preparation for the 4.0.0 release, ONLY required bug-fixes are to be merged in for the 4.0.0. Else, they will be deferred to 4.0.2 or 4.1.0 (whichever comes first)

#### Functional breaking changes

* Auto-on clientlibs described in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1715

### Major Package Changes (API breaking changes)

* com.adobe.acs.commons.fam
* com.adobe.acs.commons.functions
* com.adobe.acs.commons.http   
* com.adobe.acs.commons.httpcache.store
* com.adobe.acs.commons.json 
* com.adobe.acs.commons.mcp.form   
* com.adobe.acs.commons.mcp.util   
* com.adobe.acs.commons.quickly    
* com.adobe.acs.commons.quickly.results  
* com.adobe.acs.commons.redirectmaps.models  
* com.adobe.acs.commons.synth.children    
* com.adobe.acs.commons.util   
* com.adobe.acs.commons.wcm     
* com.adobe.acs.commons.workflow.bulk.execution.model
* com.adobe.acs.commons.workflow.bulk.removal 
* com.adobe.acs.commons.workflow.synthetic 
* com.adobe.acs.commons.xss 

* HTTP Cache JMX object names have changed:
```
Property jmx.objectname on component com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl has different values (was: {com.adobe.acs.httpcache:type=HTTP Cache Engine}, is: {com.adobe.acs.commons.httpcache:type=HTTP Cache - Engine})
Property jmx.objectname on component com.adobe.acs.commons.httpcache.store.jcr.impl.JCRHttpCacheStoreImpl has different values (was: {com.adobe.acs.httpcache:type=JCR HTTP Cache Store}, is: {com.adobe.acs.commons.httpcache:type=HTTP Cache - JCR Cache Store})
Property jmx.objectname on component com.adobe.acs.commons.httpcache.store.mem.impl.MemHttpCacheStoreImpl has different values (was: {com.adobe.acs.httpcache:type=In Memory HTTP Cache Store}, is: {com.adobe.acs.commons.httpcache:type=HTTP Cache - In-Memory Cache Store}}
```

/cc @justinedelson @heervisscher @kwin @niekraaijmakers @joerghoh @badvision

**Comment by davidjgonzalez** [comment]
@badvision , @joerghoh , @heervisscher - can you jot down what is breaking in 4.0.0 using the template above?

**Comment by joerghoh** [comment]
* New contributions need to use OSGI annotations, the support for the SCR annotations has been removed.
* org.apache.sling.commons.json package can no longer be used in acs-aem-commons; com.google.gson should be used as replacement (proper package imports already available)

**Comment by badvision** [comment]
- #1568 - Removal of all deprecated classes and methods in ACS Commons
-  Conversion to GSON instead of deprecated Sling JSON library
- #1555 - Updated dependencies to 6.3 bundle versions

**Comment by heervisscher** [comment]
Classes impacted by the changed OSGi property-names  (because hyphens are not supported in OSGi R6)
ErrorPageHandlerImpl
HealthCheckStatusEmailer
MonthlyExpiresHeaderFilter
WeeklyExpiresHeaderFilter
GroupHttpCacheConfigExtension
HttpCacheConfigImpl
ResourceTypeHttpCacheConfigExtension
HttpCacheEngineImpl
NamedTransformImageServlet
ResizeImageTransformerImpl
EnsureOakIndex
DispatcherFlusherServlet
DispatcherFlushRulesImpl
JcrPackageReplicationStatusEventHandler
EnsureGroup
DelegatingServletFactoryImpl
AemEnvironmentIndicatorFilter
AuthorUIHelperImpl
ComponentErrorHandlerImpl
CQIncludePropertyNamespaceServlet
WCMViewsFilter
WCMViewsServlet
WorkflowInstanceRemoverScheduler

**Comment by heervisscher** [comment]
I added this too in the CHANGELOG.md

**Comment by badvision** [comment]
Is it somehow possible that we can finish this one week from today?  It would be helpful to have some of these fixes and features available at Adobe Summit and they'll be building the software images very soon.

**Comment by heervisscher** [comment]
for me it is not fully clear what direction we are taking here.

**Comment by davidjgonzalez** [comment]
@justinedelson @heervisscher @kwin @niekraaijmakers @joerghoh @badvision 

Hand is finally pretty good - I took a spin through last night to see where we are wrt to 4.0.0 release.

We need to nail this down and only merge PR's directly in support of 4.0.0 (all these other non-crtical PRs are just noise in an already noisy process). I've outlined my understanding of what the outstanding   issues are (though i couldnt find GH issues for some?)

Does this look right? Can we check off specific items we know to be done/validated?

**Comment by kwin** [comment]
@davidjgonzalez I would recommend to also switch to `bnd-maven-plugin` instead of `maven-bundle-plugin`. Doing that in a minor release might not be a good idea. I mentioned this in https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1560#issuecomment-456719008 but this issue was resolved meanwhile. Should I create a dedicated new issue for that?

**Comment by badvision** [comment]
I can confirm our target is ACS Commons 4.0 for this work.  I will review the Granite main pom to see which dependencies it uses so we confirm we are using the same for 6.4 compatibility.

**Comment by davidjgonzalez** [comment]
@kwin sure - that'd be great if you could make a dedicated issue so we can track/close it out.
