### ISSUE TITLE
DispatcherFlusher using the Replicator for DELETE actions results in slow performance with big repositories.

### ISSUE THREAD

**Issue by jasper-s** [Adobe-Consulting-Services/acs-aem-commons#1630]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3.2.2
* [ ] ACS AEM Commons Version: 3.17.4
* [ ] Reproducible on Latest? yes

---
Clearing a big repository from the cache based on the dispatcher flush rules takes a long time. This can be resolved by avoiding to use the Replicator for delete actions.

A suggestion for improving speed is to avoid the Replicator for DELETE operations and instead use a HTTP request to the dispatcher to clear the cache. This avoids the Replicator calculating all paths to deactivate, and instead just removes the entire section of the repository from the cache.

In the process of trying this out, I ran into difficulties in getting my own DispatcherFlusher service bound to the DispatcherFlushRulesImpl component because of the _reluctant_ Reference Policy Option. It may be a good idea to make that _greedy_.

**Comment by davidjgonzalez** [comment]
@jasper-s making this greedy sounds fine - can you provide a PR?

**Comment by jasper-s** [comment]
Making this greedy is good for allowing custom implementations. 
Still seems like a good idea to allow using a HTTP client to issue DELETE requests. Something like

`CloseableHttpClient httpClient = HttpClients.createDefault();`
`HttpResponse response = Executor.newInstance(httpClient).execute(Request.Post("UrlHere").addHeader("CQ-Action", "DELETE").addHeader("CQ-Handle", path)).returnResponse();`

Any thoughts on that?

**Comment by davidjgonzalez** [comment]
@jasper-s are all those values derivable from the flush agents themselves? 

I dont think its a good idea to maintain the Dispatcher connection info in 2 places (Agent and elsewhere??).

Im not 100% clear your ask, are you asking:

1) If the ACS Commons existing Delete handling be updated to make a direct call?
2) If the ACS Commons should ADD a new "DIRECT DELETE" action that can be used to make a direct call?
3) Are you asking about this for a custom implementation that wouldnt ever go into ACS Commons?

**Comment by jasper-s** [comment]
@davidjgonzalez I'll try to be more precise.

These values are derivable from the Agents and their respective AgentConfig. It is indeed not a good idea to keep the info in seperate places.

I'm certainly asking for a solution in ACS Commons. This could be either with a config on the existing DispatcherFlusher, determining the delete type, or with an extra action like you say.
