### ISSUE TITLE
WCM Inbox Felix Console Plugin throws Traversal error

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1635]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4 (possibly earlier)
* [X] ACS AEM Commons Version: 3.19.0
* [X] Reproducible on Latest? yes

### Expected Behavior

WCM Inbox should list the inbox paths available for purging.

### Actual Behavior

WCM Inbox throws a traversal error and fails to query the inbox paths to purge.

```
19.12.2018 18:04:04.154 *WARN* [Thread-110] org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor Traversed 1000 nodes with filter Filter(query=select e.[jcr:path] as [jcr:path], e.[jcr:score] as [jcr:score], e. *from [nt:base] as a inner join [nt:base] as b on ischildnode(b, a) inner join [nt:base] as c on ischildnode(c, b) inner join [nt:base] as d on ischildnode(d, c) inner join [nt:base] as e on ischildnode(e, d) where name(a) = ‘wcm’ and isdescendantnode(a, ‘/home’) and name(b) = ‘notification’ and name(c) = ‘config’ and name(d) = ‘subscriptions’ and e.[type] = ‘page’ option(traversal OK) /* xpath: /jcr:root/home//wcm/notification/config/subscriptions/* [@type=‘page’] option(traversal ok) */, path=/home//*, property=[:localname=[wcm]]); consider creating an index or changing the query
```

### Steps to Reproduce

Invoke the ACS Commons WCM Inbox Web Console plugin (ensure you have enough nodes under /home to trigger the traversal) or Explain Query the query used [1] and see that it is a traversal.

[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/WCMInboxWebConsolePlugin.java#L81

Thanks to Sammit P. for identifying

**Comment by davidjgonzalez** [comment]
@justinedelson this appears to be a feature to support the clearing of Inbox tasks for ClassicUI - and i believe Inbox Tassk are now stored under /var/taskmanagement (or their respective projects folders) and not the rep:User.

Should we remove this feature for 4.0.0 (since it doesnt work)?  WDYT?

**Comment by badvision** [comment]
Classic UI is a dinosaur.  Kill it.

**Comment by justinedelson** [comment]
I'm fine removing this, but my preference would be to leave the plugin in place for 4.0.0 and just output something like "This web console plugin has been removed for performance reasons" when you navigate to it. That way there aren't questions about where it went (in case anyone is using it).

See https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1643

**Comment by trakeshkumar34** [comment]
Hi Justin,

I just want to more appropriate on the topic.

Yes, I have same warning message in my server which says as below:-

18.06.2019 23:53:05.942 *WARN* [Thread-414] org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor Traversed 2000 nodes with filter Filter(query=select e.[jcr:path] as [jcr:path], e.[jcr:score] as [jcr:score], e.* from [nt:base] as a inner join [nt:base] as b on ischildnode(b, a) inner join [nt:base] as c on ischildnode(c, b) inner join [nt:base] as d on ischildnode(d, c) inner join [nt:base] as e on ischildnode(e, d) where name(a) = 'wcm' and isdescendantnode(a, '/home') and name(b) = 'notification' and name(c) = 'config' and name(d) = 'subscriptions' and e.[type] = 'page' option(traversal OK) /* xpath: /jcr:root/home//wcm/notification/config/subscriptions/* [@type='page'] option(traversal ok) */, path=/home//*, property=[:localname=[wcm]]); consider creating an index or changing the query

The version of ACS Common package I'm using in my instance is 3.8.4. So, it will resolve the issue if I use higher of it?

Rakesh

**Comment by davidjgonzalez** [comment]
Rakesh - this is fixed (Ie the plugin is effectively removed) in v4.0.0 of acs commons. You should upgrade to 4.x if possible.

**Comment by trakeshkumar34** [comment]
Hi @davidjgonzalez,

Thanks a lot for the response.

So, now I'm planning to push the 4.x.x package in instance but the only worry is to understand the dependency of this package.

It would be great if you can share some info regarding this.

Rakesh

**Comment by davidjgonzalez** [comment]
@trakeshkumar34  check out ... https://adobe-consulting-services.github.io/acs-aem-commons/pages/releases/4-0-0.html

**Comment by trakeshkumar34** [comment]
Hi @davidjgonzalez,

Thanks for the link much needful.

Rakesh

**Comment by palbiez** [comment]
We have had the same error in AEM 6.5.1, ACS AEM 4.1 
`03.12.2019 01:02:34.835 *WARN* [Thread-903] org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor Traversed 1000 nodes with filter Filter(query=select e.[jcr:path] as [jcr:path], e.[jcr:score] as [jcr:score], e.* from [nt:base] as a inner join [nt:base] as b on ischildnode(b, a) inner join [nt:base] as c on ischildnode(c, b) inner join [nt:base] as d on ischildnode(d, c) inner join [nt:base] as e on ischildnode(e, d) where name(a) = 'wcm' and isdescendantnode(a, '/home') and name(b) = 'notification' and name(c) = 'config' and name(d) = 'subscriptions' and e.[type] = 'page' option(traversal OK) /* xpath: /jcr:root/home//wcm/notification/config/subscriptions/* [@type='page'] option(traversal ok) */, path=/home//*, property=[:localname=[wcm]]); consider creating an index or changing the query`

But WCM Inbox is deactivated. 
https://loalhost/system/console/wcm-inbox

>  This web console plugin has been removed as it is specific to the Classic UI. 

Is there any other option where we can find this Traversal Error?

**Comment by dpoplawski** [comment]
We upgraded to ACS version to 4.2.0 and are on AEM 6.4.4 and are still getting the WARN and after a certain amount of nodes an ERROR. WCM Inbox is deactivated also. 

*WARN* [Thread-115] org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor Traversed 1000 nodes with filter Filter(query=select e.[jcr:path] as [jcr:path], e.[jcr:score] as [jcr:score], e.* from [nt:base] as a inner join [nt:base] as b on ischildnode(b, a) inner join [nt:base] as c on ischildnode(c, b) inner join [nt:base] as d on ischildnode(d, c) inner join [nt:base] as e on ischildnode(e, d) where name(a) = 'wcm' and isdescendantnode(a, '/home') and name(b) = 'notification' and name(c) = 'config' and name(d) = 'subscriptions' and e.[type] = 'page' option(traversal OK) /* xpath: /jcr:root/home//wcm/notification/config/subscriptions/* [@type='page'] option(traversal ok) */, path=/home//*, property=[:localname=[wcm]]); consider creating an index or changing the query

**Comment by akashramchandani** [comment]
Hi All,

Based on earlier updates, we spent effort in upgrading to latest ACS versions, but still no luck with resolving issue.

@justinedelson Can this be fixed? Can we get some updates at least?

@All,  Any other suggestions that can be done to get rid of this error.

13.01.2020 12:21:29.559 *WARN* [Thread-1618] org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor Traversed 7000 nodes with filter Filter(query=select e.[jcr:path] as [jcr:path], e.[jcr:score] as [jcr:score], e.* from [nt:base] as a inner join [nt:base] as b on ischildnode(b, a) inner join [nt:base] as c on ischildnode(c, b) inner join [nt:base] as d on ischildnode(d, c) inner join [nt:base] as e on ischildnode(e, d) where name(a) = 'wcm' and isdescendantnode(a, '/home') and name(b) = 'notification' and name(c) = 'config' and name(d) = 'subscriptions' and e.[type] = 'page' option(traversal OK) /* xpath: /jcr:root/home//wcm/notification/config/subscriptions/* [@type='page'] option(traversal ok) */, path=/home//*, property=[:localname=[wcm]]); consider creating an index or changing the query

**Comment by trakeshkumar34** [comment]
Hi Akash,

Do you use classic UI?

Rakesh

**Comment by akashramchandani** [comment]
We don't use classic UI. Rarely for something important, we use classic UI.
Just trying to understand more, when does this occur. Is it when we access classic UI? Or when purging activity takes place.

Suggestion, can't we create index here that can improve performance and avoid this issue?

**Comment by palbiez** [comment]
We spoke with Adobe directly. Workaround is
Stop the component in ` /system/console/components ->notification: com.day.cq.wcm.notification.impl.NotificationManagerImpl` and to keep it stopped by using ACS-commons component disabler 
https://adobe-consulting-services.github.io/acs-aem-commons/features/osgi-disablers/component-disabler/index.html

**Comment by ruchimishra** [comment]
Hello @palbiez,

We also have ACS Commons 4.0.0 but still, see this error in our logs.
You have mentioned that the workaround was provided by Adobe. Just wanted to understand if this has been logged in somewhere so that we can also check with our AMS team to make sure we implement the same. Not sure what function this component serves.

Thanks
Ruchi

**Comment by trakeshkumar34** [comment]
Hi Ruchi,.

Just wanted to know in your application do you use any classic ui
components??


Rakesh

**Comment by palbiez** [comment]
@ruchimishra 
This component is deprecated and used by old UI. Normally in the WCM inbox you can see messages from AEM. But this inbox is not longer in use. 
As mentioned the wordaround is to deactivate inbox service in AEM Admin. 

Stop the component in /system/console/components ->notification: com.day.cq.wcm.notification.impl.NotificationManagerImpl and to keep it stopped by using ACS-commons component disabler
https://adobe-consulting-services.github.io/acs-aem-commons/features/osgi-disablers/component-disabler/index.html

**Comment by ruchimishra** [comment]
@trakeshkumar34, @palbiez,
Our content authors don't use the classic UI. There could be some random usage but we certainly don't need the inbox. Will disable it.

Thanks a lot for the help and input.

**Comment by justinedelson** [comment]
Just to be clear, it appears that most of the comments in this thread *do not* relate to ACS AEM Commons. The query used by the WCM Inbox web console plugin (which was removed in 4.0.0) were

> /jcr:root//element(*, rep:User)/wcm/notification/config/subscriptions/element(*)[@channel='inbox'] 

And

>  /jcr:root//element(*, rep:User)/wcm/notification/inbox

The queries in the last handful of comments here are:

> /jcr:root/home//wcm/notification/config/subscriptions/*[@type='page']
