### ISSUE TITLE
[Blocks v4.0.0] Switch to OSGI annotations breaks asset ingestion 

### ISSUE THREAD

**Issue by anasidorovich** [Adobe-Consulting-Services/acs-aem-commons#1641]
AEM 6.4 SP2 
ACS AEM Commons Version: 3.19.1-SNAPSHOT
Reproducible on Latest? yes

### Expected Behavior
Ingestor tasks should be performed by MCP (Manage Controlled Processes) dashboard 

### Actual Behavior
Asset ingestion does not work properly

### Steps to Reproduce

1 install the latest acs-commons bundle
2 Go to /etc/acs-commons/manage-controlled-processes.html
The list of process is not loaded due to exception:
The requested URL /etc/acs-commons/manage-controlled-processes/jcr:content.list.json resulted in an error in org.apache.sling.servlets.get.DefaultGetServlet.
3 review error.log:

```
20.12.2018 12:58:15.106 *ERROR* [Background Update com.adobe.acs.acs-aem-commons-bundle (552)] com.adobe.acs.acs-aem-commons-bundle bundle com.adobe.acs.acs-aem-commons-bundle:3.19.1.SNAPSHOT (552)General problem with descriptor entry '/OSGI-INF/com.adobe.acs.commons.contentfinder.querybuilder.impl.viewhandler.QueryBuilderViewHandler.xml' (org.apache.felix.scr.impl.parser.ParseException: Exception during parsing)
org.apache.felix.scr.impl.parser.ParseException: Exception during parsing
	at org.apache.felix.scr.impl.xml.XmlHandler.startElement(XmlHandler.java:434) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr.impl.parser.KXml2SAXParser.parseXML(KXml2SAXParser.java:76) [org.apache.felix.scr:2.1.0.B008]
	at org.apache.felix.scr
```

**Comment by badvision** [comment]
I believe we rolled back the changes -- is this still happening?

**Comment by anasidorovich** [comment]
Yes, is still reproducible

**Comment by badvision** [comment]
This should be resolved now with the switch to OSGi 7.  Can you confirm?

**Comment by anasidorovich** [comment]
Fixed
