### ISSUE TITLE
Asset Ingestor | Add include section

### ISSUE THREAD

**Issue by cylinder-y** [Adobe-Consulting-Services/acs-aem-commons#1644]
Currently user is able to exclude some specific folders, files, extensions that would be ignored during assets import:
![image](https://user-images.githubusercontent.com/23450886/50337388-04db0400-0522-11e9-87b3-3cd49891a419.png)

What if user is not able to analyze source content because it is too large? It is much better to provide what user wants to import.

In our case we have large filesystem with different content : video, text files and etc. We need to iterate over all file system and import only images. In this case I want to configure specific extensions to be migrated.

I guess it would be useful to have include configuration for files, folder and extensions.

I see two possible options:

1. Add additional 3 field with Inlcude label
2. Change behavior of the Exclude section, because currently Ingestor tools have too much configuration fields. 

For the second option we could rename Exclude section to the Filter section and use the following processing logic:

- If we want to include file, folder or extension we just write it into fields
- If we want to exclude file, folder, or extension we will write it with minus sign '-' into field:

![image](https://user-images.githubusercontent.com/23450886/50337910-9a2ac800-0523-11e9-9054-5ccb0b197a71.png)

Also exclude logic should have priority over include logic

What do you think?

**Comment by badvision** [comment]
I think it sounds fantastic, we just need to make sure to update the docs so people understand it and also change the defaults so the behavior still works the same if they leave the values unchanged.  I like the way you're going about this.  Admittedly when I wrote the exclude stuff it's because my sample size was small -- about 30 gb of vacation and family photos. 😄  Obviously you're working with a much larger sample size to validate the requirements of this one.

**Comment by cylinder-y** [comment]
HI @badvision, 

What solution is more suitable from your point of view?
1. Add new fields
2. Change existing fields

**Comment by cylinder-y** [comment]
stale, do not close it, please

**Comment by cylinder-y** [comment]
Hello [@badvision how could I update documentation?

**Comment by cylinder-y** [comment]
Hello @badvision PR is created: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1978
PR for documentation updates: Adobe-Consulting-Services/adobe-consulting-services.github.io#167
