### ISSUE TITLE
EndpointService does not allow overriding the ContentType and therefore cannot be used with Adobe Target

### ISSUE THREAD

**Issue by BillBeckerAtBounteous** [Adobe-Consulting-Services/acs-aem-commons#1649]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _6.4_
* [ ] ACS AEM Commons Version: _3.19.0____
* [ yes ] Reproducible on Latest? yes/no

### Expected Behavior

I want to be able to use the EndpointService class in order to post entities into Adobe Target.  I have an Abobe IO integration which is linked to Abobe Target.  When I post to endpoints such as "https://mc.adobe.io/{tenantId}/target/recs/entities" it appears that the posted data must have the content type "application/vnd.adobe.target.v1+json" specified.   The EndpointServiceImpl class hardcodes the Content-Type to "application/json" at line 231 and there appears to be no way to override it.

### Actual Behavior

When I pass in a Content-Type header into performIO_Action(), I expect the http operation will use that header value instead of passing the default value "application/json".  What actually happens is there are two entries named "Content-Type" and "content-type" added to the header.  Case sensitivity does not seem to be a factor.  Abobe Target rejects the posted entity because my posted payload contains the wrong Content-Type header value.

### Steps to Reproduce

* Install aem acs commons package.
* Configure Adobe I/O Integration Configuration in configMgr with authentication credentials.
* Configure Adobe I/O Endpoint Factory Configuration to POST to https://mc.adobe.io/{tenantId}/target/recs/entities.
* Create any AEM service or servlet and add a reference to the EndpointService.
* Call the EndpointService's performIO_Action() method, passing a valid json object and a header with Content-Type "application/vnd.adobe.target.v1+json".  The operation fails with an UnsupportedMediaType exception because "application/json" (the default value) is not an acceptable value.

### Links
http://developers.adobetarget.com/api/recommendations/#operation/saveEntity
https://adobe-consulting-services.github.io/acs-aem-commons/features/adobe-io-apis/index.html

**Comment by HitmanInWis** [comment]
I believe this request was resolved by https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1657

@BillBeckerAtBounteous please verify.

**Comment by BillBeckerAtBounteous** [comment]
That's correct.   I opened this second PR which is essentially a copy of the first one.  Only difference is I fixed the branch name.  Because the original code is now already merged, I suppose this PR can be declined.
