### ISSUE TITLE
[Blocks v4.0.0] Default values from OSGI annotations (OCD) are not injected in activate methods.

### ISSUE THREAD

**Issue by Sc0rpic0m** [Adobe-Consulting-Services/acs-aem-commons#1652]
Sorry for the brief issue instead of detailed. But it's christmas and I don't want to spend too much time, and I just want to flag this. I can provide more details later.

## Required Information

AEM 6.3 / 6.4

### Expected Behavior

On the activate method of services, with a ObjectClassDefinition object, using the new annotations, the object returns default values as specified by the @ObjectClassDefinition / @AttributeDefinition.

### Actual Behavior

The default values are not returned, only values present are returned.

### Steps to Reproduce

Examples: (start AEM in debug mode and attach IDE debugger)
com.adobe.acs.commons.fam.impl.ThrottledTaskRunnerImpl > activate line 316

Specified values in OSGI configs are being picked up, but the default values from the config are ignored.

I also faced this with the HTTP cache module where I tried to leverage this mechanism instead of the old Map<String,Object properties.

**Comment by joerghoh** [comment]
For this specific example:

```
    @AttributeDefinition(name = "Max cpu %", description = "Range is 0..1; -1 means disable this check", defaultValue = "0.75")
        int max_cpu();
```

I don't think that '0.75' can be converted safely to an int ...

**Comment by Sc0rpic0m** [comment]
Seems to me, that on felix scr-2.1.0, this fix is not present.
Not sure from which version above mentioned fix is introduced. Let me check on AEM 6.5 which version is present and if the problem is still there.

**Comment by Sc0rpic0m** [comment]
I checked on 6.4, SP 2 and 3, both versions of the felix src plugin are still 2.1.0 :(

**Comment by Sc0rpic0m** [comment]
Ok on AEM 6.5, we are using the latest and greatest, so then it works fine. Is 4.0.0 release only meant for AEM 6.5? Because then we can close this bug I guess.

**Comment by davidjgonzalez** [comment]
I think this is the ~same issue as https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1645 where WF process labels are not coming through from default values.

This is odd since in ASC, new OSGi w/ OCD and defaults are used just fine: 
For (a simple) example the Labels "work" all the Computed Properties [1] in ASC and those are set via default values.

[1] https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/master/core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/ExpiredImpl.java

**Comment by joerghoh** [comment]
@Sc0rpic0m do you have more examples where this is happening? I haven't observed any problems with that, do you see in the bundles running inside AEM or during unittests?

**Comment by Sc0rpic0m** [comment]
Well. I pulled in your code and tested it on my machine, but still the same issue (on the throttled task runner). But it works for your machine. Which AEM + SP do you use? I tested this with fresh AEM instances as well (6.3 / 6.4 SP 2, 6.4 SP 3).

And just curious, which felix scr bundle is running on your aem, higher by 2.1.0 by any chance?
<img width="788" alt="bildschirmfoto 2019-01-03 um 22 44 14" src="https://user-images.githubusercontent.com/26429828/50663519-30420200-0faa-11e9-9544-9b88c0be505f.png">


I cannot send screenshots here but il put them on slack. I see that the activate method (call stack) still comes from the package org.apache.felix.scr.. is this correct as impl bundle?
I just need 1 instance where it works and then I can work from there I guess.

**Comment by Sc0rpic0m** [comment]
What I can find on the throttled task runner that works is the default value on the interface method:

` @AttributeDefinition(name = "Max threads", description = "Default is 4, recommended not to exceed the number of CPU cores",defaultValue = "4")
        int max_threads() default 4;`

That seems to make it work. Is this the way forward?
