### ISSUE TITLE
Improve handling of OCD classes in unittests

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#1665]
In the process of the rewrite to OSGI r6 annotations, we often converted the unittests in a 1:1 approach. That means we often have this setup:

```
Config config = mock (Component.Config.class);
when (config.configSetting()).thenReturn(sometValue);
...
myComponent.activate(config);
```

This works, but only if you don't rely on the default values of these configuration (have to figure out if this only applies to configuration items with the ```defaultValue``` property in the ```@AttributeDefinition```annotation or also applies to all methods with a default value).

It definitely works if there the component is activated by OsgiMock/SlingMock. So this pattern works

```
@Rule 
public SlingContext context = new SlingContext();

...
MyComponent component = new MyComponent();
Map<String,Object> properties = new Hashmap<>();
// put your custom properties here
context.injectRegisterActivate(component, properties);
```

**Comment by davidjgonzalez** [comment]
Closing due to revert back to SCR: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1741
