### ISSUE TITLE
OSGI r6: Use of the @ObjectDefinitionClass configuration classes in the activate method

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#1666]
I found out that we have a lot of classes, which do have the ```@Designate(ocd=...)```annotation but this class is not used in the activate method; instead the classic signatures are used (either ```ComponentContext``` or ```Map<String,Object>```).

We should change this and use the class we configure for this class; I guess that the "old" signatures are still working correctly, but it makes sense to use the OCD class for it.

These 29 classes are affected by this:

HttpClientFactoryImpl.java
~~HttpCacheConfigImpl.java~~
~~ResourceTypeHttpCacheConfigExtension.java~~
~~HttpCacheEngineImpl.java~~
~~HttpCacheInvalidationJobConsumer.java~~
~~CaffeineStoreRegisterer.java~~
NamedImageTransformerImpl.java
NamedTransformImageServlet.java
JsonEventLogger.java
SyslogAppender.java
EnsureOakIndex.java
EnsureOakIndexManagerImpl.java
QuicklyEngineImpl.java
FlushRulesImpl.java
JcrPackageReplicationStatusEventHandler.java
ResourceResolverMapTransformerFactory.java
StaticReferenceRewriteTransformerFactory.java
TwitterAdapterFactoryRegisterer.java
EnsureGroup.java
EnsureServiceUser.java
DelegatingServletFactoryImpl.java
AemEnvironmentIndicatorFilter.java
AuthorUIHelperImpl.java
CQIncludePropertyNamespaceServlet.java
ComponentErrorHandlerImpl.java
FileImporter.java
PageRootProviderConfig.java
PagesReferenceProvider.java
SiteMapServlet.java

Update: If you want to contribute here, please reference your PR here and list the cases you handle there.

**Comment by Sc0rpic0m** [comment]
I will do this for the HTTP cache since I'm familiar with them and add default interface values:

HttpCacheConfigImpl.java
ResourceTypeHttpCacheConfigExtension.java
HttpCacheEngineImpl.java
HttpCacheInvalidationJobConsumer.java
CaffeineStoreRegisterer.java

**Comment by adamcin** [comment]
I can tackle the SyslogAppender and JsonEventLogger classes.

**Comment by davidjgonzalez** [comment]
Closing due to revert back to SCR: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1741
