### ISSUE TITLE
Build failure, master

### ISSUE THREAD

**Issue by maryia-tatarnia** [Adobe-Consulting-Services/acs-aem-commons#1679]
## Required Information

* [ ] AEM Version, including Service Packs
* [ ] ACS AEM Commons Version: 3.19.1
* [ ] Reproducible on Latest? yes

### Expected Behavior

Build is successful.

### Actual Behavior

Build fails cause of tests, master.
Pull request - 1678

### Steps to Reproduce

Run the build.

### Links

travis failure
https://travis-ci.org/Adobe-Consulting-Services/acs-aem-commons/builds/478368591

**Comment by cylinder-y** [comment]
As I see everything is OK with master branch. Could you please close that issue and fix unit tests in the scope of #1678 ?

**Comment by maryia-tatarnia** [comment]
Sure, will do
