### ISSUE TITLE
Use Autocloseable at all places

### ISSUE THREAD

**Issue by heervisscher** [Adobe-Consulting-Services/acs-aem-commons#1684]
Since AEM6.2 you can use Autocloseable when closing resourve resolvers ~and/or sessions~.
This removes code where this is done manually.

**Comment by joerghoh** [comment]
``javax.jcr.Session`` does not implement ``AutoCloseable`` :-)

**Comment by heervisscher** [comment]
Then only rr :-)

**Comment by heervisscher** [comment]
pr https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1690

**Comment by badvision** [comment]
Does this resolve all the cases in #1690 ?

**Comment by badvision** [comment]
@adamcin -- could your new query builder stuff also help here?

**Comment by adamcin** [comment]
@badvision `CloseableQueryBuilder` won't help with ResourceResolvers, but it's implemented in a way that allows you to use `try-with-resources` just like you would for a ResourceResolver or other `AutoCloseable` type.

**Comment by joerghoh** [comment]
I added a PR (#2086) to address the remaining locations where it's not yet implemented.

**Comment by joerghoh** [comment]
I think we covered all locations where it made sense to use try-with-resource for the ResourceResolver. 

Let's close this issue then.
