### ISSUE TITLE
Use of sling-constants

### ISSUE THREAD

**Issue by heervisscher** [Adobe-Consulting-Services/acs-aem-commons#1706]
With the change to OSGi-R6 there are a lot of hardcoded sling-literals.

Let's replace them with proper Sling-constants

**Comment by badvision** [comment]
Sounds good.  If you get to it before I do, please send PRs to the OSGi7 feature branch

**Comment by heervisscher** [comment]
why the R7-one?, not master?

**Comment by badvision** [comment]
Because our last round of changes was a bit disruptive to folks trying to work on other things such as asset ingestion.  Trying to keep the lanes separate this time.

**Comment by heervisscher** [comment]
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1717

**Comment by davidjgonzalez** [comment]
Closing due to revert back to SCR: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1741
