### ISSUE TITLE
ACS AEM Commons utility page headers broken

### ISSUE THREAD

**Issue by srcs91** [Adobe-Consulting-Services/acs-aem-commons#1709]
Issue FKA "User to CSV Exporter - Page Header is broken"

## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, : AEM 6.4.3.0
* [x] ACS AEM Commons Version: 3.19.0
* [x] Reproducible on Latest ? yes

### Expected Behavior

User to CSV Exporter page header / Breadcrumb bar breaks when I install Service Pack 3 in AEM 6.4.

### Actual Behavior

User to CSV Exporter Page header should be displayed.

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

1) Start a vanilla instance of AEM 6.4.
2) Install ACS Commons version 3.19.0.
3) Install Service Pack 3 on AEM 6.4.
4) Go to miscadmin console  and view the ACS commons user to CSV exporter page.
5) Header of the above page appears to be broken after SP3 installation.

### Links

NA

**Comment by davidjgonzalez** [comment]
Fixed via https://github.com/davidjgonzalez/acs-aem-commons/commit/cc32c5097209ea52162cb334af4f093d27be4a21
