### ISSUE TITLE
MCP: Data Importer not importing the multi valued fields properly. 

### ISSUE THREAD

**Issue by kunalgaba** [Adobe-Consulting-Services/acs-aem-commons#1710]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: __AEM 6.4 SP1_____
* [ ] ACS AEM Commons Version: _____3.19
* [ ] Reproducible on Latest? yes/no yes

### Expected Behavior

The data importer process of MCP should import the multi valued properties properly. 

### Actual Behavior

The multi value properties are not getting created correctly as in the name of the property created I see following characters - cq:tags@%5B%5D. Here "cq:tags" is the name of the property which was supposed to be created but the importer creates a property with a name - cq:tags@%5B%5D

### Steps to Reproduce

1. Run MCP tools Data importer process and provide data to import in the excel. 
2. In the excel, add a column for multi valued fields like cq:tags. The header in the excel is named as "cq:tags@[]" as per https://adobe-consulting-services.github.io/acs-aem-commons/features/utils-and-apis/data-api/index.html#structure
3. Upload the excel in data importer configuration, check "Overwrite only" option and unselect all checkboxes at the bottom. 
4. Run the importer and check the node properties in crx/de. 

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by shajiahmed** [comment]
I still see this issue, is there any update on this?

**Comment by badvision** [comment]
Nope, it had fallen off my radar.  Thanks for the ping!

**Comment by Vydeshramkumar** [comment]
I have the same issue.ACS-ARM-COMMONS v.4.5.2

**Comment by badvision** [comment]
Sorry folks, I don't have time to work on this.  I highly encourage you to do the following:
1) Read the contributing readme at the root of this project to learn how you can help ACS Commons
2) Fix the issue
3) Submit a pull request
4) ... ?
5) Profit!

-Brendan
