### ISSUE TITLE
ETag servlet filter (generating the ETag response header based on MD5 checksum)

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#1713]
To better support [conditional requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests) it would be nice if there would be an optional servlet filter  provided which generates the `ETag` response header based on the calculated MD5 checksum of the whole response.
That way the ETag would be stable among several publishers in a server farm for the same request path (as long as they deliver the same response) and would change whenever something changes about its content. Leveraging only the local properties of the current node would not consider i.e. code changes in the markup, therefore generating a checksum on top of the actual response is the only reliable way to get different values for different responses.

This is also mentioned in https://helpx.adobe.com/experience-manager/kb/optimizing-aem-site-caches.html#AEMPublishInstances.

If you use a dispatcher you would need to enable ETag header caching in addition (compare with https://helpx.adobe.com/experience-manager/dispatcher/using/dispatcher-configuration.html#CachingHTTPResponseHeaders)

**Comment by cwoeltge** [comment]
3 options come to my mind to realize this:
1) based on a hash of repository values
2) based on a simple last modified value
3) based on a hash of the response

1) 
Filter, needs management of relevant properties and nodes (e.g. exclude instance specific properties like jcr:created).
2) 
Filter, perhaps too straight forward as many changes don't change the last modified date.

1+2) are based on content - would send the same ETag for the same content, even after a deploy. So perhaps need some additional salt for the application version rendering.

3)
Would need to hash the full response and set a header - which would need a ResponseWrapper fetching and hashing the full response to set the header then. Effectively slow down all output.

So 1) content and a software version hash would sound best to me.

@justinedelson anything smarter in mind? any preferences?

**Comment by kwin** [comment]
I am currently preparing a PR for option 3. This is the only safe way how you can make sure that this really changes whenever the content changes. This is also IMHO the only reasonable option for HTML request. For larger responses like Images, CSS, JS it might make sense to also investigate other options. In any case the proposed filter can be configured with a path pattern, so it should be easy to restrict this to rendered HTML in the first place.

**Comment by kwin** [comment]
There is a PR already available for that.

**Comment by badvision** [comment]
I think there was a minor build issue on the PR otherwise good to go there.

**Comment by kwin** [comment]
@badvision Thanks for merging. Can you set a milestone for this?
