### ISSUE TITLE
Set mandatory short-name element on tld files

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#1716]
The latest master contains a lot of TLD files below https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/master/bundle/src/main/resources/META-INF. All of them reference the 2.1 taglib schema (http://java.sun.com/xml/ns/javaee/web-jsptaglibrary_2_1.xsd) in which the element `short-name` is mandatory.
Still the `short-name` is set in none of the TLD files, which leads to validation errors.

In the past all TLD files were generated only from annotations with the tld-generator annotation parser, but in commit https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/f3ba4f3dbeb23f8f8c92301ab3b2bb053c9fa275 all of those tld files were committed to the repo as well.

Please either fix the TLDs to make them have the mandatory `short-name` or preferably rely on TLD generation only.

**Comment by kwin** [comment]
I think this should be easy fix and I would like to see this in the 4.0.0 milestone. But maybe @badvision can answer, why those TLDs are no longer only generated but really committed to git (this feels redundant as we still have the TLD annotations)

**Comment by davidjgonzalez** [comment]
@badvision can you shed light on this?

**Comment by badvision** [comment]
The TLD generation stopped working and the files were committed in order to
patch the behavior.  The thinking was that jsp development is less likely
to occur and we're maintaining legacy tag libraries rather than development
new ones.

**Comment by kwin** [comment]
Ok, if it stopped working there is a lot more code (i.e. annotations and also plugins) you should get rid of.
