### ISSUE TITLE
Use bnd-maven-plugin instead of maven-bundle-plugin

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#1718]
The `bnd-maven-plugin` (https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin) and the `bnd-baseline-maven-plugin` (https://github.com/bndtools/bnd/tree/master/maven/bnd-baseline-maven-plugin) are nowadays better maintained than the `maven-bundle-plugin`and are always released along with the underlying `bnd` (which is also the foundation for `maven-bundle-plugin`). Also the former is designed much more in line with the Maven build life cycle (further information in https://blogs.paremus.com/2015/03/announcing-the-bnd-maven-plugin/).
Also Apache Sling tries to move away from `maven-bundle-plugin` (http://apache-sling.73963.n3.nabble.com/hackathon-bnd-maven-plugin-vs-maven-bundle-plugin-td4086273.html).

There are a few important differences to the `maven-bundle-plugin` to consider while migrating:

1. Packages are no longer automatically exported (but there is a handy directive for exporting all versioned packages)
1. In-POM instructions are supported but need to be enclosed in a `CDATA` section
1. Certain pom elements no longer end up automatically as manifest attributes (compare with https://github.com/bndtools/bnd/issues/2447, supposed to be fixed with version 4.2)

This was also mentioned in https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1560#issuecomment-456720819

**Comment by davidjgonzalez** [comment]
@kwin removing this a 4.0.0 blocker as maven-bundle-plugin does work. Please correct me if im missing something :)

Its worth noting as well that the productized aem-project-archetype still uses the maven-bundle-plugin, so it's reasonable to wait for that to get updated resulting in more mainstream adoption of its use (vs creating a barrier for AEM community members to engage w the project). We can revisit the pros/cons of this in 4.1.0 though.

**Comment by joerghoh** [comment]
Archetype 21 is using the maven-bnd plugin, so maybe it's time to proceed here now.

**Comment by badvision** [comment]
Sounds like a good idea since we should probably do what the archetype is doing as much as possible.

**Comment by joerghoh** [comment]
@kwin do you have a PR read for this already? I would start working on it otherwise.

**Comment by kwin** [comment]
@joerghoh I did not start working on that yet. My focus right now  is rather https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2043.

**Comment by kwin** [comment]
There is a draft in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2423. I will pick it up from there and try to finalize this.
