### ISSUE TITLE
HTTP Cache Factories do not have correct names in /confMgr

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#1720]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.3
* [x] ACS AEM Commons Version: 4.0.0-SNAPSHOT (`master`)
* [ ] Reproducible on Latest? On master

### Expected Behavior

The names in /system/console/confMgr should be accurate and meaningful.

### Actual Behavior

The names in /confMgr are the same for several  

### Steps to Reproduce

Install latest from master and goto  /system/console/confMgr 

![image](https://user-images.githubusercontent.com/1451868/51718380-fc8b5280-2012-11e9-92f1-092e8d3e0b2d.png)

### Links

Looks like this is because OCD definitions are shared between impl's. Im not sure how to remedy this without copying the impl and updating the keys. In the case of the `KeyValueConfig` it seems odd these 4 HttpCacheConfigExtension would use the same one; ie I think this is a bug in the move to new OSGi annotations for HTTP Cache. Not sure about the first duplication.

/cc @niekraaijmakers

**Comment by kwin** [comment]
Could it be related to http://apache-felix.18485.x6.nabble.com/Using-webconsole-name-hints-with-OSGi-DS-annotations-td5020184.html?

**Comment by niekraaijmakers** [comment]
Nice find kwin, I will try this one. If not, I will have to duplicate the exact same generic OCD 4 times :(

**Comment by kwin** [comment]
To me it just seems that the necessary name hints are just missing (e.g. in `ValueMapValueHttpCacheConfigExtension`)

**Comment by niekraaijmakers** [comment]
I think your right. I will try this out once I got some time (should be soon) and  let you know the result.. if it works we'll use it.

**Comment by niekraaijmakers** [comment]
I cannot get it to work. What about you Konrad? If not, we have to eat copy pasta for dinner I'm afraid.

**Comment by davidjgonzalez** [comment]
🍝

**Comment by kwin** [comment]
http://felix.apache.org/documentation/subprojects/apache-felix-web-console.html#configuration-factories

**Comment by niekraaijmakers** [comment]
Ah Konrad, many thanks. Not sure how long we can keep the PR unmerged for your ticket. But greatly appreciated.

**Comment by davidjgonzalez** [comment]
Fixed via and closing due to revert back to SCR: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1741
