### ISSUE TITLE
QueryBuilderViewHandler incorrectly registered as OSGi component

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#1744]
The property `sling.servlet.paths` is incorrectly set in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/24486e39452401d149493786c998247653963a08/bundle/src/main/java/com/adobe/acs/commons/contentfinder/querybuilder/impl/viewhandler/QueryBuilderViewHandler.java#L47. The `properties` element is supposed to have a filename as value (https://osgi.org/javadoc/osgi.cmpn/7.0.0/org/osgi/service/component/annotations/Component.html#properties--). In case you want to set a property to a literal you have to use https://osgi.org/javadoc/osgi.cmpn/7.0.0/org/osgi/service/component/annotations/Component.html#property-- instead.

Also most probably there should be an explicit service given with which this component is registered because by default

> ...the service types for this Component are all the directly implemented interfaces of the class being annotated.

(https://osgi.org/javadoc/osgi.cmpn/7.0.0/org/osgi/service/component/annotations/Component.html#service--)

**Comment by davidjgonzalez** [comment]
Closing as we are reverting to SCR https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1741
