### ISSUE TITLE
ddpathfield xtype not working properly.

### ISSUE THREAD

**Issue by itsmevarun** [Adobe-Consulting-Services/acs-aem-commons#176]
Hi ,

I am facing a small issue with the ddpathfield xtype (https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/a1d2050ab766f0456c9988329a8e4f98bf262d0) right now .It works properly if I normally drag a file inside the field  , but if I remove the file again and then again dragging another file to that same section , it is not allowing me to do so . Below are the steps  with which you can relate my issue.
1. Use a DDpath xtype inside a dialog , 

2 Create a new pathfield and Drag any random  file inside the  field and then save the dialog. The file is saved .
1. Open the dialog again and delete the field just created in last step , without clicking on save , add a pathfield again and try to drag a file  , (It does not allow me to do so ).

4.If after removing the pathfield I save and then reopen dialog and add the pathfield , I am able to drag the file inside that .

Hope I was able to explain my problem , Can anyone help me with the issue I am facing .

Thanks,

Varun

**Comment by Divya-Sekar** [comment]
Hi, I am facing this same issue in my project. I installed latest version of ACS common package 2.3. But still this issue is coming. Could you please provide me the solution?

**Comment by davidjgonzalez** [comment]
Can you please provide exact details of what is not working and your overall context (Aem version, any errors, etc)

**Comment by justinedelson** [comment]
Since this issue was fixed some time ago, I'd suggest creating a new one
