### ISSUE TITLE
MCP - URL Asset Import date columns not working as intended

### ISSUE THREAD

**Issue by francoisINM** [Adobe-Consulting-Services/acs-aem-commons#1765]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.4 SP3
* [ ] ACS AEM Commons Version: 3.19
* [ ] Reproducible on Latest? yes

### Expected Behavior
Header column with the @date should store as a date in the metadata.

### Actual Behavior
if you have a @date and the content is like 2016-02-12T14:47:41.922-05:00
the metadata isn't imported at all.

if you set the cell to be a date in excel, and have an actual date, the date is being store as a binary!

### Steps to Reproduce

Simply include a column as a date with data in it. such as:
dc:modified@date

value 
2016-02-12T14:47:41.922-05:00 (this is skipped)
1980-03-14 (this is imported as a binary instead of date)

**Comment by ahmed-musallam** [comment]
I see this issue as well.

**Comment by badvision** [comment]
It's not actually a bug, it's a feature request.  Reason I say this is that Excel doesn't actually recognize your DB date format as anything other than General.  If it were to format the cell as a date then this wouldn't actually be an issue.  I'll see if I can detect DB date formats since they're likely common all the same.

**Comment by badvision** [comment]
augh, ok so it's both a bug (date should be calendar objects, easy fix) and a feature request (add support for DB date format)

**Comment by badvision** [comment]
Not sure why I named that branch incorrectly, but it fixes this issue.  Sorry for the confusion.  Let me know if this works for you folks.  There's also now a unit test for the data importer tool.

**Comment by joerghoh** [comment]
@badvision can you provide the fix version for this?

**Comment by badvision** [comment]
It was fixed in 4.1.0
