### ISSUE TITLE
Horizontal Scroll bar and Metadata field names are not fixed in Asset Report

### ISSUE THREAD

**Issue by ShivangiHiray21** [Adobe-Consulting-Services/acs-aem-commons#1770]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3 Service Pack 2
* [ ] ACS AEM Commons Version: 3.18
* [ ] Reproducible on Latest? yes/no Yes

### Expected Behavior

Once we execute the report , result will be displayed on page and the scrollbars will be visible.
1.The column heading for the report should be fixed even if we scroll down to the bottom.
2.For first few records , there should be some way to scroll to right if the number of column are more. As in existing feature the horizontal scroll bar appears only when we scroll to the bottom.

### Actual Behavior

1.If the report is executed , and page size is 20 then after scrolling down to the bottom column heading cannot be seen. 
To check the column heading we have to scroll up.
2.For the first few records the horizontal scroll bar is not visible so we cannot scroll to the right. In order to scroll to the right , first we have to scroll to bottom and then the horizontal scroll bar will appear. 

### Steps to Reproduce

Steps are mentioned in the attached document where some initial details about the custom report has also been provided.
[SPOT-718.docx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/2930715/SPOT-718.docx)

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by ShivangiHiray21** [comment]
It is a Production Issue.. Could you please let me know when this functionality will be availqble...

**Comment by ShivangiHiray** [comment]
davidjgonzalez Any update on this
