### ISSUE TITLE
Report does not work when search parameter has '&' in it

### ISSUE THREAD

**Issue by ShivangiHiray21** [Adobe-Consulting-Services/acs-aem-commons#1772]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3, Service Pack 2
* [ ] ACS AEM Commons Version: 3.18.2
* [ ] Reproducible on Latest? yes/no yes

### Expected Behavior

Report should work even if the search parameters contains special character .

### Actual Behavior

Report does not work when search parameters contain special character. In my case search parameter contains '&' and report query is converting it to 'amp;' and that is the reason query is not working.

### Steps to Reproduce

Steps and initial background of the issue mentioned in attached document.
[SPOT-720.docx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/2934497/SPOT-720.docx)

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by ShivangiHiray21** [comment]
It is a Production Issue.. Could you please let me know when this functionality will be available...

**Comment by klcodanr** [comment]
Hi @ShivangiHiray21 -- This is an "expected feature" The problem is that handlebars is escaping the ampersand. For text fields, I would recommend encoding the parameters in triple brackets, e.g. 

```SELECT * FROM [cq:Page] AS s WHERE ISDESCENDANTNODE([{{path}}]) {{#if template }} AND [jcr:content/cq:template] LIKE '{{{template}}}' {{/if}} ORDER BY {{order}}``` 

instead of 

```SELECT * FROM [cq:Page] AS s WHERE ISDESCENDANTNODE([{{path}}]) {{#if template }} AND [jcr:content/cq:template] LIKE '{{template}}' {{/if}} ORDER BY {{order}}```
