### ISSUE TITLE
com.google.guava version introduced by 4.0.0 conflicts with the one comes with AEM

### ISSUE THREAD

**Issue by kelvinxzf** [Adobe-Consulting-Services/acs-aem-commons#1786]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3.3.2
* [ ] ACS AEM Commons Version: 4.0.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

Before acs common 4.0.0, `com.google.common.base` was resolved to the version (15.0.0) that comes with OOTB bundle`com.adobe.granite.osgi.wrapper.guava` 

### Actual Behavior

After acs common 4.0.0, seeing this `com.google.common.base,version=[27.0,28) -- Cannot be resolved` from custom bundle

### Steps to Reproduce

1. Have your custom code import any package under `com.google.common.base` like `com.google.common.base.Enums`
2. With acs common prior to 4.0.0, it is resolved to the version of 15.0.0 that comes with OOTB `com.adobe.granite.osgi.wrapper.guava`
3. Upgrade ace common to 4.0.0, and see `com.google.common.base,version=[27.0,28) -- Cannot be resolved` from custom bundle. POM is referencing acs common like this,
 
`<dependency>
               <groupId>com.adobe.acs</groupId>
                <artifactId>acs-aem-commons-bundle</artifactId>
                <version>4.0.0</version>
                <scope>provided</scope>
</dependency>`

### Links

Might be related to https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/4addcbffa110e191242437280253a080dde818de/pom.xml#L449

**Comment by kelvinxzf** [comment]
For our case, the workaround could be having the `uber-jar` dependency ahead of `com.adobe.acs` in core bundle's POM...but not sure why 4.0.0 introduces 27.0.1-jre version just for compilation purpose while AEM still holds 15.0.0 OOTB.

**Comment by justinedelson** [comment]
@kelvinxzf ACS AEM Commons does *not* use the Guava provided by AEM and has not for several versions (not just 4.0.0). Guava is embedded (and not exported).

**Comment by kelvinxzf** [comment]
@justinedelson we don't have explicit dependency on guava in our pom. It is introduced by the uber-jar. The internal bundle is `com.adobe.granite.osgi.wrapper.guava`.

**Comment by justinedelson** [comment]
Yeah, I meant to exclude the transitive dependency which is brought in via ACS AEM Commons. If #1788 is merged, the published pom for ACS AEM Commons would no longer have a declared dependency of Guava. But until that is done, you'd need to manually exclude it (or do what you are doing now).

**Comment by kelvinxzf** [comment]
What we did was moving acs commons bundle dependency behind uber-jar such that the ootb version would be picked up first.
