### ISSUE TITLE
Unable to deploy, get bundle dependency errors

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1807]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.3
* [x] ACS AEM Commons Version: 4.0.1-SNAPSHOT
* [X] Reproducible on Latest? yes

### Expected Behavior

Deploying the bundle should work

### Actual Behavior

Deploying the bundle does not work because dependencies are not met, mainly com.google.common and io.jsonwebtoken

Not sure but could this be related to recent changes @niekraaijmakers ?

**Comment by joerghoh** [comment]
From what I see on my local build, the maven-bundle-plugin runs before the maven-shade-plugin, so it doesn't know about the shading of these classes, thus it lists them as dependencies. It's more likely to be related to #1786
