### ISSUE TITLE
We are using picture tag in components and it seems that the staticReferenceRewriteTransformerFactory config is not working for scrset attribute of source tag

### ISSUE THREAD

**Issue by yadavm** [Adobe-Consulting-Services/acs-aem-commons#1822]
## Required Information

* [ ] AEM Version : AEM 6.4.3
* [ ] ACS AEM Commons Version: 3.14.10
* [ ] Reproducible on Latest? yes

### Expected Behavior

Upon creating com.adobe.acs.commons.rewriter.impl.StaticReferenceRewriteTransformerFactory all the configured Rewrite attributes should be prefixed with static host pattern

### Actual Behavior
Configured rewrite attributes are as below. But source:srcset attribute is not getting prefixed with static host name.
img:src,srcset
source:srcset
link:href
script:src

### Steps to Reproduce

Install below packages on author and publish
[developer-portal.ui.apps-0.0.1-SNAPSHOT.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/3054439/developer-portal.ui.apps-0.0.1-SNAPSHOT.zip)
[portal-content-package-04042019.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/3054441/portal-content-package-04042019.zip)

 in order:
1) developer-portal.ui.apps-0.0.1-SNAPSHOT.zip
2) portal-content-package-04042019.zip

Open http://localhost:4503/content/alexa-language-masters/en_US/alexa/alexa-skills-kit.html and view html source. You will observe that srcset of img tag is prefixed with domain value but srcset of source tag is not getting prefixed.

<picture>
--
  | <source media="(min-width: 768px)" srcset="/content/dam/alexa/en/hero-banner/ProactiveEvents-hero-feature._CB459524592_.png/_jcr_content/renditions/original">
  | <source media="(max-width: 767px)" srcset="/content/dam/alexa/en/hero-banner/ProactiveEvents-hero-feature._CB459524592_.png/_jcr_content/renditions/cq5dam.web.1280.1280.png">
  | <img class="banner-image" srcset="//amzdomain.xyz.com/content/dam/alexa/en/hero-banner/ProactiveEvents-hero-feature._CB459524592_.png/_jcr_content/renditions/original">
  | </picture>

**Comment by justinedelson** [comment]
@yadavm first off... thanks for providing the actual packages!!! Makes it super easy to see the problem.

The problem is that you aren't instructing the htmlparser to handle `source` elements.

Easy enough to fix. Just add `SOURCE` to `/apps/developer-portal/config/rewriter/developer/generator-htmlparser@includeTags` (Why this has to be upper case I can't explain).
