### ISSUE TITLE
[FEATURE] Add a tool that executes a JCR-SQL2 Query Result w/ Score Explanation for exploring index definitions

### ISSUE THREAD

**Issue by adamcin** [Adobe-Consulting-Services/acs-aem-commons#1825]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4+

### Expected Behavior

It is not currently easy to get the Lucene Score explanation field to assist with the development of oak index definitions.

Oak Lucene makes this debug-level information available as a virtual field in JCR-SQL2 queries, but this is really not accessible through the APIs used by existing Query explanation tools like QueryBuilder Debug servlet and the Query Performance tool, which usually interface with the AEM QueryBuilder or ResourceResolver.findResources() method, because of a desire to be query language-agnostic. These UIs and APIs would discard the virtual field if selected.

What is needed is a tool that fills the gap between the AEM Query Performance / Explain Query Tool, which renders the query plan for the input query (in any supported query language) into JCR-SQL2 syntax, and the CRX DE lite Query tool, which can execute a query but will only return matching nodes.

Given a JCR-SQL2 query, the tool should append the `[oak:scoreExplanation]` field to the SELECT clause, and render the results (the first 10 by default) as a table, with all selected columns, including jcr:path and oak:scoreExplanation

### Links

[Oak Query Lucene - Score Explanation](https://jackrabbit.apache.org/oak/docs/query/lucene.html#score-explanation)

**Comment by joerghoh** [comment]
Hm, this feature seems to be merged to master already with #1829, so we could close the ticket.

**Comment by davidjgonzalez** [comment]
Resolved via #1829

**Comment by abhishek140389** [comment]
how can i invoke this servlet?

**Comment by davidjgonzalez** [comment]
@abhishek140389 see mark's examples on his PR issue:

https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1829
