### ISSUE TITLE
ACS Commons report is giving exception "Exception executing report: org.apache.sling.api.scripting.ScriptEvaluationException" and the records are not displaying properly in result section for few queries

### ISSUE THREAD

**Issue by ShivangiHiray21** [Adobe-Consulting-Services/acs-aem-commons#1826]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3 and Service Pack 2 
* [ ] ACS AEM Commons Version: ACS -commons-3.18.2
* [ ] Reproducible on Latest? yes/no : Yes

### Expected Behavior

When we execute the report , records getting displayed in result section should be same as getting extracted in csv file  and in single page it number of records getting displayed should be same as given page size,

### Actual Behavior

In our case when we execute query , one exception is getting displayed and the records in result section are not proper. i.e there should be total 2000 records with the given search parameters but in result section not all records are getting listed. Only first 5 records are showing(in the title it say 1-20 which means page size is 20, it should display first 20 records
[SPOT-801.docx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/3057259/SPOT-801.docx)
) and then it skips few records and show remaining records. But in case we download the csv file , all records are properly extracted in sheet.

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, 
I have attached documnet which has steps to reproduce and the report package.
[mdlz-asset-report-1.0.3.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/3057262/mdlz-asset-report-1.0.3.zip)

[SPOT-801.docx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/3057260/SPOT-801.docx)

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by ShivangiHiray21** [comment]
This is a production issue and extremely urgent. Requesting to update asap.

**Comment by davidjgonzalez** [comment]
@klcodanr any thoughts?

**Comment by klcodanr** [comment]
Sorry @davidjgonzalez missed this one coming back from spring break. @ShivangiHiray21 -- I downloaded the package you provided and it _appears_ the problem is the number of columns is causing the report builder to hit the include limit. I was able to resolve this locally by doubling the `Number of Calls per Request` and `Recursion Depth` parameters for the Sling Main Servlet:

http://localhost:4502/system/console/configMgr/org.apache.sling.engine.impl.SlingMainServlet

Could you give that a try and see if it resolves the issue? If not could you provide a stack trace for the issue?

**Comment by ShivangiHiray** [comment]
@klcodanr  this is something related mandatory metadata properties. For those assets where mandatory property properties are missing this exception is thrown. And we are not getting anything in the logs.

**Comment by klcodanr** [comment]
@ShivangiHiray21 Strange, I was thinking perhaps it was a problem with the date field, but I just validated that it was able to successfully return results with a missing or String value (of course the date was blank).

Is there any way you could provide a sample asset which is having the issue?

**Comment by davidjgonzalez** [comment]
@ShivangiHiray21 still having this issue? If so can you provide a sample asset (per Dan's request above?)
