### ISSUE TITLE
'Paint Connections` break the view in 'Version Compare'

### ISSUE THREAD

**Issue by reggie7** [Adobe-Consulting-Services/acs-aem-commons#1835]
* [ ] AEM Version: `6.5`
* [ ] ACS AEM Commons Version: `4.0.0`
* [ ] Reproducible on Latest? yes

### Expected Behavior

Using **Paint Connections** option with other checkboxes leaves the connections pointing from source to target properly.

### Actual Behavior

When one uses **Paint Connections** option followed by other checkboxes the first connection starts in top-left corner of the console page.
Combining it with **Hide Unchanged** leaves connections pointing to empty space on the right side.

### Steps to Reproduce

1. Choose a page to work on, e.g. [Arctic Surfing in Lofoten](http://localhost:4502/editor.html/content/we-retail/language-masters/en/experience/arctic-surfing-in-lofoten.html),
2. Use its [Timeline](https://helpx.adobe.com/experience-manager/6-5/sites/authoring/using/working-with-page-versions.html) to create a version,
3. Add some random changes (I've removed a paragraph) under [Arctic Surfing in Lofoten](http://localhost:4502/editor.html/content/we-retail/language-masters/en/experience/arctic-surfing-in-lofoten.html),
4. Open [Version Compare](http://localhost:4502/etc/acs-commons/version-compare.html?path=/content/we-retail/language-masters/en/experience/arctic-surfing-in-lofoten),
5. Check **Paint Connections**,
6. Check **Hide Unchanged**,
7. Check **Hide Versions** (choose random ones).

**Hide Unchanged** will produse such artifacts:

![hide-unchanged-2](https://user-images.githubusercontent.com/5563546/56127589-d0320300-5f7d-11e9-80ce-d5a09a83c411.png)

**Hide Versions will yield:

![version-compare](https://user-images.githubusercontent.com/5563546/56127736-20a96080-5f7e-11e9-8fd3-2a82ff48097a.png)

Their combination:

![hide-unchanged](https://user-images.githubusercontent.com/5563546/56127752-2a32c880-5f7e-11e9-89e2-758c7c523df0.png)

**Comment by reggie7** [comment]
I'm on it BTW :)

**Comment by reggie7** [comment]
Fixed in [1908](https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1908).

**Comment by davidjgonzalez** [comment]
Fixed via #1933
