### ISSUE TITLE
Unclear docs regarding Contextual Path Browser

### ISSUE THREAD

**Issue by reggie7** [Adobe-Consulting-Services/acs-aem-commons#1841]
My comment [here](https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/contextual-pathfield-browser/index.html#comment-4426321254) explains what I mean for [Contextual Path Browser](https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/contextual-pathfield-browser/index.html#contextual-path-browser):
> I think the explanation for Contextual Path Browser needs a more precise info on its configuration. It's mentioning Page Info Provider, but I had to refer to the codebase to find out that it actually needs ACS AEM Commons - Page Root Provider Configuration filled.

**Comment by davidjgonzalez** [comment]
Hopefully fixed via https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/pull/153 ... @reggie7  can help confirm if that's the only wording that requires updating.
