### ISSUE TITLE
Named Transform Image Servlet does not respect inheritance for cq:Page

### ISSUE THREAD

**Issue by reggie7** [Adobe-Consulting-Services/acs-aem-commons#1843]
* [ ] AEM Version: `6.5`
* [ ] ACS AEM Commons Version: `4.0.0`
* [ ] Reproducible on Latest? yes

### Expected Behavior

[The Servlet](https://adobe-consulting-services.github.io/acs-aem-commons/features/named-image-transform/index.html) respects the inherited image for `cq:Page` resource.

### Actual Behavior

[The Servlet](https://adobe-consulting-services.github.io/acs-aem-commons/features/named-image-transform/index.html) does not return valid image defined for a parent page, when requesting a child page's `transform`.

### Steps to Reproduce

1. [Define](http://localhost:4502/system/console/configMgr/com.adobe.acs.commons.images.impl.NamedImageTransformerImpl) some transforms for yourself, e.g. `rotate` + `grey` to your likings,
2. Create a parent page with an image defined or use e.g. [We.Retail](http://localhost:4502/content/we-retail.html),
3. Create a child page with an image inherited or use e.g. [Experience](http://localhost:4502/content/we-retail/us/en/experience.html),
4. [Child](http://localhost:4502/content/we-retail/us/en/experience.transform/rotate/grey/image.png)'s transform does not work,
5. While [parent](http://localhost:4502/content/we-retail.transform/rotate/grey/image.png)'s does.

**Comment by davidjgonzalez** [comment]
@reggie7 So you're saying that the Experience page doesn't have an Image associated with it, however the We.Retail homepage does. When you request the Experience page with a transform, it doesn't auto-inherit the image from its first ancestor that has an image?

If my understand (above) is correct - I didn't even know that was expected/desired behavior, and probably an enhancement.

**Comment by davidjgonzalez** [comment]
@reggie7 bump

**Comment by reggie7** [comment]
@davidjgonzalez - well, it's a good question. I would invoke the [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) as a justification for why I saw it as a defect. I was confused to see no effect in running the given URL for a subpage in opposition to what I could see in its properties:

![experience](https://user-images.githubusercontent.com/5563546/56818751-94821d80-6848-11e9-9d49-6fb8eee965b9.png)

I'd prefer to have consistency of a plugin with the surrounding environment of the host app, so I'd vote for such enhancement to be implemented, if we don't see it as an implementation defect. I'd lean towards calling it a _UX defect_ maybe? Otherwise - the docs could simply disclaim the case above.

That's my thoughts on the subject :)

**Comment by reggie7** [comment]
Implemented in [1899](https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1899)
