### ISSUE TITLE
Bulkworkflow manager not working for eps files

### ISSUE THREAD

**Issue by praveenv2018** [Adobe-Consulting-Services/acs-aem-commons#1847]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4 SP2
* [ ] ACS AEM Commons Version: _____
* [ ] Reproducible on Latest? yes

### Expected Behavior

Bulkworkflow manager with synthetic multithreaded option is not generating thumbnails for eps files.

### Actual Behavior

Bulkworkflow manager with synthetic multithreaded option should generating thumbnails for eps files.

### Steps to Reproduce

1. Open bulkworkflow manager in aem.
1. Select Synthetic workflow with multithreaded
1. select eps files to generate thumbnails
1. Select DAM Update asset workflow model
1. Start workflow manager.

Image magic is configured for eps files.
Thumbnails are not generated.

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by praveenv2018** [comment]
Hear is the complete stack trace:
12.04.2019 02:39:25.025 *WARN* [synWf-/content/dam/hsy/test/EPS-Test-Cross-Browser-Testing3.eps] com.day.cq.dam.handler.standard.ps.PostScriptHandler I/O error while getting thumbnail image. java.io.CharConversionException: Illegal character in input. at com.day.cq.dam.core.impl.handler.ASCII85Filter.doFilter(ASCII85Filter.java:118) [com.day.cq.dam.cq-dam-core:5.11.326] at com.day.cq.dam.commons.handler.AbstractFilter.filter(AbstractFilter.java:174) [com.day.cq.dam.cq-dam-commons:5.11.180] at com.day.cq.dam.core.impl.handler.EPSThumbnailProcessor.process(EPSThumbnailProcessor.java :178) [com.day.cq.dam.cq-dam-core:5.11.326] at com.day.cq.dam.commons.handler.DefaultFormatHandler.getThumbnailImage(DefaultFormatHandle r.java:104) [com.day.cq.dam.cq-dam-commons:5.11.180] at com.day.cq.dam.handler.standard.ps.PostScriptHandler.getThumbnailImage(PostScriptHandler. java:240) [com.day.cq.dam.cq-dam-handler:5.11.26] at com.day.cq.dam.handler.standard.ps.PostScriptHandler.getImage(PostScriptHandler.java:145) [com.day.cq.dam.cq-dam-handler:5.11.26] at com.day.cq.dam.core.impl.cache.CQBufferedImageCache.getImage(CQBufferedImageCache.java:12 3) [com.day.cq.dam.cq-dam-core:5.11.326] at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.createImageLayer(CommonsGfxRenderer.java: 490) [com.day.cq.dam.cq-dam-core:5.11.326] at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.createLayer(CommonsGfxRenderer.java:165) [com.day.cq.dam.cq-dam-core:5.11.326] at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.render(CommonsGfxRenderer.java:116) [com.day.cq.dam.cq-dam-core:5.11.326] at com.adobe.cq.gfx.impl.GfxImpl.render(GfxImpl.java:94) [com.adobe.cq.cq-gfx:1.4.2] at com.day.cq.dam.core.impl.RenditionMakerImpl$PlanBasedTemplate.apply(RenditionMakerImpl.ja va:131) [com.day.cq.dam.cq-dam-core:5.11.326] at com.day.cq.dam.core.impl.RenditionMakerImpl.generateRenditions(RenditionMakerImpl.java:21 0) [com.day.cq.dam.cq-dam-core:5.11.326] at com.day.cq.dam.core.process.CreateThumbnailProcess.createThumbnails(CreateThumbnailProces s.java:119) [com.day.cq.dam.cq-dam-core:5.11.326] at com.day.cq.dam.core.process.ThumbnailProcess.execute(ThumbnailProcess.java:102) [com.day.cq.dam.cq-dam-core:5.11.326] at com.adobe.acs.commons.workflow.synthetic.impl.SyntheticWorkflowRunnerImpl.runCqWorkflowPr ocess(SyntheticWorkflowRunnerImpl.java:324) [com.adobe.acs.acs-aem-commons-bundle:3.19.0] at com.adobe.acs.commons.workflow.synthetic.impl.SyntheticWorkflowRunnerImpl.run(SyntheticWo rkflowRunnerImpl.java:248) [com.adobe.acs.acs-aem-commons-bundle:3.19.0] at com.adobe.acs.commons.workflow.synthetic.impl.SyntheticWorkflowRunnerImpl.execute(Synthet icWorkflowRunnerImpl.java:147) [com.adobe.acs.acs-aem-commons-bundle:3.19.0] at com.adobe.acs.commons.workflow.synthetic.impl.SyntheticWorkflowRunnerImpl.execute(Synthet icWorkflowRunnerImpl.java:186) [com.adobe.acs.acs-aem-commons-bundle:3.19.0] at com.adobe.acs.commons.workflow.synthetic.impl.SyntheticWorkflowRunnerImpl.execute(Synthet icWorkflowRunnerImpl.java:199) [com.adobe.acs.acs-aem-commons-bundle:3.19.0] at com.adobe.acs.commons.fam.actions.Actions.lambda$startSyntheticWorkflows$1(Actions.java:1 18) [com.adobe.acs.acs-aem-commons-bundle:3.19.0] at com.adobe.acs.commons.fam.actions.Actions.lambda$retryAll$0(Actions.java:89) [com.adobe.acs.acs-aem-commons-bundle:3.19.0] at com.adobe.acs.commons.workflow.bulk.execution.impl.runners.FastActionManagerRunnerImpl$Fa stActionManagerRunnable.lambda$null$1(FastActionManagerRunnerImpl.java:253) [com.adobe.acs.acs-aem-commons-bundle:3.19.0] at com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:214) [com.adobe.acs.acs-aem-commons-bundle:3.19.0] at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runActionAndLogErrors(ActionManagerImpl. java:176) [com.adobe.acs.acs-aem-commons-bundle:3.19.0] at com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$deferredWithResolver$0(ActionMana gerImpl.java:168) [com.adobe.acs.acs-aem-commons-bundle:3.19.0] at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:88) [com.adobe.acs.acs-aem-commons-bundle:3.19.0] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

**Comment by justinedelson** [comment]
This exception looks unrelated to ACS AEM Commons. Are you saying that this same asset is processed correctly when run through the regular AEM workflow engine?

**Comment by praveenv2018** [comment]
Yes. The asset is processed when run through the regular AEM workflow engine.

**Comment by davidjgonzalez** [comment]
@praveenv2018 weird.. I assume this happens on BWM Single Threaded as well?

**Comment by davidjgonzalez** [comment]
@praveenv2018 can you please attach a sample EPS file that is giving you problems?

**Comment by praveenv2018** [comment]
We have added one more Command line process step in DAM Update workflow which is causing this issue.
After removing this step this is working fine. Also Scene 7 properties are not generating with BWM Synthetic multi threaded option. So we have to select BWM AEM workflow option.

**Comment by justinedelson** [comment]
@praveenv2018 would it make sense to add this to the documentation?
