### ISSUE TITLE
Copy Publish URL does not work

### ISSUE THREAD

**Issue by reggie7** [Adobe-Consulting-Services/acs-aem-commons#1851]
* [ ] AEM Version: `6.5`
* [ ] ACS AEM Commons Version: `4.0.0`
* [ ] Reproducible on Latest? yes

### Expected Behavior

[Copy Publish URL](https://adobe-consulting-services.github.io/acs-aem-commons/features/assets-components/copy-publish-url/index.html) works as expected OotB.

### Actual Behavior

[Copy Publish URL](https://adobe-consulting-services.github.io/acs-aem-commons/features/assets-components/copy-publish-url/index.html) does not work. The libs are loaded, but the buttons do not show up.

### Steps to Reproduce

Follow the [docs](https://adobe-consulting-services.github.io/acs-aem-commons/features/assets-components/copy-publish-url/index.html).

**Comment by davidjgonzalez** [comment]
@reggie7 I believe this is a duplicate fo #1762 which is (should be) fixed in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1782 ..

Closing as a duplicate. If im wrong, please reopen! thanks!

**Comment by reggie7** [comment]
@davidjgonzalez - confirmed. I've checked that your solution works. Additionally though [I've ammended the docs](https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/pull/158).
