### ISSUE TITLE
SpreadsheetTest fails on non-English OS settings

### ISSUE THREAD

**Issue by csaboka** [Adobe-Consulting-Services/acs-aem-commons#1856]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: (irrelevant)
* [ ] ACS AEM Commons Version: 4.0.1-SNAPSHOT (latest)
* [ ] Reproducible on Latest? yes

### Expected Behavior

When running unit tests using e.g. "mvn clean package", all unit tests complete.

### Actual Behavior

If your OS locale is Hungarian, the SpreadsheetTest unit test fails with the following error:
```[ERROR] Failures:
[ERROR]   SpreadsheetTest.testSheetTypesAsStrings:176 expected:<123[.]456> but was:<123[,]456>
```

I'm sure the issue will also happen on other non-English locales that use something other than the dot for decimal separator.

### Steps to Reproduce

1. Set your OS locale to something that uses decimal comma (German or French can work). How to do this will depend on your OS.
2. Execute `mvn test` in the root source folder.

The issue is coming from the fact that the Variant class implicitly depends on the default Java locale in multiple places. This behavior makes CompositeVariant and Spreadsheet also depend on the default Java locale, so the assertions in the unit test can either succeed or fail based on an external factor.

How to fix this will depend on whether the locale dependency of Variant is considered a feature or a bug. If it's a feature, the unit test should either make its string-based assertions with dynamically-formatted expected values, or not make those assertions at all. If it's a bug, then Variant should get a way to specify its locale, and this change should be also applied to CompositeVariant and Spreadsheet; then the unit test could specify that it wants an en_US spreadsheet and freely make its US-based assertions.

**Comment by csaboka** [comment]
I'd like to help with fixing this issue, but I'm really not sure which of the two options is better (i.e. embracing dependency on the default locale vs. removing it).

**Comment by badvision** [comment]
Actually it might make sense to enforce the locale detected in the spreadsheet if possible.  Another point to consider is that we're relying on a library and need to at least isolate if it's a bug in the library or in our code.

**Comment by csaboka** [comment]
> Actually it might make sense to enforce the locale detected in the spreadsheet if possible.

I don't think Excel files have any locale saved with them. If I open the xlsx file from the test folder in Excel, I'm just seeing the numbers with my locale's proper decimal separator without any indication that the spreadsheet was created with another separator. I can't see any locale either on the Excel UI, or the public API of POI (the library used to parse the xlsx file).

> Another point to consider is that we're relying on a library and need to at least isolate if it's a bug in the library or in our code.

As far as I can tell, there is only one interaction between Variant and POI that relies on the default locale. Variant has a constructor that takes a POI Cell instance as an argument. The constructor eventually ends up calling [DataFormatter.formatRawCellContents()](https://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/DataFormatter.html#formatRawCellContents-double-int-java.lang.String-) to fill the string value of the variant in line 112. The no-args constructor is used to create a DataFormatter, which will implicitly use the default locale for formatting. If DataFormatter was instantiated with an explicit locale, we could control the number, date and time formats that end up used in the string form of the variant. In other words, POI is working fine, but Variant code asks it to rely on the default locale.

One way to fix this would be to add a Variant constructor that takes both a Cell and a Locale (the latter for formatting purposes), but this change would need to "ripple through" CompositeVariant and Spreadsheet to allow client code to specify the locale they expect.

**Comment by joerghoh** [comment]
Are we talking here just about a testcase, which only works in a limited number of locales, or is functionality affected as well?

The travis build runs in a combination of multiple languages and countries (-Duser.language=X -Duser.country=Y) (see https://travis-ci.org/Adobe-Consulting-Services/acs-aem-commons), but this does not seem to trigger this test to fail either. Should we run more builds also with different locale settings?

**Comment by csaboka** [comment]
> Are we talking here just about a testcase, which only works in a limited number of locales, or is functionality affected as well?

The answer really depends on what you consider the expected functionality. The behavior of the Spreadsheet class depends on the JVM default locale all the time, not just for the test case. This may be expected, but isn't documented as far as I can tell.

> The travis build runs in a combination of multiple languages and countries (...), but this does not seem to trigger this test to fail either.

Hmm, I'm pretty sure the test should fail with both German and French. Maybe it has to do with how the tests are run. As far as I remember Surefire forks a new JVM to run the tests, and that new process may not inherit the JVM args passed to Maven. I could successfully force the default locale to en_US and make the test pass locally by setting the _JAVA_OPTIONS environment variable, so I think you should be able to force a failure by setting that variable in Travis. Whether it's a good idea is another question - apparently this variable affects all newly started JVMs, so it may have some unexpected side effects.

**Comment by csaboka** [comment]
Created #1864 as a proposed minimal fix.

Turns out CompositeVariant doesn't need to be touched because it doesn't directly deal with Cell instances. I've opted to add a setter to set Spreadsheet locale since it already has a bunch of constructors and it didn't feel right to add a whole new set of them. It may be worthwhile to introduce a builder for this class instead and make client code more readable.

Please note that I haven't changed the fact that Variant still uses the default locale to convert between dates and strings. I think it would be better design to be explicit about this locale and allow specifying it, but this isn't necessary to fix the current issue.

**Comment by kwin** [comment]
This was fixed by applying https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1882.
