### ISSUE TITLE
Pathfield not working as Report Parameter in Report Builder

### ISSUE THREAD

**Issue by sreenivasb1988** [Adobe-Consulting-Services/acs-aem-commons#1865]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.4.3
* [ ] ACS AEM Commons Version: 3.19.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

I tried to add another type of report parameter, which is a path field, which I can use for "Path".
I followed https://adobe-consulting-services.github.io/acs-aem-commons/features/report-builder/extending.html#creating-a-report-parameter
Also I tried adding path field using generic list for Basic Report Parameter.
Expected Behavior - The Path field should be displayed in Reports UI.

### Actual Behavior

The Path Field Label is getting displayed, but path field (the picker) is not getting displayed.

### Steps to Reproduce

1. Install AEM 6.4
2. Install AEM Service Pack 3 for 6.4
3. Install ACS Commons 3.19.0
4. Follow the steps documented in https://adobe-consulting-services.github.io/acs-aem-commons/features/report-builder/extending.html#creating-a-report-parameter
5. Navigate to Tools - ACS AEM Commons
6. Provide a Title and Click on "Add Report".
7. Edit the New Report by clicking on "Pencil Icon"
8. Add a Report Builder Config in the First Parsys. Select "JCR Query Report Configuration"
9. Add a Query, Query Language and Page Size
10. Add a Report Builder Parameter and select the New Parameter, which was created in Step 4. 
11. Add a Report Path Column in last parsys.
12. Switch to Preview Mode and Refresh.

### Links

Link to Custom Component ScreenShot - https://imgur.com/ru0sCgt
Link to Generic List Addition of Field Type - https://imgur.com/hmhVauO
Link to Actual Behavior - https://imgur.com/epKSwNb

**Comment by klcodanr** [comment]
@sreenivasb1988 -- It could either be something mis-aligned in the implementation or that there's some magic with path fields that's not supported. Can you provide a package with the custom field so I can take a closer look?

**Comment by sreenivasb1988** [comment]
[acs_commons_custom_report.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/3130146/acs_commons_custom_report.zip)
 @klcodanr  - Attaching the package for your reference.

**Comment by klcodanr** [comment]
@sreenivasb1988 -- Not sure what's up with the resource type `granite/ui/components/coral/foundation/form/pathfield` but changing it to `granite/ui/components/foundation/form/pathbrowser` resolves the issue.

**Comment by kwin** [comment]
@klcodanr "pathbrowser" is deprecated since AEM 6.3 (https://helpx.adobe.com/experience-manager/6-3/release-notes/deprecated-removed-features.html). Instead one should always use the pathfield (compare also with https://helpx.adobe.com/experience-manager/6-3/release-notes/deprecated-removed-features.html).

**Comment by klcodanr** [comment]
Ah crud, I forgot about that change @kwin... hm let me look closer at why the supported component isn't working.

**Comment by sreenivasb1988** [comment]
@klcodanr and @kwin  - Appreciate your help in taking a look. Please let me know if there is any update on this.
