### ISSUE TITLE
MCP GeneratedDialog works only at content paths for components

### ISSUE THREAD

**Issue by gauravjasiwal** [Adobe-Consulting-Services/acs-aem-commons#1869]
## Required Information

* [6.4.3 ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [4.0.0 ] ACS AEM Commons Version: _____
* [Yes ] Reproducible on Latest? yes/no

### Expected Behavior

GeneratedDialog should work for all the paths like pageProperty, content page, etc.
Generated should take resource path as an input or at least it should read "item" as URL parameter, where most of the AEM paths comes from. 

### Actual Behavior

Current it takes the path from the current resource path/page path.

### Steps to Reproduce

Try to add the form at page property dialog and the URL will be something like here for page property http://localhost:4502/mnt/overlay/wcm/core/content/sites/properties.html?item=%2Fcontent%2Fviacom-repo%2Fen

### Links

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/mcp/form/GeneratedDialog.java#L138

For a quick fix for my project, I am using this custom method for getting the path.
Line 138 GeneratedDialog: 
```
form.setPath(ViacomGeneratedDialogUtils.getValidPath(sling.getRequest().getResource().getPath(),
                        getRequest().getParameter("item")));
```

```
public static String getValidPath(String path, final String paramItemValue) {
        if (StringUtils.startsWith(path, "/content")) {
            return path;
        }
        if (null == paramItemValue) {
            return path;
        }
        path = paramItemValue + ViacomConstants.SLASH + JcrConstants.JCR_CONTENT;

        return path;
    }
```

**Comment by badvision** [comment]
I don't think that's correct -- you can set the form dataPath from the GeneratedDialog side of things and then I believe it will work as you are expecting it to.  Check if setting data path on the form works and re-open this defect if it doesn't @gauravjasiwal.
