### ISSUE TITLE
Dispatcher flush rules - doesn't manage multiple occurrence of the same path

### ISSUE THREAD

**Issue by amargheriti89** [Adobe-Consulting-Services/acs-aem-commons#1878]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.4.2
* [ ] ACS AEM Commons Version: ACS-AEM-Commons 4.0.0
* [ ] Reproducible on Latest? yes

### Expected Behavior
By configuring the "ACS AEM Commons - Dispatcher Flush Rules" service with the following values:
-**/content/we-retail/ca/en**=/content/we-retail/ca/fr
-**/content/we-retail/ca/en**=/content/we-retail/us/es
-/content/we-retail/us/en=/content/we-retail/us/es

the expected behaviour is that after publishing the page /content/we-retails/ca/en also the paths:
- /content/we-retail/ca/fr
- /content/we-retail/us/es

are flushed.

### Actual Behavior

Inside the actual version after configuring the ACS AEM Commons - Dispatcher Flush Rules service as described above, only one of all the paths that need to be flushed after the replication of the /content/we-retail/ca/en page, is correctly flushed

### Steps to Reproduce

You can reproduce the issue with the following steps:
- Configure the ACS AEM Commons - Dispatcher Flush Rules configuration with 2 occurrence of the same path in order to flush 2 different paths (e.g. as the attached image)
- Replicate the path which need to trigger the flush of the other
- Check the flush agent into the publish instance (e.g. as the attached image)

### Links

_Links to related assets, e.g. content packages containing test components_

<img width="1300" alt="flush rule configuration" src="https://user-images.githubusercontent.com/50324156/57222533-3ea93480-7003-11e9-83b4-6221e4355c0d.png">

<img width="812" alt="flush agent info" src="https://user-images.githubusercontent.com/50324156/57222532-3ea93480-7003-11e9-801e-aa68616524bb.png">

**Comment by joerghoh** [comment]
Hm, can you try with this configuration:

-/content/we-retail/ca/en=/content/we-retail/ca/fr&/content/we-retail/us/es
-/content/we-retail/us/en=/content/we-retail/us/es
