### ISSUE TITLE
Feature Review: Granite Select Filter

### ISSUE THREAD

**Issue by ahmed-musallam** [Adobe-Consulting-Services/acs-aem-commons#1880]
I've built this: https://blogs.perficientdigital.com/2019/05/03/how-to-add-a-filter-to-aem-granite-select-widget/

I'd love to contribute it to ACS commons. I will make it CSS selector based before committing it. Is this something I can contribute? What directory should it live under in the project?

**Comment by davidjgonzalez** [comment]
@ahmed-musallam this looks quick nice! IIUC this is entirely JS, so it could be added as a new clientlib folder under: 

https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/master/content/src/main/content/jcr_root/apps/acs-commons/authoring

We haven't updated any docs yet, but for new Dialog widgets, we'd like to start providing instructions to add supporting clientlibs via the extraClientLibs dialog property - and this seems like a good candidate for that. (/cc @kwin)

**Comment by ahmed-musallam** [comment]
Made PR #1894

**Comment by davidjgonzalez** [comment]
@ahmed-musallam thanks! 4.2.0 is released (pending deploy to repo.adobe)
