### ISSUE TITLE
WorkflowPackageManager does not support the new location

### ISSUE THREAD

**Issue by swaroop61** [Adobe-Consulting-Services/acs-aem-commons#1885]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5
* [x] ACS AEM Commons Version: 4.0.0
* [x] Reproducible on Latest? yes

### Expected Behavior

Should be able to create a workflow package at location /var/workflow/packages

### Actual Behavior

Workflow packages always created at location /etc/workflow/packages

### Steps to Reproduce

As part of an upgrade to AEM 6.5, following the Common Repository Restructuring introduced in 6.4/6.5 [1],

Workflow Packages - Previous location:  /etc/workflow/packages
                    New location(s):    /var/workflow/packages

In our project we are using WorkflowPackageManager to create the workflow package, however it always creates it in /etc/workflow/packages, not in the new location.

[1] https://helpx.adobe.com/experience-manager/6-5/sites/deploying/using/all-repository-restructuring-in-aem-6-4.html

### Links

N/A

**Comment by joerghoh** [comment]
@davidjgonzalez: shouldn't this issue be closed (fixed by #1892)?

**Comment by davidjgonzalez** [comment]
It’s in dev but not released (see milestone)

**Comment by davidjgonzalez** [comment]
Released in 4.2.0
