### ISSUE TITLE
 Trying to send Email to a group Email I.D in AEM.

### ISSUE THREAD

**Issue by adithya999** [Adobe-Consulting-Services/acs-aem-commons#1886]
Hello All,

 

I am trying to send an email to a group email I.D and it doesn't give any error but we are not receiving the Email. When I try to do the same by replacing with one email I.D then we are able to send the email.

 

I am using "com.adobe.acs.commons.email.EmailService" and Day CQ Mail Service.

 

Can some one let me know what I need to do in order to achieve this.

 

Thanks,

Adithya.

**Comment by joerghoh** [comment]
From an AEM point of view there is not difference in a group email ID and the email ID of a single user. Have you checked the AEM error.log file for any statements about this? I would also recommend to check the logs of the email server to find out if there any email has been received from AEM.

There are many ways how emails can get not sent; and in a case like this it's more likely that the email server has rejected the mail or dropped it alltogether.
