### ISSUE TITLE
Localized Title doesn't work : Tag Creator

### ISSUE THREAD

**Issue by akaash2512** [Adobe-Consulting-Services/acs-aem-commons#1891]
## Required Information

* [ ] AEM Version : 6.3.0
* [ ] ACS AEM Commons Version: 3.17.0
* [ ] Reproducible on Latest? NA

I added below cell in my Excel file:
en[Categories]   de_DE[Kategorien] fr_FR[Catégories]{{categories}}

It created the tag like below:
name : categories
title : en[Categories]   de_DE[Kategorien] fr_FR[Catégories]

It should have created the tag Categories with localized titles, as per documentation.

**Comment by davidjgonzalez** [comment]
@akaash2512  - Can you attach an Excel sheet that is failing for you to this ticket as well as the Primary and Fallback converts you've selected? You need to pick the Localized Title as the Primary converter.

Thanks!

**Comment by akaash2512** [comment]
Hi David,

Thanks for your response.
Yes, I had selected the "Localized Title" as primary converter. and Falllback converter "Title And Node Name"

attached the file.

[createtag.xlsx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/3168712/createtag.xlsx)

Regards,
Akash B.

**Comment by davidjgonzalez** [comment]
the attached file is a bit of a mess, but i copied some cells out. my attached imports fine using:

- primary: Localized Title
- fallback: title and node name

note that you were using THREE formats in your file,  a max of 2 is supported (primary and fallback)

[working-test.xlsx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/3179416/working-test.xlsx)

![image](https://user-images.githubusercontent.com/1451868/57725301-cc67ce00-765a-11e9-9e63-f9bfa4161b20.png)
