### ISSUE TITLE
[New Feature] Asset/Resource Reference Search

### ISSUE THREAD

**Issue by cylinder-y** [Adobe-Consulting-Services/acs-aem-commons#1903]
## Required Information

Several times I was faced with a problem when I was requested to provide list of assets/resources that are not used in AEM any more. General idea here is to write tool that will provide the following features:

### Provides report with following information:
1. Option for used resources: path to resource and path where it is used
2. Option for unused resources: just a list of resources that are not referenced anywhere
3. Last option that combines point 1 and 2

### Possible configuration

- Textfield: XPATH/SQL2 query to get a list of resources to be verified
- Upload Field: File with a list of paths
- Pathfield: Where perform search
- Select Field:  With report type
    - Used
    - Unused
    - Both
- Checkbox: Responsible for report format: 
    - path to page, asset and etc(parent of jcr:content), were resource is used
    - path to the property,  were resource is used

### Links
- https://helpx.adobe.com/experience-manager/6-4/sites/developing/using/reference-materials/javadoc/com/day/cq/dam/commons/util/AssetReferenceSearch.html
- https://helpx.adobe.com/experience-manager/6-4/sites/developing/using/reference-materials/javadoc/com/day/cq/wcm/commons/ReferenceSearch.html

**Comment by klcodanr** [comment]
@cylinder-y - You should be able to do this with [AEM Content Reports](https://adobe-consulting-services.github.io/acs-aem-commons/features/report-builder/index.html). Currently, we don't have a report column for references, but honestly it would be pretty easy to add [using the API](https://adobe-consulting-services.github.io/acs-aem-commons/features/report-builder/extending.html)

The only thing that would be tricky is the support for used vs unused as to search by that would take a sub-search for references.

**Comment by cylinder-y** [comment]
thank you, I will take a look

**Comment by cylinder-y** [comment]
Hi @klcodanr, That's like it was in my mind. But I wanted to extend MCP tools as I have worked with it before. 
As I understood I could add reference column into the report. If it has path to somewhere - resource is used. If cell is empty - it has no references

**Comment by cylinder-y** [comment]
Hello @klcodanr, as I see you references support was implemented here: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1237

**Comment by klcodanr** [comment]
Thanks @cylinder-y ! I must have missed updating the documentation.

**Comment by cylinder-y** [comment]
@klcodanr , i'm only faced with results. Search is not performed in my content fragments:

I was testing it on image, located under dam folder

![image](https://user-images.githubusercontent.com/23450886/58319673-c1fbc000-7e22-11e9-94e9-a18b84592ed5.png)

for every category:
- contentFragment
    - /content/to/page/some/path1
    - /content/to/page/some/path2
- product
    - /content/to/page/some/path1
    - /content/to/page/some/path2
- site ref:
     - /content/to/page/some/path1
    - /content/to/page/some/path2

This image also is used in content fragment, but wasn't found. 

Using query /jcr:root//*[jcr:contains(., '/content/dam/image.jpg')] order by @jcr:score

I got 3 correct paths

I guess the reason in, ReferenceAggregator. I would try to use ReferenceSearch instead

**Comment by bsaravanaprakash** [comment]
Thanks for bringing up this @cylinder-y . ReferenceSearch API do have issue with its ReferenceAggregator where it tries to getContainingPage(res) and then apply getMaxReferencesPerPage(). Unfortunately this was not helpful to me either coz my asset was referenced at an experience fragment but, ReferenceSearch returned 0 references. 
I ended up running simple xpath query as '/jcr:root//*[jcr:contains(., '/content/dam/test/image.jpg')]'. 

Another issue was, when an asset is used in its parent folder thumbnail, above query reports as referenced. So I had to run 2 queries
'/jcr:root/content/experience-fragments//*[jcr:contains(., '%s')]'
'/jcr:root/content/test//*[jcr:contains(., '%s')]'

Please share if you faced any other issues when using direct xpath query instead of ReferenceSearch API.

**Comment by cylinder-y** [comment]
> 
> 
> Thanks for bringing up this @cylinder-y . ReferenceSearch API do have issue with its ReferenceAggregator where it tries to getContainingPage(res) and then apply getMaxReferencesPerPage(). Unfortunately this was not helpful to me either coz my asset was referenced at an experience fragment but, ReferenceSearch returned 0 references.
> I ended up running simple xpath query as '/jcr:root//*[jcr:contains(., '/content/dam/test/image.jpg')]'.
> 
> Another issue was, when an asset is used in its parent folder thumbnail, above query reports as referenced. So I had to run 2 queries
> '/jcr:root/content/experience-fragments//_[jcr:contains(., '%s')]' '/jcr:root/content/test//_[jcr:contains(., '%s')]'
> 
> Please share if you faced any other issues when using direct xpath query instead of ReferenceSearch API.

May I ask you please to open a separate issue?

**Comment by frappierer** [comment]
You can use the bash script under [https://github.com/frappierer/unrefAemAssets](https://github.com/frappierer/unrefAemAssets)
its bad but it works
