### ISSUE TITLE
Extend Travis Build to also test with JDK11

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#1911]
To prevent issues like #1893 we should build not only with OracleJDK8 but also the current LTS version (i.e. JDK11, preferably OpenJDK due to the change of the Oracle license). Multiple environments are supported in Travis: https://docs.travis-ci.com/user/languages/java/#testing-against-multiple-jdks.

**Comment by kwin** [comment]
This is blocked by #1916.

**Comment by joerghoh** [comment]
#2104 has been merged which also adds a java11 build on travis. We should close this issue.
