### ISSUE TITLE
Encoding issue in error handler pages

### ISSUE THREAD

**Issue by venkatreddyguda** [Adobe-Consulting-Services/acs-aem-commons#1915]
## Required Information

* [ ] AEM6.3  / Service Pack 6.3.3.0
* [ ] ACS AEM Commons Version: ___3.19.0__
* [ ] Reproducible on Latest? yes

### Expected Behavior
When user navigate to invalid pages it should redirect to Error handler pages and show custom messages with out  any encoding issues for all languages.

### Actual Behavior
When we upgrade from ACS AEM Commons Version 3.17.4 to 3.19.0 we are observing encoding issues in error handler pages.Invalid pages display only  "?" for the double-byte characters.We tried upgrading to latest version 4.1.0 and we still see this issue.

**Comment by davidjgonzalez** [comment]
@venkatreddyguda what language was causing you the problem? Could you c/p in some text (or attach) that is causing this issue.

**Comment by venkatreddyguda** [comment]
@davidjgonzalez  This is happening for double-byte characters.When we upgrade to  ACS AEM Commons version 3.19.0 we are observing this issue.When we tried downgrading to ACS AEM Commons Version 3.17.4 we dont see this issue.Please suggest on this.

**Comment by ronvatdc** [comment]
I have had this issue with Japanese ja-jp, Chinese zh-cn, and Korean ko-kr while the English, Portuguese, and German pages all display fine.  I assume all double byte characters cause the same issue.  

This is very similar to issue https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1010  which looks to have been previously resolved in 3.12.0
