### ISSUE TITLE
Report Builder: Too many sling includes

### ISSUE THREAD

**Issue by marcinczeczko** [Adobe-Consulting-Services/acs-aem-commons#1918]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3-6.5
* [ ] ACS AEM Commons Version: 4.1.x
* [ ] Reproducible on Latest? yes

### Expected Behavior
Reports didn't crash if you have over 1k pages.

### Actual Behavior
I do have a general question about how the Report builder is working and steer from you how to tackle with that issue. 
Basically I found in the code that reports are heavily componentized, which is fine because provides high configurability. However, in my opinion it requires significant improvements to be production ready. 
What I found is the report result jsp generates lot of `sling:include`s. Basically for every result row it generates X sling includes (where X is number of columns) that eventually might lead to `TooManyCallsException` exception because of the limit set on `SlingMainServlet`, especially if user tries to generate CSV to get all results.

Of course it's possible to increate this limit on `SlingMainServlet` but in my opinion is not solving the problem, but rather postponing it. If you have pretty small site, users can live with that, but implementations I'm working on we're talking about 10k pages and growing every day.

Do you have any plans how to overcome that issue. I believe the only way to make it happen is to avoid doing `sling:include` per result, but rather expose whole result set with transformed, extracted data in the model supplying the result set.

### Steps to Reproduce
Run the report for content with over 1k pages

**Comment by timdonovanuk** [comment]
This is still an issue:

![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/8156439/c1512de5-540d-4ba7-a9a3-c48dbc00a0aa)

As per @joerghoh - "(also please fill a ticket on ACS AEM Commons, if not already present. The design of that feature should be changed, so it does not run into this problem.)" 

https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/getting-quot-toomanycallsexception-quot-in-acs-commons-report/td-p/549174
