### ISSUE TITLE
simple google map integration

### ISSUE THREAD

**Issue by Fan-Xu** [Adobe-Consulting-Services/acs-aem-commons#192]
We have several requirements about the google map integration from customers.

The basic implementation idea is
    1.designing a dialog by which author can input the address details;
    2.an backend OSGI service will search the address and get the lat lng informations via google service(the google api key and the api URL will be configured in OSGI console);
    3.rendering a map image on the page according to the lat/lng info, and clicking on it will open the full google map in a new window;

**Comment by badvision** [comment]
I recommend we don't provide this.  Google has demonstrated that they're capable of pushing out breaking changes where features just simply disappear with no analog in revised API versions -- this makes trying to provide a one-size-fits-all integration rather a moving target.  We have bigger fish to fry.
