### ISSUE TITLE
Data Importer cannot create cq:Page nodes

### ISSUE THREAD

**Issue by EAVilleda** [Adobe-Consulting-Services/acs-aem-commons#1945]
## Required Information

* [x] AEM Version: 6.3.0
* [x] ACS AEM Commons Version: 4.1.0
* [x] Reproducible on Latest? yes

### Expected Behavior

When I import a simple spreadsheet of new paths, each with the jcr:primaryType cq:Page, the Data Importer should create these new page nodes.

### Actual Behavior

When I run the Data Importer with my spreadsheet, I run into the following exceptions (and more that are similar):

11.06.2019 13:08:34.005 *ERROR* [pool-308-thread-4] com.adobe.acs.commons.fam.impl.ActionManagerImpl Caught exception in task: Value for key sling:resourceType can't be put into node: cq:Page
org.apache.sling.api.resource.PersistenceException: Value for key sling:resourceType can't be put into node: cq:Page

11.06.2019 14:59:18.490 *ERROR* [pool-308-thread-1] com.adobe.acs.commons.fam.impl.ActionManagerImpl Caught exception in task: Value for key path can't be put into node: /content/we-retail/us/en/test
org.apache.sling.api.resource.PersistenceException: Value for key path can't be put into node: /content/we-retail/us/en/test

These exceptions do not occur if I update the spreadsheet to create sling:Folder nodes instead of cq:Page nodes.

### Steps to Reproduce

1. Start up a fresh AEM 6.3.0 instance
2. Install ACS AEM Commons 4.1.0
3. Create a new Excel spreadsheet.
4. Add headers "path" and "jcr:primaryType".
5. Enter a path for a new page and "cq:Page" in the next row.
6. Enter three more rows of paths for children pages and "cq:Page" for each.
7. Save the spreadsheet as xlsx type.
8. Open the Data Importer.
9. Upload the Excel file.
10. Update "Structure node type" to cq:Page.
11. Start the process.

**Comment by davidjgonzalez** [comment]
cq:Pages dont allow most properties, you'd want to add a 2nd import rule for a jcr:content node cq:PageContent under the cq:Page node definition (not sure if this is possible/how big a PITA it is).

I assume this is an enhancement, but it would be nice to have special handling for cq:Page nodes, considering a cq:Page node on its own is ~useless, not to mention the importance of cq:Pages in the AEM ecosystem.

**Comment by EAVilleda** [comment]
I created a spreadsheet with both cq:Page and cq:PageContent information. I included the following headers: path, jcr:primaryType, sling:resourceType, cq:template, and jcr:title. I ran the import and confirm that the same exceptions are still occurring.

I'd also like to mention that I just tested both spreadsheets on a new AEM 6.5 instance. The exceptions still occur.

**Comment by EAVilleda** [comment]
Here is the spreadsheet I used:
[test.xlsx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/3306501/test.xlsx)

**Comment by EAVilleda** [comment]
Just an update, I've worked on the enhancement/fix for this. I'll link the PR to this when it's ready.

**Comment by EAVilleda** [comment]
The pull request for this enhancement has been reviewed and merged. 
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1969
