### ISSUE TITLE
Any tool for Exporting data

### ISSUE THREAD

**Issue by ramsajja01** [Adobe-Consulting-Services/acs-aem-commons#1947]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [ ] ACS AEM Commons Version: _____cs-aem-commons-content-4.0.0
* [ ] Reproducible on Latest? yes/no

### Expected Behavior

We are using  MCP Data Importer from ACS Commons  for importing bulk data and it is working fine for multiple assets. Authors are facing an issue to enter data and import with the same for MCP data importer supporting.
Question: is there any tool in ACS commons available to export the same format of data and update the details and import the data using MCP tool?

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by davidjgonzalez** [comment]
@klcodanr Report Builder couldnt be configured to this, could it?

**Comment by klcodanr** [comment]
Yes, Report Builder would support this concept. You could create a report and then download it as a CSV.

**Comment by ramsajja01** [comment]
Thank you. I will check tomorrow using Report Builder and let you know the status.

**Comment by davidjgonzalez** [comment]
@ramsajja01 feel free to reopen the issue if you run into problems!
