### ISSUE TITLE
undefined error in classicui-limit-parsys.js

### ISSUE THREAD

**Issue by anand19cse** [Adobe-Consulting-Services/acs-aem-commons#1948]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs -6.4.2
* [ ] ACS AEM Commons Version: _____ 4.1.0
* [ ] Reproducible on Latest? yes/no - yes

This issue was raised many times earlier but not fixed yet. EX: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1759

Could you please fix this asap as editors are not able to drop any components in parsys?

 **Expected Behavior**

Should be able to drag & drop the components from sidekick on to the parsys.

**Actual Behavior**
Drag & drop the component from the sidekick to the pasrys isn't working in classic UI and there is console error from this file https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/widgets/configure-limit-parsys/classicui-limit-parsys.js#L96.
It looks like sometimes the "designObject" is not initialized within the pageInfo and just returns as an undefined limit object.
![image](https://user-images.githubusercontent.com/46091229/59337447-3fc63380-8d1e-11e9-9147-5f1ce9b2abe0.png)

**Steps to Reproduce**

1. Start AEM 6.4.2
2. Install ACS commons 3.17.4 or the latest.
3. Install the attached content package.
4. Open the page http://localhost:4502/content/parsys-drag-drop-issue.html
5. Drag & drop the component to the parsys to see the console error. Some times it works, so try refreshing the window or try in the incognito window.

**Comment by davidjgonzalez** [comment]
@anand19cse are you explicitly including the ACS Commons classicUI Widgets clientlibs? Or in other words, are you trying to use this feature? Or is this appearing simply because ACS AEM Commons is installed?

**Comment by anand19cse** [comment]
Hi David,
Thanks for the response. But latest version of ACS commons has the fixes. I installed the latest version and it was fixed.
Thanks,
Anand
