### ISSUE TITLE
Update RELEASING and READMEs to describe oakpal:webster process

### ISSUE THREAD

**Issue by adamcin** [Adobe-Consulting-Services/acs-aem-commons#1950]
@adamcin Would you mind adding the information in the description to the README project, maybe in a new section called "Updating OakPAL Checklists" (could be in just the `oakpal-checks` module, but since the instructions span both `content` and `oakpal-checks` modules, putting it in the root README makes more sense to me.

Regarding:

> This should be performed regularly as
existing content is changed, and as new content is added to the content package.
> This will likely only need to be performed when
features are added to the checklists, or when service packs are
released.

Would it make sense to add this to the RELEASING file and just establish it as something that happens as part of every minor release (no need to do these for patch releases AFAICT).

_Originally posted by @justinedelson in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1928#issuecomment-501372220_

**Comment by justinedelson** [comment]
minor edit to description (moving back and forth between JIRA and GH issues always results in me doing the formatting wrong)
