### ISSUE TITLE
New feature: OnDeployScripts support for external calls & logging to historic node

### ISSUE THREAD

**Issue by geertsmichael** [Adobe-Consulting-Services/acs-aem-commons#1956]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.4.4
* [x] ACS AEM Commons Version: latest
* [x] Reproducible on Latest? yes

### Expected Behavior

I want to use the OnDeployScriptExecutor to call from my own code to trigger a script again or run the failed scripts again. Do you approve that I move this outside the impl package and export this class for external reference:

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/ondeploy/impl/OnDeployExecutor.java

I also want to add support to the OnDeployScriptBase to support logging to the runnedNode in /var/acs-commons/on-deploy-scripts-status. So the OnDeployScript can output, and can be checked instead of checking the log files.

### Actual Behavior

The class is hidden for referencing from my OSGI bundle. No logging to /var/acs-commons/on-deploy-scripts-status is available.

### Steps to Reproduce

I just want to have push access and approval for these features. I will modify the code myself and open a Pull Request.

### Links

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/ondeploy/impl/OnDeployExecutor.java

**Comment by geertsmichael** [comment]
Can you grant me access for contribution to this project?

**Comment by davidjgonzalez** [comment]
Just PR your contribution .. all contributors follow this process:

https://adobe-consulting-services.github.io/acs-aem-commons/pages/contribute.html
