### ISSUE TITLE
Release ACS Commons 4.2.0 to unblock AEM Component Generator

### ISSUE THREAD

**Issue by HitmanInWis** [Adobe-Consulting-Services/acs-aem-commons#1962]
@davidjgonzalez How involved is cutting a minor version (4.1.1) of ACS AEM Commons, or will 4.2.0 be released soon?  Reason I ask is the new `@ChildResourceFromRequest` annotation is required by the new AEM Component Generator that Bounteous is contributing to the Adobe community (currently at https://github.com/Bounteous-Inc/bounteous-aem-commons/tree/master/aem-component-generator, but moving to https://github.com/adobe/aem-component-generator).

For internal use we are currently just depending on a locally built version of ACS AEM Commons at version `4.1.1-SNAPSHOT`, but I'm hesitant to add it to the Adobe repo that way unless 4.2.0 is coming very very shortly.

Thanks!

**Comment by davidjgonzalez** [comment]
@hitmaninwis not hard to cut - someone else at Adobe would have to take care of the Adobe-side of the deployment tho.

FWIW the next version will be 4.2.0 since your feature has been merged and it’s a new feature (rather than a bugfix)

**Comment by davidjgonzalez** [comment]
@HitmanInWis Released 4.2.0
@justinedelson any chance you can submit for release on repo.adobe?

**Comment by davidjgonzalez** [comment]
Per @bstopp the request is summitted. it's in adobe's hands now.
