### ISSUE TITLE
Uncaught cannot create Component: xtype 'graphiciconselection' not found

### ISSUE THREAD

**Issue by anand19cse** [Adobe-Consulting-Services/acs-aem-commons#1964]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______6.4.2
* [ ] ACS AEM Commons Version: _____ 4.1.0
* [ ] Reproducible on Latest? yes/no yes

### Expected Behavior

"graphiciconselection" xtype should work. I follow release notes of ACS 4.1.0 and found that we will have to explicitly enable the widgets by using "Wrapper Client Libraries" as it is depricated.
Can you please guide how can i create the wrapper clientlib to enable it? I tried the method mentioned in documentation but somehow it didn't work. Would appreciate your help.

### Actual Behavior

"graphiciconselection" xtype stops working when i installed latest version of ACS- commons(4.1.0)

### Steps to Reproduce

_Just install the ACS 4.1.0 and try to use xtype ""graphiciconselection" in classic dialog. Dialog will not open and show errors in browser console.

### Links
![image](https://user-images.githubusercontent.com/46091229/59773684-aa9dde80-92cb-11e9-87b9-f5ef0850861b.png)

**Comment by anand19cse** [comment]
I have created a wrapper clientlib node with below definition and loading this clientlib at templete level. but still not working.

<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
    jcr:primaryType="cq:ClientLibraryFolder"
          jsProcessor="[default:none,min:gcc]"
          allowProxy="{Boolean}true"
          categories="[cq.authoring.dialog,granite.ui.coral.foundation.addon.coral2]"
          embed="[acs-commons.widgets.icon-picker]"/>

**Comment by anand19cse** [comment]
I had not created blank js.txt and css.txt as mentioned in documentation. That was causing problem to enable the widgets.
Thanks.

**Comment by davidjgonzalez** [comment]
Thanks for the update @anand19cse
