### ISSUE TITLE
Icon Picker isn't working on AEM 6.5

### ISSUE THREAD

**Issue by alissonxavierosfglobal** [Adobe-Consulting-Services/acs-aem-commons#1965]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5
* [ ] ACS AEM Commons Version: 4.2.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

The Icon Picker working on AEM 6.5

### Actual Behavior

The Icon Picker isn't working on AEM 6.5. Its layout is broken.

### Steps to Reproduce

Create the icon picker field on dialog.

### Links

![image](https://user-images.githubusercontent.com/50421550/59792537-c47af980-92aa-11e9-86fe-7a26cff391cc.png)

**Comment by AndreiShilov** [comment]
@alissonxavierosfglobal 
I checked on the lates 6.5 instance and the icon select works fine

![image](https://user-images.githubusercontent.com/5828856/61583958-0c0dd300-ab40-11e9-972b-8c9aac2c0982.png)
Are you sure that you have configured everything properly?

```
<icon jcr:primaryType="nt:unstructured" fieldLabel="Icon" name="./icon" sling:resourceType="acs-commons/components/authoring/graphiciconselect">
    <datasource jcr:primaryType="nt:unstructured" path="/etc/acs-commons/lists/font-awesome-icons" sling:resourceType="acs-commons/components/utilities/genericlist/datasource"/>
</icon>
```

And do not forget to configure wrapper clientlib
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/icon-picker/.content.xml
