### ISSUE TITLE
Oak Ensure index doesn't use properties.ignore on AEM restart

### ISSUE THREAD

**Issue by wimsymons** [Adobe-Consulting-Services/acs-aem-commons#1966]
## Required Information

* [ ] AEM Version: 6.4.4.0
* [ ] ACS AEM Commons Version: 3.19.0
* [ ] Reproducible on Latest? untested

### Expected Behavior

When ignore.properties is set on com.adobe.acs.commons.oak.impl.EnsureOakIndexManagerImpl OSGi config, this should be used when ensuring the indexes.

### Actual Behavior

All extra ignore.properties are skipped when ensuring the indexes on AEM restart.

### Steps to Reproduce

- Create a Lucene type index and don't include the 'seed ' value in the Oak Ensure Index definition, but do include 'forceReindex={Boolean}true'
- Create an OSGi config for com.adobe.acs.commons.oak.impl.EnsureOakIndexManagerImpl and set ignore.properties to '[seed]'.
- Restart AEM
- Watch your index being re-indexed (normal because the index doesn't exist yet)
- Restart AEM
- Watch your index being re-indexed again (not normal because 'seed' should be ignored)

### Extra info

When enabling debug logging on com.adobe.acs.commons.analysis.jcrchecksum you see that the 'seed' property is used and not excluded for calculating the checksum, thus causing a difference to be detected and the re-index being executed.

As of 4.0.0 the issue for 'seed' will not be visible because it is added to the defaults.

### Work-around

Include the 'seed' property in your Oak Ensure Index definition

### Plausible cause

Most likely is that the activate method in EnsureOakIndexManagerImpl reading the property isn't called yet before the AppliableEnsureOakIndex is bound to the service.

**Comment by joerghoh** [comment]
@davidjgonzalez added the "seed" property to the default ignore list with #1609, and it should be fixed in 4.0.

@wimsymons can you confirm this?

**Comment by wimsymons** [comment]
I did’t have the time yet to verify this on a 6.4 instance with acs 4.0. I’ll try to test it by end of next week. Both the ‘seed’ and another ‘dummy’ value.

**Comment by wimsymons** [comment]
As expected (logs in chronological order):
```
(on bindAppliableEnsureOakIndex)
10.10.2019 12:22:00.640 *DEBUG* [OsgiInstallerImpl] com.adobe.acs.commons.oak.impl.EnsureOakIndexManagerImpl Added additional ignore properties:  to index /oak:index
(on activate)
10.10.2019 12:22:00.640 *DEBUG* [OsgiInstallerImpl] com.adobe.acs.commons.oak.impl.EnsureOakIndexManagerImpl Activated with additional ignore properties: dummy
```

**Comment by wimsymons** [comment]
Hi,

I provided a fix for this issue.

Kind regards

Wim

**Comment by wimsymons** [comment]
I don't like the fix I provided. The `ignore.properties` should actually be set on the `com.adobe.acs.commons.oak.impl.EnsureOakIndex` and not on the `com.adobe.acs.commons.oak.impl.EnsureOakIndexManagerImpl`.

But that would be a breaking change.

Maybe better to do it that way as the property on `com.adobe.acs.commons.oak.impl.EnsureOakIndexManagerImpl` isn't working anyway.

Don't know the procedure to properly deprecated an old config location though.

**Comment by joerghoh** [comment]
I agree regarding your analysis, why the ignoredProperties are not respected. Imagine this scenario:

* You can configured an OSGI configuration for the factory ``com.adobe.acs.commons.oak.impl.EnsureOakIndex``
* When this factory is activated, the ``activate`` method of it is triggered; and if immediate=true is set, the (re-) indexing will already started.
* Afterwards this Index is bound to the EnsureOakIndexManagerImpl, and there the ``setIgnoreProperties()`` method is called to provide the names of the properties to ignore.

That means, the really best way is move the ignoredProperties over to the ``EnsureOakIndex`` class, where they are available during ``activate()``. Or the ``EnsureOakIndexManagerImpl`` exposes these properties to other services.

I guess the final solution should be to move these properties into the EnsureOakIndex class, but to keep backwards compatible Option (2) could be implemented as well as a fallback, if EnsureOakIndex does not have them configured (plus proper warnings regarding migration). I try to come up with a patch, which does not affect the exported Java API.

**Comment by badvision** [comment]
We can do that, but please note we're also talking about deprecating this solution and not supporting it after 6.5; it's become rather redundant.

**Comment by joerghoh** [comment]
@wimsymons can you have a look at this PR? Should be fairly backwards compatible but fix your problem.

**Comment by joerghoh** [comment]
Fixed with #2074

**Comment by badvision** [comment]
> @badvision do you mean the Oak Ensure Index is a feature that will disappear after 6.5? Why? Is it being integrated into Oak itself perhaps?

It's a theory that the feature will just simply not be very useful, that's all.  Over time the default indexes have become much more usable out of the box.  The need for this tool will hopefully be diminished in such a case.  We've been needing this less and less since 6.3, for example.

**Comment by joerghoh** [comment]
But with custom indexes its still useful. Anyway, let's see.

**Comment by wimsymons** [comment]
Indeed it does. We have about 10-12 custom indexes on AEM 6.4. It would be a cumbersome process if this functionality is removed from acs commons.

**Comment by joerghoh** [comment]
@badvision can you close this issue?
