### ISSUE TITLE
RTE (used in multifield) is not showing the previously stored content when edit the component.

### ISSUE THREAD

**Issue by vgajendr** [Adobe-Consulting-Services/acs-aem-commons#1977]
## Required Information

* [1 ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
         AEM Version 6.3
         aem-service-pkg-6.3.3.zip
         aem-6.3.3-cfp-3.0.zip

* [ ] ACS AEM Commons Version: acs-aem-commons-content-3.17.0.zip
* [ ] Reproducible on Latest? yes/no: no

Content in RTE used in multifield component is not showing the stored values. If re author it will vanish off all the other description.

we tried installing new ACS commons versions 3.17.4, 3.19 and 4.0.0. still issue persists.

Can you please help on this.

**Comment by davidjgonzalez** [comment]
@vgajendr The obligatory question here is, why are you using the ACS Commons multi-field, instead of the AEM Granite Multi-field. Our multifield has been deprecated for quite some time now (and may go away).

**Comment by vgajendr** [comment]
we are using granite/ui/components/coral/foundation/form/multifield

**Comment by davidjgonzalez** [comment]
@vgajendr ooh! so you aren't using ACS COmmons at all for this, but simply the presence of it being installed is enough to break the OOTB functionality? Uninstalling ACS Commons (and doing nothing else) allows this to work? 
If it was pre-4.0.0 this wouldn't have surprised me since we were auto-loading a bunch of clientlibs :( .. however with 4.0.0 ACS Commons clientlibs have to be explicitly loaded.

**Comment by vgajendr** [comment]
So currently we are using 3.17 ACS commons. 

I tried to install latest version of ACS commons still it didnt fix so reverted back to 3.17.

**Comment by davidjgonzalez** [comment]
And to be clear, uninstalling ACS Commons and clearing your browser cache resolves the issue?

**Comment by vgajendr** [comment]
No even after clearing cache. issue still persists.

**Comment by davidjgonzalez** [comment]
Wait - so if you UNINSTALL ACS Commons and clear your cache, the issue persists? If so, why do you think this is an issue with ACS Commons, and not with AEM?

**Comment by vgajendr** [comment]
Issue started after installing AEM Cumulative Fix Pack 6.3.3.3.

**Comment by vgajendr** [comment]
Can someone help on this

**Comment by davidjgonzalez** [comment]
@vgajendr this doesnt sound like an ACS Commons issue at all, but rather something to do with AEM proper. Youll have better luck reaching out to Adobe Support or ask on Adobe AEM Forums: https://forums.adobe.com/community/experience-cloud/marketing-cloud/experience-manager... this Github project is for ACS Commons issues only.

**Comment by anilkumar19934** [comment]
Can any one suggest ... because I m also facing same issue.
