### ISSUE TITLE
Refresh Hierarchy Parent

### ISSUE THREAD

**Issue by gtxorb** [Adobe-Consulting-Services/acs-aem-commons#198]
This is piece of js to refresh component's parent component. This is for author using in edit view. It is provided a friendly user experience to author especially in a heavy page.
There is a case that when author create the content, he usually drags a container first then the component itself, but after the author edit or delete the component the container can't be refreshed.
It is common to refresh page, but it cost to much when the page is big. So refresh hierarchy parent is more helpful.
It is used in cq:listeners afterdelete or afteredit etc, given a parameter for which level should be refreshed.

**Comment by cgeyma** [comment]
>>This is piece of js to refresh component's parent component. 

please let me know where this piece of JS is.
Thanks.
