### ISSUE TITLE
JsonValueMapValue breaks when space is present

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2000]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc:  All
* [X] ACS AEM Commons Version: 4.2.2
* [x] Reproducible on Latest? yes

via Rajat Pachouri on Disqus:

The JsonValueMapValue Injector injection breaks when there is a space between the string.
e.g it works for "Hello" but fails at "Hello there" as GSON library consider it as malformed. Could be fixed by setting up GSON.setLenient(true).
Having this issue makes this practically unusable as its highly likely that you will add space in what you are authoring.

https://adobe-consulting-services.github.io/acs-aem-commons/features/sling-model-injectors/json-valuemap-value/index.html#comment-4549882259

**Comment by niekraaijmakers** [comment]
Damn! Never realized this. Il fix this asap

**Comment by niekraaijmakers** [comment]
Well. I tried to reproduce but I cannot. I will need more details. Please give me the sling model + exact underlying json stored as property that you are trying to inject.

**Comment by rajatpac** [comment]
I will try to reproduce today and give you guys more details. sorry for the delay.

**Comment by joerghoh** [comment]
@rajatpac any update on this?

**Comment by badvision** [comment]
Closing for now but please open if we can reproduce this with a test case.

**Comment by sau0201** [comment]
Hey, 
I am importing acs-common-4.7.0 bundle in my project. I can see other annotations available like aem object etc, but JsonValueMapValue is not available. 

When I open the jar, I can see the interface for JsonValueMapValue is available but when I try to open impl file, I see the internal error.
