### ISSUE TITLE
dead link in the index page

### ISSUE THREAD

**Issue by vincent-leung-seneca** [Adobe-Consulting-Services/acs-aem-commons#2002]
On the index page ( https://adobe-consulting-services.github.io/acs-aem-commons/features/sitemap/index.html) , there is a dead link for the externalizer.

> See http://dev.day.com/docs/en/cq/current/developing/externalizer.html for more information on configuring the Externalizer.

**Comment by klcodanr** [comment]
Thanks @vincent-leung-seneca - fixed in https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/commit/75838bf59a639c6773a592328a0ae1b936848baa
