### ISSUE TITLE
Remote Assets sync breaks when sync' metadata has a custom namespace

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2003]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.x
* [X] ACS AEM Commons Version: 4.2.2
* [X] Reproducible on Latest? yes

### Expected Behavior

REmote Assets can sync in asset metadata that use custom JCR namespace (ie. ./metadata/foo:bar)

### Actual Behavior

Remore Assets throws an exception and fails to sync the asset.

```
com.adobe.acs.commons.remoteassets.impl.RemoteAssetsNodeSyncImpl Unexpected error sync'ing remote asset nodes
org.apache.sling.api.resource.PersistenceException: Unable to commit changes to session.
javax.jcr.RepositoryException: Invalid namespace prefix ..
```

### Steps to Reproduce

Add a custom namespace to the remote DAM that does not exist on the consumer AEM.
Add metadata properties that use this custom namesapce to an asset to be sync'd
Sync the asset.
Watch the logs on the consumer AEM instances.

### Links

Report via Disqus:
https://adobe-consulting-services.github.io/acs-aem-commons/features/remote-assets/index.html#comment-4551452437

**Comment by HitmanInWis** [comment]
What is the desired fix for this?  One could argue that the local environment should be manually set up with the custom namespace as part of using the feature.  However, just blowing up when that hasn't happened isn't great either :)

Potential Solutions:
- Build in a sync of custom metadata schema configs?
- Simply skip unsupported metadata schema fields, logging that they are skipped?
- Auto-create a simple custom metadata schema w/no details when a property is detected, allowing users to later fill in the details of the schema?
- Other?

**Comment by KulshaPavel** [comment]
As far as I know replication process creates missing namespaces in the target instance as part of the process. Would be nice to have something similar.
At least we should not terminate all the sync process with all already processed assets but just skip asset or metadata with appropriate message in log.

**Comment by davidjgonzalez** [comment]
As @KulshaPavel points out it's not unprecedented for AEM to make namespaces on the fly; IIRC the other time it does this is on XMP metadata extraction when it encounters a property w/ a undeclared NS.

I personally think it should just register the schema; ultimately the source Remote DAM should be the canonical source for assets. If that DAM has determined the NS is OK, then it should be OK for subservient instances. 

Of course, this could be configurable too if there is no consensus.

**Comment by HitmanInWis** [comment]
Sounds good - if it's something AEM does in other cases I don't see why not to do it here - agreed that the remote DAM is the canonical source.  I'll take a look at this when I get some time, but if someone wants to beat me to a PR I'd be more than happy to review it.

Just to confirm, configuring the namespace on the target instance is a valid workaround, and thus this is not urgently blocking anyone, correct?

**Comment by joerghoh** [comment]
As @davidjgonzalez said, I would also register the missing namespaces on the fly, though I don't see any "nice" solution of the overall process runs with a user session in the first place. 

You either retry a failed import with an admin session. Or you check the imported but not yet saved asset for unknown namespaces, register them with an adminsession first and the do the commit of the asset with the usersession.

**Comment by HitmanInWis** [comment]
the process runs as a service user, so I dont think there should be an issue automating the add of a missing namespace, right?

**Comment by joerghoh** [comment]
@HitmanInWis not in that case, true. You just need to add the proper privilege (jcr:nameSpaceManagement) to the service user.

See https://jackrabbit.apache.org/oak/docs/security/privilege/mappingtoitems.html

**Comment by HitmanInWis** [comment]
so my main concern with adding the namespace would be knowing what URL goes with the namespace.  Node sync is happening using the default `.1.json` selctor/extension, which does not include namespace definitions.

Option 1: Fetch /path/to/asset/jcr:content/metadata.docview.xml and dig the namespace definition out of the XML
- This could be thwarted if the remote server has the default XML renderer turned off

Option 2: Fetch /jcr:system/rep:namespaces.1.json from the remote server
- This requires either the `admin` user or another user given special permissions to read this.  Unsure of security implications.

Option 3: Simply register the namespace with a URL of "unknown" or "remoteasset" or something else.  This would be similar to the OOTB `rep` namespace with a URL of "internal"

Any opinions?

**Comment by adamcin** [comment]
@HitmanInWis I don't like Option 3, because once a bad namespace mapping leaks into a repository, its going to be difficult for namespace collisions to be prevented if developers are involved in preparing migration packages. If you can't get the namespace uris with options 1 or 2, it would probably be better to avoid setting the properties with unknown prefixes during the sync.

**Comment by HitmanInWis** [comment]
so maybe try option 1, then option 2, and if both fail then blow up with a meaningful exception?  Or do we just skip the namespaced properties with WARN statements?

**Comment by joerghoh** [comment]
@HitmanInWis wouldn't it be possible to check for each property which RemoteAssets is trying to persist if it requires a namespace and create it if it's not existent? If you give the serviceuser the proper privilege it could be done quite efficient.

**Comment by HitmanInWis** [comment]
@joerghoh I agree with you that the actual checking of namespace and creation of a missing one is pretty trivial.  However, the challenge is knowing what URL to assign the namespace to when creating it.  Since the attributes are fetched via the default JSON exporter, there is no namespace definition included in the retrieved data.  Hence my post above asking for opinions on different options (1, 2, 3) for getting the namespace URL.
