### ISSUE TITLE
Thumbnails are not generating in migration environment

### ISSUE THREAD

**Issue by man178** [Adobe-Consulting-Services/acs-aem-commons#2010]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.4
* [ ] ACS AEM Commons Version: 4.0.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

Thumbnails should be generated for the migrated asset when OOTB DAM Update asset workflow is triggered.

### Actual Behavior
Thumbnail generation for assets are not working on the migration environment but working on the stage. The capacity for migration envornment is m5 Large

### Steps to Reproduce

Go to 
1.https://localhost:4502/miscadmin.
2. Start the thumbnail renditions under the bulkworkflow-manager.
3. Under the path bulk-workflow-execution://etc/acs-commons/bulk-workflow-manager, provide the Query and mention the DAM update workflow.

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by badvision** [comment]
IIRC, thumbnails aren't actually generated by the workflow.  But FWIW, there's a thumbnail regeneration tool in ACS Commons already.

**Comment by bstopp** [comment]
Thumbnails are part of the default/OOTB _DAM Update Asset_ workflow.  However i'm not sure this is a ACS Commons issue - BWF Manager just executes the workflow. It doesn't turn off the workflow. 

Can you confirm manually running a single asset through the workflow doesn't have the same problem?

**Comment by praveenv2018** [comment]
Yes, running a single asset through the workflow doesn't have the problem. If we use Bulkworkflow manager for 500 assets, it hits up to 99% of CPU also it seems to be continuously running and taking the major CPU. Also, I could see some memory issues on the environment as frequent GC was getting triggered

**Comment by badvision** [comment]
Are you using the fast action manager (FAM) option or something else?

**Comment by praveenv2018** [comment]
No, I am using "AEM workflow" option in Bulk Workflow Manager.

**Comment by davidjgonzalez** [comment]
@praveenv2018 you should definitely be using with MCP Thumbnails Generator or at least running Bulkworkflow with Synthetic WF. Why are you running Bulk Workflow Manager as "normal" AEM Workflow? Are you using Dynamic Media or something?

**Comment by praveenv2018** [comment]
Yes, we are using Dynamic media. That is the reason we are running BWM as normal "AEM Workflow".

**Comment by badvision** [comment]
Have you considered making a cut-down workflow with the thumbnail step only and using that with the synthetic+FAM option?

**Comment by davidjgonzalez** [comment]
@badvision I think the problem is the need for DMS7 which is an External Workflow process, which isn't supported by Synthetic.  (Since that spawns sling jobs and then is required to "wait around" for them to complete to get the info back from S7 to persist on the asset)..

TBH i dont have a good suggestion on how to do this :( - unless MCP Thumbnail has some specific magics to handle this.

**Comment by badvision** [comment]
Is DMS7 used to generate the thumbnails?    If so I don't have a good recommendation.  The MCP thumbnail tool basically does an inline call to the servlet which processes thumbnails internally; so I'm not sure if that's going to help in this case.  The prudent thing to do with standard product workflow is to run smaller batch sizes and add a lot of delay between batches; if nothing else you can manually throttle it by submitting less work at a time.

**Comment by davidjgonzalez** [comment]
@badvision  correct- dms7 (the s7 "cloud") processes and created the thumbnail renditions which are sync'd back into AEM. IIRC the reason for this is s7 can handle more file formats (and perhaps w/ a higher fidelity; color ranges, etc.) than aem's internal java image libs.

I think your suggestion is the most apt (and probably the only real approach!) - do it w/ AEM WF, and do it carefully and slowly.

**Comment by randomdude93** [comment]
@davidjgonzalez @badvision  I am in similar situation. We are also using dms7.  We are migrating 90GB assets to AEM. During the migration, workflows are disabled.  Post migration, I was hoping to use Bulk Workflow manager. However, based on this thread it looks like BWM won't support an external step (dms7).  

So our only option is to manually run AEM WF in small batches. Is my understanding correct?
