### ISSUE TITLE
ACS Commons dispatcher flush issue

### ISSUE THREAD

**Issue by Rakesh-Sharma-H-M** [Adobe-Consulting-Services/acs-aem-commons#2013]
## Required Information

AEM Version : 6.4
Service Package : 6.4.4
* [x] ACS AEM Commons Version: 4.1.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

The dispatcher flush page is not deleting the pages in the cache directory.

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

### Steps to Reproduce

Step1:- Create Page from author /miscadmin 
Step2:- Create new page flush page along with title
Step3:- Mention the cache paths
Step5:- Click the button for flush the dispatcher cache.

On clicking on the button the pages are not flushed in the respective cache directories.

![Screen Shot 2019-08-06 at 12 40 11 PM](https://user-images.githubusercontent.com/16306381/62698137-034f4500-b9fa-11e9-9295-839acd448b20.png)

The message appears as success but the files inside the directory is not deleted

**Comment by joerghoh** [comment]
A cache flush does not necessarily remove the files in the dispatcher, but rather only marks them as invalid.

Can you validate this scenario?
# create a number of pages, activate them on author and then request all of them on publish
# change the pages on author, and activate them again
# flush these pages in the dispatcher using the "cache flush" function of ACS AEM Commons
# recheck all pages and make sure that the change is visible.

**Comment by Rakesh-Sharma-H-M** [comment]
Hi,

We verified the steps mentioned but the cache is not getting invalidated.

Thanks,
Rakesh
