### ISSUE TITLE
High Performance SiteMap for Search Promote

### ISSUE THREAD

**Issue by GenxuanHu** [Adobe-Consulting-Services/acs-aem-commons#202]
This is an on-live sitemap generator for search promote indexing with a good performance for tens of thousands children page.

 Let's say there is a site have the structure like 
 /content/
            -abc/
            -games/
                        -a/
                           -apple
                           -aef
                           -abc
                           -other tens nodes...

The crawler of search promote for /content.sitemap.html would get the result as same as the following.

/content/abc.html
/content/games/a.sitemap.html.
......

The child sitemap indexing link (a.sitemap.html here) is for performance perspective and configured by regular expression pattern

**Comment by davidjgonzalez** [comment]
Closing due to lack of interest
