### ISSUE TITLE
Tag Creator not available in ACS Commons

### ISSUE THREAD

**Issue by lumica89** [Adobe-Consulting-Services/acs-aem-commons#2020]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.0
* [x] ACS AEM Commons Version: 4.3
* [x] Reproducible on Latest? yes

### Expected Behavior

I'm able to use the "Tag Creator"-tool from the acs-commons-section since the Tag Maker from acs-tools is outdated.

### Actual Behavior

The tool "Tag Creator" is not available in the acs-commons-tools section.

### Steps to Reproduce

Just install the package and then try to access the "Tag Creator" within acs-commons.

### Links

https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp-tools/tag-creator/index.html
![2019-08-14_14h13_14](https://user-images.githubusercontent.com/14803373/63020176-ad691a00-be9d-11e9-98bd-94c40edbd2e9.png)

**Comment by davidjgonzalez** [comment]
Hi @lumica89 Tag Creator is a MCP process - so goto "Managed Control Process" card, Click the Start button in the top right, and select Tag Creator

![image](https://user-images.githubusercontent.com/1451868/63023901-15a30600-be74-11e9-8864-d394bad35154.png)
