### ISSUE TITLE
ACS Ensure User service duplicates configs after deployment via package manager

### ISSUE THREAD

**Issue by olegsuravnyov** [Adobe-Consulting-Services/acs-aem-commons#2026]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3 SP3
* [ ] ACS AEM Commons Version: 3.19
* [ ] Reproducible on Latest? N/A

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

### Actual Behavior

After deployment via package manager few configurations for Ensure User service factory become duplicated

### Steps to Reproduce

1. Create Ensure User service configuration manually in /system/console, put name for a user - "example-user" and "/home" to the path. Action - "add", ensure immediately - true
2. Create a package for the config above thru package manager and download it
3. Modify the config in the package so that it contains "/home" and "/etc" path
4. Upload and install the package from #3
5. Verify example user config is duplicated
[dup-config-screens.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/3532757/dup-config-screens.zip)

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by joerghoh** [comment]
I guess, that packaging system users and re-deploying them does not really work. EnsureServiceUser works in a way, that it tries to lookup the service user to validate that is there. The fact, that on the second system the user is created for a second time means that the first user is not usable.

Can you try this to validate:
* Download the service user from system A as a package
* Deploy this package into system B
* Validate on system B, that this user is available as service user (not using crxde, but rather via useradmin or code which relies on the existence of this service user!)

My assumption is that on system B this service user is not present then. (That's the reason why this feature exists at all.)

Anyhow: Why do you use EnsureServiceUser to create a service user and then package this service user? Why don't you just package the configuration for EnsureServiceUser and let it do its work?
