### ISSUE TITLE
Align ACS Commons with Adobe Cloud Manager Quality Gates

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2027]
### Expected Behavior

ACS Commons has a number of issues reported when run through Adobe Cloud Manager Quality Gates. We should attempt to resolve as many as possible (prioritizing the higher priority issues)

See report here:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/3534873/build_project_issues-2019-08-23.xlsx

**Comment by kwin** [comment]
Is there any chance to integrate those rules in our CI build? I guess at least a few issues would be detected by SonarQube (https://sonarcloud.io/)...

**Comment by davidjgonzalez** [comment]
@kwin sonarcloud.io is free for OSS right? 

The Cloud Manager sonarQube rules are available here: https://docs.adobe.com/content/help/en/experience-manager-cloud-manager/using/how-to-use/assets/CodeQuality-Rules-new.xlsx

**Comment by justinedelson** [comment]
FWIW, at one point a while ago I looked at what could be done with codeclimate and there's two problems: (1) codeclimate did not allow for the ruleset to be customized for SonarQube and (2) some of the rules in the Cloud Manager set (specifically the findbugs/spotbugs ones) operate on bytecode, not source, and the nature of codeclimate is that it only uses source.

So doing this would require a full sonar installation or SonarCloud, although I do not know to what extent custom plugins can be added to SonarCloud.

**Comment by kwin** [comment]
Yes, AFAIK sonarcloud.io is free for OSS. Should we enable this for the Adobe-Consulting-Services organization (don't know I have enough Karma though). Maybe @davidjgonzalez you could enable that by going to https://sonarcloud.io/projects/create and choose the organization from GitHub. There is some possibility to tweak the configuration  (https://sonarcloud.io/documentation/project-administration/narrowing-the-focus/). But we can just try it out after having enabled it. WDYT?

**Comment by mitchross** [comment]
Please reopen.
