### ISSUE TITLE
Update AEM Uber Jar to 6.3.3 (or later)

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#2029]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4+
* [x] ACS AEM Commons Version: Any
* [x] Reproducible on Latest? yes

### Proposal

Right now we are using 6.3.0 uber jar which has rather dated apis, especially the content fragment API which was updated in 6.3.3 to support things like multiple values.  It would be ideal to move up our minimum version to 6.3 sp3 or later so that we can better support features related to content fragments with the updated API.

**Comment by kwin** [comment]
This is now superseded by #2753
