### ISSUE TITLE
Discussion: Removal of deprecated forms API and move MCP Forms to top-level

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#2041]
Currently the Forms classes in ACS Commons are deprecated, but there is a new form library under MCP which works independently of MCP -- or rather MCP is dependent on it but not the other way around.  This includes the form dialog provider as well as all the supported components and utility classes.

Is there any value in refactoring this functionality into a top-level package or is that not a valuable to anyone?

**Comment by davidjgonzalez** [comment]
FWIW the use-case of the deprecated Forms class was NOT for "authoring forms", but rather web forms end-users would interact with (ex. a registration wizard). Im not sure that MCP Forms covers this use-case... don't these generate Dialog forms that don't manage state across multiple requests?

**Comment by badvision** [comment]
The MCP Forms is really just an abstraction that provides a synthetic granite ui form, so no it wouldn't manage state across multiple requests unless we're talking about each request posting to the same AEM path, that is.

**Comment by davidjgonzalez** [comment]
Right - and you wouldn't use Granite UI forms on your AEM Publish public-facing website, so these are two different use cases.
