### ISSUE TITLE
Composite Multifield Widget checkboxes don't get checked for Coral UI 2

### ISSUE THREAD

**Issue by bastied** [Adobe-Consulting-Services/acs-aem-commons#2042]
## Required Information

* [ ] Using AEM 6.2
* [ ] Using ACS AEM Commons 3.19.0 (but issue is present as of 3.17.2)

### Expected Behavior

When opening a Touch UI dialog that contains an ACS AEM Commons Composite Multifield widget, Coral UI 2 checkboxes (i.e. `/libs/granite/ui/components/foundation/form/checkbox`) inside the multifield should be checked if their value is `true`.

### Actual Behavior

When opening a Touch UI dialog that contains an ACS AEM Commons Composite Multifield widget, Coral UI 2 checkboxes (i.e. `/libs/granite/ui/components/foundation/form/checkbox`) inside the multifield are not checked even though their value is `true`.

### Source of the problem

In the [/content/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/composite-multifield/source/touchui-widgets-init.js](/content/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/composite-multifield/source/touchui-widgets-init.js) file, the `setCheckbox` method was written in a way that doesn't take into account Coral UI 2 checkboxes.

```javascript
setCheckBox: function ($field, value) {
    if($field.parent().hasClass("coral-Checkbox")){
        $field.parent().prop("checked", $field.attr("value") === value);
    }else {
        $field.prop("checked", $field.attr("value") === value);
    }
}
```
For the Coral UI 2 checkbox, `$field.parent()` returns the `<label>` of the field. The line `$field.parent().hasClass("coral-Checkbox")` will evaluate to `true`, and therefore, the code will try to set the `checked` prop on the label, instead of the input.
```html
<label class="coral-Checkbox coral-Form-field">
    <input type="checkbox" class="coral-Checkbox-input" value="true" />
</label>
```
I am not too familiar with Coral UI 3, so I might not be proposing the best solution, but it could look something like this
```javascript
setCheckBox: function ($field, value) {
    if($field.parent().is('label')){
        $field.prop("checked", $field.attr("value") === value);
    } else {
        $field.parent().prop("checked", $field.attr("value") === value);
    }
}
```

**Comment by deenamo** [comment]
I've encountered this issue, too.

As a workaround, you can update your checkbox to CoralUI3 and add a `granite:class=coral-Form-fieldwrapper` property, e.g.
```
myCheckbox
    - granite:class = "coral-Form-fieldwrapper"
    - sling:resourceType = "granite/ui/components/coral/foundation/form/checkbox"
    - name = "./myCheckbox"
    - text = "My Checkbox"
    - value = "true"
```

**Comment by bastied** [comment]
Yes, unfortunately we're currently restricted to Coral UI 2 for the checkbox.

**Comment by bastied** [comment]
Hi, are there any chances of this getting fixed?

**Comment by badvision** [comment]
1) We're really trying to not support older widgets that have already made their way into the product.  Since 6.3 we have encouraged folks to transition over to the product's multifield and direct support questions related to the AEM product team.  It's a much more sustainable solution in the long run.
2) Pull requests are always welcome.  This is a community project which folks work on voluntarily.  There's nothing inhibiting a member of your own team from producing and submitting a fix for this.

**Comment by bastied** [comment]
That's understandable 🙂no worries. Thank you for your response. If I find the time, I'll try to submit something.
