### ISSUE TITLE
AEM Author system/console gets 403

### ISSUE THREAD

**Issue by normraby** [Adobe-Consulting-Services/acs-aem-commons#2052]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: ___AEM 6.3 SP2.CFP2_
* [ ] ACS AEM Commons Version: _4.3.2
* [ ] Reproducible on Latest? yes

### Expected Behavior
http://localhost:4502/system/console/configMgr
should be available

### Actual Behavior
Author system console not found after restart. On only the author instance http://localhost:4502/system/console/configMgr
we get this error
Resource at '/system/console/configMgr' not found: No resource found
To resolve it we restart the instance and try to login to the system/console URL immediately
that only works if we catch it in time

If I remove the ACS commons package and restart issue goes away.

**Comment by davidjgonzalez** [comment]
Do the error.logs show anything?

**Comment by normraby** [comment]
No that is the thing there is no good details into the issue. Here is the latest logs when the issue happens.
https://download.3sharecorp.com/customer/IR/auth-logs-configs.201910918.tar.gz
I had an adobe ticket as well if you are able to view it here is the link.
https://daycare.day.com/content/home/irc/irc_us/customer_services/189805.html#post0041



Norm Raby   |  ROM Team Engineer
Normand.Raby@3sharecorp.com<mailto:normand.raby@3sharecorp.com> | Twitter<https://twitter.com/3SHARE> | LinkedIn<https://www.linkedin.com/company/1621497/> | Facebook<https://www.facebook.com/3share/>
[id:image001.png@01D5114E.F3598830]<https://www.3sharecorp.com/>
[id:image002.png@01D5114E.F3598830]<https://evolve.3sharecorp.com/>

**Comment by normraby** [comment]
David G, do you have anything else on this? Is there something else you new or we can do to troubleshoot this?

Norm Raby   |  ROM Team Engineer
Normand.Raby@3sharecorp.com<mailto:normand.raby@3sharecorp.com> | Twitter<https://twitter.com/3SHARE> | LinkedIn<https://www.linkedin.com/company/1621497/> | Facebook<https://www.facebook.com/3share/>
[id:image001.png@01D5114E.F3598830]<https://www.3sharecorp.com/>
[id:image002.png@01D5114E.F3598830]<https://evolve.3sharecorp.com/>

**Comment by joerghoh** [comment]
Can you be more specific how one can reproduce this? A very simple step-by-step explanation would be great.

**Comment by normraby** [comment]
I gave all the information I have. This only happens on the author instance for one client. It does not happen all the time. Sometimes a restart resolves it. Remove the ACS commons and restarting always resolves it.

Norm Raby   |  ROM Team Engineer
Normand.Raby@3sharecorp.com<mailto:normand.raby@3sharecorp.com> | Twitter<https://twitter.com/3SHARE> | LinkedIn<https://www.linkedin.com/company/1621497/> | Facebook<https://www.facebook.com/3share/>
[id:image001.png@01D5114E.F3598830]<https://www.3sharecorp.com/>
[id:image002.png@01D5114E.F3598830]<https://evolve.3sharecorp.com/>

**Comment by joerghoh** [comment]
The only thing which can go wrong here is that the webconsole itself is not bound/active. The configMgr is not a dedicated servlet, but essential part of the webconsole.

Were you able to access the webconsole at all?

**Comment by normraby** [comment]
Is there an accurate way to monitor the system/console is working?
I get different results sometimes. Currently I have an author instance that gives me a blank page for anything under /system/console. If I view page source I get:

[cid:image001.png@01D590C7.7F592D20]

Norm Raby   |  ROM Team Engineer
Normand.Raby@3sharecorp.com<mailto:normand.raby@3sharecorp.com> | Twitter<https://twitter.com/3SHARE> | LinkedIn<https://www.linkedin.com/company/1621497/> | Facebook<https://www.facebook.com/3share/>
[id:image001.png@01D5114E.F3598830]<https://www.3sharecorp.com/>
[id:image002.png@01D5114E.F3598830]<https://evolve.3sharecorp.com/>

**Comment by mschmid42** [comment]
I've experienced this as well, and we also use ACS Commons. To fix this I've been reinstall the latest service pack, that seems to restore functionality.
