### ISSUE TITLE
Rewrite workflow remover as MCP task

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#2067]
### Proposal

In order to remove extra weight from the package, it makes sense to convert lesser-used utilities to run from the MCP console.   This requires less overall maintenance of the UI (especially in lieu of UI changes in the product over time), as well as provide a more consistent way to provide monitoring and error reporting from these utilities.

**Comment by davidjgonzalez** [comment]
This is a good idea. I created a workflow model data source for the Bulk Workflow process you probably could leverage.

Keep in mind Workflow remover has a scheduled service component to it.

**Comment by badvision** [comment]
I think we're going to keep most of it as-is (including the service component) and just focus on the MCP-based front end in this release.  A more thorough solution would to let MCP manage more of the removal queue and so on, but that's a bit extra.
