### ISSUE TITLE
Enable version client libs for MCP -- WAS: S3 Asset Ingestor tool hangs in state "Starting process, please wait..." on 6.5

### ISSUE THREAD

**Issue by pghanem** [Adobe-Consulting-Services/acs-aem-commons#2075]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.2
* [ ] ACS AEM Commons Version: 4.3.2
* [ ] Reproducible on Latest? yes

### Expected Behavior

Asset ingestion begins and caps out at max size

### Actual Behavior

Hangs in "Starting process" state indefinitely

### Steps to Reproduce

Open S3 Ingestor tool in Manage controlled Processes. Gave valid access ID and secret access key (tested and connects fine in cyberduck) and s3 bucket name, everything else left default or blank.

Question, when referring to "S3 Bucket Name" what exactly does the Tool expect? I'm using what most places would refer to as the S3 bucket name but I have a feeling theres a disconnect here. Though its possible that this doesn't actually matter.

**Comment by badvision** [comment]
Is there anything of interest in the error.log?

**Comment by pghanem** [comment]
Here is a Gist of the error log right after I try starting the ingestion:
https://gist.github.com/pghanem/513601ba54af721cc375db3ff02a12b9

**Comment by pghanem** [comment]
I managed to install the 4.3.4 latest release. Still having the same error message when trying to start the ingestor:

**Comment by badvision** [comment]
When you installed 4.3.4 did you install the separate content package?  We split apps from content, and the content package is supposed to have the necessary ACL on the /var/acs-commons/mcp node to allow the mcp service user read/write on that folder.

**Comment by pghanem** [comment]
Yes, my package manager shows 3 different packages installed: ui.content, ui.apps and content. All 4.3.4

**Comment by badvision** [comment]
I'll work on reproducing this in a clean environment.  Thank you for your patience and assistance while I try to get to the bottom of this gremlin.

**Comment by badvision** [comment]
Can you confirm if you have a /var/acs-commons/mcp folder and if there are ACLs set up on it like this example?  
![image](https://user-images.githubusercontent.com/5144198/67113490-4585c700-f19f-11e9-83d2-7aad6d9db8ec.png)

**Comment by badvision** [comment]
It's ok if your environment just shows everyone with a jcr:read permission only; but the critical one is that the MCP service user should have jcr:all

**Comment by pghanem** [comment]
Here's my environment

![Screen Shot 2019-10-18 at 10 05 46 AM](https://user-images.githubusercontent.com/34144710/67113787-37c84580-f18f-11e9-84d3-b5c56cf169a9.png)

**Comment by badvision** [comment]
There was also a recent change to the client library for the UI; resulting from change of the UI page from /etc to /apps.  If your browser has a stale cache for the client library it can prevent things from starting correctly.  Check the client library, e.g. http://localhost:4502/apps/acs-commons/components/utilities/manage-controlled-processes/clientlibs.js

You should see a variable declaration `SERVLET_URL: "/apps/acs-commons/content/manage-controlled-processes/jcr:content"` -- if you see an /etc path you have a stale clientlib caching in the browser most likely.

**Comment by pghanem** [comment]
No etc path :(
![Screen Shot 2019-10-18 at 10 46 35 AM](https://user-images.githubusercontent.com/34144710/67116092-96dc8900-f194-11e9-976b-d29871612f3a.png)

**Comment by pghanem** [comment]
Weirdly enough, I flushed my cache and its working now. Despite the SERVLET_URL being correct. Thanks for taking a look at this and helping me get to the bottom of it.

**Comment by badvision** [comment]
Reloading that page directly forces a flush. ;)  I am going to keep this issue open but rename it.  If I had enabled version client libs this would have been avoided I think.

**Comment by badvision** [comment]
Thanks for helping confirm this @shsteimer and helping me check on other possibilities @davidjgonzalez !!

**Comment by pghanem** [comment]
@badvision I am actually experiencing a variant of this issue now on my staging instance. The MCP folder that you mentioned earlier in this thread is not present. Do you know why that may be?

**Comment by badvision** [comment]
Have you installed the content package?  That was recently split from ui.apps.

**Comment by pghanem** [comment]
> Have you installed the content package? That was recently split from ui.apps.

It turned out to be that version 4.3.2 had been installed. I remember that one had some issues with the mcp folder. Updating to 4.3.4 did the trick.
