### ISSUE TITLE
We are using acs-commons-generic list component in 6.4(acs-aem-commons-content-3.19.0.zip) but it is not displaying localisation option in the page to provide localized titles for the list.

### ISSUE THREAD

**Issue by AparnaSunkari** [Adobe-Consulting-Services/acs-aem-commons#2079]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [ ] ACS AEM Commons Version: _____
* [ ] Reproducible on Latest? yes/no

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by badvision** [comment]
1) To be honest, I don't think that localization feature was fully implemented.  @davidjgonzalez any thoughts on that?
2) I just rewrote the entire thing in 4.2.4 and 3.19.0 is a rather old version of this feature.  I don't have any plans to maintain the legacy version of this feature, it's all touch ui based now.

**Comment by badvision** [comment]
Due to lack of response, I am closing this issue.  If this is still needed and you can take some time to answer the above questions, feel free to re-open this issue and I'll have a look at it.
