### ISSUE TITLE
Feature/CORS filter 

### ISSUE THREAD

**Issue by kalyanar** [Adobe-Consulting-Services/acs-aem-commons#208]
A CORS Filter that we can configure the allowed sources,headers etc ,for easy access from apps as well as js access from sites.
This will predominantly handle the preflight requests(OPTIONS) .

**Comment by davidjgonzalez** [comment]
AEM 6.3 now provides CORS OOTB
* https://helpx.adobe.com/experience-manager/kt/platform-repository/using/cors-security-article-understand.html
