### ISSUE TITLE
On-Deploy Framework commits changes made by failing scripts

### ISSUE THREAD

**Issue by csaboka** [Adobe-Consulting-Services/acs-aem-commons#2090]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3.3.0
* [ ] ACS AEM Commons Version: 3.17.4
* [ ] Reproducible on Latest? (haven't checked yet, but based on the code it should be)

### Expected Behavior

When an on-deploy script is being executed and an unhandled exception escapes from the execute() method, I expect that any uncommitted changes made through the provided resource resolver are discarded.

### Actual Behavior

When an exception escapes from an on-deploy script, the pending changes of the resource resolver are persisted.

### Steps to Reproduce

Below is a minimal script provider that demonstrates the issue. Once you deploy that provider into an AEM instance, you should see a node at "/content/should-not-see-me". This is a node created by a script just before throwing an exception. Since the script didn't commit its changes manually before throwing, it's expected that the changes are discarded and you don't see the new node.

```java
package com.example.issue.repro;

import java.util.Collections;
import java.util.List;

import org.apache.sling.api.resource.Resource;
import org.apache.sling.api.resource.ResourceResolver;
import org.osgi.service.component.annotations.Component;

import com.adobe.acs.commons.ondeploy.OnDeployScriptProvider;
import com.adobe.acs.commons.ondeploy.scripts.OnDeployScript;
import com.adobe.acs.commons.ondeploy.scripts.OnDeployScriptBase;

@Component
public class IssueReproOnDeployScriptProvider implements OnDeployScriptProvider {

  private static class FailingScript extends OnDeployScriptBase {

    @Override
    protected void execute() throws Exception {
      ResourceResolver resolver = getResourceResolver();
      Resource content = resolver.getResource("/content");
      resolver.create(content, "should-not-see-me", Collections.emptyMap());
      
      throw new IllegalStateException("Simulating script error");
    }
    
  }
  
  @Override
  public List<OnDeployScript> getScripts() {
    return Collections.singletonList(new FailingScript());
  }

}
```

**Comment by csaboka** [comment]
The issue seems to be caused by the fact that OnDeployExecutorImpl.runScript() uses the same resource resolver for tracking the script status and for executing the script itself. When it commits to record the script failure, all pending changes made by the script are also committed.

I can see two ways to eliminate the issue:
* Clone the resource resolver and pass the clone to the script. This way, the changes made by the script become independent from the status tracking repo changes and uncommitted changes are discarded when the clone gets closed.
* Call revert() on the resource resolver before recording a script failure to explicitly throw away any pending changes made by the script.

**Comment by badvision** [comment]
Revert seems like a prudent course of action.
