### ISSUE TITLE
Remove c.a.a.c.remoteAssets.RemoteAssetsConfig from public API

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#2094]
Currently the interface RemoteAssetsConfig is publicly exposed, although 

1) it should not be exposed because it's an interface only implemented by the non-exported RemoteAssetsConfigImpl, and details about the OSGI config are not required to be exposed here.
2) It cannot be used from externally (implementing it does not make sense)

Thus we should remove it from the exports for the ACS AEM Commons bundle.

(Then its use is getting questionable, because it is only used within the remoteAssets feature. Instead of referencing the RemoteAssetsConfig class, other class could reference directly the RemoteAssetsConfigImpl class, and the internal interface would not be necessarry.)

**Comment by joerghoh** [comment]
@HitmanInWis you are the biggest contributor of the Remote Assets feature, what do you think? Has this interface been exposed by intent?

**Comment by HitmanInWis** [comment]
can you help me understand the problem we are solving?   Is there inherent harm in the interface being publicly exposed?  Technically someone *could* implement their own impl if they wanted, though there's probably not a legit reason to, but I also dont know the harm that's being caused either by it being public.

**Comment by joerghoh** [comment]
While working on #2086 I came across the method ``closeResourceResolver`` and think that it is not really necessary; any call of it could be replaced simply by ``resourceResolver.close()`` (or by the try-with-resource approach, which calls ``close()`` implicitly). I don't see the purpose of having wrapper methods for ``resourceResolver.close()``. 

Thus we can either leave this method as is (with the chance, that someone is using it), we can deprecate it (only a bit better, as it will be part of the interface for longer time and we never know when to remove), or we can remove it right now, as we know all consumers inside ACS AEM Commons, and for everyone else we can provide releasenotes how to adjust their code.

And instead just removing this method from the interface (which is an incompatible change anyway), I thought about removing this interface completely. Because as said, it does bring any value.

I see ACS AEM Commons also a living styleguide how developing can be done on AEM. People look how things are done and copy the style from they find here. That's the reason I sometimes try to refactor a bit, improve code and make it easier to understand.
(Of course that's always my way of "easier to understand", but for that reason we have PRs and code reviews.)

**Comment by HitmanInWis** [comment]
looks like the code is checking for and closing a `Session` as well as the resolver.  Do you know if that's completely unnecessary?  If so, the I agree that the function is probably not necessary.

I'm personally indifferent to removing the public interface - I thought it was standard to have an interface for all services.

**Comment by davidjgonzalez** [comment]
The irony being, while services can be registered to any type (not just interfaces), it’s absolutely best practice to use an interface as it decouples the consumer from the implementation. Imo this feature is isolated within this code base so it’s not a big deal. Technically, removing a public interface is a breaking change and per semantic versioning asks for a major version bump, but I can’t imagine a user of acs commons ever relying on this interface IRL.

**Comment by joerghoh** [comment]
@HitmanInWis The rule of thumb is: "You open it, you close it". If you open a ResourceResolver, you just close the ResourceResolver. The fact, that internally a JCR Sesesion might be opened, is an implementation detail, and the implementation takes care of closing the session when the ResourceResolver is closed.

This behavior is consistent. If you use an already existing session to create a new wrapping ResourceResolver (see [1] for an example how to do that), then you must close both. You opened both the session and the resourceresolver explicitly.

[1] https://github.com/Adobe-Consulting-Services/acs-aem-samples/blob/master/bundle/src/main/java/com/adobe/acs/samples/workflow/impl/SampleWrappingWorkflowProcess.java#L161

**Comment by joerghoh** [comment]
Regarding the "a java interface for each service" discussion: If you implement a publicly usable service (which is exported to other bundles), that's the recommended way to do so, and there is hardly a justification not to do so.

When I implement services I want to access only from classes/services of the same Java package, I often omit the interface, because it does not bring any value. Any change to the service methods is harder to make (2 files to change), and benefit of it (separating implementation from public API) simply does not exist to justify the work.

**Comment by joerghoh** [comment]
The change was committed in #2101.

**Comment by joerghoh** [comment]
@badvision, @davidjgonzalez please close this issue, it's implemented in an earlier release.
