### ISSUE TITLE
Modifying a generic list deletes the sling:resourceType property on the item

### ISSUE THREAD

**Issue by swaroop61** [Adobe-Consulting-Services/acs-aem-commons#2099]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.2.0
* [x] ACS AEM Commons Version: 4.3.4
* [x] Reproducible on Latest? yes

Upgrading to acs commons 4.3.4 breaks any generic list that was extended with either additional fields or field labels changes. The resource type for the generic list item is not preserved.

### Expected Behavior
After installing acs-commons 4.3.4 version, edit the Report parameter components generic list and the items saved should retain the sling:resourceType property

/etc/acs-commons/lists/report-parameter-components/jcr:content/list/default_0

sling:resourceType=acs-commons/components/utilities/genericlist/item

### Actual Behavior

The sling:resourceType property is deleted

### Steps to Reproduce

- Install acs-commons 4.3.4
- Edit the generic list supplied.

### Links

N/A

**Comment by badvision** [comment]
The sling resource types were a hold-over from the previous implementation that used the page editing feature to build the list.  The new version is based on the properties dialog and multifield, and as such does not need the sling resource type to function.  Is there a reason you need the resource type for items?

**Comment by swaroop61** [comment]
It was used to extent the generic list to hold more than a key-value pair, some of the generic list were extended to hold 3 values, how can we extent the new properties dialog and multifield to store more?

**Comment by badvision** [comment]
The new dialog is rendered by the MCP dialog provider and is based on the resource type of the container, the generic list itself as a whole.  To make these kind of overrides I believe you'd have to extend the generic list itself, not the child item types.   Just note that the generic list dialog is rendered via the MCP dialog provider so there's no dialog.xml anywhere in the code.  It's rendered based on the annotations in the actual bean.  Still follows all the sling conventions internally though, FWIW.

**Comment by davidjgonzalez** [comment]
creating "custom" items is a relatively common use case for Generic Lists. Coupled w/ the "too many sling includes" exceptions you see for large lists, does it make sense (or even possible) to have the lists items simply be rendered by a script? Not sure the LOE would be decoupling from the model. 

IIRC the original impl which functionally never had complaints, just included a list-item component, a which could be authored by a dialog - allowing both facets (the form and the list presentation) to be customizable. (and decrease the likelihood of hitting the "too many sling includes" were seeing w/ the "inline form" impl of this)
