### ISSUE TITLE
Multifield is not storing values as JSON | ACS commons 4.3.0.1 | AEM 6.3

### ISSUE THREAD

**Issue by RohitUtreja** [Adobe-Consulting-Services/acs-aem-commons#2100]
## Required Information

* AEM 6.3 with SP 6.3.2.
* ACS AEM Commons Version: 4.3.0.1-Snapshot
* Reproducible on Latest? yes

### Expected Behavior
Multifiled should store values as JSON whenever we are providing the attribute "acs-commons-nested="JSON_STORE" as mentioned in ACS-commons doc.

### Actual Behavior

Whenever we are creating a multifield in touchui with recommended parameters to store values in JSON format, it is not working properly. Instead of saving value in JSON format, it is saving value in the multivalue property.

### Steps to Reproduce

Create a new component with touch ui. I have referred the below code snippet(which is provided in file : /apps/acs-commons/touchui-widgets/composite-multifield/source/touchui-composite-multifield.js) to create a dialog with multifield but it is not saving values in JSON format.

### TouchUI dialog XML used for multifield component:

` <?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
        jcr:primaryType="nt:unstructured"
        jcr:title="ACS AEM Commions Multifield TouchUI Component"
        sling:resourceType="cq/gui/components/authoring/dialog"
        helpPath="en/cq/current/wcm/default_components.html#Text">
    <content jcr:primaryType="nt:unstructured"
        sling:resourceType="granite/ui/components/foundation/container">
        <layout jcr:primaryType="nt:unstructured"
                sling:resourceType="granite/ui/components/foundation/layouts/fixedcolumns"/>
        <items jcr:primaryType="nt:unstructured">
            <column jcr:primaryType="nt:unstructured"
                    sling:resourceType="granite/ui/components/foundation/container">
                <items jcr:primaryType="nt:unstructured">
                    <fieldset jcr:primaryType="nt:unstructured"
                            jcr:title="Sample Dashboard"
                            sling:resourceType="granite/ui/components/foundation/form/fieldset">
                        <layout jcr:primaryType="nt:unstructured"
                                sling:resourceType="granite/ui/components/foundation/layouts/fixedcolumns"/>
                        <items jcr:primaryType="nt:unstructured">
                            <column jcr:primaryType="nt:unstructured"
                                    sling:resourceType="granite/ui/components/foundation/container">
                                <items jcr:primaryType="nt:unstructured">
                                    <dashboard jcr:primaryType="nt:unstructured"
                                            sling:resourceType="granite/ui/components/foundation/form/textfield"
                                            fieldDescription="Enter Dashboard name"
                                            fieldLabel="Dashboard name"
                                            name="./dashboard"/>
                                    <pages jcr:primaryType="nt:unstructured"
                                            sling:resourceType="granite/ui/components/foundation/form/multifield"
                                            class="full-width"
                                            fieldDescription="Click '+' to add a new page"
                                            fieldLabel="Pages">
                                        <field jcr:primaryType="nt:unstructured"
                                                sling:resourceType="granite/ui/components/foundation/form/fieldset"
                                                acs-commons-nested="JSON_STORE"
                                                name="./pages">
                                            <layout jcr:primaryType="nt:unstructured"
                                                    sling:resourceType="granite/ui/components/foundation/layouts/fixedcolumns"
                                                    method="absolute"/>
                                            <items jcr:primaryType="nt:unstructured">
                                                <column jcr:primaryType="nt:unstructured"
                                                        sling:resourceType="granite/ui/components/foundation/container">
                                                    <items jcr:primaryType="nt:unstructured">
                                                        <page jcr:primaryType="nt:unstructured"
                                                                sling:resourceType="granite/ui/components/foundation/form/textfield"
                                                                fieldDescription="Name of Page"
                                                                fieldLabel="Page Name"
                                                                name="./page"/>
                                                        <path jcr:primaryType="nt:unstructured"
                                                                sling:resourceType="granite/ui/components/foundation/form/pathbrowser"
                                                                fieldDescription="Select Path"
                                                                fieldLabel="Path"
                                                                name="./path"
                                                                rootPath="/content"/>
                                                    </items>
                                                </column>
                                            </items>
                                        </field>
                                    </pages>
                                </items>
                            </column>
                        </items>
                    </fieldset>
                </items>
            </column>
        </items>
    </content>
</jcr:root>`

I have tried with coral ui as well but that approach didn't work as well.

Screenshot of value which are getting saved now.
![image](https://user-images.githubusercontent.com/35956275/68458041-ccbadd80-0227-11ea-828f-1761a685e7d3.png)

It should be stored in the form of JSON.

**Comment by davidjgonzalez** [comment]
If you have a **new** component you should be using the OOTB Granite UI Multifield Widget. This widget is deprecated and historically has a lot of issues when people try to use it in even slightly out-of-the-ordinary ways.

(I believe the OOTB GraniteUI Multifield is available in 6.3.2, if not and you really need mutlifields, now you have a good reason to upgrade AEM! But please don't use this widget for new work!)
