### ISSUE TITLE
Update Mocking Libraries to work with Java11

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#2103]
The naive approach just to switch the JVM from 8 to 11 is not working well. We have a few failing test cases which point to issues with mocking libraries (especially powermock). But upgrading powermock alone does not help, but we should upgrade mockito as well (and we are on a pretty old version right now).

**Comment by badvision** [comment]
It is possible to switch to the newer mockito and, with the right annotations at the top to ignore some problematic java classes, have the static mocks work again.  Ultimately, though, we might do better in the long run to reduce our dependency on mockito for this, as the jigsaw changes from Java 9 and onward make it much harder for stuff like Mockito to work correctly.  Instead, we should refactor the code where possible to ensure unit tests don't have to do backflips.

**Comment by badvision** [comment]
So one example is using static methods like JcrUtils which do not work well in unit tests.  If we refactor those into facade services then we can more easily inject a mock service implementation that we can use in the unit tests.

**Comment by joerghoh** [comment]
I am sure that in many cases we could switch to AemContext/SlingContext and get rid of cascades of mocks. That would be definitely some great contribution.

**Comment by joerghoh** [comment]
#2104  has been merged.
