### ISSUE TITLE
Next Release -> ACS Commons 4.4.0

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2106]
The next release will be 4.4.0 since master now includes the new Marketo Component.

**Comment by badvision** [comment]
We might want to consider #2029 so we can finally introduce features that leverage structured content fragments.  Thoughts?

**Comment by badvision** [comment]
I moved all issues tagged against the 4.3.6 milestone over to 4.4.0

**Comment by davidjgonzalez** [comment]
Note that the release process from this release was problematic and logged in #2137 as a bug. We need to get better at validating large, project-wide changes. This wasted a lot of time.
