### ISSUE TITLE
A kind of potential NullPointerException bug.

### ISSUE THREAD

**Issue by JulyChen728** [Adobe-Consulting-Services/acs-aem-commons#2111]
Hi all,

Our tool has found a kind of potential NPE bug.

The core point is in method [```createNativeJPEGReader```](bundle/src/test/java/ch/randelshofer/media/jpeg/CMYKJPEGImageReader.java#L257) that may return null. There are several points that may use the null and cause NPE, including methods [```readImageFromYUVorGray```](bundle/src/test/java/ch/randelshofer/media/jpeg/CMYKJPEGImageReader.java#L677), [```readRGBImageFromInvertedYCCK```](bundle/src/test/java/ch/randelshofer/media/jpeg/CMYKJPEGImageReader.java#L356), [```readRGBImageFromYCCK```](bundle/src/test/java/ch/randelshofer/media/jpeg/CMYKJPEGImageReader.java#L330), [```readRGBAImageFromRGBA(InputStream```](bundle/src/test/java/ch/randelshofer/media/jpeg/CMYKJPEGImageReader.java#L304), [```readRGBImageFromCMYK(InputStream```](bundle/src/test/java/ch/randelshofer/media/jpeg/CMYKJPEGImageReader.java#L276), 
For example,

```
    public static BufferedImage readImageFromYUVorGray(ImageInputStream in) throws IOException {
        ImageReader r = createNativeJPEGReader();
        r.setInput(in);
        BufferedImage img = r.read(0);
        return img;
    }
```
If ```r``` is null, then executing ``` r.setInput(in);``` will cause NPE.

Thanks.

**Comment by ITWOI** [comment]
Hi, we have reported the bugs a while ago would you please take a look and confirm if they are real bugs. We have been conducting an experiment to measure the accuracy of our static checker. We would be deeply appreciated if you can provide some feedback!

**Comment by joerghoh** [comment]
technically it's possible; practically it's rather unlikely because then the JDK did not provide any ImageReader for JPEG, which is highly unlikely.

**Comment by badvision** [comment]
Not a bug, if you're finding an error in this code you're also (surprise, surprise) not running a supported JVM for the product either and you're on your own there.
