### ISSUE TITLE
Test Page Generator

### ISSUE THREAD

**Issue by VixKamboj** [Adobe-Consulting-Services/acs-aem-commons#2116]
Hi Team,

We are looking to generate some test pages based on some tags and properties. I understand there is an ACS AEM Tools v1.0.2 package which help to generate some test pages. However, We found that this package is supported till AEM 6.4 version only. Since we are on AEM 6.5, could you please provide a package for AEM 6.5 version.

https://adobe-consulting-services.github.io/acs-aem-tools/
https://github.com/Adobe-Consulting-Services/acs-aem-tools/releases
https://adobe-consulting-services.github.io/acs-aem-tools/features/test-page-generator/index.html

Please send a repsonse to vikramjeet.singh@medibank.com.au

**Comment by joerghoh** [comment]
Can you please raise this ticket over at https://adobe-consulting-services.github.io/acs-aem-tools/issues? It's the wrong project here :-)
