### ISSUE TITLE
Unable to read SCR descriptor file from JAR File of ACS Commons 4.0.0

### ISSUE THREAD

**Issue by atulkumar7** [Adobe-Consulting-Services/acs-aem-commons#2119]
## Required Information
We have recently upgraded from acs-commons-3.8.4 to acs-commons-4.0.0.
However, now when we run maven install command we get below warning messages in Build Console:
{WARNING] Unable to read SCR descriptor file from JAR File C:\Users\atukumar\.m2\repository\com\adobe\acs\acs-aem-commons-bundle\4.0.0\acs-aem-commo ns-bundle-4.0.0.jar at OSGI-INF/com.adobe.acs.commons.workflow.bulk.removal.impl.servlets.ForceQuitServlet.xml
ERROR:  ''

This error is happening only for acs-commnons xml files. 
Below are POM details:

Parent POM:
```
<plugin>
         <groupId>org.apache.felix</groupId>
         <artifactId>maven-scr-plugin</artifactId>
         <version>1.20.0</version>
</plugin>
```
```
<dependency>
       <groupId>com.adobe.acs</groupId>
       <artifactId>acs-aem-commons-bundle</artifactId>
       <version>4.0.0</version>
       <scope>provided</scope>
</dependency>
```
Core POM:
```
<plugin>
         <groupId>org.apache.felix</groupId>
         <artifactId>maven-scr-plugin</artifactId>
         <executions>
              <execution>
                   <id>generate-scr-descriptor</id>
                   <goals>
                         <goal>scr</goal>
                    </goals>
               </execution>
                </executions>
</plugin>
```
### Expected Behavior

This warning was not showing when we were using acs-commons-3.8.4.

### Actual Behavior

Build should be completed without this warning message.
### Steps to Reproduce

To Reproduce this issue, add acs-aem-commons-bundle version 4.0.0. and add scr annotations to any of your java class.

Note: We tried to change scr plugin version to different versions but at that time we are getting below error:
[ERROR] Failed to execute goal org.apache.felix:maven-scr-plugin:1.26.2:scr (generate-scr-descriptor) on project Project.core: SCR Descriptor parsing had failures (see log) -> [Help 1]

**Comment by joerghoh** [comment]
I don't really understand what you tried to do. Are you rebuilding acs aem commons 4.0 on your system and encounter a build failure? Have you upgrade acs-aem-commons to 4.0 as your your project dependency and now encounter build issues on your project?

And when do you get this warning? During compilation of the main code or test code?

**Comment by atulkumar7** [comment]
Hi Jorg,

I have upgraded to acs-aem-commons to 4.0.0 in my project dependency. Previously we were using acs-aem-commons-3.8.4 version.

If i build my project using 3.8.4 version i am not getting any warning messages. But as soon as i add 4.0.0 version in my POM and build my project i am seeing below errors:

![image](https://user-images.githubusercontent.com/56590719/69526506-52f95280-0f90-11ea-9867-d6be82dc27a1.png)

The warning is coming only for acs-commons files. This is coming while compilation of main code itself.

**Comment by joerghoh** [comment]
The error message is quite strange. Can you try upgrading your setup first?

* update to a later version of ACS AEM Commons?
* update the maven-scr-plugin to 1.26.0?

**Comment by badvision** [comment]
I'm going to close this issue for now, but if you can reproduce with the recent version of ACS Commons please re-open and submit your logs as an attachment.
