### ISSUE TITLE
Not able to save cq:name property to jcr:content node using mcp tool URL importer

### ISSUE THREAD

**Issue by praveenv2018** [Adobe-Consulting-Services/acs-aem-commons#2129]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______6.5
* [ ] ACS AEM Commons Version: _____4.3.2
* [ ] Reproducible on Latest? yes

### Expected Behavior
I am using MCP tool URL importer to upload assets and assign metadata. Metadata is saving to metadata node but the property cq:name is not saving to jcr:content node. I am using the excel header for this property as ../../jcr:content/cq:name. Can you please guide me how to achieve this?
_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._
cq:name property value is not saving
### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by badvision** [comment]
I haven't tested this feature with relative paths for property names.  Not impossible to support, mind you, but this would be a feature request.
