### ISSUE TITLE
MCP URL Asset Importer Issue

### ISSUE THREAD

**Issue by ab9801** [Adobe-Consulting-Services/acs-aem-commons#2130]
## Required Information

* [ ] AEM 6.5.2
* [ ] ACS AEM Commons Version: 4.3.4

### Expected Behavior

Uploading assets from local drive to aem using the spreadsheet template given in URL Asset Importer, Assets get uploaded successfully.
 
### Actual Behavior
Process Manager says job is completed but on checking only the folders are created and the folders are empty (none of the assets are uploaded).

### Steps to Reproduce

Create a spreadsheet from the given template
change the source paths to assets on local drive
login to aem assets
go to acs aem commons and click manage controlled process
click start new process
choose url asset importer
upload the spreadsheet 
click import

Note:the path used to import an asset (for example) is:
C:/abc/def/asset.jpg

**Comment by cylinder-y** [comment]
Do you have any exceptions in logs?
