### ISSUE TITLE
ValueFormat uses most copied stack exchange code in the world, which also has a bug

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#2132]
## Bug details

The human-readable byte size converter function in ValueFormat uses the most popular stack exchange code snippet in the world, but close to (but not exceeding) boundary thresholds it tends to perform incorrectly due to precision errors in the math involved.

## The fix

The original author (Andreas Lundblad) has posted explanations of the issue and the fix here: https://programming.guide/worlds-most-copied-so-snippet.html

**Comment by joerghoh** [comment]
For a potential fix see #2148
