### ISSUE TITLE
Error while executing Asset Report through ACS AEM Commons in AEM 6.5

### ISSUE THREAD

**Issue by Chethan-Nataraju** [Adobe-Consulting-Services/acs-aem-commons#2134]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5.1
* [ ] ACS AEM Commons Version: 4.0.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

When we give the Path, Start Date and End Date and select All results check box and then after clicking the Execute Report we used to get the asset details for that particular period.

### Actual Behavior

But now we are getting Error message after clicking Execute Report

### Steps to Reproduce

1. Click on Tools
2. Select ACS AEM Commons 
3. Select Asset Report  
4. Enter the details
       Path : 
       Start Date:
       End Date:
5. Select All Results checkbox
6. Click on Execute report.

**Request you to share your findings on the same at the earliest.**

**Comment by Chethan-Nataraju** [comment]
Hi,
Request you to provide the suggestions on the issue as it is critical requirement for us

**Comment by Chethan-Nataraju** [comment]
Hi Team,
Requesting you to provide your findings on this, as this is a critical issue

**Comment by badvision** [comment]
Have you tried a newer version of ACS Commons?  We've been fixing bugs, etc and I'm not sure that this issue is reproducible.  Also, it would be most helpful if you provide the actual error you're getting as "error message" could mean virtually anything.
