### ISSUE TITLE
acs-aem-commons-bundle:jar:4.4.0 is not published on Adobe repository[https://repo.adobe.com/nexus/content/groups/public]

### ISSUE THREAD

**Issue by chekurisriharsha** [Adobe-Consulting-Services/acs-aem-commons#2141]
## Required Information

* [ ] AEM Version 6.5.3
* [ ] ACS AEM Commons Version: 4.4.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

Download acs-aem-commons-bundle:jar:4.4.0 from Adobe Repository when running `mvn install`

### Actual Behavior

- Could not resolve dependencies for project cision:cision.core:bundle:1: Could not find artifact com.adobe.acs:acs-aem-commons-bundle:jar:4.4.0 in adobe-public-releases (https://repo.adobe.com/nexus/content/groups/public)

- acs-aem-commons-bundle:jar:4.4.0 is not published on Adobe repo

### Steps to Reproduce

Update the pom.xml for acs-aem-commons-bundle:jar:4.4.0 and do `mvn install`

**Comment by rwunsch** [comment]
We are seeing the same issue when building the our project.

**Comment by kwin** [comment]
Not only the bundle is missing but also the packages: https://repo.adobe.com/nexus/content/groups/public/com/adobe/acs/acs-aem-commons/
@davidjgonzalez Can you check with Adobe Infra?

**Comment by davidjgonzalez** [comment]
@kwin I bumped this last week - ill check again tomorrow though

**Comment by kwin** [comment]
Thanks, it is there now!

**Comment by davidjgonzalez** [comment]
This should be resolved now (looks like there was an issue with the twitter jar, but rest are up)
