### ISSUE TITLE
directory bundle/src/main/resources/remoteassets adds binary assets to the bundle

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#2149]
The directory bundle/src/main/resources/remoteassets contains a number files with the pattern "remote_asse.* with varios extensions). They consume nearly 8 MB of disk and are also part of the  bundle. I don't think that these are necessary runtime of the bundle. I rather assume that they are input for tests.

@HitmanInWis You have committed these files, can you give some insight here?

**Comment by davidjgonzalez** [comment]
@joerghoh if memory serves those are the "shell" asset visuals that are displayed before the "real" assets (and thus real generated thumbnails) are synced into AEM.

**Comment by HitmanInWis** [comment]
@davidjgonzalez is correct - they are the temporary assets put into the DAM in place of the real ones, ensuring no strange things happen in AEM by not having some sort of binary there.  For `admin` users, which do not trigger an asset sync, those assets are what they actually see in the DAM.

**Comment by joerghoh** [comment]
Understood & thanks for the clarification.
