### ISSUE TITLE
Please advise further on the usage of S3 ingestor bucket. Customer is manually uploading the assets since S3 Ingestor bucket is not syncing assets in a timely manner.  Would it overwrite what's already there? Would it duplicate the assets ?

### ISSUE THREAD

**Issue by meejain** [Adobe-Consulting-Services/acs-aem-commons#2150]
Please advise further on the usage of S3 ingestor bucket. Customer is manually uploading the assets since S3 Ingestor bucket is not syncing assets in a timely manner.

Would it overwrite what's already there? Would it duplicate the assets ?

**Comment by badvision** [comment]
The S3 asset ingestion option is provided as one of several options for ingesting assets into an AEM environment already hosted in AWS.  This process does not use the same S3 bucket as that used by AEM, and is only intended to be a potentially temporary S3 bucket used during the duration of the data transfer.  The handling of assets that already exist is explained in the documentation here: https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp-tools/asset-ingestion/s3-asset-ingestor/index.html  Short answer is that you don't get duplicated content but you do have the option to skip duplicated content if it already exists in the same target location in AEM, e.g. if you are running the same import twice against the same s3 bucket going to the same target AEM location, and no files were moved in S3, etc.  You can also tell it to version existing assets or replace the current version only (which doesn't retain the previous copy of the asset.)   In most cases, you can do fine using the "Skip" option if S3 is used only for transferring data and is not used for moving in-progress work copies of assets.
