### ISSUE TITLE
License Header Script Updates Incorrectly

### ISSUE THREAD

**Issue by klcodanr** [Adobe-Consulting-Services/acs-aem-commons#2151]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _N/A
* [x] ACS AEM Commons Version: _4.4.0
* [x] Reproducible on Latest? yes

### Expected Behavior

The [Contribution Guidelines](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/CONTRIBUTING.md) instruct contributors to run the following command to ensure licenses are added correctly. 

`mvn license:update-file-header`

This script should add license headers to files missing the header.

### Actual Behavior

This command updates a number of files which already have the header and updates JSON files which cannot contain comments.

### Steps to Reproduce

- Checkout the latest code
- Run the command `mvn license:update-file-header`
- Run the command `git status`

**Comment by joerghoh** [comment]
@klcodanr I guess that limiting these headers to files in ``bundle/src/main/java`` and ``bundle/src/test/java`` should suffice for the moment. I haven't found JSON files in there.
