### ISSUE TITLE
AEM delta content Refresh from production to staging

### ISSUE THREAD

**Issue by pasupularamanatha** [Adobe-Consulting-Services/acs-aem-commons#2155]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3.0.2
* [ ] ACS AEM Commons Version: Version: 4.2.0
* [ ] Reproducible on Latest? no

### Expected Behavior

We are planning to do aem content delta refresh from production to non production environment. Do any one explain the proceedure?

### Actual Behavior

No refresh planned as of now

### Steps to Reproduce

N/A

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by joerghoh** [comment]
It is not clear to me, if this is a feature request to ACS AEM Commons? A question towards a specific feature? Or rather a specific question how to implement a process best with AEM?

**Comment by pasupularamanatha** [comment]
VLT-RCP for content refresh from prod to non prod environment in AEM. Just need any sample document to implement.

**Comment by joerghoh** [comment]
I guess that the AEM Forums [1] are a better place to ask questions like this.

[1] https://experienceleaguecommunities.adobe.com/t5/Adobe-Experience-Manager/ct-p/adobe-experience-manager-community
