### ISSUE TITLE
Wrong injector when handover parameter from Sightly to SlingModel 

### ISSUE THREAD

**Issue by beo4** [Adobe-Consulting-Services/acs-aem-commons#2157]
## Required Information

* [ x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.4
* [ x] ACS AEM Commons Version: > 4.0.0
* [ x] Reproducible on Latest? yes

### Expected Behavior

When handing in parameters from htl to SlingModel a String Object is handed to JavaClass

e.g.
```
@Inject
@org.apache.sling.models.annotations.Optional
Object linkClasses;
```
corresponding html

data-sly-use.hello="${'de.eggs.core.models.HelloWorldModel' @ linkClasses=['custom-link']}"

### Actual Behavior

After installing ACS-Commons > 4.0.0 the handed Object is not a String or String Array anymore, instead a I18N Object is injected

Some more wrong Injection Mapping occure after installing ACS-Commons > 4.0.0 I will provide more later

### Steps to Reproduce
Install Project from
https://github.com/eggsunimediaGmbH/acs-commons 
Insert HelloWorld Component 

Install ACS-Commons 4.4 Debugging class de.eggs.core.models.HelloWorldModel See that htlParameter property is now I18N class

### Links

https://github.com/eggsunimediaGmbH/acs-commons

**Comment by badvision** [comment]
Is there some way we can convert your debugging class into a proper unit test?  That would help a lot!

**Comment by beo4** [comment]
> Is there some way we can convert your debugging class into a proper unit test? That would help a lot!

I try

**Comment by beo4** [comment]
Added a jUnit Test which reproduce the issue in the attached git repo
https://github.com/eggsunimediaGmbH/acs-commons/blob/master/core/src/test/java/de/eggs/core/models/HelloWorldModelTest.java

**Comment by joerghoh** [comment]
Thanks for the testcase. 

It seems that the problematic part is the ```I18NInjector```. If you don't register this service in your unittest, everything is fine. This injector has been added in ACS AEM Commons, so it matches with your observation.

For me it seems that this I18NInjector has a higher priority than the other injectors and can also handle any injections of objects, which are assignable from I18N (and of course ```Object``` can be assigned from any class).

I would think in 2 different ways now:
* Can you improve your injection by not using ```Object htlParameter```, but a something more specific class?
* In parallel we should improve the I18NInjector in a way, that it does not handle this Object case. Can you raise a dedicated ticket for it (referencing this testcase)? I don't know if reducing the priority is enough; also this would be a major change which is potentially affecting everyone already using this Injector.

**Comment by beo4** [comment]
@joerghoh 
reg 1.) With Object class i can handle String and String[] hand overs, thats why it is there.
reg 2.) https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2158

**Comment by joerghoh** [comment]
@beo4 Maybe you can use the ```@Source``` annotation in the meantime to fix the issue you face.
