### ISSUE TITLE
Multifield is not working as expected for three-level nested multifields

### ISSUE THREAD

**Issue by pankajrohira** [Adobe-Consulting-Services/acs-aem-commons#2159]
## Required Information

* AEM 6.5 SP3
* ACS AEM Commons Version: 4.3.2
* Reproducible on Latest? Yes

### Actual Behavior:

We recently upgraded AEM from 6.3 to 6.5 and part of the project was converting all dialogs from Classic UI to Touch UI. All multi-field components were storing the data as JSON in CRX, so we had to maintain the same in Touch UI as well.
We have several multi-field components in our project. Most of the components have two-level of nested multi-field where things are working as expected. We are storing data as JSON format and while opening the dialog (Touch UI), values are appearing as expected. One of the dialog (page properties) has three-level of nested multi-field. When we open the dialog, it shows values till 2nd level; we don't even see fields for 3rd level in dialog; although code had those. Also, when we try to add values manually and save the dialog, it doesn't store the values properly; it messes up the JSON structure.

When we looked at the file: /apps/acs-commons/touchui-widgets/composite-multifield/source/touchui-composite-multifield.js, it feels function "fillNestedFields" is being called only once rather it should be iterative (recursive) so that it can capture the third-level data as well.

Dialog structure:
attaching file dialog_structure.xml.zip

[dialog_structure.xml.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/4053525/dialog_structure.xml.zip)

# Steps to reproduce:
1. Install ACS AEM Commons 4.3.2 on AEM 6.5.3.0.
2. Create a three-level nested multi-field dialog
3. Try to save the value and then retrieve it.

**Comment by badvision** [comment]
When you upgraded you missed the step where you stop using the custom multifield and start using the product's multifield.  We are trying to ween you folks off of it so we can focus our attention on far more useful and exciting features.  The product has multifield already in it, please use that version of the multifield widget.
