### ISSUE TITLE
Provide Contextual PathField and PageField in addition to Contextual PathBrowser

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#2160]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3
* [x] ACS AEM Commons Version: 4.40
* [x] Reproducible on Latest? yes

### Expected Behavior

Since the `pathbrowser` is deprecated since AEM 6.3 (https://helpx.adobe.com/experience-manager/6-3/release-notes/deprecated-removed-features.html) instead a contextual variant of the replacement, the `pathfield` should be provided. Also the derived components in `/libs/cq/gui/components/coral/common/form/pagefield` should have a contextual variant.

### Actual Behavior

Only a Contextual variant of the legacy pathbrowser is being provided in https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/master/ui.apps/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/contextualpathbrowser. It should be pretty straightforward to provide a variant for the `pathfield` and `pagefield` in addition.

**Comment by kwin** [comment]
Maybe instead of providing custom variants for all those resource types there can be a more generic version which leverages the [ExpressionCustomizer](https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/reference-materials/javadoc/com/adobe/granite/ui/components/ExpressionCustomizer.html) to provide the contextual root path via EL.

**Comment by HitmanInWis** [comment]
@kwin has the new usage pattern been documented?   Would it be worth updating docs at https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/contextual-pathfield-browser/index.html ?

**Comment by kwin** [comment]
@HitmanInWis Tracked the documentation update now in https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/issues/189.
