### ISSUE TITLE
Error Page Handler - Character Encoding

### ISSUE THREAD

**Issue by jzelinski** [Adobe-Consulting-Services/acs-aem-commons#2163]
## Required Information

* [**AEM 6.3.3.0**] AEM Version, including Service Packs, Cumulative Fix Packs, etc
* [**4.3.4**] ACS AEM Commons Version
* [**Yes**] Reproducible on Latest?

### Expected Behavior

Error page that is returned should display correctly in any language (English, Chinese, Japanese, Portuguese, or Spanish). 

ACS Commons 3.17.4

English Error Page (404):
![image](https://user-images.githubusercontent.com/39139010/72463587-922e6d80-37a1-11ea-9add-62463025400d.png)

Chinese Error Page (404):
![image](https://user-images.githubusercontent.com/39139010/72463713-de79ad80-37a1-11ea-9fb3-b075bf37461f.png)

### Actual Behavior

The same pages that were working with ACS Commons 3.17.4 in the screenshots above no longer are displayed properly:

English Error Page (404):
![image](https://user-images.githubusercontent.com/39139010/72463894-44fecb80-37a2-11ea-9ea1-7b73449c5263.png)

Chinese Error Page (404):
![image](https://user-images.githubusercontent.com/39139010/72464116-b179ca80-37a2-11ea-89a3-e8c3262e2e55.png)

**Comment by joerghoh** [comment]
seems identical to #1010

**Comment by joerghoh** [comment]
@jzelinski Can you please the encoding of the response which does show with this incorrect encoding?

**Comment by jzelinski** [comment]
@joerghoh 

Incorrect encoding:
![image](https://user-images.githubusercontent.com/39139010/72735829-97f1cd80-3b6a-11ea-8841-2f6aae6e7dd3.png)


Correct encoding:
![image](https://user-images.githubusercontent.com/39139010/72735789-83add080-3b6a-11ea-9bb1-9d67ea63081a.png)

**Comment by joerghoh** [comment]
@jzelinski thanks, that was I wanted to ensure.

**Comment by joerghoh** [comment]
@jzelinski: to validate my assumption, can you add this statement to ``/apps/acs-commons/components/utilities/errorpagehandler/default.jsp`` after line 44:

``
slingResponse.setCharacterEncoding("UTF-8");
``

(right after the statement which sets the status)
and then try again?

**Comment by jzelinski** [comment]
@joerghoh Unfortunately, after adding that I am still getting the same results.

**Comment by joerghoh** [comment]
@jzelinski ok.

Can you validate that the code where you added this statement is actually executed in your case? Adding a log statement or something like that.

**Comment by jzelinski** [comment]
@joerghoh 

Sorry for the delay here, but I added a log statement to that file and I don't see it being logged.

**Comment by jzelinski** [comment]
Any other ideas of a quick fix that could made? We are working on a upgrade project to AEM 6.5 and it would be nice not having to change the error page structure to workaround the character encoding.

**Comment by joerghoh** [comment]
@jzelinski Sorry for the delay.

I was just looking again at the issue. Can you try the following:

* Restart the ACS AEM Commons Bundle
* send a request which triggers an error page
* Check the encoding of the response
* send a second request and check the encoding again.

A working theory is that it has something to do with the caching of the error pages. And that the first request gets proper headers, but on any cache hit from the cache (starting from the second request) the proper encoding is not attached to the response.
