### ISSUE TITLE
ResourceResolverMapTransformer decoding lead to wrong URLs

### ISSUE THREAD

**Issue by sblano4ka** [Adobe-Consulting-Services/acs-aem-commons#2165]
## Required Information

* [ ] Adobe Experience Manager, Version 6.3.3.5 
* [ ] ACS AEM Commons Version: 4.1.0
* [ ] Reproducible on Latest? yes/no

### Expected Behavior

_When I open a link  that was previously encoded on purpose and that was rewritten by ResourceResolverMapTransformer, I open encoded link and link is correctly mapped and i get correct escaped '&' further handling_

### Actual Behavior

_When I open a link  that was previously encoded on purpose and that was rewritten by ResourceResolverMapTransformer, link is correctly mapped but not encoded anymore and tracked incorrectly cause value "&" is considered to be a query param separator._

### Steps to Reproduce

-  Setup ResourceResolverMapTransformer to rewrite a:href.
-  In sightly remplate add next lines
`<sly data-sly-use.model="com.my.model.Tags">
    <a href="${'{0}.html?tagId={1}' @ format=[currentPage.parent.path, model.tag]}"/>
</sly>`
-  add com.my.model.Tags :
`@Model(adaptables = SlingHttpServletRequest.class)
public class Tags {
    public String getTag() throws UnsupportedEncodingException {
        return URLEncoder.encode("technologie-&-innovationen", StandardCharsets.UTF_8.name());
    }
}`

### Links

In version 3.9.0 this case works fine,
After we upgrade ACS Commons version to  4.1.0 issue is reproduced.
The reason: adding decode functionality in ResourceResolverMapTransformer introduced after 
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1492 and https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1464
According to the description, resourseResolver.map() has to encode link back. But it doesn't happened, cause it seems to encode only spaces

**Comment by sblano4ka** [comment]
Initial issue is resolved.
We incorrectly use ResourceResolverMapTransformer for making short urls for all a:href. 
It was done because linkchecker didn't work for us cause extension to a:href was added by custom Transformer after linkchecker. When order of linkchecker and custom transformer was changed, issue with long lnks was resolved so no more need to  use ResourceResolverMapTransformer.

But please take into account that there is still a case when on purpose encoded query parameters will be decoded by ResourceResolverMapTransformer.

**Comment by davidjgonzalez** [comment]
@sblano4ka thanks for the update.

Do we need to encode the transformed value? [1]

[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/ResourceResolverMapTransformerFactory.java#L106

**Comment by sblano4ka** [comment]
@davidjgonzalez 
I see that resourceResolver.map() is expected to do encoding. 
I don't know how it is implemented and what kind of encoding it supports, but I have no encoded values in transformed values.
I wrote some tests, where it can be seen that '&' char is not changed after the mapping
See https://github.com/sblano4ka/aem_tests/blob/master/src/test/java/com/sblano4ka/ResourceResolverMapTest.java 
ResourceResolverMapTransformerFactory can still decode value but maybe query parameters should be ignored in this case

**Comment by henrykuijpers** [comment]
This definitely needs a fix... 

We correctly have the following URL in the `href` attribute:
```
<a href="/content/something/something-else/nl/x.y.2.html?q=%22Search%22">Page 2</a>
```
In the transformer it gets decoded to:
```
/content/something/something-else/nl/x.y.2.html?q="Search"
```
It gets passed to `resourceResolver#map`, which does not encode it again, so the result is:
```
/x.y.2.html?q="Search"
```

So, the end result is:
```
<a href="/x.y.2.html?q="Search"">Page 2</a>
```
This breaks out of the HTML attribute and makes the unencoded part suddenly able to form real HTML outside the attribute value!

And, since this happens in a Transformer, it means that we are already past the processing where we would apply `xss:getValidHref` or similar.

**Comment by henrykuijpers** [comment]
Yes, this allows one to break out of an href-attribute and do some bad stuff:
```
<c:set var="linkHack" value="/content/something.html?q=<%= URLEncoder.encode("\"><script type=\"text/javascript\">alert(\"Evil\");</script>", StandardCharsets.UTF_8) %>"/>
<p>Hack: <a href="${xss:getValidHref(linkHack)}">Link hack</a></p>
```
When using this *without* ACS AEM Commons ResourceResolverMapTransformerFactory (set to `a:href`), this would present a link just fine (though it's not externalized/mapped).

But, when using this *with* ACS AEM Commons ResourceResolverMapTransformerFactory (set to `a:href`), this would show an alert popup with text "Evil" when visiting the page.
