### ISSUE TITLE
Poll: increase minimal version to AEM 6.4

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#2167]
This is an informal poll about dropping support for AEM 6.3 (all servicepacks/cfps) and older version. We have a number of changes (mostly related to the repo restructuring in AEM 6.4), which are currently blocked by the necessity to support AEM 6.3 as well.

I found these related issue.
* #1909 and #1975 
* #2029 could be closed
* #1408 

(and probably much more)

WDYT?

**Comment by royteeuwen** [comment]
+1, seeing as Adobe announced it will not release AEM 6.6 this year there is no reason to wait for any of that kind of announcement.

**Comment by davidjgonzalez** [comment]
+1 ... 6.3 is pretty old now. We can always back-port fixes and cut emergency releasees that are 6.3 compat if warranted.

**Comment by joerghoh** [comment]
I created an initial PR to review the amount of changes: #2180

**Comment by badvision** [comment]
Once we update our uber jar dependency I can introduce content fragment importers that I wrote a long time ago, which unfortunately don't work with 6.3 because there was an API change that is required to support that.

**Comment by joerghoh** [comment]
how should we proceed? Do we plan to release a version 5.0 and drop support for 6.3 then?

**Comment by davidjgonzalez** [comment]
@joerghoh yup - 5.x 

Should we make a GH Issue for 5.x release and make a list of what we want to do in the 5.x release (ie. any other breaking changes, etc.)

**Comment by davidjgonzalez** [comment]
@joerghoh care to take a stab at filling out: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2288 ?

**Comment by davidjgonzalez** [comment]
Closing in lieu of #2288
