### ISSUE TITLE
Generic List - backward compatibility broken: no "Localization" section in dialog

### ISSUE THREAD

**Issue by dbuhrymau** [Adobe-Consulting-Services/acs-aem-commons#2168]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.2
* [ ] ACS AEM Commons Version: 4.4.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

When generic list dialog is open "Localization" section with the localized titles is present (as it was in Classic UI)

Classic UI example:
![localized-titles-classic-ui](https://user-images.githubusercontent.com/2054873/72681856-ae4f4900-3ad8-11ea-85d5-94413bb44c6f.png)

### Actual Behavior

When generic list dialog is open the whole "Localization" section with the localized title fields is missing

![no-localization-section](https://user-images.githubusercontent.com/2054873/72681916-3f262480-3ad9-11ea-86ba-8e32d4ab17dc.png)

What makes things worse, there's no way to fallback to Classic UI anymore. Any generic list opened for editing directly in the old manner (using classic UI), shows just a completely white page. For example:
/cf#/etc/acs-commons/lists/font-awesome-icons.html
or
/editor.html/etc/acs-commons/lists/font-awesome-icons.html

Looks like crx/de now the only way to deal with localized titles

### Steps to Reproduce

1. Go to Generic Lists console: /generic-lists.html/etc/acs-commons/lists
2. Select any existing generic list(or create a new one) and press "Properties"
3. See a dialog without the "Localization" section

**Comment by asonirina** [comment]
This issue impacts our project since we have many components that rely on localized generic lists.
It would be good have it on touch UI or at least to retain the exiting Classic UI

**Comment by hsompalli16** [comment]
We are facing the same issue, as in classic UI we had option to support localization for generic list but in AEM 6.5 we don't have localization option to edit or add new fields. Could you please do the needful.

**Comment by marcschiely** [comment]
@badvision @davidjgonzalez are there plans to bring back the localization feature for the generic lists? We currently edit the localized titles via CRXDE as the TouchUI does not support this anymore.
