### ISSUE TITLE
IconPicker not working as expected in touchUI multifield

### ISSUE THREAD

**Issue by saikrishnaaemdev** [Adobe-Consulting-Services/acs-aem-commons#2173]
AEM 6.5.2
ACS Commons 4.3.2

The icon picker is working as expected outside of multi field;
In a multi field when you select the "no icon" option it is actually working as expected, but when you re-open the configuration dialog again and select the ok button(without any changes to the icon picker), it is by default taking some random icon and loading it.

This is happening only when "no icon" option is selected in the touch UI Multi field.

**Comment by filipapo** [comment]
The issue is caused by the ordering of the list items. The empty option should be the first one in the list. The icon picker takes the first item as selected when no icon has been previously selected
