### ISSUE TITLE
SMTPMailServiceHealthCheck does not greedily bind MessageGateway

### ISSUE THREAD

**Issue by bjoernweide** [Adobe-Consulting-Services/acs-aem-commons#2182]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5.3
* [x] ACS AEM Commons Version: 4.3.4
* [x] Reproducible on Latest? yes

### Expected Behavior

When the CQ Mail Service (containing the MessageGatewayService) becomes active AFTER the ACS bundle containing the SMTPMailServiceHealthCheck the HealthCheck should be able to use the MessageGatewayService and execute.

### Actual Behavior

The SMTPMailServiceHealthCheck does not find the MessageGatewayService if its not available during startup of the component.

### Steps to Reproduce

This can be manually reproduced with AEM 6.5.3+ACS Commons 4.3.4+, given the both CQ Mail Service and SMTPMailServiceHealthCheck are properly configured:
Via OSGi console
- Stop com.day.cq.cq-mailer
- Stop com.adobe.acs.acs-aem-commons-bundle
- Start com.adobe.acs.acs-aem-commons-bundle
- Start com.day.cq.cq-mailer
- Execute the SMTPMailServiceHealthCheck

The HC will fail with "MessageGatewayService OSGi service could not be found." even though the MessageGatewayService would be actually available. 

### Links
n/a

**Comment by kwin** [comment]
@bjoernweide Can you create a PR with a fix (by making reference https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/4b3da3f5fdf0b59049b966bea9306d24c87d0293/bundle/src/main/java/com/adobe/acs/commons/hc/impl/SMTPMailServiceHealthCheck.java#L91 greedy?)

**Comment by bjoernweide** [comment]
Sure I will create one soon.
