### ISSUE TITLE
ctrl+shift+s shortcut is not working after installation of CFP7

### ISSUE THREAD

**Issue by jbrarAdobe** [Adobe-Consulting-Services/acs-aem-commons#2184]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3.3.7
* [ ] ACS AEM Commons Version:3.*
* [ ] Reproducible on Latest? yes

### Expected Behavior

ctrl+shift+s shortcut should open the side panel

### Actual Behavior

ctrl+shift+s shortcut is not working

### Steps to Reproduce

1. Open any dialog where image drag-and-drop feature is available and image is mandatory field.
2. Ensure that side panel is not open.
3. Author all the fields in the dialog, except the image.
4. Now try to open the side panel using "ctrl+shift+s" and notice it does not open.

### Links

https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-hotkeys/index.html

**Comment by ahmedriyaz** [comment]
This is not working in any of the new ACS Commons versions. I am using 4.4.0 in AEM6.5

**Comment by riyazmra** [comment]
Hi,
It seems it is closed without resolution. Do we have any resolution? This is really good feature. Please suggest the solution.
