### ISSUE TITLE
Transitive dependencies on Jackrabbit Oak

### ISSUE THREAD

**Issue by reschke** [Adobe-Consulting-Services/acs-aem-commons#2187]
The project directly uses certain Oak APIs, but does not itself declare these dependencies; these are all transitive dependencies via oakpal.

This has several problems:

- updating oakpal might break the build if transitive dependencies change
- no control about what version of Oak is used

In particular: oak-core-spi will have an incompatible API change as of Oak 1.26.0 (https://issues.apache.org/jira/browse/OAK-7358). Acs-aem-commons will not work with that Oak version, unless the import range for org.apache.jackrabbit.oak.spi.security.principal is relaxed to allow version 2.0.0 (or the whole project is updated to build against Oak 1.26.0).

**Comment by joerghoh** [comment]
Hi @reschke 

I have to admit that I am not very deep into the details of dependency management (others definitely have moreknowledge here), but I don't see any direct dependency to Oak API in the ```bundle``` module, also no dependency to oakpal. 
Only the ```oakpal-checks``` module is affected, and from what I see the dependency is set to ```oak-core``` in version ```1.18``` for the ```oakpal-core-1.5.1``` code. Thus I don't see why the changes of Oak 1.26 will affect acs-aem-commons right now.

**Comment by reschke** [comment]
If you look at the bunde's manifest, you'll see this import:

~~~
org.apache.jackrabbit.oak.spi.security.principal;version="[1.4,2)"
~~~

**Comment by adamcin** [comment]
I'll try to dive into this issue over the next week to plan around the changes in 1.26.

**Comment by joerghoh** [comment]
@reschke Ah, good point. Just checked the POM and found no direct reference.

**Comment by joerghoh** [comment]
Removed the direct dependencies to OAK in the codebase; if @adamcin removes the export in oakpal, it's not possible to use it by accident.

**Comment by reschke** [comment]
...see https://github.com/adamcin/oakpal/issues/47
