### ISSUE TITLE
Enhancement Request: Export Sitemaps Servlet Code to It's own consumable service 

### ISSUE THREAD

**Issue by ahmed-musallam** [Adobe-Consulting-Services/acs-aem-commons#2189]
_Putting this request here for discussion and in case anyone wants to do this work. This is a great first contribution for anyone looking to contribute to ACS commons._

As you know the [Sitemap Generator Feature](https://adobe-consulting-services.github.io/acs-aem-commons/features/sitemap/index.html) works great! it's a servlet that serves up formatted Sitemap XML. However, its use is limited to the exported XML format.

I propose moving all that logic inside [SiteMapServlet.java](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/94c9afd291dba26a0f36f6cd1b5619ef49b6d6cf/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/SiteMapServlet.java) to a Service _`SiteMapService`_ that returns a list of URLs. This should not change the way the servlet is currently used or configured. It just means that consumers of ACS commons _(devs)_ can consume this service in their applications and use the output links however they want and export it to any format they want.

Discussion?

**Comment by joerghoh** [comment]
@ahmed-musallam are you already on it? Can you propose a service interface?

**Comment by ahmed-musallam** [comment]
@joerghoh I have not started on it yet, have a few things going on at this time but will eventually get to it..

**If/when I start on it, will be sure to add a comment here** 

I thought I’d create this issue as to not forget and in case someone wants to take a shot at it 😊
