### ISSUE TITLE
Error Handler documentation should be updated with regards to the I18NFilter

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Consulting-Services/acs-aem-commons#2203]
https://adobe-consulting-services.github.io/acs-aem-commons/features/error-handler/index.html

This documentation mentions that, in order to have I18n support on the error pages, the I18nFilter configuration needs to be updated to include ERROR as well. However, at least on AEM 6.5.3, this is by default the case (org.apache.sling.i18n 2.5.14).

**Comment by kwin** [comment]
This was fixed in the context of https://issues.apache.org/jira/browse/SLING-2705. @henrykuijpers Would you be able to come up with a documentation PR for the error-handler?
