### ISSUE TITLE
History-based test prioritization

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#2210]
### Expected Behavior

As an impatient developer, I would like if the junit tests executed in an order where the most recently-defined or recently-failed tests ran first -- that way I can quickly see if my tests pass or fail without having to wait on the rest of the test suite to complete.  I can control this locally by executing my own test by itself using IDE features to do that, but when pushing a feature branch, I don't have the same ability e.g. in Travis CI at this point in time.

### Actual Behavior

Tests run in a default JUnit order, most times new tests occur at an unspecified time.  There are studies that show re-testing effort can be up to 90% more efficient by switching to a history-based order.

**Comment by joerghoh** [comment]
The only option I see is to change the default of the runOrder of surefire [1], and use ```-Dsurefire.runOrder=failedfirst``` as parameter to your local maven build.
Do you have something different in mind?

[1] https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#runOrder

**Comment by badvision** [comment]
That sounds good to me but I was hoping for something that would work in Travis as well.

**Comment by justinedelson** [comment]
It should be possible to get this to work in travis. Something like this:

1. In the `before_cache` section, copy the `.surefire-XXXXXXXXX` file(s) to some other directory
2. Add that directory as a `cache` entry
3. In the `before_script` stage, copy those files (if they exist) out of the other directory.
