### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by wimsymons** [Adobe-Consulting-Services/acs-aem-commons#2214]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.4.0
* [ ] ACS AEM Commons Version: 4.4.0
* [ ] Reproducible on Latest? yes
* [ ] Java version: 1.8.0_144

### Expected Behavior

Use of https://adobe-consulting-services.github.io/acs-aem-commons/features/adobe-io-apis/index.html should function properly.

### Actual Behavior

This is logged every hour:

```
03.03.2020 12:00:00.027 *ERROR* [sling-default-1-com.adobe.acs.commons.adobeio.service.impl.IntegrationServiceImpl.323408] org.apache.sling.commons.scheduler.imp
l.QuartzScheduler Exception during job execution of job 'com.adobe.acs.commons.adobeio.service.impl.IntegrationServiceImpl@2132ecca' with name 'com.adobe.acs.com
mons.adobeio.service.impl.IntegrationServiceImpl.323408' : javax/xml/bind/DatatypeConverter
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at acscommons.io.jsonwebtoken.impl.Base64Codec.encode(Base64Codec.java:21)
        at acscommons.io.jsonwebtoken.impl.Base64UrlCodec.encode(Base64UrlCodec.java:22)
        at acscommons.io.jsonwebtoken.impl.DefaultJwtBuilder.base64UrlEncode(DefaultJwtBuilder.java:349)
        at acscommons.io.jsonwebtoken.impl.DefaultJwtBuilder.compact(DefaultJwtBuilder.java:295)
        at com.adobe.acs.commons.adobeio.service.impl.IntegrationServiceImpl.getJwtToken(IntegrationServiceImpl.java:158)
        at com.adobe.acs.commons.adobeio.service.impl.IntegrationServiceImpl.fetchAccessToken(IntegrationServiceImpl.java:123)
        at com.adobe.acs.commons.adobeio.service.impl.IntegrationServiceImpl.run(IntegrationServiceImpl.java:89)
        at org.apache.sling.commons.scheduler.impl.QuartzJobExecutor.execute(QuartzJobExecutor.java:347)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Steps to Reproduce

Just create any ACS AEM Commons - Adobe I/O Integration Configuration as defined in https://adobe-consulting-services.github.io/acs-aem-commons/features/adobe-io-apis/index.html.

### Further details

Exports by the Apache Felix System Bundle (related to this issue):

javax.xml.bind,version=2.1.0
javax.xml.bind.annotation,version=2.1.0
javax.xml.bind.annotation.adapters,version=2.1.0
javax.xml.bind.attachment,version=2.1.0
javax.xml.bind.helpers,version=2.1.0
javax.xml.bind.util,version=2.1.0

Imports by com.adobe.acs.acs-aem-commons-bundle (related to this issue):

javax.xml.bind; version="[2.2, 3)"; resolution:=optional

This was added in July 2019 for #1914 which fixes it on AEM 6.5, but this breaks it on AEM 6.4.
I guess it should be [2.1,3) and not optional.

**Comment by badvision** [comment]
Makes sense, but honestly javax.xml dependencies get trickier in Java 11 because they took a lot of those non-core modules out of the JRE distribution.

**Comment by wimsymons** [comment]
@badvision when can we expect the release of 4.4.4? Should I create a PR for this issue?

**Comment by joerghoh** [comment]
@wimsymons I am not @badvision but if you could contribute a PR it would be awesome.

**Comment by badvision** [comment]
I don't have any immediate plans to work on this but I definitely want to track this so we as a community don't forget this should be solved prior to the next release.  I think we fixed some release process breakage issues on the last one so if we get a PR and it's pressing just let us know and we can expedite the process a bit.

**Comment by wimsymons** [comment]
Great news! I'll submit a PR today!

**Comment by wimsymons** [comment]
@badvision @joerghoh I just sent my PR. If it's possible to cut a release sooner, we'd by very happy 👍

**Comment by wimsymons** [comment]
Hi @badvision, @joerghoh did you have any time yet to review my changes? 🙏

**Comment by wimsymons** [comment]
It's very silent here. Any status updates yet? Sorry about the nagging, but I want to have this fixed as soon as possible.

**Comment by davidjgonzalez** [comment]
🏏's

**Comment by wimsymons** [comment]
As AEM 6.3 is also in the compatibility table for ACS 4.x, should we widen the version range even more? I don't know what version of javax.xml.bind would be exported there and I no longer have access to an AEM 6.3 quickstart. Would you guys happen to know that?

**Comment by davidjgonzalez** [comment]
@wimsymon you are correct -  6.3 is still supported by ACS Commons (we'd need a major version bump to drop it). 

I don't have a 6.3 on my computer either (having laptop replacement issues this week).

Does it make sense to make it optional w/ the 6.4 -> 6.5 compat version range? 
If this feature was released with 6.4+ support, I don't think its a bit deal to keep it at that same level (and frankly, I haven't heard anyone complain about it). That said, if we can expand the range just as easily with no extra work, thats even better.

**Comment by wimsymons** [comment]
I found AEM 6.3 quickstart jar on Daycare portal. Downloading as we speak. I'll post the information as soon as I have it. If necessary, I'll update the PR.

**Comment by wimsymons** [comment]
From org.apache.felix.framework 5.6.0 from AEM 6.3.0.0:

javax.xml.bind,version=2.1.0
javax.xml.bind.annotation,version=2.1.0
javax.xml.bind.annotation.adapters,version=2.1.0
javax.xml.bind.attachment,version=2.1.0
javax.xml.bind.helpers,version=2.1.0
javax.xml.bind.util,version=2.1.0

So my patch will fix it for AEM 6.3 as well.

**Comment by wimsymons** [comment]
@davidjgonzalez @badvision now my change is approved and merged, do you have any concrete timings for the next release?

**Comment by davidjgonzalez** [comment]
@wimsymons I was hoping to get a fix in for https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2211 if possible and then cut a release... i'm a bit hamstrung right now, as my usual dev machine died :(

**Comment by wimsymons** [comment]
@davidjgonzalez any word yet? It seems very quiet on #2211, maybe you can cut a release and put #2211 on the next release? It's been 2 weeks now.

**Comment by davidjgonzalez** [comment]
@wimsymons 4.5.0 has been released; request to deploy to repo.adobe.com has been made.
