### ISSUE TITLE
NPE in Audio component due to XSSApi adapter no longer available

### ISSUE THREAD

**Issue by funkman** [Adobe-Consulting-Services/acs-aem-commons#2220]
## Required Information
* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.3
* [x] ACS AEM Commons Version: 4.3.0
* [x] Reproducible on Latest? yes

### Expected Behavior
Audio component `/apps/acs-commons/components/content/audio` is not rending the audio tag.

### Actual Behavior
NPE occurs and page doesn't load.

Root cause looks to be `/apps/acs-commons/components/content/audio/partials/analytics.jsp` where `XSSAPI slingXssAPI = slingRequest.adaptTo(XSSAPI.class);` is returning null. So when is passed to the taglib - an NPE occurs.

This behavior was also seen here with no sufficiently simple resolution https://experienceleaguecommunities.adobe.com/t5/Adobe-Experience-Manager/XssApi-is-null-6-5/qaq-p/324249

### Steps to Reproduce
Use AEM 6.5.3 and embed the audio component onto a page.

**Comment by kwin** [comment]
I cannot reproduce the issue with AEM 6.5.3. Also XSSAPI should be available on AEM 6.5.3 as well. You can check by accessing {{/system/console/components/com.adobe.granite.xss.impl.XSSAPIImpl}} whether the component is correctly started on your system and maybe also the reason why it isn't started.

**Comment by funkman** [comment]
I'll keep digging. One clarification - `/apps/acs-commons/components/content/audio/partials/analytics.jsp`  is using `<%@ page import="org.apache.sling.xss.XSSAPI" %>`. Not the granite version.

But I did go to 
`/system/console/components/org.apache.sling.xss.impl.XSSAPIImpl` and did confirm status was active.

I did update `partials/analytics.jsp` and added the null check and confirmed the ` slingRequest.adaptTo` is the part that's failing me.
    XSSAPI slingXssAPI = slingRequest.adaptTo(XSSAPI.class);
    pageContext.setAttribute("slingXssAPI", slingXssAPI);
    if (slingXssAPI==null) {
        throw new IllegalArgumentException("Why is slingXssAPI null?");
    }

My apps are currently deployed with the 6.4.X uber jar instead of the 6.5.3 uber jar. I'm hoping that is not the issue since I was hoping to upgrade without additionally performing a release at the same time.

**Comment by kwin** [comment]
Thanks for the additional info, indeed there is no adapter from SlingHttpServletRequest to org.apache.sling.xss.impl.XSSAPI.

**Comment by funkman** [comment]
Thanks for the quick fix! One question. Should the fix be :
`XSSAPI slingXssAPI = sling.getService(XSSAPI.class);`

I don't see a get() on the `SlingScriptHelper` interface. I updated my local copy of `partials/analytics.jsp` with 
```
    XSSAPI slingXssAPI = sling.get(XSSAPI.class);
```
And then I see the following in may error logs:

```
An error occurred at line: 29 in the jsp file: /apps/acs-commons/components/content/audio/partials/analytics.jsp
The method get(Class<XSSAPI>) is undefined for the type SlingScriptHelper
26: %><%@taglib prefix="audio" uri="http://www.adobe.com/consulting/acs-aem-commons/audio" %><%
27: %><%@taglib prefix="dam" uri="http://www.adobe.com/consulting/acs-aem-commons/dam" %><%
28: %><%@taglib prefix="xss" uri="http://www.adobe.com/consulting/acs-aem-commons/xss/2.0" %><%
29:     XSSAPI slingXssAPI = sling.get(XSSAPI.class);
30:     pageContext.setAttribute("slingXssAPI", slingXssAPI);
31: %>
32: <c:set var="resourcePath">${xss:encodeForJSString(slingXssAPI, resource.resourceType)}</c:set>

```

**Comment by kwin** [comment]
Indeed, good catch @funkman. Will come up with a follow-up PR in a second.
