### ISSUE TITLE
ACS Common Audio ICON img and style is not loading on Classic UI

### ISSUE THREAD

**Issue by suhashankare** [Adobe-Consulting-Services/acs-aem-commons#2221]
## Required Information

* [x] AEM 6.5 Version, including Service Packs, Cumulative Fix Packs, etc: 
* [x] ACS AEM Commons Version: 4.3.2
* [x] Reproducible on Latest? Yes

### Expected Behavior
On The classic UI Audio Icon is missing on left finder panel tabs 

### Actual Behavior

AUDIO Image and CSS are not loading on the Classic UI  **AEM 6.5.3** version 

ON 3.15.2 version  [ Works Fine ]
/apps/acs-commons/widgets/themes/default 
Node property was define as below 
categories | String | **cq.widgets**

ON 4.3.2 version [Not Wokring]
/apps/acs-commons/widgets/themes/default 
Node property name  as define below
categories | String | **acs-commons.classicui.content-finder.audio**

![image](https://user-images.githubusercontent.com/3133517/76621271-614e8880-6505-11ea-8810-9a7706903130.png)

![image](https://user-images.githubusercontent.com/3133517/76621249-509e1280-6505-11ea-9ab2-880b7a80aac5.png)

### Steps to Reproduce

AEM 6.5.3 Vanilla install ACS 4.3.2 with / Without your project build, 

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by kwin** [comment]
This is a deliberate change: https://adobe-consulting-services.github.io/acs-aem-commons/pages/releases/4-0-0.html#breaking-functional-changes

**Comment by davidjgonzalez** [comment]
@suhashankare Closing per @kwin , but if you have confusion on how to problems figuring out the proxy, let us know in a comment (hopefully the docs make sense though!)
