### ISSUE TITLE
Missing Thumbnails in Assetshare Home page for zip assets

### ISSUE THREAD

**Issue by Chethan-Nataraju** [Adobe-Consulting-Services/acs-aem-commons#2227]
Hi Team,

We have noticed that for the zip assets the thumbnails are being generated in author and in Assetshare details page but are not available in Assetshare homepage. Request you to please provide your inputs on the same. 

Regards,
Chethan

**Comment by davidjgonzalez** [comment]
@Chethan-Nataraju hi - can you explain how ACS AEM Commons might effect this? Are you sure this isn't an AEM issue that is better taken up w/ Adobe Support or in the Adobe AEM Forums?

**Comment by davidjgonzalez** [comment]
Closing as this does not appear to be ACS Commons related.
