### ISSUE TITLE
ReplicatedByWorkflowProcess step on workflow not setting who replicating

### ISSUE THREAD

**Issue by ragavan208** [Adobe-Consulting-Services/acs-aem-commons#2231]
## Required Information

* [x ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.4 (6.4 + service pack 6.4.4)
* [ x] ACS AEM Commons Version: _4.1.0____
* [x ] Reproducible on Latest? yes

**ISSUE:**

When we delegate to custom workflow from "Request for activation" by using the delegation process step. Then on the custom workflow at the end adding the process step
"Set Replicated By Property to Workflow Initiator" , it is not setting the actual user who raised the request for activation workflow it and it is setting as "workflow-process-service"'

**Comment by davidjgonzalez** [comment]
@ragavan208 is your Workflow Model transient? if so, transient workflow doesnt have access to this info (unless this was changed at some point)

**Comment by ragavan208** [comment]
my "Request for activation" & custom workflow which is delegated from "Request for acctivation" also **not transient.**

**Comment by ragavan208** [comment]
Is there any updates?
