### ISSUE TITLE
 ACS bundles and functionality

### ISSUE THREAD

**Issue by sapirshelli** [Adobe-Consulting-Services/acs-aem-commons#2244]
hi guys,

we are facing this issue once doing login/ logout 
AEM 6

23.03.2020 08:09:03.161 *ERROR* [FelixStartLevel] com.adobe.granite.repository.impl.SlingRepositoryImpl Bundle com.adobe.acs.acs-aem-commons-bundle is NOT whitelisted to use SlingRepository.loginAdministrativeorg.apache.sling.api.resource.LoginException: Bundle com.adobe.acs.acs-aem-commons-bundle is NOT whitelisted	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrProviderStateFactory.getLoginException(JcrProviderStateFactory.java:203) | 23.03.2020 08:09:03.161 *ERROR* [FelixStartLevel] com.adobe.granite.repository.impl.SlingRepositoryImpl Bundle com.adobe.acs.acs-aem-commons-bundle is NOT whitelisted to use SlingRepository.loginAdministrativeorg.apache.sling.api.resource.LoginException: Bundle com.adobe.acs.acs-aem-commons-bundle is NOT whitelisted	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrProviderStateFactory.getLoginException(JcrProviderStateFactory.java:203)
-- | --
23.03.2020 08:09:03.161 *ERROR* [FelixStartLevel] com.adobe.granite.repository.impl.SlingRepositoryImpl Bundle com.adobe.acs.acs-aem-commons-bundle is NOT whitelisted to use SlingRepository.loginAdministrativeorg.apache.sling.api.resource.LoginException: Bundle com.adobe.acs.acs-aem-commons-bundle is NOT whitelisted	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrProviderStateFactory.getLoginException(JcrProviderStateFactory.java:203)

can u please advise how to fix it?

regards,
Sapir

**Comment by joerghoh** [comment]
you have to install the complete content-package of ACS AEM Commons (as available on download page or via Maven) and not only the bundle.
