### ISSUE TITLE
Error description message in Marketo plugin

### ISSUE THREAD

**Issue by DavidAtWorking** [Adobe-Consulting-Services/acs-aem-commons#2245]
I notice that the description message in Marketo configuration shows an example with "https"
However the backend code also append a https to the front.

![image](https://user-images.githubusercontent.com/42355997/78065760-bd1c6c80-7361-11ea-9846-d7bea108c130.png)

![image](https://user-images.githubusercontent.com/42355997/78065910-066cbc00-7362-11ea-9e58-250a11f4fa3a.png)

**Comment by klcodanr** [comment]
Thanks @DavidAtWorking! I'll fix this one up quick unless you have a PR ready :-D
