### ISSUE TITLE
PROD Authoring Issues with Multi-field component with rich text and ACS generic list pages

### ISSUE THREAD

**Issue by ssridharcsegit** [Adobe-Consulting-Services/acs-aem-commons#2251]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______**AEM 6.5.2**
* [ ] ACS AEM Commons Version: _____**ACS AEM Commons Version 4.3.2/4.4.0**
* [ ] Reproducible on Latest? yes/no **Yes**

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

**This issue occurs in upgraded AEM production servers (upgraded last month from AEM 6.2 to AEM 6.5.2 - Inplace Upgrade) with ACS commons 4.3.2 package installed.
Also tried with 4.4.0 ACS Commons package, still the same issue. please check and resolve the same ASAP. Thanks!
The issue is with PROD Author when rich text value in the multi-field (ACS composite multi-field) was not getting saved.

So we have tried installing ACS commons 4.4.0 package which resolved the multi-field issue but after installing ACS commons 4.4.0 we have noticed a new issue which is related ACS generic list page component

Pages under /etc/acs-commons/lists folder created using Generic List templates are not opening up
but these pages were working with ACS Commons 4.3.2

As per our analysis we noticed ACS 4.4.0 the generic list OOB page component - /apps/acs-commons/components/utilities/genericlist has no proper properties configured or execution script is not available

We need both multi-field with rich text and generic list pages to be in working state.

Could you let us know if you have any hotfix for these issues ?**

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

When we tried with AEM 6.5.2 - genericList component (acs commons 4.4.0) in vanilla AEM instance, we couldn't find find the respective sling:resourceSuperType property. Can you please check if this can be resolved ?
### Links

_Links to related assets, e.g. content packages containing test components_

https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases - Please check.

**Comment by shadaflorida** [comment]
I had the same issue with 4.5.0! Trying 4.3.2 fixed it!

**Comment by AndreiShilov** [comment]
@ssridharcsegit I have tried to reproduce your issue on a fresh instance and everything works fine for me.

Could you share a StackTrace for 
`Pages under /etc/acs-commons/lists folder created using Generic List templates are not opening up
but these pages were working with ACS Commons 4.3.2`

And how do you install the new version? Could you share you maven config with dependencies section?
