### ISSUE TITLE
Release 4.5.2 not available on Adobe Public Maven repository

### ISSUE THREAD

**Issue by wimsymons** [Adobe-Consulting-Services/acs-aem-commons#2272]
The newly released 4.5.2 version is not yet available on the Adobe Public Maven repository, while it is already released for 3 days on Github.

https://repo.adobe.com/nexus/content/groups/public/com/adobe/acs/acs-aem-commons-content/ still reports 4.5.0.

Is this not part of the release process?
When can we expect it to appear there?

**Comment by davidjgonzalez** [comment]
@wimsymons  I just bumped the internal ticket for Adobe Eng to push the release repo.adobe.
Hopefully soon.... 🤞

**Comment by wimsymons** [comment]
Still nothing. Is it usual this takes so long?

**Comment by wimsymons** [comment]
Just found out that https://bintray.com/acs/releases/acs-aem-commons *is* up-to-date. I'll switch to using that repository instead.

**Comment by wimsymons** [comment]
Closed for me than...

**Comment by davidjgonzalez** [comment]
FYI - its now on repo.adobe.com
