### ISSUE TITLE
could  able to configure Marketo form

### ISSUE THREAD

**Issue by Risha18** [Adobe-Consulting-Services/acs-aem-commons#2275]
## Required Information
Installing the Marketo Form Embed AEM Component
aem 6.5 no service pack
acs-aem-commons-ui.content-4.5.2 
acs-aem-commons-ui.apps-4.5.2

### Expected Behavior

After installation should be able to get cloud configuration window 

### Actual Behavior

not getting  configuration window  after giving configuration name, screenshot attached

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by klcodanr** [comment]
Strange @Risha18 You mentioned a screenshot can you please attached? Do you have any logs?

**Comment by davidjgonzalez** [comment]
@Risha18 are you still having this problem? if so, can you provide the screenshot that @klcodanr requested? thanks!!

**Comment by Risha18** [comment]
thank you for your response ,
please advise which log you want, i am using my local instance

Regards,
Ritesh

**Comment by Risha18** [comment]
Please advise , if possible to share instructions

Regards,
Risha

**Comment by klcodanr** [comment]
@Risha18 Sorry for the delay!

So a screenshot of the issue would be helpful as well as attaching your error.log and _ideally_ a log at trace level for the package `com.adobe.acs.commons.marketo`

**Comment by Risha18** [comment]
thank you Dan for following up.
now it is working getting configuration window. I did clean and
reinstall AEM instance n ACS package and it is started working not getting
any error. Also i checked log folder and did not find any log for
com.adobe.acs.commons.marketo.
Questions
- Is it because i am using local instance ?
- what are the additional steps needed at configuration level if i am using
local instance

Regards,
Ritesh

**Comment by klcodanr** [comment]
Ritesh,

Looking at the code it looks like most of the logging occurs when the component is used. 

Is it now working correctly for you now?

**Comment by Risha18** [comment]
thank you yes it working . Doing configuration on local instance will let
you know if any issues

**Comment by Risha18** [comment]
Hello Dan,

followed configuration instruction as per link
https://adobe-consulting-services.github.io/acs-aem-commons/features/marketo-form/index.html
however not working not getting test component at template property
configuration

thanks
RItesh

**Comment by Risha18** [comment]
Hello Dan,

please advise on my question.

thanks,
Ritesh

**Comment by klcodanr** [comment]
Sorry @Risha18 I don't understand your question. Could you provide a screenshot / steps to reproduce?
