### ISSUE TITLE
Dropdowns in MCP forms not working

### ISSUE THREAD

**Issue by jordyelst** [Adobe-Consulting-Services/acs-aem-commons#2277]
## Required Information

* AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM as a Cloud Service Release 2020.4.3084.20200428T023039Z
* ACS AEM Commons Version: 4.5.0
* Reproducible on Latest? unknown

![image](https://user-images.githubusercontent.com/45876368/80489097-a4eb3d80-895f-11ea-87d5-d8fddebe2c55.png)

### Expected Behavior
Dropdown fields within the MCP form should expand upon being clicked.

### Actual Behavior
Dropdown fields within the MCP form do not expand upon being clicked.

### Steps to Reproduce
* Go to Tools > ACS AEM Commons > Manage Controlled Processes.
* Click "Start Process" in the top-right corner.
* Select a process that has a [dropdown](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/593af743a50ddfec3ded43825481484d4ed63c9d/bundle/src/main/java/com/adobe/acs/commons/mcp/form/SelectComponent.java) in the form (e.g. "Asset Folder Creator").
* Try to expand the dropdown.

### Links
Relevant Java-class for dropdown component: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/593af743a50ddfec3ded43825481484d4ed63c9d/bundle/src/main/java/com/adobe/acs/commons/mcp/form/SelectComponent.java

**Comment by MANID048** [comment]
It is not working now also
