### ISSUE TITLE
Indesign Deck Dynamo: insecure XML processing

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#2280]
A sonar check points out that the XML processing in the new Indesign Deck Dynamo feature is not secured against XXE (XML external entity) processing.

Affected classes:
* XMLGeneratorServiceImpl
* DynamicDeckBackTrackProcess

Will propose a PR for it.

**Comment by davidjgonzalez** [comment]
Release in 4.7.0
