### ISSUE TITLE
Report Builder pagination buttons break when Search Parameters are missing

### ISSUE THREAD

**Issue by ericvangeem** [Adobe-Consulting-Services/acs-aem-commons#2286]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.8.0
* [x] ACS AEM Commons Version: 4.6.0
* [x] Reproducible on Latest? yes

### Expected Behavior

Pagination buttons within the Report Builder tool should advance to the next page of results when clicked.

### Actual Behavior

When using the pagination feature on a report that contains _no search parameters/query parameters_, the pagination buttons do not advance pages and remain on the first page.

This happens because when there are no search parameters, an invalid URL query string is formed on the front end by appending two ampersands (e.g. `&&`) together when attempting to add the `page=1` query param. 

The request to fetch the next page thus results in the following invalid query string: http://localhost:4502/var/acs-commons/reports/test/_jcr_content.results.html?wcmmode=disabled&&page=1

This interferes with the back end pagination processing, preventing the next page of results from being returned to the front end.

### Steps to Reproduce

Create a new report with pagination configured, do not add any Search Parameters. Execute the report, ensuring it contains enough results for pagination to be used. Click the 'Next' pagination button and notice pagination does not advance to the next page.

**Comment by davidjgonzalez** [comment]
Thanks for fixing this!
