### ISSUE TITLE
Enhancement: Page Refresh after Shared Component Properties not working

### ISSUE THREAD

**Issue by shivika21** [Adobe-Consulting-Services/acs-aem-commons#2291]
**Required Information**
[AEM 6.5 SP2]
[ACS AEM Commons Version 4.3.2]

**Expected Behavior**
Using the ACS Commons Shared Component Properties feature for storing Header / Footer configuration. The shared properties are stored at /content/my-site/gb/en level and are being read properly in all pages that use said component.
The component's shared properties can be edited on any page in the hierarchy and after editing the shared (or global) properties dialog, the current page should refresh so that authors could see the outcome of this configuration without manually refreshing the page.

**Actual Behavior**
After editing the shared (or global) properties dialog, the current page does not refresh so authors cannot see the outcome of this configuration without manually refreshing the page. A typical listener afteredit="REFRESH_PAGE" doesn’t seem to work since the properties are modified at a higher level than the page where editing is done.

**Steps to Reproduce**
Starting from a vanilla instance of AEM at the above version, install the demo packages available here: https://adobe-consulting-services.github.io/acs-aem-commons/features/shared-component-properties/index.html

Use the shared component properties on a page in /content/my-site/gb/en/abc/cde page for instance and after changing the shared properties, although they are stored as expected in /content/my-site/gb, the cde.html page does not refresh.

**Comment by HitmanInWis** [comment]
FWIW this has worked this way from Day 1.  The component on which the property is updated refreshes, so it only affects Shared/Global properties used by multiple components on the same page.  Though I agree this is truly a bug, it feels low priority.  If someone the submitter is willing to put up a PR for this, I'll be happy to review.  Else I'll put it in my queue of items to get around to, but can't guarantee how soon I'll be able to turn it around.
