### ISSUE TITLE
Copy Properties Workflow Step

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2293]
It would be nice to have a Workflow Process step that can copy properties of dam:Asset's (and cq:Pages) from one location to another. This is particularly useful with Assets to expose "AEM" properties values in XMP metadata. For example, it would be nice to have:

Assets onTime (jcr:content/onTime) exposed via XMP Metadata by way of having this value copied to (jcr:content/metadata/dam:onTime).

**Comment by jameslockman** [comment]
This is great! Thanks, @davidjgonzalez!
