### ISSUE TITLE
ScrMetadataIT was looking at Bintray for latest version; we are now on Maven central

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2299]
During release the ScrMetadataIT was failing since it looks for the latest bundle from bintray, which we no longer deploy to (we now deploy direct to maven central).

This requires updating `ScrMetadataIT.java` to look up the latest version from Maven Central. I made this change "ad-hoc" during the 4.7.0 release via [1] - assigning to @justinedelson  to do a quick once over (sorry for the whitespace changes, didn't realize that happened :()

https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/4a936b7153c4332236d284cc19c77c83b3eded21

**Comment by justinedelson** [comment]
LGTM. Not 100% sure that API is stable since the Maven Central API guide has gone missing. Asked Sonatype - https://twitter.com/justinedelson/status/1261279157964754946

but I think we can close this
