### ISSUE TITLE
Error duringAEM Upgrade from 6.2 to 6.5

### ISSUE THREAD

**Issue by vandsvna** [Adobe-Consulting-Services/acs-aem-commons#2302]
## Required Information

*AEM Version - 6.5

### Expected Behavior

package should compile without any error

### Actual Behavior

When I upload a package in AEM. I got below error.
 [FelixDispatchQueue] IA_Wrapper_Services.core FrameworkEvent ERROR (org.osgi.framework.BundleException: Unable to resolve IA_Wrapper_Services.core [588](R 588.0): missing requirement [IA_Wrapper_Services.core [588](R 588.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.event.jobs)(version>=1.5.0)(version<=2.0.0)) Unresolved requirements: [[IA_Wrapper_Services.core [588](R 588.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.event.jobs)(version>=1.5.0)(version<=2.0.0))])
org.osgi.framework.BundleException: Unable to resolve IA_Wrapper_Services.core [588](R 588.0): missing requirement [IA_Wrapper_Services.core [588](R 588.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.event.jobs)(version>=1.5.0)(version<=2.0.0)) Unresolved requirements: [[IA_Wrapper_Services.core [588](R 588.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.event.jobs)(version>=1.5.0)(version<=2.0.0))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Unknown Source)

**Comment by justinedelson** [comment]
This does not appear to be an issue with ACS AEM Commons.
