### ISSUE TITLE
Acs commons not listing under tools

### ISSUE THREAD

**Issue by vgajend** [Adobe-Consulting-Services/acs-aem-commons#2318]
## Required Information

* [6.5.3 ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [ 4.7.0] ACS AEM Commons Version: _____
* [ no] Reproducible on Latest? yes/no

acs commons not listing under tools icon

**Comment by badvision** [comment]
Did you install the content package as well as the ui.apps package?

**Comment by davidjgonzalez** [comment]
I havent checked this myself, but there's been noise wrt to the fault-vault plugin and how its deploying nodes:

We may need to adjust to something like:

```
<filter root="/apps/cq" mode="merge"/>
<filter root="/apps/cq/core/content/nav/tools/whatever/the/acs-node/is"/>
 ```

If this is infact an issue. Leaving this here so i don't forget :)

**Comment by vgajend** [comment]
@badvision  I installed it  both,

**Comment by badvision** [comment]
@vgajend do you have access to look at the JCR directory (crx de, crx explorer, etc?)  If so please try to look in /apps/cq/core/content/nav/tools and see what (if any) nodes are in there.
