### ISSUE TITLE
Can't seem to get JsonValueMapValue in any version. Tried 4.0.0 to 4.7.0

### ISSUE THREAD

**Issue by sau0201** [Adobe-Consulting-Services/acs-aem-commons#2321]
## Required Information

 * [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: All
* [ ] ACS AEM Commons Version: 4.0.0-4.7.0
* [ ] Reproducible on Latest? yes

I am importing the acs-common-4.7.0 bundle (tried 4.0.0 to 4.7.0) in my project. I can see other annotations available like aem object etc, but JsonValueMapValue is not available.

When I open the jar, I can see the interface for JsonValueMapValue is available but when I try to open impl file, I see the internal error.

I can share the screenshots if needed.

**Comment by joerghoh** [comment]
Hi,

can you please be more specific. Do you mean, that you cannot use the ```@JsonValueMapValue``` annotation as described in https://adobe-consulting-services.github.io/acs-aem-commons/features/sling-model-injectors/json-valuemap-value/index.html?

**Comment by sau0201** [comment]
yes. 
And while debugging the issue and unpacking the jar, I see an internal error when I open the impl class. 

![Screenshot (45)](https://user-images.githubusercontent.com/17959926/83412319-ba281180-a3ce-11ea-8da2-25e794ccf3f3.png)

**Comment by joerghoh** [comment]
That might be a problem with your tool, does it support Java8 properly?

**Comment by joerghoh** [comment]
Next question: How do you "see" that this annotation is not available to you? Is the completion in the IDE not available for this annotation?

**Comment by justinedelson** [comment]
FWIW, I'm not sure that supporting a decomplication GUI is necessarily a goal of this project. I would suggest creating a test project which illustrates the problem. I assume this is something that could be illustrated reasonably well using a unit test.

**Comment by sau0201** [comment]
I am getting compilation issue, when I add @JsonValueMapValue in my sling model.

![Screenshot (46)](https://user-images.githubusercontent.com/17959926/83461636-18301580-a41e-11ea-8b3f-a423693a469d.png)
![Screenshot (48)](https://user-images.githubusercontent.com/17959926/83461642-19f9d900-a41e-11ea-95a5-6a615ac611e9.png)
![Screenshot (47)](https://user-images.githubusercontent.com/17959926/83461647-1c5c3300-a41e-11ea-8b10-1943cf978bcc.png)

**Comment by justinedelson** [comment]
I really think providing a small test project which illustrates this problem would be easier to understand than screenshots.

**Comment by niekraaijmakers** [comment]
Weird. In my current project we use version 4.6.0 and I can put it in without compiler errors... Sure you put the dependency in your "core" module as well?

**Comment by sau0201** [comment]
closing this as it started working on its own.
