### ISSUE TITLE
Document AEM as a Cloud Service compatibility

### ISSUE THREAD

**Issue by stefanseifert** [Adobe-Consulting-Services/acs-aem-commons#2332]
currently, the documentation is inconsistent/unclear concerning the AEM version support/AEM as a Cloud Service compatibility. i assume the current release 4.7.0 is compatible with AEM as a Cloud service, probably earlier versions as well.

the compatibility matrix lists only up to AEM 6.5
https://adobe-consulting-services.github.io/acs-aem-commons/pages/compatibility.html

the README on the github page states "Target AEM 6.2+"
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/README.md

**Comment by davidjgonzalez** [comment]
Updated:  https://adobe-consulting-services.github.io/acs-aem-commons/pages/compatibility.html#aem-as-a-cloud-service-feature-incompatibility

**Comment by stefanseifert** [comment]
this looks great, thanks!
