### ISSUE TITLE
acs-aem-commons-ui.content-4.7.0.zip stuck in distribution queue on AEM cloud service

### ISSUE THREAD

**Issue by stefanseifert** [Adobe-Consulting-Services/acs-aem-commons#2334]
## Required Information

* AEM as a Cloud Service 2020.6.3731.20200615T120157Z
* ACS Commons 4.7.0
* ACS Commons included in an AEM project generated by AEM project archetype 23 based on these instructions: https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html
* sample project to reproduce the problem on this branch: https://github.com/stefanseifert/aem-cloud-service-deployment-issues/tree/feature/archetype-23-acscommonsacs

### Expected Behavior

* ACS commons 4.7.0 should deploy without problems on author and publish instances

### Actual Behavior

* Author deployment via cloud manager works fine, but installing the mutable content part of ACS commons (acs-aem-commons-ui.content-4.7.0.zip) on publish via replication often (not always) fails
* this also happens when the package acs-aem-commons-ui.content-4.7.0.zip is replicated manually on author via the package manager
* in the distribution queue it is visible that the package acs-aem-commons-ui.content-4.7.0.zip cannot be deployed to publish - even after hundres of attempts. unfortunately there is not trace about the reason to be found in the logs downloadable via the cloud manager UI (author/publish error logs).

screenshots:
![200618-distribution-queue-1](https://user-images.githubusercontent.com/5614031/85009732-348eba80-b15f-11ea-9f6a-e550d6766d6e.png)
![200618-distribution-queue-2](https://user-images.githubusercontent.com/5614031/85009736-3789ab00-b15f-11ea-8d8d-a23f02afa54e.png)

### Steps to Reproduce

try to deploy the sample project https://github.com/stefanseifert/aem-cloud-service-deployment-issues/tree/feature/archetype-23-acscommonsacs to an AEM cloud DEV instance, and check the distribution queues afterwards.

**Comment by stefanseifert** [comment]
the source of the problem may be #2341 (have not validated yet)

**Comment by davidjgonzalez** [comment]
Thanks @stefanseifert - I do believe the /var nodes are the cause of this.

https://docs.adobe.com/content/help/en/experience-manager-learn/cloud-service/debugging/debugging-aem-as-a-cloud-service/build-and-deployment.html#including-var-in-content-package
