### ISSUE TITLE
[Documentation/Bug] Ensure authorizable documentation error

### ISSUE THREAD

**Issue by paul-bjorkstrand** [Adobe-Consulting-Services/acs-aem-commons#2335]
The Ensure Authorizable [github.io page] has an invalid example snippet:

Currently, it is
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
    xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="sling:OsgiConfig"
    principalName="my-service-user"
    type="add"
    ensure-immediately="{Boolean}true"
    aces="[type=allow;privileges=jcr:read\,rep:write;path=/content/foo;rep:glob=/jcr:content/*]"/>
```
It should have `operation` instead of `type` (per both the screen shot and [the][ensure service user code] [code][ensure group code])
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
    xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="sling:OsgiConfig"
    principalName="my-service-user"
    operation="add"
    ensure-immediately="{Boolean}true"
    aces="[type=allow;privileges=jcr:read\,rep:write;path=/content/foo;rep:glob=/jcr:content/*]"/>
```

[github.io page]: https://adobe-consulting-services.github.io/acs-aem-commons/features/ensure-service-users/index.html
[ensure service user code]: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/users/impl/EnsureServiceUser.java#L62
[ensure group code]: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/users/impl/EnsureGroup.java#L70

It took me a little bit to figure out why changing from `add` to `remove` wasn't working :slightly_smiling_face:

**Comment by kwin** [comment]
@paul-bjorkstrand Please open this issue (in the best case with a PR) at https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/issues.

**Comment by paul-bjorkstrand** [comment]
Done: https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/pull/197

I thought that the site was a private repo or something, but really my googling skills just failed me (even more so since I already had a fork for that repo). That was an utter fail on my part.
