### ISSUE TITLE
Versioned ClientLibs affecting Preview Package generation (e.g. SDL Translation Preview )

### ISSUE THREAD

**Issue by tlocwin** [Adobe-Consulting-Services/acs-aem-commons#2338]
## Required Information

* [6.5 SP4 ] AEM Version, including Service Packs, Cumulative Fix Packs
* [4.4.0, 4.7.0 ] ACS AEM Commons Version
* [ yes ] Reproducible on Latest? 

### Expected Behavior
* After extract of preview package user is able to preview HTML properly with all JS, Assets ...etc as later same is used by SDL Preview. Paths should be rendered in the way that allowing  to point to file locally in order for proper rendition even on local & 3rd party system

```
<link rel="stylesheet" href="../../../../var/designs/about-us_1/jquery-ui.css" type="text/css">
<link rel="stylesheet" href="../../../../var/designs/about-us_1/site.css" type="text/css">
<link rel="stylesheet" href="../../../../var/designs/about-us_1/clientlib-base.css" type="text/css">
<link rel="stylesheet" href="../../../../var/designs/about-us_1/default.css" type="text/css”>
```

Preview OK
![Screenshot 2020-06-23 at 14 36 21](https://user-images.githubusercontent.com/13114062/85404280-080fdf80-b55f-11ea-89e5-251f5b39ab6a.png)

Preview NOK
![Screenshot 2020-06-23 at 13 46 06](https://user-images.githubusercontent.com/13114062/85404287-09d9a300-b55f-11ea-87a2-6257a820fa30.png)

### Actual Behavior
* Preview package is generated incorrectly because paths to JS, CSS are relative file paths but the file paths are not pointing to file properly so local preview is impossible

```
<link rel="stylesheet" href="/etc.clientlibs/clientlibs/granite/jquery-ui.aeeab65fc7671696263825aac469a40d.css" type="text/css">
<link rel="stylesheet" href="/etc.clientlibs/core/wcm/components/search/v1/search/clientlibs/site.bc5eb8ab7795d16a0a599fbaef2adfe6.css" type="text/css">
<link rel="stylesheet" href="/etc.clientlibs/weretail/clientlibs/clientlib-base.8f235fd0c38c1c7f77b9d3b691838e68.css" type="text/css">
<link rel="stylesheet" href="/libs/foundation/clientlibs/jquery-ui/themes/default.d41d8cd98f00b204e9800998ecf8427e.css" type="text/css">
```

### Steps to Reproduce
* Install  AEM 6.5.x
* Configure Versioned Client libs
* Install SDL connector (enable preview feature)
* Configure SDL connector / CloudService
* Create Translation Project + configuration (method, provider, source & target languages)
* Add Translation Job, set target language and add page for translation
* Start Job
* Once status is set as Translation In Progress please go to SDL Console and download preview package
* Extract and open HTML
* Links in HTMLs are wrong as preview doesn't work as expected
Note: once configuration of versioned client libs is removed preview package is generated properly and its possible to preview locally & on SDL side.

**Comment by kwin** [comment]
@tlocwin Isn't this the same as #2330?

**Comment by tlocwin** [comment]
@kwin I was testing changes related #2338 from master and issue is still present.

**Comment by kwin** [comment]
Probably a different attribute needs to be used to disable the rewriting in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/a9d8ead2840d7068bdd32f4bf0ddb920ebedf55e/bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java#L349.
