### ISSUE TITLE
Feature : Property level inheritance in Touch UI dialog

### ISSUE THREAD

**Issue by sumantapakira** [Adobe-Consulting-Services/acs-aem-commons#2346]
[##](url) Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5, Service Pack 5
* [ ] ACS AEM Commons Version: 4.1.0
* [ ] Reproducible on Latest? yes

### Expected Behavior
As per the current implementation of Touch UI dialog, it is not possible cancel inheritance of a particular field in a dialog. As an author it's only possible to cancel whole dialog.  
1 ) Author should have the possibility to cancel only property which they want to.
2) Author should be able to see dialog property without canceling the inheritance. 

### Actual Behavior
1) Author cannot see the dialog properties without cancelling the inheritance of whole dialog. 

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

### Steps to Reproduce

1. Start AEM 6.5 
2. Go to sample We-retail implementation and open Blue print page:  http://localhost:4502/editor.html/content/we-retail/language-masters/en/experience.html
3. Open the dialog of Hero image component and edit any dialog property
4. Rollout the page
6. Open Live copy page : http://localhost:4502/editor.html/content/we-retail/us/en/experience.html
7. Try to open the Hero image dialog property , you cannot see the dialog property without cancelling the inheritance. 
8. If you cancel the whole component inheritance but there is also no possibility to cancel only the specific property you want to do cancel inheritance

It becomes really difficult to manage for editors located into different parts of the world. 

I have implemented this behaviour, if you want to include I can create a pull request. 

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by badvision** [comment]
Is this caused by installing ACS Commons or are you reporting a product bug that occurs irrespective to installing ACS Commons?  If it's a core component that isn't working right you can report bugs on those here: https://github.com/adobe/aem-core-wcm-components

**Comment by sumantapakira** [comment]
This is not caused by ACS Commons and I also do not know whether it is a product bug or not because as per Adobe support this is by design. However I strongly believes that many content authors face this issue for which I have a solution.

**Comment by badvision** [comment]
Great to know!  I just wanted to make sure I understood the context of this problem.  Thank you for the additional clarification.

**Comment by sumantapakira** [comment]
@badvision what do you think about this feature?
