### ISSUE TITLE
Feature: Microsoft Teams connector

### ISSUE THREAD

**Issue by sumantapakira** [Adobe-Consulting-Services/acs-aem-commons#2347]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5, Service pack 5
* [ ] ACS AEM Commons Version: 4.1
* [ ] Reproducible on Latest? not applicable

When working in a distributed teams of developers and content authors then communication via chat tools like Microsoft Teams or Slack becomes more effective than emails. 

Use cases may includes as follows : 
1. As a developer or content authors I would like to receive notification on my Chat channel when AEM deployment is completed on different servers (Prod/Stage)
2. As a content author I would like to receive notification on Chat channel when someone rollout a page

Pls let me know whether would you like to add this feature.

**Comment by justinedelson** [comment]
There are solutions for these use cases already:

1. This is handled by the Cloud Manager API. The [tutorial](https://www.adobe.io/apis/experiencecloud/cloud-manager/docs.html) walks through a very similar use case.
2. I believe this can be done using the [I/O Events package for AEM](https://www.adobe.io/apis/experienceplatform/events/docs.html#!adobedocs/adobeio-events/master/using/aem-event-setup.md).

**Comment by sumantapakira** [comment]
You are right but this is useful for the customers who are not using Cloud Manager and Adobe I/O
Additionally this is not only for deployment notification but also for any kind of notification such as MSM rollout or Page activation etc

**Comment by justinedelson** [comment]
> One more point is that it does not really depends on CI/CD pipeline. For example, in a distributed team if someone install any package through package manager or curl command then it can notify through event listener.
> Additionally this is not only for deployment notification but also for any kind of notification such as MSM rollout or Page activation etc.

Can't both of these cases be handled using the I/O Events package? That can wrap any OSGi event in an I/O event.

Maybe it's just me but this feels like wheel reinventing.

**Comment by sumantapakira** [comment]
Ok, after reading the I/O event its possible, thanks for pointing this. 
Again, as I/O does not come for free so people would enjoy free wheel ride in this way :) or is it possible to enjoy free ride with I/O?

**Comment by justinedelson** [comment]
> Again, as I/O does not come for free so people would enjoy free wheel ride in this way open source project like ACS commons :) or is it possible to enjoy free ride with I/O?

IIUC, every AEM customer (certainly every AMS and Cloud Service, but I believe this is also true for on-premise customers) should have access to I/O Events. Other I/O services (I/O Runtime as an example) are different and do (at least AFAIK) have explicit licensing requirements.

**Comment by joerghoh** [comment]
Actually I understand everyone which wants to have a more straight-forward / less magic way to externalize certain events. Also it might makes sense to have a direct AEM-to-custom-application connection, especially the custom application is not reachable from the outside.
I believe that there are cases for that, but as the mentioned usecase "teams notifications" can clearly be done with using the I/O Events package for AEM. At least you should investigate this case before you start coding on AEM.

**Comment by sumantapakira** [comment]
Thanks @joerghoh  @justinedelson for the feedback, I will look into I/O events
