### ISSUE TITLE
Exporting Comparison Results

### ISSUE THREAD

**Issue by kanika-anetcorp** [Adobe-Consulting-Services/acs-aem-commons#2349]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______AEM 6.x
* [ ] ACS AEM Commons Version: _____ 4.x
* [ ] Reproducible on Latest? yes/no yes

### Expected Behavior

On running page compare/Jcr compare, can we export results?

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by davidjgonzalez** [comment]
Check out the `.dump.json` selector.

https://adobe-consulting-services.github.io/acs-aem-commons/features/jcr-compare/index.html#usage
