### ISSUE TITLE
Vanity Path Rewriter sometimes doesn't map incoming Urls

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2350]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5.x
* [X] ACS AEM Commons Version: 4.7.0
* [X] Reproducible on Latest? yes

### Expected Behavior

Candidate Vanity Urls should be resourceResolver.map(...)'d before being dispatched for resolution.

### Actual Behavior

Sometimes this doe not happen, because `new PathInfo(..)` will not call `map(..)` if `resourceResolver.resolve(..)` returns null on the existing path; which, TBH im not sure how its happening, however, this check IS in AEM's PathInfo(..) code base so I guess there is way for it to happen.

**Comment by joerghoh** [comment]
Fix committed in 4.7.2, closing
