### ISSUE TITLE
SMTPMailServiceHealthCheck can easily "run-away" and use up e-mail quotas

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2357]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.5
* [X] ACS AEM Commons Version: 4.7.0
* [X] Reproducible on Latest? yes

### Actual Behavior

It has been reported from several users, and observed by myself (via access to commonly used, shared SMTP accounts) that the SMTPMailServiceHealthCheck can be easily misconfigured and "run-away" sending thousands of emails over the course of a day.

It would be nice to add extra safeguards to prevent this from occurring.

1. Do not send an email if the default email address is used (as no one can actually verify if this email is, in fact, receiving anything vs. going into a black hole)
2. Put a max limit per day, with a default of 24 (eg. 1 per hour)

**Comment by joerghoh** [comment]
That means we should introduce a rate-limit (e.g. 1 email per hour) and ignore all subsequent invocations until at least an hour has passed.

I don't think that we need to be too precise, so we keep the statistics in-memory and if the bundle/systems restarts within the hour, you start again with the full limit. Everything else makes it too complicated.

@davidjgonzalez  would that suffice?

**Comment by joerghoh** [comment]
Ok, looks like this has already been fixed. Closing.
