### ISSUE TITLE
Remove deprecated composite multifield widget

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#2361]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3+
* [x] ACS AEM Commons Version: 4.x
* [x] Reproducible on Latest? yes

### Expected Behavior

Unless there is a strong exception, customers should use the product-provided multifield widget and switch off of the 5-year old one provided in ACS Commons which has seen few updates over the past couple of years.

### Actual Behavior

Customers continuing to use the ACS Commons multifield widget in recent AEM versions report issues frequently.

### Steps to Reproduce

Deploy a customer using ACS Commons multifield.  Wait 3-4 years.  Observer lots of issues about it not working after upgrading.

Recommended short-term is to just replace the multifield with a stub that points to the product's version as its super type and then remove existing code.  Only issue is that the product version of the widget does not support the same JSON store feature as the ACS Commons widget, so simply removing the widget might leave some folks high and dry.

**Comment by badvision** [comment]
@schoudry , @davidjgonzalez , @justinedelson -- thoughts?

**Comment by schoudry** [comment]
acs commons one supports node store (NODE_STORE) and json store (JSON_STORE)... otb composite supports node store only; afaik there are customers still using json store, the only path forward for them is to migrate the json into node structure for using product composite multifield... should we direct them to do so?

**Comment by davidjgonzalez** [comment]
As much as I don’t like this for all the GH issues it causes, ppl do rely on it.  We’ll effectively break all those people. 

Perhaps we could provide an OOTB ondeploy script or sling pipe that transforms all the JSON data to composite nodes when we do remove this to help make the transition less painful?

If we do remove it should be in 5.x obviously.
