### ISSUE TITLE
Email Notification is not working as expected on one set of environment where as working on other set of environment

### ISSUE THREAD

**Issue by rohitspathak** [Adobe-Consulting-Services/acs-aem-commons#2364]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.4 (SP6)
* [ ] ACS AEM Commons Version: 4.0.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

Email alerts should be sent from AEM.

Email Notification is not working as expected on one set of environment where as working on other set of environment
This is exactly same issue which was reported here:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1137

This ticket was closed asking user to create Day Care ticket. But what was the resolution. Same issue we are facing too.

### Actual Behavior

Email alerts are not getting sent from AEM.

### Steps to Reproduce

1. Login to AEM OSGI
2. Try using ACS E-Mailer for sending test email
/system/console/configMgr/com.adobe.acs.commons.hc.impl.SMTPMailServiceHealthCheck
3. No email is sent from some AEM Env. On other AEM Env its working.

NOTE : SMTP Details has already been configured in OSGI
/apps/system/config/com.day.cq.mailer.DefaultMailService.config

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by joerghoh** [comment]
@rohitspathak Just to be sure: you get the same exception as described in #1137? Can you update your version of ACS AEM Commons to a more recent one, just to be sure that this issue has been fixed in the meanwhile?
