### ISSUE TITLE
s3 Ingestor Service  causing Jetty session leak on AEM 6.5.4/ACS Commons 4.7.0

### ISSUE THREAD

**Issue by rgummalla** [Adobe-Consulting-Services/acs-aem-commons#2368]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: ___AEM 6.5.4/ ACS Commons 4.7.0____
* [ ] ACS AEM Commons Version: __4.7.0___
* [ ] Reproducible on Latest? yes/no

### Expected Behavior

Once the S3 Ingestor service is disabled, there shouldnt be any sessions left in heap memory

### Actual Behavior

When you do use S3 Ingestor Service for ingesting assets from S3 to AMS AEM 6.5.4, it works fine. After few hours of disabling S3 ingestor service, there are lots of jetty session in memory close to 3 GB.

### Steps to Reproduce

1. Start AEM 6.5.4
2. Install ACS Commons 4.7.0
3. Use S3 Ingestor Service
4. Import few assets and disable the service
5. wait 6-7 hours, take heap dumps
6. Check to see if there are too many jetty sessions left in the heap.

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by davidjgonzalez** [comment]
@badvision / @justinedelson  - does this sound like connections made from action managers aren't being closed or something?

**Comment by badvision** [comment]
Action manager isn't managing those connections but it is possible that the import code itself (S3) that opens those connections isn't using a pool that cleans itself up.

**Comment by joerghoh** [comment]
But why would the S3 library use jetty sessions? I would expect jetty sessions to be used when incoming requests are causing requests to jetty/AEM, and there HTTP sessions are opened. But I would be surprised if that would happen.

**Comment by rgummalla** [comment]
sorry for the confusion. You are right. There is no correlation between s3 and jetty sessions. you can close this issue.
