### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#2374]
See https://tools.ietf.org/id/draft-knodel-terminology-00.html and others.

**Comment by kwin** [comment]
https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by davidjgonzalez** [comment]
Sounds good to me. I'm trying to think if/which integrations will need to change (travis, codeclimate, etc.)

**Comment by badvision** [comment]
Should not be too difficult.  Will we have to re-point any existing pull requests to the new branch name?

**Comment by joerghoh** [comment]
also let's purge the master branch and just leave a small README.md there. Just to avoid any confusion.
