### ISSUE TITLE
Shorten Sitemap urls

### ISSUE THREAD

**Issue by ampatial** [Adobe-Consulting-Services/acs-aem-commons#2376]
## Required Information

* [ ] AEM Version 6.5.3.0
* [ ] ACS AEM Commons Version: 4.4.2

**Details About the Issue:**
Urls are forming in sitemap.xml like this:-

**Existing:** 
https://www.host.com/somefolder/a/aa/aabss/
https://www.host.com/somefolder/a/ab/abass/
https://www.host.com/somefolder/b/ba/aabss/
https://www.host.com/somefolder/b/bb/abass/
....
....
....
https://www.host.com/somefolder/y/ya/yaabss/
https://www.host.com/somefolder/z/za/zabass/

**Expected:** 
https://www.host.com/somefolder/aabss/
https://www.host.com/somefolder/abass/
https://www.host.com/somefolder/aabss/
https://www.host.com/somefolder/abass/
....
....
....
https://www.host.com/somefolder/yaabss/
https://www.host.com/somefolder/zabass/

want to remove two alphabetical folder after somefolder path , how can we do it via regular expression, it is working fine if we give the complete url but not working with regular expression. We are setting URL Rewrites rule with regular expression in ACS Commons Sitemap Servlet configuration like this:-

^/([a-z]{2,3}-([a-z]{2,3}))/${somefolder}/(.)/([A-Za-z0-9]{2})/(.*?)$/$1/${somefolder}/$5

Also tried with other regular expression but its not working. can we add regex expression for all the urls matching the format.
Please let me know if you need more details.

**Comment by shsteimer** [comment]
@ampatial If you take a look at the code for this servlet [0], note that the url rewrites are applied after the externalizer configuration. I suspect the first part of your regex. `^/([a-z]{2,3}-([a-z]{2,3}))` is being mapped out by the externalizer, thus leaving you with a url `/somefolder/a/aa/aabss` which no longer matcher your regular expression. Try removing that piece from your regex and adjusting the replacement indices.

[0]: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/6b3a51752e228970634a589bd553f1a5ef83eb3f/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/SiteMapServlet.java#L273

**Comment by ampatial** [comment]
> @ampatial If you take a look at the code for this servlet [here](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/6b3a51752e228970634a589bd553f1a5ef83eb3f/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/SiteMapServlet.java#L273), note that the url rewrites are applied after the externalizer configuration. I suspect the first part of your regex. `^/([a-z]{2,3}-([a-z]{2,3}))` is being mapped out by the externalizer, thus leaving you with a url `/somefolder/a/aa/aabss` which no longer matcher your regular expression. Try removing that piece from your regex and adjusting the replacement indices.

@shsteimer tried as per your suggestion but its not working.

**Comment by joerghoh** [comment]
When you use url rewriting on the webserver to map the incoming (short) paths to the repository paths, do you have the resource mapping in place to create properly the (short) paths for links?

**Comment by ampatial** [comment]
> When you use url rewriting on the webserver to map the incoming (short) paths to the repository paths, do you have the resource mapping in place to create properly the (short) paths for links?

@joerghoh When setting URL Rewrites rule with regular expression in ACS Commons Sitemap Servlet configuration like this:-
/somefolder/a/aa:/somefolder/ - this is removing the a/aa folders
but not working with regex.

**Comment by joerghoh** [comment]
I understand, but even without this setting in the Sitemap Servlet your AEM should generate short URLs; how are you doing that? 

(Because if you use either /etc/map or a configuration of the ResourceResolverFactory, you shouldn't need to use the regexp feature, because it is done automatically.)
