### ISSUE TITLE
ACS Commons - Parameterized Granite Include - "Server Error" occurred, after use search in inbox.

### ISSUE THREAD

**Issue by OpekunAleksei** [Adobe-Consulting-Services/acs-aem-commons#2380]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5.5.0
* [ ] ACS AEM Commons Version: 4.8.0

### Expected Behavior

When i open inbox select search and type title of existing inbox item 
![image](https://user-images.githubusercontent.com/31468362/89018310-56fe2100-d324-11ea-8c4d-9234af17255c.png)
 search it, should find these items 
![image](https://user-images.githubusercontent.com/31468362/89018355-7006d200-d324-11ea-85c0-23542526dd1a.png).

### Actual Behavior

When i open inbox select search and type title of existing inbox item
![image](https://user-images.githubusercontent.com/31468362/89018310-56fe2100-d324-11ea-8c4d-9234af17255c.png)
 search it, error popup is shown
![image](https://user-images.githubusercontent.com/31468362/89018527-b2c8aa00-d324-11ea-8c09-6b08183051a3.png).

### Steps to Reproduce

Starting from a vanilla instance of AEM 6.5 install 6.5.5 Service Pack, install ACS AEM Commons Version: 4.8.0. Go to /aem/inbox, select search, try to find "Configure".

### Additional info
It broken due to use IncludeDecoratorFilterImpl filtering by resourceType. Sling https://github.com/apache/sling-org-apache-sling-resourceresolver/blob/master/src/main/java/org/apache/sling/resourceresolver/impl/ResourceTypeUtil.java relativizeResourceType(...) method throw java.lang.NullPointerException: null for "/aem/inbox" search
![image](https://user-images.githubusercontent.com/31468362/89019836-9ded1600-d326-11ea-8328-26673423de2b.png)
![image](https://user-images.githubusercontent.com/31468362/89021706-a4c95800-d329-11ea-8c87-839a6d8a7a3f.png)

The screenshot points to a resource w/ this type:

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/ui.apps/src/main/content/jcr_root/apps/acs-commons/granite/ui/components/include/include.jsp

... I'm not sure why this is a problem or how its being called looking at the screenshot stack

**Comment by niekraaijmakers** [comment]
Ok, nice find, this is really weird.

Clear steps to reproduce. Il take a look on this bad boy.
