### ISSUE TITLE
Principal based service users need to be defined using [ ] 

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2388]
Our principal based service users dont use the property bracket-based definition in the Service user mapper OSGI config def.

We need to do this before we cut 5.0.0

**Comment by davidjgonzalez** [comment]
This should be fixed via a9441e6 as part of the PR to move things out of /var

**Comment by davidjgonzalez** [comment]
@kaushalmall  Does this look right? https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/a9441e6b64a00c8332b88fd613b982606a76de79

**Comment by joerghoh** [comment]
Is it possible to merge this to the 4.8.x codebase? Or does it require AEM 6.4?

**Comment by kaushalmall** [comment]
AFAIR, this is a 6.4+ deal. If 4.8.x supports 6.3, that would be a no go.

**Comment by joerghoh** [comment]
Ehm, 4.8.x still supports AEM 6.3 :-)
