### ISSUE TITLE
Sitemap rewrite url does not support regex expression

### ISSUE THREAD

**Issue by ravipampana1** [Adobe-Consulting-Services/acs-aem-commons#2395]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: __AEM 6.5.3_____
* [ ] ACS AEM Commons Version: _4.4.2____
* [ ] Reproducible on Latest? yes/no: Yes

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

Sitemap rewrite (url.rewrites) should support regex so that we can rewrite the url as we show it live

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

Currently the url.rewrite will only works if the regex is starting with the url string and cannot replace for string in the middle of the url

Ex: we can only replace if url and url.rewrite matches starting string

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

Try to replace the string in between url using url.rewrites and it wont work 

### Links

_Links to related assets, e.g. content packages containing test components_

**To fix this we need to change the logic in below file**

SiteMapServlet.java - acs-aem-commons/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/SiteMapServlet.java

Line no: 262

**Existing:**

{code}
 if (path.startsWith(rewrite.getKey())) {
          return url.replaceFirst(rewrite.getKey(), rewrite.getValue());
}
{code}

**New:**

{code}
 if (path.matches(rewrite.getKey())) {
      return url.replaceFirst(rewrite.getKey(), rewrite.getValue());
 }
{code}

**path.startsWith** to **path.matches**

I tested the code with latest version of ACS Commons (4.8.5) and functionality is working as expected.

Please review and let me know if the changes are good to push ? If possible please provide me git commit access.

**Comment by kwin** [comment]
@ravipampana1 Can you provide a PR as described in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/CONTRIBUTING.md#how-to-contribute-code?
