### ISSUE TITLE
AEM Environment Indicator not working

### ISSUE THREAD

**Issue by mt33** [Adobe-Consulting-Services/acs-aem-commons#2396]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.5
* [x] ACS AEM Commons Version: 4.8.4
* [x] Reproducible on Latest? yes/no

### Expected Behavior

With the Filter correctly configured:

![image](https://user-images.githubusercontent.com/597107/90655339-73002e80-e20f-11ea-9630-6fcac554cabe.png)

I expected the indicator to appear in the HTML response.

### Actual Behavior

The indicator HTML is not part of the response.

The Filter never injects the indicator HTML because `accepts` returns false, because `isDisallowedWcmMode` returns true, because there is no WCMMode object to be found in the `HttpServletRequest` object, so it defaults to `DISABLED`.

![image](https://user-images.githubusercontent.com/597107/90655859-194c3400-e210-11ea-9ac6-e874a4c71650.png)

I don't know why this is.

In our own project, our filters do have the correct WCMMode in the request object e.g. `LoggingFilter` which is a sample class from the latest AEM Maven Archetype:

![image](https://user-images.githubusercontent.com/597107/90656504-5e706600-e210-11ea-804c-dbeb18ea67b9.png)

### Steps to Reproduce

* Install ACS AEM Commons on a clean 6.5.5 instance
* Add the AEMEnvironmentIndicator OSGI config
* Observe that no HTML gets added to any pages in the administrative console pages.

**Comment by mt33** [comment]
Thanks for looking into it @joerghoh, appreciate it. After running a few more tests I got it working, not entirely sure what happened on my end. Closing this one.

**Comment by joerghoh** [comment]
Thanks for letting us know!

**Comment by AntonValadzko** [comment]
@mt33 Hi, I have the same issue, it starts working only when I update config manually in OSGI console, but doesn't work via delivering these properties using OSGI config. As far as I understand the root cause of your issue is unknown and it just started to work, right?

**Comment by mt33** [comment]
Hey @AntonValadzko - it only worked for me when using the `.config` style OSGI config, which is what the system will use when manually creating/editing it in the OSGI console. So in your codebase, use a text file `com.adobe.acs.commons.wcm.impl.AemEnvironmentIndicatorFilter.config` with contents e.g.

```
always-include-base-css=B"false"
browser-title-prefix="Local"
excluded-wcm-modes=[""]
css-color="#e9c2a6"
always-include-color-css=B"false"
css-override=""
inner-html=""
```

and it should work on deploy!

**Comment by AntonValadzko** [comment]
Thanks @mt33 It works although contradicts with ACS Commons documentation a bit )) 
**UPD** It works even with XML format, looks like this property is mandatory - excluded-wcm-modes=[""] which is not obvious

**Comment by kwin** [comment]
I think you are running into #2402.

**Comment by AntonValadzko** [comment]
@kwin Agree. Closing my issue then. Thanks
