### ISSUE TITLE
on-deploy-scripts-status/rep:policy import error on publish instances

### ISSUE THREAD

**Issue by averma21** [Adobe-Consulting-Services/acs-aem-commons#2398]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [ ] ACS AEM Commons Version: _____
* [ ] Reproducible on Latest? yes/no

We have seen import error in publish instances - 
`org.apache.jackrabbit.vault.fs.io.Importer E /var/acs-commons/on-deploy-scripts-status/rep:policy (org.xml.sax.SAXException: javax.jcr.AccessDeniedException: Access denied.`

### Expected Behavior

Import error should not occur.

### Actual Behavior

Import error occurs

### Suggestion

Either this path should not be replicated, or `sling-distribution-importer` should have read/write permissions for this path.

```
set principal ACL for sling-distribution-importer
  allow   jcr:read,rep:write    on /var restriction(rep:glob,/acs-commons)
end
```

**Comment by joerghoh** [comment]
On which AEM version do you see this? Can you please specificy, when exactly you see this error? Is on during deployment of ACS AEM Commons or during runtime? Which version of ACS AEM Commons do you use?

**Comment by andrewmkhoury** [comment]
@joerghoh this is on AEMaaCS it was causing deployment issues (see SKYOPS-8318).
