### ISSUE TITLE
Installing MS-Office-asset selector

### ISSUE THREAD

**Issue by jmlg10** [Adobe-Consulting-Services/acs-aem-commons#2400]
## Required Information

aem 6.5.5 with ACS Commons 4.8

I've installed all I've found on AEM

I've the manifest files for PPT and Word edited, but how I install the add-in in PPT or word ?

**Comment by davidjgonzalez** [comment]
Hi @jmlg10 - this should be covered in the docs:

http://adobe-consulting-services.github.io/acs-aem-commons/features/ms-office-asset-selector/index.html

For "testing/try-out" purposes check out Network Share Catalog section, click into the MSFT docs, and then follow the instructions based on the OS/Platform youre using (different instructions for windows vs. mac vs. etc)

![image](https://user-images.githubusercontent.com/1451868/91987731-6c3be600-ecfc-11ea-9b12-7c4e3c2a1d5a.png)

**Comment by jmlg10** [comment]
Hi,
Thanks, I achieved to make it running on my Mac.
But it looks more difficult for Office "online".. probabily because the URL of my AEM is not public is'nt it?
I get an error "the manifest is not valid" when uploading the manifest...
