### ISSUE TITLE
OCM, Object Content Mapping (feature request)

### ISSUE THREAD

**Issue by ankur-rajput** [Adobe-Consulting-Services/acs-aem-commons#2406]
**Feature to persist models/pojos to JCR.**
Basically, right now we can only map JCR content to models (using Sling models), but there is no way to create JCR content based on our model structure.

**Available Solution:**
Jackrabbit OCM
_Issues with Jackrabbit OCM:_

- No direct bundle is provided, need to embed and configure multiple jars
- Need to work on low-level Node APIs.

It will be a great add on if we can have OCM for AEM/Sling like we have ORM for SQL.
Ongoing thread on the community - https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/persisting-sling-model-ocm/qaq-p/301637

**Comment by henrykuijpers** [comment]
Have a look at the stuff that was added in https://issues.apache.org/jira/plugins/servlet/mobile#issue/SLING-8450

**Comment by ankur-rajput** [comment]
Thanks, @henrykuijpers. This looks good to me,
