### ISSUE TITLE
Multi Field Panel doesn't load Selection's dynamic options

### ISSUE THREAD

**Issue by MisterKamran** [Adobe-Consulting-Services/acs-aem-commons#241]
#### Scenario:

Add a "selection" xtype, with type "select" to a multifieldpanel that loads its options via a servlet.

``` xml
<unit-id
    jcr:primaryType="cq:Widget"
    fieldLabel="Unit Id"
    key="unit-id"
    options="$PATH.unitid.options.json"
    type="select"
    xtype="selection"/>
```
#### Issue:

The drop down generated by the "selection" xtype fails to dynamically load its options as configured.
#### Fix:

Add a "listeners" child node to the selection node to force reloading options from servlet before it is rendered.

``` xml
<listeners
    jcr:primaryType="nt:unstructured"
    beforerender="function(){this.processPath();}"/>
```

**Comment by vasily-lazerko** [comment]
I've fixed that by adding a runtime `multifieldpanel` patch to `dialog.xml`:
```xml
<jcr:root xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
          jcr:primaryType="cq:Dialog">
...
    <listeners jcr:primaryType="nt:unstructured"
               beforerender="function(){&#10;
        if(!ACS.CQ.MultiFieldPanel.prototype.processPath) {
          ACS.CQ.MultiFieldPanel.prototype.processPath = function(path) {&#10;
            this.items.each(function(i){&#10;
              if(i.processPath) {&#10;
                i.processPath(path);&#10;
              }&#10;
            });&#10;
          }}}"/></jcr:root>
```
I hope this fix as well as recursive getValue/setValue for dialogfieldset will be included into the future ACS-AEM-Commons releases.

**Comment by justinedelson** [comment]
@vasily-lazerko can you submit a pull request with this change?

**Comment by davidjgonzalez** [comment]
ClassicUI issue
