### ISSUE TITLE
BucketPath in WorkflowPackageManager is appending continuously to its value the latest bucketSegment

### ISSUE THREAD

**Issue by leonardoderks** [Adobe-Consulting-Services/acs-aem-commons#2416]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.5
* [ ] ACS AEM Commons Version: 4.4.2
* [ ] Reproducible on Latest? yes

### Expected Behavior

When creating several workflow packages using the WorkflowPackageManager from acs-aem-commons, the path returned in the same create method is always equivalent to /var/workflow/packages/ + the bucketSegment sent as a parameter. The page path returned is not altered based on previous calls of the method.

### Actual Behavior

When creating workflow packages using the WorkflowPackageManager from acs-aem-commons we are experimenting this issue:

The bucketPath global variable in the service https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/workflow/impl/WorkflowPackageManagerImpl.java#L111 
is appending continuously to its value the latest bucketSegment sent in the create method: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/eb7219a8ac462414b51e3e76cf74bbdbefbe78bb/bundle/src/main/java/com/adobe/acs/commons/workflow/impl/WorkflowPackageManagerImpl.java#L134

Precisely in this line of code:
`bucketPath += "/" + bucketSegment;`

This means that the first time we create a workflow package we get a path like this:
`/var/workflow/packages/project/tenant/site/`

But after the tenth time, the page path returned is:
`/var/workflow/packages/project/tenant/site/project/tenant/site/project/tenant/site/project/tenant/site/project/tenant/site/project/tenant/site/project/tenant/site/project/tenant/site/project/tenant/site/project/tenant/site/`

This was working as expected for Acs-Aem-Commons in previous version 4.3.4. Within this version the bucketPath was calculated per every call: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/b4df3184c681b5583181f68508071fa87d45100f/bundle/src/main/java/com/adobe/acs/commons/workflow/impl/WorkflowPackageManagerImpl.java#L116

### Steps to Reproduce

Create several workflow packages using the WorkflowPackageManager from acs-aem-commons and check the path use for every package in the repository. 

### Links

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/eb7219a8ac462414b51e3e76cf74bbdbefbe78bb/bundle/src/main/java/com/adobe/acs/commons/workflow/impl/WorkflowPackageManagerImpl.java#L134

**Comment by muhammad-naveed** [comment]
Since the default value of `ReferenceScope` is `ReferenceScope.BUNDLE`, the `bucketPath` variable will keep its value through out the life cycle of the bundle. See https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/92209894197be247950bb5b47b40a3b10b1947f5/bundle/src/main/java/com/adobe/acs/commons/workflow/impl/WorkflowPackageManagerImpl.java#L111

So every time, the `WorkflowPackageManager.create()` method is called, a new string is concatenated to its value.

**Comment by kwin** [comment]
Can you come up with a PR?

**Comment by leonardoderks** [comment]
> Can you come up with a PR?

yes, I will do
