### ISSUE TITLE
Call to setContentLength truncates UTF-8 encoded responses

### ISSUE THREAD

**Issue by andrewmkhoury** [Adobe-Consulting-Services/acs-aem-commons#2425]
Calling of setContentLength in this line of the AemEnvironmentIndicatorFilter is causing UTF-8 encoded responses with multi-byte characters to get truncated.  It sets the number of characters in the response, not the number of bytes.
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/4bf5877c59fbec7894374b2d1be16ff5f5de0f75/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/AemEnvironmentIndicatorFilter.java#L217

**Comment by joerghoh** [comment]
@andrewmkhoury What do you think if we remove the content-length header completely (and remove this line)?

**Comment by andrewmkhoury** [comment]
Please, yes, do not set that header if it isn't necessary, it caused major problems.  I think I would be hearing from others about the same issue if we don't fix this quickly.  Not just OOME being the problem here but we had a problem were it was causing model.json calls to be truncated, causing invalid json.  Debugging and isolating it to this piece of code was quite the challenge.

**Comment by joerghoh** [comment]
See #2432 for the fix.
