### ISSUE TITLE
URL Asset Importer is ignoring cq:tags when tags exist in the image file

### ISSUE THREAD

**Issue by stevemayberry** [Adobe-Consulting-Services/acs-aem-commons#2427]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.3.0
* [ ] ACS AEM Commons Version: behavior is consistent on 4.5.2 and 4.8.4
* [ ] Reproducible on Latest? Yes

### Expected Behavior
When importing assets using URL Asset Import, existing image tags and tags specified in the Excel file (cq:tags) should BOTH be assigned to the asset.

### Actual Behavior
When the image file has been tagged in LightRoom, those tags are applied to the asset in AEM. Tags from the Excel file are not applied.

### Steps to Reproduce
Tag an image in LightRoom (TAG1) and save somewhere URL addressable. Create a URL import spreadsheet with that URL and a cq:tag value that is different from the tag that was added in LightRoom (TAG2). Use URL Asset Import to import that image into AEM. The asset will have TAG1 associated, but not TAG2

### Links
N/A

**Comment by badvision** [comment]
I suspect it could be an issue with your workflow, because that likely kicks off after import is done.  Have you tried disabling your asset workflow launchers during import?

**Comment by stevemayberry** [comment]
Imported same data with and without "workflow inhibited" checked = same result. Appreciate the thinking though. Any other ideas?



Steve Mayberry
Cognitive Box Consulting, LLC
(856) 687-3839



________________________________

**Comment by davidjgonzalez** [comment]
@stevemayberry you can look at using https://adobe-consulting-services.github.io/acs-aem-commons/features/workflow-processes/dam-metadata-property-reset/index.html

That WF Process was made for this case (originally in concert with CSV asset importer) ... It lets you either:
1) Copy metadata data values to temp props, run XMP writeback, and then copy them back (2 instances of WF Process steps)
2) Import your "real" metadata values into tmp properties (ie. your excel would write to: stevesTags) and then after XMP runs, this would copy "stevesTags" to "cq:tags" overwriting XMP extracted values)
