### ISSUE TITLE
Renovator not activating moved pages

### ISSUE THREAD

**Issue by mckeehanheadwire** [Adobe-Consulting-Services/acs-aem-commons#2430]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.0
* [ ] ACS AEM Commons Version: 4.8.4
* [ ] Reproducible on Latest? yes

### Expected Behavior

When I move content using the renovator I expect the moved content to be activated/published.

### Actual Behavior

Content is not activated

### Steps to Reproduce

Add a test to see if the asset is activated. For example, add a test to the testMoveManyAssets() method.
`assertTrue("Should publish new asset", queue.getActivateOperations().containsKey("/content/dam/folderC/subfolder/asset1-renamed"));
`

**Comment by badvision** [comment]
It was really designed to just republish pages if they were referring to assets which were moved.  Moving pages and republishing has other implications such as caching concerns and what not -- gets a little messy.

As an alternative you can take the report and filter the list of pages; then use Curly to republish those pages.  It's an extra step but still better than the alternative (or rather, the lack thereof).  I'm happy to leave this issue open in case someone has time to take up this issue but I do not at the moment, would require more time than I have available, sadly.
