### ISSUE TITLE
Question: Use of @SuppressWarnings({"findsecbugs:PATH_TRAVERSAL_IN"}) 

### ISSUE THREAD

**Issue by ksurendra** [Adobe-Consulting-Services/acs-aem-commons#2431]
## Required Information

* [ 6.5 ] AEM Version, including Service Packs, Cumulative Fix Packs, etc:
* [ 4.8.5 ] ACS AEM Commons Version: _____
* [ y ] Reproducible on Latest? yes

### Question

In the following files 
- https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/asset/FileAssetIngestor.java
- https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/54afe1508ff37f60eb68204333e48fe22da3b2df/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/FileImporter.java

there is a reference to the use of
`@SuppressWarnings({"findsecbugs:PATH_TRAVERSAL_IN"})`

Was this used to bypass Code Quality Tests? 

## Reference
We were seeing below in code quality test reports when not using the above annotation (not in acs commons classes, but in our custom code):
- Issue: java/io/File.<init>(Ljava/lang/String;)V reads a file whose location might be specified by user input
- Type/Severity: Vulnerability | Major
- Rule: **findsecbugs:PATH_TRAVERSAL_IN**
- Tags: cwe,owasp-a4,wasc
- Documentation: https://www.adobe.com/go/aem_cmcq_path_traversal_in_en

**Comment by justinedelson** [comment]
IIRC, the only code path available is one where an administrator could provide the file path. Generally this vulnerability warning is about untrusted inputs. Both cases have inline comments to this effect.

**Comment by ksurendra** [comment]
> IIRC, the only code path available is one where an administrator could provide the file path. Generally this vulnerability warning is about untrusted inputs. Both cases have inline comments to this effect.

Thanks @justinedelson
