### ISSUE TITLE
Contributor Rights Request

### ISSUE THREAD

**Issue by shsteimer** [Adobe-Consulting-Services/acs-aem-commons#2433]
Would like to get contributor rights so that I can assist with the release process.

**Comment by badvision** [comment]
You've contributed a lot to the project, so I have no reservation with this request.  @davidjgonzalez ?  @joerghoh ?

**Comment by badvision** [comment]
Interpreting no objections as consent. ;P

**Comment by davidjgonzalez** [comment]
👍  from me! (sorry - was on vaca!)
