### ISSUE TITLE
Enhancement : Ability to update asset references in components which have the paths as a list or Array[]

### ISSUE THREAD

**Issue by axp235** [Adobe-Consulting-Services/acs-aem-commons#2439]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 7.5.2_______
* [ ] ACS AEM Commons Version: _____ 4.8.6
* [ ] Reproducible on Latest? yes

### Expected Behavior

- Provide a spreadsheet to Renovator with source and destination columns. Upon the execution, all pages/XF with references should be updated with destination URL's irrespective of if the component has property fields which have assets listed as Array.

### Actual Behavior

- Updates references which match with a singular source field doesn't take care of updating all the values in property
Refer to the snapshot below in the comments for a screenshot

### Steps to Reproduce

- Run Renovator against content which have a list of assets in a single property

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by mxp737** [comment]
<img width="1447" alt="2020-10-15 at 5 08 PM" src="https://user-images.githubusercontent.com/32717784/96186219-1bc5c400-0f09-11eb-965a-22d1ed2fae59.png">

**Comment by badvision** [comment]
Does it find the affected referring items and just not update them correctly?

**Comment by axp235** [comment]
@badvision: The code has trouble when it sees a list of values. It tries to take entire content of the property and compare with "Source" field of the Renovator spreadsheet and doesn't see that as a match. PR raised my @mxp737  - https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2444 addressed this.

**Comment by badvision** [comment]
Phew!  That's a relief!  Thanks for working so hard to make this a better experience for others.  It really helps a lot.  I've seen Renovator getting a lot more use lately so this will definitely yield some good karma down the road.
