### ISSUE TITLE
Request Contributor Rights

### ISSUE THREAD

**Issue by axp235** [Adobe-Consulting-Services/acs-aem-commons#2440]
Requesting contributor rights so I participate in reviews and solve the following issues

https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2436
https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2438
https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2439

**Comment by badvision** [comment]
I'm very excited for your contributions to ACS Commons.  For now can you comment on these issues?  Also mention me in the reviews and I'll prioritize the review and acceptance of them once all the automated rules are happy with the pull requests.  I saw a code complexity issue on one of them that needs to be resolved (and yes, it is kind of an important rule that we observe low cyclomatic complexity -- it makes unit testing a lot easier as well as code clarity/maintenance.)

**Comment by axp235** [comment]
@badvision  I have tagged you for review on PR  https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2442
We are having issues with another PR  https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2443 It shows some Test Failures that we don't see in our Local and wanted to check if there is a way to see the Surefire reports and if there are any tips that we should consider for our Local Travis setup
