### ISSUE TITLE
Report download servlet can exhaust the heap if the report is too large

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#2441]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.5
* [x] ACS AEM Commons Version: 4.4.0+
* [x] Reproducible on Latest? yes

### Expected Behavior

Custom reports from ACS Commons should have realistic limits to prevent generating reports that are too large to be of any value to the user; unbounded queries can inadvertently return a very large report by accident.

### Actual Behavior

Report size is unbounded, begin/end conditions should be more enforced; also the report download servlet should stream data out of JCR and into CSV not hold anything in memory.  This behavior combined with an overly-broad query killed a production server with a 40gb heap!

![image](https://user-images.githubusercontent.com/5144198/96140123-36764980-0ec5-11eb-9932-0cf6ac138b6e.png)

### Steps to Reproduce

Find a DAM instance with millions of assets.  Create a report with an end date but no start date.  Then try to download the report.  Watch server melt to molten slag.

**Comment by badvision** [comment]
@joerghoh , @davidjgonzalez  I'm concerned that in the ReportCSVExportServlet that we're loading all the results into memory.  This is a pretty stupid idea because we could just iterate a stream of results and avoid the memory issue as shown above.

![image](https://user-images.githubusercontent.com/5144198/96151833-7ba07880-0ed1-11eb-8e5e-e7cf873e4693.png)

1) Loading all results into a list is not a good idea
2) Loop should use an iterator instead; but is that provided?  If not can we add one, or at least loop over pages so we don't retrieve a gigantic list all at once?

Another option is to place an artificial limit on the max number of report rows we will ever support, e.g. 1-2 million or something.

**Comment by badvision** [comment]
@klcodanr , @justinedelson  ^^

**Comment by klcodanr** [comment]
Nice one @badvision - So a couple of thoughts: first it probably should be streaming, but I also wonder if it should limit to a million rows since that's also the limit for Excel to open the file.

**Comment by badvision** [comment]
Problem is that even a million rows can get expensive.  In this scenario the report was taking so long, the user assumed it was stuck and reloaded.  Twice.  Hence the heap ran out 3x faster.

**Comment by badvision** [comment]
If we enforce boundary conditions (max results cap) and stream results, this problem should be very resolved, I think.  Any other ideas?

**Comment by klcodanr** [comment]
I'd also probably want to add something basically warning the user that large results will take a significant amount of time. I know it's not fool-proof, but at least a message may help.

**Comment by badvision** [comment]
You did a lot of great refactoring in here recently, did you want to take the first swing @ it @klcodanr?

**Comment by klcodanr** [comment]
Yep :-) I can take a swing, I'll have to figure out the best way to create a _bunch_ of data to test (probably groovy + content fragments)

**Comment by badvision** [comment]
I can help with that, feel free to ping me to discuss once we're ready for testing.

**Comment by badvision** [comment]
(just focus on making sure our unit tests assert the expected behavior and I can assist manual testing)

**Comment by klcodanr** [comment]
@badvision - I tested 69b8c7a02ddbcdad8cdd79cffd55f437439a465d locally on my end and it served a 1.6 million line CSV on a 4GB heap. 

Note that the path-based executor does still use a list internally, but... don't create a million paths and you should be fine :-)

**Comment by badvision** [comment]
That's exciting!  What a quick turnaround @klcodanr!  Let me know when you're in the mood to PR that sucker.
