### ISSUE TITLE
One page is displayed in multiple lines in Report Builder export CSV file

### ISSUE THREAD

**Issue by ivanarizovski** [Adobe-Consulting-Services/acs-aem-commons#2446]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6.0
* [ ] ACS AEM Commons Version: 4.5.0
* [ ] Reproducible on Latest? yes

### Expected Behavior
One page is shown in one line in the downloaded report

### Actual Behavior
One page is displayed in several lines in the downloaded CSV file
That is happening if any of the properties of the result columns contain a newline character

### Steps to Reproduce
Configure a report as described below: 
1. Setup a JCR query report configuration. 
- Query language: JCR-SQL2
- Query: SELECT * FROM [cq:Page] AS p WHERE ISDESCENDANTNODE('{{path}}')
2. Setup ACS Commons Report Builder Basic Parameter
- Label: Path
- Name: path
- Field type: Text Field
3. Setup ACS Commons Report Builder Text Column
- Heading: Title
- Property: jcr:content/jcr:title
4. Setup ACS Commons Report Builder Text Column
- Heading: Description
- Property: jcr:content/jcr:description
5. Add a new line in the description/title property on some pages
6. Open the configured report
7. Add a path that contains the pages with the edited description/title
8. Execute and download the report
=> The pages that have newline in the description/title will be displayed in multiple lines in the downloaded report. The newlines should be escaped, so the pages are shown properly in the report.

**Comment by badvision** [comment]
We saw a rewrite of that in the main branch and are gearing up for a new ACS Commons release featuring these recent fixes.  If it isn't too much trouble, could you see if this still happens with the latest main branch code?

**Comment by klcodanr** [comment]
It looks like this will also be fixed with #2450, still need to validate.

**Comment by badvision** [comment]
If it weren't for social distancing there'd be a line of folks waiting to be the next person to buy you the next round.  Thanks @klcodanr !!!

**Comment by badvision** [comment]
Also I think it's extremely reasonable to assume that if it works in one version of excel it should work in another or else it's a Microsoft bug we don't need to own.

**Comment by klcodanr** [comment]
Yeah, I'm more worried about line endings in Mac v. Windows. One of our folks has a PC and is checking now.

**Comment by klcodanr** [comment]
@samruddhi30 verified this also works for Excel for Windows
![MicrosoftTeams-image](https://user-images.githubusercontent.com/2946250/96625573-5ac69180-12dc-11eb-8014-306042baa463.png)

**Comment by badvision** [comment]
You guys are overachieving this week.  Love it!  Thanks so much. 🥇

**Comment by ivanarizovski** [comment]
@badvision @klcodanr Thank you both. May I ask you when is the release 4.8.8 planed?
