### ISSUE TITLE
Non-Latin letters shown as "?" in the downloaded report

### ISSUE THREAD

**Issue by ivanarizovski** [Adobe-Consulting-Services/acs-aem-commons#2450]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6
* [ ] ACS AEM Commons Version: 4.5.0
* [ ] Reproducible on Latest? yes

### Expected Behavior
Non-Latin letters are shown properly in the CSV report file

### Actual Behavior

Non-Latin letters are shown as "?" 

### Steps to Reproduce

Configure a report  (Tools -> Acs Aem Commons -> Reports) as described below:

1. Setup a JCR query report configuration.
 - Query language: JCR-SQL2
 - Query: SELECT * FROM [cq:Page] AS p WHERE ISDESCENDANTNODE('{{path}}')
2. Setup ACS Commons Report Builder Basic Parameter
 - Label: Path
 - Name: path
 - Field type: Text Field
3. Setup ACS Commons Report Builder Text Column
 - Heading: Title
 - Property: jcr:content/jcr:title
4. Setup ACS Commons Report Builder Text Column
 - Heading: Description
 - Property: jcr:content/jcr:description
5. Add a non-Latin letters in the description/title property on some pages
6. Open the configured report
7. Add a path that contains the pages with the edited description/title
8. Execute and download the report
=> The non-Latin letters are shown as "?" in the downloaded CSV report file
Note: The same letters are shown properly on the page when the report is executed.

**Comment by badvision** [comment]
What program are you using to open the CSV file?

**Comment by ivanarizovski** [comment]
@badvision I am using Microsoft Excel and Google Sheets

**Comment by badvision** [comment]
@davidjgonzalez @klcodanr -- I'm trying to triage this.  The export servlet sets content type to "text/csv;charset=UTF-8"; is there anything else involved in the export that could affect character encoding?  e.g. should I just try adding a line like this?
`response.setCharacterEncoding("UTF-8");`

**Comment by badvision** [comment]
I don't see anything else in the output chain where I can specify character encoding; the CSV api only takes writer as a parameter, but interestingly if provided an output stream it also accepts character set for desired encoding.

**Comment by klcodanr** [comment]
It looks like adding the BOM before writing the CSV fixes the issue for me, e.g.:

      // write the BOM to indicate this is a UTF-8 file
      writer.write("\uFEFF");

Still need to do some regression testing (e.g. open in a few different tools, etc)

**Comment by badvision** [comment]
Well, would it be safer to change the output encoding to Windows-1252 for better compatibility?  I prefer UTF-8 myself but it is a bit of a wildcard to assume every CSV tool interprets BOM correctly.  Also: Thank you!  I had gone done the rabbit-hole of finding the day CSV implementation and didn't find anything other than the fact charset encoding is respected however the writer is configured that is passed in.

**Comment by badvision** [comment]
There's nothing in the CSV format notes that mandate a specific character set, so this makes sense.  And realistically, I found a very common thread in online discussions regarding UTF-8 and CSV so it seems like a pretty common practice.

**Comment by klcodanr** [comment]
Unless I'm missing something doesn't Windows-1252 not support non-Latin languages? I'll see if I can round up someone with a PC to test this fix with Excel on a PC. I've tested with VSCode, Mac Excel, BBEdit and GDrive.
