### ISSUE TITLE
Publish instances Restart Issue

### ISSUE THREAD

**Issue by rkatteragandla-lt** [Adobe-Consulting-Services/acs-aem-commons#2455]
## Required Information

* [ ] AEM Version: 6.4, Service Pack: 6.4.4
* [ ] ACS AEM Commons Version: 4.3.4
* [ ] Reproducible on Latest? yes

### Expected Behavior

_Publish instances should not be getting restarted when a page is accessed after deployment._

### Actual Behavior

_Publish instances are getting restarted when a page is accessed after deployment_

### Steps to Reproduce

1. Deploy code base to publish server
2. Access any page. Since this is the first time we access a page after code changes, AEM starts to minify the clientlibs.
3. Minification is taking longer at this point of time and the session is going idle for ~10 minutes
4. Server gets restarted
5. We did our investigation and found that the Minification engine is taking more time when there are huge chunk of selectors in CSS.
6. Optimized the code to have less number of selectors to apply styles for any elements on the page
7. After the above step the session idle time is reduced to ~4 minutes
8. But, the restart issue still persists

It would be great if someone can let us know if there is any limitations with number of selectors here or any other reasons that causes this kind of issues. Thanks in advance.

**Comment by joerghoh** [comment]
Is here any ACS AEM Commons involved in here?

**Comment by davidjgonzalez** [comment]
Closing as does not appear to be ACS Commons release. If it is please provide more details how this is ACS Commons relevant and re-open.
