### ISSUE TITLE
BufferedServletResponse should only defer flushing if the output is really buffered

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#2459]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6
* [x] Reproducible on Latest? yes

### Expected Behavior

Even in case some filter leveraging the BufferedServletResponse (e.g. the AEMEnvironmentIndicatorFilter) is used, it should not defer flushing unbuffered responses. In most of the cases only the writer is buffered (i.e. text output) while the outputstream (binary output) is not buffered.

### Actual Behavior

The following warn can be observed in the log
```
30.10.2020 15:13:50.982 *WARN* [0:0:0:0:0:0:0:1 [1604067230756] GET /content/...../_jcr_content/image.img.840.560.70.20201018174339.jpg HTTP/1.1] com.adobe.acs.commons.util.BufferedServletResponse Prevent committing the response, it will be committed deferred, i.e. once this buffered response is closed
```

This is due to the following lines

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/d4640dd5ce47233a68c4d81ee093b90c76f68f83/bundle/src/main/java/com/adobe/acs/commons/util/BufferedServletOutput.java#L195

This does not only pollute the log unnecessarily, it also leads to latency degradations and increases memory consumption.

### Steps to Reproduce

Just enable the AEM Environment filter and request some binaries (i.e. images)

**Comment by joerghoh** [comment]
@kwin The problem is there are cases where both writer and the outputstream is used in the same request (also the ones which need to handled by consumers of that feature eg. the EnvironmentIndicator), so a synchronisation of the handling is required, and which also requires that the flush is deferred.

This message is only written in case of an explicit flush(), and I think that this is normally not required at all. I am OK to set that message to DEBUG.

**Comment by kwin** [comment]
> The problem is there are cases where both writer and the outputstream is used in the same request
This is illegal in Servlet spec, according to https://docs.oracle.com/javaee/6/api/javax/servlet/ServletResponse.html#getWriter()

> Either this method or getOutputStream() may be called to write the body, not both.

**Comment by maximenougarede** [comment]
@kwin : I noticed an issue with this specific commit using an AEM vanilla 6.5.6 instance and requesting the start page: http://localhost:4502/aem/start.html . The page doesn't render at all.

`05.11.2020 12:00:17.230 *ERROR* [qtp210337050-1952] org.apache.felix.http.jetty Exception while processing request to /aem/start.html (java.lang.IllegalStateException: Committed)
java.lang.IllegalStateException: Committed
	at org.eclipse.jetty.server.HttpChannel.resetBuffer(HttpChannel.java:908) [org.apache.felix.http.jetty:4.0.16]
	at org.eclipse.jetty.server.HttpOutput.resetBuffer(HttpOutput.java:1413) [org.apache.felix.http.jetty:4.0.16]
	at org.eclipse.jetty.server.Response.resetBuffer(Response.java:1132) [org.apache.felix.http.jetty:4.0.16]
	at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:195) [org.apache.felix.http.servlet-api:1.1.2]
	at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:195) [org.apache.felix.http.servlet-api:1.1.2]
	at com.adobe.acs.commons.util.BufferedServletOutput.resetBuffer(BufferedServletOutput.java:173)
	at com.adobe.acs.commons.util.BufferedHttpServletResponse.resetBuffer(BufferedHttpServletResponse.java:68)
	at com.adobe.acs.commons.wcm.impl.AemEnvironmentIndicatorFilter.doFilter(AemEnvironmentIndicatorFilter.java:206)
...
`

**Comment by kwin** [comment]
@maximenougarede Please report a dedicated issue against version 4.9.0!
