### ISSUE TITLE
Versioned ClientLibs with SHA2 Family (SHA256, SHA386, and SHA512) instead of MD5.

### ISSUE THREAD

**Issue by umairahmad14** [Adobe-Consulting-Services/acs-aem-commons#2462]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5 Service pack 6.5.6.0
* [ ] ACS AEM Commons Version:  4.4.0
* [ ] Reproducible on Latest? yes/no : yes

Hi All, ACS AEM Commons Versioned ClientLibs uses Sling Rewriter to rewrite the client libraries generated by aem and append a unique MD5 value at the end of the client library URL and later it is cached. It generates a new MD5 value every time a modification to the client library happens and appends the generated MD5 value to the client library url for re-cashing. MD5 cryptographic algorithms are outdated and vulnerable to security. Is there another version of the Versioned ClientLibs or any other implementation that uses SHA2 Family (SHA256, SHA386, and SHA512) instead of MD5?

**Comment by davidjgonzalez** [comment]
What is your cryptographic/security concern exactly in the context of this feature. The hash is not used for security in this case, so more details around your concern are required.
