### ISSUE TITLE
Adjusted GitHub setting: Don't dismiss stale approvals

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#2464]
Currently this repository is configured in a way that stale approvals are dismissed whenever new commits are pushed (https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-reviews-for-pull-requests, point 8). Since very often after an approval conflicts on the Changelog need to be resolved (leading to new pushes) I would recommend to either

1. Don't dismiss stale reviews (with the potential danger that the additional commit introduces unintended non-approved behaviour)
1. or to no longer maintain Changelog in Git, but exclusively rely on GitHub issues tagged with the correct milestone.

**Comment by kwin** [comment]
@davidjgonzalez WDYT?

**Comment by kwin** [comment]
@davidjgonzalez @joerghoh Can you explain which of the two options from above you prefer?

**Comment by davidjgonzalez** [comment]
@kwin I just updated for #1 

![image](https://user-images.githubusercontent.com/1451868/98544052-695ff300-2261-11eb-9ed3-558a24560c75.png)

For me, the changelog is nice in that were not as clean w/ the GH milestones (some times things get added to say, 4.9.4 but then we release as 4.10.0 - and never back-update the 4.9.4 milestones (for example).

Also, sometimes things just don't get assigned a milestone :(

**Comment by kwin** [comment]
You can edit milestones: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/creating-and-editing-milestones-for-issues-and-pull-requests. But I am fine, if you think that maintaining the changelog is beneficial.

**Comment by davidjgonzalez** [comment]
Yes - it's more of an issue of someone actually updating it :)

With multiple approvers/releasers it's been "hard" for us make sure the issues are accurately tagged. Often, I'll actually use the change list to track down issues/PRs at release and update GH milestones from there.

Not saying it's ideal, but I'm not sure there's a (realistic) good way to fix this.
