### ISSUE TITLE
AEM start page is not rendering with AemEnvironmentIndicatorFilter

### ISSUE THREAD

**Issue by maximenougarede** [Adobe-Consulting-Services/acs-aem-commons#2467]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6
* [ ] ACS AEM Commons Version: 4.9.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

AEM start page is displayed

### Actual Behavior

AEM start page is not  rendered

### Steps to Reproduce

- start vanilla instance 6.5.6 with ACS AEM Commons 4.9.0 installed
- access http://localhost:4502/aem/start.html and check the behavior 

### Links

Error log:
`05.11.2020 12:00:17.230 *ERROR* [qtp210337050-1952] org.apache.felix.http.jetty Exception while processing request to /aem/start.html (java.lang.IllegalStateException: Committed) java.lang.IllegalStateException: Committed at org.eclipse.jetty.server.HttpChannel.resetBuffer(HttpChannel.java:908) [org.apache.felix.http.jetty:4.0.16] at org.eclipse.jetty.server.HttpOutput.resetBuffer(HttpOutput.java:1413) [org.apache.felix.http.jetty:4.0.16] at org.eclipse.jetty.server.Response.resetBuffer(Response.java:1132) [org.apache.felix.http.jetty:4.0.16] at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:195) [org.apache.felix.http.servlet-api:1.1.2] at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:195) [org.apache.felix.http.servlet-api:1.1.2] at com.adobe.acs.commons.util.BufferedServletOutput.resetBuffer(BufferedServletOutput.java:173) at com.adobe.acs.commons.util.BufferedHttpServletResponse.resetBuffer(BufferedHttpServletResponse.java:68) at com.adobe.acs.commons.wcm.impl.AemEnvironmentIndicatorFilter.doFilter(AemEnvironmentIndicatorFilter.java:206) ...`

seems related to #2459 fix (reverting it does fix the issue).

**Comment by kwin** [comment]
This is an edge case where flush is called before either `getWriter` or `getOutputStream` has been called. Also in this case the flush should be deferred. I will come up with a fix.
