### ISSUE TITLE
Replacement for Redirect Map Manager for AEMaaCS

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#2471]
As https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-map-manager/index.html is no longer supported in AEMaaCS due to the lack of cron job support, I would propose a different feature (which might leverage the same UI):

Implement a new servlet filter (one of the first ones in the chain) which would evaluate the redirect configuration and issue a 302 or 301 respectively in case of a matching incoming request url. The response should also carry a Cache-Control header to make it possible to cache the result in the CDN (https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/content-delivery/cdn.html?lang=en#content-delivery, https://docs.fastly.com/en/guides/http-status-codes-cached-by-default)

Update: I opened https://github.com/AdobeDocs/experience-manager-cloud-service.en/issues/56 to get clarification on CDN caching support of redirects, as Adobe CDN being Fastly right now is an implementation detail and might change in the future....

**Comment by davidjgonzalez** [comment]
Resolved by #2513 (available in 4.12.0 and 5.0.0)
