### ISSUE TITLE
Content rendered twice on publisher when environment indicator is enabled

### ISSUE THREAD

**Issue by rvankraaij** [Adobe-Consulting-Services/acs-aem-commons#2475]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6.0
* [ ] ACS AEM Commons Version: 4.9.2
* [ ] Reproducible on Latest? yes

### Expected Behavior

Content should not be rendered twice on a publisher when the AemEnvironmentIndicatorFilter is enabled.

### Actual Behavior

Pages are rendered twice on publish instance. On author it's working fine, also with wcmmode=disabled.

### Steps to Reproduce

Enable the EnvironmentIndicatorFilter on a publish instance

```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
          jcr:primaryType="sling:OsgiConfig"
          browser-title-prefix="Local"/>
```

**Comment by kwin** [comment]
I cannot reproduce. I enabled the environment filter on publish and then opened view-source:http://localhost:4503/content/wknd/us/en.html. I see only one time a start html tag and one time an end html tag.
What is meant exactly by rendered twice?

**Comment by rvankraaij** [comment]
Two html start and end tags.

When I debug the AemEnvironmentIndicatorFilter it reaches line 241 with variable contents being the same as what is already written to the response.

`} else {
                if (contents != null) {
                    final PrintWriter printWriter = response.getWriter();
                    printWriter.write(contents);
                }
            }`

Noticed btw that the same happens for me with /libs/granite/csrf/token.json requests.

it returns 

`{token: abcd12}{token: abcd12}`

**Comment by kwin** [comment]
I still cannot reproduce. The original response should not be written to the socket: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/70096364f3cda33a38a8ae6c437533e9b08ece5e/bundle/src/main/java/com/adobe/acs/commons/util/BufferedServletOutput.java#L199 which is used in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/a3da8a5193efc931bd25245cfdf817e471120c9c/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/AemEnvironmentIndicatorFilter.java#L207.

Please set a breakpoint to https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/70096364f3cda33a38a8ae6c437533e9b08ece5e/bundle/src/main/java/com/adobe/acs/commons/util/BufferedServletOutput.java#L206 if that is triggered, and then check the variables `writeMethod`, `outputstream` and `writer`.

Also please check if you hit https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/a3da8a5193efc931bd25245cfdf817e471120c9c/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/AemEnvironmentIndicatorFilter.java#L231 or https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/a3da8a5193efc931bd25245cfdf817e471120c9c/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/AemEnvironmentIndicatorFilter.java#L242.

**Comment by rvankraaij** [comment]
I'm only reaching the last one AemEnvironmentIndicatorFilter#242, but I noticed its also hitting BufferedServletOutput#close method from try with resources statement in AemEnvironmentIndicatorFilter.

https://photos.app.goo.gl/HbpDAoXi6PLhhbis8

At that moment the content is duplicated.

**Comment by kwin** [comment]
Thanks for the additional information. I can reproduce even on author with requests to `/libs/granite/csrf/token.json`. The reason is that if you end in the else branch in line 242ff the buffered response is first given out via the `PrintWriter` and then implicitly again via the `BufferedHttpServletResponse.close()`
