### ISSUE TITLE
Replace deprecated SlingSettingsService

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#2476]
Since AEM SDK 2020.10.4423.20201028T010735Z-201028 the class `org.apache.sling.settings.SlingSettingsService` is deprecated: https://www.javadoc.io/doc/com.adobe.aem/aem-sdk-api/latest/org/apache/sling/settings/SlingSettingsService.html.

We must replace the all usages of that class: https://github.com/Adobe-Consulting-Services/acs-aem-commons/search?q=SlingSettingsService

It is unclear right now what would be the recommended API now to figure out if one is on Author or on Publish (compare with https://github.com/adobe/aem-project-archetype/issues/528#issuecomment-725554749).

**Comment by shashimuluguaem** [comment]
@kwin Any update on how you solved it?

**Comment by kwin** [comment]
Unfortunately I don't have a solution. But it is marked for removal on 1st of June 2021 in https://experienceleague.adobe.com/docs/experience-manager-cloud-service/release-notes/deprecated-apis.html?lang=en , so we need to come up with a solution now.

@joerghoh Any idea how to replace those e.g. in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/ff750e963a7ca3a1df49f4a9afa8aca4be4c63ef/bundle/src/main/java/com/adobe/acs/commons/util/ModeUtil.java? Basically starting from 1st of June ACS AEM Commons will stop working on AEMaaCS (again).

**Comment by davidjgonzalez** [comment]
@royteeuwen, unfortunately, nothing in the product itself - The POV being that things that depend on author/publish should depend on an OSGi configuration value that is set VIA the author/publish runmode, btu not the runmode itself. 

Admittedly this does leak possible otherwise unnecessary layers into an app.

**Comment by royteeuwen** [comment]
And also forces every framework to make their own osgi configuration / service again and again, in time you have 10 custom osgi configurations just to say, i'm an author / publish

**Comment by davidjgonzalez** [comment]
To be clear, I'm not disagreeing :)

We can incorporate this into RequireAEM if we want (it's implemented in ASC now, so we can copy it over).

https://github.com/adobe/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/util/impl/RequireAemImpl.java#L82

**Comment by kwin** [comment]
It is no longer deprecated since [AEMaaCS 17569](https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/release-notes/maintenance/latest). Compare https://javadoc.io/doc/com.adobe.aem/aem-sdk-api/2024.8.17465.20240813T175259Z-240700/org/apache/sling/settings/SlingSettingsService.html with https://javadoc.io/doc/com.adobe.aem/aem-sdk-api/latest/org/apache/sling/settings/SlingSettingsService.html.

**Comment by royteeuwen** [comment]
wow, who finally pulled that string :D!
