### ISSUE TITLE
NPE in JcrPackageReplicationStatusEventHandler

### ISSUE THREAD

**Issue by olenaslyshkova** [Adobe-Consulting-Services/acs-aem-commons#2492]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEMaaCS 2020.11.4506.20201112T235200Z
* [ ] ACS AEM Commons Version: 4.11.0
* [ ] Reproducible on Latest? yes

### Expected Behavior
On content package replication, configured node types/resource paths are set with corresponding replication metadata.

### Actual Behavior
An NPE appears in the logs, the replication metadata is not set.

`15.12.2020 03:46:29.543 [cm-p7802-e44859-aem-author-789fbd7c9b-zd9cp] *WARN* [Discovery-AsyncEventSender] org.apache.sling.discovery.commons.providers.base.AsyncTopologyEvent trigger: handler threw exception. handler: com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler@9427cc6, exception: java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler.handleTopologyEvent(JcrPackageReplicationStatusEventHandler.java:503) [com.adobe.acs.acs-aem-commons-bundle:4.11.0]
	at org.apache.sling.discovery.commons.providers.base.AsyncTopologyEvent.trigger(AsyncTopologyEvent.java:53) [org.apache.sling.discovery.commons:1.0.20]
	at org.apache.sling.discovery.commons.providers.base.AsyncEventSender.run(AsyncEventSender.java:118) [org.apache.sling.discovery.commons:1.0.20]
	at java.base/java.lang.Thread.run(Thread.java:834)`

### Steps to Reproduce

1. Configure the ACS AEM Commons Package Replication Status Updater: configure node types/resource paths that are included in a content package A.
2. Replicate the content package A.
Result:
The mentioned NPE can be found in the logs.
Replication metadata configured for node types/resource paths in the step1 is not set.

**Comment by kwin** [comment]
I assume the following is happening: 
1. Initially `isLeader` is set to `false` (https://github.com/Adobe-Consulting-Services/acs-aem-commons/blame/05e6e86fb69aff6afe7c3e4297b2be1d787e268a/bundle/src/main/java/com/adobe/acs/commons/replication/status/impl/JcrPackageReplicationStatusEventHandler.java#L163)
2. During `handleTopologyEvent` the NPE is thrown i.e. `isLeader` stays `false`.
3. When replication events are detected in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blame/05e6e86fb69aff6afe7c3e4297b2be1d787e268a/bundle/src/main/java/com/adobe/acs/commons/replication/status/impl/JcrPackageReplicationStatusEventHandler.java#L201 nothing happens, ass `isLeader` is `false`.

The issue in 2. should be temporary only as `TopologyEvent.getNewView()` is only supposed to return `null` in case of event `TOPOLOGY_CHANGING`. According to https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/reference-materials/javadoc/org/apache/sling/discovery/TopologyEventListener.html the `TOPOLOGY_CHANGING` event should always be followed by a `TOPOLOGY_CHANGED` event.

**Comment by kwin** [comment]
I think it makes more sense to rely on the [DiscoveryService](https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/reference-materials/javadoc/org/apache/sling/discovery/DiscoveryService.html) to check if one is running on the leader. Registering a `TopologyEventListener` does not assure, that a valid topology event has been received before a replication event needs to be processed.

**Comment by VishalBansal1508** [comment]
@kwin This issue is fixed with 4.12.0 release, but we are using <version>5.1.2</version> & still facing the same issue?
can you please help us on this : 

Issue : WARN* [Discovery-AsyncEventSender] org.apache.sling.discovery.commons.providers.base.AsyncTopologyEvent trigger: handler threw exception. handler: [com.adobe.acs.commons.util.impl.DiscoveryServiceHelper@44139618](mailto:com.adobe.acs.commons.util.impl.DiscoveryServiceHelper@44139618), exception: java.lang.IllegalStateException: Invalid BundleContext.
java.lang.IllegalStateException: Invalid BundleContext. [Seen in author error log]

**Comment by VishalBansal1508** [comment]
Open a another defect for same issue in 5.1.2 ACS common version: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3290
