### ISSUE TITLE
 Live Copies do not reflect references to local pages due to the error AemEnvironmentIndicatorFilter not accepted for uri /

### ISSUE THREAD

**Issue by AbhishekAnsira** [Adobe-Consulting-Services/acs-aem-commons#2501]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs: Adobe Experience Manager - 6.5.6.0
* [ ] ACS AEM Commons Version: 4.5.0
* [ ] Reproducible on Latest? yes/no

### Expected Behavior

We are trying to create a live copy from US to LATAM.
The references on the Live copy in LATAM should point to local pages in LATAM region.

### Actual Behavior

The references on the Live copy in LATAM are pointing to pages in US region instead of LATAM region.

Example: We created a live copy of following page
/content/xyz/us/en/solutions/abc/conventional-debt
To
/content/xyz/latam/en/solutions/abc/conventional-debt

The links/references on  /content/xyz/latam/en/solutions/abc/conventional-debt are still pointing to US pages and not local pages in LATAM.

### Steps to Reproduce

Create a live copy of page from US directory to any regional directory. 
This was working fine before but not sure what went wrong and it stopped working.
We opened a support ticket with Adobe and they pointed to an issue in ACS-AEM-COMMONS citing following reason:

-------------------------------------------------------------------
***Adobe's response***

"I have checked the error logs and found the following problem;

15.12.2020 10:34:28.519 *WARN* [qtp814692317-375935] com.adobe.ams.environment.indicator.wcm.impl.AemEnvironmentIndicatorFilter not accepted for uri /content/xyz/apac/en/solutions/abc/conventional-debt.html

This is caused by ACS-AEM-COMMONS and needs to be checked by ACS-AEM-COMMONS team please check the URL [1] and create a ticket by [2] if the URL [1] is not useful

[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1848
[2] https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues
 "

**Comment by davidjgonzalez** [comment]
Hi @AbhishekAnsira - you will need to raise this issue with Adobe AMS. This exception is coming from

`com.adobe.ams.environment.indicator.wcm.impl.AemEnvironmentIndicatorFilter` (note com.adobe.__ams__...) so it's not ACS Commons code (that would be `com.adobe.acs.commons....`). Perhaps AMS copied this out, and updated it to their liking - but either way, they will need to support it since we don't have visibility into their code-base, nor would a "fix" on our end, fix their forked code.

Thanks!
