### ISSUE TITLE
Redirect Map Manager

### ISSUE THREAD

**Issue by benrookeAVEVA** [Adobe-Consulting-Services/acs-aem-commons#2519]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5 (AMS Basic plan)
* [ ] ACS AEM Commons Version: _____
* [ ] Reproducible on Latest? yes

### Expected Behavior

Currently we rely on DevOps resources to create/edit page redirect rules that are managed in the AEM dispatcher level. This is restrictive and is dependent on production code push. 

I see Adobe consulting previously promoted the use of Redirect Map Manager to allow AEM users to make redirect map changes directly.  See - https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-map-manager/index.html 

As this product does not support out AEM version/deployment type, could you provide any other recommendations from ACS.

**Comment by kwin** [comment]
Doesn't this duplicate #2471?

**Comment by davidjgonzalez** [comment]
Resolved by #2513 (available in 5.0.0)
