### ISSUE TITLE
When xliff file is uploaded , source strings are duplicated with some spaces (which are not intended) in AEM

### ISSUE THREAD

**Issue by chaitanyaAlwala** [Adobe-Consulting-Services/acs-aem-commons#2520]
## Required Information

AEM Version 6.5.5(SP5)
No Dispatcher:
Java : jdk 11:
ACS Commons : 4.3.0

### Expected Behavior

I uploaded a xliff translation dictionary with source strings as en , and target strings as es. "id" in the translation.html and id in xliff file are different. 
Expected: Under same row and "es" column new strings are added. 

### Actual Behavior
after the upload ,the source strings are duplicated , previous souce strings has target languages ,but newly uploaded target language shows in a different row . 

@justinedelson 
@joerghoh 
Sir Pls help

**Comment by davidjgonzalez** [comment]
@chaitanyaAlwala what ACS Commons feature is in regards to?

**Comment by chaitanyaAlwala** [comment]
Its not related to acs commons , should i close it?, i didnt find anything like translations , so i have added here randomly. If you have a solution, pls do help
@davidjgonzalez

**Comment by davidjgonzalez** [comment]
@chaitanyaAlwala if you could - youll probably get better help from the Adobe Forums: https://experienceleaguecommunities.adobe.com/ or if you reach out to Adobe Support (if you suspect this is a product issue)
