### ISSUE TITLE
Bulk Workflow Manager no start button

### ISSUE THREAD

**Issue by btaymaz** [Adobe-Consulting-Services/acs-aem-commons#2521]
## Required Information

* [6.5 ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [4.8.4 ] ACS AEM Commons Version: _____
* [yes] Reproducible on Latest? yes/no

### Expected Behavior

Should work

### Actual Behavior

No start button shows up

### Steps to Reproduce

Just try to start new bulk workflow

### Links

N/A
![acs-bulk-wf](https://user-images.githubusercontent.com/56704328/106543358-8eb47400-64d3-11eb-900d-f93368733d26.png)

**Comment by davidjgonzalez** [comment]
@btaymaz im not able to reproduce this. 

Can you provide any logs from the browser's JS Console, anything from the AEM error.log, etc. and re-open when you attach them to this issue?

Thanks!

**Comment by btaymaz** [comment]
I figured out, sometimes workflows stuck in this state you don't see submit buttons here. Especially when you doing bulk asset import, DAM Asset Update workflow stuck and it resumes working after restart.
