### ISSUE TITLE
Versioned ClientLibs not working with Resource Resolver Mapping

### ISSUE THREAD

**Issue by pcastelog** [Adobe-Consulting-Services/acs-aem-commons#2528]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6
* [ ] ACS AEM Commons Version: 4.11.2
* [ ] Reproducible on Latest? yes

### Expected Behavior

When the project contains a Resource Resolver Mapping to hide the clientlib technical path, the service should be able to find the correct path before trying to obtain the Library.

### Actual Behavior

The service is relying on the path found in the html and not trying to resolve it first.

### Steps to Reproduce

[1] Setup and instance 6.5.6 with the ACS versioned clientLibs on.
[2] Add a JCR Resource Resolver Mapping like /etc/designs/myproject-/
[3] Check if the md5 was added to the request

### Links

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java#L276
It's failing on this line when is doing the getLibrary() with the incorrect path

**Comment by kwin** [comment]
@pcastelog Thanks for the report, can you come up with a fix?

**Comment by pcastelog** [comment]
@kwin I will update soon with the fix

**Comment by pcastelog** [comment]
@kwin I will update soon with the fix

**Comment by pcastelog** [comment]
PR created #2533

**Comment by davidjgonzalez** [comment]
@pcastelog just out of curiosity, why are you obfuscating this path/url?

**Comment by pcastelog** [comment]
It was done a long time ago (with cq5) to add an extra layer of security to hide the actual path of the clientlib. It's a legacy code that at some point we need to remove. @davidjgonzalez
