### ISSUE TITLE
AEM -  Redirect Map Manager: "undefined" in info message

### ISSUE THREAD

**Issue by sandeepkusam** [Adobe-Consulting-Services/acs-aem-commons#2531]
<img width="960" alt="ACS" src="https://user-images.githubusercontent.com/79263841/109922554-870b0980-7ce3-11eb-9b51-fdc22ce3061b.PNG">
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______ AEM Version - 6.5 Service Pack : 6.5.6-1.0
* [x] ACS AEM Commons Version: 4.10.0
* [x] Reproducible on Latest? yes/no Yes

### Expected Behavior
RedirectMap entry count should be displayed instead of "undefined"

### Actual Behavior

RedirectMap entry count is showing as "undefined" instead of count, even though there RedirectMap entries.

### Steps to Reproduce

1)Open any redirect map page.
2)On the top right corner of the page success notification with "undefined" entries is visible - Should be the "count of the redirect entries"

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by aacgupta** [comment]
Is there any update on this ticket? We see that its still in "open" status.

**Comment by aacgupta** [comment]
Hi @sandeepkusam 
Can you please attach the screenshots and more information here to this ticket?

**Comment by sandeepkusam** [comment]
Hi @Adobe Consulting Services Team,

Is there any update on this Issue?
