### ISSUE TITLE
Add additional permissions for acs-commons-on-deploy-scripts-service service user

### ISSUE THREAD

**Issue by Ixbitz** [Adobe-Consulting-Services/acs-aem-commons#2532]
Hi, 

**What we ran into:**
While implementing some on-deploy scripts I ran into the issue that the standard service user ACS Commons uses (`acs-commons-on-deploy-scripts-service`) does not have any write permissions to the `/conf` folder.

**Our use case:**
We created new Context-Aware configurations  and wanted to populate some properties using an on-deploy script, but this was not possible without giving the `acs-commons-on-deploy-scripts-service` service user more rights via a Sling repoinit configuration. I'd rather have this service user have additional permissions.

Could a standard write permission for the `/conf` folder be added to this service user? Most appreciated!

**Comment by Ixbitz** [comment]
Closing this issue, as this was fixed in PR #2017

**Comment by davidjgonzalez** [comment]
@AntonValadzko i believe this was in error. Both missing rules should be added back but into the RepoInit scripts.
