### ISSUE TITLE
Clientlibs Versioning - MD5 Hash not getting generated

### ISSUE THREAD

**Issue by thediveshsoni** [Adobe-Consulting-Services/acs-aem-commons#2538]
Hi team,

We are using the versioned clientlibs of ACS commons. The rewriter config successfully appears under status-slingrewriter.

Configuration versioned-clientlib

Name : versioned-clientlibs
Content Types : [text/html]
Order : 1
Active : true
Valid : true
Process Error Response : true
Pipeline : 
    Generator : 
        htmlparser
    Transformers : 
        linkchecker
        versioned-clientlibs
    Serializer : 
        htmlwriter
Resource path: /apps/app-name/config/rewriter/versioned-clientlibs

However, MD5Hash is not getting appended to any of the CSS/JS files
<link rel="stylesheet" href="/etc.clientlibs/app-name/clientlibs/clientlib-base.css" type="text/css">

Enforce MD5 is also checked in the config manager under ACS AEM Commons - Versioned Clientlibs Transformer Factory.

AEM Version - 6.5.6
ACS Commons version - 4.3.2

Can you please let us know if there is way to get this # generated

Regards
Divesh

**Comment by thediveshsoni** [comment]
Added a logger as well to com.adobe.acs.commons.rewriter.impl.VersionedClientlibsTransformerFactory but it was empty

**Comment by davidjgonzalez** [comment]
I believe this is the same issue reported here: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2494
and fixed in 4.12.0/5.0.0

If the new versions don't resolve, can you re-open this issue? Thanks!
