### ISSUE TITLE
Unable to consume "VanityUrlAdjuster" in custom application

### ISSUE THREAD

**Issue by abhinavsinha347** [Adobe-Consulting-Services/acs-aem-commons#2542]
## Required Information

* AEM version : 6.5.7
* ACS Commons version: 4.11.2
*  Reproducible on Latest? yes

### Expected Behavior

Able to consume VanityUrlAdjuster Interface to provide custom implementations as per the documentation.

### Actual Behavior
Unable to consume the Interface as its not exported.

### Steps to Reproduce

Create a service class in custom application and write an implementation of VanityUrlAdjuster. Deploy the bundle to AEM and check bundle status.

<img width="695" alt="Screenshot 2021-03-11 at 12 06 29" src="https://user-images.githubusercontent.com/80462036/110786679-51769b00-8264-11eb-9f7b-7e8def75f51c.png">

**Comment by abhinavsinha347** [comment]
@davidjgonzalez Can you please review this bug ? Its broken in this PR
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2351

**Comment by davidjgonzalez** [comment]
Fixed in v4.12.0

**Comment by davidjgonzalez** [comment]
Yesterday, should be available on maven central now. Just didn't have time to update the website!

**Comment by abhinavsinha347** [comment]
Thanks @davidjgonzalez , can someone please test this as the custom Impl class that i have written is not being called. And this is a very critical feature for our go live, unless a fix is required and we end up rewriting VanityURLServiceImpl in our code base.

Appreciate your help here :)

**Comment by davidjgonzalez** [comment]
Sorry, don't understand the ask. Only you has your customer class to test..?

**Comment by abhinavsinha347** [comment]
So, i was trying to write the Impl for Adjuster class, but for some reason in "VanityURLServiceImpl" the vanityUrlAdjuster variable is always null. May be i am doing something wrong or something wrong on ACS commons end.

**Comment by davidjgonzalez** [comment]
Have you tried compiling against 4.12.0 w the VanityUrlAdjuster interface in the updated (Public) location?

**Comment by abhinavsinha347** [comment]
@davidjgonzalez https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2548, need to make VanityUrlAdjuster volatile for dynamic references

**Comment by kwin** [comment]
@abhinavsinha347 This is not true for static reference like  https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/e049f0c091bbebfd074793e8490d1205394ba6d9/bundle/src/main/java/com/adobe/acs/commons/wcm/vanity/impl/VanityURLServiceImpl.java#L56.

**Comment by kwin** [comment]
@abhinavsinha347 Can you come up with a PR?

**Comment by abhinavsinha347** [comment]
@kwin sure.

**Comment by kwin** [comment]
Should be fixed by https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2552.

**Comment by davidjgonzalez** [comment]
Fixed in 5.0.4 (released) - @abhinavsinha347 let me know if you need this back-ported to a 4.x.x line.

**Comment by abhinavsinha347** [comment]
@davidjgonzalez , i can upgrade to 5.0.4 version that should be fine.
