### ISSUE TITLE
[Feature Review] Google Plus - Authentication using OAuth

### ISSUE THREAD

**Issue by varunstech** [Adobe-Consulting-Services/acs-aem-commons#255]
The functionality will enable users to authenticate using Google Plus account (just like users currently able to authenticate using Facebook and Twitter).

API to use - https://developers.google.com/+/api/oauth

This will involve
1. Component to have the login button
2. Configuration of Google Plus from Cloud services
3. On Authentication have a Authentication handler to authenticate user into AEM and save the user's details into AEM.

Future 
- This can be expanded in future to include bring some information into the client context (just like OOTB Facebook functoinality.)

**Comment by epsilon-sajain** [comment]
we have configured logging through google plus but client context does not load the profile .
Please let me know what should be done to enable the same as we have to  implement personalized content.
