### ISSUE TITLE
Compatibility for 5.x unclear

### ISSUE THREAD

**Issue by wimsymons** [Adobe-Consulting-Services/acs-aem-commons#2553]
Now that release 5.0.2 is out, it is a little confusing which version I should use.

Last version listed on https://adobe-consulting-services.github.io/acs-aem-commons/pages/compatibility.html is 4.7.0+.

Is 5.0.0+ targeted only for AEMaaCS or is it still compatible with AEM 6.5?

Thanks for clarifying this.

Kind regards

Wim

**Comment by kwin** [comment]
This duplicates https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/issues/207.
