### ISSUE TITLE
5.0.4 not available on Maven Central

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#2555]
I don't see version 5.0.4 at https://repo1.maven.org/maven2/com/adobe/acs/acs-aem-commons-bundle/

Was something not working with publishing?

**Comment by davidjgonzalez** [comment]
@kwin Nope. Released this on the side - had to jump on other stuff so didn't get around to releasing it till just now. It's up there now!
