### ISSUE TITLE
Asset Packager Documentation | Misleading instructions

### ISSUE THREAD

**Issue by brigham57** [Adobe-Consulting-Services/acs-aem-commons#2556]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.4 SP8 | AEM 6.5 SP5
* [x] ACS AEM Commons Version: 4.6.0 | 5.0.2
* [x] Reproducible on Latest? yes

### Expected Behavior
N/A

### Actual Behavior
N/A

### Steps to Reproduce
Documentation states:
- Log in to AEM Author
- Navigate to the Classic UI Tools Console (from the Touch UI, this is Tools:Operations:Configuration)
- Under the packagers folder, create a new Page of Template type “Asset Packager”

The actual folder that you need to create the page under is:
Tools >> acs-commons >> Content Packagers

### Links
- https://adobe-consulting-services.github.io/acs-aem-commons/features/packagers/asset-packager/index.html
- http://localhost:4502/miscadmin#/etc/acs-commons/packagers

**Comment by davidjgonzalez** [comment]
Corrected it!  Thanks!
