### ISSUE TITLE
Versioned ClientLibs Transformer does not work with script/link modules

### ISSUE THREAD

**Issue by arthurcavallari** [Adobe-Consulting-Services/acs-aem-commons#2560]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.1
* [ ] ACS AEM Commons Version: latest/any
* [ ] Reproducible on Latest? yes

### Expected Behavior

The versioned clientlibs transformer should add a hash to script/link tags even if `<script type="module" src="..."/>` or `<link rel="modulepreload" href="..."/>`

### Actual Behavior

These tags are excluded because of `SaxElementUtils.isCss` and `SaxElementUtils.isJavaScript`, these methods do not accept `<script type="module" src="..."/>` or `<link rel="modulepreload" href="..."/>`

### Links

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/84fcdd4bc66b020ac7c1a03134d1d7f474ce10e5/bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java#L198

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/84fcdd4bc66b020ac7c1a03134d1d7f474ce10e5/bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java#L202

_Links to related assets, e.g. content packages containing test components_
![image](https://user-images.githubusercontent.com/2404438/112254476-c8745080-8cb4-11eb-9f8c-68c38bc55524.png)

![image](https://user-images.githubusercontent.com/2404438/112254989-90b9d880-8cb5-11eb-991d-18c7f58f762f.png)

**Comment by makro2400** [comment]
We are facing similar issue. We want to preload some scripts, we tried to add type to link element, but like it was said, the check done in `isJavaScript` only checks script tags, while it should be also checking link elements if they have proper type set.

**Comment by jamesg1** [comment]
I am trying to use JS modules with AEM too and we've hit this issue - We are importing javascript via client lib modules `<script type="module" src="..."/>`.

**Comment by jamesg1** [comment]
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2691#issue-727533228 Added the fix to the library to enable support of this. @makro2400 @arthurcavallari

**Comment by arthurcavallari** [comment]
Fixed by https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2691#issue-727533228

Thanks @jamesg1
