### ISSUE TITLE
"Object result" parameter is not used leading to "NOT_ACTIVATED" in replication status column when downloading page report content

### ISSUE THREAD

**Issue by insideaem** [Adobe-Consulting-Services/acs-aem-commons#2565]
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/84fcdd4bc66b020ac7c1a03134d1d7f474ce10e5/bundle/src/main/java/com/adobe/acs/commons/reports/models/PageReplicationStatusModel.java#L103

**Comment by henrykuijpers** [comment]
@insideaem  see also #2509
