### ISSUE TITLE
[Feature] Add a "notes" field to the Redirect Manager

### ISSUE THREAD

**Issue by paul-bjorkstrand** [Adobe-Consulting-Services/acs-aem-commons#2571]
As a Redirect Manager user, I would like the ability to optionally add a plaintext "Note" with each Redirect Manager item.

The redirect manager currently supports four fields:
* Source Path
* Target Path
* Status Code
* Redirect Until (Optional)

This change would add an additional column to the Redirect Manager list and add an optional text area field to the create/edit UI views. In addition, the import/export functionality should include this field as well.

Having this field would greatly improve how redirects are tracked and maintained, potentially allowing us to reduce the total number of redirects that we have in our configuration. As an analogy, it is roughly equivalent to a comment near a redirect inside an Apache HTTPD conf file.

This would be a good first issue for anyone who is looking to get started contributing to this project.

**Comment by YegorKozlov** [comment]
Thanks for this feature request. Adding a Note field makes sense. The patch is coming soon and will be included in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2564

**Comment by YegorKozlov** [comment]
The feature is included in PR https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2564

There is a new input, a new column in the html table and a new column in the Export/Import Spreadsheet.
![image](https://user-images.githubusercontent.com/2543854/115401103-b2de4200-a1f2-11eb-88bf-c54baf9697a4.png)

**Comment by YegorKozlov** [comment]
The change was merged into master

**Comment by paul-bjorkstrand** [comment]
I saw! Thank you very much for including this in your other (large) PR. I have a customer eager to move to this from their existing redirect management system, and this was one of the desired features.

Closing.
