### ISSUE TITLE
Named Transform Image Servlet: Image transformer not working for .SVG image formats

### ISSUE THREAD

**Issue by dillibabujata** [Adobe-Consulting-Services/acs-aem-commons#2574]
AEM Version : 6.3.0
ACS AEM Commons Version: 4.0.0
Reproducible on Latest? Yes

Expected Behavior :
Image transform should work for .svg image file formats.

Actual Behavior :
Image transformer is not working when applied for .svg image file formats.

Steps to Reproduce :
1. We have uploaded .svg image into AEM Dam and image is 'Tersco-02.svg'.

2. Below is the OSGI configuration for Named Image Transformer Factory and below are OSGI preoperties.
     Transformer Name : psimg-1280
     Image Transformers : resize:width=1280

3. Image transformer is not working with HTTP GET Request - http://localhost:4502/content/dam/transformer/Tersco-02.svg.transform/psimg-1280/image.svg

Thanks in advance.

**Comment by davidjgonzalez** [comment]
@dillibabujata this feature only works w/ supported raster images due to the underlying java image library. SVGs are not supported; the inly way this would work is if you had a SVG DAM asset and it has raster (png/jpeg) web rendition.
