### ISSUE TITLE
Improvement in Log messages for EtagMessageDigestServletFilter.java

### ISSUE THREAD

**Issue by arunpatidar02** [Adobe-Consulting-Services/acs-aem-commons#2580]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.5
* [x] ACS AEM Commons Version: 4.4.2
* [x] Reproducible on Latest? yes/no yes

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._
When page X is requested and AEM internal redirects the user to Page Y from custom Sling Filter then there should are error message logged for Etag "_**Can not send ETag header because response is already committed, try to give this filter a higher ranking!**_" with log.error.

### Actual Behavior

When page X is requested and AEM internal redirects the user to Page Y from custom Sling Filter then there should not be error message logged for Etag "_**Can not send ETag header because response is already committed, try to give this filter a higher ranking!**_", can be logged as a warning.

### Steps to Reproduce
1. Create a custom sling filter with a lower ranking than https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/etag/impl/EtagMessageDigestServletFilter.java to redirect the user to another page
2. Access a page that fulfills custom filter criteria.
3. Check the error logs.

### Links
Error log is defined at
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/etag/impl/EtagMessageDigestServletFilter.java#L171

**Comment by kwin** [comment]
@arunpatidar02 Can you come up with a PR?

**Comment by arunpatidar02** [comment]
> @arunpatidar02 Can you come up with a PR?

@kwin it seems I don't have write access, could you please help here?

**Comment by davidjgonzalez** [comment]
@arunpatidar02 you would want to make the change as a PR, push it to your Fork, and then PR it from your For the ACS AEM Commons master branch. (all changes must go through PR process)
