### ISSUE TITLE
feature review -  Key Management Service

### ISSUE THREAD

**Issue by sumantapakira** [Adobe-Consulting-Services/acs-aem-commons#2586]
## Required Information

In many of AEM projects, we use secret key/client key/passwords for 3rd party system integration. All this keys are kept as OSGI config and those are available as part of code repository. As a result many unauthorized people can read those secret key. 

### Expected Behavior
I would like to secure the secret key/client key/passwords. And for this I would like to propose a solution called Key Management System within AEM. 
For this Admin will have an interface where he/she can maintain key and value pair, and there he/she will have possibility to encrypt the value using AEM inbuilt key or by using customer key.  
And then within the Active method of OSGI service, write code to decrypt.  

What do you think?

Thanks,
Sumanta Pakira

**Comment by paul-bjorkstrand** [comment]
@sumantapakira , if you are using AEM, there is a very similar OOTB feature: [Crypto Support ](https://experienceleague.adobe.com/docs/experience-manager-64/administering/security/encryption-support-for-configuration-properties.html?lang=en)

Bonus: if you inject the property into its service, [it will be automatically decrypted when injected into a service](https://experienceleague.adobe.com/docs/experience-manager-64/administering/security/encryption-support-for-configuration-properties.html?lang=en#decryption-support).

**Comment by sumantapakira** [comment]
@paul-bjorkstrand  Thanks for your feedback. In OOTB way the text will be encrypted only using AEM inbuilt key but is it also possible to use customer's own key? And another challenge we faced in our project to see all the lists of  keys which are protected. 
Additionally one advanced feature can also be possible to use Asymmetric Key Support.

**Comment by paul-bjorkstrand** [comment]
Asymmetric key? No, I don't believe so. Custom key? Most likely, yes! You would just need to know the format & encryption method, to generate a key. I did a quick google search, but did not find how to generate the key, but there are some [examples][example 1] on how [to copy][example 2] from [one instance to another][example 3]. Once you find how to generate a key from scratch, you can use one of the methods to change the password.

The most key-sharing you (most likely) want to do is per-environment (dev, stage, prod, etc). The only downside that I can think of this method is in the case of multitenancy - separate tenants can read other tenant's secrets (if they have read rights to those paths), and use crypto support to decrypt the secrets.

If you had a concern about multitenancy, then it might make sense to have some kind of custom, tenant specific (possibly via CAConfig) key system. If not, I recommend trying crypto support first. It may be sufficient enough for your use case and save you a heck of a lot of development and/or waiting for a feature to be developed.

[example 1]: https://www.argildx.com/technology/crypto-support-aem/
[example 2]: https://www.nextrow.com/blog/adobe-experience-manager/crypto-support-in-aem-part-2
[example 3]: https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/aem-6-5-crypto-support/qaq-p/328426

**Comment by justinedelson** [comment]
It sounds like what is being proposed here is less of a Key Management System than a Secret Management System. Leaving aside the issue that AEM already provides secret management OOTB, it seems unnecessary to build yet another secret management system when there are existing, battle-hardened solutions in this space.

I would recommend closing this issue.
