### ISSUE TITLE
Reverse Replication of User Resources

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#26]
### The Problem

As AEM moves from WCM to WebApp, the need to move around User profile information becomes more common. Current "OOTB" implementation for this requires various Launchers and dev-based "touch" of resource for replication.
### The Proposal
- Creating disabled Launchers for RR'ing profile resources - OR - creating an event listener (that could be configured for any path i supposed) that handles queuing of resources for Reverse Replication. 
- Creating a ReplicationUtil (or Helper) that can be used to "touch" a resource to trigger it for RR (setting the lastMod, lastModBy and cq:distribute properties).
### Concerns

RR has many nuances and pitfalls. We would need to be very careful we dont create a faulty/broken abstraction.

**Comment by rohanraj14** [comment]
Hi David,

What happened to this request. Can you please let me know if there is a utility already there? If not is there a way we can achieve reverse replication of users? Or, send me a documentation on it.

Rohan.

**Comment by davidjgonzalez** [comment]
Hi,
Nothing ever came of this ... AFIAK the best resource for this is at: http://www.wemblog.com/2011/10/how-to-set-up-usergroupprofile-reverse.html
