### ISSUE TITLE
ACS AEM Documentation says it supports AEM Cloud with 5.0.4 version , but it fails to install on AEM Cloud

### ISSUE THREAD

**Issue by Yogiraj24** [Adobe-Consulting-Services/acs-aem-commons#2602]
AEM Cloud 
ACS AEM Commons Version : 5.0.4
Reproducible on Latest? yes

### Expected Behavior
ACS AEM Documentation says it supports AEM Cloud with 5.0.4 version .

### Actual Behavior

ACS AEM Documentation says it supports AEM Cloud with 5.0.4 version , but it fails to install on AEM Cloud . 

### Steps to Reproduce

Download ACS AEM Commons 5.0.4 version
Install it on AEM Cloud Author 
It fails with below error message 

### Links

_Links to related assets, e.g. content packages containing test components_
https://adobe-consulting-services.github.io/acs-aem-commons/pages/compatibility.html
![asa](https://user-images.githubusercontent.com/6847078/121319133-8957b200-c929-11eb-92cb-ef2f9b79f351.PNG)

**Comment by kwin** [comment]
Installing to AEMaaCS works differently: https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/deploying/overview.html?lang=en#including-third-party

**Comment by Yogiraj24** [comment]
It worked well , thanks @kwin !!
