### ISSUE TITLE
ReplicatorQueue should not implement the Replicator interface

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#2614]
The ReplicatorQueue should not implement the Replicator interface.

See https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2604#issuecomment-864406901, thanks to @YegorKozlov for spotting it.

**Comment by kwin** [comment]
Do we really want to track each required change for #2604 individually? IMHO for consumers it just makes a difference if all four underlying issues are fixed.

**Comment by joerghoh** [comment]
@kwin I think that we cannot "fix" all problems of #2604 that easy as this one.
