### ISSUE TITLE
Build failure because of ACS-AEM-COMMONS issue

### ISSUE THREAD

**Issue by msah123** [Adobe-Consulting-Services/acs-aem-commons#2616]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______6.5.5
* [ ] ACS AEM Commons Version: _____5.0.4
* [ ] Reproducible on Latest? yes/no yes

### Expected Behavior
Build should not fail
_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._

### Steps to Reproduce

The product interface com.day.cq.replication.Replicator annotated with @ProviderType should not be implemented by custom code. Detected in com.adobe.acs.commons.mcp.impl.processes.renovator.ReplicatorQueue contained in /apps/acs-commons/install/acs-aem-commons-bundle-4.6.0.jar.

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by kwin** [comment]
Duplicates #2604
