### ISSUE TITLE
Generic Lists throw NPE in AEM CS

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2617]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM as a Cloud Service
* [X] ACS AEM Commons Version: 5.0.4
* [X] Reproducible on Latest? yes/no

### Expected Behavior

No NPE thrown.

### Actual Behavior

NPE thrown. This is due to missing ResourceMetadata property `sling.resolutionPath` that was chagned to be required 

### Links

Adobe ticket reporting this issue: GRANITE-35082

**Comment by kwin** [comment]
PR at https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2618.

**Comment by andyshreve** [comment]
Please do not close this issue. I am still waiting for this issue to be fixed by the now-stalled pull request at:

- https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2618

**Comment by davidjgonzalez** [comment]
Fixed in 5.3.4
