### ISSUE TITLE
REDIRECT MAP IMPORT FUNCTIONALITY ISSUE IN 5.0.4 and 5.0.5

### ISSUE THREAD

**Issue by Sagarmcapgemini12** [Adobe-Consulting-Services/acs-aem-commons#2620]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: ____ AEM aaCS___
* [ ] ACS AEM Commons Version: _5.0.4 and 5.0.5____
* [ ] Reproducible on Latest? yes/no : yes

### Expected Behavior
When we use a xlsx sheet with src, target and status code value we should be able to import those configurations  and a node should be created

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._
I have exported a file and have added few extra rules, but when i click on up load it stays idle and in logs i can see a null pointer exception
POST /apps/acs-commons/content/redirect-manager/_jcr_content.import.html HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.NullPointerException: Value should not be null (key = note)

The excel sheet is same as which was imported

This happens when i export a spread sheet which has 2 rules and when i add 2 more rules to that(4 in total) it throws null pointer exception

### Actual Behavior

When we use a xlsx sheet with src, target and status code value we should be able to import those configurations  and a node should be created

### Steps to Reproduce
create one configuration and export it for the same file downloaded add another configuration with proper/content path at source and destination and enter status code as 301/302 and try to import the newly saved file again in import tab

### Links

_Links to related assets, e.g. content packages containing test components_
https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-manager/index.html
added the screen shot in comments section

**Comment by YegorKozlov** [comment]
Can you please attach a sample XLSX file that causes the trouble?

**Comment by Sagarmcapgemini12** [comment]
[new.xlsx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/6732813/new.xlsx)
Steps to replicate
just create 1 fresh new configuration export it
once the file is downloaded add two extra configurations and save
try to import the same file now
[error.log](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/6732815/error.log)
I have attached the  logs as well

**Comment by YegorKozlov** [comment]
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2625

**Comment by Sagarmcapgemini12** [comment]
@YegorKozlov  any ETA when this will be available for use??
and also any  confirmed release date for 5.0.5 version

**Comment by YegorKozlov** [comment]
5.0.5 is planned, but there is no ETA yet.
