### ISSUE TITLE
Automatically deploy SNAPSHOTs

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#2623]
With GitHub actions it is easy to automatically deploy SNAPSHOTs of the master branch to OSSRH with every build. That way testing of not yet released versions is way easier.

**Comment by HitmanInWis** [comment]
This would also be very nice for project teams that contribute features to ACS AEM Commons and need to deploy those features to non-production environments prior to Adobe cutting an official release of the library.
