### ISSUE TITLE
Coveralls Github action only works when PR is local to acs/acs-aem-commons repo

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2629]
It appears that the updated to Coveralls Github integration only works if the PR is made from a branch on: `Adobe-Consulting-Services/acs-aem-commons`

If the PR is made from a fork's branch the coveralls submission fails.

I believe this is because `steps.refs.outputs.branch_name` evaluates to a detached state (uuid/hash) when the PR is from a fork - whereas when its a "local" PR, it evaluates to the proper named branch.

steps.refs.outputs.branch_name

/cc @kwin

**Comment by kwin** [comment]
Secrets are not exposed to forks: https://github.community/t/make-secrets-available-to-builds-of-forks/16166/36. Therefore the `repo.token` parameter is not set correctly on forked PRs. I don't think there a simple solution: https://github.com/codecov/codecov-action/issues/29.
How did that work with Travis?

**Comment by kwin** [comment]
Actually there is now a simple solution: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/. I am gonna provide a PR.

**Comment by kwin** [comment]
The event `pull_request_target` won't work. But Coveralls supports tokenless authentication according to https://github.com/codecov/codecov-action/issues/29#issuecomment-595288709.

**Comment by kwin** [comment]
I haven't figured out a way to parameterize the Maven plugin correctly: https://github.com/trautonen/coveralls-maven-plugin/issues/136#issuecomment-871992626. Given the reasons mentioned in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2611#issuecomment-863570673 and also this issue I would strongly recommend reconsidering switching to sonarcloud.io as that integrates nicely with Github actions.

**Comment by kwin** [comment]
Alternatively we can use https://about.codecov.io/pricing/ (which is free for OSS). That is pretty straightforward to integrate, compare with https://github.com/codecov/example-java and doesn't require a token either (i.e. works also for PRs from forked repos).
@davidjgonzalez Please decide which solution is more suitable.

**Comment by davidjgonzalez** [comment]
Codecov looks good! It's integrated into master now.
