### ISSUE TITLE
Redirect Manager: Default CaConfig Configuration not showing up

### ISSUE THREAD

**Issue by YegorKozlov** [Adobe-Consulting-Services/acs-aem-commons#2645]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: __6.5_____
* [ ] ACS AEM Commons Version: __5.0.7-SNAPSHOT___
* [ ] Reproducible on Latest? yes

### Expected Behavior

The default CaConfig configuration is created by a repo-init script and should show up .

### Actual Behavior

![image](https://user-images.githubusercontent.com/2543854/125475385-c0c4f042-d931-4b94-b9a5-890d67e0b906.png)

It's a regression caused by #2589 
The repo-init script used to set sling:resourceType and it was commented out:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/7c358e8ae6451e871823111d1439973f5190a166/ui.apps/src/main/content/jcr_root/apps/acs-commons/config/org.apache.sling.jcr.repoinit.RepositoryInitializer-aem-cs.config#L12

The fix is coming

**Comment by kwin** [comment]
@YegorKozlov Is this really fixed? I don't see any merged commit related to this in the master branch.

**Comment by YegorKozlov** [comment]
@kwin  It was a false alarm. On my local I only deployed the ui.apps  package while the CaConfig configuration is created by ui.content.
