### ISSUE TITLE
Redirect Map Manager Not visible with version 5.0.6

### ISSUE THREAD

**Issue by PrathameshMohapatra** [Adobe-Consulting-Services/acs-aem-commons#2666]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.9
* [x] ACS AEM Commons Version: 5.0.6
* [x] Reproducible on Latest? yes

### Expected Behavior

The redirect map manager box is not visible now when we upgraded from 4.3.2 to 5.0.6

### Actual Behavior

The redirect feature works but is not visible which redirect to the miscadmin page to author new redirect pages

### Steps to Reproduce

If we add the latest version the tile is not visible.

### Links

![image](https://user-images.githubusercontent.com/88785563/129046663-58302cd0-a881-490b-ac01-b062caf06433.png)

**Comment by kwin** [comment]
Look at https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-map-manager/index.html:

> This feature is not AEM as a Cloud Service compatible; starting with the release 4.6.2 this feature is disabled on this platform (including the SDK).

Please rather use https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-manager/index.html

**Comment by PrathameshMohapatra** [comment]
Hi @kwin 
We are using this feature for our AMS instance 6.5.9 (not cloudservice  instance) with the latest 5.0.6 version.

**Comment by kwin** [comment]
@YegorKozlov You removed that option in https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/4f1ae0689d386bd1c75be0f0ee40cccf1a65d5fa#diff-83a1efc626d4527ffb0a227b30e92c19dfb49bb5e202c5567ae4d7f939538ec4. Please restore the old tile, as it is still fully functional for AEM 6.5.x.

**Comment by kwin** [comment]
I wouldn't call it promote to have an entry point below Tools. Even for deprecated features we should have tiles, as otherwise it is hard to use them.

**Comment by YegorKozlov** [comment]
> I wouldn't call it promote to have an entry point below Tools -> ACS AEM Commons. Even for deprecated features we should have tiles, as otherwise it is hard to use them.

Ok. The PR is coming.

**Comment by kwin** [comment]
@PrathameshMohapatra As workaround you can still find it in Classic UI: `/miscadmin#/etc/acs-commons/redirect-maps`. Only the Touch UI tile for the quick entry towards that repo location is missing.

**Comment by YegorKozlov** [comment]
> HI @kwin thank you for looking at this, yes we are acessing it via miscadmin for now as a workaround and have informed the client till this is brought back. Any tentative version when we can expect this, so that we can keep them informed ?

The fix went into v5.10 which was released on Aug 31. Please try it out.
