### ISSUE TITLE
Renovator 5.0.6 Not Compatible with AEMaaCS

### ISSUE THREAD

**Issue by scottk0000** [Adobe-Consulting-Services/acs-aem-commons#2679]
## Required Information

* [ ] AEM Version 2021.8.5755.20210819T230729Z (ACS)
* [ ] ACS AEM Commons Version: 5.0.6
* [ ] Reproducible on Latest? yes

### Expected Behavior

Renovator to should be able to move pages on AEM CS from /content/pathA to /content/pathB.
This was working fine with ACS Commons 5.0.4.

### Actual Behavior

An exception is thrown
```
17.08.2021 15:13:54.900 *ERROR* [pool-19-thread-4] com.adobe.acs.commons.fam.impl.ActionManagerImpl Caught exception in task: Can not set final com.day.cq.replication.Replicator field com.day.cq.wcm.core.impl.page.PageManagerImpl.replicator to com.adobe.acs.commons.mcp.impl.processes.renovator.ReplicatorQueue
java.lang.IllegalArgumentException: Can not set final com.day.cq.replication.Replicator field com.day.cq.wcm.core.impl.page.PageManagerImpl.replicator to com.adobe.acs.commons.mcp.impl.processes.renovator.ReplicatorQueue
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83)
	at java.base/java.lang.reflect.Field.set(Field.java:780)
	at org.apache.commons.lang.reflect.FieldUtils.writeField(FieldUtils.java:523) [org.apache.commons.lang:2.6.0]
	at org.apache.commons.lang.reflect.FieldUtils.writeField(FieldUtils.java:500) [org.apache.commons.lang:2.6.0]
	at com.adobe.acs.commons.mcp.impl.processes.renovator.MovingPage.move(MovingPage.java:74) [com.adobe.acs.acs-aem-commons-bundle:5.0.6]
	at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.lambda$null$36(Renovator.java:689) [com.adobe.acs.acs-aem-commons-bundle:5.0.6]
	at com.adobe.acs.commons.mcp.impl.processes.renovator.MovingNode.visit(MovingNode.java:217) [com.adobe.acs.acs-aem-commons-bundle:5.0.6]
	at com.adobe.acs.commons.mcp.impl.processes.renovator.MovingNode.visit(MovingNode.java:195) [com.adobe.acs.acs-aem-commons-bundle:5.0.6]
	at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.lambda$null$37(Renovator.java:685) [com.adobe.acs.acs-aem-commons-bundle:5.0.6]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2067)
	at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.lambda$moveTree$38(Renovator.java:684) [com.adobe.acs.acs-aem-commons-bundle:5.0.6]
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:200) [com.adobe.acs.acs-aem-commons-bundle:5.0.6]
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runActionAndLogErrors(ActionManagerImpl.java:167) [com.adobe.acs.acs-aem-commons-bundle:5.0.6]
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$deferredWithResolver$0(ActionManagerImpl.java:159) [com.adobe.acs.acs-aem-commons-bundle:5.0.6]
	at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:91) [com.adobe.acs.acs-aem-commons-bundle:5.0.6]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to Reproduce

Set up a new Renovator process.  I tried many different combinations of check boxes and they all failed.
Set Publish to None
Uncheck everything except Detailed report

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by kwin** [comment]
@scottk0000 Which Java version do you use?

**Comment by kwin** [comment]
I am not sure how this was ever supposed to work, as the field `replicator` in `PageManagerImpl` has always been final (back to AEM 6.1) but the final modifier is not removed in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/bb4ddd4431d7c1ee2106c7ed5174c8c5be4d7d18/bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/renovator/MovingPage.java#L74. @badvision As you contributed the code initially, do you know under which circumstances (JDK version, AEM version) this ever worked?

**Comment by YegorKozlov** [comment]
Does AEMaaCS run with a custom Java Security manager preventing this?

**Comment by kwin** [comment]
I can reproduce easily without a security manager. As outlined above this is due to the fact that reflection is used to set the final field without removing the final modifier.

**Comment by badvision** [comment]
It was a hack, but a necessary one to intervene in the limited and inflexible way which page manager works.  The idea is to replace the replication agent with a stub so the replication events can be reprocessed in different ways.  If anyone wants to rewrite it be my guest.

As for "was this tested", "did this work", etc.  Yes at the time it did and it saved my bacon a couple of times.  If it doesn't work anymore because the JVM has moved on from letting people use dirty tricks, well that means it's showing its age unfortunately.  I was trying to strike a balance between replicating a lot of internal system logic in PageManager, or just fooling it so it works "as is" but substituting the publishing behavior so we could skip the sling job queue and publish tens of thousands of assets, pages, etc without causing AEM to grind to a screeching halt.

Horribly unconventional?  Yes.  Was there another way?  Maybe, but the clock was ticking and this was probably the quickest road to something that worked before I had to move on to other things.  Could we do better?  I sure hope so.

**Comment by badvision** [comment]
If you're leery of other weird uses of reflection then I recommend reviewing the reflection hack I had to use for the spreadsheet code.  A service release (sp3 i think?  can't remember) upgraded the POI libraries to a breaking release, but inadvertently did not update the actual version of the POI library being included so everything we had with POI was breaking.  Since it had shipped I basically had to make something that would run for both old and new versions of POI without breaking during compilation or runtime.  A total mess but if we're trying to find ways to eliminate weird reflection hacks this would be the second use of it I'd love to retire some day.

**Comment by davidjgonzalez** [comment]
It looks there are 2 problems ...

1. The `PageManager` replicator field is final (so it cant be set)
2. Due to `@ProviderType` issues, `ReplicatorQueue implements Replicator` had the `implements Replicator` removed, so no we cant inject the `ReplicatorQueue` into the `Replicator` field (even when the `final` is removed using reflection) I think we need use a Java Proxy maybe to fake out OakPAL implements @ProviderType check.

@badvision how bad would it be to use the OOTB replicator in this? 

https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/208c807eedd2f5c8b061877dfd531395fa836649#diff-a85f69e4d1bcc8b569a49335f8036fe2838e8c381dcda5758c10986631eff5bd

**Comment by YegorKozlov** [comment]
It's strange that hacking the replicator field fails in the bundle, but works fine  AfromEM Fiddle. 
The snippet below changes the final field on my local AEM 6.5 running on JDK 11 without any exception:

```

<%@include file="/libs/foundation/global.jsp"%><%
%><%@page session="false" contentType="text/html; charset=utf-8" 
	pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.*,
    java.util.*,
    javax.jcr.*,
    java.lang.reflect.Field,
    com.day.cq.search.*,
    com.day.cq.wcm.api.*,
    com.day.cq.dam.api.*,
    org.apache.commons.lang.reflect.FieldUtils,
    com.day.cq.replication.Replicator"%><%

    try {
        PageManagerFactory pageManagerFactory = sling.getService(PageManagerFactory.class);
        PageManager manager = pageManagerFactory.getPageManager(resourceResolver);
        Replicator replicatorQueue = null;
        Field replicatorField = FieldUtils.getDeclaredField(manager.getClass(), "replicator", true);
        out.println(replicatorField.get(manager));
        FieldUtils.writeField(replicatorField, manager, replicatorQueue);
        
        out.println(replicatorField.get(manager));
    } catch (Throwable e){
        e.printStackTrace(response.getWriter());
    }

%>
```

**Comment by davidjgonzalez** [comment]
How is it writing the and object of type `ReplicatorQueue` to a field of type `Replicator` ....?!

**Comment by YegorKozlov** [comment]
> How is it writing the and object of type `ReplicatorQueue` to a field of type `Replicator` .... RQ uses to implement Replicator, but now its just some Java class, no?

the snippet mimics the MovingPage code:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/62d2e66a220061724f0b9cd677fa82f8e7b269e3/bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/renovator/MovingPage.java#L74

It looks  like removing "implements Replicator" in https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/208c807eedd2f5c8b061877dfd531395fa836649 broke it.

The following snippet sets a custom implementation of Replicator. Working fine.
```

<%@include file="/libs/foundation/global.jsp"%><%
%><%@page session="false" contentType="text/html; charset=utf-8" 
	pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.*,
    java.util.*,
    javax.jcr.*,
    java.lang.reflect.Field,
    com.day.cq.search.*,
    com.day.cq.wcm.api.*,
    com.day.cq.dam.api.*,
    org.apache.commons.lang.reflect.FieldUtils,
    com.day.cq.replication.*"%><%

    try {
        PageManagerFactory pageManagerFactory = sling.getService(PageManagerFactory.class);
        PageManager manager = pageManagerFactory.getPageManager(resourceResolver);
        Replicator replicatorQueue = new Replicator() {
            @Override
            public void replicate(Session session, ReplicationActionType type, String path) throws ReplicationException {
                
            }

            @Override
            public void replicate(Session session, ReplicationActionType type, String path, ReplicationOptions options) throws ReplicationException {

            }

            @Override
            public void replicate(Session session, ReplicationActionType type, String[] paths, ReplicationOptions options) throws ReplicationException {

            }

            @Override
            public void checkPermission(Session session, ReplicationActionType type, String path) throws ReplicationException {

            }

            @Override
            public ReplicationStatus getReplicationStatus(Session session, String path) {
                return null;
            }

            @Override
            public Iterator<String> getActivatedPaths(Session session, String path) throws ReplicationException {
                return null;
            }

            @Override
            public List<ReplicationContentFilter> createContentFilterChain(ReplicationAction action) {
                return null;
            }
        };
        Field replicatorField = FieldUtils.getDeclaredField(manager.getClass(), "replicator", true);
        out.println(replicatorField.get(manager));
        FieldUtils.writeField(replicatorField, manager, replicatorQueue);
        
        out.println(replicatorField.get(manager));
    } catch (Throwable e){
        e.printStackTrace(response.getWriter());
    }

%>
```
The snippet below sets PageManagerImpl#replicator  to a object that does not implement the Replicator interface. The type does not matter, I used String because ReplicatorQueue is not exported.
 This one reproduces the "can not set final " exception.

```

<%@include file="/libs/foundation/global.jsp"%><%
%><%@page session="false" contentType="text/html; charset=utf-8" 
	pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.*,
    java.util.*,
    javax.jcr.*,
    java.lang.reflect.Field,
    com.day.cq.search.*,
    com.day.cq.wcm.api.*,
    com.day.cq.dam.api.*,
    org.apache.commons.lang.reflect.FieldUtils,
    com.day.cq.replication.Replicator"%><%

    try {
        PageManagerFactory pageManagerFactory = sling.getService(PageManagerFactory.class);
        PageManager manager = pageManagerFactory.getPageManager(resourceResolver);
        String replicatorQueue = "null";
        Field replicatorField = FieldUtils.getDeclaredField(manager.getClass(), "replicator", true);
        out.println(replicatorField.get(manager));

        // will fail with 'java.lang.IllegalArgumentException: Can not set final ' exception
        FieldUtils.writeField(replicatorField, manager, replicatorQueue);
        
        out.println(replicatorField.get(manager));
    } catch (Throwable e){
        e.printStackTrace(response.getWriter());
    }

%>
```

**Comment by davidjgonzalez** [comment]
@YegorKozlov what if you use 

```
            replicatorField.setAccessible(true);

            Field modifiersField = Field.class.getDeclaredField("modifiers");
            modifiersField.setAccessible(true);
            modifiersField.setInt(replicatorField, replicatorField.getModifiers() & ~Modifier.FINAL);

            replicatorField.set(manager, replicatorQueue);
``` instead of 

`FieldUtils.writeField(replicatorField, manager, replicatorQueue);` ?

and order use FieldUtils.write... instead of the `replicatorField.set(manager, replicatorQueue);` ?

**Comment by YegorKozlov** [comment]
> @YegorKozlov what if you use
> 
> ```
> replicatorField.setAccessible(true);
> 
> Field modifiersField = Field.class.getDeclaredField("modifiers");
> modifiersField.setAccessible(true);
> modifiersField.setInt(replicatorField, replicatorField.getModifiers() & ~Modifier.FINAL);
> 
> replicatorField.set(manager, replicatorQueue);
> ```
> 
> instead of
> 
> `FieldUtils.writeField(replicatorField, manager, replicatorQueue);`
> 
> and order use `FieldUtils.write...` instead of the `replicatorField.set(manager, replicatorQueue);` ?

that didn't work either

**Comment by YegorKozlov** [comment]
Eureka! If we cannot implement Replicator and other @ProviderType interfaces in the code, we can construct them using Java Reflection. `java.lang.reflect.Proxy` to the rescue!
Something like this:

```
        Replicator replicatorWrapper = (Replicator) Proxy.newProxyInstance(
                Replicator.class.getClassLoader(),
                new Class[]{Replicator.class},
                new InvocationHandler() {
                    @Override
                    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
                        if("replicate".equals(method.getName()) && args.length == 4){
                            replicatorQueue.replicate((Session)args[0], (ReplicationActionType)args[1], (String)args[2], (ReplicationOptions)args[3]);
                        }
                        return null;
                    }
                });
        Field replicatorField = FieldUtils.getDeclaredField(pageManager.getClass(), "replicator", true);
        FieldUtils.writeField(replicatorField, pageManager, replicatorWrapper, true);
```

this should do the trick and keep Cloud Manager Sonar analysis  happy.

**Comment by badvision** [comment]
If you replicate 50k things asynchrousnly then you create a logjam that
kills the product.   How bad would it be to start that many workflows?
Same problem...

**Comment by davidjgonzalez** [comment]
@badvision  well - non-transient WF would be worse since there is even more overheard in managing those. :)

wasnt sure if product had added any efficiencies for this use-case since you made it either. Sounds like at scale we still need the RQ.
