### ISSUE TITLE
Environment Indicator is showing on AEMCloud PROD even though it is not configured 

### ISSUE THREAD

**Issue by Yogiraj24** [Adobe-Consulting-Services/acs-aem-commons#2690]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc:  AEM as a Cloud
* [ ] ACS AEM Commons Version:  5.0.10
* [ ] Reproducible on Latest? yes

### Expected Behavior

Environment indicator shouldn't be showing if it is not configured in runmode 

### Actual Behavior

The environment indicator configuration under /config runmode is showing on prod even though it is not configured under /config.prod

**Comment by josephrignanese** [comment]
Configurations under `config` apply to all runmodes, unless there is a configuration for a more specific runmode.

In this case, `config` will apply to instances using the `prod` runmode the same way as it would for other runmodes.

If you wanted to limit the configuration to specific runmodes, you should create the configuration in a more specific folder, e.g. `config.dev`.
