### ISSUE TITLE
Parsys Limiter is counting items in clipboard even on insert/drop action

### ISSUE THREAD

**Issue by dratzenboeck-ibm** [Adobe-Consulting-Services/acs-aem-commons#2694]
## Required Information

*  AEM Version: 6.5 SP 8
*  ACS AEM Commons Version: 5.0.6
* Reproducible on Latest? yes

### Expected Behavior

If I have more items in clipboard than allowed in the parsys I should still be able to insert single components into the parsys. 
E.g. If I have 3 items in clipboard and there is space for 1 component left in the parsys, I should be able to insert/drop a single component with the insert functionality. 

### Actual Behavior

Logic is always checking the clipboard, even if I am inserting / dropping a single component. That's why I get the limit error when having multiple items in the clipboard, even if there is space left in the parsys. 

### Steps to Reproduce

- Activate parsys limiter https://adobe-consulting-services.github.io/acs-aem-commons/features/parsys-limiter/index.html and set the acsComponentsLimit to 3, for example. 
- Add 2 components to the parsys
- Copy these 2 components with multiselect so that they are added to the clipboard
- Try to insert another component into the parsys
- **It does not work, because the limiter is counting the 2 items in the clipboard**

### Links

The source of the issue should be in this line https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/d71a9a9d538854bc9f34efc776b34bd299728336/ui.apps/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/configure-limit-parsys/touchui-limit-parsys.js#L128 where it is always checking the clipboard, while it should only check it if the action was the paste action.

**Comment by kwin** [comment]
@dratzenboeck-ibm Thanks for the bug report. Can you come up with a PR?

**Comment by dratzenboeck-ibm** [comment]
PR is open
