### ISSUE TITLE
REDIRECT MAP ISSUE IN EDITOR MODE

### ISSUE THREAD

**Issue by Sagarmcapgemini12** [Adobe-Consulting-Services/acs-aem-commons#2707]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: ______AEMaaCS_
* [ ] ACS AEM Commons Version: __5.0.12___
* [ ] Reproducible on Latest? yes/no yes

### Expected Behavior

when we enter a redirect rule the page should get redirected only in wcmdisabled mode in author
But even in the editor mode the pages are redirecting

### Actual Behavior

when we create a configuration for RMM with 301 or 302 redirect the pages shoould only redirect in wcm disabled mode in author

### Steps to Reproduce

1)open acs commons manage redirects tools
2) click on conf global  add a redirect rule to a page
3)go to sites.html open the page in edit mode the page automatically redirects to new page
4) author is not able to edit the pages

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by davidjgonzalez** [comment]
@Sagarmcapgemini12  this condition appears to be handled...

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/redirects/filter/RedirectFilter.java#L500-L504

Can you set log level to TRACE for `com.adobe.acs.commons.redirects.filter` and post the results here?

**Comment by YegorKozlov** [comment]
I confirmed the issue and it smells like a bug.

`WCMMode.fromRequest(request)`  simply checks a request attribute set by WCMRequestFilter which is always null.
The logic to detect wcmmode  is handled in WCMRequestFilter  which is  executed _after_ RedirectFilter 


I'm in two minds how to fix it:

1. change the priority of RedirectFilter to run after WCMRequestFilter . Not ideal IMO as the code will depend on the priority of WCMRequestFilter 
2. detect wcmmode  in  RedirectFilter  explicitly. First check the request parameter and then the cookie:
```
      String mod = request.getParameter("wcmmode");
      if (mode == null) {
        Cookie c = request.getCookie("wcmmode");
        mode = (c == null) ? null : c.getValue();
      } 
```

**Comment by kwin** [comment]
I would prefer solution 1. The other alternative relies too much on implementation details.
