### ISSUE TITLE
MCP Content Fragment Import Not Working

### ISSUE THREAD

**Issue by AmoghDaryapurkar** [Adobe-Consulting-Services/acs-aem-commons#2712]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM SDK
* [x] ACS AEM Commons Version: 5.1.12
* [x] Reproducible on Latest? yes

### Expected Behavior

_No exception should occur during the upload process of the excel file and the content fragment should get created successfully_

### Actual Behavior

_The process is not able to create any content fragment and only creating folders_

### Steps to Reproduce

_Run the content fragment import process with required excel_

Note: Currently there is no explanation and sample present for this utility.

**Comment by YegorKozlov** [comment]
Please attach the input spreadsheet

**Comment by AmoghDaryapurkar** [comment]
@YegorKozlov Did you get a chance to check on this?

**Comment by AmoghDaryapurkar** [comment]
@YegorKozlov - Did you get a chance to check my use case above? I am just trying to avoid writing new importer on my own.

**Comment by YegorKozlov** [comment]
@AmoghDaryapurkar 

I was able to create your CFs with the following template and input spreadsheet:

[cf-events.xlsx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/7460954/cf-events.xlsx)
[cf-template-events.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/7460955/cf-template-events.zip)

http://localhost:4504/content/dam/vuse/events/bank-of-new-hampshire-pavilion-9.tidy.-1.json
```json
{
  "jcr:primaryType": "dam:Asset",
  "jcr:mixinTypes": [
    "mix:referenceable"
  ],
  "jcr:createdBy": "admin",
  "jcr:created": "Tue Nov 02 2021 16:17:08 GMT+0300",
  "jcr:uuid": "c10aec3d-0031-40b0-9b89-8acf13aa1024",
  "jcr:content": {
    "jcr:primaryType": "dam:AssetContent",
    "jcr:title": "Arizona - Alternative Rock",
    "jcr:lastModifiedBy": "admin",
    "contentFragment": true,
    "jcr:lastModified": "Tue Nov 02 2021 16:17:08 GMT+0300",
    "renditions": {
      "jcr:primaryType": "nt:folder",
      "jcr:createdBy": "admin",
      "jcr:created": "Tue Nov 02 2021 16:17:08 GMT+0300"
    },
    "related": {
      "jcr:primaryType": "nt:unstructured"
    },
    "metadata": {
      "jcr:primaryType": "nt:unstructured",
      "jcr:mixinTypes": [
        "cq:Taggable"
      ]
    },
    "data": {
      "jcr:primaryType": "nt:unstructured",
      "cq:model": "/conf/global/settings/dam/cfm/models/event",
      "master": {
        "jcr:primaryType": "nt:unstructured",
        "jcr:mixinTypes": [
          "cq:Taggable"
        ],
        "eventState@LastModified": "Tue Nov 02 2021 16:17:08 GMT+0300",
        "endDate@ContentType": "text/plain",
        "eventState@ContentType": "text/plain",
        "eventZipCode@ContentType": "text/plain",
        "eventAddress@LastModified": "Tue Nov 02 2021 16:17:08 GMT+0300",
        "eventCity@LastModified": "Tue Nov 02 2021 16:17:08 GMT+0300",
        "eventAddress": "400 W Washington St.",
        "eventCity": "Phoenix",
        "eventName": "Adult Con Amphitheatre",
        "allDayEvent@ContentType": "text/plain",
        "eventCity@ContentType": "text/plain",
        "allDayEvent@LastModified": "Tue Nov 02 2021 16:17:08 GMT+0300",
        "eventZipCode@LastModified": "Tue Nov 02 2021 16:17:08 GMT+0300",
        "eventZipCode": "85003",
        "eventName@ContentType": "text/plain",
        "eventState": "AZ",
        "eventName@LastModified": "Tue Nov 02 2021 16:17:08 GMT+0300",
        "startDate@ContentType": "text/plain",
        "eventAddress@ContentType": "text/plain",
        "endDate@LastModified": "Tue Nov 02 2021 16:17:08 GMT+0300",
        "startDate@LastModified": "Tue Nov 02 2021 16:17:08 GMT+0300",
        "allDayEvent": false
      }
    }
  }
}
```

My idea was to include your use case in the documentation so that people can follow your pattern.  Many things are not obvious and an example could be very handy.

**Comment by CarlosNN** [comment]
Hi, 

im trying to implements this process but not works. 

Have you got any more information or documentation?

@AmoghDaryapurkar  i have exactly the same case than you, were you able to find a solution using the MCP Content Fragment Import??

Thanks

**Comment by AmoghDaryapurkar** [comment]
Hi @YegorKozlov

I don't see the @date property working at all. It does create given properties with @lastmodified but doesn't actually create a property with the given value. I see it is similar to Feature/1845 bugfix #1871

For example: 
In the below JSON (taken from above) you do have context properties but not actual value with a name.
Current:
`"startDate@ContentType": "text/plain",
  "startDate@LastModified": "Tue Nov 02 2021 16:17:08 GMT+0300",`

Expected:
`"startDate": "Tue Nov 02 2021 16:17:08 GMT+0300",
  "startDate@LastModified": "Tue Nov 02 2021 16:17:08 GMT+0300",`

This same thing works perfectly with the data-importer process but it's not working with CF importer.

Thanks.

**Comment by YegorKozlov** [comment]
@AmoghDaryapurkar It has to do to the format of the input data. By trial and error I figured out it only accepts dates in the ISO-8601  format: ±YYYY-MM-DDThh:mm:ss.SSSTZD 

Try changing the date columns as follows, it should work: 

| startDate@date |
| -----------  |
| 2020-04-26T12:56:26.339+03:00    |

**Comment by AmoghDaryapurkar** [comment]
@YegorKozlov - It didn't work for me. I also tried couple of other formats but still don't see that property being created successfully. Could you please share the xlsx file which is working with the date?

**Comment by AmoghDaryapurkar** [comment]
> Hi,
> 
> im trying to implements this process but not works.
> 
> Have you got any more information or documentation?
> 
> @AmoghDaryapurkar i have exactly the same case than you, were you able to find a solution using the MCP Content Fragment Import??
> 
> Thanks

@CarlosNN  Please check my response above with updated files.

**Comment by YegorKozlov** [comment]
@AmoghDaryapurkar Thanks. I guess it took some efforts to reverse-engineer the correct combination.

I think in my experiments the code stepped in the 
```java
else if ("date".equals(type)) {
      value = ISO8601.parse(str);
    }
``` 
clause 

Are you using AEM 6.5 or Cloud SDK. I wonder if it depends on the implementation.

**Comment by AmoghDaryapurkar** [comment]
@YegorKozlov  I am currently on AEM 6.5.11

**Comment by niraj-100** [comment]
@AmoghDaryapurkar, @YegorKozlov   
I have a requirement to import content fragments from excel sheet. I found this discussion very helpful. Could you please let me know where is the interface/page to run the importer so that I can select the excel sheet that I prepare for upload.

Basically I want to know what is the path in aem to run the content fragment import utility

Thanks in advance.
Niraj

**Comment by NielsInc** [comment]
@niraj-100 
You can find the MCP process under Tools » ACS AEM Commons » Manage Controlled Processes. (https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp/subpages/process-manager.html)

When you click `Start Process`, you can select the task to import Content Fragments

**Comment by niraj-100** [comment]
> @niraj-100 You can find the MCP process under Tools » ACS AEM Commons » Manage Controlled Processes. (https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp/subpages/process-manager.html)
> 
> When you click `Start Process`, you can select the task to import Content Fragments

Thanks for the information. I am able to import a sample content fragment now.
