### ISSUE TITLE
Shared Component Properties in Experience Fragments

### ISSUE THREAD

**Issue by Derthenier** [Adobe-Consulting-Services/acs-aem-commons#2714]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM SDK
* [x] ACS AEM Commons Version: 5.1.12
* [x] Reproducible on Latest? yes

### Expected Behavior

When components with Shared and Global Properties are used in experience fragments, I should be able to author the shared and global properties in the experience fragments as well.

### Actual Behavior

Shared Component Properties do not work in Experience Fragments.

### Steps to Reproduce

1. Enable the Shared Component Properties OSGi service.
2. Specify a “page root path” pattern via OSGi config for com.adobe.acs.commons.wcm.impl.PageRootProviderConfig
3. Add SharedComponentPropertiesPageInfoProvider as an info provider for your xf page component
4. Add a component with either `dialogshared` or `dialogglobal` to an experience fragment.
5. You will notice the Shared Properties are not available to be edited.

**Comment by paulrohrbeck** [comment]
Should this be closed since https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2715 got merged?

**Comment by Derthenier** [comment]
Yes.
