### ISSUE TITLE
Named Transform Image Servlet - Handle different aspect ratios of images by letterboxing or cropping, maintaining the original image aspect ratio.

### ISSUE THREAD

**Issue by ramyareddyg** [Adobe-Consulting-Services/acs-aem-commons#273]
It would be good to handle images of any aspect ratios with appropriate cropping or resizing.
1. Images when requested in an aspect ratio that does not match the original image would be letterboxed/pillarboxed to fit in the new aspect ratio request. We could enhance the resize feature to serve this functionality.
2. If we want to crop the images for thumbnails, we can enhance the crop functionality to resize the image first when the aspect ratio isn't same as the original. And then do the cropping. Also, we can provide an option to crop the image from centre instead of top-left corner.
This could be of great help as we would generally expect images in different aspect ratios being passed and get back images of uniform size. Also, only one configuration would be needed to serve different image aspect ratios.

Example: I need an image of final dimensions 90x100.
To get the Letterboxing/pillarboxing, the author needs to specify the final image width and height(90x100). The NTIS will resize the image appropriately maintaining the aspect ratio of the original image and add the letterboxing/pillarboxing effect.

For cropping, the author needs to specify the final image width and height(90,100) and if it needs cropping from the centre. The NTIS will first resize the image appropriately maintaining the aspect ratio of the original image and then do cropping from the centre.

**Comment by davidjgonzalez** [comment]
Letter/pillar boxing is now supported
