### ISSUE TITLE
Generic List Localization

### ISSUE THREAD

**Issue by Derthenier** [Adobe-Consulting-Services/acs-aem-commons#2742]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: latest AEM SDK
* [x] ACS AEM Commons Version: 5.0.0
* [x] Reproducible on Latest? yes

### Expected Behavior

When I go to author a generic list, I should be able to specify localized titles.

### Actual Behavior

Only a single title field is available. This only allows for a single language to be saved.

### Steps to Reproduce

1. Create a new Generic List
2. Click on Add to add an item to the list.
3. Verify that only `Title` is available with no opportunity to specify localized values.

**Comment by davidjgonzalez** [comment]
Fixed in 5.1.0

**Comment by saurabh1140** [comment]
Hello @davidjgonzalez , This has made list very long and complex to author, what to do if we want to disable it? we want just Title and value. no localization.

**Comment by ericvangeem** [comment]
@davidjgonzalez Echoing what @saurabh1140 said. This has severely degraded the authoring experience of Generic Lists.

**Comment by Derthenier** [comment]
@ericvangeem / @saurabh1140  -  Have you tried overlaying `wcm/core/resources/languages` and seeing if that helps the authoring experience?
I understand the issue.
What would you think about providing a configuration for whether the generic list should be localized?

**Comment by ericvangeem** [comment]
I would agree with the idea of defining a configuration to enable
localization of the titles.

**Comment by SachinMali** [comment]
I think apart from 'Authorability' concerns outlined above, this Localization feature has caused the regression and specifically two issues, see https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2783, https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2765

And @Derthenier your above suggestion of overlaying 'wcm/core/resources/languages' won't help as the path is hardcoded @ https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/mcp/util/AnnotatedFieldDeserializer.java#L228

 Would you mind fixing it, and I think two ways..
1. Quick/Dirty + Hotfix: Disable the Localization support by toggling the annotation to 'false' @ https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/genericlists/GenericList.java#L87

2. Long Term: Configuration to enable localization and overlaying 'wcm/core/resources/languages' structure within ACS-Commons (/etc/acs-commons, or better location)
