### ISSUE TITLE
Parameterized Namespace Granite Include - Namespace Value appearing in some labels

### ISSUE THREAD

**Issue by navjotkler** [Adobe-Consulting-Services/acs-aem-commons#2747]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc:  6.5.10.0
* [x] ACS AEM Commons Version: 4.12.0
* [x] Reproducible on Latest? yes/no

### Expected Behavior

Namespace's value should not appear in some field's labels like Checkbox or Dropdown values.

### Actual Behavior

Namespace's value appears in some field's labels like Checkbox or Dropdown values.

### Steps to Reproduce

No special steps are required. Use it for tab inclusions which contain Dropdown or Dropdown.

![image](https://user-images.githubusercontent.com/36482082/143269664-b345e14f-c670-418d-bb1a-9ea2cab95cf5.png)

**Comment by niekraaijmakers** [comment]
@navjotkler  I tried reproducing this but didn't manage. does this problem still occur ? If yes, please provide dialog xml snippets of the dialog that is included.
