### ISSUE TITLE
Manage Controlled Processes does not show any process

### ISSUE THREAD

**Issue by Alonso289** [Adobe-Consulting-Services/acs-aem-commons#2749]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6.0
* [x] ACS AEM Commons Version: 4.12.0
* [ ] Reproducible on Latest? yes/no

### Expected Behavior

Shows a list of executed process

### Actual Behavior

Does not show any process

### Steps to Reproduce
Go to /apps/acs-commons/content/manage-controlled-processes.html
This is currently only happenning on PROD and the only way to see the list is accesing the instance through Ip

### Pictures

![linkview2](https://user-images.githubusercontent.com/82656019/144018693-8d169cc3-d906-4c92-9911-c75a98dbc8f7.PNG)
![ipView2](https://user-images.githubusercontent.com/82656019/144018695-0ca93ea6-8fee-46f7-b474-a69956abad4f.PNG)

**Comment by YegorKozlov** [comment]
Please check in CRXDE that MCPs are created under under /var/acs-commons/mcp/instances/ . There should be nodes like
```
/var/acs-commons/mcp/instances/41FF72DCE803657A
/var/acs-commons/mcp/instances/752C0932DF6FBB31
```
On the Manage Controlled Processes page the reports are loaded from a ajax call to http://localhost:4502/apps/acs-commons/content/manage-controlled-processes/jcr:content.list.json  Does it return any data? Are there any JS errors in the browser console ?

**Comment by Alonso289** [comment]
I can't currently check the nodes under /var/acs-commons/mcp/instances on PROD but since accessing through Ip to the same instance it is showing the proccess list properly, I'm guessing the instances are there

jcr:content.list.json comes with no data and there is no JS errors in the browser console

I found a diferent post with the same issue here, it does not seem like it got fixed
https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2488

**Comment by YegorKozlov** [comment]
It has to do flush() not being called on response.getWriter()

I was able to reproduce it on AEM 6.5.8 running in the Adobe MS cloud. 

Here are some facts from my research:

1. It always works when connecting by IP
2. It always works in Firefox .
3. It consistently does not work in Chrome and MS Edge. 
4. Reproducibility in curl and Postman is sporadic. The following request sometimes returns data an sometimes does not.
```
curl -u username:password https://author-<clientid>-stage.adobemsbasic.com/apps/acs-commons/content/manage-controlled-processes/jcr:content.list.json
```

I'd say it's a feature of the Gson library which is used to serialize MCP beans into servlet's output stream. Somehow it requires flush() 

The simplest test case:

```java
  Writer out = new PrintWriter(System.out);
  Map<String, String> map = new HashMap<>();
  map.put("1", "one");
  new Gson().toJson(map, out);

  // no data printed in the console
```

However, adding  out.flush() fixes it :

```java
  Writer out = new PrintWriter(System.out);
  Map<String, String> map = new HashMap<>();
  map.put("1", "one");
  new Gson().toJson(map, out);
  out.flush();

  // prints {"1":"one"}
```

A PR with the fix is coming.

**Comment by kwin** [comment]
@YegorKozlov Just make sure that the writer used by `GSON.toJson(...)` is properly closed. That may potentially perform other operations than just `flush()`!
