### ISSUE TITLE
Install fails with "OakConstraint0001" error message

### ISSUE THREAD

**Issue by Positronic-Brain** [Adobe-Consulting-Services/acs-aem-commons#2757]
AEM Version: 6.5.11
ACS AEM Commons: 5.0.6 onwards
Reproducible in latest? Yes

### Expected Behavior

ACS Commons installs by ensuring the parent nodes have the right resource path.

### Actual Behavior

We were having issues installing ACS Commons in our AEM servers - all our attempts to deploy ended with the following error in a pop up in the package manager:

`[ERROR] Request failed: org.apache.jackrabbit.vault.packaging.PackageException: javax.jcr.nodetype.ConstraintViolationException: OakConstraint0001: /conf/global/settings[[nt:folder]]: No matching definition found for child node redirects with effective type [nt:unstructured]`

![oakindex001](https://user-images.githubusercontent.com/8781555/145849493-af489641-cf74-4f40-a5ea-a5b1af1f244d.png)

We've found this was caused by an external dependency that had changed the resource type of /conf/global/settings to [nt:folder], causing the previous error, as the settings folder should be a sling:Folder in order to support nt:unstructured nodes. However ACS Commons should ensure that parent nodes have the right resource type.

### Steps to Reproduce

Starting from a vanilla AEM version, change the jcr:primaryType of the /conf/global/settings node to "nt:folder", then try to deploy the acs-commons package using the package manager. Installation will fail with the error message quoted above.

**Comment by davidjgonzalez** [comment]
If ACS Commons changes the node type, then it's possible that this "other functionality" might be incompatible, no? If ACS updated the node type and it broke the other func, i imagine there would be an issue for that? 

Isn't it best for the system to call this out via the error, and let you determine what the right node type is? Having ACS Commons replace `/conf/global/settings` seems quite heavy-handed.

WDYT?

**Comment by Positronic-Brain** [comment]
> I dont have a AEM up and running - but doesnt AEM provide this node with a type - any idea what that is?

After further poking we found out this node is created by /system/console/configMgr/org.apache.sling.jcr.repoinit.RepositoryInitializer~remoterefs with th sling:Folder resource type at server initializatio. Seems like the issue is that some other dependency we have runs before that and creates the node with the sling:Folder type so RepositoryInitializer arrives "late", causing the issue.

And yes, upon further reflection to force ACS to change the resource type might cause breakage down the road. I'm OK with closing this (and if some unfortunate soul in the future runs into this in the future, check your /conf/gloal/settings rsourcetype and find which one of your dependencies is creating nodes here before the server initialization)

**Comment by AmoghDaryapurkar** [comment]
@Positronic-Brain - I am that unfortunate soul. Did you find any solution to this?

**Comment by kwin** [comment]
@AmoghDaryapurkar Just manually change the node type to `sling:Folder` and you should be fine.
