### ISSUE TITLE
S3 Asset Ingestor not appearing

### ISSUE THREAD

**Issue by isosatl** [Adobe-Consulting-Services/acs-aem-commons#2769]
Please help me out with this issue

Thanks in advance

## Required Information

* [ ] AEM 6.5, Service Pack 6.5.9
* [ ] ACS AEM Commons Version: 5.0.2
* [ ] Reproducible on Latest? yes

### Expected Behavior

_Accessing Tools -> ACS AEM COMMONS -> Manage Controlled Processes -> Start Process, The option 'S3 Asset Ingestor'
 should appear between the rest of tools.

### Links

_[Documentation](https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp-tools/asset-ingestion/s3-asset-ingestor/index.html)_

![Screen shot from documentation where the option appears](https://user-images.githubusercontent.com/10908652/149028112-b7292d9f-bda2-4a12-8643-f234d4aa02e9.png)
![s3 asset ingestor does not appear](https://user-images.githubusercontent.com/10908652/149028114-f16bf9ff-6573-4b6c-8e8a-6c08ce4d9ff7.png)

**Comment by justinedelson** [comment]
is the S3 connector installed?

**Comment by isosatl** [comment]
That is where the issue lies, such that I am getting this when trying to resolve it using maven

Could not find artifact com.adobe.granite:com.adobe.granite.oak.s3connector:jar:1.10.10 in adobe (https://repo.adobe.com/nexus/content/groups/public/)

**Comment by justinedelson** [comment]
@isosatl this seems like an issue to bring up with Adobe Support since this project doesn't actually distribute the S3 connector.

**Comment by isosatl** [comment]
I just created an adobe ticket; - i appreciate your quick response. Thanks
