### ISSUE TITLE
Send templated Email workflow process

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#277]
Given that we have a way to send templated emails (http://adobe-consulting-services.github.io/acs-aem-commons/features/email-api.html), it would be good to have a way of sending this in a workflow. We could do some intelligent things where if the workflow payload is a cq:Page, the param map gets populated with the (first-level) page properties for if it is an asset, the param map gets populated with the asset metadata.

**Comment by davidjgonzalez** [comment]
Fixed via #350
