### ISSUE TITLE
Redirect Manager - Import is not working on aem-sdk-quickstart-2021.12.6151.20211217T120950Z-211100

### ISSUE THREAD

**Issue by myslinskipawel** [Adobe-Consulting-Services/acs-aem-commons#2773]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: aem-sdk-quickstart-2021.12.6151.20211217T120950Z-211100
* [ ] ACS AEM Commons Version: 5.1.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

I am able to import redirects from Excel file on Redirect Manager page (Import tab)

### Actual Behavior

There is 400 Bad Request as a response to form's request.

RequestProgressTracker Info for this request points out that wrong servlet has been chosen:

> 0 TIMER_START{Request Processing}
      0 COMMENT timer_end format is {<elapsed microseconds>,<timer name>} <optional message>
      4 LOG Method=POST, PathInfo=null
      5 TIMER_START{handleSecurity}
   1285 TIMER_END{1278,handleSecurity} authenticator org.apache.sling.auth.core.impl.SlingAuthenticator@46ec975d returns true
   1858 TIMER_START{ResourceResolution}
   1936 TIMER_END{77,ResourceResolution} URI=/apps/acs-commons/content/redirect-manager/jcr:content.import.html resolves to Resource=JcrNodeResource, type=acs-commons/components/utilities/manage-redirects, superType=null, path=/apps/acs-commons/content/redirect-manager/jcr:content
   1941 LOG Resource Path Info: SlingRequestPathInfo: path='/apps/acs-commons/content/redirect-manager/jcr:content', selectorString='import', extension='html', suffix='null'
   1941 TIMER_START{ServletResolution}
   1943 TIMER_START{resolveServlet(/apps/acs-commons/content/redirect-manager/jcr:content)}
   2604 TIMER_END{660,resolveServlet(/apps/acs-commons/content/redirect-manager/jcr:content)} Using servlet **com.adobe.aem.wcm.site.manager.internal.servlets.ImportSiteTemplateServlet**
   2606 TIMER_END{665,ServletResolution} URI=/apps/acs-commons/content/redirect-manager/jcr:content.import.html handled by Servlet=com.adobe.aem.wcm.site.manager.internal.servlets.ImportSiteTemplateServlet

### Steps to Reproduce

Just choose Excel file to upload and try to submit the form. Then check this request in Recent Request page http://localhost:4502/system/console/requests

**Comment by bpauli** [comment]
@myslinskipawel There is currently a product issue which is preventing the upload for the Redirect Manager. It will be fixed with the next public SDK.

**Comment by shawleys** [comment]
Hi @bpauli,  Do you happen to know if this will be fixed with the 5.2.1 SDK or some kind of ETA?

**Comment by YegorKozlov** [comment]
The upload is working fine in the latest 2022.3.6698.20220318T233218Z-220400 and AEM 6.5.12.
I believe this ticket can be closed.

**Comment by shawleys** [comment]
Agreed.  This can be closed
