### ISSUE TITLE
In AEM6.5 Version Unable to run Twitter Feed Scheduler and getting the Below Login Exception

### ISSUE THREAD

**Issue by velurunaveen** [Adobe-Consulting-Services/acs-aem-commons#2777]
Issue Description:-
error.log - the twitter feed scheduler is erroring out with the following exception and so does not retrieve twitter feed.

```
17.12.2021 13:10:00.001 ERROR [sling-default-4-com.adobe.acs.commons.twitter.impl.TwitterFeedScheduler.7881] com.adobe.acs.commons.twitter.impl.TwitterFeedScheduler Exception while running TwitterFeedScheduler.
org.apache.sling.api.resource.LoginException: Cannot derive user name for bundle com.adobe.acs.acs-aem-commons-bundle [627] and sub service twitter-updater
at org.apache.sling.resourceresolver.impl.ResourceResolverFactoryImpl.getServiceResourceResolver(ResourceResolverFactoryImpl.java:79) [org.apache.sling.resourceresolver:1.7.0]
at com.adobe.acs.commons.twitter.impl.TwitterFeedScheduler.run(TwitterFeedScheduler.java:73) [com.adobe.acs.acs-aem-commons-bundle:4.12.0]
at org.apache.sling.commons.scheduler.impl.QuartzJobExecutor.execute(QuartzJobExecutor.java:349) [org.apache.sling.commons.scheduler:2.7.12]
```

* [ ] ACS AEM Commons Version: _4.12.0____
* [ ] Reproducible on Latest? yes

Twitter Feed is working fine in AEM6.2 version and it is having the Separate bundle for twitter support. In AEM 6.5 version we have only the Twitter4J budle.

### Expected Behavior

Twitter Feed scheduler need to run in AEM6.5 version.

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

Install the AEM 6.5 version and use the AEM ACS common 4.12.0 version.

### Links

_Links to related assets, e.g. content packages containing test components_
https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/aem-6-5-version-issue-for-twitter-scheduler-component/td-p/435170

**Comment by davidjgonzalez** [comment]
Can you check in  `/home/users/system/acs-commons/twitter-updater` and post back what that node looks like on your AEM instance?

Can you also goto: http://localhost:4502/system/console/status-InventoryPrinter.323
and copy/paste the section/entry for twitter-updater?

After a quick review 4.12.0 code source code looks fine (the service user itself is defined in ui.content project, the service mapping is there, and the OSGi Component is using the correct service user...)

**Comment by justinedelson** [comment]
@davidjgonzalez the service mapping is incorrect

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/ui.apps/src/main/content/jcr_root/apps/acs-commons/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-acs-commons.config#L12

It should be to the `com.adobe.acs.acs-aem-commons-bundle` bundle, not the (no longer extant `com.adobe.acs.acs-aem-commons-bundle-twitter` bundle).

I suggested that @velurunaveen submit a tested PR for this. It's a trivial change but should be tested before merging.

**Comment by velurunaveen** [comment]
Thank you so much for helping on this .After com.adobe.acs.acs-aem-commons-bundle this instead of com.adobe.acs.acs-aem-commons-bundle-twitter I am unable to see the LoginException for Twitter Feed scheduler. But unable to updates the Twittes in my website. If it is possible Could you please help on this.
![image](https://user-images.githubusercontent.com/92776408/152030599-7ec4fde5-69e9-40b4-9d09-d5ef54461207.png)

**Comment by justinedelson** [comment]
@velurunaveen that seems like a different issue -- you opened this issue about the login exception. That said, the log lines you included don't appear to reference anything related to this project.
