### ISSUE TITLE
Bulk WorkFlow Manager Issue

### ISSUE THREAD

**Issue by SmritiMahto** [Adobe-Consulting-Services/acs-aem-commons#2801]
Hi Team,
We are using AEM ACS commons Bulk Workflow Manager for triggering DAM Update Assets for videos which are approximately more than 3-4 giga(~5k video assets). In the workflow status it shows Completed but the workflow instances are still running.
Can you please give us some inputs on how do we run the DAM Update Assets for these assets.

Thanks,
Smriti Mahto

**Comment by davidjgonzalez** [comment]
@SmritiMahto Im guessing your Dam Update Asset WF is transient, and as the docs for BWM there is no good way to check to see if a transient WF has been completed - so it just assumes it is.

You may have better luck running the WF as Synthatic (test this out to make sure DAM Update Asset WF still handle being Synthetic before doing a big run)
