### ISSUE TITLE
The renovator feature not functioning

### ISSUE THREAD

**Issue by devandramarimuthu** [Adobe-Consulting-Services/acs-aem-commons#2825]
## Required Information

* [1] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _6.5.0&6.5.8_____
* [2] ACS AEM Commons Version: __5.0.4&5.3.0___
* [3] Reproducible on Latest? no

### Expected Behavior

The renovator should be functioning as described in this https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp-tools/renovator/index.html.

### Actual Behavior

The renovator **NOT** functioning as described in this https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp-tools/renovator/index.html at all.

### Steps to Reproduce

We also tried with a vanilla instance of AEM (6.5.0). Still, it does not function as described.

### Links

No link.

**Comment by davidjgonzalez** [comment]
@devandramarimuthu can you describe what that means? Is it not loading? are there errors? can you start it? Does it run and not do anything?

**Comment by devandramarimuthu** [comment]
**The sample .xlsx file:**
![image](https://user-images.githubusercontent.com/42599583/164143011-22b2aede-855a-446e-a18e-c4c8e8d37afb.png)

**Renovator's report**
![image](https://user-images.githubusercontent.com/42599583/164142403-fddbb36f-cead-487c-8bf8-94601e3a64ab.png)
The renovator functions able to produce the report (as shown in the above link), after we run the renovator with the above .xlsx file.

However, if we checked from the AEM Sites or pages, we still could not see the changes. It just remains as it is.

**AEM Sites:**
![image](https://user-images.githubusercontent.com/42599583/164143091-ae74ce15-2ee2-450e-a5ef-f4d16b628c8f.png)
- By right the "experience" > "experiences3" & "men" > "man"

**Page**
![image](https://user-images.githubusercontent.com/42599583/164143315-88444d84-0849-4ff5-8e26-1d49ac107954.png)
- By right the **"/content/we-retail/us/en/experience"** should be changed to **"/content/we-retail/us/en/experiences3"**

**Comment by josephrignanese** [comment]
Hi @devandramarimuthu - did you have "Dry run" checked when you started the process?

> Dry Run: If checked, no moves or publish operations happen but the report is generated, and ACL checks are performed. This lets you see what will be affected by this operation.

**Comment by davidjgonzalez** [comment]
@devandramarimuthu did you see @josephrignanese 's question above?

Can you provide a screenshot of the Renovator configuration screen that youre uploading the XLS to?

**Comment by devandramarimuthu** [comment]
Hi @davidjgonzalez & @josephrignanese,

Thank you for your responses on this matter. Really appreciate it.
Currently, we are having public holidays till Wed, 04/05. Once, we get back to work, we will look into it and respond back.

Thanks

**Comment by devandramarimuthu** [comment]
Hi @davidjgonzalez & @josephrignanese,

I tried with "Dry Run" option unchecked, it works fine now.

Thanks for helping with this. Really appreciate it.
