### ISSUE TITLE
Attributes are getting added/updated in coral panel after Coral.Commons.ready event.

### ISSUE THREAD

**Issue by bhansa** [Adobe-Consulting-Services/acs-aem-commons#2834]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc:
  - Adobe Experience Manager 2022.4.7138.20220427T075748Z-220400
  - Adobe Experience Manager Forms 2022.04.12.02-220400
* [x] ACS AEM Commons Version: 5.2.0
* [x] Reproducible on Latest? yes/no *YES*

### Expected Behavior

DOM Attributes like ids and aria label are not available even after `Coral.Commons.ready` event is fired.

### Actual Behavior

Attributes should be available after ready event is fired, so code should be able to access those.

I have a tabs show hide functionality written based on attrbutes which is not working because of this behavior.

Please refer this post for more details about this issue: 
https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/coral-ids-and-attributes-are-getting-added-after-the-coral/td-p/443895

**Comment by davidjgonzalez** [comment]
@bhansa this doesnt sound like it has anything to do with ACS Commons, but more with Granite UI/Touch UI?

If you can tie this back to how this is breaking some specific ACS Commons feature we can look at it - but this sounds more like a question for ExL Community and/or Adobe Support if you believe this is an issue w/ the product. (not sure that anything has ever stated when these attrs are available though - so i doubt Support would consider this something to fix in AEM, but you never know!)
