### ISSUE TITLE
Redirect Manager - Selector based redirection request looping to same page

### ISSUE THREAD

**Issue by karthikelumalaimm** [Adobe-Consulting-Services/acs-aem-commons#2855]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.9
* [ ] ACS AEM Commons Version: 5.3.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

Need to redirect source "/content/we-retail/en/home.product1" to "/content/we-retail/en/home.product2" based on selector value

### Actual Behavior

Its redirecting to same "/content/we-retail/en/home" home page again and again, kind of request looping to same page.

### Steps to Reproduce

Use source as /content/we-retail/en/home.product1 and target as /content/we-retail/en/home.product2, it should redirect same page with target selector value.

Kindly guide to resolve this issue.

Also refer below patterns

Pattern 1
/content/we-retail/en/home.product1
/content/we-retail/en/home.product2

Pattern 2
/content/we-retail/en/home.product1/*
/content/we-retail/en/home.product2

**Comment by YegorKozlov** [comment]
Selectors are not yet supported. This is something to in improve in future releases.

**Comment by YegorKozlov** [comment]
@karthikelumalaimm I submitted a PR with the support for selector-based redirects. See https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2877
