### ISSUE TITLE
Getting the below error with the updation of 5.3.0 version

### ISSUE THREAD

**Issue by epcy2809** [Adobe-Consulting-Services/acs-aem-commons#2863]
Using AEM as cloud service
ACS Commons 5.3.0

Getting the below error when we include ACS commons 5.3.0 version.

```
07:19:21,729 [main] [ERROR] Error downloading dependencies for project
07:19:21,729 [main] [ERROR] The following artifacts could not be resolved: com.adobe.acs:acs-aem-commons-ui.apps:content-package:5.3.0, com.adobe.acs:acs-aem-commons-ui.content:zip:min:5.3.0, com.adobe.acs:acs-aem-commons-ui.apps:zip:min:5.3.0: Could not find artifact com.adobe.acs:acs-aem-commons-ui.apps:content-package:5.3.0 in central (https://repo.maven.apache.org/maven2)
```

**Comment by ranjith129143** [comment]
But we are using acs commons 5.0.6  version

**Comment by epcy2809** [comment]
It works still 5.2.0. Error is thrown only for 5.3.0

**Comment by ranjith129143** [comment]
I don't get exactly what I need to do

**Comment by epcy2809** [comment]
If we include 5.3.0, we get error as below. It couldnt download the dependency.

 Could not find artifact com.adobe.acs:acs-aem-commons-ui.apps:content-package:5.3.0 in central (https://repo.maven.apache.org/maven2)

**Comment by davidjgonzalez** [comment]
5.3.0 no longer has a `min` package - can you make sure you remove `min` from your dependency?

Its on maven central: https://search.maven.org/artifact/com.adobe.acs/acs-aem-commons-ui.apps/5.3.0/content-package

Ill close this for now, please re-open if that doesnt resolve. thanks!
