### ISSUE TITLE
Wrong assets on the 5.3.2 release

### ISSUE THREAD

**Issue by wimsymons** [Adobe-Consulting-Services/acs-aem-commons#2873]
https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases/tag/acs-aem-commons-5.3.2 shows the wrong assets.

5.3.2 does appear to be correct on Maven Central.

**Comment by davidjgonzalez** [comment]
Thanks @wimsymons - trying to get this stuff automated so I don't make silly mistakes like this :) vaca today, so was trying to cut releases of both!
