### ISSUE TITLE
Robots.txt generator: disallowing specific pages instead of whole sections

### ISSUE THREAD

**Issue by svbeek-ida** [Adobe-Consulting-Services/acs-aem-commons#2876]
I'd like to request a new feature in the ACS commons sitemap generator.

Currently, when adding the disallowed property on a page, the line thats beeing added in robots.txt looks like this:

`Disallow: https://www.mysite.com/somepage/`

Basicly, this will disallow the whole /somepage/ section. However somepage.html does not match this path, and will be indexed. See the robots.txt spec for details: https://developers.google.com/search/docs/advanced/robots/robots_txt#disallow

Shouldnt it be possible to also disallow somepage.html, or maybe make it configurable wether the single page or whole section should be disallowed?

Removing the trailing slash is not an option, since it would match any page starting with /somepage*

**Comment by kwin** [comment]
Fixed in v5.3.4
