### ISSUE TITLE
Content Fragment Importer not working for multivalue field

### ISSUE THREAD

**Issue by tram42** [Adobe-Consulting-Services/acs-aem-commons#2881]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM as a Cloud Service (local SDK 2022.3.6582.20220307T234020Z-220100)
* [ ] ACS AEM Commons Version: 5.3.3-SNAPSHOT
* [ ] Reproducible on Latest? yes

### Expected Behavior

Multi-value text field in content fragment contains all values.

### Actual Behavior

Multi-value text field in content fragment contains a single value

### Steps to Reproduce

- Created content fragment model with 2 fields. One field is a multi value text field
-- content fragment model contains 2 fields: _title_ (single text field) and _multiText_ (multi text field)
 
- Created excel sheet for import of content fragment
-- excel contains all fields. For the multi text field 2 columns are created.

Content fragment model and excel sheet are attached.

Import Content fragment using the _Content Fragment Import_ option in _Manage controlled processes_.

The process finishes with a successful result. The content fragment is created, but the multi text field only contains a single line of text.

Can you share an example model and excel that works for a multi-value text field?

### Links

http://localhost:4502/apps/acs-commons/content/manage-controlled-processes.html
[test-importer.xlsx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/9092082/test-importer.xlsx)
[test-cf-model.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/9092084/test-cf-model.zip)

**Comment by YegorKozlov** [comment]
To specify multivalued fields enter multiple lines in a single Excel cell by pressing Alt + Enter keys simultaneously while entering text:
<img width="276" alt="image" src="https://user-images.githubusercontent.com/2543854/179216060-788f8534-7eef-4fc3-bd8f-65678b4daa01.png">
[test-importer.xlsx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/9120488/test-importer.xlsx)

See the attached spreadsheet.
