### ISSUE TITLE
Email Service - Sending multiple e-mail copies

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#292]
Via Disqus comments on: http://adobe-consulting-services.github.io/acs-aem-commons/features/email-api.html
1. If we have more than one recipients. The second recipient is getting one attachment which is the mail template. Third recipient gets two attachments etc. This is the behaviour in outlook.
2. When we are sending mail to gmail or other. Second recipient getting two mails. Third receipt getting three mails etc.

I believe the code is adding recipients in loop rather than generating email for each recipient.

**Comment by piagarwa** [comment]
@justinedelson  i guess the issue still exists when we are having multiple recipients . I am using the EmailService of acs-aem-commons 1.8.0 , have saved the notification email template as .html , but still , when there is more than 1 recipient , the notification email template content is duplicated in the sent email.
