### ISSUE TITLE
Smart tags are not populating in Reports Result column

### ISSUE THREAD

**Issue by jyothishey** [Adobe-Consulting-Services/acs-aem-commons#2929]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: __6.5.10_____
* [ ] ACS AEM Commons Version: __4.11.0___
* [ ] Reproducible on Latest? yes/no - yes

### Expected Behavior

When I configure Report Result columns for smart tags, they should populate in the reports. Attached is the crx structure for the same.
![image](https://user-images.githubusercontent.com/68094839/183399904-bfacb734-a250-4c69-a709-403ccb325943.png)

jcr:content/metadata/predictedTags

### Actual Behavior

When Report Results column configured for the smart tags, they should populate. Though it is in node structure under metadata. 

### Steps to Reproduce

Please add a predictedTags node under metadata as shown in the screenshot with few nodes under it. Configure the report results Tags column, and it should get the nodes under 'Predicted Tags'.

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by robnlla** [comment]
Hi @jyothishey ,

Just wondering if there has been any update on this? It looks as though there hasn't been any activity on the ticket. I've also opened a ticket on the Adobe Support Console and have not been able to progress it, so have been referred here.

Thanks,

Niall

**Comment by jyothishey** [comment]
@davidjgonzalez Hello, Sorry to ping you directly. We are not sure whom to reach out as this issue raised and no one had take a look into this till now. Could you help us if someone can take a look into this issue the customer is waiting for this fix on the ACS commons reports to pull the smart tags?

**Comment by davidjgonzalez** [comment]
@jyothishey hi - this is an enhancement as reports feature was not designed to handle pulling complex structures like this. @pahupe was looking at this as something to possibly work on (but i can speak for him :))

**Comment by robnlla** [comment]
Hi,

Is this likely to be picked up soon? I appreciate it’s an enhancement request but it was also done as part of project/ application enhancements to AEM and it would be great to get it added soon.

Thanks,

Niall

**Comment by robnlla** [comment]
Hi all,

Looking for any information on this? Is it likely to be added as a feature in the future?

Thanks,

Niall

From: Robinson, Niall
Sent: 05 October 2022 16:56
To: Adobe-Consulting-Services/acs-aem-commons ***@***.***>; Adobe-Consulting-Services/acs-aem-commons ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [Adobe-Consulting-Services/acs-aem-commons] Smart tags are not populating in Reports Result column (Issue #2929)

Hi all,

Just wondering if there’s any update on this?

Thanks,

Niall

From: Robinson, Niall
Sent: 29 September 2022 15:13
To: Adobe-Consulting-Services/acs-aem-commons ***@***.******@***.***>>; Adobe-Consulting-Services/acs-aem-commons ***@***.******@***.***>>
Cc: Comment ***@***.******@***.***>>
Subject: RE: [Adobe-Consulting-Services/acs-aem-commons] Smart tags are not populating in Reports Result column (Issue #2929)

Hi,

Is this likely to be picked up soon? I appreciate it’s an enhancement request but it was also done as part of project/ application enhancements to AEM and it would be great to get it added soon.

Thanks,

Niall

**Comment by robnlla** [comment]
> @jyothishey hi - this is an enhancement as reports feature was not designed to handle pulling complex structures like this. @pahupe was looking at this as something to possibly work on (but i can speak for him :))

Hi @davidjgonzalez , is there any update you can provide? i'd just like to know if it's likely to be added as a feature request in the future? thanks!
