### ISSUE TITLE
[Redirect Manager] Redirect rules imported from excel file do not store `jcr:created` and `jcr:createdBy` properties

### ISSUE THREAD

**Issue by sozores** [Adobe-Consulting-Services/acs-aem-commons#2938]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 2022.7.8085.20220725T140323Z-220600
* [ ] ACS AEM Commons Version: 5.3.2
* [ ] Reproducible on Latest? yes

### Expected Behavior

When importing redirect rules from an excel file:
- the rules imported from the excel file contain the creation date and creator user information in CRX properties `jcr:created` and `jcr:createdBy` respectively
- the rules created via UI, keep the values of these properties at the moment of creation.

### Actual Behavior

When redirect rules are imported from an excel file:
- existent redirect rules are overwritten and do not longer contain the properties `jcr:created` and `jcr:createdBy`
- redirect rules in CRX do not contain the `jcr:created` and `jcr:createdBy`, although included in the code (link [2])

### Steps to Reproduce

1. Navigate to the redirect manager tool
2. Create a new redirect rule
3. Observe in CRX properties `jcr:created` and `jcr:createdBy` are set
4. Import an excel file with new redirect rules
3. Observe in CRX the previous rules added from the UI no longer contain `jcr:created` and `jcr:createdBy` properties and either the new rules imported via excel file contain them

### Links

[1] Feature doc page: https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-manager/index.html
[2] Redirect Rules Import Servlet: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/06d2c1c5e82545feabba8251e6f3a0ee503964e4/bundle/src/main/java/com/adobe/acs/commons/redirects/servlets/ImportRedirectMapServlet.java#L129
[3] Rules added from UI
<img width="887" alt="rules_created_from_UI" src="https://user-images.githubusercontent.com/10310287/187178136-cad235dc-38cc-4024-977a-dcb06d19dbb1.png">
[4] Rules imported from Excel
<img width="875" alt="rules_from_imported_file" src="https://user-images.githubusercontent.com/10310287/187178248-622e2536-102f-4a69-9f4a-dcd1a6f4302f.png">

**Comment by YegorKozlov** [comment]
@sozores Thanks for this bug  report. The PR with the fix is https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2943
