### ISSUE TITLE
Expose 'last modification' properties and 'creation date' property in the Redirect Manager Tool

### ISSUE THREAD

**Issue by sozores** [Adobe-Consulting-Services/acs-aem-commons#2944]
**Feature Enhancement**
Exposing the "Created Date", "Last Modified Date" and "Last Modified By" in the Redirect Manager tool, will help identify easily when the redirect was initially created and when and by whom last modifications where done.

These properties have been added to the redirect properties, the aim of this ticket is to propose the enhancement of the tool by exposing them in the UI and also including them in the exported excel file.

**Expected Behavior**
'jcr:created', 'jcr:lastModified' and 'jcr:lastModifiedBy' properties are exposed:
- in the UI, new columns "Created date", "Modified Date" and "Modified By" are added
<img width="1513" alt="image" src="https://user-images.githubusercontent.com/10310287/188682345-4655ee42-f098-410e-864e-53c662500e52.png">

- in the exported excel file the corresponding "read only" columns are added for these properties.

**Links**
Feature doc page: https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-manager/index.html

**Comment by YegorKozlov** [comment]
@sozores I'm reluctant to clutter the UI with the "Modification date" and "Modify By" columns. The current design is laconic and I'd like to keep it so.  

Excel export is not a problem and we can include all the new fields in it:

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/2543854/193527202-19599aba-9eb0-47fa-94d6-5e1a30f74002.png">

I checked-in this change in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2943
