### ISSUE TITLE
[Redirect Manager] Include a 'Redirect Category' property

### ISSUE THREAD

**Issue by sozores** [Adobe-Consulting-Services/acs-aem-commons#2945]
**Feature Enhancement**

As a Redirect Manager, I want to clearly understand the purpose of a redirect and group them accordingly to make them easier to manage. Usually, there are different reasons why redirects are installed, e.g. some redirects have been created during migration, some are for marketing activities, some have been requested by SEO, etc.

To make the management of redirects easier (especially in combination with searching/filtering/grouping), it is good to have a field to select categories. This field is only for categorising/grouping the redirects into certain topics, without statement about the redirect itself (which would be the notes field).

The usage of Tags for Categories naturally fits into this proposal.

**Expected Behaviour**

- Include a new field "Category" into the creation/modification dialog of a redirect rule to allow the selection of tags
- Expose this new property in the UI: new column "Redirect Category" in the redirect rules table
- Include this new property in the exported excel file
- Include a new column "Redirect Category" in the imported excel file and process accordingly

**Links**
Feature doc page: https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-manager/index.html

**Comment by sozores** [comment]
If you find this proposal useful, I would like to participate in the implementation if possible

**Comment by kwin** [comment]
What about leveraging tags for the classification. That way one can predefine a taxonomy of redirects. Also tags can be created ad hoc if the user has the necessary permission.

**Comment by YegorKozlov** [comment]
@kwin I like the idea to leverage tags. It naturally fits into the AEM content model. 

Adding a Tags field in the Edit dialog and html listview is not a big deal. In the Excel Export tags will be a multi-line cell, we use a similar convention in MCP reports. The only potential caveat is importing tagged redirects from an Excel file on a target AEM  instance where the tags don't exist. In such a case the tag references will be removed by AEM.

@sozores patches are welcome. See my recent PR with support for the Created By field, you can follow the pattern.

**Comment by sozores** [comment]
Thanks @kwin and @YegorKozlov for your comments! Great idea using tags, I'm updating the description of the ticket to replace the free text for categories with the usage of tags.

**Comment by YegorKozlov** [comment]
@sozores I checked in initial support for tagging redirect rules in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2943.
 
The Edit dialog now provides a way to apply tags:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/2543854/192480439-c4120fde-d783-4a45-ae89-c3a8737fcf58.png">

and the tags are displayed in the html view:
<img width="944" alt="image" src="https://user-images.githubusercontent.com/2543854/192480686-9145687d-291e-4bec-9572-55295ef25ef6.png">

and Excel export:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/2543854/192481848-cdfbfbc4-db44-4eec-9d49-2237a779047f.png">
