### ISSUE TITLE
[Redirect Manager] Include a 'Redirect Mapping Type' property

### ISSUE THREAD

**Issue by sozores** [Adobe-Consulting-Services/acs-aem-commons#2946]
**Feature Enhancement**

As a Redirect Manager, I want to ensure that redirects are evaluated as quickly as possible, such that the experience for the end-user improves. 
Separating between simple and RegEx redirects allows performance optimisations: All 'simple' redirects can be resolved with a fast comparison, while only the complex RegEx redirects will run the costly match. This is especially important in a migration scenario, when there are thousands of redirects pointing from an old to a new location only. Marking those as simple prevents thousands of RegEx matches.
Additionally, as a redirect manager, I want to ensure the stability of redirects. As regular expressions come at considerable complexity, a separation can be used to limit the access rights to the redirects, such that only a selected few can edit and maintain regEx redirects, and a larger group of people can define and edit simple redirects.

**Expected Behaviour**

- This property is to be calculated dynamically when creating or modifying a Redirect Rule, setting its value to "RegEx" or "Simple" according to the result
- Expose the new property in the UI: new column "Mapping Type" in the redirect rules table.
- Include this new property in the exported excel file as (read only).

**Links**

Feature doc page: https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-manager/index.html

**Comment by YegorKozlov** [comment]
@sozores I believe the current implementation takes care about performance.

The rules are internally divided into two categories:
-	by exact path
-	by regex

When evaluating a request, the Redirect Filter tries to find an exact match by JCR path and this is a O(1) lookup in a hash map. Then, if an exact match wasn’t found, the filter iterates over regex rules until it finds a match. This gives O(N) performance where N is the number of regex rules.   

See https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/redirects/models/RedirectConfiguration.java

So, if you have thousands of simple redirects then you are good, it will be O(1) lookup regardless of how many you have, and this was the primary use case for me. 

Also, there is no Resource IO when evaluating a request. The rules are cached, and all the evaluation happens in memory, and the cache is refreshed on change or on replication.

**Comment by sozores** [comment]
Hi @YegorKozlov thanks for the detailed explanation, however the idea of this ticket was to start by exposing this property in the UI and excel file. So depending on the profile of the user, only a few will be able to edit and maintain RegEx rules while a larger group will be able to do so with simple redirect rules, and this can allow them to filter out some rules.
This separation may also be used to limit the access rights to the redirects.

**Comment by YegorKozlov** [comment]
This flag seems an extra feature to me. Even if we add it, I don't see how it will help you to manage access.  It sounds like a client-specific feature, not a generic functionality to be added in the Redirect Manager by default.

In my projects I used two ways to manage access to redirects:

1. Organize redirects by context and restrict edit permissions to individual /conf folders. 
2. Allow editing, but restrict the permission to replicate. This way, publishing redirects will fall into the Request For Activation workflow where you can add a custom step to check if the redirects being replicated contain regex rules, auto-approve or reject it, notify the editor in their Inbox, etc. 

Regards,
Yegor
