### ISSUE TITLE
Reports - not possible to open the page in editor mode

### ISSUE THREAD

**Issue by royteeuwen** [Adobe-Consulting-Services/acs-aem-commons#2969]
Currently when selecting the custom editor, you could state /editor.html but this will not open the page correctly seeing as the editor.html expects the .html extension after the resource path.

**Comment by royteeuwen** [comment]
Fixed by https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2970

**Comment by klcodanr** [comment]
@royteeuwen Looks like the PR is merged, any reason this can't be closed?

**Comment by royteeuwen** [comment]
Released in 5.4.0
