### ISSUE TITLE
QA Instance | Redirects Manager - ACS Commons

### ISSUE THREAD

**Issue by nakkerla-spandana** [Adobe-Consulting-Services/acs-aem-commons#2971]
## Required Information

* [ ] AEM Version - 6.5,  Service Packs Service Pack 13
* [ ] ACS AEM Commons Version: 5.1.2
* [ ] Issue: We are using ACS common’s redirect manager for handling the 301 redirects for the legacy site.

Reference Doc: https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-manager/index.html

We have followed the above-shared reference document link and implemented the redirects. And there is no instance-specific configuration to be for these redirects.

Dev – redirect manager
https://author-domain-dev.adobecqms.net/apps/acs-commons/content/redirect-manager.html/conf/project/settings/redirects

https://publish1useast1.dev.project.adobecqms.net/content/project/us/en/asadsdasdasdsd redirects to /content/project/us/en/about-us

QA
https://author-teladoc-qa.adobecqms.net/apps/acs-commons/content/redirect-manager.html/conf/project/settings/redirects
https://publish1useast1.qa.teladoc.adobecqms.net/content/project/us/en/business doesn’t redirect to /content/project/au/en as it should be

We have an observation when we were debugging. We found that the redirects enabled from /conf/global are working but the redirects enabled for the custom config are not, i.e. redirects configured under /conf/project are not working. 

Can you please assist us in checking if there is any difference or discrepancy between Dev and QA instances, as it is working on dev and not on QA

### Expected Behavior

The redirects enabled under /conf/project should work as expected on QA instance as they do on dev instance.

### Actual Behavior

The redirects enabled under /conf/project are not redirecting

**Comment by YegorKozlov** [comment]
1. Is RedirectFilter enabled in the OSGi configuration? 
2. did you publish the `/conf/project` configuration ?
3. do you have a reference to this configuration from the `/content/project` tree?
```
 /content/project
    + jcr:content
      - cq:conf = "/conf/project"
```

**Comment by nakkerla-spandana** [comment]
Yes, the OSGI config is enabled and /conf/project is published

**Comment by nakkerla-spandana** [comment]
Yes, cq:conf="/conf/project" is refered as property of jcr:content of the node /content/project

**Comment by YegorKozlov** [comment]
Can you try upgrading to the latest and greatest v5.3.2?
If it does not help, then enable a debug logger on `com.adobe.acs.commons.redirects`  . It should shed light on what's going on.
