### ISSUE TITLE
Redirect Manager : Add "Effective From" field

### ISSUE THREAD

**Issue by thcharan** [Adobe-Consulting-Services/acs-aem-commons#2977]
## Required Information

@davidjgonzalez  @YegorKozlov 

This is not a bug, but a request for enhancement for Redirect Manager for (AEM-Cloud-Service).

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM-as-a-Cloud Service
* [ ] ACS AEM Commons Version: 5.0.4 
* [ ] Reproducible on Latest? yes

### Expected Behavior

In the current state, we have the field "Redirect Until" which acts as an "Expiry Date" for the redirect.
In addition to above, it would be great to add an additional field "Effective From" which acts as "Redirect Go Live Date".
This really helps, where many campaign redirects are planned ahead of time, the redirect rules can be setup ahead of time and published with this effective date. 
The servlet filter will only pick up this rule on once effective date is met. This will help automate the whole process of "setup ahead of time" and the redirect becomes automatically live on a future date.

Key Changes required -
1) Add this new field in UI.
2) Handle the conditional check in RedirectFilter -> handleRedirect()

**Comment by YegorKozlov** [comment]
@thcharan It is certainly doable. 
The Edit Dialog is growing bigger and I wonder if we should split it into two tabs. The "Basic" tab will have "source", "target" and "status" fields. The "Advanced" tab will have the dates , etc. 

Also, "Effective From" and "Redirect Until" are mutually exclusive.  I'm thinking about a radio button to switch between two.
Or, may be it should keep one date field and have a drop-down next to it with two options:   Redirect Until (default) and Effective From.

**Comment by thcharan** [comment]
@YegorKozlov  - 

Good idea, that't right. we should split that in to two tabs.

Effective date and Redirect date Until aren't mutual, below are the use cases - 

Case 1) An author can create a redirect rule where ( Effective Date = EMPTY and Redirect Date = EMPTY ) and publishes the rule. 
Expected behavior - The rule starts working from the moment it is published to the publish server and with no expiry.

Case 2) An author can create a redirect rule where ( Effective Date = FUTURE DATE  and Redirect Date = EMPTY ) and publishes the rule. 
Expected behavior - The redirect rule will start working from the future date and with no expiry.

Case 3) An author can create a redirect rule where ( Effective Date = EMPTY and Redirect Date = FUTURE DATE ) and publishes the rule. 
Expected behavior - The rule starts working from the moment it is published to the publish server and stops working on the date of expiry.

Case 4) An author can create a redirect rule where ( Effective Date = FUTURE DATE and Redirect Date = FUTURE DATE ) and publishes the rule. 
Expected behavior - The rule starts working from the future date and stops working on the date of expiry.

Edge Cases -

Case 5) If an author creates a redirect rule where ( Effective Date = CURRENT DATE OR PAST DATE  and Redirect Date = EMPTY ) and publishes the rule. 
Expected behavior - SAME as Case-1.

Case 6) If an author creates a redirect rule where ( Effective Date = EMPTY and Redirect Date = PAST DATE OR CURRENT DATE ) and publishes the rule. 
Expected behavior - The redirect will not work because it already met it's expiry, when the first request is handled by the RedirectFilter -> handleRedirect().

Pseudo logic - 
 handleRedirect () {
     If (match != null) {
              if (match expired OR match not yet active) {
                   return false;
               } else {
                    // proceed with redirect logic
               }
     }

Hope that helps.

**Comment by YegorKozlov** [comment]
@thcharan thanks for the use cases. I'll  include them in junits.

**Comment by thcharan** [comment]
@YegorKozlov  Cool.  :)
