### ISSUE TITLE
AEM-Scene 7 Custom Workflow to create Adaptive Video Set for Videos on Scene 7 SPS

### ISSUE THREAD

**Issue by KVIKASCHANDRAN** [Adobe-Consulting-Services/acs-aem-commons#298]
Scene 7 Custom Workflow to create Renditions i.e. Adaptive Video Set on Scene 7 SPS for DAM Videos published to Scene 7 through DAM

**Comment by badvision** [comment]
@davidjgonzalez, @justinedelson I recommend we close this one.
