### ISSUE TITLE
 ACS AEM Commons /apps/cq/core/content package may cause node-constraint conflicts

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#299]
Removing menu items from the nav using an overlay in another package results in the following errors when installing packages. 

Error: org.apache.jackrabbit.vault.packaging.PackageException: javax.jcr.nodetype.ConstraintViolationException: OakConstraint0001: /apps/cq/core/content[[nt:folder]]: No matching definition found for child node nav with effective type [nt:unstructured]

Resolve by updating ACS AEM Commons overlay to mimic the OOTB node type structure

**Comment by charlie2869** [comment]
I am very new to CRXDE and believe I need to do the above but have no idea how to actually do it.  Do I create the folder structure /apps/cq/core/content/nav/tools and I am uncertain how to create a node?  I have installed CQ v6.2 and the hotfix 12785.  I am getting node constraint conflicts when doing so.  Can someone point me in the right direction?  I am trying to do the CQ install on localhost and can't even get it working to learn it better.

**Comment by charlie2869** [comment]
Here's my actual error:  Could not Install Package

"org.apache.jackrabbit.vault.packaging.PackageException: javax.jcr.nodetype.ConstraintViolationException: OakConstraint0021: /apps/nscorp/install/nscorp-bundle-1.6.10.jar/jcr:content[[nt:resource, cq:ReplicationStatus]]: Mandatory property jcr:data not found in a new node"

**Comment by justinedelson** [comment]
@charlie2869 that error doesn't look related to this issue (which was resolved almost 2 years ago). The particular error you have posted seems to be a problem in the package. I'd suggest working with support to troubleshoot.
