### ISSUE TITLE
Redirect Manager Queries

### ISSUE THREAD

**Issue by Vipraja18** [Adobe-Consulting-Services/acs-aem-commons#3002]
AEM As a Cloud Service: Adobe Experience Manager 2022.10.9398.20221020T071514Z-220900
ACS AEM Commons Version: 5.4.0

We're newly trying to use the Redirect Manager in AEM as a cloud service for some of our existing redirects.

We've found that the redirects work for cases where the "Source Url" is an actual page that exists like "/content/abc/([a-zA-Z]+)/([a-zA-Z]+)/def/ghi"

But in the case of it not being an existing page, the redirect doesn't happen.

Is there a workaround for this? Where we can redirect from a non-existing url to a page?

In addition to the above:
- Is there a way to delete multiple redirects at once? It seems like the only way to delete them is by individually going in to edit them and then removing them.
- Is there a way to delete a context aware redirect configuration (/conf/example)?

Any help appreciated!

**Comment by YegorKozlov** [comment]
> We've found that the redirects work for cases where the "Source Url" is an actual page that exists like "/content/abc/([a-zA-Z]+)/([a-zA-Z]+)/def/ghi"

Redirects are evaluated early and existence of the resource should not matter. I tried your example as is, and it worked for me.

test redirect rule:
```
/content/abc/([a-zA-Z]+)/([a-zA-Z]+)/def/ghi => /test
```

curl example:
``` 
$ curl -I -u admin:admin "http://localhost:4502/content/abc/ABC/xyz/def/ghi.html?wcmmode=disabled"
HTTP/1.1 302 Found
Location: /test.html?wcmmode=disabled
```

Note that the source and target paths don't exist on my local instance. 

> Is there a way to delete multiple redirects at once? It seems like the only way to delete them is by individually going in to edit them and then removing them.

No, if can only delete them one by one in the UI. 

> Is there a way to delete a context aware redirect configuration (/conf/example)?

You can't do it in the UI, but you can use Sling POST servlet, e.g.
``` 
curl -X DELETE -u admin:admin "http://localhost:4502/conf/example/settings/redirects"
```

**Comment by Vipraja18** [comment]
Another question - when there are multiple pages of redirects, when a keyword is searched, it filters through only the redirects on the current page. Is there a way to search through _all_ the redirect rules?
