### ISSUE TITLE
Redirect Manager : Add "State" field

### ISSUE THREAD

**Issue by sozores** [Adobe-Consulting-Services/acs-aem-commons#3008]
## Required Information

This is not a bug, but a request for enhancement for Redirect Manager for (AEM-Cloud-Service).

-  AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM-as-a-Cloud Service
-  ACS AEM Commons Version: 5.4.1
-  Reproducible on Latest? yes

### Expected Behavior

After the enhancement provided in https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2977, it would be nice for users to have a new field STATE in the UI so it is visible at a glance the current status of the redirect:

- Active: if activation date is previous or equal to current date and previous to the expiration date. 
- Inactive: if expiration date is previous or equals to current date.
- Planned: if current date is previous to activation date.
- Invalid: if there is an error with the configuration of a redirect (for instance, activation date is previous to expiration date).

**Comment by thcharan** [comment]
@sozores - I think that would be a good enhancement.
Not sure, if there is enough real estate to fit a new column.
@YegorKozlov  - from an UX side, Should we reconsider alternate view ? 
In most cases i see these redirects run in to 1000's and grows over a period of time,... excel export helps and but console view can be made better ... i don't have many ideas though on alternate view!

**Comment by YegorKozlov** [comment]
@sozores what about an icon, e.g. coloured circle? green will be active, yellow will be Inactive, blue will be Planned and red is Invalid.

@thcharan an alternative view is a very heavy manoeuvre . It's doable in theory, but will requires quite a bit of work.

**Comment by sozores** [comment]
Thanks for your feedback! @YegorKozlov @thcharan 
@YegorKozlov the use of icons sounds good! It is easily identifiable at first sight and kind of common in other tools. Maybe also adding a tooltip with the text itself will help users to get more detail on the meaning of the color code.

**Comment by thcharan** [comment]
@YegorKozlov @sozores - Yes, Color Icon is a good idea. I believe, when we export to excel it would still need to have text column for 'state' field to enable standard group by/filter by functions in the excel.

**Comment by YegorKozlov** [comment]
#3023 adds the State column in the Redirect Manager UI.  The new column reflects the state of published redirects, i.e. that are  live.

If a redirect is never published, or modified after publication, then State is blank.  Once redirects are published, users will get something like this:

![image](https://user-images.githubusercontent.com/2543854/212529113-9618505b-8a9f-4289-816c-07c17ba06642.png)

where green is Active, red is Invalid, orange is Pending, grey is Expired. 

@thcharan I don't think we need it in Excel exports. State is evaluated relative to the current time, while Excel export returns you a static view. This can lead to confusion, e.g. if a redirect expires then user can still see it as Active in the spreadsheet while the UI will show it as Expired.

**Comment by thcharan** [comment]
@YegorKozlov  -  reg: excel export - ok, that makes sense.

the only thing i am not sure is, leaving an state column blank if a rule was live but a trivial modification is done. it doesn't inform author what is going on.
