### ISSUE TITLE
ACS Redirect Manager

### ISSUE THREAD

**Issue by khaic** [Adobe-Consulting-Services/acs-aem-commons#3014]
AEM As a Cloud Service: Adobe Experience Manager 2022.10.9398.20221020T071514Z-220900
ACS AEM Commons Version: 5.4.0

We are currently using the ACS Redirect Manager and have over 4000 redirect configurations.
At the moment this spans over 5 pages in the Redirect Manager UI

### Expected Behavior

When we search on a particular keyword, it only filters on the current page of redirect manager we are on.
eg if the rule we are looking for is on page 5, and we are searching on page 1 - it only returns results from page 1

### Actual Behavior

When we search on a particular keyword, the search should return results from any page of the redirect manager listing.

### Steps to Reproduce

1. Add redirects into ACS Redirect Manager (as many until there are more than 1 page of redirects in the UI
2. Stay on the first page and search for a known keyword of an entry in page 2
3. Nothing will be returned in the results

**Comment by YegorKozlov** [comment]
This is by design. Current implementation of search is client-side and can only search on the current page.
