### ISSUE TITLE
Button in sidekick,  to switch page in wcmmode=disabled

### ISSUE THREAD

**Issue by gauravjasiwal** [Adobe-Consulting-Services/acs-aem-commons#302]
As we use "wcmmode=disabled" very frequently to test our pages. 
By using "wcmmode=disabled" page get loaded as it is usually the case on a 'publish' instance where the normal WCM capabilities are disabled.

So it will be good if we add a button in sidekick to do this job to save our time as shown below:
ScreenShot: https://cloud.githubusercontent.com/assets/7764899/4107465/1e386c62-31c8-11e4-9d3e-bac58e262d33.png

Here is a clientlib package with js which add button in sidekick and on hit of button its reload same page wcm disabled mode.

Eg: 
URL Before : http://localhost:4502/cf#/content/actemrahcp/en_us.html
URL After : http://localhost:4502/content/actemrahcp/en_us.html?wcmmode=disabled

Thanks,
Gaurav Jasiwal.

**Comment by badvision** [comment]
Is this solved, or if not, still relevant?

**Comment by davidjgonzalez** [comment]
This exists in TouchUI Page Editor now
