### ISSUE TITLE
System Notifications inject Javascript into Exports to Target

### ISSUE THREAD

**Issue by benpeter** [Adobe-Consulting-Services/acs-aem-commons#3021]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5.15.0
* [ ] ACS AEM Commons Version: 5.2.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

If a system notification is active, it should not effect HTML exports to Target

### Actual Behavior

If a system notification is active, it will erroneously inject the following JS before the closing body tag:

`<script>if(window === top) {   window.jQuery || document.write('<script src=\"/etc/clientlibs/granite/jquery.js\"><\\/script>');   document.write('<script src=\"/apps/acs-commons/components/utilities/system-notifications/notification/clientlibs.js\"><\\/script>');}</script>\n`

### Steps to Reproduce

- set up a connection with Adobe Target
- create an active system notification
- create an experience fragment
- export the experience fragment to Adobe Target
- retrieve the experience fragment's HTML
- observe that above Javascript is included in the HTML code

**Comment by benpeter** [comment]
PR: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3022

**Comment by davidjgonzalez** [comment]
Fixed release in 5.5.0
