### ISSUE TITLE
Non-Compatible Changes - Content issues in preparation for move to AEMaaCS

### ISSUE THREAD

**Issue by merodioc** [Adobe-Consulting-Services/acs-aem-commons#3026]
* AEM Version:  6.5.12
* ACS AEM Commons Version: 5.1.0

Looking to move to AEMaaCS and as such ran Best Practices Analyser.

See the following 2 issues show up as Critical, Non-Compatible Changes - Content:

- The content stored at /apps/acs-commons/components/workflow/copy-properties by overriding (sling:superResourceType) the JCR path at /libs/cq/workflow/components/model/process might be incompatible after update and might need some adaption
- The content stored at /apps/acs-commons/console/templates/jcr:content/head/clientlibs by including (sling:resourceType) the JCR path at /libs/granite/ui/components/foundation/includeclientlibs might be incompatible after update and might need some adaption

Are you able to provide why this may be occurring and whether it is something that needs to be addressed by me?

/apps/acs-commons/components/workflow/select-agent itself has the same value for sling:superResourceType as /apps/acs-commons/components/workflow/copy-properties, yet it doesn't appear in the report.

Thanks

**Comment by davidjgonzalez** [comment]
Nothing required to be addressed by you. This appears to be a false positive in the BPA actually - as this node space isnt protected in 6.5 or in latest AEM CS.

![2023-01-19 at 9 47 AM](https://user-images.githubusercontent.com/1451868/213473004-204a86b2-ced8-4eda-a47f-f4e0287d4e99.png)
