### ISSUE TITLE
Redirect Map - Redirects are not working on AEM Cloud

### ISSUE THREAD

**Issue by n-spandana** [Adobe-Consulting-Services/acs-aem-commons#3027]
## Required Information

* [ ] AEM Version: AEM Cloud
* [ ] ACS AEM Commons Version: 5.4.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

Redirects should be working

### Actual Behavior

Redirects not working

### Steps to Reproduce

We made the configurations suggested at https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-map-manager/index.html. We enabled redirect paths, but redirects were not working.

We tried on AEM Cloud vanilla instance(New instance without any project code), but still we couldn't observe redirects.

Please do let us know if there is anything more we need to check/enable/configure on AEM cloud for the redirects to work.

**Comment by YegorKozlov** [comment]
Redirect Maps is incompatible with AEMaaCS, see the yellow banner in the documentation. Please use [Redirect Manager](https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-manager/index.html) instead.

**Comment by n-spandana** [comment]
We tried both Redirect Map and Redirect Manager, both were not working.
