### ISSUE TITLE
Redirect Manager - Redirects are not working on AEM Cloud

### ISSUE THREAD

**Issue by n-spandana** [Adobe-Consulting-Services/acs-aem-commons#3028]
## Required Information

* [ ] AEM Version: AEM Cloud
* [ ] ACS AEM Commons Version: 5.4.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

Redirects should be working

### Actual Behavior

Redirects not working

### Steps to Reproduce

We made the configurations suggested at https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-manager/index.html. We enabled redirect paths, but redirects were not working.

We tried on AEM Cloud vanilla instance(New instance without any project code), but still we couldn't observe redirects.

Please do let us know if there is anything more we need to check/enable/configure on AEM cloud for the redirects to work.

**Comment by fbonheurCap** [comment]
We are facing the same issue. Configuration works properly on local environment and fails on AEMaaCS instances.

**Comment by YegorKozlov** [comment]
I can't help much without additional information. 

- did you add the `com.adobe.acs.commons.redirects.filter.RedirectFilter` OSGi configuration?  It should be active on both author and publish tiers. 
- did you replicate the redirects? 
- export your redirects into a spreadsheet and attach to this ticket. I wonder  if the rules are incorrect. 
- show how you test it and what are the response headers.

**Comment by n-spandana** [comment]
OSGI Configuration is enabled both on author and publish instances
Author:
![image](https://user-images.githubusercontent.com/123091679/214014842-2bef5b85-63fa-415f-9e7a-afef597bfb09.png)
Publish:
![image](https://user-images.githubusercontent.com/123091679/214014986-32e73a5c-ee28-4562-b95d-6814b9524ab5.png)

Redirect Paths:
Author Instance:
![image](https://user-images.githubusercontent.com/123091679/214015126-ea556242-d967-40a7-be17-191d9637b0b4.png)
Publish Instance:
![image](https://user-images.githubusercontent.com/123091679/214015208-6b32de16-889c-4560-ad1d-a0a439dc8c9c.png)

I am testing the redirects by hitting the source endpoint on publish instance.
i.e. http://localhost:4503/content/test-project/language-masters/en/components.html

When the above URL is hit, we find the below information in the network tab.
![image](https://user-images.githubusercontent.com/123091679/214015771-1bdc9513-a986-4c30-ba7f-bee6a1da8d2a.png)

**Comment by YegorKozlov** [comment]
I can't reproduce it with aem-sdk-2023.1.10675.20230113T110236Z-220900 and the latest ACS Commons  5.5.2

I'm running a vanilla installation + wknd site

<img width="994" alt="image" src="https://user-images.githubusercontent.com/2543854/214056208-9c25aad0-6d4c-44e6-8e93-7de588487a01.png">

the redirect is working fine, both in the browser and in console:

```
$ curl -I http://localhost:4505/content/wknd/language-masters/en/about-us.html
HTTP/1.1 302 Found
Date: Mon, 23 Jan 2023 13:33:04 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Location: /content/wknd/language-masters/en/adventures.html
Content-Length: 0
```

Please create a debug logger on `com.adobe.acs.commons.redirects ` and see the messages.  It should shed light on it.

**Comment by n-spandana** [comment]
Created a logger for com.adobe.acs.commons.redirects (Debug Mode).
When redirects are published from author instance below logs were observed
Author:
![image](https://user-images.githubusercontent.com/123091679/214293645-b73aab3c-22d3-4763-8952-7bd3913db5dc.png)
Publish:
![image](https://user-images.githubusercontent.com/123091679/214293689-6606ed25-a50e-448a-b5ad-283a099dda98.png)

When the source page, i.e. a page for which redirect has been enabled is accessed from the browser on publish instance, no logs were observed.

**Comment by YegorKozlov** [comment]
@n-spandana please change the level to TRACE and try again . There are must be traces of what's happening.

**Comment by n-spandana** [comment]
Have set the log level to Trace. And the observed logs:
![image](https://user-images.githubusercontent.com/123091679/214297426-670c4aef-f343-4c0f-8abb-ba0b05c0df6c.png)
Screenshot of redirects enabled on publish:
![image](https://user-images.githubusercontent.com/123091679/214297575-8bfdcf3d-f3e5-4748-ab38-857eed32dc08.png)
Redirect Configuration Enabled:
![image](https://user-images.githubusercontent.com/123091679/214297726-d220e024-43a6-4330-b04b-b038541ec567.png)

**Comment by YegorKozlov** [comment]
Your localhost:4503 instance seems to be running in the author runmode.  Check the crx-quickstart/bin/start script, it should set `CQ_RUNMODE='publish'`:

```
if [ -z "$CQ_RUNMODE" ]; then
	CQ_RUNMODE='publish'
fi
```

You can also check the runmode in the JMX console: http://localhost:4503/system/console/jmx/java.lang%3Atype%3DRuntime

**Comment by davidjgonzalez** [comment]
@n-spandana  - To be clear, to use this on AEM SDK Author + Publish, you need to set both up w/ the proper runmodes, and then use the AEM classic Replication UI to setup the replication agent to publish changes from Author -> Publish (so you can author your Redirects on AEM Author SDK and then publish them to AEM Publish SDK for testing) ... you do not want to be starting AEM Publish SDK as an AEM Author and accessing authoring UIs on Publish ... this usecase is not tested/supported so things will likely break (as youre seeing)

**Comment by n-spandana** [comment]
Thanks
