### ISSUE TITLE
Redirect Manager: support for 307 and 308 redirects

### ISSUE THREAD

**Issue by sozores** [Adobe-Consulting-Services/acs-aem-commons#3031]
## Required Information

This is not a bug, but a request for feedback on supporting 307 and 308 redirection codes.

### Expected Behavior

As a Redirect Manager, when I set up a redirect I usually want to set a status code of 301 or 302, indicating a permanent or a temporary redirect. 
In some cases, though, a 307 or 308 is required, e.g. for some SPA functionality that will not work properly with a 301. 
Therefore, these values should also be available to support borderline cases out of the box. 

Adding these two codes will not increase the cost for ACS but if the case comes around for a client it will provide great value to be able to support it, otherwise, the client would have to adapt the core functionality of the ACS Commons value for something quite trivial.

**Comment by YegorKozlov** [comment]
@sozores here you go: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3034

<img width="562" alt="image" src="https://user-images.githubusercontent.com/2543854/214896032-c5bfe02d-677c-426f-b90a-39cbe5de504a.png">

**Comment by sozores** [comment]
Thank you @YegorKozlov !
