### ISSUE TITLE
ACS Commons Manage Redirect Console Giving Error

### ISSUE THREAD

**Issue by n-spandana** [Adobe-Consulting-Services/acs-aem-commons#3033]
## Required Information

* [ ] AEM Version:Cloud
* [ ] ACS AEM Commons Version: 5.4.0

###Issue
When we tried to open the Redirect Manager Console i.e. /apps/acs-commons/content/redirect-manager/redirects.html
![image](https://user-images.githubusercontent.com/123091679/214585816-e2b66d48-6ef4-41e6-be4d-ce5a5099b96a.png)

Logs:
25.01.2023 13:53:10.598 [cm-p84102-e748252-aem-author-579f8867c-thb4z] *WARN* [49.37.154.30 [1674654790551] GET /apps/acs-commons/content/redirect-manager/redirects.html HTTP/1.1] com.adobe.granite.metrics.knownerrors.impl.ErrorLoggingComponentFilter Exception in component: category=CUSTOMER_CODE, resourceType=acs-commons/components/utilities/manage-redirects/redirects, exceptionType=org.apache.sling.scripting.sightly.SightlyException, errorId=CUSTOMER, resource=/apps/acs-commons/content/redirect-manager/redirects/jcr:content, exceptionMessage = Compilation errors in org/apache/sling/scripting/sightly/apps/acs__002d__commons/components/utilities/manage__002d__redirects/redirects/redirects__002e__html.java:_Line 47, column 2400 : com.adobe.acs.commons.redirects.models.UpgradeLegacyRedirects cannot be resolved to a type_Line 84, column 7358 : com.adobe.acs.commons.redirects.models.Configurations cannot be resolved to a type
25.01.2023 13:53:10.600 [cm-p84102-e748252-aem-author-579f8867c-thb4z] *ERROR* [49.37.154.30 [1674654790551] GET /apps/acs-commons/content/redirect-manager/redirects.html HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught SlingException
org.apache.sling.scripting.sightly.SightlyException: Compilation errors in org/apache/sling/scripting/sightly/apps/acs__002d__commons/components/utilities/manage__002d__redirects/redirects/redirects__002e__html.java:_Line 47, column 2400 : com.adobe.acs.commons.redirects.models.UpgradeLegacyRedirects cannot be resolved to a type_Line 84, column 7358 : com.adobe.acs.commons.redirects.models.Configurations cannot be resolved to a type
	at org.apache.sling.scripting.sightly.impl.engine.compiled.SlingHTLMasterCompiler.compileSource(SlingHTLMasterCompiler.java:353) [org.apache.sling.scripting.sightly:1.4.18.140]
	at org.apache.sling.scripting.sightly.impl.engine.compiled.SlingHTLMasterCompiler.compileHTLScript(SlingHTLMasterCompiler.java:252) [org.apache.sling.scripting.sightly:1.4.18.140]
	at org.apache.sling.scripting.sightly.impl.engine.SightlyScriptEngine.compile(SightlyScriptEngine.java:66) [org.apache.sling.scripting.sightly:1.4.18.140]
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:386) [org.apache.sling.scripting.core:2.4.8]
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:191) [org.apache.sling.scripting.core:2.4.8]
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:500) [org.apache.sling.scripting.core:2.4.8]

**Comment by YegorKozlov** [comment]
Is the ACS Commons bundle up? I deployed the latest 5.5.2 and it's working fine to me:
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/2543854/214630285-0b091db8-b1d5-4dfc-bf74-31d30b1aa0a9.png">

**Comment by n-spandana** [comment]
Hi @YegorKozlov, 
We have deployed ACS commons as a maven dependency following the steps at https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html 

After the project is deployed, we found that acs-aem-commons-content, acs-aem-commons-ui.apps, acs-aem-commons-ui.content are installed. But the bundle didn't get installed.

Regards,
Spandana

**Comment by YegorKozlov** [comment]
@n-spandana Can you try the latest 5.5.2?
