### ISSUE TITLE
Using the ACS Commons include double namespaces dialog fields that are inside a mutli composite dialog field

### ISSUE THREAD

**Issue by hwillis2** [Adobe-Consulting-Services/acs-aem-commons#3040]
## Required Information

* [ ] AEM Version 6.5.13.0
* [ ] ACS AEM Commons Version: 5.3.2
* [ ] Reproducible on Latest? yes

### Expected Behavior

When using the provided acs-commons include options in dialogs `acs-commons/granite/ui/components/include` and using the ability to pass the `namespace` prop to namespace all included dialog options, the fields that are inside of mutli composite field won't be namespace with it's multi composite field.

### Actual Behavior

When using the provided acs-commons include options in dialogs `acs-commons/granite/ui/components/include` and using the ability to pass the `namespace` prop to namespace all included dialog options, the fields that are inside of mutli composite field are having their namespace twice.

### Steps to Reproduce

Use the acs-commons include to point to a dialog that contains a mutli composite field and set a namespace for the include. The container field does get namespace (correclty) but then the fields under the container gets namespaced again (now it won't save where it's needed to save to).

Ex:
Include
```
<include
  jcr:primaryType="nt:unstructured"
  namespace="test"
  sling:resourceType="acs-commons/granite/ui/components/include"
  path="/apps/test"/>
```
Dialog being included
```
<list
  jcr:primaryType="nt:unstructured"
  sling:resourceType="granite/ui/components/coral/foundation/form/multifield"
  composite="{Boolean}true">
  <field
      jcr:primaryType="nt:unstructured"
      sling:resourceType="granite/ui/components/coral/foundation/container"
      name="./container">
      <items jcr:primaryType="nt:unstructured">
          <label
            jcr:primaryType="nt:unstructured"
            sling:resourceType="granite/ui/components/coral/foundation/form/textfield"
            fieldLabel="Test Field"
            name="./fieldInMultifield"/>
      </items>
  </field>
</list>
```
The dialog will try to save this under `./test/container/item0/./test/container` when it should save under `./test/container/item0/./container`. It seems like the field in any mutli composite field is being namespaced (shouldn't be so it saves in the correct place under the container which has already been namespaced)

**Comment by chaitanyah** [comment]
Is any workaround available for this issue?

**Comment by niekraaijmakers** [comment]
@chaitanyah I am working on a fix, hopefully will be in next release.

**Comment by niekraaijmakers** [comment]
@chaitanyah fixed in the newest release.
