### ISSUE TITLE
Redirect Manager Import Spreadsheet Issue

### ISSUE THREAD

**Issue by gagandeepsaluja22** [Adobe-Consulting-Services/acs-aem-commons#3046]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: ___AEMaaCS SDK 2021.12.6151____
* [ ] ACS AEM Commons Version: _5.6.0____
* [ ] Reproducible on Latest? yes

### Expected Behavior

Redirect Manager import functionality should work without any issues.

### Actual Behavior

Redirect Manager import functionality is giving 400 Bad request error.

### Steps to Reproduce

1. Open the Redirect Manager on the AEM instance.
2. Go to Import tab and use the below CSV values (Create a sample CSV) -> Import the CSV

Source						Target						Status Code			Tags
/content/geometrixx/en/blog	/content/project1/us/en1	301					wknd-shared:	

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by YegorKozlov** [comment]
Can you please attach the input spreadsheet?
Redirect Manager imports from an Excel spreadsheet and you seem to be uploading a CSV file.

**Comment by YegorKozlov** [comment]
@gagandeepsaluja22  Importing from spreadsheet was improved in the latest release 5.7.0.  The attached spreadsheets worked fine for me. 
Also, instead of silent page reload user now gets a feedback dialog with the information which cell had what problem
