### ISSUE TITLE
ACS Commons System Notification scripts getting Added to XF while export to Target

### ISSUE THREAD

**Issue by sherinregi** [Adobe-Consulting-Services/acs-aem-commons#3049]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______ 6.5 sp 11
* [ ] ACS AEM Commons Version: _____ 4.7.0
* [ ] Reproducible on Latest? yes/no

### Expected Behavior
While system notification are enabled on author , when we export XF to target only XF code to be exported

### Actual Behavior
System Notification script is also getting exported. This causes unexpected behavior on the targeted page

### Steps to Reproduce

Configure ACS Commons System Notification
Create a new Experience Fragment
While the notification is enabled. Export the XF to target
Target Supported page shows unexpected behavior and this script is added to that.

**Comment by davidjgonzalez** [comment]
This was fixed in v5.5.0
