### ISSUE TITLE
[Redirect Manager] selecting a line prevents edit button to work

### ISSUE THREAD

**Issue by javabean** [Adobe-Consulting-Services/acs-aem-commons#3055]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEMaaCS 2023.1.10912
* [X] ACS AEM Commons Version: 5.6.0
* [X] Reproducible on Latest? yes (5.7.0)

### Steps to Reproduce

Create a Redirect Manager configuration and add at least 1 redirection rule.
Select the line by clicking on it.
Click the Edit button (pen icon); see screenshot 1

### Expected Behavior

Dialog to open to configure the redirection rule; see screenshot 2

### Actual Behavior

Clicking the Edit button does nothing.
See screen recording movie.

### Links

![redirect manager screenshot 1](https://user-images.githubusercontent.com/1197179/222467405-85231b4e-2e80-4467-88e6-f3a191d9f1f1.png)

![redirect manager screenshot 2](https://user-images.githubusercontent.com/1197179/222467438-45883309-7aeb-4c9b-9d9f-d4761ba2202b.png)

![redirect manager screen recording](https://user-images.githubusercontent.com/1197179/222467480-b5d19f02-1932-45dd-bb53-2ad47311aafc.mp4)

**Comment by YegorKozlov** [comment]
I was able to reproduce it and it sems to be a pecularity of the Coral Table component. 
When a table is declared as "orderable" then :
 - click on the drag handler (the icon in the rightmost cell) disables the Edit icon. This is true for any row.
 - click on any cell in the 1st row disables the Edit link in the 1st cell. This is true only for the 1st row, rows 2 and others are editable. 

@javabean Does it agree with your observations?

**Comment by davidjgonzalez** [comment]
Is this a bug with CoralUI, or something we can/should fix?

**Comment by YegorKozlov** [comment]
It seems to be a bug in Coral UI, but I'd like to see if there is a workaround. 
An orderable Coral table appends some unexpected styles on click . I wonder if we can overrider or cancel it. 

And it is a minor bug. Clicking on a drag handle disables the Edit icon, clicking on any other cell unlocks it back. So in the worst case user has to do an extra click to open the dialog.
