### ISSUE TITLE
AEM In Unified Shell, The Environment Indicator is displayed multiple times in site Page Editor 

### ISSUE THREAD

**Issue by sirgil2009** [Adobe-Consulting-Services/acs-aem-commons#3062]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [ ] ACS AEM Commons Version: _____
* [ ] Reproducible on Latest? yes/no

### Actual Behavior

As shown in the attached screenshot, When in Unified Shell, the Environment Indicator 
Label is being displayed multiple times in the Page. Apparently, this is caused by 
the ACS common component being inserted in every Iframe in the page.  This
behavior is reproducible in AEM Cloud - Skyline. 
### Steps to Reproduce
- Install the ACS common package on a Cloud Environment
- Configure ACS common in OSGI to give a label to the environment 
- (optional) install the weekend package sample project 
- Select a page and Click Edit. Notice there are multiple tabs showing the Environment Label. 
This seems to be happening because the label component is inserted in each Iframe that
is contained in the page. 

### Links
https://jira.corp.adobe.com/browse/SITES-11728
_Links to related assets, e.g. content packages containing test components_
![Screen Shot 2023-03-09 at 3 06 45 PM](https://user-images.githubusercontent.com/58415503/224181227-32041d7c-46b3-4882-a358-a7298c5e7e46.png)

**Comment by davidjgonzalez** [comment]
@sirgil2009 i assume the top most one is the one you want, correct?

![2023-03-13 at 4 56 PM](https://user-images.githubusercontent.com/1451868/224830479-2089ac23-827a-46a5-bd20-8a7201542c32.png)

This almost seems like a page editor thing, more than a UShell thing

**Comment by sirgil2009** [comment]
Hi @davidjgonzalez , Yes the top one is correct. It should only have just that one.
