### ISSUE TITLE
In AEM, ACS Commons getting overridden by custom configuration under path /apps/cq after build

### ISSUE THREAD

**Issue by psm1420** [Adobe-Consulting-Services/acs-aem-commons#3063]
We are working on AEM SDK 2023.1.10912.20230130T173736Z version & ACS Commons version is 5.0.10.

In our project we have a custom config which is residing under the same path /apps/cq/core/content/nav/tools where ACS Commons gets installed. So whenever we are giving the build the ACS Commons getting overridden by custom configuration, even after we have added <filter root="/apps/cq/core/content/nav/tools" mode="merge"/> in ui.apps (filter.xml). 

Please recommend any solution on this issue?

**Comment by psm1420** [comment]
We have tried the below changes but still ACS Commons is getting overridden,

Updated the ui.apps/src/main/content/META-INF/vault/filter.xml

<?xml version="1.0" encoding="UTF-8"?>
<workspaceFilter version="1.0">

	<filter root="/apps/cq/core/content/nav/tools/xyz"/>

</workspaceFilter>

Added overlay paths to the ui.apps.structure/pom.xml

                        <filter><root>/apps/cq/core</root></filter>
                        <filter><root>/apps/cq/core/content</root></filter>
                        <filter><root>/apps/cq/core/content/nav</root></filter>
                        <filter><root>/apps/cq/core/content/nav/tools</root></filter>
                        <filter><root>/apps/cq/core/content/nav/tools/xyz</root></filter>

**Comment by YegorKozlov** [comment]
Try  using the "merge" mode:  ` <filter root="/apps/cq/core" mode="merge"/>`
this way the existing content should be preserved

**Comment by davidjgonzalez** [comment]
@psm1420  what @YegorKozlov  suggested.
Also, your `ui.apps.structure` only needs the ANCESTORS of the subtree youre providing - since youre providing the `xyz` node/sub-nodes -- it doesnt need to be in the structure def (the structure is telling the installation what nodes it can expect to exist when installing this package).


```
<filter><root>/apps</root></filter>
<filter><root>/apps/cq</root></filter>
<filter><root>/apps/cq/core</root></filter>
<filter><root>/apps/cq/core/content</root></filter>
<filter><root>/apps/cq/core/content/nav</root></filter>
<filter><root>/apps/cq/core/content/nav/tools</root></filter>
```

**Comment by PoojaMahajanPS** [comment]
> Try using the "merge" mode: ` <filter root="/apps/cq/core" mode="merge"/>` this way the existing content should be preserved

its working...thanks for the solution!
