### ISSUE TITLE
[AEMaaCS] Cannot access selector in ACS COMMONS 404 error page

### ISSUE THREAD

**Issue by fbonheurCap** [Adobe-Consulting-Services/acs-aem-commons#3064]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: aem-sdk 2023.1.10912.20230130T173736Z-220900
* [ ] ACS AEM Commons Version: 5.7.0
* [ ] Reproducible on Latest? yes

### Steps to Reproduce

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

Configure ACS COMMONS Error handler feature
Create a simple component that display the sling request selectors
` <div>${request.requestPathInfo.selectors}</div>`

Create a 404 HTML page that embed the "selectors" component
Access a non existing page

### Expected Behavior

The selectors are displayed in the 404 error page thanks to the custom component

### Actual Behavior

The selectors are not displayed in the 404 error page.

**Comment by davidjgonzalez** [comment]
@fbonheurCap IIRC since youre in the context of a missing resource, this data isnt assumed (since it doesnt know what the resource actually is intended to be since there isnt a resource to resolve to). I believe you'd have to parse that data out of the request URI yourself (you could make a PathInfo object from it, and get the selectors off that).

**Comment by blair-robertson** [comment]
Hello, just a note for anyone else who has the problem. We discovered that it was not that the `selectors` where getting removed that caused the problem but the additon of the `.html` (configured via the `error-page.extension` osgi property) that causes internal include to remove the selectors.

Configuring this to a blank string allowed the selectors to be passed through but created a problem for the error page cache (which is based upon the path).

In the end we overrode the `404.jsp` and added the selectors from the current `slingRequest` into the path - so the cache key contained the selectors as well
