### ISSUE TITLE
PDF to PDF redirection not working

### ISSUE THREAD

**Issue by dagni06** [Adobe-Consulting-Services/acs-aem-commons#3074]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc:_AEM Cloud
* [ ] ACS AEM Commons Version: 5.3.4 (also tried with 5.7.0)
* [ ] Reproducible on Latest? yes

### Expected Behavior

While using PDF to PDF redirection in Dev Environment. It should hit 308/307/302/301 as set redirection in MANAGE REDIRECT.

### Actual Behavior

PDF to PDF redirection does not work in Dev environment. It is not hitting 308/307/302/301 as seen in the logs even when we try with the latest version of ACS Commons.

### Steps to Reproduce

1. Set a PDF to PDF redirection in your environment ( preferably your DEV environment where we have a fully functioning Dispatcher)
2. Publish the redirection.
3. Use the redirection in PUBLISH.

### Links

Not required

**Comment by davidjgonzalez** [comment]
Sorry - can you detail what feature youre using? Is it Redirect Manager? If so, can you provide exactly the rule set you're using, and what the resulting response is?

**Comment by YegorKozlov** [comment]
There are non-obvious gotchas with respect to redirecting assets.

1. page redirects are typically organised by context, e.g. when user requests a page in `/content/we-retail/*` , Redirect Manager will lookup rules in `/conf/we-retail` 

This is not the case with assets. DAM folders are not contextual and Redirect Manager will fallback to the default `/conf/global` configuration. This means you need to define your asset rules under `/conf/global/*` . 

2. It's a good idea to flush the Dispatcher and CDN caches after activating redirects. Redirect Manager operates in AEM, i.e. the request needs to reach AEM to be evaluated.

**Comment by dagni06** [comment]
Hi Yegor,

Thank you for the explanation. We were able to achieve the PDF to PDF/HTML redirections.

Regards,
Dhruv
