### ISSUE TITLE
Vulnerability with com.github.jknack:handlebars:jar:4.0.5 - please upgrade it to 4.2.0 or higher

### ISSUE THREAD

**Issue by vibhuranjan** [Adobe-Consulting-Services/acs-aem-commons#3075]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.15
* [x] ACS AEM Commons Version: 6.0.0 or later
* [x] Reproducible on Latest? yes

### Expected Behavior

No Vulnerabilities issues in scanning jar

### Actual Behavior

Vulnerabilities with one of the dependencies on acs commons bundle 6.0.0

### Steps to Reproduce

scan the jar. Vulnerabilities issues can be found here as well. https://mvnrepository.com/artifact/com.github.jknack/handlebars/4.0.5

**Can we use 4.2.0 or higher version.**

### Links

https://mvnrepository.com/artifact/com.github.jknack/handlebars/4.0.5

**Comment by davidjgonzalez** [comment]
This is a dependency provided by AEM.
