### ISSUE TITLE
errorpagehandler/default.jsp has a reference to a removed class

### ISSUE THREAD

**Issue by awadheshv** [Adobe-Consulting-Services/acs-aem-commons#3077]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.16.0
* [x] ACS AEM Commons Version: 6.0.2
* [x] Reproducible on Latest? yes

### Expected Behavior
503 Error pages are not working

### Actual Behavior
When a 503 error is triggered the page specified under errorPages should render

### Steps to Reproduce

please refer details below - let me know if more details needed.

### Links

The script `/apps/acs-commons/components/utilities/errorpagehandler/default.jsp` has a reference to class  `com.adobe.acs.commons.wcm.ComponentHelper` which has been removed as of [5.4.0](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/CHANGELOG.md#540)  and is failing as a result. hence no 503 error page.

**Comment by awadheshv** [comment]
> Any chance you can copy the PR'd JSP into your dev and just verify this works for you.
> 
> #3078

Yes, works for me. thank you.

**Comment by davidjgonzalez** [comment]
Fixed in 6.0.8
