### ISSUE TITLE
AngularJS directives for CoralUI Widgets

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#308]
Namely..
- Tag Selector
- Dropdown
- ~~Calendar/Date Time selector~~ (works as is)

**Comment by davidjgonzalez** [comment]
@ireasor 

Given the CUI Dropdown (see http://docs.adobe.com/docs/en/cq/current/touch-ui/coral-ui/index.html#Dropdown)

```
<div class="dropdown" data-init="dropdown">
    <button>Single Select</button>
    <select name="dropdown">
        <option ng-repeat="option in $scope.options" value="{{ option.value }}">{{ option.name }}</option>
    </select>
</div>
```

I'm pretty sure the above CUI dropdown list (or atleast the visual rendering on the page) doesnt change as $scope.options is modified.. the actual   This makes it hard to use it in ng-based interfaces.

It appears that CUI creates the Dropdown visual elements using dynamically created buttons/divs that are generated from the DOM options (i assume on load?)

Changing the option DOM elements after load does not sync to the dynamically created elements that display the actual dropdown. I expect on change something (CUI JS?) needs to be triggered to pull in the new options and re-draw the dynamic dropdown button/divs.

**Comment by justinedelson** [comment]
I've started to build some of these in the feature/coralui2 branch, but these are mostly designed to generate the CoralUI-required markup. The Select issue is a big one that I haven't figured out how to deal with as it involves, as @davidjgonzalez notes above resyncing the CUI JS. I've also found that (assuming your select uses ng-required or the like) that Angular doesn't detect the change in the widget value.

**Comment by davidjgonzalez** [comment]
FWIW I think the Datetime selector works as is (Its used on Bulk Workflow Removal)

**Comment by ireasor** [comment]
Sometimes it can tricky with what you bind to.  It is important to bind to an object that is not re-assigned so that you don't lose your reference.  I spent a little time playing around with this today and this seems to be working:

        <div class="coral-Form-fieldwrapper">
            <label class="coral-Form-fieldlabel">Workflow Model</label>
			<span class="coral-Select" data-init="form.workflowModel">
				<button type="button" class="coral-Select-button coral-MinimalButton">
					<span class="coral-Select-button-text">{{form.workflowModel.label}}</span>
				</button>
				<select
                    class="acs-select"
                    name="workflowModel"
                    ng-required="true"
                    ng-model="form.workflowModel"
                    ng-options="workflowModel as workflowModel.label for workflowModel in formOptions.workflowModels">
            	</select>
           </span>
        </div>

I was trying to get CoralUI select markup to render, but the hookup between the button and the select don't seem to line up properly (one doesn't open the other).  If you modify values externally via the DOM, I don't think that there is a way to get Angular to respect that.  Ideally, changes should be made to $scope and everything else should trigger from that.

**Comment by davidjgonzalez** [comment]
AngularJS is going the way of the dodo...
