### ISSUE TITLE
RedirectFilter mapUrls should be true by default

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#3089]
Currently the default value of `mapUrls` in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/40a40016cbbb5fc9cdd684ef60d2fc9505d3d7c3/bundle/src/main/java/com/adobe/acs/commons/redirects/filter/RedirectFilter.java#L143 is `false` by default which kind of contradicts the Sling/AEM defaults.
Mapping is usually applied everywhere where a path can be maintained. Therefore it is reasonable to also map the destination paths by default.
I fail to see the harm enabling this by default.

**Comment by YegorKozlov** [comment]
@kwin agree, there is no harm defaulting it to `true`. My only concern was performance. I thought that Sling mappings can introduce a delta in high-load systems and made it an opt-in feature.

**Comment by YegorKozlov** [comment]
the PR is https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3091
