### ISSUE TITLE
Documentation Update: NamedTransformImage Servlet

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#3096]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: ALL
* [x] ACS AEM Commons Version: ALL
* [x] Reproducible on Latest? yes

The documentation of the NamedImageTransformer should be extended. It should cover the fact, that the creation of renditions on-the-fly can be problematic, especially when the underlying image is large. In that case it can cause memory/garbage collection issues and even Out-Of-Memory situations, leading to overall slowdown of the instance up to a "crash" of the JVM.

Instead all required renditions should be pre-created using Processing profiles ([AEM CS](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/assets/manage/asset-microservices-configure-and-use.html?lang=en#custom-config); [AEM 6.x](https://experienceleague.adobe.com/docs/experience-manager-65/assets/administer/processing-profiles.html?lang=en
)); in this case the rendition will only be created once, and for that case more optimized solutions are available (for example the use of imagemagick on AEM 6.x, and assetCompute on AEM CS), which are much more suited for that case.

**Comment by davidjgonzalez** [comment]
@joerghoh This can be marked as not-compatible with AEM CS, especially now that we have web-optimized renditions (which is the proper way - better than using static renditions).

IIUC the on the fly renditioning is supported by AEM 6.5 since this is how the AEM Adaptive Servlet works.

**Comment by joerghoh** [comment]
Yeah, I think we should add the same warning also to the Core Components in case Renditions (of whatever size) are resized on the fly.

**Comment by davidjgonzalez** [comment]
@joerghoh so you want to write up the docs PR?

**Comment by joerghoh** [comment]
https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/pull/248

**Comment by joerghoh** [comment]
I added a warning whenever this servlet is used. And even if this warning is turned off, we will see that it is turned off :-)

https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3097
