### ISSUE TITLE
MCP Not running when perform Content Fragment Import

### ISSUE THREAD

**Issue by stephenkhoo** [Adobe-Consulting-Services/acs-aem-commons#3099]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: not sure where to check, but is 6.5+ sdk, and cloud
* [X] ACS AEM Commons Version: 6.0.8
* [ ] Reproducible on Latest? yes/no

### Expected Behavior

Import content fragment smoothly, or show some error to get the understanding of the situation

### Actual Behavior

After import start, it goes back to the list, and halt.
The started, completed both show n/a

<img width="1418" alt="Screenshot 2023-04-27 at 9 41 24 PM" src="https://user-images.githubusercontent.com/80662326/234882194-a8e9034b-9443-4c14-85fe-de4f67a4a3c6.png">

When click on the process, nothing pops-up.
And in console there's link to something like this, and its 404
http://localhost:4502/var/acs-commons/mcp/instances/561798D8A8E630F6.html

### Steps to Reproduce

Created content fragment model
And installed the ACS AEM Commons
MCP > Start process > Content Fragment Import
Then it shows like the actual bahaviour

I've tried with .csv .xlsx.

I've tried with process clean up, it works.

Thanks in advance.

**Comment by davidjgonzalez** [comment]
Is there anything in the error.log?

**Comment by stephenkhoo** [comment]
Just figured out I can find the error logs in crx-quickstart/logs/error.log

/apps/acs-commons/content/manage-controlled-processes/jcr:content.start.json HTTP/1.1] com.adobe.acs.commons.mcp.impl.ControlledProcessManagerServlet null -- End of line.
java.lang.NullPointerException: null

It throws a NullPointerException

**Comment by stephenkhoo** [comment]
Additional update:
.csv has error of not type OOXML
.xlsx only will get the NullPointerException


I think will only focus on the .xlsx problem

**Comment by davidjgonzalez** [comment]
Thanks for the update @stephenkhoo
