### ISSUE TITLE
Redirect Manager - AEM SPA not working

### ISSUE THREAD

**Issue by anshul-goyal-1** [Adobe-Consulting-Services/acs-aem-commons#3104]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.0.4
* [ ] ACS AEM Commons Version:6.0.4
* [ ] Reproducible on Latest? yes

### Expected Behavior

While setting up the redirect via the Redirect Manager,I need to add a redirect and after publish can redirect to the source page. We are using AEM SPA based implementation

### Actual Behavior

When I add a redirect, the page goes blank.

### Steps to Reproduce

1. Install the ACS Commons on AEM cloud service
2. Create a redirect from a source "/test/" to destination - "https://www.google.com"
3. Publish the redirect
4. Try to access the redirect via publisher (http://localhost:4503/test/) 

I get the blank page rather than it navigates to the destination page

### Links

_Links to related assets, e.g. content packages containing test components_

[redirect.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/11489496/redirect.zip)

**Comment by YegorKozlov** [comment]
Do you have [Sling Mappings](https://sling.apache.org/documentation/the-sling-engine/mappings-for-resource-resolution.html) to resolve _/test/_  to a full path , e.g. _/content/my-site/en/test_ ? 

If not, use the full JCR path, e.g. instead of _/test/_ the source should be _/content/my-site/en/test_

**Comment by anshul-goyal-1** [comment]
The use case is that there is no physical page in AEM with a full path that resolves to /test/, In the e-commerce application, we need to apply the rules to /test/ category which is coming from the commerce engine and then re-direct it to a place in AEM. So I can put a destination to a full path like /content/my-site/en/new-landing but the source will not be a page/location within AEM.
Hope this make sense

**Comment by YegorKozlov** [comment]
by default the Redirect Filter listens to /content/* requests:
![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/2543854/96f8aa02-f5fa-44f0-93ce-efb2d70adfad)

change it to an empty string to listen from the root. 
![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/2543854/7c9e1108-7bea-4e3a-9f49-15e14243c662)

(the value "/" won't work, it's a bug which I'm going to fix)


with these settings it worked to me:
<img width="845" alt="image" src="https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/2543854/23e0e707-fd73-4e21-89d1-88af036af89e">

```
curl -I  http://localhost:4503/test
HTTP/1.1 302 Found
Date: Wed, 17 May 2023 08:31:33 GMT
Location: https://www.google.com
Content-Length: 0
```

**Comment by anshul-goyal-1** [comment]
Thanks for the prompt reply and are you planning to release the fix for "/" soon or is there a roadmap for the same.

**Comment by anshul-goyal-1** [comment]
Thanks, I will keep an eye and update it. Thanks for the help

**Comment by YegorKozlov** [comment]
https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3105
