### ISSUE TITLE
Content Fragment Model not getting Saved while using a reference to another CF model

### ISSUE THREAD

**Issue by madhurkapooribm** [Adobe-Consulting-Services/acs-aem-commons#3121]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM Cloud as A Service

* [ ] Reproducible on Latest? Yes

While I'm creating a new content fragment model including the data type content fragment reference to another model, it is not saving the model. Not sure why is this happening?

any idea ?

![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/64793443/f11ab275-6b9a-409f-a0a0-a381d567dbc9)

**Comment by davidjgonzalez** [comment]
Hi - this sounds like an issue with AEM itself, and not ACS Commons. 

If this is ACS Commons related, can you please re-open and add the relevant details? Thanks!
