### ISSUE TITLE
Named Transform Image: Icons showing a white background

### ISSUE THREAD

**Issue by websstone** [Adobe-Consulting-Services/acs-aem-commons#3124]
## Required Information

* [x] AEM Version: last AEMaaCS (2023.4.11873.20230421T153841Z)
* [x] ACS AEM Commons Version: 6.0.6
* [x] Reproducible on Latest? yes

### Expected Behavior
Round icons rendered with transparent background  

### Actual Behavior
Image rendered with white background

### Steps to Reproduce
![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/1935061/6dfc0aca-2d60-4940-a176-22cf96c1cb6b)

1. Start the vanilla instance.
2. Upload ACS Commons Package
3. Configure ACS AEM Commons - Named Image Transformer Factory with below configuration
      Transform Name : default
      Image Transformers : quality:quality=75
7. Upload an attached image to DAM
8. Open the image with configured transformation like /content/dam/image.png.transform/default/image.png
10. See the background of the image

### Links
Image: ![Icon](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/1935061/29ab888b-41ed-4361-a856-246f1011c33b)

**Comment by davidjgonzalez** [comment]
Can you double check that the web rendition for this asset is in fact a PNG w/ transparency?

PNG transparency should "just work" ... but this servlet picks the WEB rendition of an asset to transform, so if that web rendition doesnt have transparency, etc. then the resulting image wont either.

**Comment by websstone** [comment]
@davidjgonzalez  Thanks a lot for your response!
You are right, I see that this image has a **png** extension for thumbnails + original, but the web rendition has **jpeg** format.
Seems like it was created by [default configuration](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/assets/manage/asset-microservices-configure-and-use.html?lang=en#default-config), which cannot be modified, might be you can advise how to deal with that issue (it's should be something pretty common)

**Comment by websstone** [comment]
I see configuration "prop.asset-rendition-picker-regex" so the original image can be specified for example - looks like a solution
thank a lot for your response and sorry for the silly question

**Comment by davidjgonzalez** [comment]
@websstone You got it! The `prop.asset-rendition-picker-regex` lets you pick what rendition you want; so you could have it pick original. The trick is to make sure you arent transforming monster source images as this can take up AEM resources. 

For some reason, i thought OOTB web rendition would get generated in the same format (atleast PNG, JPG) as the original asset, but i must be misremembering.
