### ISSUE TITLE
Generic List not working on AEM Cloud Publish 

### ISSUE THREAD

**Issue by n-spandana** [Adobe-Consulting-Services/acs-aem-commons#3125]
### Fix

AEM CS Publish is deny by default on `/etc` so you must set ACLs on your generic lists to allow access. 

I've added an example of allowing everyone (anonymous) access to all Generic Lists via RepoInit:

https://adobe-consulting-services.github.io/acs-aem-commons/features/generic-lists/index.html#generic-lists-access-on-aem-publish

This can of course be scoped to whatever users/groups you need to scope access to.

## Required Information

* [x] AEM Version: AEM Cloud
* [x] ACS AEM Commons Version: 5.5.2
* [x] Reproducible on Latest? yes

### Expected Behavior

Generic List should be available on Publish instance

### Actual Behavior

Generic List not available in publish instance

### Steps to Reproduce

Generic List created and pushed via code deployment. Generic List is available on the author instance, but not on the publish instance.
<filter root="/etc/acs-commons/lists/xxx/comparison_table_values" mode="merge"/> is added

**Comment by ChuckGlidewell** [comment]
This issue is happening for me as well. My Generic Lists are created and published via the Generic List editor.

**Comment by Abhishek-F-Secure** [comment]
not working for me too? any resolution for this?

**Comment by n-spandana** [comment]
By enhancing the permissions of the system-user for the Generic List path, i.e. /etc/acs-commons/lists addressed the issue.

**Comment by davidjgonzalez** [comment]
@n-spandana can you expound? Which system-user did you have to add ACLs to? and which ACLs exactly? jcr:read?

**Comment by Abhishek-F-Secure** [comment]
@n-spandana @davidjgonzalez I faced the same issue and moved the lists under /content...that is not the optimal solution tough, it will require change in default acs files also to make it editable, which might be more complex, even if I do so, I think with next deployment it will overwrite my changes..we should have more optimal solution. So mostly It will be with permissions I think for "anonymous" user?

**Comment by n-spandana** [comment]
To address the issue, I have enhanced the permissions of the serviceuser created for the project and enhanced the permissions of the service user for the path /etc/acs-commons/list with permissions similar to that of /content/project.

To access the generic list I used the following:
            Map<String,Object> param = new HashMap<>();
            param.put(ResourceResolverFactory.SUBSERVICE,"serviceuser");
            resourceResolver = resourceResolverFactory.getServiceResourceResolver(param);
           PageManager pageManager = resourceResolver.adaptTo(PageManager.class);
            Page genList = pageManager.getPage("/etc/acs-commons/lists/project/generic-list");
            ListIterator<GenericList.Item> gList = genList.adaptTo(GenericList.class).getItems().listIterator();
