### ISSUE TITLE
ACS redirects weren't working in Publish environments with ACS AEM Commons 6.0.10 version

### ISSUE THREAD

**Issue by Ashwini-UOC** [Adobe-Consulting-Services/acs-aem-commons#3126]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _____AEM 6.5., SP15, Forms add on(6.0.856), Forms Compat(2.0.48), Core WCM 2.21.2
* [ ] ACS AEM Commons Version:  6.0.10
* [ ] Reproducible on Latest? yes

### Expected Behavior

The redirects configured in the path (<SERVER>/apps/acs-commons/content/redirect-manager/redirects.html) are not working in the prod publishers alone with our little customised code. But it works fine in Prod Author instance as well as all stage instances with the customised code.

### Actual Behavior
The redirects are not working in the prod publishers alone.

### Steps to Reproduce

With AEM 6.5, proceed to install SP15, Forms add on(6.0.856), Forms Compat(2.0.48), Core WCM 2.21.2 and ACS 6.0.10 and installing our customised code. And then try out the redirects.

**Comment by YegorKozlov** [comment]
Redirects are working fine to me with ACS AEM Commons  v6.0.10. 

Please check that the redirect filter is enabled on Prod Publisher instances. 
If the problem is still reproducible, create a debug logger on `com.adobe.acs.commons.redirects`  and see the messages. It should shed light on it.

**Comment by davidjgonzalez** [comment]
@Ashwini-UOC any luck getting this to work (or steps to reproduce it not working?)

**Comment by Ashwini-UOC** [comment]
OOTB ACS works fine with 6.0.10, our customisation doesn't work in prod publishers, whereas it works in prod author. Now my lead is checking on that. 

Thanks for checking this.
