### ISSUE TITLE
Dispatcher Flush Rules are applicable in AEM Cloud on Publish side

### ISSUE THREAD

**Issue by royteeuwen** [Adobe-Consulting-Services/acs-aem-commons#3127]
I see that it mentions in the docs that the dispatcher flush rules are not applicable for AEM Cloud, but they are definitely working on the publish side, where you should place your flush agent anyway.

Can the docs be adapted?
https://adobe-consulting-services.github.io/acs-aem-commons/features/dispatcher-flush-rules/index.html

**Comment by davidjgonzalez** [comment]
@royteeuwen You can't configure replication agents for AEM Publish tho, right?
So i assume this is limited to "hierarchical flushes", and wont support resource-only flushing?

**Comment by davidjgonzalez** [comment]
Released in 6.0.14

**Comment by royteeuwen** [comment]
@davidjgonzalez can you tell me what is released in 6.0.14? Because the documentation page I sent still shows the yellow box at the top that it is cloud incompatible

**Comment by davidjgonzalez** [comment]
@royteeuwen sorry - got this issue mixed up w/ the Dispatcher Flush UI working on AEM Publish. Do you know about my Q above? I'd like to call out any incompatibilities w/ AEM CS even if it does mostly work.

**Comment by royteeuwen** [comment]
I have no idea about the resource-only flushing. The Replication API is available though and a flush agent exists on AEM Cloud Publish, so the system does work for the use-cases we did so far.

**Comment by davidjgonzalez** [comment]
@royteeuwen I adjusted the message on the page: 

https://adobe-consulting-services.github.io/acs-aem-commons/features/dispatcher-flush-rules/index.html

Feel free to re-open if you think it could be worded better.

**Comment by kwin** [comment]
@royteeuwen In the mid term we anyways have to ship separate packages for Classic and Cloud, similar to what is done in https://github.com/adobe/asset-share-commons. There the Cloud distribution uses another bundle fragment on top of the bundle that also ships for Classic (https://github.com/adobe/asset-share-commons/blob/develop/core.cloud/pom.xml). Maybe you can prepare a PR using that approach?

**Comment by royteeuwen** [comment]
@kwin  sure that's possible. 
Is there a good reason to make it a fragment instead of making it an entire new bundle? I haven't worked extensively with fragments yet, but I guess it will have access to private packages, compared to just another bundle?

**Comment by kwin** [comment]
Yes, the primary reason is that the fragment has access to all private packages.

**Comment by royteeuwen** [comment]
@kwin  @davidjgonzalez  I have an open PR at Sling's side to get this fixed (in a nice manner) in AEMaaCS:
https://issues.apache.org/jira/browse/SLING-11991

The other option to get this working in the current sling distribution is to make an ImportPostProcessor / InvalidationProcessor that has a higher ranking than the current one provided by granite. This one could then execute the DispatcherFlushRules and have a reference to the granite one and execute that one afterwards.

**Comment by davidjgonzalez** [comment]
FYI - removed the partial AEM CS compatibility from the docs for now.
