### ISSUE TITLE
Acs commons repoint error with AEM cloud manager 

### ISSUE THREAD

**Issue by MJDemo123** [Adobe-Consulting-Services/acs-aem-commons#3131]
I am facing issue with acs commons latest version whil deploying on AEM cloud manager .

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: ___ AEM cloud____
* [ ] ACS AEM Commons Version: _____6.0.10
* [ ] Reproducible on Latest? yes/no   yes 

### Expected Behavior

Acs commons shall deploy with main code without errors on AEM as cloud

### Actual Behavior

Acs commons gives repository repoint error while deploying to cloud instance 

[Apache Sling Repository Startup Thread #1] com.adobe.granite.repository.impl.SlingRepositoryManager Exception in a SlingRepositoryInitializer, SlingRepository service registration aborted
javax.jcr.RepositoryException: Applying repoinit operation failed despite retry; set loglevel to DEBUG to see all exceptions. Last exception message was: [Session.save](http://session.save/) failed: javax.jcr.nodetype.ConstraintViolationException: OakConstraint0001: /etc/acs-commons[[nt:folder, rep:AccessControllable]]: No matching definition found for child node redirect-maps with effective type [nt:unstructured]

**Comment by davidjgonzalez** [comment]
@MJDemo123 can you take a look at https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/9d9b4ee23bcb7428d6366a27bebd125b1038bc0c and see if that looks like it will resolve the issue?

I believe the originating, conflicting node is defined here (with the correct node type).

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/ui.content/src/main/content/jcr_root/etc/acs-commons/redirect-maps/.content.xml

**Comment by davidjgonzalez** [comment]
Fixed in 6.0.12

**Comment by MJDemo123** [comment]
hi @davidjgonzalez  6..0.12 has dependency on package adobe/cq650/servicepack:aem-service-pkg:6.5.10 
We are getting above issue on aem as cloud services

**Comment by MJDemo123** [comment]
![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/139107417/df77a0a7-7ac6-4cf4-840e-a7acea2a2430)
