### ISSUE TITLE
Acs commons repoint error with AEM cloud manager 

### ISSUE THREAD

**Issue by MJDemo123** [Adobe-Consulting-Services/acs-aem-commons#3136]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: ___AEM cloud____
* [ ] ACS AEM Commons Version: _____6.0.12
* [ ] Reproducible on Latest? yes/no yes

### Expected Behavior

Acs commons shall deploy successfully in cloud

### Actual Behavior

Acs commons 6.0.122 gives with cloud deployment -> Error while assembling launcher: Package has unresolved dependencies: adobe/cq650/servicepack:aem-service-pkg:6.5.10

![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/139107417/f18f83a7-9ab1-4b33-902b-f562fa4c4e79)

**Comment by kwin** [comment]
Duplicates #3135
