### ISSUE TITLE
Redirects per project don't work

### ISSUE THREAD

**Issue by arianna-marzilli-cs** [Adobe-Consulting-Services/acs-aem-commons#3144]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: Cloud
* [x] ACS AEM Commons Version: 6.0.14
* [x] Reproducible on Latest? yes

I've been trying to create redirects on our environment but I'm having an issue with the creation of different configurations for each site.

If I create a redirect in /conf/global I am able to verify it, if I create the redirect in /conf/project, that won't work.

**Comment by YegorKozlov** [comment]
Redirect Manager performs a lookup based on the content and it’s contextual `cq:conf` property to find the appropriate configuration. If `cq:conf` is not set then `/conf/global` is used as a fallback, e.g.


content tree:
```
/content/we-retail
    + jcr:content
      - cq:conf = "/conf/we-retail"
```

configuration:
```
/conf/we-retail
    + settings
      + redirects
        + rule-1
            - source = "/content/we-retail/page1"
            - target = "/content/we-retail/page2"
            - statusCode = 302
```

For example, when user requests /content/we-retail/page1
- AEM goes up the content tree until a resource with the `cq:conf` property is found: `/content/we-retail/jcr:content@cq:conf`
- Check if a configuration resource exists at the path the property points to: `/conf/we-retail`
- Check if the redirect configuration exists below the configuration resource: `/conf/we-retail/settings/redirects`
- Use `/conf/global` as fallback path

**Comment by kwin** [comment]
Implementation details for lookup of CACs are also explained in https://sling.apache.org/documentation/bundles/context-aware-configuration/context-aware-configuration-default-implementation.html
