### ISSUE TITLE
ACS Commons MCP reports are not getting downloaded

### ISSUE THREAD

**Issue by surbhi-choudhary** [Adobe-Consulting-Services/acs-aem-commons#3145]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM Cloud : 2023.7.12790.20230720T124230
* [x] ACS AEM Commons Version: 5.4.0
* [x] Reproducible on Latest? yes/no Yes

### Expected Behavior
ACS-Commons Manage Controlled Process reports can be downloaded via the download button

### Actual Behavior

We have upgraded our AEM cloud version to feature release 2023.7.12790.20230720T124230Z and have noticed that the MCP reports are not getting dowloaded. 
This is happening on Production and Non Prod instances. 

Error Logs:
20.07.2023 04:32:21.645 [cm-p69603-e836309-aem-author-7474bc7f9f-m5l6r] *ERROR* [203.16.33.254 [1689827541570] GET /var/acs-commons/mcp/instances/0D984CE29508B281/jcr:content/report.xlsx HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.NoSuchMethodError: org.apache.poi.xssf.usermodel.XSSFColor.<init>(Ljava/awt/Color;)V
at com.adobe.acs.commons.mcp.impl.GenericReportExcelServlet.createHeaderStyle(GenericReportExcelServlet.java:140)
at com.adobe.acs.commons.mcp.impl.GenericReportExcelServlet.createSpreadsheet(GenericReportExcelServlet.java:99)
at com.adobe.acs.commons.mcp.impl.GenericReportExcelServlet.doGet(GenericReportExcelServlet.java:68)
at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:266)

<img width="1073" alt="Screenshot 2023-07-21 at 10 41 30 am" src="https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/140570080/f2d2835f-99c0-4320-87cf-c6cd2343ab86">

**Comment by YegorKozlov** [comment]
please upgrade to the latest release v6.0.14
It has to do to internal upgrade of Apache POI, the library used to generate Excel reports.

https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3128
