### ISSUE TITLE
Get DispatcherFlushRules working again on AEMaaCS

### ISSUE THREAD

**Issue by royteeuwen** [Adobe-Consulting-Services/acs-aem-commons#3148]
The current implementation depends on the `Preprocessor` interface, which is no longer used by Sling Content Distribution on AEMaaCS.

I have an open PR at Sling's side to get it fixed (in a nice manner) in AEMaaCS to be able to provide custom ImportPostProcessors:
https://issues.apache.org/jira/browse/SLING-11991

Afterwards we can implement an ImportPostProcessor that would trigger the existing DispatcherFlushRules for AEMaaCS

**Comment by royteeuwen** [comment]
See also https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3127

**Comment by royteeuwen** [comment]
@davidjgonzalez  Konrad approved the PR, could you also have a look and see how we will be doing the releases in the future?

**Comment by kwin** [comment]
Fixed in 6.0.14
