### ISSUE TITLE
Redirect Manager - Not working with Latest AEM as a Cloud Service Version (2023.7.12874.20230726T072051Z)

### ISSUE THREAD

**Issue by anshul-goyal-1** [Adobe-Consulting-Services/acs-aem-commons#3155]
## Required Information

* [2023.7.12874.20230726T072051Z ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 2023.7.12874.20230726T072051Z 
* [ 6.0.4] ACS AEM Commons Version: 6.0.4
* [ Yes] Reproducible on Latest? Yes

### Expected Behavior

1. Test environment for AEM Cloud as a service is updated to version **2023.7.12874.20230726T072051Z** and the Redirect Manager Plugin v6.0.4 - The new redirects must work
2. Prod version of AEM as a cloud service **2023.7.12790.20230720T124230Z** and the Redirect Manager Plugin v6.0.4 - The new redirects must work

### Actual Behavior

1. The new redirects don't work on the versions mentioned above
2. The State column is empty for new Redirects

### Steps to Reproduce

Update the version, create the redirect and then publish

![Screenshot 2023-08-08 at 15 45 25](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/133237064/8860eb1c-e700-44dc-be12-f9e2ae29c897)

### Links
http://localhost:8080/test2/ https://www.google.com

**Comment by anshul-goyal-1** [comment]
Hi There, any thoughts on this issue @YegorKozlov or Team

**Comment by YegorKozlov** [comment]
@anshul-goyal-1 I don't see anything wrong with Redirect Manager.
I tried the 2023.7.12874.20230726T072051Z. and the latest build from master and all worked for me. 

Could you create a DEBUG logger on `com.adobe.acs.commons.redirects`  , run some tests and attach the results ?

**Comment by anshul-goyal-1** [comment]
Thanks @YegorKozlov - It has worked after the latest maintenance release was applied on the cloud service by Adobe. So closing this issue and thanks for your support
