### ISSUE TITLE
ACS - common redirect manager publish issue

### ISSUE THREAD

**Issue by NivethaSelvakumar95** [Adobe-Consulting-Services/acs-aem-commons#3161]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______AEM cloud
* [ ] ACS AEM Commons Version: _____
* [ ] Reproducible on Latest? yes/no - yes

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._
We should be able to publish the changes from redirect manager

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._
We are unable to publish the latest date is not updating
[redirect-manager-publish-issue.webm](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/38250363/c1c8c0a2-af6a-478e-9058-153a3b1fa7ca)
<img width="872" alt="publish-redirect-manager" src="https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/38250363/3f2b2b82-0e7b-4659-bfe3-a9bf83072522">

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_
Hi,
We are facing issue in the author instance while trying to publish any page or content they are getting published and it is still showing the old publish date. The queue is not blocked and there is no error found in the logs as well. Refer to the attached screenshot and video reference. We noticed that there is an auto maintenance activity done on our environment not sure whether because of this the issue is occurring.

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by YegorKozlov** [comment]
I can't reproduce it with ACS Commons 6.0.14 and AEM 2023.6.12441.20230623T133322Z-230702

Are you able to publish pages and assets?

**Comment by NivethaSelvakumar95** [comment]
Hi @YegorKozlov 

Yes I am able to publish pages and assets.
![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/38250363/d4c341ba-1324-4e03-b5c7-550c577c1b1e)
AEM version - 2023.7.12874.20230726T072051Z
ACS-AEM commons - 6.0.8

**Comment by YegorKozlov** [comment]
do you have permissions to replicate resources under `/conf/*`  ?

**Comment by journeycruz-ping** [comment]
Hello @YegorKozlov,

I'm not associated with the original post, but I'm addressing this issue as my team and I are encountering the same problem today.

AEM Version: 2023.7.12874.20230726T072051Z
ACS-AEM Commons Version: 5.0.6

Steps to Reproduce:

- Add a new redirect rule using ACS Commons Redirect Manager
- Publish the content (note the date remains unchanged).
- The new rule is not visible in the redirect manager search.
- Check page properties for the rule; redirect input field is blank.
- Despite no visible rules, the source URL still redirects.


The redirect rules seem to publish based on logs but are not editable in the Touch UI.

User permissions for replicating resources under `conf/*` remain unchanged.

I've tested on an AEM version similar to the one you mentioned (2023.6.12441.20230623T133322Z-230600), and everything works fine. This issue appears to affect newer versions of AEM as a Cloud Service.

**Comment by kwin** [comment]
Please update to a newer version. AEM Cloud release 13173 lists the following fix (https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/release-notes/maintenance/latest.html?lang=en) which may be related:

> Fixed Issues
SITES-15463: Sites Templates - Templates cannot be published.

**Comment by journeycruz-ping** [comment]
That's a good suggestion. However, even after testing with AEM v2023.7.12874.20230726T072051Z and ACS AEM Commons v6.0.14, I can still reproduce this issue by following the steps I mentioned earlier.

**Comment by kwin** [comment]
12874 is older than 13173. You really need to test with the version released today.

**Comment by journeycruz-ping** [comment]
That fixed it for us. Thanks!
