### ISSUE TITLE
Renovator tool not removing old source path

### ISSUE THREAD

**Issue by jeyuen** [Adobe-Consulting-Services/acs-aem-commons#3162]
## Required Information

* [ ] AEM Version: AEM Cloud
* [ ] ACS AEM Commons Version: 5.4.0
* [ ] Reproducible on Latest? Yes

### Expected Behavior

When moving pages from one folder to another, the old source path should be completely removed from the Publish instance.

### Actual Behavior

When moving pages from one folder to another, the old source will be unpublished which removes the jcr:content node. However, it fails to remove the actual cq:Page node i.e. an empty node/orphan page is left behind. These page nodes are being picked up by our site wide search, which is causing issues.

### Steps to Reproduce

1. Navigate to the renovator tool

2. Either import a spreadsheet to move multiple pages or enter a single page move:
Source: `/content/site/en/folder-1/my-page`
Destination: `/content/site/en/folder-2/my-page`

3. Populate the remaining fields with these options:
-  Max references = `-1`
- Publish = `self-managed`
- Check `Create versions`
- Check `Update status`
- Check `Dry run`
- Check `Audit trails`
- Check `Detailed report`

5. If dry run does not result in any errors, uncheck "dry run" and proceed to execute the actual page move(s)

6. After the execution finishes, there should be no error reports and execution report shows all moves from source and target paths have passed.

7. Navigate to your old page path on author: http://localhost:4502/sites.html/content/site/en/folder-1. Check that `my-page` is no longer there.

8. Navigate to the new page destination on author http://localhost:4502/sites.html/content/site/en/folder-2/my-page. Check that `my-page` is there and publish it.

9. Navigate to the publish instance. If replicating on cloud server, go to the repository browser in the developers console.
If replicating this on your local, go to http://localhost:4503/crx/de/index.jsp#/content/site/en/folder-1/my-page. Notice how this is an empty node where the cq:Page node is still there, but the content has been removed making it an incomplete removal. Instead `my-page` should not appear at all.

<img width="217" alt="image" src="https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/135186875/446edb1c-5fff-4272-8855-0b7e3abbdaf3">

**Comment by jeyuen** [comment]
Can we please get an update on this - this issue is still ongoing.

**Comment by YegorKozlov** [comment]
The Renovator tool delegates the actual move to `PageManager#move` where the 4th argument is a boolean flag `shallow` which was set to `true`. 
It appears when shallow is true then `PageManager#move` only moves the `jcr:content` node leaving the parent `cq:Page` node intact.  Setting shallow=false fixed the problem.
