### ISSUE TITLE
ACS Commons 6.1.0 - Generic List can't get Repository Initializer to make generic lists available on AEMaaCS Publish

### ISSUE THREAD

**Issue by eagleinhills** [Adobe-Consulting-Services/acs-aem-commons#3186]
## Required Information

* [ AEMaaCS - 2023.8.13206.20230821T124823Z ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [ 6.1.0 ] ACS AEM Commons Version: _____
* [yes ] Reproducible on Latest? yes/no

### Expected Behavior
Following the instruction on how to make the Generic Lists available on the AEMaaCS publish as defined here should work:

https://adobe-consulting-services.github.io/acs-aem-commons/features/generic-lists/index.html#generic-lists-access-on-aem-as-a-cloud-service-publish

### Actual Behavior

The code snippet should work 

### Steps to Reproduce

Following the instruction on how to make the Generic Lists available on the AEMaaCS publish as defined here:

https://adobe-consulting-services.github.io/acs-aem-commons/features/generic-lists/index.html#generic-lists-access-on-aem-as-a-cloud-service-publish

This is the Config Json I am using:
Name of the file:
**org.apache.sling.jcr.repoinit.RepositoryInitializer~acs-commons-generic-lists-publish.cfg.json**

in the folder **ui.config/src/main/content/jcr_root/apps/my-app/osgiconfig/config.publish**

**Content of the file:**
`
{
    "scripts": [
        "create path /etc/acs-commons(sling:OrderedFolder)/lists(sling:OrderedFolder)",
        "set ACL for everyone",
        "allow jcr:read on /etc/acs-commons/lists"
    ]
}
`

The error I am getting is:
[ERROR] The analyser found the following errors for publish : 
[ERROR] [repoinit] repoinit: Parsing error in repoinit from extension : Encountered " "create" "create "" at line 544, column 1.
Was expecting:
    "end" ...

**Comment by davidjgonzalez** [comment]
@eagleinhills youre repo init script is malformed. You are missing an `end` (as the error log mentions).

While not "best practice" i still prefer .config for repo init scripts since its very difficult for me to reason about repo init scripts modeled as JSON (since its 1 big line and each directive is a string in the overall array).

**Comment by eagleinhills** [comment]
@davidjgonzalez if I use the file format as the documentation suggests I get this error:

Content Package Converter Exception IOException occured on path /jcr_root/apps/my-apps/application/install/csh-aemcs-odfd.ui.config-1.0.0-SNAPSHOT.zip with message: IOException occured on path /jcr_root/apps/my-app/osgiconfig/config.publish/org.apache.sling.jcr.repoinit.RepositoryInitializer-acs-commons-generic-lists-publish.config with message: Unexpected token 78; expected: 61 (line=3, pos=7)  and the file contents are :

create path /etc/acs-commons(sling:OrderedFolder)/lists(sling:OrderedFolder)
set ACL for everyone
    allow jcr:read on /etc/acs-commons/lists
end

**Comment by davidjgonzalez** [comment]
@eagleinhills in the docs, its just the snippet for the specific commands needed for this. You need to add it to a properly formatted file, like below:

```
scripts=[
"
create path /etc/acs-commons(sling:OrderedFolder)/lists(sling:OrderedFolder)
set ACL for everyone
   allow jcr:read on /etc/acs-commons/lists
end
"
]
```

You can see an example of a properly formatted file here:

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/all/src/main/content/jcr_root/apps/acs-commons/config.author/org.apache.sling.jcr.repoinit.RepositoryInitializer-acs-commons-author.config

**Comment by eagleinhills** [comment]
@davidjgonzalez Thank you so much for your quick response. That worked. Sorry, I just copy pasted mindlessly.

**Comment by davidjgonzalez** [comment]
no worries! typically its added to an existing repo init so having the "wrapping" stuff can be confusing on the other side. damned if you do, damned if you dont ;)
