### ISSUE TITLE
ACS Content Sync stores creds in plain format

### ISSUE THREAD

**Issue by Roman-Skripka** [Adobe-Consulting-Services/acs-aem-commons#3197]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.18
* [x] ACS AEM Commons Version: 6.2.0
* [x] Reproducible on Latest? yes

### Expected Behavior

The user credentials saved by this feature under /var should be at least encrypted using Crypto Support

### Actual Behavior

Creds are stored in plain format

### Steps to Reproduce

Go to /apps/acs-commons/content/contentsync/configure.html and add a host with credentials. Check in repository the actual values.

### Links

https://adobe-consulting-services.github.io/acs-aem-commons/features/contentsync/index.html

**Comment by YegorKozlov** [comment]
A good catch, although Content Sync is not the only feature storing password in plain text.
