### ISSUE TITLE
Github actions fail after introduction of configurations for Cloud Bundle

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#3201]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [X] ACS AEM Commons Version: 6.3.0
* [X] Reproducible on Latest? yes

### Expected Behavior

Github actions do not fail

### Actual Behavior

Github actions fail.

### Links

See Github action logs: https://github.com/Adobe-Consulting-Services/acs-aem-commons/actions/runs/6471397505

**Comment by kwin** [comment]
This is a regression of #3149. @royteeuwen Can you have a look and also clarify in the readme the meaning of the new `cloud` profile?
