### ISSUE TITLE
Unable to bulk upload HTTP redirects for a CSV file.

### ISSUE THREAD

**Issue by matthew-dalby** [Adobe-Consulting-Services/acs-aem-commons#3202]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: (Whatever is running in the cloud)
* [ ] ACS AEM Commons Version: (Whatever is running in the cloud)
* [ ] Reproducible on Latest? yes

### Expected Behavior
(/apps/acs-commons/content/redirect-manager.html/conf/global/settings/redirects) within the cloud environment.

We should be able to upload a csv file with redirect options, and have that reflected.

### Actual Behavior

On a corporate laptop, I experience a CORs related issue, which may or may not be organization specific on our end. On a private laptop/network, I do not experience the CORs issue, and upon submission the operation lets me proceed back to the main screen, however changes uploaded are not reflected.

When attempting the import CSV operation on a personal laptop/network, from the Chrome browser debug tools I get an error message: 'runtime.lastError: The message port closed before a response was received'.

### Steps to Reproduce

Perform an 'export' operation from the admin panel, make a change to the file, and perform an 'import' operation. 

I have tried both use cases where I download and upload a modified export file and where a new change (not an update directive) is defined. 

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

Expectation is that I can export, modify, and upload a new redirect configuration and see the changes refleced.

### Links

_Links to related assets, e.g. content packages containing test components_

/apps/acs-commons/content/redirect-manager.html/conf/global/settings/redirects

**Comment by matthew-dalby** [comment]
Additional note, just to confirm, I am on a Mac (OSX), I originally attempted to export from the UI into xlsx format, modify, and then re-import, I just tried another path where I exported, converts to xls format, but there is no option to import from the 'select file box' . This may or may not be related to my work configuration. My first ask is that can anyone reproduce this in the cloud environment. It might be possible it it a network/configuration issue on my end we should rule out.

**Comment by YegorKozlov** [comment]
@matthew-dalby It's entirely possible your corporate laptop is blocking sending/uploading Office documents.
I checked the latest build of ACS Commons in AEM cloud, AEM 6.5 running in AMS and my local, both on my Mac and Ubuntu laptops, and bulk upload of redirected worked fine  for me. 

Does it happen in Chrome only or in other browsers too? Do you have any fancy plugins installed that could cause it?

**Comment by matthew-dalby** [comment]
Yup! There is an corporate firewall setting that was a factor.... Able to confirm. Nice feature to be able to backup and bulk upload the redirects. I did stumble across a recorded session on YouTube where there was a reference to marketing to handle theses requests (if possible), and that is our direction moving forward. Appreciate the effort on your guy's part. This is a non issue on your end. Have a good weekend.
