### ISSUE TITLE
Installation of bundle fragment for AEMaaCS from v6.3.0 is not happening

### ISSUE THREAD

**Issue by Promathia** [Adobe-Consulting-Services/acs-aem-commons#3221]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM as a Cloud Service, latest: 2023.11.14227.20231108T162349Z
* [ ] ACS AEM Commons Version: 6.3.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

After switching from ACS Commons 6.0.6 version to 6.3.0, the fragment bundle for cloud version should be installed. 
Commit:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/302aadee81429a73c82c3f67c9ff02b8c556dc37
Message:
Add cloud bundle + cloud all package containing dispatcher flush rules fixes

### Actual Behavior

Neither fragment bundle, nor code from it is installed on AEMaaCS.

### Steps to Reproduce

Change version in a default archetype
Deploy to AEMaaCS via Cloud Manager Pipeline

### Links

[_Links to related assets, e.g. content packages containing test components_](https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/302aadee81429a73c82c3f67c9ff02b8c556dc37)

**Comment by Promathia** [comment]
is it expected and should we just embed the fragment in our pom?

**Comment by royteeuwen** [comment]
@Promathia  there is a new all package available, namely the `acs-aem-commons-all-cloud`. Installing this one will also install the fragment.

**Comment by Promathia** [comment]
@royteeuwen, thanks for your response, now I can see it, it was uploaded only yesterday. I'll check it now and provide feedback

**Comment by Promathia** [comment]
@royteeuwen , it would be very helpful, if you could upload it to Maven central since it is missed there now, we can not normally embed it into the code.
Here is the screenshot from Maven Central:
![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/16146208/a9f1d96a-ee29-4058-abd9-817a577c3a93)

**Comment by kwin** [comment]
Both cloud and classic version are having the same artifact id `acs-aem-commons-all` and therefore can be found in the same folder: https://repo1.maven.org/maven2/com/adobe/acs/acs-aem-commons-all/6.3.2/.

**Comment by Promathia** [comment]
Hello colleagues, thanks for your responses and comments, now it is clear.
At the same time, I think lots of library users may be confused with how to successfully use it for AEMaaCS with 'cloud' fragment.
I prepared a short description, since we are actively working with an AEMaaCS project, and I tested the approach on an env, hopefully it will be helpfull and maybe appear in official docs on site one day :)

For additing ACS AEM Commons library to AEM as a Cloud Service deployment project (including special cloud fragment for dispatcher flush rules and others), one should perform the following updates in _pom.xml_ files:

**Prerequsites:** _AEM as a Cloud Service_
**ACS Commons version:** _6.3.2_
**Project:** _Adobe recommended project structure_

**Updates required:**
_Root pom file updates **/pom.xml**:_
```
<properties>
   ...
   <acs.commons.version>6.3.2</acs.commons.version>
   ...
</properties>
...
<dependencyManagement>
    <dependencies>
	...
       <!-- ACS Commons-->
       <dependency>
         <groupId>com.adobe.acs</groupId>
         <artifactId>acs-aem-commons-bundle</artifactId>
         <version>${acs.commons.version}</version>
         <scope>provided</scope>
       </dependency>
       <dependency>
         <groupId>com.adobe.acs</groupId>
         <artifactId>acs-aem-commons-bundle-cloud</artifactId>
         <version>${acs.commons.version}</version>
         <scope>provided</scope>
       </dependency>
	...
    </dependencies>
</dependencyManagement>
```

_Pom file updates in package with java code: **core/pom.xml**:_
```
<dependencies>
    ...
    <dependency>
        <groupId>com.adobe.acs</groupId>
        <artifactId>acs-aem-commons-bundle</artifactId>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>com.adobe.acs</groupId>
        <artifactId>acs-aem-commons-bundle-cloud</artifactId>
        <scope>provided</scope>
    </dependency>
    ...
</dependencies>
```

_Pom file updates in 'all' package: **all/pom.xml**:_
```
...
<plugin>
   ...
   <artifactId>filevault-package-maven-plugin</artifactId>
   ...
   <configuration>
   ...
      <embeddeds>
	  ...
	  <embedded>
          <groupId>com.adobe.acs</groupId>
          <artifactId>acs-aem-commons-all</artifactId>
          <type>zip</type>
          <target>/apps/aem-full-stack-packages/container/install</target>
          <filter>true</filter>
          <isAllVersionsFilter>true</isAllVersionsFilter>
      </embedded>
      ...
...
<dependencies>
    ...
    <dependency>
        <groupId>com.adobe.acs</groupId>
        <artifactId>acs-aem-commons-all</artifactId>
        <version>${acs.commons.version}</version>
        <classifier>cloud</classifier>
        <type>zip</type>
    </dependency>
    ...
</dependencies>
```


Hopefully this makes sense. Thank you once again for such a project and huge effort.

Regards,
Ivan

**Comment by kwin** [comment]
Feel free to come up with a PR for https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html

**Comment by Promathia** [comment]
ok, thanks, I'll create a PR
