### ISSUE TITLE
PackageGarbageCollector leaves temp files behind

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#3225]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM CS, release 14227
* [X] ACS AEM Commons Version: 6.2.0
* [X] Reproducible on Latest? yes/no: yes

### Expected Behavior

The PackageGarbageCollector must not leave temporary files behind.

### Actual Behavior

When the PackageCollectorJob runs across a large amount of packages, which are not deleted, all these packages remain in the java.io.tmpdir; depending on the size of the allocated scratch space and the package size of these non-removed packages, this can lead to stability problems.

### Steps to Reproduce

* have a spare test instance which you can throw away after this test (local SDK is ok)
* configure the logger com.adobe.acs.commons.packagegarbagecollector to DEBUG
* configure the PackageGarbageCollector in a way, that it does not remove any package
 ** configure the "packageName" property to ``day/cq60/product``
 ** set the cron expression to ``0 17 12 ? * * *`` to execute it at 12:17 PM (local time), so it's executed immediately and you don't need to wait
* wait until the job has been executed 
* now check  the files in your "java.io.tmpdir" directory, and you will find (at least some of) these packages left there.

(you can find the actual path for ``java.io.tmpdir`` in the OSGI webconsole: "Main" -> "JMX" -> "Runtime")

(the root cause seems to be that the jcrPackage objects are not closed.)

**Comment by ieb** [comment]
Causing CSO https://adobe.app.exigence.io/secure/index.html#/events/50747/situationroom

**Comment by ieb** [comment]
oops, sorry, removed it. Thanks for letting me know.. (that the AuthZ really does work).

**Comment by kwin** [comment]
As @joerghoh pointed out the packages implicitly opened within the for loop at https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/d5ae95bf3895d47e8b441bc103f13746067d3a88/bundle/src/main/java/com/adobe/acs/commons/packagegarbagecollector/PackageGarbageCollectionJob.java#L90 need to be closed again. Most likely this cases the issue. @joerghoh Can you come up with a PR?

**Comment by davidjgonzalez** [comment]
Thanks @kwin  for providing the fix for this
