### ISSUE TITLE
The acs-aem-commons subpackage isn't installing using curl command 

### ISSUE THREAD

**Issue by jerinraj5555** [Adobe-Consulting-Services/acs-aem-commons#3228]
## Required Information

* [ ] AEM Version: 6.5.16
* [ ] ACS AEM Commons Version: 6.0.14
* [ ] Reproducible on Latest? yes(Subpackages will be installed at the first deployment but at the next deployment, the subpackage won't install hence we can see the past installed time stamp.)

### Expected Behavior
Both acs-aem-commons-ui.content and acs-aem-commons-ui.apps sub-packages must be installed in each deployment using `curl`. 

### Actual Behavior

I'm trying to install the acs-aem-commons-all-6.0.14.zip package explicitly using the curl command, and I get the response that the package is installed, but it doesn't install, so we need to manually install the package at the first time. 

`curl -u admin:admin -F cmd=upload -F force=true -F package=@acs-aem-commons-all-6.0.14.zip  http://localhost:6014/crx/packmgr/service/.json`
`curl -u admin:admin -F cmd=install  http://localhost:4502/crx/packmgr/service/.json/etc/packages/adobe/consulting/acs-aem-commons-all-6.0.14.zip`

But in the next deployment, the time subpackage didn't install and the timestamp was either empty or showing the past installed date.
Please refer the screenshot's  below,

![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/13197867/6c78cd97-3c8e-48c3-8520-f458abab7e5e)
![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/13197867/be90cd4b-805f-4d70-91a9-f8bad34937c0)

In the acs-aem-commons-all-6.3.2, Subpackage will be installed at the first deployment, but in the redeployment, it won't install and will show the past installed date.

<img width="1057" alt="6 3 2" src="https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/13197867/bbcb88bc-86d5-4e0a-9ede-8259a3d00d9a">
### Steps to Reproduce

1. Set up AEM 6.5 instance and install SP 16
2. Download [acs-aem-commons-all-6.0.14.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases/download/acs-aem-commons-6.0.14/acs-aem-commons-all-6.0.14.zip) or the latest version.
3. Upload the package using ` curl -u admin:admin -F cmd=upload -F force=true -F package=@acs-aem-commons-all-6.0.14.zip  http://localhost:6014/crx/packmgr/service/.json`
4. Install the package using `curl -u admin:admin -F cmd=install http://localhost:6014/crx/packmgr/service/.json/etc/packages/adobe/consulting/acs-aem-commons-all-6.0.14.zip`
5. Go to the package manager (http://localhost:5502/crx/packmgr/index.jsp) to verify the installation status.
6. Repeat steps 3 to 5 and verify the installation status.

### Links
https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases/tag/acs-aem-commons-6.0.14
https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases/tag/acs-aem-commons-6.3.2

**Comment by kwin** [comment]
You need to add the flag `recursive=true` to the install command.

**Comment by jerinraj5555** [comment]
Hi @kwin , Thanks for the suggestions but it's not working and getting the same. 

 `curl -u admin:admin -F cmd=install http://localhost:6014/crx/packmgr/service/.json/etc/packages/adobe/consulting/acs-aem-commons-all-6.0.14.zip   recursive=true`

**Comment by jerinraj5555** [comment]
Hi @kwin ,

I have added  `- F` before `recursive=true` in the command and it worked as expected also every time I got the Last Installed date and time for acs-aem-commons-ui-all,acs-aem-commons-ui.content and acs-aem-commons-ui.apps.

`curl -u admin:admin -F cmd=upload -F force=true -F package=@acs-aem-commons-all-6.0.14.zip http://localhost:4502/crx/packmgr/service/.json
curl -u admin:admin -F cmd=install http://localhost:4502/crx/packmgr/service/.json/etc/packages/adobe/consulting/acs-aem-commons-all-6.0.14.zip -F recursive=true `

Thanks for the solution.
