### ISSUE TITLE
Redirect Manager Tool - Enhancement to ignore selectors in the url

### ISSUE THREAD

**Issue by thcharan** [Adobe-Consulting-Services/acs-aem-commons#3235]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: ___ALL Versions____
* [ ] ACS AEM Commons Version: __ALL VERSIONS___
* [ ] Reproducible on Latest? yes/no YES

### Expected Behavior

We often run in to business cases - where we want to rewrite url's based on specfic user profile cookies with "Selectors" .

for example -
when user requests a url /content/a/b/c.html , it needs to rewritten to
/content/a/b/c.xyz.html  , 
/content/a/b/c.qrt.html , 
/content/a/b/c.rtp.html

We want to have ability where ACS redirect tool ignores the selectors. Preferably define it as OSGI config Global flag. "ignoreSelectors"

So, the expected behavior of this flag be :  
if there is redirect entry with source as /content/a/b/c.html to redirect to /content/d/e/f.html is defined in the redirect tool.
when a incoming request is any of the below ->
/content/a/b/c.xyz.html  , 
/content/a/b/c.qrt.html , 
/content/a/b/c.rtp.html

the redirect tool will ignore the selectors and match the redirect entry and will honor the redirect to /content/d/e/f.html

**Comment by thcharan** [comment]
@YegorKozlov  - thoughts?

**Comment by YegorKozlov** [comment]
@thcharan, @tomasz-niedzwiedz-wttech  You can use regex to match selectors,. e.g.
```
/content/we-retail/en/terms(.one)?(.two)?(.three)?

# will match
/content/we-retail/en/terms.one.html
/content/we-retail/en/terms.two.html
/content/we-retail/en/terms.one.two.three.html
```

so instead of ignoring selectors you'd specify which ones you need to match.

Will it work for you?

**Comment by thcharan** [comment]
@YegorKozlov - 
Thanks for the response.

Couple of reasons why i have different point of view on this, 


1) The biggest advantage of Redirect tool is have business users self manage the redirects, they do not know any of these selectors and regexp. I do not think - having that burden on Marketing users of this tool to remember these intricasies is a good idea.

I would still lean on either 
"IgnoreSelectors" option as global osgi setting 
OR 
even better Context Aware Confg Setting per site as the most preferable approach that works seemlessly across implementations on multi tenant platforms with many sites hosted..

thoughts?

**Comment by tomasz-niedzwiedz-wttech** [comment]
I think there's merit in @thcharan's proposal. If this tool is given to super users to self-manage the redirects, requiring them to know and update the glob patters to include all selectors used internally by the given implementation across multiple redirects would be unreasonable.

One could try to work around this by crafting a regex that matches a whole selector string, assuming there are no `.` characters in the URL itself
```
/content/we-retail/en/terms(\..+)*\.html
```
but it seems error-prone and a potential performance problem if the number of such entries is excessive. I can see how this could backfire even if such rules were created by developers and admins only.

**Comment by thcharan** [comment]
@YegorKozlov  - Any thought on 'Context Aware Config + Glob' approach for this that may land us with a more scalable solution.

**Comment by YegorKozlov** [comment]
@thcharan @tomasz-niedzwiedz-wttech I'm fine add this feature, just wanted to understand why you needed it and why regex wouldn't work for you.

IMO it should be a runtime, user-managed setting, managed at either on redirect level, or on the context level, e.g. there can be cases where selectors would be off for one content tree, and be on for others.

**Comment by YegorKozlov** [comment]
@thcharan I'd rather not complicate this feature. Your point is that using regex  is too complicated for non-tech users. IMO overloading the dialog with too many options will result in the same problem, i.e. it will confuse users instead of helping them. IMO if we support this feature, it would be a simple checkbox at the site conf level.

**Comment by YegorKozlov** [comment]
@thcharan @tomasz-niedzwiedz-wttech  here you go
The context configuration offers a new option to ignore selectors for the content tree:
![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/2543854/00803579-8f46-4735-a512-7518dceef446)

**Comment by thcharan** [comment]
@YegorKozlov - Looks Great!

**Comment by thcharan** [comment]
@YegorKozlov  -- seems like this is not working in the cloud envts... it works for you ?

**Comment by YegorKozlov** [comment]
@thcharan it worked for me in AMS and on-prem 6.5.18. please give me a few days to check in the cloud setup.

**Comment by thcharan** [comment]
@YegorKozlov   - So, My Team investigated this issue by debugging runtime on a AEM Cloud SDK on localhost. Below is our findings. It's a major issue.
 
In a nutshell, None of the "Context Aware Cfg Options" is working in AEM-Cloud. So technically this is not just impacting "Ignore Selectors" option, but impacts all the CA options. Findings below

1) com.adobe.acs.commons.redirects.filter.RedirectFilter.java is having this below line of code, 

  @Reference
    ConfigurationResourceResolver configResolver;

2) The configResolver is injected with a valid configResolver object --- no issues with that. However keep in mind -- this configResolver is still operating with a anonymous user context ( NOT AS A SERVICE USER CONTEXT WITH ELEVATED PERMISSIONS).

3) when code flow control reaches the match() method,

we have this line, which works fine, returning the path of an valid context aware path applicable to that site.
 String configPath = configResource.getPath(); 

The code fails here -- returns an empty valuemap (size=0) since the anonymous user context didn't have permissions on that node.
            ValueMap properties = configResource.getValueMap();

On local, when we are logged in as admin on that browser session -- the same code worked,.

Solution - 
 use this to get the conf resource path, String configPath = configResource.getPath(); 
once you have above context aware conf path, use resourceResolver  of the service user to get the valuemap on that "redirects" node..to read the properties.

Note - **Anonymous** is part of everyone group... the Out of the box permissions in the below screenshot should make it clear of the issue described above.

![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/112187708/adff8025-edbb-4891-8e32-ef78d180659f)

**Comment by thcharan** [comment]
Since this issue pre-existed before IgnoreSelectors, created a new issue for this -- 

https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3284

we can communicate on that issue thread.
