### ISSUE TITLE
Content Sync make timeouts configurable

### ISSUE THREAD

**Issue by Roman-Skripka** [Adobe-Consulting-Services/acs-aem-commons#3238]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.19
* [x] ACS AEM Commons Version: latest
* [x] Reproducible on Latest? yes

### Expected Behavior

Read/Connect timeouts hardcoded in com.adobe.acs.commons.contentsync.RemoteInstance are configurable

### Actual Behavior

Timeouts aren't configurable and it isn't possible to sync the large folders taking e.g. 2min to build catalogue response for.

### Steps to Reproduce

Try syncing large folder (e.g. big DAM folder) and observe the timeout

### Links

https://adobe-consulting-services.github.io/acs-aem-commons/features/contentsync/index.html

**Comment by nikstyagi** [comment]
Hi , what are the steps to add custom timeout to content sync utility , getting the same error as above
