### ISSUE TITLE
ACS commons System notification - Question

### ISSUE THREAD

**Issue by mnarchana** [Adobe-Consulting-Services/acs-aem-commons#3244]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5 SP 12
* [ ] ACS AEM Commons Version: 5.6.0
* [ ] Reproducible on Latest? N/A

### Expected Behavior

ACS Commons System notification shows up as expected in the default position

### Actual Behavior

ACS Commons System notification shows up as expected in the default position (No issue)

### Steps to Reproduce

This is more of a question than an Issue.

In AEM, we are using ACS Commons system notification feature. AEM --> Tools --> ACS AEM Commons --> System notifications.

We use this notify users during deployments.  This OOTB feature puts the notification dialog box after its enabled right in the middle of the UI which makes it difficult for testing team during deployment testing and we dont want to disable this dialogue until testing team wraps up testing.

Is there a way we can change the position of the system notification dialogue box?

https://adobe-consulting-services.github.io/acs-aem-commons/features/system-notifications/index.html

**Comment by davidjgonzalez** [comment]
Hi! Yes - you can do this by 

1. Creating a new custom clientlibrary with category = `acs-commons.system-notifications.notification`
2. Add your own .css or .less to your clientlibrary that overrides whatever styles you want in:

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/system-notifications/notification/clientlibs/notification.less

You may want to scope your CSS classes with `div#acsCommons-System-Notifications ... { .. }` so they are (every so slightly) heavier that the ACS Commons ones -- or you could always just jam on an `!important`  ;) 


Then when the notification loads, it will load the CSS file that contains BOTH the ACS commons CSS and your overrides - and assuming your overrides are have more weight (or come after the ACS commons ones -- though cant recall if you can guarentee that order w/ clientlibs, thus selector weight) .. your styles will take affect!
