### ISSUE TITLE
Package Garbage Collector does not find all packages to clean up in v6.3.4 

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#3246]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: N/A
* [X] ACS AEM Commons Version: 6.3.4
* [X] Reproducible on Latest? yes

### Expected Behavior

Package Garbage Collector should clean up all old pacakges.

### Actual Behavior

It misses package now ...

`/etc/packages/example-5.22.53.2023_1109_1163103_0003406251.zip/jcr:content/vlt:definition ] has no created date, assuming it's NOT old enough`

Error is due to the package defintion not always returning a created date, even tho it might be ont he underlying JCR node.

### Steps to Reproduce

This issue was identified by Leo B. who has a large number of test packages he can run this against.

**Comment by Roman-Skripka** [comment]
@davidjgonzalez please also check https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3249
