### ISSUE TITLE
Code Droplets

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#325]
The Problem
Lately I've needed to run "mini-scripts" against multiple envs to post-process content. These are 1 time executions that involve small code bases; currently the simplest way to execute is via ACS Tools > AEM Fiddle, but this is less controlled and requires the installation of the ACS Tools package (potentially on higher level envs).

Idea
Create a CQ Package installation hook that inspects the package for a signature (TBD), and executes a script in a well-known location in said package. Progress/status could be marked on a /var node somewhere to prevent "re-running" or collecting information post-execution.

Actual impl details TBD.

Ideally all the data would be clean and not require this, however IRL these needs arise, and it is seldom practical to make the changes centrally on Author and replicate them out (too much content, too much mixed content; replicated but modified)

This problem grows as the content volume and no of publishers grow.

**Comment by davidjgonzalez** [comment]
@chetanmeh interested if you have thoughts on a simple/clean way to do this.

**Comment by badvision** [comment]
This is kind of the general idea behind MCP's blockly-based scripting feature, which is slated for v2 of that featureset.  Would that fill the need?
