### ISSUE TITLE
Invalid max-age header set from property

### ISSUE THREAD

**Issue by senn** [Adobe-Consulting-Services/acs-aem-commons#3251]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.18
* [ ] ACS AEM Commons Version: 6.3.2
* [ ] Reproducible on Latest? yes

### Expected Behavior

When using the `PropertyBasedDispatcherMaxAgeHeaderFilter` we expect only valid values to be set.  A check if the value of the property is of integer value should be sufficient.
If yes => set max-age from resource-property
If no => fall back to superclass (use max-age OSGi property)

### Actual Behavior

In some cases a property may have a different type (Date for example) and it will cause bad max-age values:
![image](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/1144233/0ead5693-b683-4308-9e0b-adb994defb2e)
This can happen if the same property name is used in different contexts.

### Steps to Reproduce

Use the PropertyBasedDispatcherMaxAgeHeaderFilter with a proeprty that is not a valid integer value like a date, or "XXX" or whatever.

**Comment by kwin** [comment]
Fixed via #3235
