### ISSUE TITLE
release 6.3.8 failed to install on cloud service

### ISSUE THREAD

**Issue by danzhang-pm** [Adobe-Consulting-Services/acs-aem-commons#3255]
## Required Information

* [ ] AEM Cloud Service
* [ ] ACS AEM Commons Version: 6.3.8 and 6.3.6 , acs-aem-commons-all-6.3.8-cloud.zip
* [ ] Reproducible on Latest? yes

### Expected Behavior

Successfully install the ACS Commons package on AEM Cloud Service

### Actual Behavior

Failed with error message, "Package (or it's subpackage(s)) contains application content which isn't supported at runtime"

### Steps to Reproduce
Upload package through AEM Cloud Service pakage manager

![err](https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/54833095/809833f8-71f7-427e-952d-e42a2aca4760)

**Comment by kwin** [comment]
You can only install ACS AEM Commons in AEMaaCS as outlined in https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html due to it having read-only mounts for `/apps` at runtime.
