### ISSUE TITLE
Generic list error handing 

### ISSUE THREAD

**Issue by trenchard** [Adobe-Consulting-Services/acs-aem-commons#326]
We move code around to various environments and run into missing list content all the time.  It would be very helpful to have graceful handling when a dialog using a list component cannot find the list JSON.  Ideally the dialog would load, but the field using the list would simply echo: Options list missing.

**Comment by rajeshp** [comment]
I would say this issue has nothing to do with generic lists. This has to be handled at the selection xtype when the options json is null.
