### ISSUE TITLE
NullPointerException when trying to open dialog generated via @DialogProvider

### ISSUE THREAD

**Issue by csaboka** [Adobe-Consulting-Services/acs-aem-commons#3264]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM Cloud 2023.12.14697.20231215T125030Z-231200
* [x] ACS AEM Commons Version: 6.3.8
* [x] Reproducible on Latest? yes

### Expected Behavior

Composite widgets should work on dialogs generated by the @DialogProvider annotation.

### Actual Behavior

A NullPointerException is thrown when you try to open a dialog built using @DialogProvider and @FormField, but only if a field of type MultifieldComponent is used and a complex type is used as the component type.

### Steps to Reproduce

1. Start from a new project created from the AEM archetype using [these instructions](https://github.com/adobe/aem-project-archetype) . Use aemVersion=cloud
2. [Add ACS AEM Commons to the project](https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html)
3. Delete ui.apps/src/main/content/jcr_root/apps/mysite/components/helloworld/_cq_dialog . We will replace this dialog via annotations.
4. Add the necessary annotation processor to core/pom.xml:
```
            <plugin>
                  <artifactId>maven-compiler-plugin</artifactId>
                  <configuration>
                    <annotationProcessors>
                      <annotationProcessor>com.adobe.acs.commons.mcp.form.DialogProviderAnnotationProcessor</annotationProcessor>
                    </annotationProcessors>
                  </configuration>
            </plugin>
```
5. Delete the HelloWorldModelTest class so it won't interfere with the changes.
6. Replace the HelloWorldModel class with this code:
```
package com.mysite.core.models;

import java.util.List;

import com.adobe.acs.commons.mcp.form.DialogProvider;
import com.adobe.acs.commons.mcp.form.FormField;
import com.adobe.acs.commons.mcp.form.MultifieldComponent;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.models.annotations.Model;

@DialogProvider(title = "Example Component")
@Model(adaptables = Resource.class, resourceType = "mysite/components/helloworld")
public class HelloWorldModel {

    public static class Nested {
        @FormField(name = "Dummy Text")
        private String dummy;
    }

    @FormField(name = "Nested data", component = MultifieldComponent.class)
    private List<Nested> nesteds;

    public String getMessage() {
        return "Hello, world!";
    }

}
```
7. Build the project and deploy it to a local AEM instance.
8. Open the following link in your browser: http://localhost:4502/mnt/override/apps/mysite/components/helloworld.-1.json . You will get a NullPointerException error.
9. The same NullPointerException can be reproduced by placing a HelloWorld component on a page and trying to edit it. You will first need to add either a legacy "dialog" child node or a "cq:editConfig" node to the components, otherwise AEM will assume it's not editable.

**Comment by kwin** [comment]
Look at https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2500.
