### ISSUE TITLE
Only JUnit5 tests executed by m-surefire-p

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#3270]
The commit https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/66497685d3df8de35a4b7fc5e575cb4270dda4c6 broke execution of JUnit4 test cases.
That leads to the fact that only 7 from the 1800 are being executed.

We need to explicitly add the `junit-vintage-engine` according to <https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#how-to-run-multiple-apis-or-engines>

**Comment by kwin** [comment]
@henrykuijpers Can you provide a fix for this?

**Comment by csaboka** [comment]
I have added #3273 today, which should fix this. I haven't noticed this issue, so that PR does not reference it, though.

**Comment by henrykuijpers** [comment]
I'm very sorry for this! I was sick and when I was back up & running this was already fixed (which is a good thing of course).
