### ISSUE TITLE
Content Sync - Version history not preserving from source to destination

### ISSUE THREAD

**Issue by sanjana287** [Adobe-Consulting-Services/acs-aem-commons#3278]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.15, service pack sp15.
* [x] ACS AEM Commons Version: 6.3
* [x] Reproducible on Latest? yes

### Expected Behaviour

_The Content Sync Documentation mentions that version history is preserved during sync. Although upon trying, we did not see the versions reflecting from source to destination. Is this expected behaviour and the documentation has a different interpretation, or the version history should be reflecting from source to destination?_

### Actual Behaviour

_We tried to sync content from the source to destination instance, but did not see the versions of the synced content reflecting from source to destination_

### Steps to Reproduce

- Go to http://localhost:4502/apps/acs-commons/content/contentsync.html
- Add a content path to sync, add a source instance from configured instances
- Click on Submit, check the content path in destination instance, the versions from source do not reflect.

### Links

_https://adobe-consulting-services.github.io/acs-aem-commons/features/contentsync/index.html_

**Comment by YegorKozlov** [comment]
This is expected. Content Sync preserves version history on the target instance, but it does not copy versions from the source.

**Comment by sanjana287** [comment]
Okay, I have a follow up question to this. What is the additional advantage of content sync over CRX Package manager in terms of versions ? If some content already has some version information on the source instance), we observed that the version history was still preserved on the destination instance using the CRX package manager as well. For new pages with no version information, we did observe CRX overriding the version history on destination.

**Comment by YegorKozlov** [comment]
> Okay, I have a follow up question to this. What is the additional advantage of content sync over CRX Package manager in terms of versions ? If some content already has some version information on the source instance, we observed that the version history was still preserved on the destination instance using the CRX package manager as well. For new pages with no version information, we did observe CRX overriding the version history on destination.

CRX package manager preserves the version history *only* if the node uuid is the same on the source and the target.  Content Sync preserves the version history regardless of the uuid.
