### ISSUE TITLE
Dynamic RTE - <p> tags are not removed

### ISSUE THREAD

**Issue by kkedem** [Adobe-Consulting-Services/acs-aem-commons#328]
Hi,

I have seen an article that talks about RTE customization : http://blogs.adobe.com/contentmanagement/tag/custom-richtext/

8th customization in that link talks about removing paragraph tags from the RTE text. It recommends to add a parameter called 'removeSingleParagraphContainter' on the RTE widget and that will take care of <p> tags. It is working as expected if I include 'richtext' xtype in dailogue but the same thing is not working when I include the parameter through Dynamic RTE configurations.

My configuration was like this:

```
text: {
xtype: "slingscriptinclude",
jcr:primaryType: "cq:Widget",
script: "rte.custom-rich-text.primaryheadline1.json?removeSingleParagraphContainter=true&defaultValue=There is some text&hideLabel=true&externalStyleSheets=/apps/dcom/dm/components/pages/dcompage/clientlibs-shared-header/css/rte-style.css.jsp"
}
```

It was still adding parahraph tags.

**Comment by sunilcemk06** [comment]
@kkedem , @davidjgonzalez  any solution  ? I am also facing the same issue. The property removeSingleParagraphContainter=true is not read by and on debuggin js , the removeSingleParagraphContainter value is still set as false.
