### ISSUE TITLE
AEMaaCS | Missing users in Publishers

### ISSUE THREAD

**Issue by singhal425** [Adobe-Consulting-Services/acs-aem-commons#3285]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: **AEMaaCS 2023.12.14697.20231215T125030Z**
* [x] ACS AEM Commons Version: **6.0.8**
* [x] Reproducible on Latest? yes/no: yes

### Expected Behavior

On publishers, errors appear in logs for missing service users. 
_2024-01-01T16:23:34+01:00	01.01.2024 15:23:34.744 [cm-p23958-e477620-aem-publish-856487b4bb-xznlf] *ERROR* [pool-7-thread-1] com.adobe.granite.repository.impl.SystemPrincipalsValidation Principal 'acs-commons-twitter-updater-service' does not exist. Unable to validate._

_2024-01-01T16:23:34+01:00	01.01.2024 15:23:34.730 [cm-p23958-e477620-aem-publish-856487b4bb-xznlf] *ERROR* [pool-7-thread-1] com.adobe.granite.repository.impl.SystemPrincipalsValidation Principal 'acs-commons-package-replication-status-event-service' does not exist. Unable to validate._

### Actual Behavior

These errors shouldn't appear in logs. 

### Steps to Reproduce

Deploy mentioned version of ACS common on AEM as cloud service and these logs would start to appear with missing service user information. 

### Links

[_Links to related assets, e.g. content packages containing test components_](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/all/src/main/content/jcr_root/apps/acs-commons/config.publish/org.apache.sling.jcr.repoinit.RepositoryInitializer-acs-commons-publish.config)
Following config doesn't have mentioned service users defined for Publisher.

**Comment by davidjgonzalez** [comment]
It looks like the service user mappings are set in the `config` but the repo init scripts that create the users are only in `config.author` .. we should move the user mappings to `config.author` as well

**Comment by singhal425** [comment]
@davidjgonzalez Thanks and yes, it's exactly the same. I want to raise a PR for the same but not able to create branch. Is it possible for me to do so?

**Comment by kwin** [comment]
Please create a PR from a branch in your fork.

**Comment by singhal425** [comment]
@kwin @davidjgonzalez Here's the PR https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3310
