### ISSUE TITLE
ACS Commons Content Sync not working on publish servers

### ISSUE THREAD

**Issue by jarvislukow** [Adobe-Consulting-Services/acs-aem-commons#3299]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.20
* [x] ACS AEM Commons Version: 6.4.0
* [x] Reproducible on Latest? yes

### Expected Behavior

Content is successfully synced from one AEM Publish server (source) to another (destination).  

### Actual Behavior

Content is not successfully synced from one AEM Publish server (source) to another (destination).  
This error is returned:

building catalog from https://remoteServer:8443/apps/acs-commons/content/contentsync/jcr:content/sync.catalog.json?root=%2Fcontent%2FsiteName&strategy=com.adobe.acs.commons.contentsync.impl.LastModifiedStrategy
<span class="error">java.io.IOException: Failed to fetch data from https://remoteServer:8443/apps/acs-commons/content/contentsync/jcr:content/sync.catalog.json?root=%2Fcontent%2FsiteName&strategy=com.adobe.acs.commons.contentsync.impl.LastModifiedStrategy, HTTP [404]

### Steps to Reproduce

Configure a new publish host on a publish server and attempt to sync content.

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by jarvislukow** [comment]
I should also add that the path above that is returning a 404 will work if I request it in Postman and pass the remote server user and pass.  It seems like the Content Sync tool is not passing the remote server the correct user name and password when the source server is an AEM publish server.

**Comment by davidjgonzalez** [comment]
@jarvislukow  this sounds eerily similar to #3288

Can you use the proxy.jar approach as described in this comment: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3288#issuecomment-2000129216 andcheck if the credentials are attached to the request leaving the "client" AEM? 

@sanjana287 may be able to help w/ details of what the problem turned out to be for them.

**Comment by jarvislukow** [comment]
Thanks @davidjgonzalez - I'll take a look

**Comment by jarvislukow** [comment]
@davidjgonzalez  looks like it was the same issue for us.  On AEM Publish servers, the Allow Anonymous Access option is enabled by default... which makes sense.  

I was able to solve this by adding +/apps/acs-commons/content/contentsync in the paths that require authentication requirements in the Sling Authenticator config.

Thanks again for the quick response.

**Comment by davidjgonzalez** [comment]
I updated the docs to address this when syncing from AEM Publish.

https://adobe-consulting-services.github.io/acs-aem-commons/features/contentsync/index.html
