### ISSUE TITLE
Composite multifield: Underscore dependency missing

### ISSUE THREAD

**Issue by roszpapad** [Adobe-Consulting-Services/acs-aem-commons#3333]
AEM version: 6.5.20
ACS AEM Commons Version: 6.3.2
Reproducible on Latest? yes

### Expected Behavior

There is no JS error in the console.

### Actual Behavior

Current error in the console:
<img width="577" alt="image" src="https://github.com/Adobe-Consulting-Services/acs-aem-commons/assets/32868620/5a7d9fc2-e9e9-43f2-92ee-fae2b3abb8e6">

The issue is caused by `window._` is undefined. /apps/acs-commons/touchui-widgets/composite-multifield and more touch-ui widgets depend on lodash.underscore which is not found in AEM 6.5.20. Therefore, we always get this issue. A potential fix would be to depend on acs-commons.lodash instead (/apps/acs-commons/clientlibs/vendor/lodash) or depend on cq.integ.underscore (/libs/cq/personalization/clientlib/underscore)

### Steps to Reproduce

Embed acs-commons.authoring.composite-multifield clientlib. If you open a dialog, the JS issue will appear.

Note: /apps/acs-commons/touchui-widgets/search-based-path-browser also depends on lodash.underscore.

**Comment by roszpapad** [comment]
FYI The same issue was fixed in https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2821 by introducing lodash.underscore. But this category is not working anymore.

**Comment by roszpapad** [comment]
I am reopening the issue. I double-checked it and the issue is with the dependency of composite-multifield. On my local environment, I changed it manually to `acs-commons.lodash` and the issue was gone. Can you please double-check it on your side as well?

**Comment by kwin** [comment]
FTR: According to https://experienceleague.adobe.com/en/docs/experience-manager-65/content/release-notes/deprecated-removed-features

> Deprecated Feature: Lodash/underscore client library. Adobe does not plan to further maintain and update the Lodash/underscore client library that is shipped as part of the distribution (Quickstart).

> Replacement: Adobe recommends customers that still require Lodash/underscore for their code to add it into their project code base.
