### ISSUE TITLE
Updated maven-scr-plugin Excludes TLD files from bundle

### ISSUE THREAD

**Issue by bstopp** [Adobe-Consulting-Services/acs-aem-commons#337]
The recent update to v1.20.0 of the maven-scr-plugin breaks the inclusion of the TLDs for all of the WCM modes. Version 1.17.0 added the generated *.tld files to the Include-Resources so that the maven-bundle-plugin would pick them up; however something changed in v1.19.0 and this is no longer the case.

**Comment by badvision** [comment]
@kwin This was where we had the TLD issue, FYI
