### ISSUE TITLE
Using the ACS Commons include to attach a dialog as part of the items under a composite multifield, the namespace does not work

### ISSUE THREAD

**Issue by marctabia** [Adobe-Consulting-Services/acs-aem-commons#3385]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 2024.6.16971.20240628T122619Z-240600 (AEMaaCS)
* [ ] ACS AEM Commons Version: 6.5.0+
* [ ] Reproducible on Latest? yes

### Expected Behavior

Before, on version 5.4.0, when adding an ACS Parameterized Include with namespace under a composite multifield, the namespace works and creates a node which gives a separation from the 1st level named fields. 

### Actual Behavior

When using a composite multifield, elements / items under the multifield that use the ACS-Commons Include with a namespace parameter, the namespace is not created after updating to version 6.5.0. tested 6.6.2 and it also does not work. 

This causes the names for the fields inside the included dialog to not having namespace and causes conflict if 2 fields have the same name in the multifield, i.e. "./text". ACS-Include without a namespace still works. This happens to items where a multifield is used, including when inside Page Properties.

### Steps to Reproduce

Create a composite multifield, then create 2 items under the multifield: one with a dialog that uses ACS-commons include with a namespace, and another item that uses ACS-commons include but without a namespace. 

Ex. The multifield: 

```
<boxes jcr:primaryType="nt:unstructured" 
   sling:resourceType="granite/ui/components/coral/foundation/form/multifield"
   composite="{Boolean}true" 
   fieldLabel="Boxes">     
   <granite:data jcr:primaryType="nt:unstructured" maxboxes="5" />
      <field jcr:primaryType="nt:unstructured" 
      sling:resourceType="granite/ui/components/coral/foundation/container" 
      name="./container">        
         <items jcr:primaryType="nt:unstructured">               
         <!-- list of items below --!>
```

One of the items under the multifield using an ACS include but without a namespace (richtext-extended here is a custom dialog that extends Core Text RTE, has parameter name passed "./text"): 

```
<text jcr:primaryType="nt:unstructured" 
   sling:resourceType="acs-commons/granite/ui/components/include" 
   path="/apps/project/components/commons/dialog/richtext-extended">
      <parameters jcr:primaryType="nt:unstructured" 
         name="./text"        
         required="{Boolean}true"        
         label="Text" />
</text> 
```

Another item under the same multifield, also using ACS include but has namespace "cta0", inside this included dialog has a field with same name as above, “./text” (button is a custom dialog for a custom button component): 

```
<cta0 jcr:primaryType="nt:unstructured"     
   sling:resourceType="acs-commons/granite/ui/components/include"     
   path="/apps/project/components/commons/dialog/button"     
   namespace="cta0">     
      <parameters jcr:primaryType="nt:unstructured"        
         hideIcon="{Boolean}true"        
         hideHeading="{Boolean}false"        
         headingText="First Button" /> 
</cta0>
``` 

Before, the expected result is that due to the namespace there should be no overlapping in the names because one would have the name “./container/item0/./text” while the 2nd one should be ““./container/item0/./cta0/text”. 

But this does not happen, the namespace “cta0” is not created and therefore the 2nd one gets the same name from the first one “./container/item0/./text”. This results in that the content text from the first one is copied to the second one. 

Also, the Component Model for the second dialog ( which is a custom button using @ChildResource) returns null and does not generate this component on the page.

### Links

It seems to behave opposite to the previous reported bug: #3040, which is also related to multifield.

Also there was an opened discussion about broken namespace (but might not be related): Namespace Include feature is broken in new ACS-commons package version 6.5 · Adobe-Consulting-Services/acs-aem-commons · Discussion #3314 (github.com)

**Comment by niekraaijmakers** [comment]
I think what I could maybe do is with a property on the multifield, determine whether to namespace the children or not. In any case it gets tricky.

**Comment by niekraaijmakers** [comment]
@marctabia , i addressed the issues. I have the pr's open, i hope to have them released soon.
