### ISSUE TITLE
Remove usage of commons collections 3

### ISSUE THREAD

**Issue by cziegeler** [Adobe-Consulting-Services/acs-aem-commons#3390]
Apache commons collections 3 is not maintained anymore since years. Usage of it should be replaced with Apache Commons Collections 4. Both libraries are part of AEM as a Cloud Service and AEM 6.x, only a change of the imports is required.

**Comment by kwin** [comment]
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3389

**Comment by cziegeler** [comment]
#3389 got merged
