### ISSUE TITLE
Extract OSGI configuration from acs-aem-commons-all to a new package acs-aem-commons-ui.config

### ISSUE THREAD

**Issue by SzymonSzafraniec** [Adobe-Consulting-Services/acs-aem-commons#3433]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: n/a
* [ ] ACS AEM Commons Version: 6.6.4
* [ ] Reproducible on Latest? yes

### Expected Behavior

Package acs-aem-commons-all should not contain config files. OSGI Configuration files should be located in a separate package called acs-aem-commons-ui.config embedded in acs-aem-commons-all.

See: https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/implementing/developing/aem-project-content-package-structure#container-packages

### Actual Behavior

OSGI Configuration files are located directly in acs-aem-commons-all (src/main/content/jcr_root/apps/acs-commons/config.*). This package embeds other packages and bundles as well as individual configuration files.

### Steps to Reproduce

n/a

### Links

https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/implementing/developing/aem-project-content-package-structure

**Comment by davidjgonzalez** [comment]
Release in 6.7.0
