### ISSUE TITLE
Content Sync without Recurse slow as though it's still analyzing children

### ISSUE THREAD

**Issue by tim-grimes-graco** [Adobe-Consulting-Services/acs-aem-commons#3443]
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 2024.9.17964.20240924T170544Z
* [x] ACS AEM Commons Version: 6.7.0
* [x] Reproducible on Latest? yes

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._
When content syncing a sites page with a lot of children pages but unchecking the recurse button, the content sync should quickly synchronize the one site page.

### Actual Behavior

_Please describe briefly the actual behavior, i.e. when I do X, Z happens._
I get a 503 as though it is still processing all children just in the same way it does when the Recurse button is still checked.

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_
Parent page with LOTS of content underneath it.

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by tim-grimes-graco** [comment]
fyi @YegorKozlov. Really appreciate your work on this feature. very good tool.

**Comment by YegorKozlov** [comment]
@tim-grimes-graco It sounds like an easy fix but I'd like to reproduce the 503 error first.  How many pages do you have in the tree and how deep  the tree is? I need a ballpark estimation.

**Comment by tim-grimes-graco** [comment]
My main test case was ~16,144 subpages but I believe I also saw it slow and time out on ~2,405 subpages
