### ISSUE TITLE
Asset share commons set up not working on publish instance

### ISSUE THREAD

**Issue by njariwala2019** [Adobe-Consulting-Services/acs-aem-commons#3469]
## Required Information

* [ ] AEM Version  - AEM AS A CLOUD 
* [ ] ACS AEM Commons Version: 2.1.12

`2024-11-06 21:48:04.984 WARN [com.adobe.aem.commons.assetshare.configuration.impl.ConfigImpl] Could not find a valid Asset Share Commons root page for [ /content/abc/us/en/error ]. Check to ensure a parent page sling:resourceSuperTypes one of [ asset-share-commons/components/structure/search-page ]

2024-11-06 21:48:04.984 WARN [com.adobe.aem.commons.assetshare.configuration.impl.ConfigImpl] Could not find a valid Asset Share Commons root page for [ /content/abc/us/en/error ]. Check to ensure a parent page sling:resourceSuperTypes one of [ asset-share-commons/components/structure/search-page ]
 
org.apache.sling.scripting.sightly.render.ObjectModel Cannot access method ready on object`

We are using asset share commons on our project, we are getting the above error on the publish instance on the cloud. Things are working as expected on author.
Does anyone have any idea on why we would be getting the above error only on publish instances??

**Comment by kwin** [comment]
This is the wrong project. Asset-Share Commons is maintained in https://github.com/adobe/asset-share-commons.
