### ISSUE TITLE
Limited Parsys

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#35]
A Component that allows a fixed # of components to be added; something like a Parsys that only accepts N components; where N is configurable by Design.

**Comment by tommix1987** [comment]
+1

**Comment by djessup** [comment]
I agree this would be a handy feature.

**Comment by matthiasschoger** [comment]
+1


2015-03-17 4:16 GMT+01:00 djessup <notifications@github.com>:

**Comment by taylor-l-beach** [comment]
+1  - any updates on this? working on a huge project and i need a component with a parsys to only allow one component to be added to that parsys

**Comment by davidjgonzalez** [comment]
@taylor-l-beach AFIAK its stagnated .. would love if you could contribute what you come up w though!

**Comment by schoudry** [comment]
For latest acs commons ( support >= 6.0 sp2 ) this extension in Touch makes more sense, sorry for posting an external link - but if anyone needs it for classic http://experience-aem.blogspot.com/2016/01/aem-61-classic-ui-limit-components-added-in-parsys.html

**Comment by schoudry** [comment]
the pull for tracking this touchui extension - https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/639

**Comment by davidjgonzalez** [comment]
Fixed in #639

**Comment by jainankush385** [comment]
This feature is not working on AEM 6.3.
![image](https://user-images.githubusercontent.com/39520807/40359200-803eee76-5ddf-11e8-99de-d83fac8ce119.png)


Working after i modified the function **getDesignPath** with following code.
file location `/apps/acs-commons/touchui-widgets/configure-parsys-placeholder/touchui-configure-parsys-placeholder.js`
```
function getDesignPath(editable){
        var parsys = editable.getParent(),
            designSrc = parsys.config.designDialogSrc,
            result = {}, param;

        if (designSrc === undefined) {
            return undefined;
        }

        designSrc = designSrc.substring(designSrc.indexOf(".html") + 5 ,designSrc.indexOf("?") );


        return decodeURIComponent(designSrc);
    }


```

**Comment by jainankush385** [comment]
acs commons version `3.14.6`

**Comment by kiranbabuveeranki** [comment]
Hi jainankush385,
After replacing you code also i'm facing same exception. Can you help me here?
