### ISSUE TITLE
html5smartfile doesn't work inside a Multi Field Panel

### ISSUE THREAD

**Issue by cpfabian23** [Adobe-Consulting-Services/acs-aem-commons#363]
If you add a html5smartfile widget as an item of the Multi Field panel, it doesn't work. 
There will be only a blank space where the upload file should appears.

**Comment by pepe79** [comment]
I have the same problem. Is there any solution for this?

**Comment by davidjgonzalez** [comment]
deprecated ClassicUI issue; closing as wont fix
