### ISSUE TITLE
i18n translations do not work with error page handler

### ISSUE THREAD

**Issue by sharath-madappa** [Adobe-Consulting-Services/acs-aem-commons#382]
The i18n part does not work when response from the error page designated by the _errorPages_ property  is included by the error page handler.

The translations work fine when the error page is directly requested. However it fails to pick up any values and falls back to the key when the response of the error page is included by [**includeUsingGET**](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/errorpagehandler/ErrorPageHandlerService.java) method

_Example :_
`com.day.cq.i18n.I18n i18n = new     com.day.cq.i18n.I18n(slingRequest.getResourceBundle(currentPage.getLanguage(false)));` 
`String translatedValue = i18n.get("key");`
`out.write(translatedValue);`

1.Output when error page is **accessed directly** with a get request -> translatedValue
2.Output when the error page is **included by errorpagehandler** on a 404 -> key

The value of `currentPage.getLanguage(false).getLanguage()` is same in both the cases.

**Comment by ronnyfm** [comment]
For CQ5.6, just edit your *org.apache.sling.i18n.impl.I18NFilter.config*, adding the following line (without spaces):

`sling.filter.scope=["REQUEST","ERROR"]`
