### ISSUE TITLE
Support dynamic width on multifieldpanel

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#383]
Currently I need to specify the width for each widget in the MultiFieldPanel (http://adobe-consulting-services.github.io/acs-aem-commons/features/widgets.html). Otherwise the default form layout (http://docs.adobe.com/docs/en/cq/current/widgets-api/index.html?class=CQ.Ext.layout.FormLayout) does not work well (i.e. it will not make the widgets span the whole width next to the label). It seems that form-layout cannot really be nested. Maybe another layout is better to choose as the default.

**Comment by davidjgonzalez** [comment]
Also ClassicUI
