### ISSUE TITLE
EmailService of acs-aem-commons 1.9.2 sends plain text mail

### ISSUE THREAD

**Issue by gschneck** [Adobe-Consulting-Services/acs-aem-commons#393]
With v1.7.4 : 

`MIME-Version: 1.0
Content-Type: multipart/mixed;
        boundary="----=_Part_1_305313608.1418050055425"

------=_Part_1_305313608.1418050055425
Content-Type: multipart/alternative;
        boundary="----=_Part_2_1067376973.1418050055425"

------=_Part_2_1067376973.1418050055425
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit`

With 1.9.2 : 

`MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit`

**Comment by davidjgonzalez** [comment]
Fixed via Documentation for EmailService of acs-aem-commons 1.9.2 sends plain text mail #52
