### ISSUE TITLE
Responsive column control component not working

### ISSUE THREAD

**Issue by raviks007** [Adobe-Consulting-Services/acs-aem-commons#394]
When we drag and drop the column control component and define the column layout like 50, 50, in the author mode, the layout wont appear as 2 columns(in my case 50%-50% columns). Also we cannot see the parsys of the second column at all. All I see is the first column and parsys underneath. When I edited in firebug and then added a new component in the second column using firebug and surprised to see the component is displayed at the end of the first column components and not next to each other. 
Please see the screenshot for more details.
![image](https://cloud.githubusercontent.com/assets/7669340/5358622/a0a06d12-7fb6-11e4-94b0-c39dc35d92e1.png)

**Comment by davidjgonzalez** [comment]
@raviks007 I think you have some good ideas. 

Ill close for now and you or someone else that takes an interest can provide an Pull Request w these enhancements.

**Comment by srikanth010** [comment]
Can Anyone help me where can i find acs-commons.components?
