### ISSUE TITLE
HTTP Request Logger

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#395]
A high-level Request Filter that writes very verbose information about a Request to the logger.

Information to log would include most `HttpServletRequest.get*()` including Headers and Parameters.

**Comment by davidjgonzalez** [comment]
Works much better as a Sling Filter .. `SlingHttpServletRequest` provides some niceties around data access.

**Comment by davidjgonzalez** [comment]
@benpeter i've added a handful of request options to the filters accept method that might help you with logging specific requests ex. POSTs; you can accept by: HTTP Method, HTTP Header, Path prefixes

1 outta 3 aint bad, right?! ;)

**Comment by davidjgonzalez** [comment]
@chetanmeh Do think AEM Tracer would supersede this? I don't want to release it as a feature only to deprecate it for redundancy in a few months. WDYT?

**Comment by chetanmeh** [comment]
@davidjgonzalez AEM Trace would be a complimentry feature so serves a different purpose. However you do have a look at [Sling Request Analyzer][1]. May be we can extend that

@fmeschbe Thoughts?

[1]: http://sling.apache.org/documentation/bundles/request-analysis.html

**Comment by davidjgonzalez** [comment]
@justinedelson thoughts on this vs Sling request analyzer?

**Comment by davidjgonzalez** [comment]
Thoughts on what we should do w this?

It's all coded up; but also don't want to clutter the space w yet another tool.

(Granted im not sure how well used/known the other tools are in the AEM Space)
