### ISSUE TITLE
1.9.2 not found in repo.adobe.com

### ISSUE THREAD

**Issue by paulrohrbeck** [Adobe-Consulting-Services/acs-aem-commons#400]
It seems the 1.9.2 version does not exist in the Adobe repository. The link on the ACS site [1] points to [2].

[1] http://adobe-consulting-services.github.io/acs-aem-commons/
[2] http://repo.adobe.com/nexus/content/groups/public/com/adobe/acs/acs-aem-commons-content/1.9.2/

**Comment by davidjgonzalez** [comment]
@justinedelson Any insight into the repo.adobe situation?

**Comment by gaetanmarmasse** [comment]
Hey @davidjgonzalez & @justinedelson,
Any info on getting back the 1.9.2 into the public adobe repo?
Thanks

**Comment by davidjgonzalez** [comment]
@gaetanmarmasse it sounded like @justinedelson was able to escalate this internally; were hoping in the next day or two (i think?)

**Comment by gaetanmarmasse** [comment]
Thanks guys! We'll stay tuned.

**Comment by justinedelson** [comment]
This is finally fixed. Sorry for the inconvenience.
