### ISSUE TITLE
Usage Documentation / Unit Test  / Working example for Widgets?

### ISSUE THREAD

**Issue by bgronek** [Adobe-Consulting-Services/acs-aem-commons#411]
Is there any usage documentation or working examples for the widgets?  Specifically, I'm looking for information pertaining to the multi field panel.  

Thanks!

**Comment by davidjgonzalez** [comment]
@bgronek Have you checked the feature documentation page [1]? It provides a complete `cq:Widget` XML structure you can copy/paste into your Project. Are you looking for something else?

[1] http://adobe-consulting-services.github.io/acs-aem-commons/features/widgets.html

**Comment by bgronek** [comment]
Thanks for the quick response!

I found my issue.  I was actually working with this example and had it mis-configured.  Thanks so much!
