### ISSUE TITLE
Allow user selection of Disaptcher Flush UI Flush Agents

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#413]
Dispatch Flush UI selects all the active dispatcher flush agents by default and does not give the option to select the required agents. Can you please update this so that it gives an option to select from the available dispatcher flush agents.

**Comment by kalyanar** [comment]
I can do that. Is help still needed?

**Comment by davidjgonzalez** [comment]
@kalyanar yup - this we never implemented!
