### ISSUE TITLE
Provide a way to consume MultiFieldPanel values with an optionsProvider

### ISSUE THREAD

**Issue by dlh3** [Adobe-Consulting-Services/acs-aem-commons#417]
Perhaps this is a better candidate for acs-aem-samples.

I think it would be great to see a mechanism for consuming MultiFieldPanel values with an optionsProvider.  A simple use case is that a super user uses a MultiFieldPanel to define the options that will appear in a dropdown on a different dialog, which will be used by other, less privileged users.

The way that the MultiFieldPanel value is serialized, it can not be evaluated as the appropriate JSON object for an optionsProvider.  A simple transformation to use the data is something like:
```
eval(json.replaceAll("\\\"", "'").replaceAll("\"", ""))
```

**Comment by davidjgonzalez** [comment]
Creating an options provider sample would be great!

Wrt to Commons, I'm confused as to what would be populated? Would the options prepopulate field set? Or just a single field (ex drop down) in each set?

**Comment by dlh3** [comment]
I've created an example at https://gist.github.com/dlh3/11f8c2bd4efda0569c30

Please feel free to integrate this with acs-aem-samples.

**Comment by justinedelson** [comment]
moved to samples
