### ISSUE TITLE
Responsive Column Control: AfterEdit Listener Refresh breaks in TouchUI AEM 6-SP2

### ISSUE THREAD

**Issue by godanny86** [Adobe-Consulting-Services/acs-aem-commons#419]
When adding the Responsive Column Control to a page and editing the number of columns the first time the component behaves as expected. 

However on subsequent edits the AfterEdit listener does not get called to refresh the page. Instead the author has to manually refresh the page to view the updated columns. This occurs whether there is no content inside the columns:
![screen shot 2015-02-16 at 9 53 30 am](https://cloud.githubusercontent.com/assets/8974514/6213894/3e4de454-b5c2-11e4-866e-52dc88910d85.png)

and if there is content inside the columns:
![screen shot 2015-02-16 at 9 51 12 am](https://cloud.githubusercontent.com/assets/8974514/6213888/343c3312-b5c2-11e4-8d1a-1e396c2b37b1.png)

For the record I believe all components that embed subcomponents are effected by this update in SP2, but just wanted to record the issue in case a hotfix comes out. Classic UI authoring is not effected as far as I can tell.

**Comment by davidjgonzalez** [comment]
Deprecated feature; Should be Layout Container now
