### ISSUE TITLE
/apps/cq/core/content/nav/tools installed with wrong node type

### ISSUE THREAD

**Issue by dobrist** [Adobe-Consulting-Services/acs-aem-commons#420]
The node at /apps/cq/core/content/nav/tools is installed using node type nt:folder instead of nt:unstructured (as is the case for /libs/cq/core/content/nav/tools). This creates a conflict if another package tries to install an nav overlay as well.

**Comment by justinedelson** [comment]
Thanks!

@davidjgonzalez - can you check if this is also an issue for acs-aem-tools?

**Comment by davidjgonzalez** [comment]
Np - coulda sworn I had fixed this on both projs

**Comment by justinedelson** [comment]
I think we fixed one or two levels up from this...

**Comment by justinedelson** [comment]
but yes, very deja vu-y.
