### ISSUE TITLE
Lightweight HTML5 Scene 7 Video component

### ISSUE THREAD

**Issue by amol-anand** [Adobe-Consulting-Services/acs-aem-commons#422]
Scene7 Video Component that has Scene7 HTML5 embed code instead of the OOTB Scene7 Video Component that comes with AEM.

**Comment by amol-anand** [comment]
Would this be a useful component in the ACS AEM Commons arsenal ala the audio component?

**Comment by justinedelson** [comment]
@amol-anand probably :)

What's the difference in the embed code?

Also, is this different than the embed code you get when using the Dynamic Media video component?
