### ISSUE TITLE
Bulk Workflow Manager status update does not work properly in IE 10

### ISSUE THREAD

**Issue by ireasor** [Adobe-Consulting-Services/acs-aem-commons#431]
In IE 10, after clicking the button to 'Start Bulk Workflow', the page does a quick refresh and then highlights the required input fields in red.  If you wait a few seconds and refresh the page manually, you can see the status of the workflows.  Each time you want to see an updated status, you must manually refresh the page.

**Comment by davidjgonzalez** [comment]
I dont have IE10 - If a Windows/IE10 user can resolve this would be great.
