### ISSUE TITLE
Bulk Workflow Manager Doesnt Work on AEM 5.6.1

### ISSUE THREAD

**Issue by gauravs23** [Adobe-Consulting-Services/acs-aem-commons#433]
The button - Start Bulk Workflow is not visible on AEM 5.6.1. When inspecting the html it is hidden, so somewhere the angular code is failing, probably.

I have tried installing all the version of the acs-commons after version 1.8 in which Bulk Workflow Manager was introduced, but it doesnt work with any version on AEM 5.6.1, however as per guidelines, I believe 5.6.1 is being supported by acs-commons.

**Comment by davidjgonzalez** [comment]
@gauravs23 I verified this on 5.6.1 .. this appears to be an issue w ng not detecting the forms $valid and $pristine status; At the moment im a bit confused why/how this is contingent on the AEM version, since the ng version is the same.

**Comment by justinedelson** [comment]
Closing. Unfortunate that we couldn't get this to work, but we need to move on from 5.6.1 support.
