### ISSUE TITLE
Empty dialog fields overwritten when reordering Multifield Panel Items

### ISSUE THREAD

**Issue by radmike** [Adobe-Consulting-Services/acs-aem-commons#440]
Issue exists with the ACS Commons custom Multi Field Panel widget. Using the built-in dialog ordering mechanism (up/down arrows) to reorder items in the MFPanel list, empty/blank/optional dialog fields get overwritten by the item that is moved up or down. The values are no longer empty and persist if the dialog is saved.

To recreate:
1. Create a component dialog using the MFP widget; for example create a basic definitions (two-textfield MFP) as described here:
http://adobe-consulting-services.github.io/acs-aem-commons/features/widgets.html
2. Add this component to the design of a page or create a test page that uses this component
3. Open the dialog, and add four term/definitions to the dialog, but only fill out the 'term' field
4. In the third MFP item/row, fill out the 'definition' field w/ a test value
5. The 3rd item should be the only item w/ 'definition' included.
6. use the dialog MFP reordering mechanism to move the 3rd row up or down
7. the 3rd value will overwrite the empty values in the other rows, blowing away the empty values.

this makes reordering the items in a dialog w/ optional values difficult for authors.

you can also see this by filling out the bottom-most MFP row fully (term + definition), and adding a new, empty definition to the end of the list. Moving this item up to the middle of the list will cause the default empty fields to be overwritten by the data in other rows (starting with the bottom row).

This makes an otherwise awesome widget less usable for authors, especially around reordering.

**Comment by rajavdv** [comment]
I am also facing exactly the same behaviour. Reordering causes the empty field is overwritten by the value of item moved.

**Comment by schoudry** [comment]
working on it

**Comment by radmike** [comment]
awesome looking forwards to checking the fix <3 this project

**Comment by nishantongithub** [comment]
Has the issue of empty dialog fields being overwritten been solved?
