### ISSUE TITLE
Multi tenant dam assets error handling

### ISSUE THREAD

**Issue by kapildev111** [Adobe-Consulting-Services/acs-aem-commons#446]
We are using ACS AEM Commons version 1.9.4 (tried latest 1.9.6 as well) with AEM 6.0+service pack 1

Error handler is not supporting multi tenant dam assets error handling. Use case described below

We have two sites say SiteA and SiteB. ACS-commons error handler is configured for both the sites and for content pages works fine. Site structure/details given below

![screen shot 2015-04-20 at 11 45 02 am](https://cloud.githubusercontent.com/assets/6804078/7222484/f7d8d11a-e752-11e4-901a-a9971e1cf62c.png)

ACS-Commons Error Handler OSGI-Config is
<?xml version="1.0" encoding="UTF-8"?>   
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"    
jcr:primaryType="sling:OsgiConfig"     
error-page.system-path="/content/sitea/errors/404"     
not-found.behavior="respond-with-404"/>

If for any page aem returns 404 status code for either of the sites, it shows the correct 404.html page configured with the acs-commons error handler from the respective site and looks all good.

If any DAM asset (from one of the sites dam structure like /content/dam/sitea/images/imagex.png or /content/dam/siteb/images/imagex.png) is accessed which do not exists, in that case error handler returns error-page.system-path which is configured as “/content/sitea/errors/404” for both the sites which we do not want. 

We wanted to show the error pages respective to the site as it is happening in case of the content pages. Is it possible to add the errorPages property to the DAM site node as well so that it shows the corresponding error pages for any of the sites DAM assets as well(or some other solution). We don’t want to use the image placeholder’s property of error handler(It’s not even working either. Not sure if anyone have tested/used it before).

**Comment by davidjgonzalez** [comment]
@kapildev111 Error Page Handler does not have this granularity of support for Images. A pull request with this feature is welcome and/or you can see if someone in the community wants to pick this up. I've marked it as a Feature Request.

**Comment by kapildev111** [comment]
Sure David. Will be pick this up.

Thanks
Kapil

**Comment by davidjgonzalez** [comment]
@justinedelson @kapildev111 @tinotruppel

Error Page Handler Impl is starting to feel a bit bloated; 
* Generic handling
* Generic Image handling
* Caching
* Proposed multi-tenant handling 

Thoughts on using this opportunity to break these concerns out into supporting services? 

Maintaining backwards compatibility might be challenging. 

WDYT? Am I overthinking it?
