### ISSUE TITLE
missing dependency on CQ 6.1

### ISSUE THREAD

**Issue by hughwah** [Adobe-Consulting-Services/acs-aem-commons#447]
com.adobe.acs.acs-aem-commons-bundle fails to resolve the dependency:
com.day.cq.mailer,version=[5.6,6) -- Cannot be resolved

the package exists within osgi but is version 6.0.0.  this does not happen in CQ 6.0, as that package has a version of 5.8.0

**Comment by justinedelson** [comment]
This is a bug in AEM and will be fixed before GA. We can leave this issue open until that point if desired, but this is a no-op for ACS AEM Commons.
