### ISSUE TITLE
Authentication error while adding com.adobe.acs:acs-aem-commons-bundle:pom:1.9.6  dependency

### ISSUE THREAD

**Issue by chhavi1412** [Adobe-Consulting-Services/acs-aem-commons#449]
While creating a project and adding following error is received:

Failed to read artifact descriptor for com.adobe.acs:acs-aem-commons-bundle:jar:1.9.6: Could not transfer artifact com.adobe.acs:acs-aem-commons-bundle:pom:1.9.6 from/to adobe-public-releases (https://repo.adobe.com/nexus/content/groups/public): peer not authenticated -> [Help 1]

How can we take care of this error ?

**Comment by davidjgonzalez** [comment]
Have you looked at http://stackoverflow.com/questions/15691985/maven-release-peer-not-authenticated ?

Sounds like your maven build is not able to establish a HTTPS connection w the nexus repo. On my phone so cant try anything out, but I'd poke around Google for "maven +peer not authenticated" .. I haven't seen anyone else complain about cert issues today so I expect this is localized to you/your machine.

**Comment by davidjgonzalez** [comment]
@chhavi1412 closing as this does not appear to be an issue w the project.
