### ISSUE TITLE
TransformerTypes versioned-clientlibs issue with AEM 6 SP2

### ISSUE THREAD

**Issue by tvdoan** [Adobe-Consulting-Services/acs-aem-commons#451]
Hi,

Our site is currently using acs-aem-commons to solve the client-side caching and it works flawlessly.  However, we want to apply SP2 to our existing AEM 6, but after testing, we noticed, versioned-clientlibs is not working with AEM 6 SP2.

All our CSS and JS files do not have the MD5 appended to it.  Can you please take a look and advice as to how long we can wait for a release, which will fix this issue?

Thanks,
Doan

**Comment by davidjgonzalez** [comment]
@tvdoan can you verify that the transform is registered and active at: http://localhost:4502/system/console/status-slingrewriter

**Comment by tvdoan** [comment]
It looks like it is:

Current Apache Sling Rewriter Configuration
=================================================================
Active Configurations
-----------------------------------------------------------------
Configuration custom

Content Types : [text/html]
Paths : [/content/sas, /content/sas-test, /content/campaigns/sas, /content/campaigns/sas-test]
Order : 1
Active : true
Valid : true
Process Error Response : true
Pipeline : 
    Generator : 
        htmlparser
    Transformers : 
        versioned-clientlibs
        friendly-url-link-transformer
    Serializer : 
        htmlwriter
Resource path: /apps/sas/config/rewriter/custom


Configuration pdf

Extensions : [pdf]
Order : 0
Active : true
Valid : true
Process Error Response : false
Pipeline : 
    Generator : 
        empty-generator
    Transformers : 
        htmlparser
        xslt : {source=sling://libs/wcm/core/content/pdf/page2fo.xsl}
    Serializer : 
        fop : {mime-type=application/pdf}
Resource path: /libs/cq/config/rewriter/pdf


Configuration default

Content Types : [text/html]
Order : -1
Active : true
Valid : true
Process Error Response : true
Pipeline : 
    Generator : 
        htmlparser
    Transformers : 
        linkchecker
        mobile : {component-optional=true}
        mobiledebug : {component-optional=true}
        contentsync : {component-optional=true}
    Serializer : 
        htmlwriter
Resource path: /libs/cq/config/rewriter/default

**Comment by justinedelson** [comment]
In the Recent Requests web console plugin, please find the request log for an HTML page and post the line begining with:

   LOG Found processor for post processing ProcessorConfiguration

For example:

    54 LOG Found processor for post processing ProcessorConfiguration: {contentTypes=[text/html],order=-1, active=true, valid=true, processErrorResponse=true, pipeline=(generator=Config(type=htmlparser, config={}), transformers=(Config(type=linkchecker, config={}), Config(type=mobile, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-mobile: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), Config(type=mobiledebug, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-mobiledebug: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), Config(type=contentsync, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-contentsync: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), serializer=Config(type=htmlwriter, config={}))}

**Comment by justinedelson** [comment]
FWIW, I can't reproduce this with AEM 6.0SP2.

I created this package with a sample configuration: https://files.acrobat.com/a/preview/2b6f5d9e-d097-4d18-b51f-eb3ec9817662

**Comment by tvdoan** [comment]
Thanks for that Justine.  Looking further into the issue, I found out that
one of our Filters was causing this bug and not because of SP2.  Appreciate
your help.
