### ISSUE TITLE
TransformerTypes versioned-clientlibs issue when forwarding request

### ISSUE THREAD

**Issue by tvdoan** [Adobe-Consulting-Services/acs-aem-commons#452]
Hi,

I have a filter which intercepts requests and forward them to a resource. If I don't forward the request and instead using filterChain.doFilter(request, response), it works fine.  Example below:

versioned-clientlibs is not working when forwarding request:

public class MyFilter implements Filter {
    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain) throws IOException, ServletException {
            RequestDispatcher requestDispatcher = request.getRequestDispatcher("/content/my_page.html").forward(request, response);
     }
}

versioned-clientlibs is working:

public class MyFilter implements Filter {
    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain) throws IOException, ServletException {
        filterChain.doFilter(request, response);
     }
}

Also, this only started happening when we migrated to AEM 6 SP2.

One more thing, if I go directly to the URL, e.g. http://localhost:4503/content/my_page.html, versioned-clientlibs is also working fine.

Hope you can provide us some lights as to why this is happening.

Cheers!

**Comment by justinedelson** [comment]
Can you provide the information from the Recent Requests web console tab I requested in #451

**Comment by justinedelson** [comment]
Looking at this some more, I don't see how this could possibly be related to the versioned-clientlib transformer specifically. Do you have a package which demonstrates this issue as being *only* related to this one transformer, i.e. showing that one of the standard transformers (e.g. linkchecker) works but versioned-clientlibs does not? Without some way of reproducing the problem, I don't think we can consider this to be a defect with ACS AEM Commons.

**Comment by tvdoan** [comment]
Hi Justine,

We are not using linkchecker, we only used the versioned-clientlibs.  Also,
we used acs-aem-commons version 1.6.2, could that be the issue as well?

Is it possible for you to create a page, then copy my Filter and just
forward the request to that page for all requests and see if it works for
you.

As I mentioned, it was working with SP1, but not SP2 of AEM 6.

I will try to update acs-aem-commons to 1.9.6 and see if that solves the
problem.



Thanks,
Trang

**Comment by justinedelson** [comment]
Again, I see no reason to think this is an issue with ACS AEM Commons, so I don't see how deploying a different version will help. Please provide the log entries I mentioned and a package which can be used to reproduce the issue. Your filter is incomplete -- it has no annotations.

**Comment by justinedelson** [comment]
To be clear, the package needs to contain:
* a bundle containing the filter
* the rewriter configuration

**Comment by justinedelson** [comment]
Feel free to provide a Maven project which can be used to build such a package or a pre-built package. Either way is fine.

**Comment by tvdoan** [comment]
I have also debugged VersionedClientLibsTransformerFactory.java and found
that when the Filter forward on the request, the transformer does not get
called at all.  However, if I go directly to the page, e.g.
http://publisher:4503/content/my_page.html, the transformer does get called
and script/css are transformed.

**Comment by justinedelson** [comment]
Exactly as I suspected -- based on that, it is almost impossible this is something we can address in this project. Of course, I would still like a reproducible test case to be sure.

**Comment by tvdoan** [comment]
import org.apache.felix.scr.annotations.sling.SlingFilter;
import org.apache.felix.scr.annotations.sling.SlingFilterScope;

import javax.servlet.*;
import java.io.IOException;

@SlingFilter(name = "friendly-url-redirect-filter", scope =
SlingFilterScope.REQUEST, order = 1)
public class FriendlyUrlRedirectFilter implements Filter {

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
    }

    @Override
    public void doFilter(ServletRequest request, ServletResponse
response, FilterChain filterChain) throws IOException,
ServletException {
        RequestDispatcher requestDispatcher =
request.getRequestDispatcher("/content/sas.html");
        requestDispatcher.forward(request, response);
    }

    @Override
    public void destroy() {
    }
}

**Comment by tvdoan** [comment]
I can't send the package zip file, as there is some restrictions on the
message...can you please provide an email I can send it to?

**Comment by justinedelson** [comment]
that filter appears to forward every request. Was that intentional?

**Comment by justinedelson** [comment]
Sure. My email is jedelson@adobe.com

**Comment by tvdoan** [comment]
Yes, that is correct.  I want it to just forward to that page, so you can
verify that the versioned-clientlibs is not applied to css and js.

**Comment by justinedelson** [comment]
Hi,
I did not get the package from you, but I was able to reproduce this with a vanilla AEM 6.0 SP2 setup. 

Code to reproduce is here: https://github.com/justinedelson/rewriter-with-filter-testcase
Binary package here: https://files.acrobat.com/a/preview/bfb83d0f-008e-4cb9-a2cc-6bdb816d8ebe

After installing, access http://localhost:4502/content/geometrixx-outdoors/en.html?redirect=true

If the rewriter filter is called, the "click me" link under Shape Technology will have been supressed by the link checker. If the rewriter filter is not called, this link will be present, but not go anywhere.

You can workaround this issue by changing the order of your filter to be -3000.

This issue is unrelated to ACS AEM Commons and there is nothing which can be done in this project to workaround it. Thus closing.

**Comment by tvdoan** [comment]
Thanks for looking into it Justine.  Yes, I am not sure whether it is Adobe AEM bug or acs commons.

**Comment by justinedelson** [comment]
What is the source of your continued uncertainty? If this is reproducible with the linkchecker transformer, that seems to definitively illustrate that it is not related to anything in this project.

**Comment by tvdoan** [comment]
Sorry, I meant to say I wasn't sure where the bug was from, hence why I
submit a issue log on both ACS AEM Commons  and Adobe.

Also, wanted to let you know the work around does work, so thanks for that.
