### ISSUE TITLE
Quickly - Uncaught TypeError: Cannot read property 'module' of undefined

### ISSUE THREAD

**Issue by joseph-devito** [Adobe-Consulting-Services/acs-aem-commons#453]
Im still using AEM Build :Adobe Experience Manager, Version 6.0.0.20140509  
We are on SP2
Im using the 1.9.7 ACS commons package that jgonzalez created to fix the Java 8 issue

On loading the touch interface that module error immediately populates and it causes all of quickly to fail.  Im not sure what changed within my instance (at least what would change that would affect the quickly client lib)  I've isolated the issue to:

http://localhost:4502/apps/acs-commons/components/utilities/quickly/clientlibs.js

/*
 AngularJS v1.3.3
 (c) 2010-2014 Google, Inc. http://angularjs.org
 License: MIT
*/
(function(M,f,S){'use strict';f.module("ngAnimate",["ng"]). -- The first line where 'module' is called within angular

**Comment by davidjgonzalez** [comment]
@joseph-devito can you try uninstalling ACS Commons and re-installing?

I recall seeing something w this in the past; it seemed like the client libs didnt include the main angular JS file.

**Comment by joseph-devito** [comment]
So I had tried uninstalling via pkg mngr and that didnt work BUT this time I fully deleted it after installing and did a fresh install and that appears to have worked.  So it looks like a full removal is required.  Any idea of why that would happen?  Is there a way to change my build process to make sure it grabs these clientlibs that it needs?

**Comment by davidjgonzalez** [comment]
@joseph-devito i dont think there is a problem w your build process. I think this is an issue w CQ's HtmlLibraryManager but need to debug it some more. The odd part is how it randomly works/doesnt work w the exact same CQ Package.

**Comment by joseph-devito** [comment]
Okay, I'll just have to keep an eye on my environments , until that LibraryManager is fixed in order to use it across my 3 environments Ill have to implement a manual remove / re-add of the ACS commons

**Comment by davidjgonzalez** [comment]
@joseph-devito can you consistently reproduce this? I see it from time to time but once i fix it (uninstalling, deleting, reinstalling) it fixes it self for a bit

**Comment by joseph-devito** [comment]
I thought it occurred on build for me but nope, just did a new build and I still have quickly functionality so it is intermittent

**Comment by davidjgonzalez** [comment]
@joseph-devito FYI -  84474dd95f400ce4597139e565539a4f551a03b7 should fix this; It splits the main AngularJS main include into a separate call so it wont be lost during the quickly clientlib packing.

**Comment by joseph-devito** [comment]
Im using your 1.9.7 package that you provided me, is there a way you could add this into that?

**Comment by davidjgonzalez** [comment]
Sure ..

https://www.dropbox.com/s/6kkmba4gnv6tn11/acs-aem-commons-content-1.9.7-SNAPSHOT.zip?dl=0

https://www.dropbox.com/s/38jn8tpnd1bduu9/acs-aem-commons-content-1.9.7-SNAPSHOT-min.zip?dl=0
