### ISSUE TITLE
MultifieldPanel in page properties custom tab gives "Unresponsive script" error when more than 40 items are added in it.

### ISSUE THREAD

**Issue by rajeevratnasd** [Adobe-Consulting-Services/acs-aem-commons#455]
MultifieldPanel in page properties custom tab gives "Unresponsive script" error on Mozilla Firefox and IE9 when more than 40 items are added in it.
Steps to Reproduce.
1) Create a custom tab in the page properties of any page.
2) Add a multifield in that tab using ACS MultifieldPanel.
3) Add 40-50 items in that multifield.
4) When we visit the page properties again of the same page, the browser is giving a popup saying "Warning : Unresponsive Script" and gives options to continue, debug & stop the script (Attached screenshot of error).

Need to remove this error. Help needed. 
Thank You.
![unresponsiveerror](https://cloud.githubusercontent.com/assets/12445318/7632258/d2873734-fa68-11e4-9818-44ee6a8e65cf.png)

**Comment by justinedelson** [comment]
@kalyanar - WDYT about this? Can anything be done?

**Comment by lsaini** [comment]
Hi,

Did anyone find a resolution for this issue. Similar case is happening when we are using multifield with items around 50. Please let us know if there is a solution this
