### ISSUE TITLE
Component Error Handler disables the Sling Error Handler in Author instance

### ISSUE THREAD

**Issue by niradadas** [Adobe-Consulting-Services/acs-aem-commons#457]
Steps to reproduce:

Enable the component error handler in author mode.
Open a valid url: http://localhost:4502/cf#/content/myapp/us/en/home.html
Enter some junk value in the url in the middle of the url: http://localhost:4502/cf#/content/mya000pp/us/en/home.html, it renders our sling customized 404 page, which is expected.
Enter some junk value in the url in the end node of the url: http://localhost:4502/cf#/content/myapp/us/en/home000.html, it renders the component error handler's edit.html rather than the sling 404 page.

Here, in the last step, although the exception is resource not found(404), it directly calls the component error handler and not the sling errorPageHandler.

**Comment by davidjgonzalez** [comment]
@niradadas I think you are running into the same issue as: http://adobe-consulting-services.github.io/acs-aem-commons/features/errorpagehandler.html#comment-1698474318

**Comment by niradadas** [comment]
Thanks for the reply @davidjgonzalez , but the link you have mentioned is quite different from the issue I am facing. Your suggested link discusses about the 500 error, where as I m finding trouble in displaying the 404 page in author, as the component error handler is called before the sling errorPageHandler when a ResourceNotFoundException occurs, and instead of our customized 404 page, the acs-common's edit.html is displayed.
