### ISSUE TITLE
Extjs IFramed Dialogs in TouchUI submit issue

### ISSUE THREAD

**Issue by andre-inside** [Adobe-Consulting-Services/acs-aem-commons#458]
Since installation of acs commons 1.10.0 touchui dialogs which have embedded ExtJS dialog in it can't be submitted anymore (request is issued, but the screen is stuck in the "pending submit" state). How to reproduce:
- Create new geometrixx page
- Open the page in touchui
- Add any component which has no touchui dialog yet (for instance sitemap -> foundation/components/sitemap)
- Open the dialog
- Submit or Cancel -> JS Error -> "Uncaught TypeError: Cannot read property 'addEventListener' of null"

**Comment by justinedelson** [comment]
@schoudry - can you look into this? I would like to hold off on publicizing the release until this can be addressed.

**Comment by schoudry** [comment]
checking....
