### ISSUE TITLE
Create an easy way to update content associated with component changes

### ISSUE THREAD

**Issue by shsteimer** [Adobe-Consulting-Services/acs-aem-commons#460]
Often during the course of a projects, components will evolve and those evolutions necessitate updates to existing content.  Just a few examples of this, though there are many more:
- moving a component; need to update the sling:resourceType of all component instances
- change the value of a drop down selection option; need to update old value to new value
- add new dialog property with default value; need to update all component instances with this new property

It would be cool if there was an easy way to handle things like this.  My normal approach has been to write a script and run it as a post-deployment step, but that tends to be tedious and one-off.  

I'm still brain-storming this, but I was thinking that this could be done via a factory service.  sling:OsgiConfig's could be created that describe the updates to be made (TBD, what are the options on the config to allow for flexibility but also ease of use).  The rules would be run on service activation, causing the content to be updated as described.

**Comment by davidjgonzalez** [comment]
@shsteimer love the idea - I think this is in the same vein as: 

https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/325

**Comment by shsteimer** [comment]
@davidjgonzalez Yes, I'd agree.  I had seen that issue before, but it didn't come to mind when I created this.  

I guess I see this as a specific use-case for your code droplets idea, where code droplets would be more generalized.

**Comment by davidjgonzalez** [comment]
@shsteimer btw - this might help you wrt to sling:resourceType and cq:template changes: http://adobe-consulting-services.github.io/acs-aem-tools/csv-resource-type-updater.html

**Comment by badvision** [comment]
If you could create a blockly-based script and then assign that script to an action such as a content change, would that work?  It could use sling's listener mechanics for that, possibly.
