### ISSUE TITLE
HTTPComponentsFactory

### ISSUE THREAD

**Issue by kalyanar** [Adobe-Consulting-Services/acs-aem-commons#467]
ACSCommonsHttpClientFactory - a component factory that lets us configure for each domain and easily make use of apache HTTPComponents.

configuration is like this

com.adobe.acs.commons.httpclient.HttpClientFactory-domain1
with options for domain,scheme,port,username,password, max connections per domain,total max connections.

Usage is like this
  ACSCommonsHttpClient acsCommonsHttpClient = httpClientFactory.getACSCommonsHttpClient("http://google.com",HTTPRequestMethod.GET);
        acsCommonsHttpClient.addBody("");//for post
        acsCommonsHttpClient.addHeaders(new HashMap<String, List<String>>());
        acsCommonsHttpClient.addCookies(new ArrayList<String>());
        acsCommonsHttpClient.addResponseClassType(String.class);
       Response<String> response = acsCommonsHttpClient.executeAndConvertJsonResponseToPojo();

**Comment by davidjgonzalez** [comment]
@kalyanar take a spin through the Apache APIs, and this looks like a nice convenience wrapper.

What were you thinking wrt to supported authentication schemes? 

Also - if there isnt already an existing corollar to this in the Apache APIs (if there is then this might not be that valuable) I think just calling it "HttpComponentsJsonClient" or something would be cleaner. (Also - cant tell , but this example seems to execute, and convert a JSON response to a POJO; not sure if the vision is to handle and serialize-to different formats.

**Comment by kalyanar** [comment]
I wrote this for connecting to SAP via oauth and a simple basic auth scheme in my current project. We have  is a Jsonserializer using jackson and a method to simple return a string(if the REst end point returns some other format). I can pass a ResponseSerializer interface to the method allowing anyone to customize for other formats.

Response<T> response = acsCommonsHttpClient.execute(ResponseSerializer.JSON);

**Comment by justinedelson** [comment]
Hi,
Perhaps I'm missing something - what does this do which HttpClient doesn't do natively? If it is just a matter of configuring an HttpClient instance, that makes sense, but then it looks like there is some business about processing responses -- wouldn't that make more sense to implement using the `ResponseHandler` interface?

IIOW, why not just use this code:

    CookieStore cs = new CookieStore();
    cs.addCookie("name", "value");

    Request request = Request.get("http://www.google.com/").addHeader("name", "value");
    Executor executor = Executor.newInstance().use(cs);
    Response response = executor.execute(request);
    JSONObject json = response.handleResponse(new JsonHandler());

In which case, the only new code necessary is a `JsonHandler` class. If we're specifically talking about OAuth, then it would be better to use one of the libraries already in AEM to handle OAuth requests. There are also one or two additional projects which integrate OAuth signing into Apache HttpClient. 

Justin

**Comment by davidjgonzalez** [comment]
Agree - this is hard for me to conceptualize without seeing the code. I *think* there are 2 pieces here:

1) defining base-line connection params via an OSGi Config factory -- i suspect the use case is if multiple AEM Services could access the same external service (Ex. hitting the same SFDC, SAP, etc.) and this allows the connection config to be centrally managed per env.

2) serializing the response into a "consumable" format (JSON, POJO?, etc.)

@kalyanar can you provide a 2-3 liner on the problem that this is solving that the Apache APIs dont provide a (reasonably) clean solution for?

**Comment by justinedelson** [comment]
FWIW, the first use case totally makes sense to me, but I would expect the service code to return an HttpClient instance (or an Executor instance if you wanted to use HC Fluent), not an instance of some ACS AEM Commons-specific interface.

**Comment by davidjgonzalez** [comment]
yeah - unless theres a very compelling reason, we shouldn't make folks dependent on ACS APIs.

If the Config Factory could return a standard Apache HC object, that would be ideal, same w passing in a ACS impl'd result handler (assuming we can impl an interface for our common use-cases)

**Comment by kalyanar** [comment]
@davidjgonzalez , @justinedelson . Thanks for the comments. Just to explain what I was trying to do. 

 The idea of the wrapper here was to allow the developers to just send in List of Strings for cookies and Map for headers.  This also allows us to change the internal implementation to any other library. 
 We can preconfigure a handler in the factory for all similar requests. Assuming, all GET calls to SAP(or any specific domain( will result in a JSON response or  an XML response(any specific type). We can even have the handler to be configured in the factory itself and our handler class can serialize the format to any pojo.
ACSResponse<Sample.class> response = acsClient.execute("url",params,cookiesList,headersMap,Sample.class)
Sample sample = response.getContent();

The configuration for acsClient would have
gateway.domain
gateway.port
responsetype - (JSON/XML/ATOM etc)
timeout
numberofconcurrentreq

**Comment by justinedelson** [comment]
@kalyanar regarding the headers/cookies - I'd personally rather see this done with helper classes which interact with the HC Fluent API. For example:

    CookieStore cs = new MapBackedCookieStore(cookieMap);
    executor.use(cs);
    HCUtils.setHeaders(request, headerMap);

This would be a minimal API surface.

For the rest, you could do also do this with a heleper service:

    Executor executor = httpClientFactory.getExecutor(); // would set up auth
    Request request = httpClientFactory.get("/foo/bar"); (with other methods like post(), put(), etc.) which would simply prepend the scheme/host/port from the configuration to the path.
    Response response = executor.execute(request);

The thing this doesn't account for is how you get a properly typed object out of response.handleResponse(). You could have httpClientFactory.getResponseHandler(), but I don't think this could return a parameterized object. You could do a cast:

    JSONObject json = (JSONObject) response.handleResponse(httpClientFactory.getResponseHandler());

But I think it would be better to just provide some implementations of ResponseHandler and do

    JSONObject json = response.handleResponse(new JSONResponseHandler());

To be clear, the reason I'm wary of building a complete abstraction in front of HttpClient is that this would take on a lot of responsibility. There's a lot of options there.

**Comment by kalyanar** [comment]
Sure. I will implement in the same way.

**Comment by davidjgonzalez** [comment]
Fixed via .. https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/http/impl/HttpClientFactoryImpl.java
