### ISSUE TITLE
Workflow Remover persisted running state after Exception is thrown

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#468]
Sometimes the Workflow Remover cannot update the WF Remover status node (Repository exception) which stops the thread from executing but keeping the node marked as "running" preventing subsequent execution (until the property is manually cleared).

The observed cause is a RepositoryException (trying to write to these values), so there should be a retry mechanism to update this property, and/or some other checks (possibly a last updated check that allows a running state to be reset)

**Comment by justinedelson** [comment]
Setting milestone to 2.0, but might slip I suppose depending on @davidjgonzalez 's availability to fix :)

**Comment by justinedelson** [comment]
is this done? or should the milestone be changed?

**Comment by davidjgonzalez** [comment]
Done
