### ISSUE TITLE
Links are removed when we use RTE in multifieldpanel widget  

### ISSUE THREAD

**Issue by deepmca** [Adobe-Consulting-Services/acs-aem-commons#469]
Steps to reproduce : 
1. Add RTE in multifieldpanel .
2. In the dialog open RTE which is added in multifieldpanel .
3. add some text in RTE and hyperlink some text using RTE link plugin and click ok .
4. submit the dialog 
5. check RTE text again(using view source ) the links which are added to text will be removed 
Also refer to screen shot as well

It seems that due to this line [1] in multifieldpanel widget  issue is happening so we when we comment this line , this issue get fixed . Please have a look in that also I would like to know that is it safe to comment this line  .
Thanks in advance 

[1] pData[i.key] = predata.replace(/"/g, '&quot;');
![screen shot 2015-06-17 at 1 17 15 pm](https://cloud.githubusercontent.com/assets/6832624/8199087/45606c18-14f3-11e5-95e8-5b0343a22aba.png)

**Comment by djessup** [comment]
This doesn't just affect RTE fields, any text field with double quotes is having them erroneously escaped to &quot;

I don't understand why this escaping is happening, since the only obvious reason is to avoid JSON syntax errors, however JSON.stringify will do this automatically  - e.g. "quotes" becomes \"quotes\".

**Comment by justinedelson** [comment]
@brennill @djessup I'm going to reopen this based on your comments. If this was wrong, please let me know and I'll reclose it.

**Comment by davidjgonzalez** [comment]
in support of a deprecated ClassicUI .. closing as wont fix

**Comment by djessup** [comment]
Suggest updating the documentation and listing this as a known issue, if it still occurs.
