### ISSUE TITLE
touchui-composite-multifield doesn't load values for several field types e.g. checkbox, dropdown selection

### ISSUE THREAD

**Issue by keseruk** [Adobe-Consulting-Services/acs-aem-commons#477]
When using checkbox on a touch ui dialog built using touchui-composite-multifield, then values from those fields added to the composite multifield form will be saved to JCR properly, but several fields won't load/display the value when I open the dialog again. We observer this issue with checkbox and dropdown selection fields so far. To reproduce the issue, just add a checkbox to the dialog example in touchui-composite-multifield.js.

**Comment by justinedelson** [comment]
Can you add a content package containing a test component?

**Comment by keseruk** [comment]
Added simple component for demonstrating the issue. Rename to .zip. Thanks!
![checkbox](https://cloud.githubusercontent.com/assets/6104409/8377550/7f072a76-1c12-11e5-8a4e-56b3cc0f4465.png)

**Comment by keseruk** [comment]
I found the same issue in the widget published on http://experience-aem.blogspot.hu/2015/06/aem-61-touch-ui-composite-multifield-store-values-as-child-nodes.html and the fix that Sreekanth provided worked. Probably works here, too?

**Comment by justinedelson** [comment]
@kalyanar - can you help identify what needs to be done here?

**Comment by kalyanar** [comment]
Sure.
I shall look at it over the weekend.

**Comment by akuntsch** [comment]
I have the same problem with checkboxes.

Is there any update on the issue?

**Comment by NielsInc** [comment]
Dropdown selection fields are still not being populated correctly in the latest release (2.1.2).
For me the fix that Sreekanth provides is an alternative, but has a different approach since it stores the values of the children in a child node instead of in JSON format - which means adapting code for an unofficial fix that might be implemented differently in the acs-aem-commons - so not very desirable...

**Comment by schoudry** [comment]
I'll work on a fix

**Comment by akuntsch** [comment]
Thanks @schoudry. Your fix works for checkboxes.

**Comment by mt33** [comment]
Thanks for this PR, exactly what I was looking for!

**Comment by NielsInc** [comment]
@schoudry Is there an event that is triggered when the data is loaded? 
The values for the multifield are set after the `foundation-contentloaded` event is triggered, so the content is not yet available then

**Comment by schoudry** [comment]
@NielsInc with current code, no custom events are triggered after data load or data update

**Comment by mt33** [comment]
I've run into the same use @NielsInc - submitted #591
