### ISSUE TITLE
Oak Index manager does not support deployments on ContextRoots other than /

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#480]
I have deployed AEM 6.0 on an application server using the context root "/cqa/", but the the Oak Index Manager does a JSON request to "/etc/acs-commons/oak-index-manager/_jcr_content.list.json", which fails of course with an internal server error (delivered by the application server).

This request should include the context root.

**Comment by davidjgonzalez** [comment]
@joerghoh what version are you using? This should be resolved now per the rr.map(..) call here:

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/components/utilities/oak-index-manager/oak-index-manager.jsp#L24

**Comment by joerghoh** [comment]
I use 1.9.4

**Comment by davidjgonzalez** [comment]
This was fixed in 1.10.0
