### ISSUE TITLE
NamedTransformImageServlet should check for null-Layer and send 404 status

### ISSUE THREAD

**Issue by m-kay** [Adobe-Consulting-Services/acs-aem-commons#483]
Before trying to transform the Layer with all the configured transformers the NamedTransformImageServlet should check if the Layer is not null. If it is null the servlet should send  a response with 404 status code.
This can happen if a fileReference is used which doesn't exist anymore and can lead to NullPointerExpetions in all the configured transformers

**Comment by davidjgonzalez** [comment]
Good catch. Will see if I can get this updated this weekend! 

Appreciate the feedback!

**Comment by m-kay** [comment]
Thanks for the quick fix.

Do you know when the next version will be release so we could include this fix?
