### ISSUE TITLE
Base AJAX Component - Content Is not displaying in Publish

### ISSUE THREAD

**Issue by veenavikram07** [Adobe-Consulting-Services/acs-aem-commons#486]
Hi

   I have followed the steps and set slin:resourceSuperType and renamed my jsp to ajax.jsp. When I am authoring, the component's values are displaying in the author mode. But the same is not visible in the publish mode

Please let me know if this is a bug or I missed any configuration. Please find Screenshots below

Author view

![image](https://cloud.githubusercontent.com/assets/5857468/9011327/42591796-37ca-11e5-98ce-0acb81f18a39.png)

Publish View

![image](https://cloud.githubusercontent.com/assets/5857468/9011333/52f40fa2-37ca-11e5-8915-c32e27e7af06.png)

Apps

![image](https://cloud.githubusercontent.com/assets/5857468/9011361/7894e4de-37ca-11e5-9f30-eb592ed2f9ce.png)

Thanks
Veena

**Comment by davidjgonzalez** [comment]
@veenavikram07 did you include the acs-commons.components clientlib into your site's clientlib? If you dont then the JS doesnt exist to do the AJAXing.

**Comment by justinedelson** [comment]
No response. Closing...
