### ISSUE TITLE
How this can be migrated to granite UI component ? Are you thinking of adding this for touch ui ? 

### ISSUE THREAD

**Issue by kunalgaba** [Adobe-Consulting-Services/acs-aem-commons#490]

**Comment by justinedelson** [comment]
Can you be more specific?

**Comment by kunalgaba** [comment]
We want drag and drop feature in the new Granite Touch UI of AEM. The OOTB UI component - /libs/granite/ui/components/foundation/form/pathbrowser does not support drag and drop. Is there any plan to add this either in the product or is consulting team working on it.

**Comment by justinedelson** [comment]
If you are making a feature request or bug report on the product, please use DayCare (Adobe Support).
