### ISSUE TITLE
weird leftovers (?) with wcm views

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#492]
@davidjgonzalez can you take a look at these two things:

1) https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/widgets/add-ons/wcm-views/.content.xml seems to have the same category twice
2) https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/widgets/js.txt has wcm-views.js listed, but AFAICT, that isn't in that folder anymore.

**Comment by davidjgonzalez** [comment]
@justinedelson thanks for the catches; fixed #2 

#1 I accidentally missed the 's' on acs-commons, so i added the properly named category but left the misspelled for backwards compatibility - happy to remove it. WDYT?

**Comment by justinedelson** [comment]
Ah OK. I missed the fact that the s was missing in the second category. No biggie, let's leave it.

**Comment by justinedelson** [comment]
Thanks for fixing.
