### ISSUE TITLE
Unable to install on publish server

### ISSUE THREAD

**Issue by jtriemstra** [Adobe-Consulting-Services/acs-aem-commons#494]
I posted on the Adobe forums earlier - when I install the ACS Commons package on our 6.1 author server, it works fine. When I install on the publish server, the ACS Commons bundle doesn't activate. When I attempt to manually activate, I get this error

*ERROR* [qtp2146598994-630] org.apache.felix.http.jetty %bundles.pluginTitle: Cannot start (org.osgi.framework.BundleException: Unresolved constraint in bundle com.adobe.acs.acs-aem-commons-bundle [445]: Unable to resolve 445.0: missing requirement [445.0] osgi.wiring.package; (&(osgi.wiring.package=org.scribe.builder.api)(version>=1.3.0)(!(version>=2.0.0))))
org.osgi.framework.BundleException: Unresolved constraint in bundle com.adobe.acs.acs-aem-commons-bundle [445]: Unable to resolve 445.0: missing requirement [445.0] osgi.wiring.package; (&(osgi.wiring.package=org.scribe.builder.api)(version>=1.3.0)(!(version>=2.0.0)))

But as far as I can tell, the relevant bundle exists on both author and publish. Per the forum thread, I'm attaching my configuration status from the publish server.

Thanks

**Comment by justinedelson** [comment]
I don't see the attachment.

**Comment by jtriemstra** [comment]
Sorry - just got the zip pulled down, but...not actually seeing a way to add a non-image attachment to the issue.

**Comment by justinedelson** [comment]
Right, you need to put the ZIP file somewhere and then link to it. Sorry, I always forget this limitation of GitHub. You can use Creative Cloud Files, Dropbox, etc.

**Comment by jtriemstra** [comment]
OK, this should do it https://vml.sharefile.com/d-s29ccd389b1b422a9

Thanks

**Comment by justinedelson** [comment]
Sorry, this is *just* the OSGi Configuration data. I need the full configuration status ZIP.

**Comment by jtriemstra** [comment]
Would it be alright if I email you a link to that? I'd feel better if I could anonymize some of this for a publicly posted link, and looks like there's a fair amount of updates I'd have to make.

**Comment by justinedelson** [comment]
This is an open source project and communication should be done in the open so that a record is kept for other users. If you want to provide just the bundle status, that's probably a good enough start.

**Comment by jtriemstra** [comment]
OK, thanks. Most of the ZIP is intact - I removed a handful of files. https://vml.sharefile.com/d-s5d6eadd1d0343cca

**Comment by justinedelson** [comment]
Thanks for posting that. If I gave you a test build, could you install it and see if the error still surfaces?

**Comment by jtriemstra** [comment]
Yeah, that should work

**Comment by justinedelson** [comment]
OK. Please give one of these a shot: https://files.acrobat.com/a/preview/9522dcf2-063d-4521-b89b-9d0355c22041

**Comment by jtriemstra** [comment]
I think that did it - thanks. The non "min" version had a similar error b/c I don't have the bundle for the Twitter dependency installed (and I don't need it anyway), but the "min" version seems to be working well. Is this something that would get included with a future release of the library?

**Comment by justinedelson** [comment]
I'll try to cut a 1.10.4 today or tomorrow with this fix in it. It might take a few days to get fully promoted.

**Comment by justinedelson** [comment]
1.10.4 is available from https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases/tag/acs-aem-commons-1.10.4. Will be up on repo.adobe.com in a day or two.
