### ISSUE TITLE
add nameHints for factory components

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#495]
https://issues.apache.org/jira/browse/FELIX-4710 added a nice capability to provide a "name hint" for factory configurations rather than displaying the PID. This capability is availble in 6.1, but is backwards compatible (it's just ignored on 6.0).

We should take advantage of this in at least the Named Image Transform Factory and the Oak Ensure Index as those already have logical names.

**Comment by bstopp** [comment]
Like this?

![image](https://cloud.githubusercontent.com/assets/6520270/10717515/b1c27fea-7b28-11e5-831f-d5cb1f8f7809.png)

**Comment by justinedelson** [comment]
Exactly
