### ISSUE TITLE
maxItems not working for multifield

### ISSUE THREAD

**Issue by saulovenancio** [Adobe-Consulting-Services/acs-aem-commons#499]
Hi Guys, 
I saw that there is a bug in this line of add_multifield_limit.js

            if (this.maxItems && (this.maxItems === this.getActualItemCount())) {

The comparison runs two different types so this never gets true.
A simple fix is to do 

if (this.maxItems && (this.maxItems == this.getActualItemCount())) {

that wont check the type.
The way it is implemented today is not working. 

Should i open a pull request and implement it?
Thanks.

**Comment by justinedelson** [comment]
Aren't maxItems and getActualItemCount() both numbers?

**Comment by justinedelson** [comment]
According to @amclin, #555 fixed this.

**Comment by amclin** [comment]
To be clear, #555 would prevent the resulting form from being submitted, but I am unsure as to whether the check here that blocks an author from adding to many multifield entries would actually work or not.

**Comment by amclin** [comment]
@saulovenancio is correct typeof(this.maxItems) is string whereas typeof(this.getActualItemCount()) is number. So the types never match the test never works.
