### ISSUE TITLE
Synthetic Workflow - Workflow Model Support

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#500]
Synthetic Workflow (as it currently exists) requires programmatic enumeration of the Workflow Process steps to execute.

It would be convenient if AEM Workflow Models (that only use a limited set of functionality; Process steps only and serial execution/no decision trees) could be used as the WF Process exception; effectively the same role they play in the content of non-Synthetic WF.

For instance, having the ability to execute the DAM Update Asset WF Model against a set of Assets without duplicating the Process List (and parameters) makes Synthetic Workflow significantly more accessible.

Please note; As always; users of Synthetic WF must full vet that their Models/Workflow Process steps do not leverage unsupported (by Synthetic WF) Workflow functionality.

```
<%@include file="/libs/foundation/global.jsp"%><%
%><%@page session="false" contentType="text/html; charset=utf-8" 
	pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.*,
    java.util.*,
    javax.jcr.*,
    com.adobe.acs.commons.workflow.synthetic.*,
    com.day.cq.dam.commons.util.DamUtil,
    com.day.cq.wcm.api.*,
    com.day.cq.dam.api.*"%><%

    /* Get Synthetic Workflow Runner service */
    SyntheticWorkflowRunner swr = sling.getService(SyntheticWorkflowRunner.class);   
    SyntheticWorkflowModel model = swr.getSyntheticWorkflowModel(resourceResolver,
                                        "/etc/workflow/models/dam/update_asset",
                                        true);
    
    /* Collect the Resource to execute the Workflow against */
    String rootPath = "/content/dam/synthetic-workflow";
    Resource root = resourceResolver.getResource(rootPath);
    int count = 0;
    for(Resource r : root.getChildren()) {
        if(DamUtil.resolveToAsset(r) == null) { continue; }

        boolean saveAfterEachWFProcess = false;
        boolean saveAtEndOfAllWFProcesses = false;
        
        swr.execute(resourceResolver, 
            r.getPath(), 
            model,
            saveAfterEachWFProcess, 
            saveAtEndOfAllWFProcesses);

        if(++count % 1000 == 0) {
        	// Save in batches of 1000; How data is saved should be driven by the use case.
        	resourceResolver.commit();
        }	
    }
    
    // Final save to catch stragglers
    resourceResolver.commit();

%>
```

Current impl at: https://github.com/davidjgonzalez/acs-aem-commons/tree/feature/synthetic-wf-model-support

Seems to work well; need to cleanup and test corner cases.

**Comment by davidjgonzalez** [comment]
@andrewmkhoury welcome any thoughts/feedback

**Comment by justinedelson** [comment]
this is done, right?

**Comment by davidjgonzalez** [comment]
Yup
