### ISSUE TITLE
Add source.jar for acs-aem-commons-bundle to https://repo.adobe.com/nexus/

### ISSUE THREAD

**Issue by paul-bjorkstrand** [Adobe-Consulting-Services/acs-aem-commons#505]
It would help with debugging (in IDE) and when looking for examples of implemented functionality, without the need to have the project cloned/checked out in IDE.

**Comment by justinedelson** [comment]
You can do this by using our BinTray repo directly: https://bintray.com/acs/releases

**Comment by paul-bjorkstrand** [comment]
Thanks for the quick reply, we will be doing that, but it would still be nice to have this mirrored on the adobe repo, since I think a lot of people just use the adobe repo.

**Comment by justinedelson** [comment]
Agreed, just wanted to make sure you were aware of the option.

**Comment by justinedelson** [comment]
Unfortunately, this isn't something we can handle on repo.adobe.com. There are restrictions on serving sources artifacts from there, even for open source projects like ACS AEM Commons.
