### ISSUE TITLE
ACS Commons 2.0.0 - AEM6-only Support

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#512]
@justinedelson the move to AEM6-only support is a big milestone; thoughts around messaging?

Was talking w @andrewmkhoury around the proliferation of ACS Commons use in the wild and his gut reaction was that of alarm (if i read him correctly ;)) -- might be interesting to get his perspective.

Threw this together; might be too obnoxious though.. 

![commons200](https://cloud.githubusercontent.com/assets/1451868/9429158/0d81b7f8-4995-11e5-99be-a63cbf0e4dc4.png)

**Comment by justinedelson** [comment]
FWIW, I'm fine with being this obnoxious between 2.0 and 2.1.

In addition, I have publicly announced this on the AEM Podcast, will do so again this week in my CQ Gems session and we should both send tweets out on Monday or Tuesday.

**Comment by justinedelson** [comment]
So far, my tweet this morning has been seen by 320+ people. I'd say that is a good start.

**Comment by davidjgonzalez** [comment]
@justinedelson not bad; site gets ~4k uniques a month.

Btw - i pushed the yellow banner to the acs-aem-commons-2.0.0 jekyll branch; feel free to finesse the text. Currently reads: ACS AEM Commons 2.0 requires AEM 6+
