### ISSUE TITLE
Feature Review: SVG Component

### ISSUE THREAD

**Issue by auniverseaway** [Adobe-Consulting-Services/acs-aem-commons#513]
I would like to contribute my OS SVG component to ACS commons. I was waiting for 6.1 to implement SVG, but they're still not implemented quite right. You can view the source [here](https://github.com/auniverseaway/svg-sightly).

**Comment by justinedelson** [comment]
Is there any way to avoid context=unsafe here? Or is there a way to validate the SVG in some way before outputting it?

**Comment by auniverseaway** [comment]
Unfortunately, there currently isn't a way to detect an XML context in [Sightly](https://github.com/Adobe-Marketing-Cloud/sightly-spec/blob/master/SPECIFICATION.md#121-display-context). I could probably validate the xml using a Java class, but was trying to avoid something so heavy handed. It's not ideal, but we could also remove the whole notion of inline SVG completely.
