### ISSUE TITLE
Version Comparison tool not displaying any results

### ISSUE THREAD

**Issue by Karthhik** [Adobe-Consulting-Services/acs-aem-commons#517]
I created some versions for a page and trying to use version comparison tool, there is no output on to the page. In the logs, the following warning is there
 *WARN* [127.0.0.1 [1440778893134] GET /etc/acs-commons/version-compare.html HTTP/1.1] org.apache.sling.models.impl.ModelAdapterFactory Required properties [private org.apache.sling.api.resource.ResourceResolver com.adobe.acs.commons.version.model.EvolutionModel.resolver] on model class class com.adobe.acs.commons.version.model.EvolutionModel were not able to be injected.

I am not sure whether it is a bug or i am missing anything?

**Comment by steffenrosi** [comment]
Hi @Karthhik,

which version of sling models are you using? Try to use the latest which you can get from:

http://apache.mirrors.lucidnetworks.net//sling/org.apache.sling.models.api-1.2.0.jar
http://apache.mirrors.lucidnetworks.net//sling/org.apache.sling.models.impl-1.2.0.jar

Best Regards,
Steffen

**Comment by Karthhik** [comment]
That worked.Thanks for your help.

**Comment by justinedelson** [comment]
@steffenrosi - do we need to add a note to the docs? I assume this is only an issue on 6.0

**Comment by steffenrosi** [comment]
@justinedelson - yes, I will add this to the docs section.
