### ISSUE TITLE
Version Replicator

### ISSUE THREAD

**Issue by Adolfff** [Adobe-Consulting-Services/acs-aem-commons#518]
Dear ACS Commons Engineers,

Would it be possible to obtain some tips on how to use the Version Replicator Tool?. Created an agent to replicate versions to another instance, log just says:

28.08.2015 12:10:50 - INFO - publish : Agent updated. State is enabled and valid
28.08.2015 12:10:50 - INFO - publish : Agent started.

Nothing seems to have happened in the target instance.

I can't thank you enough for your prompt response, you guys are awesome.

**Comment by Karthhik** [comment]
I am also having the same issue. Couldn't find the actual use of version replicator. I tried it once but it wiped out all the versions of my page in other instance. 

Should we use only default agent or any other agents in particular

**Comment by justinedelson** [comment]
You can use whichever agent you want.

**Comment by justinedelson** [comment]
Replication in general will replace all the versions on the target instance. This feature is not intended to replicate version history, but rather to replicate a particular past version of a node. When replicated, it will become the "current" version on the target instance.

**Comment by justinedelson** [comment]
There's already an issue opened to document this feature. See #90.
