### ISSUE TITLE
Version Replicator - Take II

### ISSUE THREAD

**Issue by sdelcast** [Adobe-Consulting-Services/acs-aem-commons#521]
So after playing with it a bit more I got the replicator to do its thing, however, we have a problem.  Once the replicator sends the versions to the Target instance, all versions that existed previously, get deleted.  In other words, it wipes out the target instance versions.  

Many thanks for your guidance on this, big fan of your work.

**Comment by justinedelson** [comment]
This is an attribute of the underlying replication subsystem, specifically the DurboImporter.

**Comment by sdelcast** [comment]
Hi Justin, thank you very much for your prompt response.  Can you please elaborate a bit more, just want to make sure I fully understand....

Again, thank you very much indeed.

**Comment by justinedelson** [comment]
All the Version Replicator does is call the standard Replication API (https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/replication/impl/ReplicateVersionImpl.java#L143). It has no control over what happens on the receiving end. That behavior is defined by the existing replication subsystem.
