### ISSUE TITLE
Maven way of installing the acs commons doesn't work

### ISSUE THREAD

**Issue by kdesineedi** [Adobe-Consulting-Services/acs-aem-commons#524]
Hi,

I have followed the steps outlined in http://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html.I am unable to get the acs package generated.

Please note I am using only the error page handling part of the acs commons functionality where I created only a few JSPs pages needed per the usage video.It works well if I install it  manually but I wanted to integrate it into our build process so tried to follow the above without any luck.

Versions used:

AEM : 6.0 SP2
Java : 1.8
Maven :3.2.1

**Comment by justinedelson** [comment]
Does the ACS AEM Commons package get included in your content package? Can you post your pom.xml file?

**Comment by justinedelson** [comment]
How about posting the output of running Maven?

**Comment by kdesineedi** [comment]
@justinedelson : Thanks for the quick response.
No it does not get included.

Posting the build output:

[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building projectName Content Only 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ projectName-content-only ---
[INFO] Deleting F:\projectName\GitCode\parentProjectName\projectName\projectName-content-only\target
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ projectName-content-only ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources to META-INF
[INFO] Copying 7 resources to jcr_root
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ projectName-content-only ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ projectName-content-only ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory F:\projectName\GitCode\parentProjectName\projectName\projectName-content-only\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ projectName-content-only ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ projectName-content-only ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-vault-plugin:0.0.10:package (default-package) @ projectName-content-only ---
[INFO] Building jar: F:\projectName\GitCode\parentProjectName\projectName\projectName-content-only\target\projectName-content-only-0.0.1-SNAPSHOT.zip
[INFO] 
[INFO] --- maven-vault-plugin:0.0.10:package (default) @ projectName-content-only ---
[INFO] Building jar: F:\projectName\GitCode\parentProjectName\projectName\projectName-content-only\target\projectName-content-only-0.0.1-SNAPSHOT.zip
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ projectName-content-only ---
[INFO] Installing F:\projectName\GitCode\parentProjectName\projectName\projectName-content-only\target\projectName-content-only-0.0.1-SNAPSHOT.zip to F:\MavenRepos\com\projectName\projectName-content-only\0.0.1-SNAPSHOT\projectName-content-only-0.0.1-SNAPSHOT.zip
[INFO] Installing F:\projectName\GitCode\parentProjectName\projectName\projectName-content-only\pom.xml to F:\MavenRepos\com\projectName\projectName-content-only\0.0.1-SNAPSHOT\projectName-content-only-0.0.1-SNAPSHOT.pom
[INFO] 
[INFO] --- maven-sling-plugin:2.1.0:install (install-bundle) @ projectName-content-only ---
[INFO] F:\projectName\GitCode\parentProjectName\projectName\projectName-content-only\target\projectName-content-only-0.0.1-SNAPSHOT.jar is not an OSGi Bundle, not uploading
[INFO] 
[INFO] --- maven-vault-plugin:0.0.10:install (install-package) @ projectName-content-only ---
[INFO] Installing projectName-content-only (F:\projectName\GitCode\parentProjectName\projectName\projectName-content-only\target\projectName-content-only-0.0.1-SNAPSHOT.zip) to http://localhost:4502/crx/packmgr/service.jsp
[INFO] projectName-content-only, 0.0.1-SNAPSHOT (16862 bytes)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.262 s
[INFO] Finished at: 2015-09-02T15:55:21-05:00
[INFO] Final Memory: 13M/150M
[INFO] ------------------------------------------------------------------------

**Comment by kdesineedi** [comment]
it doesn't seem to recognize anything related to ACS

**Comment by justinedelson** [comment]
It appears you are using the maven-vault-plugin. Our documentation only documents usage with the content-package-maven-plugin. I wouldn't expect that to work with the maven-vault-plugin.

**Comment by kdesineedi** [comment]
Thanks @justinedelson.There was a wrong profile configured due to which this vault plugin was invoked and overriding content-package plugin.Now I see the acs bundle getting installed.
