### ISSUE TITLE
Named Transform Image Servlet producing blurry results

### ISSUE THREAD

**Issue by dterner** [Adobe-Consulting-Services/acs-aem-commons#525]
I have recently made use of the Named Transform Image Servlet. 

When using crop the resulting image appears blurred as if scaled up form a lower resolution even starting with a high quality image and going down in size. 

The scaling appears to work well, but the cropping produces a heavily blurred result.

**Comment by davidjgonzalez** [comment]
@dterner can you provide the original image and the transform params you are using in this issue?

**Comment by davidjgonzalez** [comment]
@dterner bump

**Comment by davidjgonzalez** [comment]
@dterner double bump
