### ISSUE TITLE
Error Page Handler not resolving the correct "Page" resource

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#526]
* Requesting a page and on the head.jsp throw a slingResponse.sendError(500)
* When it reaches ACS default.jsp, the current resource becomes jcr:content and it is existent so the resulting page for 500 response comes out to be null
* in this case the request URL is still page.html but but it does not go to the 500 page

**Comment by davidjgonzalez** [comment]
@apoorv81 please feel free to add/color details to the issue

**Comment by apoorv81** [comment]
Thanks @davidjgonzalez 

The use case is as follows

**Content Structure**
* Home Page - /content/my-site/index
* Errors Page - /content/my-site/errors
* 500 Page - /content/my-site/errors/500

Home page is setup to have `errorPages="/content/my-site/errors"`

**Steps**
* User requests /content/my-site/index.html.
* The head.jsp breaks and results in 500 error.

**Expected**: User is shown the 500 page in disabled or publish mode.
**Actual**: The error handler is not able to find the errors page and thus does not show the intended 500 page.

**Some analysis that may help**
When the control reaches ACS Commons `default.jsp` it tries to find the error page for the "current resource". In this use case it is `jcr:content` of the index.html. 

It uses `ErrorPageHandlerImpl.findErrorPage` method.

At line 269 in `ErrorPageHandlerImpl`, code uses `findFirstRealParentOrSelf` method which results in returning `jcr:content`.
At line 272 the `pageContentResource` becomes `null` as the code is assuming the parent to be a page and thus tries to find`jcr:content` below it.

This is then returned back and thus 500 page is not shown. 

**Possible Resolution**
Before trying to find the errorPages check if the parent resource is not a page and then find containingPage. Use the containing page to do the same logic as currently is.

I hope this helps.

ta,
Apoorv

**Comment by davidjgonzalez** [comment]
Perfect! i wish all GH issues were as thorough as this :)

**Comment by ajaykpaul** [comment]
seems, issue not resolved with the release 2.0.2 yet. I am getting the following error:
it still not able to find the 500 page.

**Comment by ajaykpaul** [comment]
following is the configuration I used:
src\main\content\jcr_root\apps\dhl\config.author/com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl.xml.xml

<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="sling:OsgiConfig"
    enabled="{Boolean}true"
    cache.serve-authenticated="{Boolean}true"
    error-page.fallback-name="500"
    cache.ttl="{Long}300"
    error-page.system-path="/content/dhl/master/en/home/error/500"
    paths="/content/dhl/master/en/home/error"/>

**Comment by jochen314** [comment]
For me, #1490 works
