### ISSUE TITLE
title attribute with the cqinclude namespace

### ISSUE THREAD

**Issue by jtriemstra** [Adobe-Consulting-Services/acs-aem-commons#527]
The documentation for the namespace functionality of the cqinclude xtype shows a title attribute. However, that doesn't appear to be having any effect in my dialogs. If the source tab of the cqinclude specifies a title, that title is used, and if the source tab does not specify a title, no title appears.

**Comment by davidjgonzalez** [comment]
@jtriemstra you are correct; that is a typo in the docs.

```
        <title-tab
		jcr:primaryType="cq:Widget"
		title="Title Tab"
		path="/apps/demo/components/title/dialog/tab.cqinclude.namespace.title.json"
		xtype="cqinclude"/>
```

should be 

```
        <title-tab
		jcr:primaryType="cq:Widget"
		path="/apps/demo/components/title/dialog/tab.cqinclude.namespace.title.json"
		xtype="cqinclude"/>
```

This really piggybacks the functionality of the normal cqinclude
