### ISSUE TITLE
XSS Taglib getValidHref(..) does not support paths with spaces

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#530]
@justinedelson See any problems if we update:

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/1cbfc7f9e4688eebd3e9941dabe3260d773cb355/bundle/src/main/java/com/adobe/acs/commons/xss/XSSFunctions.java#L108

to use the `xssAPI.getValidHref(..)`  since ACS AEM Commons 2+ no longer supports 5.6.1?

**Comment by justinedelson** [comment]
good call. fixed

**Comment by sabyamon** [comment]
Hi @justinedelson @davidjgonzalez Any approx date when 2.1.0 will be released ?

**Comment by justinedelson** [comment]
2.1.0 is probably a bit off. I'll cut a 2.0.2 with this fix in it now. Will hopefully be up on repo.adobe.com on Monday.

**Comment by sabyamon** [comment]
Awesome :) .. Thanks @justinedelson /cc @dchang @SachinMali
