### ISSUE TITLE
Left Nav/Breadcrumb Components are not appearing in Publish Instance

### ISSUE THREAD

**Issue by manish-strut** [Adobe-Consulting-Services/acs-aem-commons#534]
Hi,

For Breadcrumb and Left Nav components we do not have authoring dialogs. They get rendered based on the child nodes. In author they all appear fine, but when the pages get deployed to publish, both the components disappear.

If I create a node for any of the missing component under the "jcr:content" node of page, the component gets displayed.

Has anyone faced similar issue?

Any pointers will be appreciated.

Regards,
MJ

**Comment by davidjgonzalez** [comment]
@manish-strut How does this question relate to ACS Commons?

**Comment by justinedelson** [comment]
Not sure I understand - which components in ACS AEM Commons are you referring to?
