### ISSUE TITLE
Filter rules being created by the Authorizable Packager should not include .tokens subnode

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#538]
Since the .tokens subnode is only a temporary folder which tracks the currently active user sessions of a specific user it should never be included in any authorizable package. Please always exclude the ".tokens" subfolder automatically from those packages.

**Comment by davidjgonzalez** [comment]
This code could be used to achieve this; https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/packaging/impl/ACLPackagerServletImpl.java#L307

(ACL Package Manager does this when it includes Principals; IIRC Oak will prevent package installation is tokens exist - or at least used to which is how/why this fix was originally added)
