### ISSUE TITLE
Configuration help needed

### ISSUE THREAD

**Issue by kdesineedi** [Adobe-Consulting-Services/acs-aem-commons#545]
Hi,
I am using the ACS commons error handler and it is behaving as expected for 404 pages under /content/myAppName/ because the error pages path is defined at the root node.However when the request goes to any page like the below pattern(s) apart from the /content/myAppName structure:
/content/non-existent-page.html
/content/geometrixx/non-existent-page.html

I am getting the below error in the logs:
ACS AEM Commons Error Page Handler is enabled but mis-configured. A valid error image handler nor a valid error page could be found.;

Is there any configuration I can do to disable ACS error handler for all other content path hierarchies except for my app specific content paths?

**Comment by davidjgonzalez** [comment]
@kdesineedi If you dont set a system path, then sling's default.jsp is used. You will see a warn that says `ACS AEM Commons Error Page Handler is enabled but mis-configured. A valid error image handler nor a valid error page could be found.` but you can ignore this - it isnt hurting anything.

What exactly are you trying to do? Why not just have a system error pages?

**Comment by kdesineedi** [comment]
True.I am using the error system path config for the time being.However our logs are getting clogged with this warning message as there was a scheduled service trying to do some checkup activity and it is giving this error message for any non existing page in other apps of the same instance.Wanted to check if apart from setting up system level error pages,is there is a better way?The goal is to not have repeated instances of this message in our logs as mis-configuration.

**Comment by davidjgonzalez** [comment]
@kdesineedi i dont see a problem dropping the log level; would INFO be ok?

**Comment by kdesineedi** [comment]
We are having INFO as our log level in some of the systems so maybe changing the message text might be better in addition to degrading the log level.Basically it is not much of a mis-configuration but something which can be safely ignored.

**Comment by davidjgonzalez** [comment]
switched to debug
