### ISSUE TITLE
cqinclude namespace should affect more properties

### ISSUE THREAD

**Issue by jtriemstra** [Adobe-Consulting-Services/acs-aem-commons#547]
Currently the servlet only modifies properties named "name". In the case of the smartimage widget, and perhaps others, there are multiple properties that have the same behavior as "name" typically does (eg "fileName"), and these should be modified as well.

I think 99% of the time it would be safe to say that any property with a value that starts with "./" should be modified. I could also see implementing this as an OsgiConfig property so a list of property names could be configured, if the first idea seems too broad.

**Comment by davidjgonzalez** [comment]
@jtriemstra please check out #560 and let me know your thoughts
