### ISSUE TITLE
Error Page Handler not work with Resource Resolver URL Mapping

### ISSUE THREAD

**Issue by victole** [Adobe-Consulting-Services/acs-aem-commons#562]
The issue we have is when implemented URL shortening on the publisher with "/content/xyz/:/" the error handling quit working. With the full/long url it works well.
Related comments:
http://adobe-consulting-services.github.io/acs-aem-commons/features/errorpagehandler.html#comment-2319750347 and http://adobe-consulting-services.github.io/acs-aem-commons/features/errorpagehandler.html#comment-2176369848

**Comment by davidjgonzalez** [comment]
@victole Few items
* What version of ACS AEM Commons?
* What version of AEM?
* How are you shorting your URLs (/etc/maps vs jcr resource resolver factory incoming/outgoing map)

**Comment by davidjgonzalez** [comment]
Thinking about this ... youre using /etc/map arent you? meaning the URI that hits AEM (request.getPathInfo()) is still /notFound.html .. so when EPH tries to look up the tree for the first real parent it finds "/" which in the JCR is the Root.

I think we'll need to use `rr.resolve(slingRequest, ..)` to look up the URI path.

@justinedelson can you think of any other gotchas/corner cases/approaches?

**Comment by victole** [comment]
Hi @davidjgonzalez 
1) What version of ACS AEM Commons?
    1.9.6
2) What version of AEM?
    6.0.0 SP2
3) How are you shorting your URLs (/etc/maps vs jcr resource resolver factory incoming/outgoing map)
i'm using the JcrResourceResolverFactory and my configuration is 

resource.resolver.searchpath="[/apps,/libs,/apps/foundation/components/primary,/libs/foundation/components/primary]"
resource.resolver.mapping="[/:/,/content/:/,/content/dam/:/,/content/home/:/,/content/home/en/:/]"

and i have /etc/map by default without modifications

**Comment by davidjgonzalez** [comment]
Thanks; bi-directional mapping; should result in ~same effect as above since you arent prepending your /content/home prefix at httpd

**Comment by victole** [comment]
Thanks! do you says that i need to remove /:/ ?

**Comment by davidjgonzalez** [comment]
@victole i think we need an update of the EPH code :T ..   i was sort of talking to myself on that last comment :)

**Comment by victole** [comment]
great! Do you know how long might be the fix?
And thanks very much for you work!! and the quick response

**Comment by davidjgonzalez** [comment]
@victole went back and looked at the code; i believe this is resolved in the latest build as a side effect of a different fix. The finding of the first real parent now uses `rr.resolve(request, ...)` which should allow 

`/` to be resolved to `/content/home/en`

Previously it used `rr.getResource(path)` which doesnt take into account the mapping.

Can you try w ACS Commons 2.0.8 and let me know if it fixes the issue?

Thanks

**Comment by victole** [comment]
Hi @davidjgonzalez. i changed my pom configuration with:
ui project:
`<dependency>
	<groupId>com.adobe.acs</groupId>
	<artifactId>acs-aem-commons-content</artifactId>
	<version>2.0.8</version>
	<type>content-package</type>
</dependency>`

bundle project:
`<dependency>
        <groupId>com.adobe.acs</groupId> 
        <artifactId>acs-aem-commons-bundle</artifactId>
	<version>2.0.8</version>
	<scope>provided</scope>
</dependency>`

then i deleted my /apps/acs-commons package to re create it with the maven installing process.

Now i getting always the default error page (with the short and long url)

### Error message:

No resource found
RequestURI=/test/about2.html
Servlet= /apps/sling/servlet/errorhandler/404.jsp

No resource found
RequestURI=/content/home/en/test/about2.html
Servlet= /apps/sling/servlet/errorhandler/404.jsp


![error](https://cloud.githubusercontent.com/assets/2567323/10731958/8e97003c-7bd6-11e5-84a2-7faeb01b2a48.png)


### My /apps/sling/servlet/errorhandler/404.jsp has
`<%@page session="false"%><%
%><%@include file="/apps/acs-commons/components/utilities/errorpagehandler/404.jsp" %>`

**Comment by victole** [comment]
hi @davidjgonzalez, i think that is working!!
I was having an default error, but i deleted all /apps/sling node into the jcr, and then it starts working

**Comment by davidjgonzalez** [comment]
@victole thanks for confirming!!

Ill close this issue - if you run into anything else, please re-open or make a new issue!

**Comment by victole** [comment]
@davidjgonzalez thank you very much!

**Comment by dipankarhcl** [comment]
I am facing the same issue on AEM 6.3 and ACS version 3.13.0 and ACS 3.10.0
It works fine on AEM 6.1 and ACS 2.3.0
Can you please help ?

**Comment by davidjgonzalez** [comment]
Can you turn debug on the erropagehandler impl and post the resulting logs?

**Comment by dipankarhcl** [comment]
Below are the trace logs. "/content/us/en-us" has the error path configured and the error page works fine if requested page has "/content" in it. Thanks.

15.01.2018 01:36:37.495 *DEBUG* [0:0:0:0:0:0:0:1 [1515960397103] GET /us/en-us/tll1.html HTTP/1.1] com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl Not Found Behavior: respond-with-404
15.01.2018 01:36:37.495 *DEBUG* [0:0:0:0:0:0:0:1 [1515960397103] GET /us/en-us/tll1.html HTTP/1.1] com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl Path did NOT match exclusions for "respond w/ 404" ~> "respond w/ 404"
15.01.2018 01:36:37.496 *DEBUG* [0:0:0:0:0:0:0:1 [1515960397103] GET /us/en-us/tll1.html HTTP/1.1] com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl 
--------------------------------------------------------------------------------
ACS AEM Commons - Error Page Handler 404 Handling
================================================================================
Status code: 404
Is anonymous: false
Is browser request: true
Is redirect to login page: false
Default 404 Behavior: respond-with-404
--------------------------------------------------------------------------------

15.01.2018 01:36:37.496 *DEBUG* [0:0:0:0:0:0:0:1 [1515960397103] GET /us/en-us/tll1.html HTTP/1.1] com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl Allow error page handler to handle request
15.01.2018 01:36:37.496 *TRACE* [0:0:0:0:0:0:0:1 [1515960397103] GET /us/en-us/tll1.html HTTP/1.1] com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl Finding first real parent for [ /us/en-us/tll1.html ]
15.01.2018 01:36:37.497 *DEBUG* [0:0:0:0:0:0:0:1 [1515960397103] GET /us/en-us/tll1.html HTTP/1.1] com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl **Found real aggregate resource via getParent() at [ /us/en-us ]**
15.01.2018 01:36:37.497 *TRACE* [0:0:0:0:0:0:0:1 [1515960397103] GET /us/en-us/tll1.html HTTP/1.1] com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl **Found real resource at [ /us/en-us ]**
15.01.2018 01:36:37.498 *TRACE* [0:0:0:0:0:0:0:1 [1515960397103] GET /us/en-us/tll1.html HTTP/1.1] com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl **could not find inherited property for [ NonExistingResource, path=/us/en-us/tll1.html ]**
15.01.2018 01:36:37.498 *DEBUG* [0:0:0:0:0:0:0:1 [1515960397103] GET /us/en-us/tll1.html HTTP/1.1] com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl **Best matching errors path for request is: null**
15.01.2018 01:36:37.498 *TRACE* [0:0:0:0:0:0:0:1 [1515960397103] GET /us/en-us/tll1.html HTTP/1.1] com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl no custom error page could be found
15.01.2018 01:36:37.498 *DEBUG* [0:0:0:0:0:0:0:1 [1515960397103] GET /us/en-us/tll1.html HTTP/1.1] com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl ACS AEM Commons Error Page Handler is enabled but mis-configured. A valid error image handler nor a valid error page could be found.

**Comment by davidjgonzalez** [comment]
Based on the logs it doesn’t appear you’re providing an errorPages property on that content tree.

**Comment by dipankarhcl** [comment]
We have. Here is the screenshot. More over it works when error pages has "/content" present in URL.
![image](https://user-images.githubusercontent.com/25001102/34991122-7424bff2-faee-11e7-80c2-eb10e1154c71.png)

**Comment by davidjgonzalez** [comment]
@dipankarhcl ah right - my brain pre-pended /content to you logs. 
.. ooh, i think HierarchyNodeInheritanceValueMap doesn't support non-real paths for resources... so it doesnt know how to look-up the resolved resource with path: /us/en-us  (since it uses `rr.getResource(..path..)` which of course `rr.getResource(/us/en-us) => null`.

You could log a bug w Adobe Support asking them to fix HierarchyNodeInheritanceValueMap.  

Alternatively we'd have to write out own HierarchyNodeInheritanceValueMap to use in this class.

Or, you could pre-pend /content on at httpd, which is what everyone else does, and have the mapping that removed /content be one-way (on `rr.map(..)`)

**Comment by dipankarhcl** [comment]
Thanks @davidjgonzalez
