### ISSUE TITLE
system-notifications/notification/clientlibs.js is also referenced in Publish mode

### ISSUE THREAD

**Issue by andre-inside** [Adobe-Consulting-Services/acs-aem-commons#579]
We installed the latest release of AEM commons 2.1.0 on our instances. Unfortunalty we got a "Failed to load resource: the server responded with a status of 404 (Not Found)" for the script "apps/acs-commons/components/utilities/system-notifications/notification/clientlibs.js" for requests over dispatcher (as normally /apps is restricted) to our publish instance. This shouldn't be included on publish instances, as this is only a author feature (and if, only over /etc).

**Comment by davidjgonzalez** [comment]
Agreed.

Can you disable the component on publish for now, manually or via: http://adobe-consulting-services.github.io/acs-aem-commons/features/osgi-disabler.html 

Will update to only enable on Author

**Comment by davidjgonzalez** [comment]
Fixed in v2.1.2 (released today)
