### ISSUE TITLE
Workflow Remover needs a stop mechanism

### ISSUE THREAD

**Issue by thedoc31** [Adobe-Consulting-Services/acs-aem-commons#582]
Using the "Workflow n Audit purge" package located at https://helpx.adobe.com/experience-manager/kb/howtopurgewf.html, an admin is able to stop the Workflow removal by deleting the cleanWorkflow.now file.  AEM Commons should provide a similar mechanism. Some processes should not be run during business hours, and if the client has a purge running all night long and into the morning (which does happen), there needs to be a way to short-circuit it and stop at a certain time.  In addition to the cron, there should be an "allow to run" window which automatically stops the maintenance after a certain amount of time.  There should also be an emergency kill button added to the UI just in case an admin needs to stop the job from running RIGHT NOW.

**Comment by davidjgonzalez** [comment]
@thedoc31 on the WebUI there is a "Force Quit" button that shows when Workflow Remover is executing. Is this not sufficient?

Btw - can you describe your situation where this runs for hours?  IME this runs very quickly due to the tree walking approach even on 10k's of wf instances.

**Comment by thedoc31** [comment]
Unfortunately not – for several Adobe Managed Services clients, I have seen the built-in workflow removal cronjob take several hours to complete on an Author. One of my clients in particular does a lot of batch uploads to their DAM, but every uploaded item goes through a workflow to be approved by a human.  This means thousands of workflows sitting there waiting to complete, and when they do approve items, they complete large batches at once.  This causes a massive number of completed workflows to be purged at once and long-running maintenance which spills over into business hours and causes slowness on the system.

Unfortunately the built-in AEM workflow purge scheduler doesn’t have any way to abort or stop the cronjob once it’s started, so for my client to consider a different solution using acs-commons I believe there should be a defined maintenance window for a job – a set start and stop time which will guarantee that the purge can’t start prior to or run past a certain time every day.

**Comment by davidjgonzalez** [comment]
@thedoc31 fair enough - strong feelings about force quitting at a specific time vs a duration? Duration (in mins) seems more straight forward and flexible. Trying to specify an end time can get complex - you have to use quartz expressions which are confusing as all gets to me as a user.

Fwiw this should be able to tear through 10k wf in less than an hour easily (if your mongo it might be slower I suppose) but I still see the value in this safe guard. Force quit in web UI provides that kill switch you're looking for in the event it kicks off and you simply don't want it to be running in that moment.

**Comment by thedoc31** [comment]
Not at all, setting a max duration of ‘n’ minutes or hours is definitely easier to understand for an end user than a specific window of time anyway.  The Force Quit in UI is definitely the kill switch they would like to have available. Can I assume that if we terminate the process at max duration that during the next window it would pick up wherever it left off?

**Comment by davidjgonzalez** [comment]
Closed via #586
