### ISSUE TITLE
Bulk Workflow Manager doesn't purge workflows

### ISSUE THREAD

**Issue by marwellazure** [Adobe-Consulting-Services/acs-aem-commons#583]
Hi,
I noticed that when selecting the "Purge workflows" option it does not really purges the workflow. This may happen because in the http request a clearworkflow parameter is sent, but on the other side a purgeworkflow parameter is checked.
Thanks!

**Comment by davidjgonzalez** [comment]
@marwellazure crazy! Thanks for finding and reporting - will fix adapter

**Comment by davidjgonzalez** [comment]
64e34be56974ddd398e94ed90bbaeca53e3bf90e fixes this issue.
