### ISSUE TITLE
EnsureIndex blocks system startup

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#587]
When a synchronous property index is being created with the EnsureOakIndex functionality, the indexing takes place synchronously when persisting the index definition. As this is done during the activation() of the service, this might block the startup of the instance, thus causing large delays.

It would be better if the index creation could be executed in a async thread using the Sling scheduler.

**Comment by davidjgonzalez** [comment]
Fixed via #593
