### ISSUE TITLE
Uses constraint violation on javax.inject when adding guava dep.

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#594]
After adding the following dependency to the acs commons bundle (which is provided by AEM 6.0)

```
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>15.0</version>
            <scope>provided</scope>
        </dependency>
```

The following exception occurs..

```
06.12.2015 17:30:25.363 *ERROR* [qtp1639533583-44] org.apache.felix.http.jetty %bundles.pluginTitle: Cannot start (org.osgi.framework.BundleException: Uses constraint violation. Unable to resolve bundle revision com.adobe.acs.acs-aem-commons-bundle [507.1] because it is exposed to package 'javax.inject' from bundle revisions org.apache.sling.models.api [344.0] and org.apache.sling.scripting.java [215.1] via two dependency chains.

Chain 1:
  com.adobe.acs.acs-aem-commons-bundle [507.1]
    import: (osgi.wiring.package=javax.inject)
     |
    export: osgi.wiring.package=javax.inject
  org.apache.sling.models.api [344.0]

Chain 2:
  com.adobe.acs.acs-aem-commons-bundle [507.1]
    import: (&(osgi.wiring.package=com.google.common.cache)(version>=15.0.0)(!(version>=16.0.0)))
     |
    export: osgi.wiring.package=com.google.common.cache; uses:=javax.inject
  com.google.guava [78.0]
    import: (osgi.wiring.package=javax.inject)
     |
    export: osgi.wiring.package=javax.inject
  org.apache.sling.scripting.java [215.1])
```

I've tried setting Importing-Dependency to !javax.inject, and also the former with embedding javax.inject; in both cases  the ACS Commons EvolutionModel fails to @Inject the proper objects.

@justinedelson, @joerghoh, @chetanmeh  .. Any thoughts how to work around this?

/cc @Sivaramvt

**Comment by justinedelson** [comment]
I've heard that version 1.2.0 of Sling Models fixes this issue. Or at least
one which sounds similar.

**Comment by davidjgonzalez** [comment]
@justinedelson 

Seems the simplest options for this issue..
1) Keep this feature in its own bundle
2) Bump Sling Models dep to 1.2.0 and make optional (assuming 1.2.0 fixes)
 
Regardless it seems like we should make Sling Models 1.1.0+ optional since AEM 6 ships w 1.0.0.

**Comment by justinedelson** [comment]
@davidjgonzalez I had a chance to look into this. I think we should go with option 1 - keep this in a separate bundle. This is less than ideal, but of those two, I think it is the best.

There is another option we can discuss which would to be embed Guava. We haven't done this before, but it might be a good idea in this case. While this may seem counter-intuitive as Guava is included in AEM, Guava has some serious problems with semantic versioning. Essentially they don't do it and every release comes with a new major version bump. There's some internal discussions I can't get into depth here about insulating customers from the usage of Guava in Oak (and AEM more broadly) so as to allow them to deploy their own version.

Assuming that we don't expose Guava interfaces/classes in the API of this new feature (and it actually resolves this issue), I'd like to go down this path.

**Comment by davidjgonzalez** [comment]
@justinedelson  the following seems to work! 

Without the optional sun.misc import due to: `sun.misc -- Cannot be resolved and overwritten by Boot Delegation`

```
<configuration>
  <instructions>
      <Bundle-SymbolicName>com.adobe.acs.acs-aem-commons-bundle</Bundle-SymbolicName>
      <Import-Package>
          sun.misc.*;resolution:=optional,
          com.adobe.cq.dialogconversion;resolution:=optional,
          *
      </Import-Package>
      <Embed-Dependency>guava</Embed-Dependency>
      <Sling-Model-Packages>com.adobe.acs.commons.version.model</Sling-Model-Packages>
  </instructions>
</configuration>
```

![2015-12-10 at 11 34 pm](https://cloud.githubusercontent.com/assets/1451868/11736026/aaf2b364-9f96-11e5-8363-d2d54e32a108.png)

**Comment by Sivaramvt** [comment]
Thanks @justinedelson @davidjgonzalez for the guidance.
