### ISSUE TITLE
Deprecate EnsurePropertyIndex

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#596]
With the EnsureIndex functionality in place I don't see a need for EnsurePropertyIndex any more. We should deprecate it asap (including a warn message when it's used) and then remove it from the codebase.

**Comment by davidjgonzalez** [comment]
agree

**Comment by justinedelson** [comment]
+1

**Comment by davidjgonzalez** [comment]
Closed via #598
