### ISSUE TITLE
AEM environment indicator should be able to embedd system properties into HTML

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#597]
I have a case where I have a large number of environments which makes configuration via OSGI config quite inconvenient. Thus I would like to use variables which are replaced by either system properties or environment variables.
This makes it very convenient to embedd for example the hostname into the indicator.

**Comment by davidjgonzalez** [comment]
@joerghoh WDYT about having the option to point to a JSP, that you have full control of what that JSP renders (conceptually similar to how component error handler works).

Been a while since i looked at the AEM Env Indicator code, but shouldnt be too bad?

**Comment by joerghoh** [comment]
At the moment it is a filter, and is visible in /crx/de, /system/console and other places as well. From my point of view it is hard to move the rendering part into a JSP and would make it much more complicated if we want to stick with the filter approach.

**Comment by joerghoh** [comment]
I would imagine to use a servicetracker and exposing a public interface. Then you can implement your custom logic there, and the default implementation could expose the very same behaviour as we have now. When we use service ranking overlaying it shouldn't be any problem.

**Comment by justinedelson** [comment]
IMHO, we shouldn't over complicate things. Let's just pass the configured value through StrSubstituor

**Comment by davidjgonzalez** [comment]
@joerghoh good point wrt global scope of the filter.

@justinedelson but what will be responsible for building the map StrSubstitutor uses? The template String comes form OSGi config (inner-html), but we need a facility for building the map - which i think what @joerghoh was suggesting via the service tracker.

As an aside, It'd be nice time to align this Filter w the (relatively) new AbstractHTMLInjectorFilter.

**Comment by joerghoh** [comment]
I will give a try with the system properties and check if it's enough. I will raise a new request if it isn't enough. Thanks @justinedelson
