### ISSUE TITLE
Content Finder Query Builder

### ISSUE THREAD

**Issue by anujrattan** [Adobe-Consulting-Services/acs-aem-commons#604]
I was trying to use query builder implementation to fetch data in a custom content finder tab. I tried hitting the url in browser for the query builder servlet as provided in the sample. The result contains only a few fields. But in the dialog of the component there are a lot of fields that we created and are used in the pages. We need all the fields to be fetched by this query builder. If we use traditional query builder there is a base param as: p.hits=full.. if we mention this the query builder provides all the fields in the component dialog (as saved in node properties under /content). What is the equivalent for p.hits=full for this implementation ?
Code is as below:

 "url": "/bin/wcm/contentfinder/qb/view.json"

"baseParams": {
                "path": "/content/Assets/Reference-Components/html-promo-modules/",
                "p.nodedepth": 5,
                "nodename": "htmlpromomodule",
                "p.limit": 1000,
                "p.hits" : "full",
                "orderby": "@name"
            }

The result when this is executed in a browser:
{
"hits": [
{
"path": "/content/Assets/Reference-Components/html-promo-modules/promo1/jcr:content/htmlpromomodule",
"name": "htmlpromomodule",
"lastModified": 1450415449660,
"title": "htmlpromomodule",
"excerpt": "",
"type": "Data",
"msm:isLiveCopy": false,
"msm:isInBlueprint": false,
"msm:isSource": false
}
]
}

The other properties in the node (node at 'path' above) are not displayed..
What is the equivalent for p.hits=full for this implementation ?
Thanks

**Comment by davidjgonzalez** [comment]
This feature only supports a set number of data points for the JSON response as defined in [1].

Making these configurable would be an enhancement.

[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/contentfinder/querybuilder/impl/ContentFinderHitBuilder.java

**Comment by davidjgonzalez** [comment]
This is in support of deprecated ClassicUI feature
