### ISSUE TITLE
ComponentDisabler sets the status of the component it disables to a random number.

### ISSUE THREAD

**Issue by gschneck** [Adobe-Consulting-Services/acs-aem-commons#609]
With ACS Commons 2.2.0, I tried to disable the component "org.apache.jackrabbit.oak.security.user.RandomAuthorizableNodeName" .

It seems to work, but the status of this component is now "64" .

**Comment by davidjgonzalez** [comment]
What version of AEM? Did the ever set the status correctly (to disabled) using a prior acs commons version?

**Comment by davidjgonzalez** [comment]
bump
