### ISSUE TITLE
Icon Picker is not working properly in Touch UI when using it under multifield.

### ISSUE THREAD

**Issue by sudipdgp** [Adobe-Consulting-Services/acs-aem-commons#610]
Hi All,

When i am using the icon picker in a multifield ( here i have used acs-aem-commons multifield functionality to create the multifield ) , its working properly in classic UI. Its saving the data with other fields in a string array, but when i am using Touch Ui , its creating a separate field under jcr:content with the field name and the corresponding values and not storing in the string array and hence both the dialogs are not in sync since values are pointing to different parts of the repository. Could you please tell me what's the issue with the Touch UI.

**Comment by davidjgonzalez** [comment]
@justinedelson any thoughts!?

**Comment by davidjgonzalez** [comment]
I know this was discussed on gitter [1] - did this ever get resolved?

[1] https://gitter.im/Adobe-Consulting-Services/acs-aem-commons

**Comment by sudipdgp** [comment]
@schoudry  : any thoughts???

**Comment by sudipdgp** [comment]
@davidjgonzalez : Hi David the issue still persists. Any idea how to resolve this. In classic UI it's working properly... The problem.is with Touch UI

**Comment by sudipdgp** [comment]
@justinedelson : any thoughts?

**Comment by justinedelson** [comment]
unassigning myself, I don't have time to look into this right now.

**Comment by sudipdgp** [comment]
@acheson0410 @ahmed-musallam : Could you please help me out in this issue.

Thanks,

**Comment by ahmed-musallam** [comment]
@sudipdgp I have not used this widget before, but I can take a quick look at what's happening. can you post your xml for the touch and classic? Or post a package with a ready component I can install on my local and test?

**Comment by viveksachdeva** [comment]
@sudipdgp : I created a dummy component with icon-picker in multifield.. it appears to work fine to me.. Attaching the package here...  Could you give this a shot..
I tested this on AEM 6.2..

[multi-icon-picker.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/518911/multi-icon-picker.zip)

**Comment by davidjgonzalez** [comment]
@sudipdgp was this resolved via @viveksachdeva 's package?
