### ISSUE TITLE
BundleException : Unresolved constraint in bundle com.adobe.acs.acs-aem-commons-bundle-twitter

### ISSUE THREAD

**Issue by anupdugar** [Adobe-Consulting-Services/acs-aem-commons#611]
When i install the acs-aem-commons-content-2.2.0.zip on AEM 6.1, i end up getting the below exceptions:

org.osgi.framework.BundleException: Unresolved constraint in bundle com.adobe.acs.acs-aem-commons-bundle-twitter [460]: Unable to resolve 460.0: missing requirement [460.0] osgi.wiring.package; (&(osgi.wiring.package=twitter4j)(version>=3.0.5)(!(version>=4.0.0)))
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4095)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:977)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:964)
	at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:93)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:847)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:689)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:265)

And from the console there's no way to disable this. Thoughts?

**Comment by jstomar** [comment]
Restart the instance and see if that issue still exist.

**Comment by davidjgonzalez** [comment]
Use the min package of you don't need the Twitter integration or install the supplementary Twitter package if you need Twitter.

**Comment by anupdugar** [comment]
Thanks Guys...
I actually need Bundle and Component Disabler and found that the min package is missing it...
I will try a restart and see if it helps...
Aside this, do you guys think its worth to get the acs commons just for the Disablers components. Or just disabling them manually will do it. 
I am concerned with the number of components and bundles acs commons comes with, it might consume additional resources on the server...

**Comment by joerghoh** [comment]
@anupdugar By default only a very small number of services brought by ACS Commons is active, most require an OSGI configuration to get active. And I don't think, that the ACS Commons bundle consumes that much resources that it really has an impact.

**Comment by anupdugar** [comment]
Tried a restart and it doesn't help.. Twitter exception still comes up.

07.01.2016 08:45:20.892 *ERROR* [FelixDispatchQueue] com.adobe.acs.acs-aem-commons-bundle-twitter FrameworkEvent ERROR (org.osgi.framework.BundleException: Unresolved constraint in bundle com.adobe.acs.acs-aem-commons-bundle-twitter [460]: Unable to resolve 460.0: missing requirement [460.0] osgi.wiring.package; (&(osgi.wiring.package=twitter4j)(version>=3.0.5)(!(version>=4.0.0))))
org.osgi.framework.BundleException: Unresolved constraint in bundle com.adobe.acs.acs-aem-commons-bundle-twitter [460]: Unable to resolve 460.0: missing requirement [460.0] osgi.wiring.package; (&(osgi.wiring.package=twitter4j)(version>=3.0.5)(!(version>=4.0.0)))
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4095)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:744)
07.01.2016 08:45:20.901 *INFO* [FelixStartLevel] com.day.cq.cq-compat-codeupgrade BundleEvent RESOLVED



Thanks for your input @joerghoh ... 
I pulled up the list of acs components and lots of them show up as active

com.adobe.acs.commons.analysis.jcrchecksum.impl.ChecksumGeneratorImpl 	active 	
com.adobe.acs.commons.analysis.jcrchecksum.impl.servlets.ChecksumGeneratorServlet 	active 	
com.adobe.acs.commons.analysis.jcrchecksum.impl.servlets.JSONDumpServlet 	active 	
com.adobe.acs.commons.components.longformtext.impl.LongFormTextComponentImpl 	satisfied 	
com.adobe.acs.commons.contentfinder.querybuilder.impl.viewhandler.QueryBuilderViewHandler active 	
com.adobe.acs.commons.dam.impl.AddWatermarkToRenditionProcess 	active 	
com.adobe.acs.commons.dam.impl.MatteRenditionProcess 	active 	
com.adobe.acs.commons.designer.impl.DesignHtmlLibraryManagerImpl 	satisfied 	
com.adobe.acs.commons.designer.impl.OptionsServlet 	active 	
com.adobe.acs.commons.email.impl.EmailServiceImpl 	active 	
com.adobe.acs.commons.email.process.impl.SendTemplatedEmailProcess 	active 	
com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl 	satisfied 	
com.adobe.acs.commons.forms.helpers.impl.ForwardAsGetFormHelperImpl 	unsatisfied (reference) 	
com.adobe.acs.commons.forms.helpers.impl.PostRedirectGetFormHelperImpl 	unsatisfied (reference) 	
com.adobe.acs.commons.forms.helpers.impl.PostRedirectGetWithCookiesFormHelperImpl 	unsatisfied (reference) 	
com.adobe.acs.commons.forms.impl.FormsPostFilterImpl 	unsatisfied (reference) 	
com.adobe.acs.commons.forms.impl.FormsPostRedirectGetFilterImpl 	unsatisfied (reference) 	 
com.adobe.acs.commons.genericlists.impl.GenericListAdapterFactory 	active 	 
com.adobe.acs.commons.genericlists.impl.GenericListJsonResourceProvider 	active 		
com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl 	unsatisfied (reference) 	 
com.adobe.acs.commons.httpcache.filter.impl.HttpCacheFilter 	unsatisfied (reference) 	
com.adobe.acs.commons.httpcache.invalidator.HttpCacheInvalidationJobConsumer 	unsatisfied (reference) 	
com.adobe.acs.commons.httpcache.rule.impl.CacheOnlyGetRequest 	satisfied 	 
com.adobe.acs.commons.httpcache.rule.impl.CacheOnlyResponse200 	satisfied 	
com.adobe.acs.commons.httpcache.rule.impl.DoNotCacheRequestWithQueryString 	satisfied 	
com.adobe.acs.commons.httpcache.rule.impl.DoNotCacheZeroSizeResponse 	satisfied 	
com.adobe.acs.commons.httpcache.rule.impl.HonorCacheControlHeaders 	satisfied 	 
com.adobe.acs.commons.httpcache.rule.impl.MarkResponseAsCacheDelivered 	satisfied 	
com.adobe.acs.commons.httpcache.store.disk.impl.DiskHttpCacheStoreImpl 	satisfied 	 
com.adobe.acs.commons.httpcache.store.jcr.impl.JCRHttpCacheStoreImpl 	satisfied 	 
com.adobe.acs.commons.httpcache.store.mem.impl.MemHttpCacheStoreImpl 	active 	
com.adobe.acs.commons.images.impl.NamedImageTransformerImpl 	active 	
com.adobe.acs.commons.images.impl.NamedTransformImageServlet 	active 	
com.adobe.acs.commons.images.transformers.impl.AdjustImageTransformerImpl 	active 	 
com.adobe.acs.commons.images.transformers.impl.BoundedResizeTransformerImpl 	active 	
com.adobe.acs.commons.images.transformers.impl.CropImageTransformerImpl 	active 	 
com.adobe.acs.commons.images.transformers.impl.GreyscaleImageTransformerImpl 	active 	
com.adobe.acs.commons.images.transformers.impl.LetterPillarBoxImageTransformerImpl 	active 	
com.adobe.acs.commons.images.transformers.impl.MultiplyBlendImageTransformerImpl 	active 	
com.adobe.acs.commons.images.transformers.impl.ResizeImageTransformerImpl 	active 	
com.adobe.acs.commons.images.transformers.impl.RGBShiftImageTransformerImpl 	active 	
com.adobe.acs.commons.images.transformers.impl.RotateImageTransformerImpl 	active 	
com.adobe.acs.commons.images.transformers.impl.ScaleImageTransformerImpl 	active 	
com.adobe.acs.commons.models.injectors.impl.AemObjectsInjector 	active 	
com.adobe.acs.commons.oak.impl.EnsureOakIndex 	satisfied 	
com.adobe.acs.commons.oak.impl.EnsurePropertyIndex 	active 	
com.adobe.acs.commons.packaging.impl.ACLPackagerServletImpl 	active 	
com.adobe.acs.commons.packaging.impl.AuthorizablePackagerServletImpl 	active
com.adobe.acs.commons.packaging.impl.PackageHelperImpl 	active 	
com.adobe.acs.commons.packaging.impl.QueryPackagerServletImpl 	active 	
com.adobe.acs.commons.quickly.impl.QuicklyFilter 	unsatisfied (reference) 	
com.adobe.acs.commons.quickly.impl.QuicklyInitServlet 	unsatisfied (reference)
com.adobe.acs.commons.quickly.impl.QuicklyServlet 	unsatisfied (reference) 	
com.adobe.acs.commons.quickly.operations.impl.DuckDuckGoDocsOperationImpl 	satisfied 	
com.adobe.acs.commons.quickly.operations.impl.GoOperationImpl 	satisfied 	
com.adobe.acs.commons.quickly.operations.impl.HelpOperationImpl 	satisfied 	
com.adobe.acs.commons.quickly.operations.impl.LastModifiedOperationImpl 	satisfied 	
com.adobe.acs.commons.quickly.results.impl.ResultBuilderImpl 	satisfied 	
com.adobe.acs.commons.quickly.results.impl.serializers.GenericResultSerializerImpl 	satisfied
com.adobe.acs.commons.quickly.results.impl.serializers.OpenResultSerializerImpl 	satisfied
com.adobe.acs.commons.replication.dispatcher.impl.DispatcherFlusherImpl 	active 	
com.adobe.acs.commons.replication.dispatcher.impl.DispatcherFlusherServlet 	active 	
com.adobe.acs.commons.replication.impl.AgentHostsImpl 	satisfied 	
com.adobe.acs.commons.replication.impl.ReplicateVersionImpl 	active 	
com.adobe.acs.commons.replication.impl.ReplicateVersionServlet 	active 	
com.adobe.acs.commons.replication.status.impl.ReplicatedByWorkflowProcess 	active 	
com.adobe.acs.commons.replication.status.impl.ReplicationStatusManagerImpl 	satisfied 	
com.adobe.acs.commons.rewriter.impl.PlainXMLSerializerFactory 	active 	
com.adobe.acs.commons.rewriter.impl.VersionedClientlibsTransformerFactory 	active 	
com.adobe.acs.commons.rewriter.impl.XMLParserGeneratorFactory 	active 	
com.adobe.acs.commons.scripting.impl.QueryBuilderBindingsValuesProvider 	active 	
com.adobe.acs.commons.util.impl.AemCapabilityHelperImpl 	active 	
com.adobe.acs.commons.util.impl.BundleDisabler 	active 	
com.adobe.acs.commons.util.impl.ComponentDisabler 	active

**Comment by justinedelson** [comment]
unless you've deployed the Twitter4J bundle as described here: http://adobe-consulting-services.github.io/acs-aem-commons/features/twitter.html, no amount of restarting will get rid of that exception.

The min package is *not* missing Bundle/Component Disabler.

**Comment by anupdugar** [comment]
@justinedelson  I see. That's good to know.

The other concern was the amount of active components. Do we have any performance numbers or analysis of the impact that acs commons can add? 
In the past we have had issues with performance using AEM 6.1 and that's why anything that brings it down even slightly is of a concern.
If its a concern,  we will disable the components and bundles manually, if its a valid alternative, instead of using the Disablers.

**Comment by justinedelson** [comment]
the number of active-by-default components in ACS AEM Commons is relatively small and is honestly a drop in the bucket relative to the overall number of components in any AEM instance. I've never seen it raised as a concern by any of the users who are using ACS AEM Commons in production.

**Comment by anupdugar** [comment]
Thanks all and @justinedelson for the input..
I will try it out and get back to the community in case of any issue.
