### ISSUE TITLE
Build from fresh clone failing on EmailServiceImplTest

### ISSUE THREAD

**Issue by sachioross** [Adobe-Consulting-Services/acs-aem-commons#612]
After cloning the repo, followed instructions to build the project (_mvn -PautoInstallPackage clean install_ from root, after _mvn -PautoInstallBundle clean install_ from bundle). Build failed with the following: 

    Tests in error: 
    com.adobe.acs.commons.email.EmailServiceImplTest.testBlankTemplatePath(com.adobe.acs.commons.email.EmailServiceImplTest)
      Run 1: EmailServiceImplTest.setUp:96 » FileNotFound /Users/dross/20%20Lines%20of%20Co...
      Run 2: EmailServiceImplTest.tearDown:205 UnfinishedStubbing 
    Unfinished stubbing dete...
    

Looking at 
`com.adobe.acs.commons.email.EmailServiceImplTest`, it was failing at this code: 
`emailTemplatePath = this.getClass().getResource("/emailTemplate.txt").getFile().toString();`

Being honest, not sure why this didn't work. But after searching around found suggestions that lead me to this line of code:

`emailTemplatePath = new File(this.getClass().getResource("/emailTemplate.txt").toURI()).getPath();`

This now correctly locates the file and the tests pass. 

OSX 10.11.2 (El Capitan), Java 8

**Comment by davidjgonzalez** [comment]
@sachioross thanks for reporting and providing the fix!
