### ISSUE TITLE
Twitter feed does not contain timestamp

### ISSUE THREAD

**Issue by hkuiyo** [Adobe-Consulting-Services/acs-aem-commons#618]
Timestamp is not in there, see following code of TwitterFeedUpdaterImpl:

```
  private String processTweet(Status status) {
    String tweet = status.getText();

    for (URLEntity entity : status.getURLEntities()) {
      String url = String.format("<a target=\"_blank\" href=\"%s\">%s</a>", new Object[] { entity.getURL(), entity.getURL() });
      tweet = tweet.replace(entity.getURL(), url);
    }

    return tweet;
  }
```

Now, I don't have the timestamp available.

**Comment by justinedelson** [comment]
Would it help if, in addition to the `tweets` property containing String array, we also set a `tweetsJson` property containing an array of JSON objects? That would allow your component to provide more advanced formatting using the full tweet data.

**Comment by hkuiyo** [comment]
Yes indeed, that would be very helpful!

I can't imagine anyone else hasn't stumbled upon this issue.
