### ISSUE TITLE
Checkbox is not working properly in Touch UI when using it under multifield.

### ISSUE THREAD

**Issue by sudipdgp** [Adobe-Consulting-Services/acs-aem-commons#620]
Hi,

When I am using checkbox under multifield the data is not getting persisted on the dialog.

Anybody has faced the same issue?

**Comment by salaksouth** [comment]
If you are referring to "granite/ui/components/foundation/form/checkbox", mine is working fine. You may want to provide more details on how you are using it.

**Comment by sudipdgp** [comment]
@salaksouth : Yes for me also via checkbox it's working.But I want to show the icons itself in the dialog so that it's easy for the authors to select the icons.
