### ISSUE TITLE
Named Transform Images: Transparent PNG are rendered on black background

### ISSUE THREAD

**Issue by janpop** [Adobe-Consulting-Services/acs-aem-commons#624]
When using the named transform image servlet with resizing I noticed that transparent PNG images are rendered with black background.
Can this be changed to white?
Is there a configuration for this?

**Comment by janpop** [comment]
This only occurs when rendering PNGs as JPGs. 
Using the correct suffix helps.

**Comment by jaredray** [comment]
was there any resolution on this? we are having the same issue with jpg using the servlet

**Comment by davidjgonzalez** [comment]
@jaredray - IIUC - see the above commment. What do you expect the behavior to be? You have a source file (w transparency) (png) and you're converting it to a format that doesn't support transparency (jpg).

**Comment by jaredray** [comment]
@davidjgonzalez we would expect the background to be white... for some reason the background is black on the jpg
