### ISSUE TITLE
ERROR for EnsureOakIndex with no configuration

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#629]
If I just install ACS AEM Commons without any configuration, I get this error message:

     18.01.2016 12:45:41.010 *ERROR* [FelixStartLevel] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.oak.impl.EnsureOakIndex(2245)] The activate method has thrown an exception (java.lang.IllegalArgumentException: OSGi Configuration Property `ensure-definitions.path` cannot be blank.)

I'm guessing this component needs a require policy

**Comment by justinedelson** [comment]
@joerghoh @davidjgonzalez thoughts?

**Comment by davidjgonzalez** [comment]
@justinedelson is that config factory marked w policy=REQUIRED?

@joerghoh noticed something similar to this on WorkflowRemoverScheduler where the configFactory still called activate even in the absence of config policy. (IIRC activate should only be called on a a configFactory when a config is provided?)

**Comment by davidjgonzalez** [comment]
https://github.com/Adobe-Consulting-Services/acs-aem-commons/search?utf8=%E2%9C%93&q=configurationFactory

**Comment by davidjgonzalez** [comment]
Fixed in release 2.2.4
