### ISSUE TITLE
private reference in com.adobe.acs.commons.httpcache.engine

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#633]
[WARNING] Bundle com.adobe.acs:acs-aem-commons-bundle:bundle:2.2.3-SNAPSHOT : Export com.adobe.acs.commons.httpcache.engine,  has 1,  private references [com.adobe.acs.commons.httpcache.engine.impl],

**Comment by justinedelson** [comment]
@davidjgonzalez @Sivaramvt how should this be resolved? Can we just make the referenced class (HttpCacheServletResponseWrapper) part of the API?

**Comment by Sivaramvt** [comment]
@justinedelson I think it's the easy fix for this build warning. BTW, I don't see any application bundle consuming com.adobe.acs.commons.httpcache.engine.HttpCacheEngine either unless it provides a custom implementation for it (which is far fetched).
