### ISSUE TITLE
private references in com.adobe.acs.commons.workflow.bulk.removal

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#634]
[WARNING] Bundle com.adobe.acs:acs-aem-commons-bundle:bundle:2.2.3-SNAPSHOT : Export com.adobe.acs.commons.workflow.bulk.removal,  has 2,  private references [com.adobe.acs.commons.workflow.bulk.removal.impl.exceptions, com.adobe.acs.commons.workflow.bulk.removal.impl],

**Comment by justinedelson** [comment]
@davidjgonzalez I assume the right solution here is just to move the referenced classes to the API, but please confirm.

**Comment by davidjgonzalez** [comment]
Yup - appears to be the WFStatus and the 3 exceptions that can be thrown on the public API.
