### ISSUE TITLE
findbugs issues

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#641]
I just invoked the analysis profile on master and got some warnings:

<pre>
[INFO] --- findbugs-maven-plugin:3.0.1:check (default) @ acs-aem-commons-bundle ---
[INFO] BugInstance size is 14
[INFO] Error size is 0
[INFO] Total bugs: 14
[INFO] com.adobe.acs.commons.httpcache.config.impl.HttpCacheConfigComparator implements Comparator but not Serializable [com.adobe.acs.commons.httpcache.config.impl.HttpCacheConfigComparator] At HttpCacheConfigComparator.java:[lines 10-18]
[INFO] Dead store to cacheContent in com.adobe.acs.commons.httpcache.engine.CacheContent.build(HttpCacheServletResponseWrapper) [com.adobe.acs.commons.httpcache.engine.CacheContent] At CacheContent.java:[line 63]
[INFO] Sequence of calls to java.util.concurrent.ConcurrentHashMap may not be atomic in com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl.bindHttpCacheHandlingRule(HttpCacheHandlingRule, Map) [com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl] At HttpCacheEngineImpl.java:[line 213]
[INFO] Sequence of calls to java.util.concurrent.ConcurrentHashMap may not be atomic in com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl.bindHttpCacheStore(HttpCacheStore, Map) [com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl] At HttpCacheEngineImpl.java:[line 177]
[INFO] Dead store to cacheKey in com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl.wrapResponse(SlingHttpServletRequest, SlingHttpServletResponse, HttpCacheConfig) [com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl] At HttpCacheEngineImpl.java:[line 374]
[INFO] com.adobe.acs.commons.httpcache.rule.HttpCacheHandlingRule is incompatible with expected argument type String in com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl.unbindHttpCacheHandlingRule(HttpCacheHandlingRule, Map) [com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl] At HttpCacheEngineImpl.java:[line 230]
[INFO] String is incompatible with expected argument type com.adobe.acs.commons.httpcache.rule.HttpCacheHandlingRule in com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl.unbindHttpCacheHandlingRule(HttpCacheHandlingRule, Map) [com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl] At HttpCacheEngineImpl.java:[line 229]
[INFO] Synchronization performed on java.util.concurrent.CopyOnWriteArrayList in com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl.bindHttpCacheConfig(HttpCacheConfig, Map) [com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl] At HttpCacheEngineImpl.java:[line 127]
[INFO] Found reliance on default encoding in com.adobe.acs.commons.httpcache.engine.impl.HttpCacheServletResponseWrapper.getWriter(): new java.io.PrintWriter(OutputStream) [com.adobe.acs.commons.httpcache.engine.impl.HttpCacheServletResponseWrapper] At HttpCacheServletResponseWrapper.java:[line 55]
[INFO] com.adobe.acs.commons.httpcache.store.mem.impl.MemCachePersistenceObject.buildForCaching(String, String, Map, InputStream) invokes inefficient new String(String) constructor [com.adobe.acs.commons.httpcache.store.mem.impl.MemCachePersistenceObject, com.adobe.acs.commons.httpcache.store.mem.impl.MemCachePersistenceObject, com.adobe.acs.commons.httpcache.store.mem.impl.MemCachePersistenceObject] At MemCachePersistenceObject.java:[line 47]Another occurrence at MemCachePersistenceObject.java:[line 48]Another occurrence at MemCachePersistenceObject.java:[line 54]
[INFO] com.adobe.acs.commons.httpcache.store.mem.impl.MemHttpCacheStoreImpl.getCacheSize() makes inefficient use of keySet iterator instead of entrySet iterator [com.adobe.acs.commons.httpcache.store.mem.impl.MemHttpCacheStoreImpl] At MemHttpCacheStoreImpl.java:[line 215]
[INFO] com.adobe.acs.commons.synth.impl.SynthesizedResource.getValueMap() makes inefficient use of keySet iterator instead of entrySet iterator [com.adobe.acs.commons.synth.impl.SynthesizedResource] At SynthesizedResource.java:[line 71]
[INFO] com.adobe.acs.commons.synth.impl.SynthesizedSlingHttpServletRequest.setSelectors(String[]) may expose internal representation by storing an externally mutable object into SynthesizedSlingHttpServletRequest.selectors [com.adobe.acs.commons.synth.impl.SynthesizedSlingHttpServletRequest] At SynthesizedSlingHttpServletRequest.java:[line 169]
[INFO] Result of integer multiplication cast to long in com.adobe.acs.commons.workflow.bulk.removal.impl.WorkflowInstanceRemoverImpl.removeWorkflowInstances(ResourceResolver, Collection, Collection, Collection, Calendar, int, int) [com.adobe.acs.commons.workflow.bulk.removal.impl.WorkflowInstanceRemoverImpl] At WorkflowInstanceRemoverImpl.java:[line 155]
[INFO]
</pre>

**Comment by justinedelson** [comment]
I fixed most of these. The ones outstanding are:

    [INFO] Sequence of calls to java.util.concurrent.ConcurrentHashMap may not be atomic in com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl.bindHttpCacheHandlingRule(HttpCacheHandlingRule, Map) [com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl] At HttpCacheEngineImpl.java:[line 232]
    [INFO] Sequence of calls to java.util.concurrent.ConcurrentHashMap may not be atomic in com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl.bindHttpCacheStore(HttpCacheStore, Map) [com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl] At HttpCacheEngineImpl.java:[line 196]
    [INFO] Synchronization performed on java.util.concurrent.CopyOnWriteArrayList in com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl.bindHttpCacheConfig(HttpCacheConfig, Map) [com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl] At HttpCacheEngineImpl.java:[line 146]
[INFO] Found reliance on default encoding in com.adobe.acs.commons.httpcache.engine.impl.HttpCacheServletResponseWrapper.getWriter(): new java.io.PrintWriter(OutputStream) [com.adobe.acs.commons.httpcache.engine.impl.HttpCacheServletResponseWrapper] At HttpCacheServletResponseWrapper.java:[line 74]

@davidjgonzalez these require a bit more knowledge about the internals of the http cache than I have. can you take on the rest?
