### ISSUE TITLE
Making a field mandatory is not working in multifieldpanel

### ISSUE THREAD

**Issue by sudipdgp** [Adobe-Consulting-Services/acs-aem-commons#642]
I am using multifieldpanel and there is textfield and description field. Problem is that the textfield should be a mandatory field. Outside the multifield panel the "required = true" is working properly but in multifieldpanel it is not working.Do you have any idea about this??

**Comment by justinedelson** [comment]
@schoudry any ideas?

**Comment by schoudry** [comment]
@justinedelson i see that the validator was implemented in classic multifieldpanel, nothing exists for touch (node store and json store).... 'll work on it....
