### ISSUE TITLE
VersionedClientlibs calculate the md5 hash on every invocation causing overhead

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#643]
whenever the VersionedClientlibs rewriter rewrites a link, the md5 hash of the respective clientlib is calculated.

On the IBM JVM this can block as indicated by this stacktrace:

````
3XMTHREADINFO      "172.23.7.23 [1453380001694] GET /content/geometrixx/en/favorites.html HTTP/1.1" J9VMThread:0x0000000007537700, j9thread_t:0x00007FFE55BC6190, java/lang/Thread:0x000000011ECD3DB0, state:B, prio=5 
3XMJAVALTHREAD            (java/lang/Thread getId:0x76D8, isDaemon:true) 
3XMTHREADINFO1            (native thread ID:0x28FF4, native priority:0x5, native policy:UNKNOWN, vmstate:B, vm thread flags:0x00000201) 
3XMTHREADINFO2            (native stack address range from:0x00007FFEC000D000, to:0x00007FFEC004E000, size:0x41000) 
3XMTHREADINFO3           Java callstack: 
4XESTACKTRACE                at org/apache/harmony/security/fortress/Engine.getInstance(Engine.java:138(Compiled Code)) 
4XESTACKTRACE                at java/security/MessageDigest.getInstance(MessageDigest.java:75(Compiled Code)) 
4XESTACKTRACE                at org/apache/commons/codec/digest/DigestUtils.getDigest(DigestUtils.java:87(Compiled Code)) 
4XESTACKTRACE                at org/apache/commons/codec/digest/DigestUtils.getMd5Digest(DigestUtils.java:101(Compiled Code)) 
4XESTACKTRACE                at org/apache/commons/codec/digest/DigestUtils.md5(DigestUtils.java:179(Compiled Code)) 
4XESTACKTRACE                at org/apache/commons/codec/digest/DigestUtils.md5Hex(DigestUtils.java:215(Compiled Code)) 
4XESTACKTRACE                at com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.getVersionedPath(VersionedClientlibsTransformerFactory.java:141(Compiled Code)) 
4XESTACKTRACE                at com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.rebuildAttributes(VersionedClientlibsTransformerFactory.java:82(Compiled Code)) 
4XESTACKTRACE                at com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.versionClientLibs(VersionedClientlibsTransformerFactory.java:68(Compiled Code)) 
4XESTACKTRACE                at com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.access$100(VersionedClientlibsTransformerFactory.java:50(Compiled Code)) 
4XESTACKTRACE                at com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory$VersionableClientlibsTransformer.startElement(VersionedClientlibsTransformerFactory.java:161(Compiled Code)) 
4XESTACKTRACE                at org/apache/cocoon/xml/sax/AbstractSAXPipe.startElement(AbstractSAXPipe.java:97(Compiled Code)) 
4XESTACKTRACE                at com/day/cq/rewriter/linkchecker/impl/LinkCheckerTransformer.startElement(LinkCheckerTransformer.java:341(Compiled Code)) 
````

But also from a performance perspective this not benefical. I wonder if the MD5 hash can be stored as part of the clientlib resource and get recalculated on change. Even when the md5 hashing is implemented efficiently, it's overhead we should aim to avoid.

**Comment by davidjgonzalez** [comment]
how are you thinking about achieving this? While i agree the there is a big trade off in # of update operations vs read operations; updating the transitive chain sounds complicated.

**Comment by justinedelson** [comment]
We can certainly test that the `com/adobe/granite/ui/librarymanager/INVALIDATED` event (used here: https://github.com/Adobe-Consulting-Services/acs-aem-tools/blob/master/bundle-live-reload/src/main/java/com/adobe/acs/livereload/impl/ClientLibraryListener.java) is fired and use some kind of in-memory cache of these values. But I'm a little concerned we won't find all the edge cases. Perhaps this should be done as a configuration flag.

**Comment by joerghoh** [comment]
@justinedelson having a small in-memory cache to keep all the MD5 hashes sounds reasonable. Have you already experienced, that the events are not sent correctly?

**Comment by justinedelson** [comment]
> Have you already experienced, that the events are not sent correctly?

No. I think the only case I'd be concerned about is an embed changing, which now that I think about it would be easy enough to test.

**Comment by joerghoh** [comment]
ok, I'll give it a try. I will just cache the MD5 hash of the requested clientlibs and purge the cache entry when the invalidation event is sent. I don't care about the dependency chains and the embedding stuff, that's all the business of the the LibraryManager.

**Comment by justinedelson** [comment]
I've got some time today to figure this out. Should have something to review in an hour or so.

**Comment by joerghoh** [comment]
looks good; I would make the size configurable, but 300 as default is ok.
