### ISSUE TITLE
Multifield event listeners are getting fired.

### ISSUE THREAD

**Issue by rgummalla** [Adobe-Consulting-Services/acs-aem-commons#647]
What is the problem? How is it observed? 

While using the multifield, which stores data in the form of nodes instead of a JSON, the event listeners such as "loadcontent" and "selectionchange" are not getting fired.

How to reproduce?

Create a component with the x-type ,"multi-field-panel" and add event listeners to the nodes. The event listeners don't get fired on the occurrence of that particular event.

**Comment by justinedelson** [comment]
> What is the problem? How is it observed? And what have you already tried to solve the issue?

I don't understand this part of your issue comment.

**Comment by schoudry** [comment]
@rgummalla not sure how you got the xtype:selection to work in node multifield panel (there is a bug which prevents from saving the value); anyway fixed the bug for widget to fire "selectionchanged" event
