### ISSUE TITLE
AEM Project creation in custom hierarchy based on data from project creation wizard

### ISSUE THREAD

**Issue by ramyareddyg** [Adobe-Consulting-Services/acs-aem-commons#649]
Hi,

We have seen a general requirement in projects where we need to create and save the projects in a custom location based on the project data(data from the project creation wizard). 

We could develop a service which handles the projects creation(in AEM 6.x Touch UI) to create and organize the projects in a custom hierarchy(instead of the OOTB hierarchy /content/projects/<date>) so that when there are 1000s of projects we can quickly find the ones related to my category. Categories on which the hierarchy depends can be taken from the project creation wizard and this would be made configurable via having custom properties for widgets in the project creation wizard. 

This service would ensure the below:
1.  Create the project at custom content hierarchy based on the categories chosen in project creation wizard
/content/projects/category1/category2/../categoryN
2.  Move all the project related tiles to the new project location.
3.  Handle the ACLs at the new project location(This would need to create ACLs at new location similar to the ACLs at the original project location).

Let me know your thoughts about this.

**Comment by justinedelson** [comment]
#1 looks interesting to me. I don't know about #2 and #3. Is moving the project really necessary? And if you move a project out of /content/projects does it continue to work in the Projects UI? I would expect not (in the same way that if you create a `dam:Asset` node under /content/mysite, it isn't usable from the Assets UI).
