### ISSUE TITLE
IconPicker in Touch UI - Problem with the classValuePrefix

### ISSUE THREAD

**Issue by jfgrenier-inm** [Adobe-Consulting-Services/acs-aem-commons#651]
Hi

There is a problem with the render of the Selcted Icon. 
**this.settings.classValuePrefix** is undefined and there is no space between the "undefined prefix" and the "fa" class. 

So the class is generated like this : 
`<i class="undefinedfa fa-bluetooth-b"></i>`
instead of
`<i class="fa fa-bluetooth-b"></i>`

File : acs-aem-commons/content/src/main/content/jcr_root/apps/acs-commons/authoring/vendor/jquery.fonticonpicker/jquery.fonticonpicker.js

Line : 695

**Comment by viveksachdeva** [comment]
@jfgrenier-inm : Could you add steps to reproduce this issue? Thanks!!

**Comment by viveksachdeva** [comment]
@jfgrenier-inm : Here is the PR that I have created for this issue.. Mind taking a look? Thanks!!
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/811
