### ISSUE TITLE
enforce password policy in AEM

### ISSUE THREAD

**Issue by ajaykpaul** [Adobe-Consulting-Services/acs-aem-commons#657]
The default password to be set in AEM doesn't have much of rules. If we can enforce crx password policy rules thorough anything from acs commons. 

It should have some UI work, tight integration with the sling and the target website.

**Comment by justinedelson** [comment]
In what way? Oak already supports regex validation: https://jackrabbit.apache.org/oak/docs/apidocs/org/apache/jackrabbit/oak/spi/security/user/action/PasswordValidationAction.html

**Comment by schoudry** [comment]
@ajaykpaul if the error of [1] is not descriptive enough, you can try [2] for touhchui [3] for classicui

[1]
http://experience-aem.blogspot.com/2015/12/aem-61-this-and-that.html#AEM_61_PASSWORD_VALIDATION

[2]
http://experience-aem.blogspot.com/2015/09/aem-61-touch-ui-add-simple-password-policy.html

[3]
http://experience-aem.blogspot.com/2015/09/aem-61-classic-ui-implementing-simple-password-policy.html
