### ISSUE TITLE
Mandatory field is not working properly in multifieldpanel in Touch UI

### ISSUE THREAD

**Issue by sudipdgp** [Adobe-Consulting-Services/acs-aem-commons#662]
Hi All,
After the 2.3 release the mandatory field issue inside the multifieldpanel has been resolved. But I am facing another issue regarding this. Suppose I have a multifield with fields like Link name and Link path which are mandatory fields and the author clicks on add fields options and then click the delete button , the dialog box is not closing as if it still thinks that the fields are empty and not allowing me to click done button.

@justinedelson @schoudry : Could you please look into this?

Thanks,

**Comment by sudipdgp** [comment]
@schoudry  : Have you faced this issue???

**Comment by chhavi1412** [comment]
One of the customers reported this on daycare, I saw the issue on call

**Comment by schoudry** [comment]
@sudipdgp sorry havent checked yet

**Comment by sudipdgp** [comment]
@schoudry : Did you get a chance to see the issue?

**Comment by schoudry** [comment]
@sudipdgp let me try it out today... can you upload a sample component package and share the url

_clicks on add fields options and then click the delete button_

fill the fields and delete or just click add and then delete?

**Comment by sudipdgp** [comment]
@schoudry  : just click on the add new fields( mandatory field inside multifield) and then delete . It freezes and I am not able to click the done button.
