### ISSUE TITLE
Utility to read each item under xtype fieldconfig 'nodemultifieldpanel' values

### ISSUE THREAD

**Issue by ajaykpaul** [Adobe-Consulting-Services/acs-aem-commons#665]
background: The new xtype 'nodemultifieldpanel' creates a node instead of string array for each item. This is helpful in scenarios such as localization. 

However a utility is what we must have which iterates and gets the values of each multfield item for this xtype(nodemultifieldpanel).

**Comment by ajaykpaul** [comment]
A new method should be created here like: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/widgets/MultiFieldPanelFunctions.java

something with the name : getNodeMultiFieldPanelValues.

**Comment by justinedelson** [comment]
I'm not sure this is necessary since you can use the regular resource/node iteration methods in this case. The reason that function exists is that when storing the multifield data in a string array you have to do the JSON parsing. That said, patches welcome!

**Comment by ajaykpaul** [comment]
sure, I am creating a patch for the same then

**Comment by davidjgonzalez** [comment]
supports deprecated ClassicUI feature
