### ISSUE TITLE
EnsureOakIndex removes indexCount property on existing Lucene indexes

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#666]
Recent versions of Oak use the CopyOnWrite feature for Lucene indexes, for which the indexCount property is used to determine a path name on the local disk to store a copy of the lucene index. But these directories are not removed even when a reindexing happened and the indexCount has been incremented.

When an existing lucene index is updated using EnsureOakIndex, the existing indexCount property on the Oak index is removed. When then a reindexing is performed, the COW features doesn't cope well with the existing directory on disk and throws exceptions.

Therefor EnsureOakIndex should never delete an existing indexCount property on an Oak index.

**Comment by davidjgonzalez** [comment]
This was fixed via #765
