### ISSUE TITLE
Versioned ClientLibs

### ISSUE THREAD

**Issue by kdesineedi** [Adobe-Consulting-Services/acs-aem-commons#668]
Hi team,

We are using the versioned clientlibs of ACS commons.Everything was working as expected with the hash numbers for example:

"//localhost:4502/etc/ui/xyz/clientlibs/**one_two**.51fa0469aee8be9249c96195c63e7b73.js"

"//localhost:4502/etc/ui/xyz/clientlibs/**one_two**.51fa0469aee8be9249c96195c67e7b73.css"

However when we renamed to the following naming convention,the hashing is not done for CSS files.

"//localhost:4502/etc/ui/xyz/clientlibs/**one.two**.51fa0469aee8be9249c96195c63e7b73.js"

"//localhost:4502/etc/ui/xyz/clientlibs/**one.two**.css"

Can you please let us know if there is way to get this # generated even with the dot notation for css since it is working for JS.

Regards
Kartheek

**Comment by cpilsworth** [comment]
What version of acs-aem-commons are you using @kdesineedi?

**Comment by kdesineedi** [comment]
Acs 2 0.0

**Comment by cpilsworth** [comment]
It looks like in the VersionedClientlibsTransformerFactory code that it is difficult seperate the part of the URL that is the _resource_ and the part that is a _selector_ (e.g. /path/resource.**min**.css) if the resource name contains dots.  

It would be best to avoid "." characters in jcr node names as you may find problems elsewhere - for example, a valid path to a node with a dot in its name may not be able to resolved from a URL by the Sling ResourceResolver, as it would ignore the part after the "." assuming it to be a selector.

**Comment by kdesineedi** [comment]
Thanks @cpilsworth .However why is not failing the same way for JS files?

**Comment by justinedelson** [comment]
I agree this is very odd. Based on the code, this should not be happening as we check the ending of the path. Can you post the full HTML element for the CSS?

**Comment by kdesineedi** [comment]
Yes.Please find it below.
<link rel="stylesheet" href="//domain.net/etc/ui/abc/clientlibs/abc.xyz.lmn.css" type="text/css">

**Comment by justinedelson** [comment]
hrefs beginning with // will never be rewritten. See https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java#L158

That is true for JavaScript as well.

**Comment by kdesineedi** [comment]
@justinedelson Please see the entire html for the libraries.

```
<link href="/favicon.png" type="image/x-icon" rel="shortcut icon">
<script type="text/javascript" src="//abcdomain.gfhdomain.net/etc/ui/xyz/clientlibs/script1.f8ae99fff2503b7a838a0654f38f4eac.js"></script>
<script type="text/javascript" src="//abcdomain.gfhdomain.net/etc/ui/xyz/clientlibs/script2.bf464603da0f42f30e4489e387620bd1.js"></script>
<script type="text/javascript" src="//abcdomain.gfhdomain.net/etc/ui/xyz/clientlibs/script3.31123ede238a5fabf19a65ae513fc170.js"></script>




<link rel="stylesheet" href="//abcdomain.gfhdomain.net/etc/ui/xyz/clientlibs/style1.monsref.dos.css" type="text/css">





<script type="text/javascript" src="//abcdomain.gfhdomain.net/etc/ui/xyz/clientlibs/script4.dorven.e50sb0360f0009f99bb8453ef39f556c.js"></script>

<script type="text/javascript" src="//abcdomain.gfhdomain.net/etc/ui/xyz/clientlibs/script5.somnoc.e50db0360f0009f99ba8453ef39f556c.js"></script>

<script type="text/javascript" src="//abcdomain.gfhdomain.net/etc/ui/xyz/clientlibs/script6.fedaglt.e50db0360g0009f99bb8453ef39f556c.js"></script>
 
```

The // was coming due to the StaticReferenceRewriterTransformer..
Our attribute configuration is
img:src,link:href,script:src

host.pattern is abcdomain.gfhdomain.net

We are just using cq:includeClientLib for JS and CSS

The moment I change the name of my client lib to underscore the same thing works without any more changes.

Please observe the script5 and script6 JS with a . in the name and they just get appended with the # without any issues.It is only for the CSS the issue arises.

**Comment by justinedelson** [comment]
can you try enabling DEBUG logging on `com.adobe.acs.commons.rewriter.impl.VersionedClientlibsTransformerFactory` ?

**Comment by kdesineedi** [comment]
I can see this message after enabling the debug logs 

```
message=Rewriting to:  <corresponding library>.hashcode.js (including JS libraries with .)

```

When the css has dots. error message:
```
Could not find HtmlLibrary at path: /etc/ui/xyz/clientlibs/style1

```
(It is actually at style1.monsref.dos)

Did not find any log statement corresponding to the CSS  files in question.

When css has underscore in it I can see the log message 

```

Rewriting to: /etc/ui/xyz/clientlibs/style1_monsref_dos.hashcode.css

```

I understand if it is an issue for all selector paths but it succeeds for JS files with . which is what I am trying to understand.

Can you please simulate this scenario at your end and see if the behavior is similar for CSS and JS.

**Comment by cpilsworth** [comment]
When I trace that through, every URL that goes into [VersionedClientlibsTransformerFactory. getVersionedPath:183](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java#L183) that contains a `.` in the node name cannot be found.  I can't see another way that they versioned path can be generated.

The PathInfo object is expecting the part after the `.` to be part of the selector, rather than part of the node name.  So it returns a path with the node name truncated, which `htmlLibraryManager.getLibrary` then doesn't find.

When I try and reproduce this, creating a clientlib with a dash and a dot, I get the following:

```    
<!-- CSS -->
<link rel="stylesheet" href="/etc/designs/app/x/clientlib-all.d41d8cd98f00b204e9800998ecf8427e.css" type="text/css">
<link rel="stylesheet" href="/etc/designs/app/x/clientlib.all.ss.css" type="text/css">

<!-- JS -->
<script type="text/javascript" src="/etc/designs/app/x/clientlib-all.d41d8cd98f00b204e9800998ecf8427e.js"></script>
<script type="text/javascript" src="/etc/designs/app/x/clientlib.all.ss.js"></script>
```

**Comment by kdesineedi** [comment]
@cpilsworth can you please change the name of the JS to 

```
<script type="text/javascript" src="/etc/designs/app/x/clientlib.all.js"></script>

```
and try please.

**Comment by cpilsworth** [comment]
I see a similar result:
```
<link rel="stylesheet" href="/etc/designs/app/x/clientlib-all.d41d8cd98f00b204e9800998ecf8427e.css" type="text/css">
<link rel="stylesheet" href="/etc/designs/app/x/clientlib.all.css" type="text/css">

<script type="text/javascript" src="/etc/designs/app/x/clientlib-all.d41d8cd98f00b204e9800998ecf8427e.js"></script>
<script type="text/javascript" src="/etc/designs/app/x/clientlib.all.js"></script>
```

**Comment by justinedelson** [comment]
@kdesineedi can you try out the patch in #670 and verify that it fixes your issue?

**Comment by kdesineedi** [comment]
Thanks @justinedelson.
Can you please provide a patch zip I can install and verify?

**Comment by justinedelson** [comment]
@kdesineedi you'll need to rebuild the project including the patch.

**Comment by kdesineedi** [comment]
ok @justinedelson .Will do it in a while and let you know.Just want to confirm that there is no restriction to the number of selectors that can be in the clientlibs path post this fix?

**Comment by justinedelson** [comment]
well, if you mean actual selectors (which isn't the case IIUC in your situation), then the only selector supported is `min`. Everything else is assumed to be part of the client library path.

The problem, as @cpilsworth notes is that the current (without this patch) logic is to assume that everything after the first `.` in the path is a selector. Which in your case is a bad assumption as all of that is part of the resource path.

**Comment by kdesineedi** [comment]
Thanks @justinedelson .Yes I mean the filenames for the folders used for clientlibs.We have a case to follow the same name as the UI assets inside the client lib folder and basing on only .min would not help us as the name of the JS/CSS files can be named based on a custom client-specific convention.

Unless it can take any name (with . or _  or - ,etc.) we cannot achieve the hashing part of it.

**Comment by justinedelson** [comment]
Sorry, I can't follow you and/or you've misunderstood me. What I'm trying to explain is that, with this change, the only selector (as in an *actual* selector) is `min`. That makes sense since that's the only select which is actually supported for Client Libraries.

In your examples, however, you don't actually use any selectors (at least if I understood them). You don't even have minification turned on. 

In the example of `/etc/ui/abc/clientlibs/abc.xyz.lmn.css`, my understanding was that `/etc/ui/abc/clientlibs/abc.xyz.lmn` is the actual path to the `cq:ClientLibraryFolder`. Is that not the case? If it is, then `/etc/ui/abc/clientlibs/abc.xyz.lmn.css` does not actually have any selectors in it. `/etc/ui/abc/clientlibs/abc.xyz.lmn.min.css` does have a selector (`min`).

**Comment by kdesineedi** [comment]
Ok let me clarify:
some of our UI assets (JS/CSS) are named as abc.xyz.lmn.css,script6.fedaglt.js,etc.In the view source when the front-end developers are debugging,they are not seeing the actual file names and are seeing the modified filenames(due to clientlibs).So the need is to just keep them consistent.While this works for normal functionality,the hashing part of the libs do not work.Hence the issue.( you are correct in saying that we do not have selectors as such for clientlibs,it is just the name)
