### ISSUE TITLE
RTE (used in multifield) is not showing the previously stored content when edit the component.

### ISSUE THREAD

**Issue by sudipdgp** [Adobe-Consulting-Services/acs-aem-commons#669]
Hi,

We are using multi-field from ACS AEM COMMONS package which was given from your team.

We are facing some issue in RTE plugins in multi-field.

Steps to reproduce:
Create a component with multifield and use RTE inside the miltifield
Drag & Drop the component on your page and Fill the content & save it.
Reopen the dialog to edit the content.
On the RTE you will not see the previously stored content.

We got the reply from Adobe support team as follows.
==================
The Adobe Platinum Maintenance & Support contract entitles to log any product related issue (ie. fully reproducible on an OOTB installation), but doesn't officially cover the following :
Custom code review or troubleshooting
Custom enhancements
Development services
Architecture reviews
Knowledge transfer and training services
Third party product or hardware recommendations
Troubleshooting of non-Adobe products
Issues of non supported configurations

Leveraging our Adobe Professional Services team is highly recommended for application/customization/architecture issues, as they have much more in-depth project experience. In case you'd like to reach out to Adobe Professional Services, you can contact : <EMAIL ADDRESS OF THE ENGAGEMENT MANAGER FROM PROFESSIONAL SERVICES>

For non urgent application/development related questions/issues, please leverage the Adobe AEM forum (1). 

(1) http://help-forums.adobe.com/content/adobeforums/en/experience-manager-forum/adobe-experience-manager.html

Thanks for your understanding.
============================
Can you please resolve the issue from your end.

**Comment by schoudry** [comment]
@sudipdgp is it possible for your team to try the logic in [1], test, port the pieces to ACS AEM Commons Multifield and submit a pull with fix patch..

[1]
http://experience-aem.blogspot.com/2015/07/aem-61-touch-ui-composite-multifield-with-rich-text-editor-rte.html

**Comment by acheson0410** [comment]
Hi @schoudry, can we please have following updates on the touchui-widgets-init.js?

        isHiddenField: function ($field) {
            return !_.isEmpty($field) && ($field.prop("type") === "hidden");
        },

        setHiddenField: function($field, value) {
            var $parent = $field.parent();
            if ($parent.hasClass("coral-DatePicker")) {
                var displayFormat = $parent.attr("data-displayed-format");
                var storedFormat = $parent.attr("data-stored-format");
                var date = new moment(new Date(value));
                var dateFormatted = date.format(displayFormat);
                $parent.find("input.coral-Textfield").val(dateFormatted);
                value = date.format(storedFormat);
            }
            $field.val(value);

            if (!$parent.hasClass("richtext-container") || $field.hasClass("coral-RichText-isRichTextFlag")) {
                return;
            }

            $parent.find(".coral-RichText-editable.coral-RichText").empty().append(value);
        },

        setWidgetValue: function ($field, value) {
            if (_.isEmpty($field)) {
                return;
            }

            if (this.isSelectOne($field)) {
                this.setSelectOne($field, value);
            } else if (this.isCheckbox($field)) {
                this.setCheckBox($field, value);
            } else if (this.isHiddenField($field)) {
                this.setHiddenField($field, value);
            } else {
                $field.val(value);
            }
        }

**Comment by schoudry** [comment]
@acheson0410 - can you submit a pull request with a brief write-up of issues fixed by the logic above...

**Comment by sudipdgp** [comment]
@acheson0410  @schoudry : Hi ,After the Fix content is showing for the RTE inside multifield, but another issue came up while authoring the content. 

Suppose if there are 2 fields in the multifield like Title( texfield ) and Description ( richtext ) , if the hover  is on the description field and then I click the " Add new field " option then the data gets vanished in the RTE field, however if the hover is on the Title field and then I click the " Add new field " option then the data remains in the RTE. Could you please check this scenario from your end.

Thanks,

**Comment by acheson0410** [comment]
@sudipdgp, there are many bugs within RTE and multifield in Touch UI 61. The one you mentioned above is one of them. You are better to raise daycare ticket and ask for hotfix package regarding it.
