### ISSUE TITLE
Multifield Storing issue

### ISSUE THREAD

**Issue by SanketDixit** [Adobe-Consulting-Services/acs-aem-commons#671]
Hi,

I'm using acs-commons multifield in my project for storing multiple data.

Found a issue in the storing mechanism for the multifield:-

Scenario 1:-
When adding 2 fields in the multifield, it's store as a Json string in String[] data type.

Scenario 2:-
When adding 1 field in the mutlifield, it's store as a Json string but in String data type.

Scenario 3:-
Now adding 1 more field in the Scenario 2 multifiled, now the Json string is still stored in the String data type & is separated by ','. Here the data type of String to String[] is not happening.

As per my understanding, if I'm using multifield it should store the data in String[] data type only not in String data type.

Thanks & Regards,
Sanket

**Comment by sudipdgp** [comment]
@justinedelson @schoudry : Could you please look into this issue.

**Comment by SanketDixit** [comment]
Clone #675.
Got the solution so closing.
