### ISSUE TITLE
Multifield storing data as a string if authored only one entry in multifield.

### ISSUE THREAD

**Issue by sudipdgp** [Adobe-Consulting-Services/acs-aem-commons#675]
Hi,

I'm using acs-commons multifield in my project .

Found a issue in the storing mechanism for the multifield:-

Scenario 1:-
When adding 2 fields in the multifield, it's store as a Json string in String[] data type.

Scenario 2:-
When adding 1 field in the mutlifield ( 1st time when the author is entering data in the multifield), it's store as a Json string but in String data type.

Scenario 3:-
Now adding 1 more field in the Scenario 2 multifiled, now the Json string is still stored in the String data type & is separated by ','. Here the data type of String to String[] is not happening.

As per my understanding, if I'm using multifield it should store the data in String[] data type only not in String data type.

Could you please check this issue.

@justinedelson @schoudry @acheson0410

**Comment by acheson0410** [comment]
@sudipdgp, I am not able to re-produce it. But did you try to set the TypeHint as String[]?

**Comment by sudipdgp** [comment]
@acheson0410 : Thanks a lot .. I tried the TypeHint property and after that it's working properly.. :)
