### ISSUE TITLE
Composite Multifield Issues in Touch UI and Classic UI

### ISSUE THREAD

**Issue by salaksouth** [Adobe-Consulting-Services/acs-aem-commons#679]
Found several issues when testing with a few more Touch UI dialogs by using a cloned (and renamed) "definition-list" component. 

**1. Radio Group (granite/ui/components/foundation/form/radiogroup)**
- Always save the first selection value into JCR, no matter if any radio button selected or not.
- After save, reopen for in editing mode; Radio Group selected value will not be populated.
- While editing, if there's more than one set of dialogs; Radio Group will only recognize one set of selection at one time. First Radio Group selection will be gone, if we click on the second set Radio Group selection.

**2. Only the default showcase Touch UI dialogs (Text, TextArea) values will be populated and displayed in Classic UI editing mode. (Right click on the component, edit).**
- Tested with numberfield, datetime, checkbox, radiougroup, selectsingle, and pathfield.

**3. Not sure if I'm doing it correctly or not, here attach the sample component I created to simulate the above mentioned issues.**
[composite-multifield-test-0.1.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/171159/composite-multifield-test-0.1.zip)

**Comment by schoudry** [comment]
@salaksouth thank you for the effort - classic and touch multifields, both were not tested with all available widgets - any issues were fixed when reported

check this pull where conditional statements were added by @acheson0410 for richtext and date fields - https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/674/files

would you be able to submit a pull with similar fixes for radiogroup, numberfield etc...

**Comment by AnuVelayutham** [comment]
@davidding  Still the issue is occurring in AEM 6.4. Is the solution arrived for this?
