### ISSUE TITLE
Bundle not starting after Server Restart | AEM 6.1 | Sightly

### ISSUE THREAD

**Issue by nikhil-gupta89** [Adobe-Consulting-Services/acs-aem-commons#681]
23.03.2016 08:07:05.683 *ERROR* [qtp805710203-5004] org.apache.felix.http.jetty %bundles.pluginTitle: Cannot start (org.osgi.framework.BundleException: Unresolved constraint in bundle com.volvo.volvo-platform-bundle [499]: Unable to resolve 499.0: missing requirement [499.0] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.sightly)(version>=2.2.0)(!(version>=3.0.0))))

org.osgi.framework.BundleException: Unresolved constraint in bundle com.volvo.volvo-platform-bundle [499]: Unable to resolve 499.0: missing requirement [499.0] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.sightly)(version>=2.2.0)(!(version>=3.0.0)))

**Comment by davidjgonzalez** [comment]
This looks like an issue w your projects sightly dependency. What makes you believe this has something to do a acs commons?

**Comment by nikhil-gupta89** [comment]
As it is not happening in all the environments. We believe that it may be relates to acs commons.

**Comment by justinedelson** [comment]
Why do you believe that?

**Comment by nikhil-gupta89** [comment]
May be i m wrong :)

Could you please guide me, where should i Put this issue ?

**Comment by NielsInc** [comment]
Hi Nikhil, 
We also have this issue occasionally.
 
To resolve it, we stop the server, navigate to following path:
\crx-quickstart\launchpad\felix\bundle21\data
and delete the **digraph** file.

We learned from Adobe that this file somehow retains some dependencies between bundles, so by removing the file, the issue should be solved.

**Comment by justinedelson** [comment]
I would suggest working with daycare before deleting any internal files.

**Comment by NielsInc** [comment]
@justinedelson This is a solution that was communicated to us by Adobe Managed services

**Comment by nikhil-gupta89** [comment]
@justinedelson: The solution is not working for us,

Raised the concern with the daycare. :)

Thanks guys. Will post here once daycare provide the solution.

**Comment by krassib** [comment]
Hi nikhil-gupta89,

We are facing same issue in my current AEM 6.1 project. Can you tell me if you got an update from Daycare on the solution?

Thanks,
Krass

**Comment by nikhil-gupta89** [comment]
Hi @krassib,

Daycare team provided the solution by deleting the ''org.eclipse.equinox.region" bundle from the felix and then restart the server and then redeploy your code bundle.

We learned from Adobe that this bundle has some dependency with eclipse and should not be in AEM6.1, it was meant for AEM 6.2. But somehow it got introduced in this version.

Hope this will work for you too.

Thanks,
Nikhil

**Comment by krassib** [comment]
Hi @nikhil-gupta89,

Thanks for the quick reply. I really appreciate it!

Do you remember during your research if the Geometrixx content was involved? I.e. did you have to have Geometrixx app and content in order to make it work? I am asking because we are facing some dependency on it. If the Geometrixx is present  and then uninstalled we don't see the bundle issue.

Thanks again,
Krass

**Comment by justinedelson** [comment]
@krassib this issue (aside from having nothing to do with ACS AEM Commons and so probably shouldn't be discussed further here) is non-deterministic. It has nothing to do with Geometrixx. It is a bug in the Equinox Region bundle and could appear with really any combination of installed packages.

**Comment by gmisura** [comment]
This worked (removing the eclipse bundle).
However, it is a bit strange that the issue did present itself on environments where we had: 1dispatcher, 1publisher, 1author
The issue only showed up where we had: 4dispatchers, 4publishers, 1 author.
I'm still going to remove the eclipse patch from the environments with 1disptcher/1publisher to be consistent.
But I'm curious to know if there is something about the eclipse bundle that would cause it to work on a single instance setup and fail on a multiple instance setup?

Should this not be addressed in a SP?

Thanks
