### ISSUE TITLE
Delegating Servlet issues in AEM 6.1

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#685]
Moving to GH for visibility from Brett Birschbach: http://adobe-consulting-services.github.io/acs-aem-commons/features/delegating-servlet.html#comment-2613784251

I tested this on AEM 6.1 for the use case of "Moving resource type implementations without modifying all content sling:resourceType properties." I ran into several issues and am curious if anyone has any input.

In my example I changed a "hero" component to "hero-changed". Note that I did test all scenarios with new instances of the "hero-changed" component to verify that I have that component configured correctly. The issues below all involve rendering the old "hero" component instances which are being mapped to "hero-changed" by the DelegatingServlet.
- Instances of the old "hero" resourceType will render on the page, but they will not include the CSS class (.hero-changed) in the HTML for the component. As such, component styling is not picked up.
- Instances of the old "hero" resourceType do not have a dialog on the touch UI and thus cannot be configured/updated.
- At times the rendering of the old "hero" components fails if the component is sufficiently far enough down the page to trigger "java.lang.IllegalStateException: Response already committed"
- At times (I'm not sure the full cause) an old "hero" component on the page causes some of the page HTML to simply be missing at the top of the page, completely breaking the page. This happened when attempting to use the classic authoring UI, but also in other cases.

One other "gotcha" for those using the DelegatingServlet for this use case:
- Initially the background image from the DAM for the old "hero" instances were not successfully rendered. That's because I had configured the DelegatingServlet with the default extension of ".html". For the image connected to the component to render correctly, I needed to also add ".png" as an extension. In practice, it looks like I would need to add every possible image extension to be safe.

**Comment by HitmanInWis** [comment]
Thanks David!
