### ISSUE TITLE
Path Based Render Condition

### ISSUE THREAD

**Issue by kaushalmall** [Adobe-Consulting-Services/acs-aem-commons#692]
Out of the box, there's really only two render conditions available. Privilege and simple. Although simple is pretty powerful as you can provide an EL expression, but it doesn't something as simple as "show this menu item under path /content/geometrixx/*". For this we can use a path based render condition. 

Is this something that'll be useful? WDYGT? @justinedelson @davidjgonzalez

**Comment by davidjgonzalez** [comment]
So this would be a convenience method for using el on requestPathinfo.resourcePath matches XXX?

I can see this being a very common use case. Are you thinking a startsWith check or a refer matches? Also could multiple path patterns be specified or would an OR rendition condition be used?

**Comment by kaushalmall** [comment]
>So this would be a convenience method for using el on requestPathinfo.resourcePath matches XXX?

Yes. 

>Are you thinking a startsWith check or a refer matches? 

I was thinking something like below. 

`boolean vote = false;
String suffix = slingRequest.getRequestPathInfo().getSuffix();
    if (suffix != null) {
        vote = suffix.matches(pathRegex);
    }`

>Also could multiple path patterns be specified or would an OR rendition condition be used?

You can use OR.

**Comment by kaushalmall** [comment]
Where should I put the render condition? Under /apps/acs-commons/authoring?

**Comment by davidjgonzalez** [comment]
Per our offline discussion i think your suggestion of: `acs-commons/granite/ui/components/renderconditions/path` is great. aligns well w the product pathing.

**Comment by justinedelson** [comment]
+1
