### ISSUE TITLE
Pathfield inside multifiled issue

### ISSUE THREAD

**Issue by Divya-Sekar** [Adobe-Consulting-Services/acs-aem-commons#694]
When there is a pathfield inside a multifield, the second time we try to author the pathfield without clicking on OK, drag and drop functionality is not working.
Summary: This is related to a component with multifield in its dialog. When there is a pathfield inside a multifield, the second time we try to author the pathfield without clicking on OK, drag and drop functionality is not working.
How to reproduce: 
Step 1: Drag and drop a component with pathfield inside a multifield.
Step 2: Click and edit the component.
Step 3: Click on Add Item and drag and drop an image in the pathfield.
Step 4: Delete the item in the multifield, by clicking on the red delete icon.
Step 5: Now without click OK, click on Add Item again and try to drag and drop image into the same pathfield
Step 6: Drag and drop functionality doesn’t work. (Image field)
Occurrence: It occurs always for a multifield

**Comment by viveksachdeva** [comment]
@Divya-Sekar : Could you add a content package that can be used to validate this issue.. Moreover adding AEM and ACS-commons using which you re getting this issue would help..

Thanks!!

**Comment by davidjgonzalez** [comment]
@Divya-Sekar can you please provide the requested info and re-open as needed? Thanks!
