### ISSUE TITLE
Query Autocomplete List

### ISSUE THREAD

**Issue by kaushalmall** [Adobe-Consulting-Services/acs-aem-commons#696]
For a project we had to build an autocomplete list generator that would run based on a query. A simple example of the node structure would look something like 

```
<filter
         jcr:primaryType="nt:unstructured"
	sling:resourceType="granite/ui/components/foundation/form/autocomplete"
	fieldLabel="Select Old Part *"
	name="./filterOld">
	<options
		jcr:primaryType="nt:unstructured"
		sling:resourceType="granite/ui/components/foundation/form/autocomplete/list"
		predicates="[type=nt:unstructured,1_property=sling:resourceType,1_property.value=my-app/components/content/part]"
		property="jcr:title"
		src="/apps/my-app/gui/content/common/filterautocomplete.html{?query,start,end}"/>
</filter>
```

![image](https://cloud.githubusercontent.com/assets/4323558/14661580/91bd267a-0663-11e6-83ce-57cda6b36b43.png)

@davidjgonzalez @justinedelson. Is this something worth contributing? Basically the idea is that, you provide a list of predicates and the query result set becomes your autocomplete list.

**Comment by davidjgonzalez** [comment]
@kaushalmall this is basically a querybuilder search widget? it just we just parameterize the predicates instead? 

```
<filter
         jcr:primaryType="nt:unstructured"
    sling:resourceType="granite/ui/components/foundation/form/autocomplete"
    fieldLabel="Select Old Part *"
    name="./filterOld">
    <options
        jcr:primaryType="nt:unstructured"
        sling:resourceType="granite/ui/components/foundation/form/autocomplete/list"
        predicates="[type=nt:unstructured,1_property=sling:resourceType,1_property.value=my-app/components/content/part,p.limit={limit},p.offset={offset},fulltext={query}]"
        property="jcr:title"
        src="/apps/my-app/gui/content/common/qb.html"/>
</filter>
```

**Comment by kaushalmall** [comment]
sort of, currently, the OOTB autocomplete widget doesn't have anything nice to build a list out. Usually people will use something similar to populate the valid items. Also, the QB search widget won't just work, because the autocomplete list has to populate items in <li> tags as `<li class='coral-SelectList-item coral-SelectList-item--option' data-value='" + text[1].toLowerCase() + "' data-path='" + text[1] + "'>" + text[0] + "</li>`

Does this help? Or did you mean something totally different?

**Comment by davidjgonzalez** [comment]
@kaushalmall ah gotcha; still think this is a nice addition..

**Comment by kaushalmall** [comment]
sounds good. I just need to dumb down our version for the PR. will send one when I am done.

**Comment by kaushalmall** [comment]
@justinedelson @davidjgonzalez submitted a PR for this and the corresponding document. let me know if there is anything else you need from me.

**Comment by davidjgonzalez** [comment]
Added in 2.5.0/3.1.0
