### ISSUE TITLE
Configure Parsys Placeholder

### ISSUE THREAD

**Issue by rcouto-cit** [Adobe-Consulting-Services/acs-aem-commons#698]
Hi,

On the version 2.3.2 there is a feature called touchui-configure-parsys-placeholder that tries to request a configuration from a path like that: /etc/designs/geometrixx/jcr:content/contentpage/par

But as I don't have this path configured in my repository, neither I want to use this feature, I believe that this feature should starts turned off and only when I want to use it I should have a way to turn it on.

When this feature starts and tries to access a node that doesn't exist the author can see this error on the console:
granite.min.js:64 GET http://localhost:4502/etc/designs/default/jcr:content/templateWeb/par.2.json?_=1461268087386 404 (Not Found)

Which is the better way to resolve this issue?
![screenshot from 2016-04-21 16 59 49](https://cloud.githubusercontent.com/assets/12274195/14722578/88e63ade-07e2-11e6-92c9-95fcba52e836.png)

**Comment by stevenwoodson** [comment]
I've also just come across this same issue and hoping for a resolution.

**Comment by justinedelson** [comment]
Sorry, perhaps I'm being dense, but why is this an issue? A 404 is a valid response and this doesn't prevent other JS on the page from working.

**Comment by shams8090** [comment]
Hi, i'm facing the same issue. Any fix or work around.
Currently i have installed ACS commons version 2.8.

**Comment by rao4** [comment]
Facing the same issue on 3.0.2 any resolutions found for this issue?

**Comment by adpv-gm** [comment]
Has this issue been resolved? I'm using the latest version of AEM Commons (3.7.0) and still seeing the 404 console errors when hovering over parsys.

**Comment by davidjgonzalez** [comment]
@adpv-gm can you show the line of code that is initiating this XHR? Like @justinedelson requesting something that doesnt existing isnt an error; it can simply be checking to see if it exists, and if it doesn't it will react accordingly. The 5xx class of responses are the ones that you ought to be worried about.

**Comment by shubhakirani** [comment]
We had the same issue. All the jsons with .2.json are being blocked. We commented this function below and issue disappear. Please recommend what this function is for and if we have any alternate solution?

`/*        $.ajax( { url: path + ".2.json", async: false } ).done(function(data){
            if(_.isEmpty(data) || !data[ACS_COMPONENTS_LIMIT]){
                return;
            }

            currentLimit = data[ACS_COMPONENTS_LIMIT];

            var limit = parseInt(data[ACS_COMPONENTS_LIMIT]);

            isWithin = children.length <= limit;
        }); */`

**Comment by justinedelson** [comment]
@shubhakirani with the next release, you will be able to disable this functionality (it will still be enabled by default for backwards-compatibility reasons).

**Comment by davidjgonzalez** [comment]
Fixed via https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/944
