### ISSUE TITLE
EnvironmentIndicator should not be displayed with wcmmode=disabled

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#699]
To have a consistent preview on author, the environment indicator should not be displayed when the wcmmode=disabled is set. With the current version it is always injected into the output.

This would allow to use this feature also on publish instances, where it's useful for CRXDE Lite and Webconsole.

**Comment by davidjgonzalez** [comment]
@joerghoh dont a number of authoring console have wcmmode set to disabled?

Are you suggesting this on requests for /editor.html and /cf only? 

Would `preview` fall into this blacklist bucket as well?

**Comment by joerghoh** [comment]
@davidjgonzalez not sure about the authoring consoles. I got the feedback especially for /cf and wcmmode=disabled, but for preview it should work as well.
But thanks for the hint, wasn't thinking of that yet.

**Comment by davidjgonzalez** [comment]
Added in 2.5.0/3.1.0 - thanks @joerghoh
