### ISSUE TITLE
Scrollbar issue for "Findreplace" plugin for RTE in touch UI

### ISSUE THREAD

**Issue by Divya-Sekar** [Adobe-Consulting-Services/acs-aem-commons#700]
Steps to reproduce:
1) Add findreplace plugin for rte component
2) Edit a component using inplace editing 
3) Go to fullscreen mode where you can see rte plugins including find replace
4) Give some big paragraph which exceeds a page
5) find for some word
6) once it reaches end of the page, the scrollbar is not moving down to show other find results. we have to manually scroll and see

What is the solution for this?

**Comment by justinedelson** [comment]
How is this related to ACS AEM Commons?

**Comment by davidjgonzalez** [comment]
Closing as does not appear to relate to ACS Commons. Please reopen if it does and provide info how.
