### ISSUE TITLE
Responsive column control - LESS compilation failure when using AEM 6.1

### ISSUE THREAD

**Issue by mauro-dellachiesa** [Adobe-Consulting-Services/acs-aem-commons#701]
Hi,
Looks like the LESS compiler of my AEM 6.1 instance does not play well with .loopingClass. I'm getting this error when adding the client library **"acs-commons.components"**.
This is the particular error I'm getting:

`LESS compilation failed due a JavaScript error!

Input: /apps/acs-commons/components/content/column-control/clientlib/css/colctrl.less
Error: ParseError: Unrecognised input in /apps/acs-commons/components/content/column-control/clientlib/css/colctrl.less on line 45, column 15:
44 // will be called as long the index is above 0
45 .loopingClass (@index) when (@index > 0) {
46     (~".acs-commons-resp-colctrl-col-@{index}") {`

This causes the columns in the column control not to display in the way they are supposed to look: they are shown in rows.
My version, according to http://localhost:4502/system/console/status-productinfo, is Adobe Experience Manager (6.1.0.SP1)

The particularity of this is that if I use the same package (maven generated) on a AEM 6.0 SP1 instance it works flawlessly 

Thanks!

**Comment by otarsko** [comment]
Have the same issue on AEM 6.2 with 3.3.0 version. Is it fixed in 3.3.2?

**Comment by otarsko** [comment]
Replacing 
`(~".acs-commons-resp-colctrl-col-@{index}")`
with
`.acs-commons-resp-colctrl-col-@{index}`
fixes issue in AEM 6.2 but I am not sure regarding compatibility with older versions.

**Comment by rubnig** [comment]
Fix from otarsko works also for AEM 6.1

**Comment by hkuiyo** [comment]
Still not fixed in 3.4.0.

**Comment by Ramadevi3** [comment]
Hi,

What is the permanent fix for this issue for older versions also.

Can I add these properties in 'colctrl.less' file to fix permanently?
.multicolor .acs-commons-resp-colctrl-col { 
 padding: 0 24px; 
 position: relative; 
 box-sizing: border-box;
 float: left;
 width: 25%; 
}
