### ISSUE TITLE
Touch UI Draggable List Widget

### ISSUE THREAD

**Issue by kaushalmall** [Adobe-Consulting-Services/acs-aem-commons#708]
A draggable list widget for Touch UI that would build out a list from a simple datasource and let authors prioritize the list like below. 

![image](https://cloud.githubusercontent.com/assets/4323558/14942791/04c08f38-0f7c-11e6-9859-625fabeaf5c5.png)

Its kind of like the widget on the left side of this page, without the settings and the delete icon. We could add the delete icon eventually.  
http://localhost:4502/libs/social/console/content/editgrouptemplate.html/etc/community/templates/groups/reference/reference-group-workspace-site 

WDYT?

**Comment by SuperAnkit** [comment]
I was having problem using the list for more than 15 items. The re-ordering doesn't seem to work.

**Comment by kaushalmall** [comment]
@SuperAnkit which version of AEM are you using? What does your datasource look like? I am not able to reproduce it on 6.1. I have a simple DS like below which loads 20 items and it seems to work for me. 

```<%@include file="/libs/granite/ui/global.jsp" %>
<%@page session="false"
        import="com.adobe.cq.commerce.common.ValueMapDecorator,
                com.adobe.granite.ui.components.ds.DataSource,
                com.adobe.granite.ui.components.ds.SimpleDataSource,
                com.adobe.granite.ui.components.ds.ValueMapResource,
                org.apache.sling.api.resource.ResourceMetadata,
                java.util.ArrayList,
                java.util.HashMap,
                java.util.List" %>
<%
    List<Resource> resourceList = new ArrayList();
    
    for( int i = 0; i <= 20; i ++) {
        ValueMap vm = new ValueMapDecorator(new HashMap<String, Object>());
        vm.put("value", i);
        vm.put("text", i);
        resourceList.add(new ValueMapResource(resourceResolver, new ResourceMetadata(), "nt:unstructured", vm));
    }
    
    DataSource ds = new SimpleDataSource(resourceList.iterator());
    request.setAttribute(DataSource.class.getName(), ds);
%>

```

**Comment by davidjgonzalez** [comment]
@SuperAnkit please re-open if needed.
