### ISSUE TITLE
CEDDL Data Layer object component

### ISSUE THREAD

**Issue by araraty** [Adobe-Consulting-Services/acs-aem-commons#712]
A data layer is a way to format data within a web page in a JavaScript Object (JSO) object readily available to analytics and personalisation scripts. It is comprised of a collection of one or more JSOs holding data or events/signals about the page and current user.
As the CEDDL standard has been most requested and adapted by clients, the implementation of a seed of the CEDDL format (https://www.w3.org/2013/12/ceddl-201312.pdf) will create a quicker point to start from the implementation of the data layer.
The Data Layer is a component included in the page template at the required point and will run at server side to collect some elements.
Due to each project been different and content structure to be unique the current implementation is based on the geometrixx outdoors and is between a showcase and a seed to be used by developers.

**Comment by justinedelson** [comment]
@araraty would this be more suited to https://github.com/adobe-consulting-services/acs-aem-samples?

**Comment by araraty** [comment]
@justinedelson Torn between the 2. as it is a base that you can just install and be done with it.
You then let the data expert use JS to fill the data layer and can also, in custom components, fill the data layer.
You don't need to change the original component for the above to be working. 

It could be considered a sample you extend upon in case you want to add more server side data collection for pages in your template in some cases. but those are a bit more "advance" situations.

So it fits both in some sort of a way. though i think it might be important to have it in the commons capability as it is something you can just turn on.

**Comment by IttaiB** [comment]
@araraty @justinedelson - I vote ags-commons simply because it has a very broad reach in the AEM ecosphere. We need to ensure the documentation emphasizes that this is something that customers should extend.

**Comment by davidjgonzalez** [comment]
To @IttaiB's point, if we move this to commons it might be interesting to think about a pluggable/extendable framework so ppl can develop/distributed CEDDL populators - could look at server-side vs client-side (IME i've had to do ALOT of client-side population of CEDDL; we actually build a light framework for it)

For example, a 80% use case is populating the obj w/ a page's title, path, language, country, etc. Im guessing there are other common use-cases as well (products perhaps?)

**Comment by davidjgonzalez** [comment]
Closing as @klcodanr suggested he may be interested in contributing his award winning DDO
