### ISSUE TITLE
ddpathfield: drag & drop doesn't work unless the page is refreshed

### ISSUE THREAD

**Issue by nsrini** [Adobe-Consulting-Services/acs-aem-commons#717]
Environment:AEM 6.0 with acs commons 2.2.0

In the dialog.xml: 
<highlighted-stories
                            jcr:primaryType="cq:Widget"
                            fieldLabel="Highlighted Stories"
                            fieldDescription="Press + to add more links"
                            name="./highlightedStories"
                            xtype="multifield">
                            <fieldConfig
                                jcr:primaryType="cq:Widget"
                                ddGroups="[article,video]"
                                ddAccept="[*]"
                                height="80"
                                width="150"
                                rootPath="/content/fox-business"
                                xtype="ddpathfield"/>
                        </highlighted-stories>

When I go to the component, I can add and drop as many as I want. After I closed the dialog, If I reopened the dialog, I can't drop unless I refresh the page.

thanks
Srini

**Comment by davidjgonzalez** [comment]
This works fine for me. Can you provide exact steps to reproduce on vanilla AEM and re-open?
