### ISSUE TITLE
Responsive Column Control - Should provide an option for specifying the heights of the columns

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Consulting-Services/acs-aem-commons#723]
Currently, the responsive column control is a great way to create "grid"-like features on a website.

By specifying how wide columns are, you are very flexible in what you can do.

I would say a great addition to this feature would be to also specify the heights of the columns. I.e. you want a column to span 2 rows. Currently, there is no way to configure this.

**Comment by davidjgonzalez** [comment]
This is now a deprecated ClassicUI feature
