### ISSUE TITLE
Responsive Column Control - Specify styling on generic class instead of specific column classes

### ISSUE THREAD

**Issue by hkuiyo** [Adobe-Consulting-Services/acs-aem-commons#726]
Look at: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/7956e740008d09d753351aec6f238993ef55f25e/content/src/main/content/jcr_root/apps/acs-commons/components/content/column-control/clientlib/css/colctrl.less

There was an issue to add a generic class to the HTML output: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/154

I believe we can now transfer all the styling (position, border-box, etc etc) to that generic class, instead of putting it on every column. 
We believe only the width should be on the styles per specific column.

Right now, it's giving our designer a headache. :1234:

**Comment by davidjgonzalez** [comment]
Ah yes - agree. It looks anything non-dynamic could be bubbled up to a generic class.

@hkuiyo any way you can make a PR for this (and any other responsive col tickets)

**Comment by davidjgonzalez** [comment]
@hkuiyo it doesnt appear you ever PR'd this back in. Ill close this since Responsive Columns are quasi-irrelevant now in light of AEM Responsive Grid. If you have the fix feel free to PR it though.
