### ISSUE TITLE
Uncaught Error: Components could not be loaded (AEM 6.2, ACS 3.1.0)

### ISSUE THREAD

**Issue by thanhnk** [Adobe-Consulting-Services/acs-aem-commons#727]
Hi ACS team,

After I install the ACS Common 3.1.0 to AEM 6.2, and go to the editor.html page, it show the error follow:

> granite.js:233 GET http://localhost:4502/libs/wcm/core/content/components.1464762778429.html 500 (Server Error)XMLHttpRequest.send @ granite.js:233send @ jquery.js:9659jQuery.extend.ajax @ jquery.js:9210(anonymous function) @ core.js:27245(anonymous function) @ jquery.js:3300fire @ jquery.js:3143self.fireWith @ jquery.js:3255(anonymous function) @ jquery.js:3307fire @ jquery.js:3143self.fireWith @ jquery.js:3255done @ jquery.js:9309callback @ jquery.js:9713
core.js:27272 Uncaught Error: Components could not be loaded

![error](https://cloud.githubusercontent.com/assets/559449/15700476/9b9b9cf2-2806-11e6-93f9-99d22e1e4583.png)

**Comment by umasreey** [comment]
I am receiving the similar error in AEM 6.2.  http://localhost:4502/libs/wcm/core/content/components.1473281136083.html showing 500 error.

core.js:27272 Uncaught Error: Components could not be loaded . 

How to solve this problem?

Thanks
Uma

**Comment by justinedelson** [comment]
I'm not sure this is an ACS AEM Commons issue. Is there anything in the error log file?

**Comment by umasreey** [comment]
Thanks for the reply . I am able to solve it by using other thread.  Its because of the too  many calls. I have updated the "Number of Calls per Request" in sling mail servlet.

**Comment by Gazmit** [comment]
Hi, 

Please can you share the thread. I am facing same issue.

**Comment by Gazmit** [comment]
Hi, Issue is resolved. Servlet is "sling **main** servlet"

**Comment by jatingupta030** [comment]
Hi, I am also facing the same issue. what count you have givem. By default, its 1000

**Comment by karnkumarmphasis** [comment]
Change it to 1200
