### ISSUE TITLE
Deleting an index from Multifieldpanel makes the dialog unresponsive

### ISSUE THREAD

**Issue by anujrattan** [Adobe-Consulting-Services/acs-aem-commons#731]
we are using the very useful widget multifieldpanel in our components. after Authoring the component, the data is saved successfully. But when we try to remove an item (by clicking the '-' button) from the panel, the dialog becomes unresponsive. I am not able to save the changes by clicking the "OK". is it we are doing something wrong ?

We are using ACS-aem-Commons-content-2.5.0.

Thanks for the help

**Comment by anujrattan** [comment]
This behavior happens particularly when there is an RTE in multifieldpanel. Hoping for a response..!! thanks

**Comment by davidjgonzalez** [comment]
in support of deprecated ClassicUI feature
