### ISSUE TITLE
Touch UI Composite Multifield - Tagpicker values saved are not populated in the dialog

### ISSUE THREAD

**Issue by ramyareddyg** [Adobe-Consulting-Services/acs-aem-commons#732]
When tagpicker field is used in the composite multifield(Touch UI), values are saved in CRX. But these values are not populated when the dialog is opened.
Observed this issue on AEM 6.1(with SP1) using ACS Commons v2.5.0.

**Comment by ymahajan-axis41** [comment]
Hi @ramyareddyg, Did you find solution to this issue? I am also facing the same.

**Comment by schoudry** [comment]
@ymahajan-axis41 can you add this logic, test and submit a PR

http://experience-aem.blogspot.com/2016/08/aem-62-touch-ui-nested-composite-multifield-store-data-as-child-nodes.html

```

    function isTagsField($fieldWrapper) {
        return !_.isEmpty($fieldWrapper) && ($fieldWrapper.children(".js-cq-TagsPickerField").length > 0);
    }
 
    function getTagsFieldName($fieldWrapper) {
        return $fieldWrapper.children(".js-cq-TagsPickerField").data("property-path").substr(2);
    }
 
    function getTagObject(tag){
        var tagPath = "/etc/tags/" + tag.replace(":", "/");
        return $.get(tagPath + ".tag.json");
    }
 
    function setTagsField($fieldWrapper, tags) {
        if(_.isEmpty(tags)){
            return;
        }
 
        var cuiTagList = $fieldWrapper.find(".coral-TagList").data("tagList");
 
        _.each(tags, function(tag){
            getTagObject(tag).done(function(data){
                cuiTagList._appendItem( { value: data.tagID, display: data.titlePath} );
            });
        });
    }
```

**Comment by geetika95** [comment]
I am also facing the same issue. Values are getting saved in CRX but not getting populated in the dialog.Moreover, Values that are getting saved in CRX are being clubbed together in a single property. 

![image](https://cloud.githubusercontent.com/assets/10187135/19417213/923c1e1e-93c4-11e6-81c8-612e732c58c9.png)

The **parentTag** property in the screenshot is part of the same multifield, but upon saving values of the two fieldSet from the multifield is getting clubbed together in the single property. See the dialog for reference.

![image](https://cloud.githubusercontent.com/assets/10187135/19417221/c7c58926-93c4-11e6-8132-7609ca6ccfc2.png)


The expectation is to have it part of the same json string. No matter, if I choose the NODE_STORE behavior, the tags are not getting saved correctly. There is no way that I can figure out which tag belongs to which fieldSet.

I Have tried achieving the same using the example given in  http://experience-aem.blogspot.in/2016/08/aem-62-touch-ui-nested-composite-multifield-store-data-as-child-nodes.html

But this works well with tags, if they are part of the nested multifield. If I make the tags property as part of the outer multifield, it only saves one value and ignores the rest of them, Should save all of them. Could you please provide some solution to it?

**Comment by PKAVKR248** [comment]
Hi @geetika95 

Even I have similar problem. Tags works outside multifield. But tags value are not getting saved properly and values do not populate in dialog., when the tag is inside multifield.

Did you find the solution for the same? If yes please provide the solution.

Thanks

**Comment by davidjgonzalez** [comment]
Did this ever get resolved? It sounded like @schoudry provided a fix? did it work? did it get into a PR?
