### ISSUE TITLE
Issue with  host pattern when using different ports for SSL

### ISSUE THREAD

**Issue by kdesineedi** [Adobe-Consulting-Services/acs-aem-commons#733]
Hi Team,

We are using the below ACS feature and found it very useful.
https://adobe-consulting-services.github.io/acs-aem-commons/features/static-reference-rewriter.html

We are currently facing an issue where our dispatcher is configured to use a different port for SSL (9443 instead of 443) and 8888 instead of the standard 80 for non-SSL.

In this case is there a way to specify two host patterns for SSL vs non-SSL in the same configuration?

Regards
Kartheek

**Comment by davidjgonzalez** [comment]
@kdesineedi this feature uses the relative scheme url pattern to handle SSL vs Non-SSL requests. In fact, this implementation is agnostic to the request being HTTP or HTTPS - so long story short, no - this only has a single host pattern and relies on the relative scheme to manage HTTP/HTTPS resource retrieval.

**Comment by justinedelson** [comment]
it's hard to see me this being a generally useful feature. I would suggest just making your own transformer based on the code in this project.
