### ISSUE TITLE
JS error in the page property window

### ISSUE THREAD

**Issue by flashravi** [Adobe-Consulting-Services/acs-aem-commons#734]
Try to access the page properties from the Site view list. The page will load with the following error and it breaks the functionalities of form fields.

TypeError: gAuthor.ui is undefined
 	var dropController = gAuthor.ui.dropController,
 	 
file name:
/apps/acs-commons/touchui-widgets.js

**Comment by justinedelson** [comment]
what version of AEM? what version of ACS AEM Commons?

**Comment by justinedelson** [comment]
I think I committed a fix to fix this.

**Comment by flashravi** [comment]
Awesome. Thanks for the quick fix. We found this issue in AEM 6.1 SP1 & ACS common 2.4.2 & 2.5.0 too.
