### ISSUE TITLE
EmailService to send the attachments

### ISSUE THREAD

**Issue by vivekdhiman** [Adobe-Consulting-Services/acs-aem-commons#742]
Do we have any way out to add the attachment with email send via EmailService?

**Comment by kaushalmall** [comment]
@justinedelson @davidjgonzalez we wrote an EmailServiceWithAttachment service based on the ACS Commons EmailService. If this is needed, we can submit a PR.

**Comment by justinedelson** [comment]
@kaushalmall this is the first I've heard of this requirement, but I'm sure it would be a nice addition. Is a new service necessary or could this be a new method on the existing service?

**Comment by kaushalmall** [comment]
we could add a new method, we have the code, so most of the work is done already.

**Comment by shamalroy** [comment]
I worked with @kaushalmall on this and will submit a PR soon.
