### ISSUE TITLE
Thead Safety issue in FastActionManagerImpl

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#743]
Looking at https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/fam/impl/ActionManagerFactoryImpl.java, there seems to be a few thread safety issues:
* Simultaneous calls to `createTaskManager` could result in the map key collisions.
* The `remove()` call on line 91 could be called while the map's values are being iterated in a different method causing a failure.

I think the simplest approach would be to always generate a unique key for the map (first issue) and use a concurrent map (second issue).

**Comment by badvision** [comment]
Makes sense!  Thanks @justinedelson! 👍

**Comment by badvision** [comment]
There might be one unresolved thread safety issue in the ActionManager class with how it handles its ResourceResolver pool.  What would you say if we changed it to use ThreadLocal and a master resolver, such that if the current thread doesn't have a resolver, or its closed, we just open a new resolver for that thread and keep a list of them solely to support closing them at the end when all the work completes.  

I'm still kind of working on the idea a little but maybe you have some ideas here?
