### ISSUE TITLE
Bulk Workflow Manager- workflowId is null

### ISSUE THREAD

**Issue by gharperhs2** [Adobe-Consulting-Services/acs-aem-commons#749]
Running Bulk Workflow Manager on one particular server generates an error only on one workflow. You click start workflow, it starts, then errors immediately during the first job.

```
05.07.2016 11:48:48.090 *WARN* [pool-7-thread-2] com.adobe.acs.commons.workflow.bulk.impl.BulkWorkflowEngineImpl Could not find workflowId at [ Missing WorkflowId ] to purge.

05.07.2016 11:48:48.110 *ERROR* [pool-7-thread-2] com.adobe.acs.commons.workflow.bulk.impl.BulkWorkflowEngineImpl Error processing periodic execution: {}
java.lang.NullPointerException: Value should not be null (key = workflowId)
    at org.apache.sling.jcr.resource.internal.JcrModifiableValueMap.put(JcrModifiableValueMap.java:446)
    at org.apache.sling.jcr.resource.internal.JcrModifiableValueMap.put(JcrModifiableValueMap.java:47)
    at com.adobe.acs.commons.workflow.bulk.impl.BulkWorkflowEngineImpl.process(BulkWorkflowEngineImpl.java:473)
    at com.adobe.acs.commons.workflow.bulk.impl.BulkWorkflowEngineImpl.access$400(BulkWorkflowEngineImpl.java:71)
    at com.adobe.acs.commons.workflow.bulk.impl.BulkWorkflowEngineImpl$1.run(BulkWorkflowEngineImpl.java:257)
    at org.apache.sling.commons.scheduler.impl.QuartzJobExecutor.execute(QuartzJobExecutor.java:115)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

05.07.2016 11:48:48.113 *INFO* [pool-7-thread-2] com.adobe.acs.commons.workflow.bulk.impl.BulkWorkflowEngineImpl Bulk Workflow Manager stopped for [ /etc/acs-commons/bulk-workflow-manager/update_dam_7_3_911/jcr:content ]
```

Speaking to @davidjgonzalez in chat, he thinks it's a race condition and says he's working on a package of updates he'll include on this ticket. The only odd thing is that we haven't seen this on local or another server, nor even on another job on the same server. Race conditions can be tricky like that so it's possible, just seems odd to be so reliable in such a specific case.

**Comment by davidjgonzalez** [comment]
@gharperhs2  these are AEM 6.1 compat builds that include a revamped impl of BWM.

Can you try them out and see if you see the same issue? In a pinch, you should be able to run the WF as Synthetic WF (now an option). This should be significantly more performant that normal non-transient WF -- naturally the WF's being run have to be compat w Synthetic to begin with.

[acs-aem-commons-content-2.5.1-SNAPSHOT-min.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/350496/acs-aem-commons-content-2.5.1-SNAPSHOT-min.zip)
[acs-aem-commons-content-2.5.1-SNAPSHOT.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/350497/acs-aem-commons-content-2.5.1-SNAPSHOT.zip)

**Comment by gharperhs2** [comment]
We're doing an assessment on deploying the package, devops types are having a powwow to avoid a custom package if we can help it. It turns out the AEM instance we're looking at also won't manually kick off a single workflow instance for out-of-the-box processes, so we may need to resolve that first before we can come back to this. Right now it looks like we'll pursue that avenue before we have sufficient blame to attempt this package. I will update regardless of resolution.

**Comment by davidjgonzalez** [comment]
@gharperhs2 thanks! yes - if you cant kick off a WF normally, then i expect you have some other more serious problems that could be contributing to the effects you're seeing in in BWM. If these other issues are at play, i doubt this package will resolve anything outside of using it to process w Synthetic WF - but you'd still have a broken instance, just one w processed assets so there's dubious value in that ;)

**Comment by gharperhs2** [comment]
@davidjgonzalez Agree 100%. If it's okay I'll leave this ticket open until we can troubleshoot the single workflow issue w/ Adobe and guarantee there isn't a further issue here. If not can reopen/recreate later, no problem either way.

**Comment by davidjgonzalez** [comment]
No problem - thanks!

**Comment by gharperhs2** [comment]
@davidjgonzalez We have a meeting w/ Adobe this morning, so I should have an answer for you by EOD.

**Comment by gharperhs2** [comment]
...and our Adobe contact fixed one part but broke another, pushing hard to get a final answer.

**Comment by gharperhs2** [comment]
Looks like our issues were solved once Adobe fixed the server issues, so I'll have to close this. If there is a race condition we're not hitting it anymore and that's sufficient. Thanks.

**Comment by davidjgonzalez** [comment]
Any chance you can give a general overview of what the problem stemmed from? Curious as someone else reporter similes at symptoms and I'm stumped as to what might be causing it outside some esoteric bug.

**Comment by gharperhs2** [comment]
We were starting to do the csv-asset-import on a client server and kept having to toggle relevant workflows on and off so the client authors could keep working. A couple times we mixed up the process and csv-asset-import was overloading the server, so we had to nuke workflows to reset everything. The command we came up with while under fire deleted the root node for workflows when it should have removed just the instances under (/etc/workflow/instances). Restarting the server recreated the root node, but without the proper configs. Recreating a proper root node fixed our issue.

**Comment by davidjgonzalez** [comment]
@gharperhs2 ah cool. BTW - ACS Commons has Workflow Remover which is a really handy tool for ad-hoc nuking of Workflow instances at scale. There are a number of parameters you can specify as well to only delete instances you (don't) care about.
