### ISSUE TITLE
The draggable list doesn't work for than 15 items in the list.

### ISSUE THREAD

**Issue by SuperAnkit** [Adobe-Consulting-Services/acs-aem-commons#751]

**Comment by davidjgonzalez** [comment]
@SuperAnkit can you provide a package that reproduces this behavior w the target AEM 6 version (and any FP's/ HF's applied). It sounds like on gitter, @kaushalmall was unable to reproduce.

**Comment by SuperAnkit** [comment]
The issue was with the height being set in the js, if the height is removed it works fine.

**Comment by kaushalmall** [comment]
@SuperAnkit can you please describe the issue and submit a PR for the fix?

**Comment by davidjgonzalez** [comment]
Thanks @SuperAnkit
