### ISSUE TITLE
Ensure oak index shouldn't wipe all properties at index-def node

### ISSUE THREAD

**Issue by catholicon** [Adobe-Consulting-Services/acs-aem-commons#763]
There are a few properties [IGNORE_PROPERTIES](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/oak/impl/EnsureOakIndexJobHandler.java#L84) which are currently used to identify if an index definition requires update or not.

BUT, when applying actual update, all props (apart from `jcr:primaryType`) from this list is wiped out.

Properties that are not factored while figuring out "something has changed" shouldn't be updated as well.

Note: removing reindexCount leads to [OAK-3629](https://issues.apache.org/jira/browse/OAK-3629)

**Comment by catholicon** [comment]
While discussing on gitter, @davidjgonzalez suggested that may be we should have 2 lists - 1 to ignore props to detect update and another to ignore actual updates. He also suggested that these should probably be backed by Osgi conf.

To me, it seems that there should be a single list (Osgi backed though). Actually, I think there should be 2 lists - 1 hard-coded to have system props like primaryType, lastModified, etc.. the other (Osgi configurable) which is more specific to index ops (reindex, reindexCount etc). Union of both these list should be used to figure out "if updated" and "whether to update"

**Comment by davidjgonzalez** [comment]
@catholicon in the case of 1 list, then we will NOT remove 

- JcrConstants.JCR_LASTMODIFIED,
- JcrConstants.JCR_LAST_MODIFIED_BY,
- JcrConstants.JCR_MIXINTYPES,
- JcrConstants.JCR_CREATED,
- JcrConstants.JCR_CREATED_BY,

I can see the last 3 being "permanent" (dont remove them), but none of those should have a impact if the index should be viewed as different or not. WDYT?

**Comment by catholicon** [comment]
> Regardless it seems lastModified and lastModifiedBy should not be their previous values since EnsureOakIndex modifies them if it determines a delta.
Good point. I agree, it makes sense to have some props not participate in "if changed", but indeed get changed eventually.

So,
* `primaryType`, `created`, `mixinTypes`, `createdBy` remain as sacrosanct (don't consider and don't update) - hard-coded(??)
* `lastModified`, `lastModifiedBy` don't get considered to check if update is needed... but are updated (and hence ok to be wiped) - hard-coded(??)
* others - don't check and don't touch - osgi conf based (??)

@davidjgonzalez sounds good?

**Comment by davidjgonzalez** [comment]
Sounds good! I cant recall if JCR will auto-set lastModified and lastModifiedBy values when the handler writes; i want to say it doesnt? we could take this opportunity and write them ourselves so its very clear when and who (ensure index) touched these defs.

[EnsureOakIndexManagerImpl](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/oak/impl/EnsureOakIndexManagerImpl.java)  looks like the logical place to associate this "global" property list.

**Comment by davidjgonzalez** [comment]
@catholicon btw - you gonna work on this? :)

**Comment by davidjgonzalez** [comment]
@catholicon no worries - let me take a stab and see if i can get it done after work today, and then cut a bug fix release over the weekend for Monday.

**Comment by catholicon** [comment]
> I cant recall if JCR will auto-set lastModified and lastModifiedBy values when the handler writes; i want to say it doesnt?

You're right, jcr won't do it automatically.

> let me take a stab and see if i can get it done after work today, and then cut a bug fix release over the weekend for Monday.

Thanks :)
