### ISSUE TITLE
Versioned Clientlibs is not HTML compliant when checking isCSS/isJavascript

### ISSUE THREAD

**Issue by wolfpl** [Adobe-Consulting-Services/acs-aem-commons#764]
The logic in both isCSS and IsJavascript is faulty; it checks for the presence of the type attribiute for script and link tags,  but fail to obey the contract that HTML sets for them: specifically, they do not allow a tags with default values.

This means that any compression of HTML (which commonly will omit the default values in type, as explicitly permitted in HTML standard) will cause versioned-clientlibs to fail to apply.

The code really should be refactored to allow missing attributes for type and also allow default values:

https://www.w3.org/TR/html5/scripting-1.html#attr-script-type
The type attribute gives the language of the script or format of the data. If the attribute is present, its value must be a valid MIME type. The charset parameter must not be specified. The default, which is used if the attribute is absent, is "text/javascript".

https://www.w3.org/TR/html5/document-metadata.html#attr-link-type
For external resource links, the type attribute is used as a hint to user agents so that they can avoid fetching resources they do not support. If the attribute is present, then the user agent must assume that the resource is of the given type (even if that is not a valid MIME type, e.g. the empty string). If the attribute is omitted, but the external resource link type has a default type defined, then the user agent must assume that the resource is of that type.

As a side note, this did not seem to happen for us in 6.1, but with 6.2 the compression filter appears earlier in the process and thus fails.

**Comment by davidjgonzalez** [comment]
Agree - would you like to make a pr? I'd like to cut a bug fix build this weekend for an issue w ensure oak index and would be great to get this in.

**Comment by justinedelson** [comment]
While I'm by no means opposed to this change and would welcome a PR, I am a little confused about this issue. The HTML we're looking at isn't arbitrary HTML; it is the HTML output by the AEM Client Library Manager. And that is always including the `type` attribute in version 6.2 (and IIRC every prior version for the past 5 years).

**Comment by davidjgonzalez** [comment]
@wolfpl which "compression filter" do you mean?

> As a side note, this did not seem to happen for us in 6.1, but with 6.2 the compression filter appears earlier in the process and thus fails. 

Initially read this on phone while waking up :) - at second glance it seems strange what compression filter would effect the HTML. The CL's themselves have the gzip/minify options but those are on the CSS/JS resources themselves, not the html that version client libs run on.

Either way - it seems a nice thing to do for general correctness, but to @justinedelson's point it may not solve whatever issue youre running into.

**Comment by justinedelson** [comment]
closing due to lack of interest
