### ISSUE TITLE
Ensure oak index while updating an index defnition doesn't copy over property types

### ISSUE THREAD

**Issue by catholicon** [Adobe-Consulting-Services/acs-aem-commons#768]
The title of the issue is a little vague, so let me mention a concrete example. If `nodetype` index is updated by ensure oak index then `declaringNodeTypes` and `propertyNames` properties in updated index definition get type `String[]` even though even the source information (ensure oak index index templates) had `Name[]`. This leads to `nodetype` getting ignore by Oak.

/cc @davidjgonzalez

**Comment by catholicon** [comment]
Fwiw, opened [OAK-4636](https://issues.apache.org/jira/browse/OAK-4636) so that oak can be more resilient or avoid such situations. In either case, this issue should still be fixed imho.

**Comment by davidjgonzalez** [comment]
By Node[] you mean Name[]?

Bascislly the copy operation is normalizing ensure definition Name property types to Strings? Agree should be fixed here. Strange this is first notice of it. I expect it has something to do w use of value maps to quickly move the properties over.

**Comment by davidjgonzalez** [comment]
[acs-aem-commons-content-2.6.5-SNAPSHOT-min.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/400559/acs-aem-commons-content-2.6.5-SNAPSHOT-min.zip)
[acs-aem-commons-content-2.6.5-SNAPSHOT.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/400560/acs-aem-commons-content-2.6.5-SNAPSHOT.zip)

**Comment by davidjgonzalez** [comment]
Fixed
