### ISSUE TITLE
RTE don't store content in the page properties

### ISSUE THREAD

**Issue by flashravi** [Adobe-Consulting-Services/acs-aem-commons#774]
I'm using the RTE field in the page properties and it doesn't store the value that I enter in the field. The issue is that the form field post the content from the Input field and this Input field listens to the actual RTE editable field. But, the input field is not updated with the new content we enter and it is failing to store the data in the CRX. 

Here is my node structure for RTE looks like
`<teaserTitle
	jcr:primaryType="nt:unstructured"
	sling:resourceType="cq/gui/components/authoring/dialog/richtext"
	charcount="true"
	hideLabel="{Boolean}false"
	useFixedInlineToolbar="{Boolean}true"
	title="Teaser Title"
	name="./teaserTitle"
	fieldLabel="Teaser Title"
	fieldDescription="Text displayed when a user hovers over the description"
	value=""
	emptyText="Teaser Title"
	disabled="false"
	required="false"
    rteheight="2.8rem"
	renderReadOnly="{Boolean}true"
	pagePropertyListener="true"
	cq-msm-lockable="teaserTitle"
	cq:showOnCreate="{Boolean}true">
	<htmlRules
		jcr:primaryType="nt:unstructured">
		<blockHandling
			jcr:primaryType="nt:unstructured"
			removeSingleParagraphContainer="{Boolean}true"/>
	</htmlRules>
	<rtePlugins jcr:primaryType="nt:unstructured">
		<format
			jcr:primaryType="nt:unstructured"
			features="*"/>
		<justify
			jcr:primaryType="nt:unstructured"
			features="*"/>
		<subsuperscript
			jcr:primaryType="nt:unstructured"
			features="*"/>
		<edit
            jcr:primaryType="nt:unstructured"
            features="[paste-wordhtml]"
            stripHtmlTags="{Boolean}true"/>
	</rtePlugins>
	<uiSettings jcr:primaryType="nt:unstructured">
		<cui jcr:primaryType="nt:unstructured">
			<inline
				jcr:primaryType="nt:unstructured"
				toolbar="[#format,subsuperscript#subscript,subsuperscript#superscript,-,links#modifylink,links#unlink,#justify,edit#paste-wordhtml,-,fullscreen#start,-,control#close]">
				<popovers jcr:primaryType="nt:unstructured">
					<format
						jcr:primaryType="nt:unstructured"
						icon="text"
						items="[format#bold,format#italic,format#underline]"
						ref="format"/>
					<justify
						jcr:primaryType="nt:unstructured"
						icon="text"
						items="[justify#justifyleft,justify#justifycenter,justify#justifyright]"
						ref="justify"/>
				</popovers>
			</inline>
			<fullscreen
				jcr:primaryType="nt:unstructured"
				toolbar="[format#bold,format#italic,format#underline,subsuperscript#subscript,subsuperscript#superscript,links#modifylink,links#unlink,links#anchor,tracklinks#modifylinktracking,-,fullscreen#finish]">
			</fullscreen>
		</cui>
	</uiSettings>
</teaserTitle>`

**Comment by justinedelson** [comment]
How is this related to ACS AEM Commons?

**Comment by flashravi** [comment]
I apologize for raising this issue. This seems to be AEM bug and not acs common. I initially thought it came up after installing the acs-common.
