### ISSUE TITLE
Occasional (but important) "Maximum call stack size exceeded" when using Composite Multifield

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#779]
In some, hard to reproduce scenarios, the Composite Multifield fails to initialize and the message "Maximum call stack size exceeded" is logged. This seems to be caused by multiple loads of the client library, which should never happen under normal circumstances.

**Comment by MuriloDAG** [comment]
@justinedelson had same issue when using [IncludeClientlibs](https://docs.adobe.com/docs/en/aem/6-1/ref/granite-ui/api/jcr_root/libs/granite/ui/components/foundation/includeclientlibs/index.html)

**Comment by awaismalik82** [comment]
Does anyone know if ACS has officially released a new version of the library with this fix?

**Comment by kaushalmall** [comment]
@justinedelson has fixed this, but I don't think the new dependency has been posted to the public Adobe repository yet. You can get the latest code from GH and build locally or Justin can send you a link to the package.

**Comment by justinedelson** [comment]
The 2.6.10 (for 6.0 and 6.1) and 3.2.12 (for 6.2) releases have this fix and are available from GitHub Releases and repo.adobe.com.

**Comment by awaismalik82** [comment]
thanks guys! appreciate the help.

**Comment by AnishKhanna** [comment]
@awaismalik82 - I have created the issue for  this. Below is the path
https://github.com/AnishKhanna/Code-Issues/issues/1
