### ISSUE TITLE
Named Transform Image Servlet: cropping issue

### ISSUE THREAD

**Issue by chunshengluo** [Adobe-Consulting-Services/acs-aem-commons#780]
We use this capability for adaptive images. There is one issue when we crop the images with cropConfig settings from the classic dialog. It worked OK on the author. There is an issue after activation to publishers. The error is pasted below. I have not checked the servlet code. Any thoughts?

20.08.2016 01:12:45.570 *ERROR* [50.59.141.27 [1471669965382] GET /content/icop/ico/home/locations/orange-county/irvine-spectrum/alton-corporate-center/_jcr_content/mainParsys/section_container_1386025988/width-container/containerwidth/new_mondrian/grid/rollover_element_1053832790/image/large.transform/mondrianSquareLarge/image.jpg HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught SlingException
java.awt.image.RasterFormatException: (x + width) is outside of Raster
	at sun.awt.image.ByteInterleavedRaster.createWritableChild(ByteInterleavedRaster.java:1245)
	at java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1203)
	at com.day.image.Layer.crop(Layer.java:1569)
	at com.day.cq.commons.ImageResource.crop(ImageResource.java:553)
	at com.adobe.acs.commons.images.impl.NamedTransformImageServlet.getLayer(NamedTransformImageServlet.java:423)
	at com.adobe.acs.commons.images.impl.NamedTransformImageServlet.doGet(NamedTransformImageServlet.java:214)
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:269)

**Comment by davidjgonzalez** [comment]
are you sure the image on author has been replicated to publish? Download the image from publish that the dimensions support the crop coordinates.

**Comment by chunshengluo** [comment]
That is an interesting question. There was no 404, the image without manual cropping from the dialog box will always render from the publisher, I always activate the page before viewing from the publisher, and the image seems saved to the page node. That was why I did not think of replication issues. But will check. Thanks for your response, David.

**Comment by chunshengluo** [comment]
Just checked the image replication. Yes. The image fileReference URL is tested as a valid full image. I tested the replicated images by prefixing with the domain. The issue is when there is imageCrop property. The error occurs. One example of the imageCrop from CRXDE Lite:
imageCrop String 1314,284,2914,1884/1,1

**Comment by chunshengluo** [comment]
I also tested the latest acs 2.6.8 for my aem6.1 with sp1. The next step for me is to pull the source to figure out the issue when I am back to work next week.

**Comment by justinedelson** [comment]
So this error suggests that the cropping was done on author with a larger image than is present on publish. In other words, the image is present on publish, but the image isn't the same one. You should get this same exception when just using the regular image servlet.

**Comment by chunshengluo** [comment]
It is the cropping applied to the original image in the DAM. The rendition is based on the cropping coordinates and the ACS named image transformation. What is puzzling is that the author instance can handle it just fine. The publish however generates the error I pasted above.  

As for your question an image cropped with the regular out of the box image component which does not use the ACS named image transformation will render fine by both author and publisher. The main difference is the ACS named image transformation. I think the ACS image transformation servlet is likely causing the issue.

**Comment by davidjgonzalez** [comment]
Jcje

**Comment by davidjgonzalez** [comment]
@chunshengluo I expect its the cropping applied to the cq5dam.web rendition in the DAM (not the original) -- that is the OOTB behavior. The fact that it works on AEM Author and NOT on Publish really points to there being a delta between the environments. Named Image Transform doesn't have logic to detect Author vs. Pub and act differently.

Can you CQ package up, per environment (1 set for author, 1 set for publish) and attach to this ticket (or email direct to davidjgonzalez@gmail.com if you cannot share publicly)

1) The dam:Asset content tree for the image youre referencing 
2) The page you with the image component w the crop params
3) The named transform OSGi config(s) you are using for this image

My guess is one of those 3 things is not the same between your author and publish (try replicating each one, and checking)

**Comment by chunshengluo** [comment]
David, I think you brought up a couple of important points on the no detection of author vs. publisher and renditions. I will look into the activation of all renditions. I am only sure that the original is activated.

**Comment by chunshengluo** [comment]
Dave, We have figured out the issue. There were two causes that are hard explain here. I will close the issue.
