### ISSUE TITLE
Checkboxes doesn't work in multifield with both classic and touch ui

### ISSUE THREAD

**Issue by murilodag** [Adobe-Consulting-Services/acs-aem-commons#782]
We are trying to have a dialog with a checkbox inside the multifield.
**Is there a way to do it so touch and classic can save/retrieve values correctly?**

In the attached zip, there are dialogs for both classic and touch ui, inside and outside the multifield.
The dialogs are using both xtype=checkbox and xtype selection/type=checkbox, but neither of them works.
When we update the values in the classic, the touch ui cannot retrieve correctly.
Classic is always consistent, the problem only occurs in the touch.

[checkbox_inside_multifield.zip.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/430502/checkbox_inside_multifield.zip.zip)

**Comment by RodrigoNascCarvalho** [comment]
We are currently having the same problem in one of our projects, does anyone know a fix for this issue?

**Comment by viveksachdeva** [comment]
@murilodag , @RodrigoNascCarvalho  : Could you check the values that are being stored on the content node and add that information here...
I am using following configuration:
For classic:
xtype = " selection" and type="checkbox"

For touch:
sling:resourceType = "granite/ui/components/foundation/form/checkbox"
value = "true"

Checkbox added in one is reflected in other also..

**Comment by rubnig** [comment]
You can get the same result with a select for now by adding two options two it.

- Touch UI: **sling:resourceType="granite/ui/components/foundation/form/select"* 
- Classic UI: ** type="select" xtype="selection"**

**Comment by aanchalsikka** [comment]
For Touch UI, specify a value field for the checkbox. The value will now be persisted on selecting the checkbox as "persistent_property_name=some_value". On reopening the checkboxes the value should be retained.

<field_name
jcr:primaryType="nt:unstructured"
sling:resourceType="granite/ui/components/foundation/form/checkbox"
name="./persistent_property_name"
text="Field_Label"
value="some_value">

**Comment by RashidJorvee** [comment]
We are also facing the same problem, is there any solution form this?
