### ISSUE TITLE
Dismissable System Notifications redisplayed after visiting Admin page IE 11

### ISSUE THREAD

**Issue by notizklotz** [Adobe-Consulting-Services/acs-aem-commons#783]
Tested on a vanilla AEM 6.1 SP1 instance with ACS AEM Commons 2.6.10:

With IE 11:
1. Start AEM with SP1, ACS Commons and Geometrixx installed
2. Create a dismissable System Notification
3. Visit http://localhost:4502/sites.html. Notification is shown -> Dismiss
4. Open a content page like http://localhost:4502/editor.html/content/geometrixx/en/products.html Notification is shown -> Dismiss
5. Return to the admin page. Notification is shown -> Dismiss

- The same happens using Classic UI.
- With Chrome and Firefox the problem does not occur.

I struggle to debug the issue becuase of the poor Developer Tools in IE but I think the cookie to remember the dismissed notficiations is not set in IE 11.

**Comment by brigham57** [comment]
Also reproduced in IE 11 on Windows 10 with AEM 6.0 SP3.

**Comment by davidjgonzalez** [comment]
@brigham57 - Can you try this out, by running this code directly in the IE11 JS console?

```
var name = 'acs-commons-system-notifications';
var value = '1234-1234-1234-1234';
document.cookie = name + '=' + value + '; expires=0; path=/;';
```

Can you check if there are any errors or if the cookie is/isn't set?

**Comment by brigham57** [comment]
@davidjgonzalez 
Thanks for the assistance.

I have tried all the suggested settings in the links with no success.

Running the code in the IE11 JS console produces the following output:
"acs-commons-system-notifications=1234-1234-1234-1234; expires=0; path=/;"

IE version is IE 11.545.10586.0.

All tests performed against Geometrixx.

**Comment by davidjgonzalez** [comment]
@brigham did you adjust the IE protected modes settings?

**Comment by brigham57** [comment]
@davidjgonzalez 

IE protected mode is disabled.
AEM is set to be a trusted site with a low security level.
As mentioned by notizklotz, this only affects IE, Chrome & Firefox are not affected.

Thanks

**Comment by davidjgonzalez** [comment]
This sounds like a IE bug.. I don't have Windows so it's difficult to test ie11.
Can you provide a js snippet that uses document.cookie to create a cookie that works in IE11?

Thanks

**Comment by notizklotz** [comment]
I just discovered that the problem ist the "expires" part.

If I have a look at the documentation at https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie then "0" is not a valid value for "expires". Expires must be a valid date expression. As IE11 apparently doesn't understand "max-age" I think the cookie should always be set using an "expires" statement with a specific date, which seems to be the most portable approach.

Here are the results of my experiments:

- No cookie in IE 11: 
document.cookie = 'acs-commons-system-notifications=1234-1234-1234-1234; expires=0; path=/;'

- Creates a session cookie in IE 11 (max-age is ignored)
document.cookie = 'acs-commons-system-notifications=1234-1234-1234-1234; max-age=120; path=/;'

- Works correctly (cookie survives session):
document.cookie = 'acs-commons-system-notifications=1234-1234-1234-1234; expires=Mon, 6 Mar 2017 12:00:00 UTC; path=/;'

**Comment by davidjgonzalez** [comment]
@notizklotz thanks for troubleshooting this - feel free to make a PR w fix if you feel so inclined else I'll do it but probably won't have time till Thursday. Just drop a comment in if you pick it up and I'll do the same if I do

Thanks again!

**Comment by notizklotz** [comment]
Thanks for fixing this!

**Comment by brigham57** [comment]
Thanks from me as well!
