### ISSUE TITLE
When trying to open touch ui component focus is on RTE

### ISSUE THREAD

**Issue by sukesh1** [Adobe-Consulting-Services/acs-aem-commons#785]
When i am trying to open a component which contains RTE, focus is directly going on RTE. i have one scenario where RTE is at positioned at last but when i am trying to open the component focus is directly jumping to RTE.

**Comment by justinedelson** [comment]
How does this relate to ACS AEM Commons?

**Comment by davidjgonzalez** [comment]
Closing as does not appear pertain to ACS AEM Commons.

**Comment by rohan-pulekar** [comment]
you can use   useFixedInlineToolbar="{Boolean}false"
in the 'cq/gui/components/authoring/dialog/richtext'  element definition.
That will make sure that focus does not go to the RTE field when dialog is opened.  But the dropback is that the RTE options will be shown only when user takes cursor to the RTE field.

**Comment by Rampai94** [comment]
@rohan-pulekar,
If we use useFixedInlineToolbar="{Boolean}false", then the RTE plugins start moving up and down along with scroll which blocks the editing. Please share how to fix this issue if anyone is aware of the same.
