### ISSUE TITLE
Touch UI nested JSON Store format does not match Classic UI multifieldpanel format

### ISSUE THREAD

**Issue by cameronoxley** [Adobe-Consulting-Services/acs-aem-commons#786]
The output format from the Touch UI nested Multifield saves JSON data as a JSONObject, whereas the second level of a nested Classic UI saves as an encoded string.
See Issue: #380

**Comment by paul-bjorkstrand** [comment]
@cameronoxley does my description [here](https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/380#issuecomment-257699070) describe the problem you reported in this ticket?

**Comment by cameronoxley** [comment]
@paul-bjorkstrand Yes, perfectly. Happy to close this in favor.
