### ISSUE TITLE
Selective version purging

### ISSUE THREAD

**Issue by jbenn313** [Adobe-Consulting-Services/acs-aem-commons#793]
Out-of-the-box version management policy is, for the most part, applied the same way throughout the entire repository.  Maximum number of versions and maximum version age can be specified, but these settings apply to all versionable nodes in the repository.  

In some situations it would be advantageous to apply version management policies more selectively.  For example, subasset versioning could be eliminated altogether.  If many subassets are derived from one "master" asset, these subassets are immutable, and the subassets can be re-generated from the master asset by re-ingesting it; then maintaining subasset versions is entirely unnecessary.  This issue was raised by a customer for which 50 subassets are typically created for each master asset.  The master asset undergoes many revisions before it is finalized. On each revision 50 subassets are modified and 50 renditions are created.  This customer's AEM instance is heavy with unneeded renditions. They believe that more than half of their 15 TB repo is consumed by subasset versions.

To address this issue I propose to do the following:
- create a workflow step that applies the standard max versions and max age version policy to the workflow payload.  This, in combination with the Bulk Workflow Manager, makes it possible to purge renditions precisely as needed for a set of nodes that is selected in a query statement.  
- create a utility that enables a system administrator to preview what versions will be purged given a query statement and max age, max number version purge settings.

**Comment by davidjgonzalez** [comment]
@jbenn313 

1) Do you see any benefit in having this a Workflow Process other than allowing it to leverage the Bulk Workflow Manager tooling (preferably some Synthetic WF type; serial or FAM)? Do you see this being added as part of a "normal" WF (ex. XMP Writeback, DAM Asset Update, etc.)

2) Wrt to the 2nd bullet; what do you mean by "preview" the versions purged? Would these previews just be 

* Asset path
* Version label
* Version date

Im having a hard time envisioning what the preview UI would look like for any meaningful scale (or should this be a CSV to load into Excel, etc.?)

**Comment by jbenn313** [comment]
1)       No, the only reason for this to be a Workflow Process is to enable it to be used within the context of existing Workflow-related tooling.  This way we can drive version cleanup using Bulk Workflow Manager.  We can throttle the work, make it lightweight, and keep a history work done if we want to.  No, I do not envision this Workflow Process being used in any “normal” workflow model.

2)       Regarding the second bullet, I envision a utility that provides output similar to the following:

Inputs were:

-          Query type: xPath

-          Query: <the query string>

-          maxAge: 7 days

-          maxVersions: 2 versions

Results:
/content/dam/…/asset1.jpg
    version: root
          created: 2016-01-01 09:34:56
          disposition: purge
   version: 1.0
          created: 2016-02-23 19:34:56
          disposition: purge
    version: 2.0
          created: 2016-03-05 04:34:56
          disposition: retain
    version: 3.0
          created: 2016-03-06 11:34:56
          disposition: retain

/content/dam/…/asset2.jpg
    version: 6.0
          created: 2016-09-12 06:34:56
          disposition: retain
   version: 7.0
          created: 2016-09-13 08:34:56
          disposition: retain
   version: 8.0
          created: 2016-09-14 09:34:56
          disposition: retain

/content/dam/…/asset3.jpg
    … and so on …

The purpose of this is to clearly visualize for the user what versions will be purged with a given set of inputs.  I have found that the disposition results are often not what one would intuitively expect.

The data shown is the result of a Version Manager dry run.  No repository change is made as a result of using this utility.  This gives the user the ability to tweak the inputs and confirm expected results before making any changes to the repository.

After the user confirms the correct inputs they would 1) set up a workflow model with the Version Purge workflow process.  maxAge, maxVersions, and isDryRun are specified as process parameters.  2) Use Bulk Workflow Manager to push assets through the workflow.

I have in mind to implement this following the pattern of the existing Version Compare utility, with some UI elements borrowed from the Bulk workflow manager.  The Version Purge utility would appear with the ACS AEM Commons tools.  It would take as input Query Type, Query String, Version maxAge (in days), and Max Versions.  Output would be a size-limited list of assets, their versions, and disposition for each version, given the inputs, as shown in the example above. If someone wants more version disposition data than the utility provides they can get it from a servlet endpoint.  Originally I was thinking that the servlet would return json but I like your suggestion of CSV.  That would probably be more useful for this purpose.

**Comment by jbenn313** [comment]
@davidjgonzalez 

What is the protocol here?  Should I wait for a "green light" from you before doing this work?  Should I get more feedback from the community before going ahead?

Do you think that this would be a worthwhile addition to the toolkit?

Thank you.

**Comment by davidjgonzalez** [comment]
@jbenn313 I think it's a good idea. I'm not the sure reporting jives w the put existing WF functionality though- it might make sense/be simpler to create a new util pge whose express Purpose is doing this (along w dry run) - bulk workflow manager is already too complex to try to include dry run / reporting.

Think having a version purge on steroids is a great idea though
