### ISSUE TITLE
upgrading acs-aem-commons-content version from 1.10.2 to 3.3.0

### ISSUE THREAD

**Issue by jaiwaikhom** [Adobe-Consulting-Services/acs-aem-commons#795]
We are in a process of upgrading AEM 5.6.1 to 6.2. Along with that we are also upgrading acs-aem-commons package to 3.3.0 from 1.10.2. We are using many of the widgets provided by acs-aem-commons. After the upgrade the page does not even loads. Please let me know if there is a roadmap for this upgrage?

**Comment by justinedelson** [comment]
Version 3.3.0 works with AEM 6.2

**Comment by justinedelson** [comment]
Closing this issue as it is extremely vague and unqualified. Please create an issue which describes in detail the specific problem you are having and includes steps to reproduce.

**Comment by jaiwaikhom** [comment]
I could see an error while rebuilding the clientlib 

building /etc/clientlibs/acs-commons/vendor/angularjs/v1.3/modules/ng-storage.min.js...error: java.io.IOException: Error while reading cached library: javax.jcr.RepositoryException: Error during assembly of /etc/clientlibs/acs-commons/vendor/angularjs/v1.3/modules/ng-storage.js

**Comment by justinedelson** [comment]
As I said, please create a new issue with the steps to reproduce.
