### ISSUE TITLE
Error rebuilding clientlib with asc-aem-commons 3.3.0 with AEM6.2

### ISSUE THREAD

**Issue by jaiwaikhom** [Adobe-Consulting-Services/acs-aem-commons#796]
I am using acs commons version 3.3.0 with AEM6.2. while trying to rebuild clientlib using the URL http://localhost:4502/libs/granite/ui/content/dumplibs.rebuild.html?rebuild=true
I get 2 errors as follows. please suggest how i can fix it.

1.
building /apps/acs-commons/components/utilities/quickly/clientlibs.min.js...error: java.io.IOException: Error while reading cached library: javax.jcr.RepositoryException: Error during assembly of /apps/acs-commons/components/utilities/quickly/clientlibs.js

2.
building /etc/clientlibs/acs-commons/vendor/angularjs/v1.3/modules/ng-storage.min.js...error: java.io.IOException: Error while reading cached library: javax.jcr.RepositoryException: Error during assembly of /etc/clientlibs/acs-commons/vendor/angularjs/v1.3/modules/ng-storage.js

**Comment by justinedelson** [comment]
thanks for identifying this. it is fixed now.
