### ISSUE TITLE
Getting ConfigurationManager in dtm component

### ISSUE THREAD

**Issue by fedorprokhorenko** [Adobe-Consulting-Services/acs-aem-commons#797]
There are come deprecated code fragments in dtm component (https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/master/content/src/main/content/jcr_root/apps/acs-commons/components/utilities/dtm) JSPs headlibs.jsp and dtm.jsp for AEM 6.2 version. ConfigurationManager is obtained in the following way:
`ConfigurationManager cfgMgr = sling.getService(ConfigurationManager.class);`
and cfgMgr is always null in AEM 6.2 (I believe in 6.1 as well, but we tested on 6.2)

The code for 6.2 should be like this:
`ConfigurationManagerFactory factory = sling.getService(ConfigurationManagerFactory.class);
 ConfigurationManager cfgMgr = factory.getConfigurationManager(slingRequest.getResourceResolver());`

**Comment by justinedelson** [comment]
You should not use the DTM components in AEM 6.2 (or any version greater than 6.0) and instead use the OOTB components.

**Comment by fedorprokhorenko** [comment]
What do you mean by OOTB components?

**Comment by justinedelson** [comment]
https://docs.adobe.com/docs/en/aem/6-2/administer/integration/marketing-cloud/dtm.html

**Comment by sathish-git** [comment]
Hi @justinedelson , Can't we add a fix for this? There are still some people using the DTM integrations. It's an easy fix and wouldn't really impact anything. I wonder if DTM itself is deprecated, why do we still even have the option in AEM?
