### ISSUE TITLE
Issue with Cache-Control response header when Cache-Control request header is set 

### ISSUE THREAD

**Issue by coatpont** [Adobe-Consulting-Services/acs-aem-commons#798]
This issue relates to the Cache-Control filter for support Dispatcher TTLs. 

It is unclear why the ACS filter does NOT return a Cache-Control response header, if it sees one in the request [1]. Looking at the HTTP 1.1 specification [2], the client is simply asking for a response that has at most that age. The specification says:
 
[…] If both the new request and the cached entry include "max-age" directives, then the lesser of the two values is used for determining the freshness of the cached entry for that request. […]
 
Therefore the filter should still return max-age in the response.

The current behavior might result in "stale" content on the dispatcher, never honoring the configured TTL, if the very first request comes in with a Cache-Control max-age value for instance.

[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/http/headers/impl/DispatcherMaxAgeHeaderFilter.java#L84
[2] https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by justinedelson** [comment]
@bstopp can you take a look at this?

**Comment by bstopp** [comment]
Sure. I missed that excerpt when designing this; so i'll remove the header check and always return the max-age.

But I suppose there's another question: Should we remove the check that the request is from the Dispatcher, treating the dispatcher as a _Shared Cache_ specifically (therefore using the _s-maxage_ directive [1]) or both?

Removing the dispatcher check would allow the value to be returned for every request. Changing the directive to _s-maxage_ should prevent browser caching while still caching content at the Dispatcher and CDNs. This assumes that the Dispatcher is designed to honor that _Cache-Control_ directive.

Thoughts?

[1]https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.3

**Comment by justinedelson** [comment]
I'd suggest leaving the Dispatcher check in place. At least for now. I would, however, suggest that we clearly document that this only fires if a request comes via the Dispatcher and maybe even provide a sample curl command to pass the header required to "trick" the filter into thinking it is coming from the Dispatcher (as that would be useful for testing purposes)

**Comment by bstopp** [comment]
On it.

**Comment by coatpont** [comment]
+1 thanks for the quick turnaround. Note that the max-age returned should be the lesser of the two values though (request / response)

**Comment by dominique-pfister** [comment]
@coatpont : Not sure about that. Looking at the relevant HTTP specification, it says:
> then the lesser of the two values is used.

So, it's okay for the filter to e.g. return "max-age=60", although the client sent "max-age=15"

**Comment by coatpont** [comment]
ok, then I'm wrongly interpreting what the "lesser of the two values" means.

**Comment by dominique-pfister** [comment]
I think, it means the *client* will use the lesser of the two values, not the cache when sending its response.

**Comment by davidjgonzalez** [comment]
I read it same as @dominique-pfister - the client uses the lesser values (the request max-age and the response max-age) to determine the freshness (or staleness) of the response, and then acts accordingly. 

IIUC, if a client could change the max-age written to the response by AEM, then a client could dictate how dispatcher caches requests for all other clients.

**Comment by bstopp** [comment]
See David's response; that's how I read it too. The excerpt is taken from the context of how the _cache_ must handle the processing of conflicting headers.

**Comment by davidjgonzalez** [comment]
> I don't think that a client's max-age request will affect other client's requests, but any client passing a max-age=0 directive would, by this definition, bypass the dispatcher for every request.

Welcome to DOS-ville, USA :)

**Comment by justinedelson** [comment]
PR Merged
