### ISSUE TITLE
Make SSL option configurable for Twitter Adapter Factory 

### ISSUE THREAD

**Issue by sharath-madappa-icfi** [Adobe-Consulting-Services/acs-aem-commons#799]
The client uses SSL by default when using proxy configuration. Can this configurable instead of the code assuming the proxy is on SSL

**Comment by justinedelson** [comment]
I added support for configuring the useSsl flag passed to the Twitter4J ConfgurationBuilder. As I don't have a good proxy setup, can I ask that you build and test this to see if it meets your needs? Feel free to reopen if it doesn't.
