### ISSUE TITLE
Remove usages of administrative logins

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#801]
For the 6.2 branch, I would like to remove all of the usages of `loginAdministrative` and `getAdministrativeResourceResolver()`.

In my analysis, this impacts the following components:
- [x]  Ensure Oak Index
- [x]  ReviewTaskAssetMoverHandler
- [x]  EmailService
- [x]  ErrorPageHandler
- [x]  AbstractFormHelper
- [x]  PackageHelper
- [x] QuicklyFilter
- [x]  DispatcherFlusherServlet
- [x] DispatcherFlushRulesImpl
- [x] JcrPackageReplicationStatusEventHandler
- [x] ComponentErrorHandler
- [x] WCMInboxWebConsolePlugin
- [x] SystemNotificationsImpl
- [x] BulkWorkflowEngineImpl
- [x] AEMWorkflowRunnerImpl
- [x] FAMRunnerImpl
- [x] SyntheticWorkflowRunnerImpl
- [x] WorkflowInstanceRemoverScheduler
- [x] TwitterFeedScheduler

I will be doing this work in a branch and reporting back status on this issue as I progress.

In the end, each service should use a specific user account with permissions set up by default based on a standard content structure. If a particular installation deviates from that content structure, they may need to apply additional ACLs. These assumptions about content structure will be documented on the feature documentation pages.

**Comment by justinedelson** [comment]
Ensure Oak Index:

User: acs-commons-ensure-oak-index-service
ACLs: read on /apps, r/w on /oak:index

ReviewTaskAssetMoverHandler

User: acs-commons-review-task-asset-mover-service
ACL: r/w on /content/dam

EmailService

User: acs-commons-email-service
ACLs: read on /etc/notification/email

ErrorPageHandler

User: acs-commons-error-page-handler-service
ACLs: read on /content

**Comment by justinedelson** [comment]
Form Helper:
User: acs-commons-form-helper-service
ACLs: none (map only)

Package Helper:
none (removed usage of separate resource resolver)

**Comment by davidjgonzalez** [comment]
@justinedelson wrt to Ensure Oak Index.. a user can define non-root oak:indexes as well; is the idea we provide documentation that instructs per feature cases where custom ACLs may need to be defined?

**Comment by justinedelson** [comment]
@davidjgonzalez maybe. Let me try to deal with that case with `rep:glob`.

Question - it looks like Ensure Oak Index assumes that the `oak:index` node (say under /content) already exists. Is that correct?

**Comment by davidjgonzalez** [comment]
@justinedelson yes, but TBH i think thats an oversight on the part of the implementation now that you bring it up.

**Comment by justinedelson** [comment]
actually, when I was testing moving the ACLs around, I did see an error message when it couldn't find `/content/oak:index` So I think we're good there.

**Comment by justinedelson** [comment]
Dispatcher Flush:
User - acs-commons-dispatcher-flush-service
ACLs: read and replicate on /

**Comment by justinedelson** [comment]
Package Replication Event Listener:
User - acs-commons-package-replication-status-event-service
ACLs - read and write on /

I think there is a bug in the package manager. This user should only require read access and write access to a handful of properties, but extracting the package in dry run fails with those permissions. I need to research this further.

**Comment by justinedelson** [comment]
Component Error Handler:
User - acs-commons-component-error-handler-service
ACLs - read on /apps and /content

**Comment by justinedelson** [comment]
System Notifications:
User - acs-commons-system-notifications-service
ACL - read on /etc/acs-commons/notifications

**Comment by justinedelson** [comment]
Twitter:
User - acs-commons-twitter-updater-service
ACL - read, writeproperties, replicate on /content

**Comment by justinedelson** [comment]
Workflow Remover:
User - acs-commons-workflow-remover-service
ACL - read, write on /etc/workflow/instances

**Comment by justinedelson** [comment]
Bulk Workflow:
User - acs-commons-bulk-workflow-service
ACL - read, writeproperties on /etc/acs-commons/bulk-workflow-manager

**Comment by justinedelson** [comment]
WCM Inbox
User - acs-commons-wcm-inbox-cleanup-service
ACL - read on /home/users, removeChildNodes on /home/users */wcm/notification/inbox, removeNodes on /home/users */wcm/notification/inbox/*

**Comment by justinedelson** [comment]
Workflow runners use existing workflow-process-service user
