### ISSUE TITLE
Multi-Field Dialog breaks when acs-aem-commons is installed

### ISSUE THREAD

**Issue by sammykumar** [Adobe-Consulting-Services/acs-aem-commons#803]
I've noticed the dialog box for the [Multi-Field component](https://helpx.adobe.com/experience-manager/using/first_htl_WCMUsePojo.html) becomes unresponsive when acs-aem-commons is installed. 

I get this error in the console of Chrome Dev Tools
`Uncaught RangeError: Maximum call stack size exceeded
`

[Content Package file](https://helpx.adobe.com/content/help/en/experience-manager/using/first_htl_WCMUsePojo/_jcr_content/main-pars/download/file.res/myHTL62.ui.apps-1.0-SNAPSHOT.zip) 

Steps to reproduce
1. Install AEM 6.2 (with or without sample content, I've tried both)
2. Install content package above
3. Navigate to http://localhost:4502/editor.html/content/myHTL62/en.html
4. Open dialog box for multi touch component
5. Verify it works
6. Install acs-aem-commons 3.30
7. Refresh http://localhost:4502/editor.html/content/myHTL62/en.html
8. Try to open dialog box 
9. Open Dev Tools open equivalent to see console error and see that the dialog box has become unresponsive and will not show data anymore.

**Comment by viveksachdeva** [comment]
@sammykumar : I installed your package with corresponding acs-aem-commons-3.3..
A few things that I notices:
- You mentioned that multi fields component becomes unresponsive but the link that you added above takes me page that is not for multi field component 
- Moreover I could find some components on the page that are not multi-field and they are working fine with and without the package..

**Comment by davidjgonzalez** [comment]
@sammykumar thoughts on @viveksachdeva's comments? wrong package?

**Comment by vsurep** [comment]
@sammykumar even I am facing same error after installing acs-aem-commons package. Did you get any solution for this ?

**Comment by abhisheknarula25** [comment]
We recently installed acs-aem-commons in aem 6.2. Multifield stopped working with the same error in console as above:

Uncaught RangeError: Maximum call stack size exceeded
