### ISSUE TITLE
Limit Parsys and Parsys Decorator Breaks on deep /etc/design hierarchy.

### ISSUE THREAD

**Issue by dwaynehale** [Adobe-Consulting-Services/acs-aem-commons#805]
If you have a /etc/designs/ hierarchy that is any more complex than the OOTB Geometrixx structure, you will be met with this error in the browser console using the classic UI limit parsys and parsys decorator/configurator features:
<img width="722" alt="acslimitparsysissue" src="https://cloud.githubusercontent.com/assets/186984/19115574/89477dea-8ae0-11e6-93ec-28e4936999ed.png">

and the plugins will not work as they cannot find the acs properties that they need to evaluate.

Example of /etc/designs hierarchy:
![image](https://cloud.githubusercontent.com/assets/186984/19115621/adb95284-8ae0-11e6-9581-4658b3e7b688.png)

PR for each fix:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/806
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/807

**Comment by davidjgonzalez** [comment]
Fixed
