### ISSUE TITLE
Granite Include not compatible with NODE_STORE or JSON_STORE multifields

### ISSUE THREAD

**Issue by christopher-jones-i3** [Adobe-Consulting-Services/acs-aem-commons#808]
Not sure whether to classify this as a new feature or as a bug.

Context: Using multifields in a dialog on AEM 6.1 with ACS AEM Commons 2.7.0:

`acs-commons-nested="NODE_STORE"`
or
`acs-commons-nested="JSON_STORE"`

I've noticed that any fields that have been included via a 'granite/ui/components/foundation/include' inside the multifield are not persisted and (as a result) don't show when re-opening the dialog.

In my specific scenario, we are attempting to centralize a set of fields that will be used in several different dialogs (sometimes within multifields, sometimes not).

If any more specific information is needed or a code example, let me know.

If nodody can reproduce this, I will chalk it down as an environment issue and close this down.

Granite Include documentation: 
https://docs.adobe.com/docs/en/aem/6-1/ref/granite-ui/api/jcr_root/libs/granite/ui/components/foundation/include/index.html

Related ACS AEM Commons code: 
https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/master/content/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/composite-multifield/source

**Comment by khakiout** [comment]
I can reproduce this. 

I initially created a Link List component with a multifield property having fields (i.e. path, label, and a checkbox). It's working at that point. Then I moved the fields to a Link component then referenced it to the multifield via Granite Include, it's not showing on the dialog box anymore.

See:
![multifield-with-no-include](https://cloud.githubusercontent.com/assets/3415132/21984650/de2098ae-dc31-11e6-8e53-0dafbc8a6acf.PNG)
![multifield-with-include](https://cloud.githubusercontent.com/assets/3415132/21984656/e46e971a-dc31-11e6-98d6-8978d22453c1.PNG)

**Comment by khakiout** [comment]
is there any workaround for this?
