### ISSUE TITLE
Issue while using ACS AEM Commons Icon Picker feature in a Touch UI Multifield

### ISSUE THREAD

**Issue by CtsJHRewardsLife** [Adobe-Consulting-Services/acs-aem-commons#809]
Attached the documents for the issue :
[Icon_issue.docx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/513374/Icon_issue.docx)
[Steps_To_Reproduce.docx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/513373/Steps_To_Reproduce.docx)

**Comment by quoo** [comment]
Can you put the issue and steps to reproduce in the issue itself, rather than in docs?

**Comment by viveksachdeva** [comment]
@CtsJHRewardsLife : For the icon not displaying issue, I have created a PR https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/811
For other issue that you mentioned in the doc, where editing one icon changes other, I have not been able to reproduce it.. I created a package with a dummy component for the same..  
P.S. : I am using AEM 6.2 with ACS commons 3.x

Could you take a look at this and add more info in case you are still facing this issue..

Thanks!!
