### ISSUE TITLE
Bundle not getting active

### ISSUE THREAD

**Issue by viveksachdeva** [Adobe-Consulting-Services/acs-aem-commons#810]
I forked the repository and did a autoInstallPackage. The bundles com.adobe.acs.acs-aem-commons-bundle and com.adobe.acs.acs-aem-commons-bundle-twitter remain in Installed state with some errors in Import Packages. Do I need to do something more to get it to work?

I am using Vanilla 6.2 instance

**Comment by justinedelson** [comment]
if you want the twitter bundle to be active, you need to install the twitter4j dependency. see http://adobe-consulting-services.github.io/acs-aem-commons/features/twitter.html

**Comment by viveksachdeva** [comment]
@justinedelson But main acs bundle is also in installed state..

**Comment by justinedelson** [comment]
what version of AEM? what version of ACS AEM Commons?

**Comment by viveksachdeva** [comment]
Its 6.2 Vanilla instance and 2.7.1 Snapshot of ACS commons.. Some os the errors:
![screen shot 2016-10-08 at 12 29 07 pm](https://cloud.githubusercontent.com/assets/1879953/19211132/df7d0224-8d52-11e6-989f-d5b6a847c0c8.png)

**Comment by justinedelson** [comment]
For 6.2, you need to use the feature/6.2-compatibility branch, which will always be a 3.x version

**Comment by davidjgonzalez** [comment]
@viveksachdeva curious, I see th confusion randomly even though it's on the home page (in pretty big font) and also noted in the releases. Understanding here you were building on the wrong branch, but I would've though the installed 2.x on AEM 6.2 would alert you to the crux of problem based on the messaging cited above.

Any suggestions on how we can make it clear 2.x is for 6.0/6.1 and 3.x is for 6.2? Do you not even go to the web site and just hit the GH repo?

**Comment by viveksachdeva** [comment]
Thanks @justinedelson .. 
@davidjgonzalez  : Sorry for the confusion.... My bad that I did not see the page for version compatibility.. Preoccupied mind that master would have latest code and I am using latest version of AEM..

**Comment by davidjgonzalez** [comment]
@viveksachdeva no worries! I was (genuinely) looking for feedback or suggestions to help clarify -- like I said before - you're not he first to make this mistake and won't be the last. If there is a better place to call this out we're all ears. Thanks!

**Comment by viveksachdeva** [comment]
Actually having that in README of respective branch would have helped me.. but it could just be me... :)
