### ISSUE TITLE
JS Error on Selection of pathbrowser component inside of Multifield

### ISSUE THREAD

**Issue by quoo** [Adobe-Consulting-Services/acs-aem-commons#812]
Using a pathbrowser component inside a composite multi field does not seem to be functioning as expected. This is in AEM **6.2**, using acs-aem-commons-content-**3.2.6**.zip

**Steps to replicate:**
1. Add a pathbrowser as a required field to a composite multifield in a Touch UI dialog (my test also has additional text fields). 
2. In Edit mode, edit the component. Add two (or more) items to multifield. Do not select anything for the first path browser. It will be marked as invalid.
3. Move to the second pathbrowser. Click the browse button and attempt to select a file. 

**Results:**
The pathbrowser window does not close and store the selection.

Line 182 of touchui-widgets.js (this.clear($el);) throws an error "this.clear($el);

touchui-widgets.js:182 Uncaught TypeError: Cannot read property 'clear' of undefinedshow @ touchui-widgets.js:182validator.show @ foundation.js:1317f @ foundation.js:1086(anonymous function) @ foundation.js:1100everyReverse @ foundation.js:206updateUI @ foundation.js:1096validateHandler @ foundation.js:4765dispatch @ jquery.js:4665elemData.handle @ jquery.js:4333trigger @ jquery.js:4574(anonymous function) @ jquery.js:5284each @ jquery.js:384each @ jquery.js:136trigger @ jquery.js:5283jQuery.fn.(anonymous function) @ jquery.js:8476_setInputValue @ coralui2.js:17377_pickerSelectionConfirmed @ coralui2.js:17568dispatch @ jquery.js:4665elemData.handle @ jquery.js:4333trigger @ jquery.js:4574(anonymous function) @ jquery.js:5284each @ jquery.js:384each @ jquery.js:136trigger @ jquery.js:5283_selectionConfirmed @ coralui2.js:17949dispatch @ jquery.js:4665elemData.handle @ jquery.js:4333

**Expected:** 
The pathbrowser closes and saves the selection without throwing an error when attempting to validate.

**Comment by quoo** [comment]
This is also happening in 3.3.0

**Comment by viveksachdeva** [comment]
@quoo : If possible, could you attach a content package for the same..

**Comment by quoo** [comment]
Sorry for the delay, here's a cleaned up sample content package. 
[multifield_pathbrowser_sample.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/558807/multifield_pathbrowser_sample.zip)

**Comment by viveksachdeva** [comment]
@quoo : Unfortunately there seems to be an issue with the package.. "Zip File is not a content package. Missing 'jcr_root'."

Moreover after unzipping the file, it seems that the dialog contains 2 text fields but no pathbrowser and all fields are not mandatory.. Could you please check the package again...

**Comment by quoo** [comment]
I apologize, I was a little overzealous when cleaning up that component to upload. Please try this one. It should contain the relevant data. 
[multifield_pathbrowser_sample (2).zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/565033/multifield_pathbrowser_sample.2.zip)

**Comment by viveksachdeva** [comment]
@quoo : I have created a PR for this.. Would you please take a look at that and give it a round of test.. Thanks!!

**Comment by quoo** [comment]
Your PR seems to fix my issue, thank you!

**Comment by viveksachdeva** [comment]
@justinedelson : Could you please take a look at my PR and see if can be merged.. Thanks!!

**Comment by viveksachdeva** [comment]
@quoo : PR has been merged. I believe this can be closed now.. Thanks!!
