### ISSUE TITLE
Named Image Transform doesn't support animated GIFs

### ISSUE THREAD

**Issue by paulrohrbeck** [Adobe-Consulting-Services/acs-aem-commons#813]
I have a simple transformer `media-text` configured with `resize:width=465` but when I use it for an animated GIF (http://localhost:4502/content/dam/acme/asset.gif.transform/media-text/image.gif) the animation is lost and only the first frame is shown. I have the `Asset Rendition Picker Regex` configured to `original` so that it would use the actual GIF instead of the web rendition (where the animation is also broken).

Something I'm doing wrong? Known Bug? (Related to using AEM's OOTB Layer write() method?)

**Comment by davidjgonzalez** [comment]
@paulrohrbeck animated gifs are not supported, just like they are not supported by the OOTB aem image component

**Comment by paulrohrbeck** [comment]
@davidjgonzalez Thanks for the quick response. Are there any plans on adding this in the future or is it too much of an edge case? From my perspective, one of the reasons for using ACS Commons is to go beyond what the (limited) OOTB components can do.

**Comment by davidjgonzalez** [comment]
@paulrohrbeck no plans. This implies using the image APIs provided by aem which have limited supporter of these more interesting file formats. If you want to propose a new API (ideally that ships w AEM to avoid external dependencies) that is more robust we could take a look at that.

**Comment by paulrohrbeck** [comment]
That makes sense, thank you.
