### ISSUE TITLE
Sling Health Check for SMTP access

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#815]
A near universal integration for AEM projects is configuring an SMTP server in the AEM Mail Service for sending emails. This can be cumbersome to test as it requires engaging in an activity that sends email (ex. Workflow, Registration, etc.)

There should be a Sling Health Check that reports if the SMTP server can be reached and a test email sent.

**Comment by justinedelson** [comment]
Would this test that the DefaultMailService (which is generally the universal holder of this information) is configured? And get the configuration bits from ConfigAdmin for that PID?

**Comment by davidjgonzalez** [comment]
@justinedelson it would ~ send a SimpleEmail using the OOTB MessageGatewayService (which in turn depends on the DefaultMailService) and expose the configuration params of the OSGi config via the Email obj that is sent (or attempted to be be sent) -- rather than using ConfigAdmin to grab the config bits direct; Checking the email seems nearer to the point of truth.

**Comment by davidjgonzalez** [comment]
@justinedelson the idiomatic package name for health checks `.hc`, right? 

Also, thoughts if this PR should provide the health check nodes so that this health check shows in the AEM Operations Web UI? My gut says "yes, why not" (even though i personally gravitate to the Felix/JMX consoles, which is likely because they all exist there, and not all are in the WebUI)

**Comment by justinedelson** [comment]
@davidjgonzalez I think `.hc.` is good.

I'm not totally sure I understand what you are saying about sending an email, but I guess that'll work. I'm also not sure about the health check nodes. WDYT about adding them, but using a rendercondition to actually show them in the console based on a feature flag?

**Comment by bstopp** [comment]
I thought most of the WebUI tooling simply made calls to the JMX console? I like the idea of being able to see this check on the same dashboard as the others.

**Comment by davidjgonzalez** [comment]
Stopp - It does, you need to drop in the nodes that's point to the HCs tho
