### ISSUE TITLE
named image transform restricting bounded resize on PSD files

### ISSUE THREAD

**Issue by jaredray** [Adobe-Consulting-Services/acs-aem-commons#818]
We are using the named transform servlet for our images... we have a large transform set at 1500px wide. However it is being restricted to 1280px (seems to be an AEM default) instead of respecting the servlet dimensions. Any thoughts on how to fix? http://assets.microncpg.com/content/dam/crucial/dram-products/server/ecc-sodimm/images/product/crucial-ddr3-ecc-sodimm-kit4-image.psd.transform/large/image.png

here is our config:
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0" jcr:primaryType="sling:OsgiConfig" name="large" transforms="[bounded-resize:width=1500]" />

Strange thing is that it works as expected on a smaller size at 1000px:
http://assets.microncpg.com/content/dam/crucial/dram-products/server/ecc-sodimm/images/product/crucial-ddr3-ecc-sodimm-kit4-image.psd.transform/medium/image.png

Seems to be a restriction on transforms on PSD files as it works if we target a larger rendition with a transform:
http://aemauthor.microncpg.com:4502/content/dam/crucial/dram-products/server/ecc-sodimm/images/product/crucial-ddr3-ecc-sodimm-kit4-image.psd/_jcr_content/renditions/cq5dam.resized.2000.2000.png.transform/large/image.png

**Comment by justinedelson** [comment]
By default, when you access a DAM asset directly as in your first URL, the first rendition matching the regex `cq5dam\.web\.(.*)` is used. This can be configured through the `prop.asset-rendition-picker-regex` configuration property of the Named Transform Image Servlet.

so it seems like in this case you want to configure it to use the pattern `cq5dam\.resized\.2000\.2000`

Perhaps this option needs to be better documented.

**Comment by jaredray** [comment]
cool, thanks @justinedelson so where is that configuration property on the servlet?

**Comment by justinedelson** [comment]
It is in OSGi ConfigAdmin

![image](https://cloud.githubusercontent.com/assets/65906/19488368/93c9f820-9534-11e6-9f35-ce8e2289fff9.png)

**Comment by jaredray** [comment]
sweet, thanks

**Comment by zschill** [comment]
@justinedelson how would I set this asset-rendition-picker-regex up in an xml file so it will be stored in source control?

Thanks!

**Comment by justinedelson** [comment]
@zschill it depends a bit on the your project structure, but in general, you would create the XML file in /src/main/content/jcr_root/apps/_yourproject_/config and name it `com.adobe.acs.commons.images.impl.NamedTransformImageServlet.xml`.

**Comment by zschill** [comment]
Thanks, would I only need to add the settings that need to be overridden in the xml file?  Also what would the actual syntax be for the setting?  I can't seem to find documentation that lays it out very well.

**Comment by justinedelson** [comment]
Have you read through https://docs.adobe.com/docs/en/aem/6-2/deploy/configuring/configuring-osgi.html and https://sling.apache.org/documentation/bundles/jcr-installer-provider.html ?

**Comment by zschill** [comment]
I think what I had been looking at was outdated.  I'll look through these, thanks!
