### ISSUE TITLE
Feature request: The crop image transformer should support relative dimensions

### ISSUE THREAD

**Issue by joelrich** [Adobe-Consulting-Services/acs-aem-commons#819]
On devices with wide screens, my page loads a wide hero image. On mobile devices with narrow screens, the hero image has to be cropped. Depending on the page, it loads a different hero image (with different heights). This is why I cannot specify the height for the crop transformer. To get it working anyway, I have copied CropImageTransformerImpl and made the following adjustment:

```java
            int width = Integer.parseInt(bounds[PARAM_INDEX_WIDTH]);
            if (width < 0) {
                width = layer.getWidth() - x;
            }

            int height = Integer.parseInt(bounds[PARAM_INDEX_HEIGHT]);
            if (height < 0) {
                height = layer.getHeight() - y;
            }
```

This allows to crop the hero image without having to specify a height. Here is an example config:

```
transforms="[resize:width=1280,flex-crop:bounds=320\,0\,640\,-1]"
```

It would be even better if I could specify relative dimensions. Then I could use the following configuration:

```
transforms="[crop:bounds=25%\,0\,50%\,100%,resize:width=1280]"
```

This could then also be chained with a separate resize configuration (which is not possible with the first configuration). Also, I am sure there would be several other use cases.

What do you think about this proposal?

**Comment by justinedelson** [comment]
@joelrich this sounds good to me. I can't 100% tell if you are suggesting a new transformer or an enhancement to the existing transformer. Obviously the latter should be backwards compatible, but I don't see that being a big issue in this case.

Is this something you are planning on submitting a PR for?

**Comment by joelrich** [comment]
I was thinking about extending the existing crop transformer (flex-crop was just my own copy of it). It should be quite easy to make it backward compatible. We would just have to check if the number is followed by a percentage sign.

If I submitted a pull request with the change, how long would it take until the package is released? I cannot promise it, but I would be interested in doing it.

**Comment by justinedelson** [comment]
@joelrich it depends :) but unless there is some big change pending more "soak" time, we usually do releases pretty quickly (or at least I would like to think that's the case)

**Comment by davidjgonzalez** [comment]
@joelrich also, wrt to the image transforms, they lend themselves well to unit testing so they tend to be easier to debug/test.

I have a few other PRs that im hoping to clean up today so, depending on if/when you can drop this soon-ish, it would be added motivation to cut a release. (no pressure tho :))

**Comment by joelrich** [comment]
I have created a pull request here: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/821. Please let me know if anything is missing.

**Comment by justinedelson** [comment]
PR Merged
