### ISSUE TITLE
Users to CSV Report

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#820]
There should be an easy way to export users, basic profile data, and their groups (declared and transitive) from AEM for governance and reporting purposes.

**Comment by davidjgonzalez** [comment]
Something like .. 

![image](https://cloud.githubusercontent.com/assets/1451868/19587112/90ee3c50-9710-11e6-8c36-9faf5c2741b0.png)

[users.export.csv.txt](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/543534/users.export.csv.txt)

**Comment by rgummalla** [comment]
Hi David, Do you know when its available on AEM 6.2, one of my customer is actively looking for this feature.

**Comment by davidjgonzalez** [comment]
@rgummalla should be today with the new release

**Comment by rgummalla** [comment]
@davidjgonzalez  Can i get a preview of this feature and when will this be released.

**Comment by rgummalla** [comment]
@davidjgonzalez  I have installed 3.4 version that includes this feature. I am getting errors on my linux VM
http://10.36.65.87:6202/etc/acs-commons/users-to-csv.html
Resource at '/etc/acs-commons/users-to-csv.html' not found: No resource found

Cannot serve request to /etc/acs-commons/users-to-csv.html in /libs/sling/servlet/errorhandler/404.jsp

Request Progress:

      0 TIMER_START{Request Processing}
      0 COMMENT timer_end format is {<elapsed msec>,<timer name>} <optional message>
      0 LOG Method=GET, PathInfo=/etc/acs-commons/users-to-csv.html
      0 TIMER_START{ResourceResolution}
      0 TIMER_END{0,ResourceResolution} URI=/etc/acs-commons/users-to-csv.html resolves to Resource=NonExistingResource, path=/etc/acs-commons/users-to-csv.html
      0 LOG Resource Path Info: SlingRequestPathInfo: path='/etc/acs-commons/users-to-csv.html', selectorString='null', extension='html', suffix='null'
      0 TIMER_START{ServletResolution}
      0 TIMER_START{resolveServlet(/etc/acs-commons/users-to-csv.html)}
      1 LOG {0}: no servlet found
      1 TIMER_END{1,resolveServlet(/etc/acs-commons/users-to-csv.html)} Using servlet org.apache.sling.servlets.get.DefaultGetServlet
      1 TIMER_END{1,ServletResolution} URI=/etc/acs-commons/users-to-csv.html handled by Servlet=org.apache.sling.servlets.get.DefaultGetServlet
      1 LOG Applying Requestfilters
      1 LOG Calling filter: com.adobe.granite.resourceresolverhelper.impl.ResourceResolverHelperImpl
      1 LOG Calling filter: org.apache.sling.bgservlets.impl.BackgroundServletStarterFilter
      1 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter

**Comment by davidjgonzalez** [comment]
Create a users to Csv exporter under /etc/acts-commons/exporters

**Comment by rgummalla** [comment]
Thanks @davidjgonzalez  . it works like a charm.

**Comment by davidjgonzalez** [comment]
Great to hear! Thanks for the feedback!
