### ISSUE TITLE
uploads / install via /crx/packmgr/service/.json no longer work with 3.3.2

### ISSUE THREAD

**Issue by kleinlain** [Adobe-Consulting-Services/acs-aem-commons#822]
Hello,

I realized after quite some trial and error that with version 3.2.2 of the acs commons, we can no longer upload and / or install packages with the /crx/packmgr/service/.json commands. It still works with 3.2.12 but with 3.3.2 after a first successful installation we get a 404 error when trying to upload, manually checking crx shows the package exists in the given version.

is this a somewhat known issue and I missed out?

kind regards

/anja

**Comment by justinedelson** [comment]
I can't reproduce this. What is the specific cURL command (if you aren't using cURL, please describe how you are invoking that service).

I'm using this as the installation command:
    curl -u admin:admin -v -X POST http://localhost:4502/crx/packmgr/service/.json/etc/packages/my_packages/testpackage.zip?cmd=install

**Comment by kleinlain** [comment]
it's the same command. Can you delete it after a successful installation?
?cmd=delete



And another thing I noticed is that I cannot uninstall the 3.3.2 bundle manually from CRX package manager, error message then says "cannot uninstall 'undefined'"

**Comment by justinedelson** [comment]
delete works OK for me as does an uninstall of ACS AEM Commons.

**Comment by kleinlain** [comment]
this is interesting, I had the 3.3.2 and only used it for creating the acl and authorizables package, the rest was a standard 6.2 aem version

**Comment by justinedelson** [comment]
Does the package manager HTML  interface work?

**Comment by sabyamon** [comment]
I think I have seen similar behavior in 6.2. @kleinlain - Can you see if you can uninstall other packages(apart from ACS Commons) from package manager HTML interface ?
@justinedelson - interestingly , I did not find any hint in the error.log(INFO) when I see this "cannot uninstall 'undefined'"  .

**Comment by kleinlain** [comment]
yup, but I coud not uninstall the 3.3.2 version via interface.

**Comment by kleinlain** [comment]
unfortunately I cannot assist any more in reproducing the error, I use the 3.2.12 version now, since I need a working version for development.

All I can offer is that uninstalling via crxlite did not work, reinstalling other software bundles did not work, I had created the content packages for ACL and authorizables.

**Comment by kleinlain** [comment]
hm, so I tried once more.
Started up a naked aem 6.2 instance, runmode author, installed some content. install no software of our onwn. installed aem commons 3.3.2, installed a content package with system users, and one with ACLs. restarted the instance. cannot uninstall the aem commons. cannot install our own software via curl on /crx/packmgr/service/.json?cmd=upload.

On startup quite a lot of errors are logged from several com.adobe.cq.social packages.

encountered problems of the same kind with 3.2.12

**Comment by kleinlain** [comment]
looks like it has been a permission problem in the ACL package, can't quite figure out which one, but that seems to have been the mistake
