### ISSUE TITLE
The ‘acs-commons’  has a touch-UI listener which is overriding our components. Thus it prevented our components from editing. 

### ISSUE THREAD

**Issue by iwovsys** [Adobe-Consulting-Services/acs-aem-commons#823]
The ‘acs-commons’  has a touch-UI listener which is overriding our components. Thus it prevented our components from editing. 

on installing the ACS commons, we see all the fields in a component empty.

**Comment by justinedelson** [comment]
Can you provide a package and steps to reproduce?

**Comment by iwovsys** [comment]
Hi @justinedelson 

Can you please let us know if there is a an FTP server or file sharing system, where i can upload the packages. 

I am unable to add them here. 

Regards
Sanket

**Comment by justinedelson** [comment]
There's a lot of online file sharing services. Take your pick. Obviously I'm biased to Adobe Creative and Document Clouds:)
