### ISSUE TITLE
Feature request: Add deny filter pattern for Dispatcher TTL

### ISSUE THREAD

**Issue by bobbyjam99** [Adobe-Consulting-Services/acs-aem-commons#827]
I'm using Dispatcher TTL. It is very nice features. But there is a problem.

I have been set for Dispatcher TTL as follows.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
    xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="sling:OsgiConfig"
    filter.pattern="[/content/site/products/(.*)]"
    max.age="60"
    />
```

Dispatcher can set allow and deny. But Dipatcher TTL can set only allow. So it's too difficult to be same settings. And contents that does not cache will still remain in the Request Header like "Cache-Control: max-age=60".

I hoge to set deny filter pattern.

**Comment by davidjgonzalez** [comment]
Can you give an example? 

It sounds like you want a blacklist expression that is evaluated after the existing whitelist is evaluated?

**Comment by bobbyjam99** [comment]
> It sounds like you want a blacklist expression that is evaluated after the existing whitelist is evaluated?

That's right.

"dispatcher.any" sets as follows. First, it's allow the all content. Next, it's deny the content that does not cache. Search results are with content that does not cache.
```
    /cache
      {
      /rules
        {
        /0000 {/glob "*" /type "allow"}
        /0001 {/glob "/content/site/products/favorite/*" /type "deny"}
        /0002 {/glob "/content/site/products/search/*" /type "deny"}
        }
      }
```

Now we are set as follows. So contents that does not cache(ex. /content/site/products/favorite/*) will still remain in the Response Header like "Cache-Control: max-age=60". It is not be removed from the Response Header. Cache-Control to the content that I don't want to cache is in trouble have been set.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
    xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="sling:OsgiConfig"
    filter.pattern="[/content/site/products/(.*)]"
    max.age="60"
    />
```

If I was corresponding with a regular expression, it looks like the following. But error-prone because the "dispatcher.any" with the notation is different.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
    xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="sling:OsgiConfig"
    filter.pattern="[/content/site/products/(?!(favorite|search))/(.*)]"
    max.age="60"
    />
```

I would like to set in the same way as "dispatcher.any". 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
    xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="sling:OsgiConfig"
    filter.pattern="[/content/site/products/(.*)]"
    deny.filter.pattern="[/content/site/products/favorite/(.*),/content/site/products/search/(.*)]"
    max.age="60"
    />
```
