### ISSUE TITLE
Ensure Oak Index - Resource Change Listener

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#837]
Ensure Oak Index should have a ResourceChangeListener that listens for changes to registered ensure index trees, and when a change is detected it invokes the ensuring of indexes (respecting the application flags on the ensure oak index nodes)

/cc @bstopp

**Comment by joerghoh** [comment]
@davidjgonzalez in that case you might trigger an immediate reindex during the installation of the content package, potentially delaying the installation. If your deployment process requires a restart afterwards, the reindexing process might interfere here.

**Comment by davidjgonzalez** [comment]
Yeah - been delaying doing anything w this because of the odd corner cases. It seems like this is generally development or updating ensure indexes on a live system, manually or via packages.  There seems to be a disconnect in the running of the mbean to effect the change, and the expectation, and even desire for it to apply immediately.

**Comment by davidjgonzalez** [comment]
May not be so safe either...
