### ISSUE TITLE
PagesReferenceProvider checks for references regardless of resource type and path

### ISSUE THREAD

**Issue by josephrignanese** [Adobe-Consulting-Services/acs-aem-commons#838]
Currently the page reference provider [1] does not do any validation of the resource before attempting to find references.

IIUC, this should only need to scan page resources for references, and not other resources.

This can lead to OutOfMemory errors when activating large binaries as the provider iterates through all of the node properties. A simple check to see if the resource needs to be scanned should resolve this.

[1] http://adobe-consulting-services.github.io/acs-aem-commons/features/reference-providers.html

**Comment by justinedelson** [comment]
I see no reason for this check. The OOM bug was fixed in 2.7.0 & 3.3.0 in #788.

It is very easy to imagine cases where you would want to do this reference check on non-page content.

**Comment by josephrignanese** [comment]
Thanks @justinedelson, closing as per the above.
