### ISSUE TITLE
Aem Environment Indicator Tab Title gets reset by AEM console code

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#842]
In the Touch and ClassicUI in AEM 6.1/6.2 there is code that resets the document.title after page load. The AEM Environment Indicator should put safeguards in to reset any re-writes to itself.

Candidate approach is to update the Tab title javascript to: 

```
"<script>(function() { var c = 0; t = '%s' + ' | ' + document.title, i = setInterval(function() { if (document.title === t && c++ > 10) { clearInterval(i); } else { document.title = t; } }, 1500); document.title = t; })();</script>";
```

Where %s is replaced by the custom title.

/cc @bstopp

**Comment by bstopp** [comment]
is 1500 enough of a delay 👍

**Comment by davidjgonzalez** [comment]
It checks 10x at a 1.5s interval.. so at 15s it's the last check? Could adjust those 2 #s...

**Comment by davidjgonzalez** [comment]
Reopening since the comment fix should be sufficient ; just need to get around to applying
