### ISSUE TITLE
Client Libraries Set Base Root Path

### ISSUE THREAD

**Issue by alvin0618** [Adobe-Consulting-Services/acs-aem-commons#847]
May I know is that possible to set base root to point to a specific path?

Example:-   
`/etc/clientlibs/folder-a/js.txt`
`/etc/clientlibs/folder-a/css.txt`
`/etc/design/libs/folder-b/file-one.css`
`/etc/design/libs/folder-b/file-two.css`
   
    
In  `/etc/clientlibs/folder-a/css.txt`
```
#base=/etc/design/libs/folder-b
file-one.css
file-two.css
```

**Comment by davidjgonzalez** [comment]
Not relevant to this project. Try the adobe forums.
