### ISSUE TITLE
ACL Packager not packaging empty rep:policy nodes

### ISSUE THREAD

**Issue by kristian-wright** [Adobe-Consulting-Services/acs-aem-commons#848]
I'm testing out the ACL Packager in order to migrate permissions from one AEM instance to another.  

If a create a group called 'test-group' and assign the read permission to /content/geometrixx/en/products, then use the ACL Packager on the 'test-group' authorizable, it correctly creates the filter /content/geometrixx/en/products/rep:policy.  I can then download and deploy this on another author instance and it works as expected (assuming the destination also has the group 'test-group')

But if on the source instance I then remove the permission at /content/geometrixx/en/products, when I look at the /content/geometrixx/en/products/rep:policy node, it correctly has no children.  But if I want to then package this to remove the permission on my destination instance, the ACL Packager does not recognise the 'empty' policy node and does not create the filter.

This means that whenever I remove permissions from the source, they are not packaged by the ACL Packager if this was the only permission under the policy node, and I can therefore not use the package to remove the ACL that was deleted from the source on the destination.

Is it possible to also allow the addition of 'empty' policy nodes so that when I remove a permission from the source and it was the last permission, that this permission is deleted from the destination when using the ACL overwrite setting in the package?

**Comment by poojachauhan** [comment]
I think it's right to not package the empty rep:policy node. When you will deploy the new package to new  instance it'll just remove the rep:policy node that would be same as blank rep:policy node.
