### ISSUE TITLE
Versioned ClientLibs css include rewrite rule doesn't recognise link rel attributes, which value differs from "stylesheet"

### ISSUE THREAD

**Issue by andrewpakhomov** [Adobe-Consulting-Services/acs-aem-commons#849]
Hi, i faced with the next issue in  "Versioned ClientLibs" module.

Our UI team asked for rendering css client lib include snippet next way:
`<link rel="preload" href="/path/to/client/lib" type="text/css" .... >`

So, we implemented this, but Versioned ClientLib module stopped to process such css includes.

The reason is, that VersionedClientlibsTransformerFactory.isCss( ... ) [method](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/release/1.10.6/bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java#L93) check if "rel" attribute equals to "stylesheet".

In modern web apps, css resources could be referenced with not only rel="stylesheet" parameter, but also "preload", "prefetch" and [others](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types).

This reproduces at 1.8.0. and 1.10.6. Current master is also affected, i assume.

**Comment by davidjgonzalez** [comment]
@andrewpakhomov this seems fine to me. I assume you are creating your own direct links to clientlibs?

**Comment by andrewpakhomov** [comment]
@davidjgonzalez, yes i directly render client libraries include markup for some pages

**Comment by kdesineedi** [comment]
@andrew:can you please elaborate how preload was added to the clientlibs?(when you say directly render client libraries?)
