### ISSUE TITLE
New ACS Commons compatible with AEM 6.3

### ISSUE THREAD

**Issue by chibulcuteanu** [Adobe-Consulting-Services/acs-aem-commons#855]
A new set of ACS commons bundles (currently at 3.4.0) are need which are compatible with AEM 6.3.
This is needed in order to validated the upgrade of AEM from 6.x to 6.3 prior to the official release of the 6.3 GA.

Later Edit: The bundles should be applicable for snapshots/load post AEM 6.3 Load 14

**Comment by justinedelson** [comment]
@chibulcuteanu the latest release (3.5.0) is compatible with the latest AEM 6.3 internal load. I'm going to keep this issue open until 6.3 is GA as additional changes may be necessary. Please report any issues you find here.

**Comment by davidjgonzalez** [comment]
AEM 6.3L15 Content Fragment editor UI breaks due to the inclusion of: `/apps/acs-commons/touchui-widgets/source/icon-picker.js`

`$('[data-init~=graphiciconselect] > select')` is undefined.

```
$(document).on('cui-contentloaded.data-api', function (e) {
    $('[data-init~=graphiciconselect] > select').fontIconPicker({
        'theme' : 'fip-coral'
    }); 
});
```

**Comment by justinedelson** [comment]
@davidjgonzalez that looks weird. if the selector `[data-init~=graphiciconselect] > select` doesn't match any elements, jQuery is supposed to return an empty set, not undefined.

**Comment by chibulcuteanu** [comment]
@justinedelson when trying to install this content package over a 6.3 L16 upgraded instance, the acs-aem-tools-bundle-0.0.28.jar bundle cannot start due to the fact that "com.day.cq.widget,version=[5.5,6) -- Cannot be resolved" Is there something on acs part that needs to be added/modified?

**Comment by justinedelson** [comment]
Please report Tools issues in the Tools project.

**Comment by davidjgonzalez** [comment]
@justinedelson we good to close this with 3.8.0 release?

**Comment by justinedelson** [comment]
I feel like we should keep this open until 6.3 is actually released. But let's be optimistic and close and reopen if necessary.
