### ISSUE TITLE
WorkflowDelegatingStep

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#856]
I need a functionality to specify a workflow on a per (sub-) folder basis, but the enduser should not know in detail, which workflow exactly is executed.

For example the "request for activation" workflow. Technically I need different implementations for it on specific parts of the repository. In /content/<mysite>/en/pages I need an approval workflow, while on /content/<mysite>/en/pages/faq pages should not require the approval workflow, and on /content/dam/<mysite>/products I need another approval workflow.

Technically this should be a workflow step, which can lookup on the node where it's started (in case it's not found it goes up the tree) what workflow to invoke. If a workflow path is found this workflow is then invoked to perform the activation.
This allows us to expose only a single "Request for activation" and implement it on each folder with the requested behaviour, without making the user aware of it or the technical details.

If there's any interest in this feature, I would implement it for ACS AEM Commons (instead creating it as project code).

**Comment by davidjgonzalez** [comment]
Absolutely; IME this is a very populist request. Path based and/or template based (for pages). How are you envisioning the configuration definition?

**Comment by davidjgonzalez** [comment]
Ah - specify the model on the content tree - missed that on first read. (Phones are overrated)

**Comment by joerghoh** [comment]
@davidjgonzalez I will implement support for assets of course. I don't plan to implement the maintenance dialogs for it (yet).

Regarding workflow packages: I don't see a difference to a "regular" page/asset, so it should be supported as well.

**Comment by davidjgonzalez** [comment]
But a WF package can have many pages and assets across content trees, so how will you decide what WF to proxy to? Are you thinking you'd unwrap the WF package in this step and put each item of the package under its proper WF?

TBH I think it's easier to say they arent supported - but figured I'd mention it earlier than later in case we could come up w a good approach.

**Comment by joerghoh** [comment]
Ok, I understand your question now. I don't plan to implement it in a way that checks each element of a workflow package and then start the proper workflow for it. If you start a workflow on a workflow package, this WorkflowDelegatingStep will look up the right workflow for /etc/workflow/packages and start the it on the package. It's then the job of this called workflow to handle the workflow packages the right way.

**Comment by davidjgonzalez** [comment]
@joerghoh makes sense to me.

**Comment by davidjgonzalez** [comment]
Merged into master. Will be in next release.

**Comment by steffenrosi** [comment]
@joerghoh 
Is there any documentation on how to use this? Is this configurable via /conf?

**Comment by davidjgonzalez** [comment]
@steffenrosi  https://adobe-consulting-services.github.io/acs-aem-commons/features/workflow-processes/workflow-delegation/index.html

**Comment by steffenrosi** [comment]
@davidjgonzalez 
Ah, under Workflow Processes, makes sense, thanks ;)

**Comment by davidjgonzalez** [comment]
the docs site incurred a medium re-org; tried to group features a bit better!

**Comment by steffenrosi** [comment]
the only "problem" I see now is that the "NEW" badge tends to get overlooked, which I was looking for when browsing the "Features"...

**Comment by davidjgonzalez** [comment]
good call - that should be bubbled up to the parent
