### ISSUE TITLE
Assets Geolocation Map - lat/long format support

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#858]
I am using photos from galaxy S6 and its default notation uses coma to separate the values like exif:GPSLatitude = “9,9,9S”.

It would be nice if this was supported along w the existing lat/long format.

**Comment by justinedelson** [comment]
is that degrees,minutes,seconds?

**Comment by davidjgonzalez** [comment]
Correct
