### ISSUE TITLE
Optional inclusion of ACS Commons Clientlibs

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#864]
Not sure if the ship has sailed on this, but it might be nice to start optionally including clientlibs that effect (and potentially break) major UIs.

For @HitmanInWis's we gave each clientlibs a discrete name and for someone to use it, they must create a proxy Clientlib that includes our feature clientlib into `cq.widgets` or `cq.authoring.editor` based on their needs.

We could even manage our own "acs-commons.widgets.all" if someone always wanted everything? I dont like that we have a slew of stuff already added to the OOTB categories, but dont htink we can do much about that.

WDYT? good, bad, overkill?

https://adobe-consulting-services.github.io/acs-aem-commons/features/shared-component-properties.html > How to Use > 2. Adding the Client Libraries for Authoring

//cc @justinedelson, @schoudry, @bstopp

**Comment by schoudry** [comment]
@davidjgonzalez i think it's a good idea; though additional configuration needed and some bugs might be missed (as the logic executes only after adding respective proxy clientlib) upside is - it doesn't break UI on hotfix or FP installs (which ACS commons almost never tests with) or upgrades

**Comment by bstopp** [comment]
I like the idea. Auto-including the ACS widgets is akin to auto-loading services. We require configs to be defined to enable any feature. Same should be for custom widgets; yes, maybe it requires an extra development step but creating aggregate clientlibs is almost standard ops now.
