### ISSUE TITLE
Refactor acs aem commons to use the new HTML Library Manager

### ISSUE THREAD

**Issue by chibulcuteanu** [Adobe-Consulting-Services/acs-aem-commons#872]
Starting with AEM 6.3 Load16, the old HTLM Library Manager is no longer present.
Starting with com.day.cq.widget-6.0.0 the old HTML Library Manager is removed.

To fix this, a refactor is needed in all the classes which import com.day.cq.widget.HtmlLibraryManager. They need to use the new HTML Library Manager: com.adobe.granite.ui.clientlibs.HtmlLibraryManager

Later Edit: com.adobe.granite.ui.clientlibs.HtmlLibraryManager is available since AEM 6.2

**Comment by justinedelson** [comment]
@chibulcuteanu where do you see a use of the old HTML Library Manager in Commons (in the 6.2 branch)? I can't find any.

**Comment by chibulcuteanu** [comment]
It looks like the only references(in the release 3.5.2 packages) are in com/adobe/acs/commons/errorpagehandler/impl/ErrorPageHandlerImpl.java and apps/acs-commons/components/utilities/version-replicator/main.jsp

**Comment by justinedelson** [comment]
well spotted!

I missed the JSP. that's been fixed now. The case in the ErrorPageHandlerImpl is a string and we are setting both the new attribute and the old one.
