### ISSUE TITLE
Loadcontent not working for Multicompositefield : AEM 6.2 Classic UI

### ISSUE THREAD

**Issue by dibakardas67** [Adobe-Consulting-Services/acs-aem-commons#873]
[samplecode.txt](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/666024/samplecode.txt)
**Issue Description** : We have a requirement where based on the selected value of a dropdown in classic UI, a corresponding pathfield is either hidden or shown.

This is inside a multifield(two items, selection and pathfield).

We are using selectionchanged to show/hide the path field when the dialog is open and the authoring is in progress. This is working as expected.

But the same is not working on using with loadcontent. When we open the dialog again after auhtoring has competed once, the pathfield is shown irrespectively. On changing the selection the pathfoeld is shown/hidden correctly.

So basically, **selectionchanged** is working but **loadcontent** is not.

Could you please help us fix this issue. This is critical to our authoring experience.

AEM version : 6.2
acs-commons ersion : 3.5.2

Below is the code sample from the dialog:

<examples
                        jcr:primaryType="cq:Widget"
                        fieldLabel="Examples"
                        name="./examples"
                        width="{Long}500"
                        xtype="mtmulticompositefield">
                        <fieldConfigs jcr:primaryType="cq:WidgetCollection">
                            <exampletype
                                jcr:primaryType="cq:Widget"
                                fieldLabel="Example Type"
                                name="exampletype"
                                type="select"
                                width="500"
                                xtype="selection">
                                <listeners
                                    jcr:primaryType="nt:unstructured"
                                    loadcontent="function(comp, val, check){&#xa;    var dlg = comp.findParentByType(&quot;dialog&quot;); //find the dialog&#xa;    var selectionArray = dlg.findByType(&quot;selection&quot;);&#xa;&#x9;var pathfieldArray = dlg.findByType(&quot;pathfield&quot;);&#xa;&#x9;for (var i=0; i&lt;selectionArray.length; i++){&#xa;&#x9;&#x9;if(selectionArray[i].getValue()!='/apps/mecommerce/digitalkit/components/content/mbsVideoExample'){&#xa;&#x9;&#x9;&#x9;pathfieldArray[i+2].hide();&#xa;&#x9;&#x9;}else{&#xa;&#x9;&#x9;&#x9;pathfieldArray[i+2].show();&#xa;&#x9;&#x9;}&#xa;&#x9;}&#xa;}"
                                    selectionchanged="function(comp, val, check){&#xa;    var dlg = comp.findParentByType(&quot;dialog&quot;); //find the dialog&#xa;    var selectionArray = dlg.findByType(&quot;selection&quot;);&#xa;&#x9;var pathfieldArray = dlg.findByType(&quot;pathfield&quot;);&#xa;&#x9;for (var i=0; i&lt;selectionArray.length; i++){&#xa;&#x9;&#x9;if(selectionArray[i].getValue()!='/apps/mecommerce/digitalkit/components/content/mbsVideoExample'){&#xa;&#x9;&#x9;&#x9;pathfieldArray[i+2].hide();&#xa;&#x9;&#x9;}else{&#xa;&#x9;&#x9;&#x9;pathfieldArray[i+2].show();&#xa;&#x9;&#x9;}&#xa;&#x9;}&#xa;}"/>
                                <options jcr:primaryType="cq:WidgetCollection">
                                    <o1
                                        jcr:primaryType="nt:unstructured"
                                        text="Text Example"
                                        value="/apps/mecommerce/digitalkit/components/content/mbsTextExample"/>
                                    <o2
                                        jcr:primaryType="nt:unstructured"
                                        text="Video Example"
                                        value="/apps/mecommerce/digitalkit/components/content/mbsVideoExample"/>
                                    <o3
                                        jcr:primaryType="nt:unstructured"
                                        text="Image Example"
                                        value="/apps/mecommerce/digitalkit/components/content/mbsImageExample"/>
                                </options>
                            </exampletype>
                            <videopath
                                jcr:primaryType="cq:Widget"
                                fieldLabel="Video Path"
                                name="videopath"
                                width="{Long}500"
                                xtype="pathfield"/>
                        </fieldConfigs>
                    </examples>

**Comment by viveksachdeva** [comment]
@dibakardas67 : Could you please attach content package for this issue?

**Comment by davidjgonzalez** [comment]
this issue is in support of deprecate ClassicUI feature
