### ISSUE TITLE
Named Transform ImagIe Servlet Crop percentage support

### ISSUE THREAD

**Issue by theorise** [Adobe-Consulting-Services/acs-aem-commons#879]
I am looking at the documentation for the [image transform servelets](https://adobe-consulting-services.github.io/acs-aem-commons/features/named-image-transform.html) and I see that the parameters required for cropping only support pixels.

Our content editing team use different sized images across the site and it would be really useful to be able to use percentage values as options so you could, for example, crop an image from the center.

**Comment by davidjgonzalez** [comment]
@theorise checkout the notation described in the comments of #819

`transforms="[crop:bounds=25%\,0\,50%\,100%,resize:width=1280]"`

This should be supported in the latest versions of ACS Commons.

**Comment by theorise** [comment]
@davidjgonzalez nice, thank you!
