### ISSUE TITLE
Service User Manager

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#892]
Basic idea:
* Simplify service user creation and service user configuration
* Ensure that service user exists
* Ensure that service user permissions are correct (edited)

ideally the code should be small and simple, nothing too complex; a set of rules similar to the "Day CQ ACL Setup Service"

-----

WDYT about 2 Config Factories... the first that will add/update .. and the 2nd that removes; not sure if the Remove being separate is overkill... we could have an "operation" property and consolidate?

com.adobe.acs.commons.util.impl.EnsureServiceUser-abc.xml
```
principalName="service-user"
ace="[type=allow;permissions=jcr:read,rep:write;path=/content/foo;rep:glob=/jcr:content/*]"
```

Im thinking this would

1. Create the service user if does not exist
2. Query for all rep:grant/rep:deny with principal name = principalName
3. Remove any ACE's that dont match the config
4. Add any ACE's that are defined in the config but don't exist

... Remove would remove all ACLs and the service user.

/cc @andrewmkhoury @joerghoh

**Comment by davidjgonzalez** [comment]
chatted w @andrewmkhoury  offline and the above config could be improved. I think the major tenants are:

1) Each Config should represent a single service user
2) Each Config can be comprise of multiple rows each "modeling" the ACE to create/destory

**Comment by davidjgonzalez** [comment]
Needs some cleanup and corner case handling .. but pretty much there...

![image](https://cloud.githubusercontent.com/assets/1451868/22296296/b61fbc10-e2e7-11e6-95c7-1efef35a1ce3.png)

@andrewmkhoury  @joerghoh WDYT should happen for bad data in the config? For example; if the provided "path" value doesn't exist a RepositoryException is thrown stopping the entire ensurance. I haven tested but expect oddities may happen if a privilege is is typo'd as well (doesnt match to real JCR priv). WDYT should happen in these cases?



[acs-aem-commons-content-3.6.3-SNAPSHOT-min.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/730084/acs-aem-commons-content-3.6.3-SNAPSHOT-min.zip)

**Comment by andrewmkhoury** [comment]
@davidjgonzalez If the path doesn't exist then log a WARN level message and apply all other ACLs.  Once they install that missing content path then it would get applied the next time the service is restarted.  Maybe makes sense to have a way to trigger a "re-ensuring" of the service users at runtime via JMX like you mentioned before.

**Comment by justinedelson** [comment]
should this issue be closed?
