### ISSUE TITLE
Stale workflows are not removed

### ISSUE THREAD

**Issue by bowerjd** [Adobe-Consulting-Services/acs-aem-commons#894]
I selected to remove completed, aborted, suspended, and stale workflows.  After it successfully ran I see there are still stale workflows.

**Comment by davidjgonzalez** [comment]
Is it possible for you to send a package of some stale workflows that aren't being removed? You can direct send to my davidjgonzalez@gmail.com if you'd rather not post publicly.

**Comment by davidjgonzalez** [comment]
@bowerjd This should be fixed via #897 -- what version of AEM are you using? (i added a SNAPSHOT for 6.0/6.1 on #897 comments)

**Comment by bowerjd** [comment]
I'm using AEM 6.0 SP3

**Comment by davidjgonzalez** [comment]
@bowerjd if you have a lower env you can try this out on please do and let me know how it works! 

I also added more debugging if you pop `com.adobe.acs.commons.workflow.bulk.removal.impl.WorkflowInstanceRemoverImpl @ TRACE`
