### ISSUE TITLE
Touch UI Multifield - Saved Userpicker values are not populated in the dialog

### ISSUE THREAD

**Issue by aanchalsikka** [Adobe-Consulting-Services/acs-aem-commons#896]
When userpicker field is used in the multifield(Touch UI), values are saved in CRX. But these values are not populated when the dialog is reopened.
Observed this issue on AEM 6.2 with ACS Commons 3.3.0

**Comment by agnitsevich** [comment]
Might this be related to changes in core AEM (and\or this one #934 too)? Check out:

/libs/cq/ui/widgets/source/widgets/wcm/SiteAdmin.Actions.js
function CQ.wcm.SiteAdmin.openPropertiesDialog(), line 369:
propsDialog.loadContent(path + "/jcr:content", ".1.json")

The nice second parameter is forcing the depth limit, which leads to siteadmin UI not seeing anything from page's contents that is stored at a level deeper than root plus one child - specifically, implementations of multifields that store properties in child nodes and not JSON.

**Comment by davidjgonzalez** [comment]
fixed
