### ISSUE TITLE
File encoding broken when trying to cache js/css files with Http Cache

### ISSUE THREAD

**Issue by tommix1987** [Adobe-Consulting-Services/acs-aem-commons#898]
Steps to reproduce:
Configure Http Cache to cache js/css, for example:

```<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
		  xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
		  jcr:primaryType="sling:OsgiConfig"
		  httpcache.config.order="1000"
		  httpcache.config.filter-scope="REQUEST"
		  httpcache.config.requesturi.patterns="[/libs/cq/(.*).css,/libs/cq/(*.).js]"
		  httpcache.config.request.authentication="both"
		  cacheKeyFactory.target="(&amp;(service.factoryPid=com.adobe.acs.commons.httpcache.config.impl.GroupHttpCacheConfigExtension)(config.name=groupsCacheExtensions))"
		  cacheConfigExtension.target=""
/>
```

Expected:
CSS/JS file gets cached and then gets served from cache.

Actual:
File gets cached but with broken encoding. After retrieving from cache it's non-human-readable array of bytes.
![image](https://cloud.githubusercontent.com/assets/11005984/22489596/37e29e98-e810-11e6-9b92-afb39d1b7de8.png)

**Comment by davidjgonzalez** [comment]
@tommix1987 it appears to be an issue w/ the handling of gzip content; i expect you have gzip enabled on the AEM HTML Library Manager.. Need to look at it more to figure out whats going / to fix .. Im not sure if the result is getting double-gzipped (i dont see how), or the bytes are getting mangled? The Content Encoding response header doesnt seem to be the problem...

**Comment by davidjgonzalez** [comment]
@justinedelson anything glaring wrt to this issue? I dont think its double gzipping, and the headers appear to be passed through "as is" .. the browser definitely can't match the response body content to the headers though ..

**Comment by tommix1987** [comment]
You can actually see the content of the cache broken already when you try
view it through jmx console.
Best regards
TS

12.02.2017 6:19 PM "david g." <notifications@github.com> napisał(a):

**Comment by davidjgonzalez** [comment]
@tommix1987  are you sure? I believe the cached value is the gzip contents; viewing the cached shouldnt show you the actual CSS/JS i dont believe? Where does the gzipping occur? at the servlet level or in an outer filter?
