### ISSUE TITLE
Delete Cache Replication Action Type not working and throwing warning

### ISSUE THREAD

**Issue by Souradeep123** [Adobe-Consulting-Services/acs-aem-commons#899]
We are using ACS AEM Commons 3.6 version on AEM 6.2 and used 2.8 version on AEM 6.0. Post upgrade to 6.2 and installing 3.6, we notice that the Dispatcher Flush Rules which had Delete Cache as Replication Action Type is throwing a warning as "Warn: No rights to replicate. Request for de/activation got issued for <path>", also the pages are not getting replicated. Please let us know how to resolve this one.
Attached are the logs for your reference.

[access.pdf](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/745712/access.pdf)
[request.pdf](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/745713/request.pdf)
[error.pdf](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/745714/error.pdf)

**Comment by davidjgonzalez** [comment]
`acs-commons-dispatcher-flush-service` requires `jcr:removeNode` privileges

**Comment by davidjgonzalez** [comment]
Fixed via #900
