### ISSUE TITLE
Workflow Remover - Scheduled Service - Ability to remove workflows older than a specific number of days

### ISSUE THREAD

**Issue by bowerjd** [Adobe-Consulting-Services/acs-aem-commons#910]
Currently the workflow remover tool has a scheduled service that can be configured to remove workflows older than a specific date, but that seems of limited use for a scheduled service.  Once it runs once and removes those workflows, it doesn't really need to be run again (unless I'm misunderstanding the workflow.older-than property). A more useful parameter would be to remove workflows older than a specific number of days.

**Comment by badvision** [comment]
I have a complete job purge script in my fork which I'm slowly moving over in time.  It's aimed more at cleaning Sling Jobs' clock entirely but I think adding this kind of thing wouldn't be too hard in theory.
