### ISSUE TITLE
Versioned ClientLibs not working with multiple publishers/dispatchers

### ISSUE THREAD

**Issue by wimsymons** [Adobe-Consulting-Services/acs-aem-commons#911]
The root problem is that any md5sum can be used to request a versioned clientlib. This causes an old version of the clientlib to be cached with the md5sum of a new version. I'll explain.

We currently have 4 publishers (P), each fronted with a dispatcher (D). When we deploy, we take the first P+D out of the load balancer, deploy, put them back in the load balancer, and do all other 3 P+D the same way. 

Because of this a newer version of the client libs is deployed on a part of our infrastructure.

Someone requests a webpage from the freshly deployed instance and gets the md5sum of the new clientlibs. The request for the clientlib comes in, but the load balancer requests it from another P+D. This one responds with the old clientlib, but caches it with the new md5sum.

As I can see, we only have 2 options:
1/ we take all P offline and serve stale content while we are deploying, or
2/ some servlet filter is written which checks if the md5sum matches with the cache data (as seen in JMX). If not, it responds with 404, which causes the clientlibs not to be cached with the wrong md5sum.

For us option 2/ would be the most viable option.

Also curious that nobody else has ever noticed this before?

PS: Using sticky load balancer is not an option.

**Comment by davidjgonzalez** [comment]
Is the underlying problem the in-memory versioned clientlibs is mis-populated? or that the wrong version is cached at dispatcher?  or both?

If youre do rolling deployments, arent you also purging the dispatcher caches after each Slice is upgraded? Traditionally /etc/clientlibs cache (at least, if not everything that is effected by code changes) is cleared after a deployment.

**Comment by wimsymons** [comment]
The in-memory is correct. The wrong version is cached at the dispatcher.

The point is, that when using Versioned ClientLibs, you never have to clear after a deployment.

**Comment by davidjgonzalez** [comment]
I think the intent was to set long-lived TTLs for browsers on them, but same difference (since you could potentially cache an old file for very long on a users browser).

Wrt to the 404 approach, wouldnt you be breaking the user experience during the upgrades? (404 on CSS and JS would have a devastating effect on mdoern sites)

**Comment by wimsymons** [comment]
Yes, I know, but the 404 would be cached shortly (say 10-30s), after which the correct JS/CSS would be delivered.

If I would need to block access to _all_ dispatchers from the LB when deploying, then I could serve stale cache, but if deploy goes wrong anywhere in the middle, this would mean I loose part of the compute power of my publisher farm (albeit 1/4th), and content would be stale until all publishers are up again. As we are a news agency, we can't afford that kind of downtime. (Deploying to all 4 publishers one at a time takes +- 20 min).

Looking at that, I think the worst would be serving a few 404's for a short time to a number of users. Anyhow, if a user sees a site without CSS, he would be refreshing until it's OK anyway.

**Comment by wimsymons** [comment]
Hi, I committed a PR to fix this. This is what we are using now as well. I did slightly modify the source code, as I now could change the VersionedClientlibsTransformerFactory by exporting the GenericCacheMBean interface and reference it in the sling filter. In our version of the code, we could not do that, but we could read the cacheEntry by doing a JMX call instead.

The contribution readme said something about a policy require but I did not find how to do this on the `@SlingFilter` annotation.

**Comment by justinedelson** [comment]
Unfortunately, the patch in #945 doesn't work in the case where the path contains a period. We don't have a good way of determining which segment of the path is the hash.

I'm still looking at options here. At present, I think the most logical approach is to change the hash to be a predictable pattern when the "Enforce MD5" option is selected. Something like:

    <clientlibpath>.ACSHASH<hash>(.min)?.(js|css)

**Comment by justinedelson** [comment]
@wimsymons any ideas?

**Comment by wimsymons** [comment]
Hi Justin,

In our case, we only use the filter for the clientlibs on the publisher, and we use clientlibs exclusively. So that covers it for us.

But if you want to cover all cases, I think your option is not so bad.

You could use a regex as well, but that would be more CPU intensive I guess. Something like `"[0-9a-f]{32}"`?.

What do you think?

Kind regards

Wim

**Comment by justinedelson** [comment]
Can't see a better (and reliable/universal) solution. Applying the pull request.

**Comment by dzmitry-kankalovich** [comment]
Apparently, this issue can hit you even if you are not doing B/G deployment, but rather simply replicate package from the author to multiple publishers with dispatchers in front and all behind the balancer. Seems like If there is notable enough difference in speed in clientlib build process between publishers and high enough traffic, you can run into such situation, that old JS file will be cached under the new name on dispatcher level. 

Our plan is to enforce MD5 check (I really think this should be enabled by default, there is no good reason to serve the wrong file under the new name) and rework current deployment approach to something more reliable.
