### ISSUE TITLE
ErrorPageHandlerImpl.findErrorPage(...) does not work on invalid pages

### ISSUE THREAD

**Issue by nc-andreashaller** [Adobe-Consulting-Services/acs-aem-commons#913]
If the requested resource is an invalid page without `jcr:content` node the search for the most appropriate error page in the method `ErrorPageHandlerImpl.findErrorPage(...)` is cancelled and the fallback mechanisms like the system error page is used.

To solve this I propose to change the method `ErrorPageHandlerImpl.findFirstRealParentOrSelf(SlingHttpServletRequest, Resource)` to return the `jcr:content` node and continue the search if no such node is found.

**Comment by nc-andreashaller** [comment]
Could someone verify this issue as a valid bug so I can create a PullRequest for the fix?

**Comment by davidjgonzalez** [comment]
This case should be handled; a PR w a fix would be great

**Comment by nc-andreashaller** [comment]
Opened https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/914

**Comment by davidjgonzalez** [comment]
Closed via #914
