### ISSUE TITLE
ACL packager should include only ACEs for configured principals or that option should be provided

### ISSUE THREAD

**Issue by smiroslav** [Adobe-Consulting-Services/acs-aem-commons#917]
Currently all access control entry nodes that are siblings,  are included in package, if it happens that among them there is one ACE with principal name matching one from ACL packager config. 

I want to include ACEs only for Alison, but resulting _rep_policy.xml, contains another user as well.

**Comment by davidjgonzalez** [comment]
IIRC this gets very hairy, very quickly, between how to packages 
* i dont think you can package JUST the ACE, maybe could packages the ACL with include/exclude rules?
* how do manage node-name conflicts (i package rep:policy/allow1 but destination has a different allow1)

Would allowing the AC Handling on the ACL package help -- this could still move over unwanted ACEs, so dont think it solves your problem.

Im open to suggestions, but i just dont know of a clean, safe way of doing this.

**Comment by smiroslav** [comment]
Hi @davidjgonzalez ,

I think  exclude rules could work. So nodes for principals that are not part of configuration are excluded. 

Regarding node name conflicts, I guess that it can happen even now.

**Comment by davidjgonzalez** [comment]
@smiroslav 
> Regarding node name conflicts, I guess that it can happen even now.

is it "guaranteed" to happen now? whatever is coming in will supersede the target (while respecting AC Handling) 

The concern i have at the ACE level is the uncertainty of what is going to happen to existing aces and/or ordering.

**Comment by justinedelson** [comment]
I'm not sure that include/exclude rules work for ACL child nodes. Would suggest testing this *before* implementing something.

However... regarding the node name conflicts, this is IME not an issue

In https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/feature/6.2-compatibility/content/src/main/content/jcr_root/_rep_policy.xml, for example, we have `allow`, `allow0`, etc. but these actually get created as `allow6`, `allow7` or something like that based on the fact that there are already allow nodes in the repository.
