### ISSUE TITLE
QueryHelper's List delimiter is too broad

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#918]
Lists are intended to support lists of Resources, and thus should handle valid resources paths. Currently the list splitting is overly broad (appears to be a copy-down from Querybuilder splitting) and prevents resources paths that have spaces from being split properly (along w `,` and `;` )

[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/util/impl/QueryHelperImpl.java#L89

**Comment by davidjgonzalez** [comment]
@nateyolles thoughts on this? IIRC you initially defined these delimiters in QueryPackager (which I moved to QueryHelper for general use)

**Comment by nateyolles** [comment]
@davidjgonzalez As per our conversation with the Document Cloud team that uses this feature heavily, this change should make everyone happy.

**Comment by davidjgonzalez** [comment]
Fixed in latest
