### ISSUE TITLE
Mispelled Category and missing Angular.js file

### ISSUE THREAD

**Issue by mpongelupe** [Adobe-Consulting-Services/acs-aem-commons#921]
## Mispelled Category on embed Clientlib

On [**/apps/acs-commons/components/utilities/quickly/clientlibs/.content.xml**](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/components/utilities/quickly/clientlibs/.content.xml#L27), it is specified the following category as embedded: **acs-commons.json2**. However, this category seems to be mispelled. The correct category seems to be **[acs-commons.json](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/etc/clientlibs/acs-commons/vendor/json/.content.xml)**.

## Missing Angular.js file

On [**/etc/clientlibs/acs-commons/vendor/angularjs/v1.2/all/js.txt**](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root//etc/clientlibs/acs-commons/vendor/angularjs/v1.2/all/js.txt#L7), the **angular-messages.min.js** is referenced. However, this file is not present under the **[etc/clientlibs/acs-commons/vendor/angularjs/v1.2](https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/master/content/src/main/content/jcr_root/etc/clientlibs/acs-commons/vendor/angularjs/v1.2)** folder.

**Comment by davidjgonzalez** [comment]
@mpongelupe thanks for reporting!

**Comment by mpongelupe** [comment]
Hi @davidjgonzalez ,

thanks for your reply! 
Is the problem with the **angular-messages.min.js** missing file being fixed as well?

**Comment by davidjgonzalez** [comment]
@mpongelupe thanks! missed that .. Fixed via: 7d0a766b6f6faa6a46a892194379119edbeba9a4

Would nice to upgrade to v1.6 .. spent a little time doing it, but requires a number of updates across the Commons utils ...
