### ISSUE TITLE
Removing deprecated Code From XSS-Functions

### ISSUE THREAD

**Issue by jt-jayati** [Adobe-Consulting-Services/acs-aem-commons#922]
In AEM 6.2 use of com.adobe.granite.xss.XSSAPI is deprecated and org.apache.sling.xss.XSSAPI should be used instead.
However https://adobe-consulting-services.github.io/acs-aem-commons/features/xss-functions.html is still using deprecated API even in verion 3.6.x.

Deprecated code needs to be updated in Taglib for XSSFunctions.

Here:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/acs-aem-commons-3.6.2/bundle/src/main/java/com/adobe/acs/commons/xss/XSSFunctions.java

**Comment by davidjgonzalez** [comment]
Fixed via e05b7e4
