### ISSUE TITLE
Support for immutable property in dispatcher-ttl module

### ISSUE THREAD

**Issue by insideaem** [Adobe-Consulting-Services/acs-aem-commons#933]
It would be good to add support for the immutable property in the dispatcher-ttl module for the Cache-Control header.

Example:
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
    xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="sling:OsgiConfig"
    filter.pattern="[/content/site/products/(.*)]"
    max.age="60"
    immutable="{Boolean}true"
    />

Will render the header: "Cache-Control: max-age=60, immutable"

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/

**Comment by davidjgonzalez** [comment]
+1

**Comment by davidjgonzalez** [comment]
@insideaem were you thinking about contributing this?

+ @bstopp since he initially wrote the feature

**Comment by insideaem** [comment]
Not really, Just a suggestion of mine.
