### ISSUE TITLE
RTE in multi field displays blank even if values present

### ISSUE THREAD

**Issue by rohan-pulekar** [Adobe-Consulting-Services/acs-aem-commons#934]

**Comment by manisha199010** [comment]
Hi @rohan-pulekar, @davidjgonzalez 

I had tried reproducing this issue. But whether I use JSON_STORE or NODE_STORE type structure, I get the values in rte.
Below are the snapshot for the same:
1. JSON_STORE
![image](https://user-images.githubusercontent.com/12714330/26921530-f9847c76-4c59-11e7-9567-4a8a3f11eb41.png)
And in crx it is:
![image](https://user-images.githubusercontent.com/12714330/26921596-385a6b18-4c5a-11e7-8c72-1c0ff94be1cd.png)

2. NODE_STORE
![image](https://user-images.githubusercontent.com/12714330/26921951-3c49321c-4c5b-11e7-80a0-59e73c93d8bd.png)

And in crx-de
![image](https://user-images.githubusercontent.com/12714330/26921982-563aaff2-4c5b-11e7-8594-13e2dd683085.png)

Also, I tried the same in classic UI(as it is not specified anywhere), I got the same result:
![image](https://user-images.githubusercontent.com/12714330/26923199-fdc60b7e-4c5e-11e7-8648-3452da0c06f0.png)

In crx-de:
![image](https://user-images.githubusercontent.com/12714330/26923246-274bbb38-4c5f-11e7-9fb8-7e3cdf3221cf.png)

**Comment by arunimasahu** [comment]
Hi manisha199010 ,
I am facing the same issue. The Rte in multifield is not retaining the values on re-opening the dialog. Could you please share your package . Also let me know which AEM version you are using.

**Comment by manisha199010** [comment]
Hi @asahu02 ,

I had used AEM 6.2. 
And this is the touch UI dialog I'm using:
[touchui_dialog.txt](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1084581/touchui_dialog.txt)
