### ISSUE TITLE
Multifield not working with multiple tabs and nested multifield.

### ISSUE THREAD

**Issue by AmoghDaryapurkar** [Adobe-Consulting-Services/acs-aem-commons#935]
Attached is my cq:dialog xml. I tried almost every possible way to make it work but still no luck.
[cqdialog.txt](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/866802/cqdialog.txt)

**Comment by 11289** [comment]
Does anyone get a chance to look at it? We are running on some urgent need.

**Comment by poojachauhan** [comment]
Can you please specify what exactly is not working in your component's dialog. I used your shared dialog.xml . Working fine in my insatnce.

**Comment by 11289** [comment]
Can you paste your dialog snapshot over here? There should be multiples tabs in dialog. In my case only one tab is visible with Nested multifield.

**Comment by poojachauhan** [comment]
I got three tabs in dialog. second and third tabs have the multifields. Below are the screenshots 

![image](https://user-images.githubusercontent.com/23373829/29155156-97098fde-7db7-11e7-9e55-4cdd83a2742e.png)
![image](https://user-images.githubusercontent.com/23373829/29155178-b456f66c-7db7-11e7-963c-83efeb9d1dab.png)
![image](https://user-images.githubusercontent.com/23373829/29155183-c0bb7cfc-7db7-11e7-9a69-bc744341469b.png)

**Comment by 11289** [comment]
Hi Pooja, 
I have updated the code and added nes
[nested-multifiled-tabs-touch.txt](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1218906/nested-multifiled-tabs-touch.txt)
ted multifield structure in attached pom. 

Tab1 is with simple text fields. Tab2 is with nested multifield and Tab3 is again with Nested multifield. But, if you check below screen shots Tab 3 fields are not visible because I have nested multifiled structure in Tab2.

![image](https://user-images.githubusercontent.com/8004528/29229303-91310b10-7eab-11e7-9d0b-e5839a691d9e.png)

![image](https://user-images.githubusercontent.com/8004528/29229521-e78ff614-7eac-11e7-9b12-918abf78fa9c.png)

![image](https://user-images.githubusercontent.com/8004528/29229543-f9a4c0aa-7eac-11e7-87bd-2246b9acdd77.png)

Thanks,
Amogh

**Comment by poojachauhan** [comment]
@11289 yes, it is a bug. If there is any nested multi field , fields of next tab are not visible.
One temporary solution could be , if you have nested multifield in one tab only, make that tab as a last last tab.

**Comment by AmoghDaryapurkar** [comment]
@poojachauhan Thanks for the info. But, is there any other solution if I want to use nested multifield inside multiple tabs. I have tried changing a couple of things in the multi-field-touch.js, but nothing seems working. 

It would be a great help if you can provide some workaround to make this work.

**Comment by poojachauhan** [comment]
@AmoghDaryapurkar  use sling:resourceType as   "granite/ui/components/coral/foundation/form/multifield" for inner multifileds. It will work .

**Comment by AmoghDaryapurkar** [comment]
This worked like a charm @poojachauhan. 

Thanks Pooja.

**Comment by SekharSareddy** [comment]
@poojachauhan, Thanks for the info.
After using of "granite/ui/components/coral/foundation/form/multifield" for inner multifileds, it fixed the dialog issue. But, it's not recognized as "multifield" with below line, while iterating over outer multifield fields.

 //may be a nested multifield
$nestedMultiField = $field.find("[data-init='multifield']");

Can you please suggest a solution for this.

**Comment by BHLORQ** [comment]
@SekharSareddy, did you find a way to fix it?

**Comment by AmoghDaryapurkar** [comment]
Hi @SekharSareddy,

Use the same foundation multifield for all the outer and inner fieldset and do the following:

1. Create an overlay of /libs/granite/ui/components/foundation/form/multifield/render.jsp

2.Modify `<script class="js-coral-Multifield-input-template" type="text/html"><% include(field, cmp, request); %></script>`
 to `<template class="js-coral-Multifield-input-template" type="text/html"><% include(field, cmp, request); %></template>`

Thanks,
Amogh

**Comment by ireasor** [comment]
@AmoghDaryapurkar Unless I am missing something here, it seems that the issue you are reporting is in /libs/granite/ui/components/coral/foundation/form/multifield.  This is product code that is not part of ACS AEM Commons.  If you would like to report an issue with OOTB code, your best option is to open a case with Adobe support at https://daycare.day.com.

**Comment by AmoghDaryapurkar** [comment]
@ireasor I just posted a comment on the issue Sekhar is facing. The actual issue is related to ACS-COMMON and not with the daycare.

Also, Pooja just gave us the workaround to resolve nested multifield issue temporary which is not 100% accurate.

Thanks,
Amogh

**Comment by GonzaloCalandria** [comment]
I'm having the same issue... second tab is blank with the first tab as a nested multifield.
Does anyone fixed this?

**Comment by gauravpujari** [comment]
I'm also having same issue, I added nested multifield in second tab and my third tab shown blank.
As suggested one of the above comment, if we use "granite/ui/components/coral/foundation/form/multifield" and for other tab field if we use for ex.
"granite/ui/components/foundation/form/textfield" then is this create any issue?

Please suggest.........

**Comment by AneleAndrew** [comment]
Hi Guys

Has anyone found a fix for this.
