### ISSUE TITLE
Rename master and feature/6.2-compatibility branches

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#938]
With the upcoming release of AEM 6.3, I think we should revise our branch names.

`master` - should be the 6.2/6.3 branch (what is now `feature/6.2-compatibility`)
`compat/6.0` - should be the 6.0/6.1 branch (what is now `master`)

I'm not confident that github will correctly handle the open pull requests if the baseline branch name changes, so those may now need to be merged manually (or just get cleaned up).

**Comment by davidjgonzalez** [comment]
So, we would limit official support to 6.3/6.2 .. and if we feel like, we'd cherrypick critical fixes from 6.2/6.3 back to 6.0/6.1 ?

**Comment by justinedelson** [comment]
Well, we don't have any "official" support :)

The way I think of it is that our primary focus should be on the 6.2/6.3 branch. As such, that should be "master". We can still do releases of the 6.0/6.1 branch, but I expect those to slow to a crawl.

**Comment by davidjgonzalez** [comment]
@justinedelson +1 on official ;)

Ah - so we'd basically do exactly what we do today, we are just changing branch names. Meaning...

* Anything that works on 6.0+ goes into `compat/6.0` and merge -> `master`
* Anything that works only in 6.2+ goes into `master`

Works for me.

**Comment by justinedelson** [comment]
More broadly... our historical goal has been to have compatible releases with the current and past AEM releases. We are on the verge of having compatibility with 4 versions which I just don't think is sustainable/healthy.

**Comment by justinedelson** [comment]
but yes, this is mostly about perception than any dramatic change.
