### ISSUE TITLE
AEM 6.2 RTE in Multifield not storing Hyperlinks

### ISSUE THREAD

**Issue by utsavnirgudka** [Adobe-Consulting-Services/acs-aem-commons#940]
Hi,

I am using ACS Commons Version 3.6.0.
I am facing issue with RTE in multifield. When i select a link or enter external link in a RTE in multifield, it is not storing the link value as href, instead it is creating blank a tag (like <a> </a>).

Any help is appreciated. 

Thanks

**Comment by Akuyi** [comment]
Had the same problem when generating custom plugins for RTE. 
Try _rte_href="..." instead of href="..."

This solved the problem for me

**Comment by davidjgonzalez** [comment]
Thanks @Akuyi!
@utsavnirgudka did this comment resolve the issue for you? Can we close this?

**Comment by trines123** [comment]
@Akuyi i am facing similar kind of issue and we are using ACS Commons version 3.9.0. Can you say where did you changed href to _rte_href? I did  not get that. 

Can you please elaborate a bit?

Thanks

**Comment by chada23** [comment]
@davidjgonzalez Hi David, would you be able to help me with this issue? When rich text component not added in acs-aem-commons multifiled, the link works fine but when we use RTE component with  multifiled then it is removing href when it is saving the data. This behaviour will not happen when you add links in RTE in the first save but when you open the dialog and close it again then it will remove the href. This is happening even with OOTB RTE component.

We are using Touch UI dialog and acs aem commons version is 3.9.0 , AEM version is AEM 6.2 SP1. 

Thanks for any suggestion or help.

**Comment by mhomaid** [comment]
@davidjgonzalez We are facing the same issue. RTE in multifield does not save the links when nested.

Adobe Experience Manager, Version 6.2.0.SP1-CFP8 
ACS 3.13.O
