### ISSUE TITLE
HTTP Cache invalidates complete config's instead of 1 key

### ISSUE THREAD

**Issue by dimio111** [Adobe-Consulting-Services/acs-aem-commons#947]
Hello,

I am having problems with the HTTP Cache configuration.
Every time a change is detected that is applicable for one of the cache configs, then that complete config is invalidated in the memory cache.

Our structure is a bit like this:
/content/site/language/year/month/day/page.html

Case:
I have 2 pages in my HTTP cache.
1. /content/site/language.html
2. /content/site/language/year/month/day/page.html

when i edit a component on 1 of those 2 pages, they both get invalidated when they are in the same cache configuration.

This is a sample config that looks like the one we use.
![screen shot 2017-04-03 at 07 14 16](https://cloud.githubusercontent.com/assets/8222510/24596133/37de41ce-183d-11e7-9d60-31da16ccaba1.png)

We could use multiple configs so they are invalidates separately, but this would result in a lot of configurations since our content tree is date based.

**Comment by davidjgonzalez** [comment]
@dimio111 could you throw logging at DEBUG got `com.adobe.acs.commons.httpcache` and run it again?

I think i see the problem - it appears the Group extension builds off the actual RequestURI (complete w selectors, extensions) where-as the ResourceType extension builds off the resource path.

Need to stew on in for a bit and see if there is a simple, safe way to adjust so INVALIDATIONS can match configs on resource path, but match cache REQUESTS on full URIs.

/cc @Sivaramvt

**Comment by Jarflux** [comment]
I'm experiencing the same problem!

**Comment by davidjgonzalez** [comment]
I was looking at this some more, and i think this going to have to follow a convention of invalidating at the hierarchy node level ... for example

* If i request `/content/some/page.html` ... it will be cached
* If i modify `/content/some/page/jcr:content/root/my-component`, trying to match on resource path's wont work:
  * `/content/some/page/jcr:content/root/my-component` != `content/some/page`

I think we'll have to invalidate changed resources via the node above the `jcr:content` node ..  for mounted resources, this will have sweeping effects.

thoughts?

**Comment by davidjgonzalez** [comment]
Fixed in latest version; it will now invalidate based on the closest hierarchyNode, so changes to 

`/content/page/jcr:content/foo`'s invalidation key is `/content/page`
