### ISSUE TITLE
Dynamic RTE externalStyleSheets property not including correct file name

### ISSUE THREAD

**Issue by imransaeed** [Adobe-Consulting-Services/acs-aem-commons#95]
I am using the dynamic RTE component and all the configurations work with the script slingscriptinclude as follows

``` xml
<text jcr:primaryType="cq:Widget" 
 script="rte.default.text.json?externalStyleSheets=/etc/designs/myapp/clientlibs/css/richtext.css"
                    xtype="slingscriptinclude">
```

However, the RTE in edit mode is not including the correct stylesheet and is rendering a link as follows:

``` html
<link type="text/css" rel="stylesheet" href="/etc/designs/myapp/clientlibs/css/richtext" media="screen">
```

as you see, the link reference points to the file without the css extension so this obviously does not work.

If I check the net-traffic from chrome, I see a request like:

``` html
http://localhost:4502/content/.../RTE/jcr:content/.../richtext.rte.json?externalStyleSheets=/etc/designs/myapp/clientlibs/css/richtext
```

which suggests that the .css extension has been trimmed off before being passed to the json filter. If I change the request and append the .css extension then the configuration is rendered correctly.

All other parameters like width, height, etc works ok and the issue is only with the .css parameter in externalStyleSheets parameter. 

Is this a bug with dynamic RTE config?

PW: I am following the guide on: http://adobe-consulting-services.github.io/acs-aem-commons/features/dynamic-rte-configurations.html

**Comment by lgerndt** [comment]
We're using this technique.  But I also wanted to add a listener to the *richtext* but can't since it's not that xtype, it's *slingscriptinclude*.  So how would I add a listener?

**Comment by justinedelson** [comment]
@lgerndt If you want a listener which is specific to a single dialog (vs. all instances of the same RTE), I believe you can do that attach that at the dialog level. More JS code for sure, but that's the tradeoff.
