### ISSUE TITLE
ACS Commons Error Page Handling Issues On Dispatcher

### ISSUE THREAD

**Issue by y0050915** [Adobe-Consulting-Services/acs-aem-commons#957]
I was wondering if someone could explain why ACS Commons Error Handler is not functioning properly on the Dispatcher?

Here are some of the tests I have done:

Accessing the publisher with the following URL's it will resolve the en-us specific 404 page properly:

http://publisher:4503/content/en-us/nopage
http://publisher:4503/content/en-us/products/nopage.html

When I access the dispatcher with the URL's below it does not resolve the page with the custom 404, but instead with a blank page (Console does show 404). I can set the error-page.system-path to point to the /content/en-us/404 page and it would behave correctly as a catch all.

http://qa.crown.com/content/en-us/nopage
http://qa.crown.com/content/en-usnopage

When I access the dispatcher with the following URL's it will resolve the 404 page (Seems the period is needed after en-us)
http://qa.crown.com/content/en-us.htmlblabla
http://qa.crown.com/content/en-us.nopage
http://qa.crown.com/content/en-us/products.nopage
http://qa.crown.com/content/en-us/products.htmlblabla

On the dispatcher I did set DispatcherPassError to 0 so that the dispatcher spools all error responses to AEM. I have also tested this without any rewriterules and it results with the same issue.

We're currently using ACS Commons 2.8.0, but have tried the latest relase (2.10.0) in another environment, but I'm not having much luck with the latest version as it seemed to have broken the Author and Publisher region specific 404, looking at the logs it tries to resolve the "System error page" /content/error.html rather than the one under /content/en-us/error/404. Dispatcher obviously still does not work.

**Comment by davidjgonzalez** [comment]
@y0050915 few questions; which page is the `errorPages` property on? I assume its on `/content/en-us/jcr:content@errorPages`

If this is true, then requests' to `/content/en-usnopage` should use the system page, however requests to `/content/en-us/nopage`use the errorPages defined on the `en-us` page.

I'm surprised `/content/en-us/nopage` doesnt work though ...

**Comment by y0050915** [comment]
Thanks for that information. I was able to resolve the issue. It was something to do with how /etc/map was configured to remove /content so I used the Apache Sling Resource Resolver Factory.

**Comment by prathyusha1509** [comment]
Hi ,

I am facing similar issue in calling custom pages using acs-commons error handler in dispacther url. Our dispacther url is https://domainname/junction/content/abc/home.html. In Author and Publish my custom error pages are coming up for 404 and 500, but in the end url default error message from apache shows up but not my custom error pages. Can anyone suggest any solution on this? Should I need to make any changes in dispatcher configurations?

@zhengy370  Can you elaborate what you have done to make it working?

**Comment by mkovacek** [comment]
Hi, currently I'm facing the same issue on the dispatcher.
I have error pages set on /market/language with system fallback to cover /some-non-existing-page
It works fine directly on publish, but on dispatcher /some-non-existing-page is blocked and default web server 404 is responded.
