### ISSUE TITLE
Add sharpening / unsharp options for Named Transform Image Servlet

### ISSUE THREAD

**Issue by x2jitendra** [Adobe-Consulting-Services/acs-aem-commons#958]
Feature Request:  It would be nice if the Named Transform Image Servlet supported sharpening / unsharp mask options... Similar to the Dynamic Media options (https://docs.adobe.com/docs/en/aem/6-2/author/assets/dynamic-media/managing-assets/best-practices-for-optimizing-the-quality-of-your-images.html)

**Comment by davidjgonzalez** [comment]
Why does this code seem to accept 4 params as the transform param, however only the first 2 are ever used?

**Comment by manisha199010** [comment]
@davidjgonzalez  I had read from the [doc](https://marketing.adobe.com/resources/help/en_US/s7/is_ir_api/is_api/http_ref/r_op_usm.html
) that unsharp-mask can take 2 more params apart from amount and radius. ie. threshold and monochrome. But Layer API accepts only 2 params i.e. amount and radius.

Thus, for those, who sharp their image with 2 as well as with 4 parameters get their image sharp. 

Now, I had changed it for accepting 2 parameters only. Please have a look.

**Comment by justinedelson** [comment]
@manisha199010 that document refers to the Image Server (Dynamic Media/Scene7). The Layer API is here: https://docs.adobe.com/docs/en/aem/6-2/develop/ref/javadoc/com/day/image/Layer.html
