### ISSUE TITLE
Require Java 8

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#961]
As mentioned in #956, I think we should require the use of Java 8 for ACS AEM Commons releases moving forward. The only supported platform for AEM 6.2 which requires Java 7 is IBM AIX. I think the customer base there is small enough that it is not worthwhile to for us to continue to compile for Java 7.

**Comment by davidjgonzalez** [comment]
+1

**Comment by cwoeltge** [comment]
+1

**Comment by justinedelson** [comment]
announced on Twitter: https://twitter.com/justinedelson/status/852589691681488896

so now it's official :)
