### ISSUE TITLE
 Issue while using Acs commons Versioned-Clientlibs with StaticReferenceRewriter

### ISSUE THREAD

**Issue by flmylv2005** [Adobe-Consulting-Services/acs-aem-commons#963]
We are using the versioned clientlibs of ACS commons. every thing is working as expected.
When we are using Acs commons StaticReferenceRewriter with Versioned Clientlibs then versioned-clientlibs stopped working.

We observed that if we change the order of versioned clientlibs later to StaticreferenceRewriter  then its started working but again StaticreferenceRewriter stopped working.

AEM 6.1
ACS Commons Version 2.2

1) Create  versioned-clientlibs configuration with order 1
2) Create SaticReferenceRewriter configuration with order 2 Versioned-clientlibs wont work.

**Comment by justinedelson** [comment]
The Versioned Clientlibs rewriter has to go before the Static Reference rewriter. This is in the documentation - http://adobe-consulting-services.github.io/acs-aem-commons/features/static-reference-rewriter.html.
