### ISSUE TITLE
AEM Environment Indicator does not work on AEM 6.3 TouchUI

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#975]
![image](https://cloud.githubusercontent.com/assets/1451868/25277223/c623bce8-266b-11e7-9791-70590aa7cb0f.png)

**Comment by davidjgonzalez** [comment]
Previously logged at #973

**Comment by justinedelson** [comment]
I closed #973 in favor of this one since you had added a nice screenshot...
