### ISSUE TITLE
Ensure Service User - Documentation Issues & Question

### ISSUE THREAD

**Issue by ichirital** [Adobe-Consulting-Services/acs-aem-commons#978]
Hi all,
 
I have struggled to get this service to work on AEM 6.2 SP1 and while doing this I found a few issues with the documentation at [1].
 
1. FIXED: It indicates it's available since version 3.10.0, while the latest release is 3.8.2. I find this confusing.
2. FIXED: The OSGI configuration is named /apps/my-app/config/com.adobe.acs.commons.**util**.impl.EnsureServiceUser-myServiceUser. It needs to be /apps/my-app/config/com.adobe.acs.commons.**users**.impl.EnsureServiceUser-myServiceUser for the config to be picked up.

3. There is no mention of giving specific permissions to the **acs-commons-ensure-service-user** which I found in [2]. I have given them ALL on the /home/users path, not sure if this is what I was supposed to do, however not doing this resulted in the confusing error message attached (_Ensure Service User requires at least 1 privilege to apply._). Is this the correct approach that I took?
 
For reference, my config:
 
com.adobe.acs.commons.users.impl.EnsureServiceUser-i18n-service.xml
 
```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
    xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="sling:OsgiConfig"
    principalName="i18n-service"
    type="add"
    ensure-immediately="{Boolean}true"
    aces="[type=allow;permissions=jcr:read;path=/apps/i18n]"/>
 ```
Error message without the action at #3 - see attachment.
[acs-error.txt](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/947476/acs-error.txt)
 
Thank you,
 
Regards,
Irina
 
[1] https://adobe-consulting-services.github.io/acs-aem-commons/features/ensure-service-users/index.html
[2] https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/acs-aem-commons-3.8.2/bundle/src/main/java/com/adobe/acs/commons/users/impl/EnsureServiceUser.java

**Comment by davidjgonzalez** [comment]
Fixed 1 and 2; 
I expect updating the /home/users/rep:policy to 

```
  <allow2
            jcr:primaryType="rep:GrantACE"
            rep:principalName="acs-commons-ensure-service-user-service"
            rep:privileges="{Name}[rep:userManagement,jcr:addChildNodes]"/>
```

will fix #3

**Comment by justinedelson** [comment]
Ugh. Is updating the ACE really necessary? This seems like something the user manager should take care of.

**Comment by justinedelson** [comment]
I mean, if it is, so be it. but blah...

**Comment by davidjgonzalez** [comment]
@justinedelson havent actually tried yet; we shall see.

**Comment by davidjgonzalez** [comment]
IDK - looks like rep:UserManagement is sufficient on `/home/users` but had to modify permissions on `/` to allow `jcr:read,rep:write,jcr:readAccessControl,jcr:modifyAccessControl`

Note sure why we were seeing the UserManager exceptions tho? I tested on a vanilla 6.3 pre-load and works. Tried a variety of combos for principal locations so UserManager would have to create intermediate folders.

Also, accidentally pushed changes direct to master: 83a6193bcff0738e51890f2163e85ba7b538338e

**Comment by davidjgonzalez** [comment]
@ichirital found some more bugs in the docs; the problem w the aces is the key is `privileges` not `permissions` ... so

```
...
aces="[type=allow;privileges=jcr:read;path=/apps/i18n]"/>
```

Also, i added a guard-rail for the principalName in this fix to always try to put the service user under `/home/users/system` since thats required by Oak; basically any path-like principal name will be stored as a relative location under `/home/users/system` (unless it starts w `/home/users/system` which will then just use that location) .. i've updated the docs to reflect this.

**Comment by ichirital** [comment]
Hi @davidjgonzalez, I've changed my config to use "privileges" and pulled the latest from master. It now works as expected. 

However, this feature does not seem to be fully functional on 3.8.2.
Any idea if we could have a 3.8.3 release soon?

Thanks,
Irina

**Comment by davidjgonzalez** [comment]
@ichirital  thank you for confirming. 

You can get 3.8.4 w/ this fix here: https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases/tag/acs-aem-commons-3.8.4

It should be in adobe public repo sometime tomorrow..
