### ISSUE TITLE
Icon Picker - Inconsistent code <> documentation

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Consulting-Services/acs-aem-commons#982]
https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/icon-picker/index.html
States:
"In version 2.1.0 the default fa CSS class has been removed. If you have created a custom Font Awesome generic list using 2.0.0, you will need to prefix each value with the fa CSS class."

This commit however:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/432a45aab7f4d03cd9dd6bb447d920edd540b6b5
Puts back the "fa"-class..?

**Comment by jurgenbrouwer** [comment]
In addition: I've used this component for a custom list/font and now all my values are prefixed with "fa ".
![screen shot 2017-04-28 at 13 15 02](https://cloud.githubusercontent.com/assets/1295167/25526635/bb5dfad6-2c14-11e7-8c4d-4f2a764758c0.png)

When undoing the changes of the commit mentioned above, both my custom list and the provided Font Awesome list work as expected.

**Comment by davidjgonzalez** [comment]
@kuckmc01 or @justinedelson  thoughts on this? Was [1] intentional?

[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/432a45aab7f4d03cd9dd6bb447d920edd540b6b5#diff-1b1f20933ee382aa8bdb011eb34dfd1aR236

**Comment by kuckmc01** [comment]
I was under the impression that font awesome required the "fa" prefix. We can remove the automatic prefixing.

**Comment by kuckmc01** [comment]
PR in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1028

**Comment by davidjgonzalez** [comment]
This issue was fixed via #1028
