### ISSUE TITLE
Generic Lists Touch UI Support

### ISSUE THREAD

**Issue by eriweiss** [Adobe-Consulting-Services/acs-aem-commons#986]
Has any work been done for converting generic list authoring and management into the touch, so that it can be integrated with the tools flyout?

Seems like the biggest hurdle will be creating a management screen, as the new UI doesn't seem to have a uniform place to manage "page-like" resources that fall under /etc (like /miscadmin)

**Comment by justinedelson** [comment]
Pinning this because we are eventually going to need to do this.

**Comment by badvision** [comment]
So what is needed is a tools page then?   I know that there is no /miscadmin which lets you create sub-pages, but creating a generic console-like page or reusing the Shell UI abstraction might be the way to go here.

**Comment by justinedelson** [comment]
we need a console and a list editor. AFAIK, the page editor only operates on paths under /content. Presumably we will also need to migrate the lists (and a whole bunch of other stuff) to /conf.

**Comment by reusr1** [comment]
@justinedelson @badvision @davidjgonzalez @josephrignanese should the generic list be replaced by using content fragment models instead?

**Comment by badvision** [comment]
Nope.

**Comment by badvision** [comment]
I don't think this will be terribly hard to rewrite in TouchUI

**Comment by badvision** [comment]
If we forego any kind of conversion tooling, this isn't a large effort I think.  Are you folks ok to say people have to manually update their old lists to this version if they want to keep editing?   e.g. they have to move their generic lists into the new /conf location and update existing dialogs to point to the new list paths?

**Comment by badvision** [comment]
@davidjgonzalez raises a good point that /conf might be a sub-par place to put the generic lists as opposed to /content.  Does anyone have a strong opinion on this?

**Comment by justinedelson** [comment]
TBH, I don't fully understand why /etc needs to be changed here.

**Comment by badvision** [comment]
You should ask Justin from Sep 29, 2017. 😝

**Comment by davidjgonzalez** [comment]
I think(?) the issue revolves around moving away from ClassicUI/miscadmin UI. Do we have a TouchUI interface that can be used to CRUD/Publish/Workflow Generic List pages? 

Or are you suggesting keeping everything in /etc, and creating a new TouchUI interface (ala TouchUI SiteAdmin) that exposes these features?

If we go through the trouble of creating a new UI etc, it seems reasonable (assuming we have the time) to store the content in a more appropriate place (as /etc has fallen out of favor with the product).

**Comment by badvision** [comment]
The approach I'm taking is to clone the sites console and put the cloned shell experience and all the necessary modified components that drive that experience under /apps/acs-commons/components/utilities/generic-list-console.  This is essentially the same familiar shell used in many places, but just cut down to managing folders and generic lists.

**Comment by badvision** [comment]
Generic lists would still be pages as they are today, but the "create page" button will just be renamed to say "Create Generic List" so it feels more obvious to the user.

**Comment by badvision** [comment]
The only part unanswered is where do we want/recommend people to create their generic lists?

**Comment by justinedelson** [comment]
> Or are you suggesting keeping everything in /etc, and creating a new TouchUI interface (ala TouchUI SiteAdmin) that exposes these features for Generic Lists IN /etc?

The UI itself should be in /apps, right? At that level, where the lists are stored shouldn't matter - it is abstracted away by the UI.

> If we forego any kind of conversion tooling

This is, I think problematic. Which is why (contrary to me from 2 years ago), I would suggest to at least start with a new UI which writes to the existing location.

**Comment by badvision** [comment]
Ok, easy enough.  I just have to change the root from /conf to /etc, basically.

**Comment by davidjgonzalez** [comment]
I assumed that storing the Generic Lists in /conf would lend to leveraging AEM's "/conf UI", which is strongly coupled to /conf IIRC. 

If this is a net new UI either way, makes sense. I vote for /etc over /conf - and we can move later  if/when we find the "proper" place for this type of content.

**Comment by justinedelson** [comment]
> I assumed that storing the Generic Lists in /conf would lend to leveraging AEM's "/conf UI", which is strongly coupled to /conf IIRC.

Ah, this was a detail I didn't get. I thought we were talking about an entirely new from-scratch console (kind of similar to the workflow models console).

**Comment by badvision** [comment]
It is a "new" console, but rather in the sense that I took /sites.html and cloned it so I could change the buttons and remove stuff (like versions, launches, etc) that are not useful for generic lists.   There's no safe way to add to an existing shell without a potentially risky (to some, but not all) overlay so this was the safer option for a software project this widely used.

**Comment by joerghoh** [comment]
The location where to store these "generic lists" is quite obvious. If it is content (that means it could be subject to translation and MSM processes) we should definitely store it in /content instead of /conf. And /etc should be avoided anyhow.

**Comment by joerghoh** [comment]
what's the status here? has it been merged already?

**Comment by synox** [comment]
This was released. See https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases/tag/acs-aem-commons-4.3.4
