### ISSUE TITLE
/editor.html requests parsys specific designs rather than the template design resulting in many 404s when parsys are nested

### ISSUE THREAD

**Issue by modeckimellett** [Adobe-Consulting-Services/acs-aem-commons#989]
In AEM 6.2 with ACS Commons 3.8.2 installed, if a component with a dynamic path (such as one in a parsys) contains a parsys, /editor.html makes an ajax call for a design for that specific parsys which results in a 404.

These requests are being made by /apps/acs-commons/touchui-widgets/source/touchui-configure-parsys-placeholder.js Line 130 - https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/source/touchui-configure-parsys-placeholder.js#L130

How to reproduce?
To prep, we'll need to create a component with a parsys in it. We can do this by modifying a geometrixx component like so:
1) Go to /crx/de/index.jsp#/apps/geometrixx-gov/components/thankyoumessage/thankyoumessage.jsp
2) Add the following to the end of the file
<cq:include path="anotherparsys" resourceType="foundation/components/parsys"/>
3) Click save all

Now we'll enable the component in design mode
1) Go to /editor.html/content/geometrixx-gov/en/thankyou.html
2) Switch to design mode from the dropdown in the upper right next to "Edit"
3) Click on the lowest box marked "Drag components here"
4) Click the "Parent" option in the toolbar that appears
5) Click the wrench in the toolbar that appears
6) Scroll down to Geometrixx Gov and expand it
7) Select the check box next to Thank You Message inside the group
8) Click OK

Next we'll nest a few of these new components
1) Switch back to edit mode from the dropdown in the upper right next to "Design"
2) Switch to the components list in the side panel
3) Change the side panel dropdown to "Geometrixx Gov"
4) Drag the Thank You Message component into the top "Drag components here box" immediately below the line that says "Please specify your application tracking number."
5) Repeat step 4 twice, using the highest "Drag components here box" each time.

Open dev tools and refresh the page. Note the 404s in the request log such as
/etc/designs/geometrixx-gov/jcr:content/contentpage/par/thankyoumessage/anotherparsys.2.json

Proposed Fix
Retrieve the design once at the template level in the same way that AEM's native code does with /etc/designs/express/_jcr_content.0.json
OR
Provide a way to disable this feature.

Other Benefits to fixing:
Reduce the number of requests made.
Eliminate 404s for parsys prior to a design being selected.

**Comment by mickleroy** [comment]
Yes! I just stumbled upon this today whilst working on a new project. My console log is full of 404s 😞

**Comment by justinedelson** [comment]
if you are trying to disable the parsys placeholder feature, you can do so using the configuration options added with #944.

**Comment by modeckimellett** [comment]
@justinedelson At first glance, #944 appears to only be for disabling it in the Classic UI. Can you confirm that the change affects the Touch UI where this bug is present? If not, please reopen this defect.

If this does in fact fix my issue, can you confirm that the appropriate action is to set the `exclude.all` property to `true` on the `com.adobe.acs.commons.wcm.impl.DynamicClassicUiClientLibraryServlet` configuration?

**Comment by justinedelson** [comment]
apologies, I missed that you were talking about the Touch UI. We do not have anything similar for the TouchUI at this time. We would welcome a pull request for this.

**Comment by modeckimellett** [comment]
No worries! Unfortunately I don't have time to build a robust fix for this right now. I've commented out the ajax call at Line 130 on our deployments until this can be addressed.

**Comment by slalomoliver** [comment]
Hello @modeckimellett @justinedelson ! 
I'm also working on an AEM site that has custom nested parsys and I realized that the number of requests (depending on how deeply nested the parsys is) easily bombard and crossed the default "Number of Calls per Request" in the Main Servlet. While I like the concept of parsys-specific design, I still would like to have the option to turn this off at the site or page level (and be able to specify the default). Thanks!

**Comment by yerriswamyreddy1111** [comment]
Hi @justinedelson ,
Could you please let us know when this issue is going to be fixed for Touch UI?

Please update this thread once the issue is fixed for the Touch UI.

Thanks in advance.

--
Regards,
Yerriswamy

**Comment by modeckimellett** [comment]
Can we leave this open? I know that we don't have resources to address this right now, but it is definitely still an issue.

**Comment by davidjgonzalez** [comment]
@modeckimellet yup! Your comment (aka activity) is enough to reset staleness!
