### ISSUE TITLE
Automatic Package Replicator/ResourceServiceManager has private references

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-commons#997]
There's two warnings in the logs with a master build:

    [WARNING] Bundle com.adobe.acs:acs-aem-commons-bundle:bundle:3.8.5-SNAPSHOT : Export com.adobe.acs.commons.replication.packages.automatic,  has 1,  private references [com.adobe.acs.commons.util.impl],
    [WARNING] Bundle com.adobe.acs:acs-aem-commons-bundle:bundle:3.8.5-SNAPSHOT : Export com.adobe.acs.commons.util,  has 1,  private references [com.adobe.acs.commons.util.impl],

This was introduced with #920 / #987 .  If `com.adobe.acs.commons.replication.packages.automatic.AutomaticPackageReplicatorMBean` and/or `com.adobe.acs.commons.util.ResourceServiceManager` need to be exported, then `ResourceServiceManagerMBean` needs to be moved to an exported package. Alternatively, the two classes can be moved into non-exported packages.

**Comment by davidjgonzalez** [comment]
Fixed via #999
